### ISSUE TITLE
Unable to connect to Gateway because of new Authorize.net SSL cert

### ISSUE THREAD

**Issue by granthleslie** [spree/spree#10033]
There was a change in Authorize's certificate and that's fine, but when I visit https://secure2.authorize.net/gateway/transact.dll, I get this error: (91) Version 2.5 is no longer supported. 
Is anyone else getting this issue and are you able to fix with the Gateway::AuthorizeNetCim payment gateway?

**Comment by damianlegawiec** [comment]
This is Spree Gateway related so closing it here...
