### ISSUE TITLE
Mega-menu Categories not updating after updating spree_storefront.yml

### ISSUE THREAD

**Issue by wairaguedd** [spree/spree#10042]
## Context
I tried customizing the mega-menu categories on the storefront by editing the spree_storefront.yml file but it still doesn't update on the homepage

## Expected Behavior
It should update the mega-menu categories on the front-end

## Actual Behavior
The categories stay the same

## Possible Fix
Make it that an update of the spree_storefront.yml file will automatically update the mega-menu categories

## Your Environment

* Working on amazon cloud9 with Rails 6 and the newest version of spree:

**Comment by damianlegawiec** [comment]
Hey @wairaguedd have you restarted your web server? Those  changes are picked up after restart

**Comment by wairaguedd** [comment]
Thanks @damianlegawiec for the prompt response. I restarted the server and the changes got picked up.
