### ISSUE TITLE
Invalid Spree Demo Credentials

### ISSUE THREAD

**Issue by itsgauravjain22** [spree/spree#10040]
Spree Demo admin credentials are invalid.

## Context
Demo Url: [https://demo.spreecommerce.org/](https://demo.spreecommerce.org/)
login: spree@example.com
password: spree123

## Expected Behavior
The user should navigate admin dashboard

## Actual Behavior
User is not authenticated using  above credentials.

## Possible Fix
Reset the demo credentials with above provided credentials

## Steps to Reproduce

1. Navigate to [https://demo.spreecommerce.org/login](https://demo.spreecommerce.org/login)
2. Enter Email: spree@example.com and Password: spree123
3. Notice the "Invalid email or password."message.

**Comment by damianlegawiec** [comment]
@itsgauravjain22 those credentials are for Heroku button demo

**Comment by itsgauravjain22** [comment]
Could you share [https://demo.spreecommerce.org/login](https://demo.spreecommerce.org/login) admin credentials. Heroku require credit card info for getting started.
