### ISSUE TITLE
Sort By in Taxonomy show raises an exception

### ISSUE THREAD

**Issue by qoobaa** [spree/spree#10060]
Sort by function is broken on taxonomy show pages.

https://demo.spreecommerce.org/t/sportswear?sort_by=newest-first

## Expected Behavior
Ordering products just like on products#index.

## Actual Behavior
`PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list`

**Comment by damianlegawiec** [comment]
Hey @qoobaa this commit - https://github.com/spree/spree/commit/be3bf5b746c000f6447624b0b43db34a73878f9f - should fix the problem

**Comment by qoobaa** [comment]
Thank you!

Is it going to be included in the next release?

**Comment by damianlegawiec** [comment]
Yup, we'll release 4.1.3 shortly

**Comment by damianlegawiec** [comment]
4.1.3 released 🎉
