### ISSUE TITLE
spree_analytics_trackers help identify brands

### ISSUE THREAD

**Issue by NetViz** [spree/spree#10061]
spree_analytics_trackers - Works so well sending data to Google Analytics with enhanced e-commerce data like product details, category details and transaction-related information,

it would be super cool if we could also able to send brand that particular product is related to.

![image](https://user-images.githubusercontent.com/60209134/78062109-d1855700-73ab-11ea-8a07-710b5fade4cf.png)

**Comment by damianlegawiec** [comment]
@NetViz please post this issue in https://github.com/spree-contrib/spree_analytics_trackers
