### ISSUE TITLE
Spree::Zone calling super on kind method

### ISSUE THREAD

**Issue by barhum** [spree/spree#10062]
Server error when adding and removing items to cart.  Happens sporadically.

## Context
I was getting a server error in production, saying that the super method being called from Spree::Zone does not exist when adding/deleting items to cart.  

## Expected Behavior
Adding and deleting items to cart should work.

## Actual Behavior
`NoMethodError (super: no superclass method `kind' for #<Spree::Zone:0x00007fd7c553f468>):`

## Possible Fix
Line 64 on Core > Model > Zone calling super should be checked.  I removed the super call and the cart seems to be working now. 

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:

```
ruby '2.6.5'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'pg'
gem 'puma', '~> 4.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'

gem 'spree', '~> 4.1'
gem 'spree_auth_devise', '~> 4.1'
gem 'spree_gateway', '~> 3.7'
gem 'dotenv-rails'
gem 'faraday'
gem 'pry'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize'

gem "aws-sdk-s3", require: false



gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/commit/7e860b52994925854bc416d2d5bab8c439a1f4fd
