### ISSUE TITLE
Order success URL must be different from My Account-Orders URL

### ISSUE THREAD

**Issue by NetViz** [spree/spree#10072]
Most of the conversion tracking(Google and Facebook) codes identify successfully placed an order by taking words from the successful orders page URL. 

Example: www.example.com/order-successful-R7854555587

and they show that in a diff URL structure when a user go back to check the status of the order in the account page

Example: www.example.com/orders/R7854555587

But, in our new Spree frontend, both the structures are exactly the same, this led to sending wrong information to marketing application, its actually double counts the conversion rates every time user goes to check the placed order status of his/her.

Shall we differentiate the order successful page with a different URL structure?

**Comment by damianlegawiec** [comment]
This haven't changed in the new UI, it's the same as in previous Spree versions. To distinguish that order was placed successfully you can use this helper: 

https://github.com/spree/spree/blob/f84ccd012729046391e915e994799a4c2866d278/frontend/app/views/spree/orders/show.html.erb#L2

**Comment by NetViz** [comment]
but third party application may have difficulties picking this one up from there, isn't URL differentiator comes out in best practices?

**Comment by deepakhb2** [comment]
@damianlegawiec Can I start working on this issue? It is a good first issue for me.

**Comment by damianlegawiec** [comment]
> @damianlegawiec Can I start working on this issue? It is a good first issue for me.

Of course! Go ahead 🙂
