### ISSUE TITLE
Hi.. We need to one help.. How to add product attribute in spree 4.1?? 10:51 Please tell me if any i have used ruby 2.6 and rails 6.

### ISSUE THREAD

**Issue by avadhesh82** [spree/spree#10087]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by avadhesh82** [comment]
We need to one help.. How to add product attribute in spree 4.1??
10:51
Please tell me if any i have used ruby 2.6 and rails 6.

**Comment by damianlegawiec** [comment]
https://guides.spreecommerce.org/user/products/creating_products.html#product-properties
