### ISSUE TITLE
Can't start Thin server when using Windows, Spree 4.1.x and Ruby 2.6.0

### ISSUE THREAD

**Issue by jotamartos** [spree/spree#10081]
## Context
Hi, I'm trying to deploy Spree in Windows using Ruby 2.6.x and Rails 6.0.2.2. The Thin server doesn't start.

## Expected Behavior
Thin server running properly

## Actual Behavior
Thin returns an error when starting the server. The error is reported here:

https://github.com/macournoyer/thin/issues/362

## Steps to Reproduce
Use this:

OS: Windows Server 2016
Ruby Version: 2.6.5
Rails version: 6.0.2.2
Rack version: 2.1.2

and try to start a Thin server 

```
"RUBY_PATH\ruby.exe" "SPREE_INSTALLATION_DIRECTORY\bin\thin" start -p 3001 -e production -c "SPREE_INSTALLATION_DIRECTORY" -a 127.0.0.1
```

## Your Environment
As I mentioned

OS: Windows Server 2016
Ruby Version: 2.6.5
Rails version: 6.0.2.2
Rack version: 2.1.2

## Question

Is Spree fully supported on Windows? Did you try to start the server with the configuration mentioned above? 

Thanks

**Comment by damianlegawiec** [comment]
Please follow https://guides.spreecommerce.org/developer/tutorials/getting_started_tutorial.html and use Docker
