### ISSUE TITLE
Store does not receive e-mail when a new order is made

### ISSUE THREAD

**Issue by DianaKoenraadt** [spree/spree#10098]
When a new order is made, the customer does receive an e-mail but the store does not.

## Context

- Register as new user
- Place an order

## Expected Behavior

Both the customer and the store receive an e-mail

## Actual Behavior

Only the customer receives an e-mail. The store does not get an e-mail.

## Steps to Reproduce

1. Register as new user with unique e-mail address (not same as store email)
2. Place an order
3. Check user inbox: E-mail of order confirmation is there
4. Check store inbox: No e-mail

## Your Environment

* Version used:  

gem 'spree', '~> 4.1'
gem 'spree_auth_devise', '~> 4.1'
gem 'spree_gateway', '~> 3.7'
gem 'spree_mollie_gateway', '~> 4.0'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize'

* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/DianaKoenraadt/5ab9532ad68c4faa3dd01d4cf39d9d04
* Any relevant stack traces ("Full trace" preferred): n/a

**Comment by damianlegawiec** [comment]
That's correct. There's no feature currently for that
