### ISSUE TITLE
add record type to billing_address, shipping_address in Cart Serializer 

### ISSUE THREAD

**Issue by cuon-kakimoto** [spree/spree#10117]
**Is your feature request related to a problem? Please describe.**
I'm using json api serializer in frontend.
https://github.com/SeyZ/jsonapi-serializer

this can deserialize for fastjson-api response including has_many relatitonships.
https://github.com/SeyZ/jsonapi-serializer/blob/master/test/deserializer.js#L228-L232

But, some spree api response can't deserialize

example:
```
module Spree
  module V2
    module Storefront
      class CartSerializer < BaseSerializer
        ...
        # this is can serialize by jsonapi-serializer
        belongs_to :user

        # this is can not serlizaised by jsonapi-serializer
        belongs_to :billing_address,
          id_method_name: :bill_address_id,
          serializer: :address
```

A response for relationships billing address data type is 'billing_address'.
And, a response for included data type is 'address'
this mismatch caused cannnot deserialized.

<img width="529" alt="スクリーンショット 2020-04-28 5 55 53" src="https://user-images.githubusercontent.com/24713957/80421182-089d4880-8917-11ea-9ccc-41b8322538e1.png">

**Describe the solution you'd like**
I would like to add `record_type` for deserialize.
https://github.com/Netflix/fast_jsonapi#customizable-options

```
module Spree
  module V2
    module Storefront
      class CartSerializer < BaseSerializer
        belongs_to :billing_address,
          id_method_name: :bill_address_id,
          serializer: :address,
          record_type: :address
```

A response for relationships billing address data type is 'address'.
And can serialize.

**Comment by damianlegawiec** [comment]
Hey @cuon-kakimoto go ahead and propose this change via pull request 👍
