### ISSUE TITLE
How to configure active storage to work with Amazon S3

### ISSUE THREAD

**Issue by healthybro** [spree/spree#10111]
Hello I am very new to spree and Ruby in general. I come from a Scala and Play framework background. I've been able to deploy spree to Heroku but due to heroku's ephemeral file system, uploaded images get deleted after some time.

I've read this [article](https://guides.spreecommerce.org/developer/customization/images.html) about how to configure ActiveStorage for AWS. As earlier mentioned I'm new to ruby so I don't know where exactly in the spree code I have to apply those setting.
Any guide on how to achieve this will be highly appreciated.

**Comment by damianlegawiec** [comment]
https://edgeguides.rubyonrails.org/active_storage_overview.html#amazon-s3-service
