### ISSUE TITLE
SpreeSimpleSales VariantDecorator undefined method `orig_price_in'

### ISSUE THREAD

**Issue by kirykr** [spree/spree#10138]
I tried to create extension by following the [spree tutorials guide](https://guides.spreecommerce.org/developer/tutorials/extensions_tutorial.html). Everything works except the VariantDecorator test.

## Context

I think this block of code never run:
```ruby
def self.included base
       base.class_eval do
          alias_method :orig_price_in, :price_in
      end
 end
```

So i modified the code by updating the method to `def self.prepended base`
```ruby
def self.prepended base
       base.class_eval do
          alias_method :orig_price_in, :price_in
      end
 end
```
## Expected Behavior

After updating the method, the class alias methods is invoked which is correct.
## Actual Behavior

But it leads to another problem. Stack level too deep.
## Possible Fix

Is there any way to solve this problem? if we can override parent method without calling it infinitely that would fixed the issue. Or should we use the old direct `Spree::Variant.class_eval ` method override? This would fix this issue.
```ruby
Spree::Variant.class_eval do
  alias_method :orig_price_in, :price_in
  def price_in(currency)
    return orig_price_in(currency) if sale_price.blank?

    Spree::Price.new(variant_id: id, amount: sale_price, currency: currency)
  end
end
```
## Steps to Reproduce

1. follow this [spree tutorials guide](https://guides.spreecommerce.org/developer/tutorials/extensions_tutorial.html).
2. run the test
3. undefined method `orig_price_in' will raise
## Your Environment

* Version used: 4.1.5
* Gemfile and Gemfile.lock as text in a Gist: 
```ruby
gem 'spree',              '~> 4.1'
gem 'spree_auth_devise',  '~> 4.1'
gem 'spree_gateway',      '~> 3.7'
gem 'spree_simple_sales', path: '../spree_simple_sales'
```
* Any relevant stack traces ("Full trace" preferred):

**Comment by emystein** [comment]
I had the same issue, and after playing around a little with monkey patching, the following code worked for me:

```ruby
module SpreeSimpleSales
    module Spree
      module VariantDecorator
        def price_in(currency)
          return super unless sale_price.present?
          ::Spree::Price.new(variant_id: self.id, amount: self.sale_price, currency: currency)
        end
      end
    end
  end
  
Spree::Variant.prepend SpreeSimpleSales::Spree::VariantDecorator
```
I can't explain why the original example in the [extensions tutorial](https://guides.spreecommerce.org/developer/tutorials/extensions_tutorial.html#decorating-variants) is not working though.

My environment:

* Spree version: 4.2.0.alpha
* Ruby version: 2.6.1

**Comment by kirykr** [comment]
```ruby
module SpreeSimpleSales
  module Spree
    module VariantDecorator
      def self.included base
        base.class_eval do
          alias_method :orig_price_in, :price_in
        end
      end

      def price_in(currency)
        return orig_price_in(currency) unless sale_price.present?
        ::Spree::Price.new(variant_id: self.id, amount: self.sale_price, currency: currency)
      end
    end
  end
end
Spree::Variant.prepend SpreeSimpleSales::Spree::VariantDecorator
```
The example is not working because this block never be called
```ruby
def self.included base
        base.class_eval do
          alias_method :orig_price_in, :price_in
        end
 end
```
unless  we use `self.prepended` method. Now this block get called.
```ruby
def self.prepended base
        base.class_eval do
          alias_method :orig_price_in, :price_in
        end
 end
```
So if we want to override the class method by calling the `Spree::Variant.prepend` we must use `self.prepended` otherwise the parent class methods can not be overriden.
