### ISSUE TITLE
Allow to filter products within multiple taxons

### ISSUE THREAD

**Issue by oklas** [spree/spree#10132]
**Is your feature request related to a problem? Please describe.**
Filter products within multiple taxons

**Describe the solution you'd like**
add taxons to whitelist of ransackable relations
https://github.com/spree/spree/blob/v4.1.5/core/app/models/spree/product.rb#L114

**Describe alternatives you've considered**
I do not found alternatives, please let me know them

**Additional context**
Additionally I have a question why there is no taxons in whitelisted relations and what is the possible problems to have it?

Thanks

**Comment by damianlegawiec** [comment]
@oklas good catch, this is probably some oversight on our end. Would you be able to create a PR with this change? Thanks you!

**Comment by oklas** [comment]
If someone looking for a way to enable that in prior versions, check [this](https://stackoverflow.com/a/61549347/2969544):
