### ISSUE TITLE
Invalid self-closed HTML tags

### ISSUE THREAD

**Issue by tkDarch** [spree/spree#10166]
## Context
I was trying to restructure the `products#show` view, and the structural Bootstrap utility classes didn't work as expected. I then realised, quite a few places the HTML nesting seems to be broken by unsupported use of self-closed div tags. Not sure if it's a conscious decision based on something related to the use of the _Deface_ gem, but if it's not, I thought it would be worth mentioning.

## Possible Fix
Avoid using self-closed `<div />` tags.
https://en.wikipedia.org/wiki/Category:Pages_using_invalid_self-closed_HTML_tags

## Steps to Reproduce
1. Go to the `products#show` view.
2. Inspect the html and see how the outer div tags are nested.

## With invalid self-closed tags
<img width="836" alt="image" src="https://user-images.githubusercontent.com/33635699/82047082-78028e80-96b2-11ea-9a1a-cf17c5aca871.png">

## With valid closed div's
<img width="618" alt="image" src="https://user-images.githubusercontent.com/33635699/82047225-bb5cfd00-96b2-11ea-9674-b3240e879ade.png">

**Comment by damianlegawiec** [comment]
Hey @tkDarch could you make a PR wit a fix for this issue?

**Comment by tkDarch** [comment]
Sure. You're welcome, Damian.

**Comment by tkDarch** [comment]
Looks like it's already been fixed.
