### ISSUE TITLE
Product images for "all" variants are not returned in cart request in api v2

### ISSUE THREAD

**Issue by flobby** [spree/spree#10176]
If you want to use the cart request to display a cart with product images, you need all images related to the variant the user has in her/his cart.

## Context
Currently we are only able to display product variant images in the cart. This means unnecessary data storage or no images at all.

## Expected Behavior
If an image is saved for "all" variants I want it to be returned in the images array for every variant.

## Actual Behavior
Only images that are tagged for a specific variant are returned.

## Possible Fix
I did not look into the code yet but probably it's just a simple "OR" / relation that is missing :)

## Steps to Reproduce
1. Add a new Product with
-  at least one variant and
-  with an image that is tagged for "all" variants and
-  with an image that is tagged for the variant

![image](https://user-images.githubusercontent.com/159259/82534642-c053fd80-9b45-11ea-8988-dc65280d704c.png)

2. Add the product to your cart via API v2
`/api/v2/storefront/cart/add_item.json?include=line_items,variants,variants.images`

3. The result does not return the product image for "all" variants but only the one for the specific variant

This is also true for all other cart requests

## Your Environment
* Version used: spree master at commit `b0f2e86591ee9ae071807bffb9d1243b4eaa8700`

**Comment by imgarylai** [comment]
@flobby Would you mind taking a look at an issue I created in the [spree_mailchimp_ecommerce](https://github.com/spree-contrib/spree_mailchimp_ecommerce)  I created an issue on https://github.com/spree-contrib/spree_mailchimp_ecommerce/issues/103. 

Is this the reason to cause the issue?

**Comment by flobby** [comment]
My current workaround is to add the default image to the variant and fallback in frontend.

```
module StorefrontShop
  module Spree
    module VariantSerializerDecorator
      def self.prepended(base)
        base.has_one :default_image,
          object_method_name: :default_image_for_product,
          id_method_name: :product_id,
          record_type: :image,
          serializer: :image

      end
    end
  end
end

Spree::V2::Storefront::VariantSerializer.prepend StorefrontShop::Spree::VariantSerializerDecorator if Spree::V2::Storefront::VariantSerializer.included_modules.exclude?(StorefrontShop::Spree::VariantSerializerDecorator)
```

**Comment by JTimings** [comment]
@damianlegawiec don't understand the fix for this? Variant images are not being included in the cart response when images are set to "All" Variants in admin. [#10231](https://github.com/spree/spree/pull/10231) didn't seem to help.

**Comment by damianlegawiec** [comment]
@JTimings in the API you can fetch images via `primary_variant` - https://github.com/spree/spree/commit/1f33360591d75df38085e43356103376da5ba331

**Comment by JTimings** [comment]
how about via the cart_serializer when using 1 image for ALL variants?

**Comment by JTimings** [comment]
> @damianlegawiec how about via the cart_serializer when using 1 image for ALL variants?

@damianlegawiec any thoughts on this?
