### ISSUE TITLE
ActionView::Template::Error (wrong number of arguments (given 0, expected 1))

### ISSUE THREAD

**Issue by mashhood-ahmad** [spree/spree#10171]
Whenever tyring to fetch taxonomies, this following file is hit but ends with an error.

https://github.com/spree/spree/blob/8142c4348baf77043b01005c0646ec5912d49520/api/app/views/spree/api/v1/taxons/jstree.rabl#L1

![image](https://user-images.githubusercontent.com/8642730/82380489-f60fbe00-9a41-11ea-9223-4fb245768f07.png)

**Setup Details:**
Rails 5.2.4.3
Spree 3.6.6

**Gemfile:**
gem 'spree', '~> 3.6.6'
gem 'spree_auth_devise', '~> 3.5'
gem 'spree_gateway', '~> 3.4'

gem 'acts-as-taggable-on', '~> 6.0'

gem 'spree_multi_vendor', github: 'spree-contrib/spree_multi_vendor'
gem 'spree_analytics_trackers', '~> 1.1'
gem 'spree_account_recurring', github: 'vinsol-spree-contrib/spree-account-recurring',  branch: 'master'

gem 'sprockets-helpers', '~> 1.2.1'
gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: '3-6-bump'

Am I getting into conflicts due to incompatibility between different versions.
I've chosen Spree 3.6.6 because I have to use a theme given by vinsol_spree_themes extension which works with < spree 3.7

Any help would be much appreciated.

**Comment by mashhood-ahmad** [comment]
Also facing another taxonomy related issue which I think has the same cause.

app/views/spree/shared/_taxonomies.html.erb:4:in
```
    1: <% max_level = Spree::Config[:max_level_in_taxons_menu] || 1 %>
    2: 
    3: <nav id="taxonomies" class="sidebar-item" data-hook>
    4:   <% @taxonomies.each do |taxonomy| %>
    5:     <% cache [I18n.locale, taxonomy, max_level, @taxon] do %>
    6:       <% if taxonomy.root.children.any? %>
```

What could be causing this issue?

**Comment by damianlegawiec** [comment]
Sorry, Spree 3.6 is not supported anymore, [please upgrade to a supported version](https://guides.spreecommerce.org/developer/upgrades/).
