### ISSUE TITLE
API v2 returns server error HTML page when payment fails

### ISSUE THREAD

**Issue by johannboutet** [spree/spree#10192]
## Context
During the checkout process, if the payment fails because the charge is rejected by the gateway, the API responds with a 500 status code and an HTML error page. This happens with Stripe gateways (tested with `StripeGateway` and `StripeElementsGateway`), I don't have accounts with other gateways to test them.

## Expected Behavior
The API should answer with a 422 status code and a JSON body explaining the error like specified in the docs.

## Actual Behavior
The API answers with a 500 status code and an HTML error page.

## Possible Fix
The base controller for API v1 `Spree::Api::BaseController` has a line to `rescue_from Spree::Core::GatewayError, with: :gateway_error`. The API v2 base controller `Spree::Api::V2::BaseController` should probably have a similar logic.

## Steps to Reproduce
1. Create a basic rails app and install spree
2. In the Admin, setup a payment method with `Spree::Gateway::StripeGateway` or `Spree::Gateway::StripeElementsGateway`
3. Through the API v2, create a cart, add some items, and go through the checkout steps until the `payment` step.
4. Try to update the checkout with one of Stripe's [special test tokens](https://stripe.com/docs/testing#cards-responses) that result in a charge failure, like `tok_chargeDeclined` or `tok_chargeDeclinedInsufficientFunds`

## Your Environment
* Version used:
Tested with 2 different setups:
  - Rails 5.2.4.3 and Spree 3.7.10
  - Rails 6.0.3.1 and Spree 4.1.6
* Gemfile, Gemfile.lock and stack trace:
https://gist.github.com/johannboutet/0e4774bfeedcc86bc72402081e95ed1c

**Comment by damianlegawiec** [comment]
Hey @johannboutet could you prepare a PR with a fix you've described? Thank you!

**Comment by johannboutet** [comment]
For sure, I'll try and get it done in the next few days.
