### ISSUE TITLE
"We are unable to calculate shipping rates for the selected items."

### ISSUE THREAD

**Issue by shubham-kaushal** [spree/spree#10270]
## Expected Behavior
There should be an error that tells you what is missing.

## Actual Behavior
It just says "We are unable to calculate shipping rates for the selected items."
I cross-checked everything zones, state, Country, Shipping Category, Shipping Method, Stock (Backoderable also) and everything looks fine still we got the error msg. pf the same.

Also checked #7823 but there is no solution

## Steps to Produce this Error
Add Product To Cart
Go to Checkout
Fill Shipping form
This error will occur at Delivery. We are not moving further 'Address"

## Possible Fix
Update the documentation or put out a new guide to integrating checkout.

## Environment
* Version used: spree 4.1.7

**Comment by shubham-kaushal** [comment]
![image](https://user-images.githubusercontent.com/63925481/84931642-ada2f900-b0f0-11ea-821c-ef79be553563.png)

**Comment by shubham-kaushal** [comment]
![image](https://user-images.githubusercontent.com/63925481/84931703-cca18b00-b0f0-11ea-98cd-f23e8df2b7e2.png)

**Comment by flobby** [comment]
Please provide steps on how to reproduce, otherwise nobody can confirm that.

**Comment by shubham-kaushal** [comment]
Steps: 
Add Product To Cart
Go to Checkout
Fill Shipping form 
This error will occur at Delivery. We are not moving further 'Address"

**Comment by shubham-kaushal** [comment]
@damianlegawiec We are experiencing this again. We tried to dump the old database and create new database and import the Spree Demo data and it worked but after creating a new product or cloning the Spree Demo Product again we are facing this issue. Although Spree Demo Data has no issue. We are trying to debug but not able to get anything yet. 

If you can give your input then it will be a great help. I tried to post this in the forum also but I think you missed it. So, here I am again just sending you a friendly notice on this issue.

**Comment by kainio** [comment]
I have the same problem in spree version 4.1.6

**Comment by kainio** [comment]
@shubham-kaushal  Are you using spree_multi_vendor? because I am suspecting that the problem may come from the products that were created for a specific vendor.

**Comment by shubham-kaushal** [comment]
@kainio Yes, we are using multi-vendor. We have done a lot of debugging but not got any specific solution. I think the issue is related to variants.
@damianlegawiec I hope you will give some input on this as there are many people experiencing this.

**Comment by nicolasconnault** [comment]
Looks like this software has been completely abandoned.. Paypal integration broken in 4.1.6, checkout broken since 3.7.0... no one answers the bug reports...

**Comment by SagarKarwande** [comment]
> @kainio Yes, we are using multi-vendor. We have done a lot of debugging but not got any specific solution. I think the issue is related to variants.
> @damianlegawiec I hope you will give some input on this as there are many people experiencing this.

We also faced the same issue. You need to create a shipping method for each vendor.

**Comment by ctsstc** [comment]
I ended up having to re-enter states/countries and rebind them to the shipping/taxes it seems.

**Comment by lshepstone** [comment]
I can confirm that as of spree `4.2` and spree_multi_vendor `2.1` you need to create shipping methods for each vendor to get this working.

**Comment by zolzaya** [comment]
I also faced the same issue. any solutions?

**Comment by funder7** [comment]
Hello guys, I think that I've found the issue with my setup, maybe it can help somebody else: 
if you have the ext spree_multivendor installed, then a new column is added to the `spree_shipping_methods` table.
This column is the `vendor_id`, which cannot be set from the UI (the input element is missing). With a vendor_id, I was able to move to the next step.
