### ISSUE TITLE
connection.column_exists?(:spree_stores, :new_order_notifications_email) causes db creation failed.

### ISSUE THREAD

**Issue by imgarylai** [spree/spree#10274]
I think we should not use `connection` in the store model. This line may cause migration failure in the following scenario. 

If the database hasn't been created yet, the `connection` will cause `Unable to connect to a database.`. For example, after a clean installation of Spree, and the user runs `rails db:create`. I found this problem in my CI environment. In my CI environment, it always creates a clean new rails database for testing. And because of this line, it doesn't allow me to create a new database. 

https://github.com/spree/spree/blob/b17e5a1993a6b41d8b974f15183d43b627613281/core/app/models/spree/store.rb#L11-L13

Since the migration has been merged to the master, do we still need to check the column existence for the validation? Once a user has upgraded their app to the current latest version, they should run the migration anyway, right? 

In the meanwhile, I'm also thinking of another workaround.

**Comment by damianlegawiec** [comment]
This PR should fix this issue - https://github.com/spree/spree/pull/10275

We still need this clause, we're adding validation to a column that doesn't exist at the time we run migrations

**Comment by imgarylai** [comment]
@damianlegawiec Great! Sorry I didn't notice that. 

I was preparing for another PR. 

Or maybe we can just check the column name existence? 

```
    column_names.include? 'new_order_notifications_email' do
      validates :new_order_notifications_email, email: { allow_blank: true }
    end
```

**Comment by damianlegawiec** [comment]
@imgarylai fixed via https://github.com/spree/spree/pull/10385
