### ISSUE TITLE
Future of multi store and the spree-multi-domain gem

### ISSUE THREAD

**Issue by codebycliff** [spree/spree#10286]
The current documentation [mentions the possibility of integrating](https://guides.spreecommerce.org/user/configuration/configuring_multi_stores.html#future-development) the [spree-multi-domain](https://github.com/spree-contrib/spree-multi-domain) community extension into core by version `4` or `4.1`. Given that we are currently at `4.1`, I was hoping to better understand the plan around this and the future of the [spree-multi-domain](https://github.com/spree-contrib/spree-multi-domain) community extension. 

I'm [failing to receive a reply](https://github.com/spree-contrib/spree-multi-domain/pull/211#issuecomment-628758038) by the current maintainers and would like to know how to better support the [spree-multi-domain](https://github.com/spree-contrib/spree-multi-domain) gem and spree ecosystem as a whole. We are currently using a fork and fixing things as we see them pop-up, but would love to know how to contribute back upstream and ensure other people get to use this functionality going forward. It seems contributing back to [spree-multi-domain](https://github.com/spree-contrib/spree-multi-domain) is likely not the route to go, but I'm not sure the exact path toward migrating this code into core.

Any guidance would be greatly appreciated. Thanks in advance.

**Comment by damianlegawiec** [comment]
Hey @codebycliff 

Our plan is as follows:

* **Spree 4.2** will include additional multi-store fixes but our main focus is better localization, multi-currency, multi-language support. We're merging [spree_multi_currency](https://github.com/spree-contrib/spree_multi_currency)
* **Spree 4.3**, on the other hand, will include Spree Multi Domain code being merged into Core

In the meantime, we will work on fixing Spree Multi Domain for Spree 4.1, to be precise - [this PR](https://github.com/spree-contrib/spree-multi-domain/pull/211) (that's the one you've mentioned). 

If you have a fork with additional fixes please submit it as a PR to spree-multi-domain repo - we will happily merge that code. 

Cheers,
Damian

**Comment by shubham-kaushal** [comment]
Is spree 4.2 with GraphQL releasing anytime soon? We are waiting for this for more than 2 months.

**Comment by poudelprakash** [comment]
@shubham-kaushal Please give https://github.com/TruemarkDev/spree_graphql_base a try until we have official release.

We started this gem with code that was available on core spree and we would be further fixing any graphql issues as we find and hopefully can contribute back to core with some stability in this area.

**Comment by shubham-kaushal** [comment]
> @shubham-kaushal Please give https://github.com/TruemarkDev/spree_graphql_base a try until there is official graphql release.
> 
> We started this gem with code that was available on core spree and we would be further fixing any graphql issues as we find and hopefully can contribute back to core with some stability in this area.

Thanks for sharing! I Will test this.
