### ISSUE TITLE
Prevent duplicates on products with multiple taxons

### ISSUE THREAD

**Issue by jsandeo** [spree/spree#10372]
## Context
Finding products by taxon sorted by position produces duplicates when certain products have multiple taxons in that taxonomy.
This is essentially a regression of bug https://github.com/spree/spree/issues/1917 . As described there:
Suppose a simple taxonomy:
* Animals
  * Dogs
  * Furry

If I add a product "Retriever" to the Dogs and Furry taxons, then I click on the "Animals" taxon in the app frontend (using the default sort option), I will see:
* Animals:
  * Retriever
  * Retriever

## Expected Behavior
No duplicates, i.e.:
* Animals:
  * Retriever

## Actual Behavior
The following Products query is being generated for the show action on the taxons controller:

```SELECT DISTINCT spree_products.*, spree_products_taxons.position FROM "spree_products" INNER JOIN... ORDER BY "spree_products_taxons"."position" ASC LIMIT ? OFFSET ?```

This means that any product having n>1 taxons on the same taxonomy will appear n times in the query result for the parent taxon (unless by chance it had the same position on every one of the n taxons).

## Possible Fix
Since it is not necessary to include the "spree_products_taxons.position" column in the query to be able to ORDER BY it, we can just remove the "select()" line so that it will generate this instead:

```SELECT DISTINCT spree_products.* FROM "spree_products" INNER JOIN... ORDER BY "spree_products_taxons"."position" ASC LIMIT ? OFFSET ?```

, thus avoiding duplicates.

## Steps to Reproduce
This pull request contains both the test and the fix:
https://github.com/spree/spree/pull/10371/files

## Your Environment

* Version used: 4.1.6, but the bug goes all the way to master
* [Gemfile](https://github.com/jsandeo/spree/blob/master/Gemfile) and [Gemfile.lock](https://gist.github.com/jsandeo/8a7236398ab6ebe9016edd4e11803f26)

**Comment by jsandeo** [comment]
Is there anything else I can do to get this reviewed? Thx

**Comment by kejiro** [comment]
This fix will not work. Some databases (in particular PostgreSQL, but there might be others) require the ordered column to be in the output list when using distinct, which is probably why it's done that way. 

I had a similar issue, I fixed it by not sorting on position (I had to add more sorting options anyway and we don't use positions) ;)
