### ISSUE TITLE
ActionView::Template::Error (undefined method `facebook' for #<Spree::Store:0x0000563ef9738780>):

### ISSUE THREAD

**Issue by rawho** [spree/spree#10381]
i got this error while checking the production.log file while deploying using capistrano

**Comment by dmric** [comment]
> i got this error while checking the production.log file while deploying using capistrano

Hi. were you able to get past this template error?

**Comment by hoshinotsuyoshi** [comment]
Hi. Same here.

I use Spree 4.1.8.

Encountered in development mode.

When I reloaded that object(`current_store`),  I was able to get the `facebook` column:


<img width="1387" alt="8" src="https://user-images.githubusercontent.com/1394049/90790323-e35b9c80-e342-11ea-9939-4f5690d52495.png">

The view file  is [this](https://github.com/spree/spree/blob/v4.1.8/frontend/app/views/spree/shared/_footer.html.erb). 

And I guess `spree_nav_cache_key` will cause this problem.

Problem(I guess):

1. In [here](https://github.com/spree/spree/blob/v4.1.8/frontend/app/helpers/spree/navigation_helper.rb#L14) , the object `current_store` which did not have `facebook` yet,  was cached.
2. [This migration](https://github.com/spree/spree/blob/v4.1.8/core/db/migrate/20200102141311_add_social_to_spree_stores.rb) was executed.  
3. [This line](https://github.com/spree/spree/blob/v4.1.8/frontend/app/views/spree/shared/_footer.html.erb#L1) was called.

--------

## Solution(I guess)

If you have only one `Spree::Store`, Executing

```
$ Spree::Store.current.touch
```

may solve it.

**Comment by rawho** [comment]
@dmric Sorry for the late reply. I just removed the facebook section in the code and it worked

**Comment by hoshinotsuyoshi** [comment]
Instead of

> ```
> $ Spree::Store.current.touch
> ```

, `Rails.cache.delete('default_store')` will work.

**Comment by hoshinotsuyoshi** [comment]
Proposed: https://github.com/spree/spree/pull/10459
