### ISSUE TITLE
Redirect to cart path with some flash message show wrong modal

### ISSUE THREAD

**Issue by ronzalo** [spree/spree#10423]
## Context
I've create a custom action that redirect to cart page with a success flash, but page open `no-product-available` modal

## Expected Behavior
Show modal only if applies

## Actual Behavior
Cart page open a modal if there are a flash, no matter if is success or error

## Possible Fix
Fix this view https://github.com/spree/spree/blob/a7f7114d3237ad214aacc9fe96d1676f1c115976/frontend/app/views/spree/orders/edit.html.erb#L100

**Comment by damianlegawiec** [comment]
Hey @ronzalo could you create PR with a fix? I suppose the current condition needs to be changed to a check that actually confirms that's an error flash

**Comment by prayeshshah** [comment]
Hello @damianlegawiec , I would like to work on this issue.

**Comment by damianlegawiec** [comment]
> Hello @damianlegawiec , I would like to work on this issue.

Awesome! We'll wait for your PR then
