### ISSUE TITLE
uninitialized constant Spree::ReturnItem::EligibilityValidator::RMARequired

### ISSUE THREAD

**Issue by brunovelasco** [spree/spree#10456]
## Context

- Spree 4.1.8, Ruby 2.6.5 and Rails 6.0.2.1
- Using classic reloader
- Having a decorator for `Spree::ReturnItem`

For development env, when reloading a code change (through a page refresh), it raises this error `uninitialized constant Spree::ReturnItem::EligibilityValidator::RMARequired` . 

In order to skip the error, I must either restart rails OR to delete the file `app/models/spree/return_item_decorator.rb`

## Expected Behavior

Reloading should be successful

## Actual Behavior

It raises `uninitialized constant Spree::ReturnItem::EligibilityValidator::RMARequired`

## Possible Fix

include/require/load the `spree/return_item/eligibility_validator/r_m_a_required.rb` on top of decorator file

## Steps to Reproduce

1. Have this file created at `app/models/spree/return_item_decorator.rb`

```
module SpreeReturnItemDecorator
  def self.prepended(base)
    base.attr_accessor :custom_items
  end
end

Spree::ReturnItem.prepend SpreeReturnItemDecorator
```

2. modify any `app/models` file
3. refresh localhost:3000
4. it raises error

## Your Environment

* Version used: Spree 4.1.8 and Rails 6.0.2.1

**Comment by kewubenduben** [comment]
Can anyone follow-up on this?

This is broken by simply doing:
```
module SpreeReturnItemDecorator
  def self.prepended(base)
  end
end

Spree::ReturnItem.prepend SpreeReturnItemDecorator
```

**Comment by damianlegawiec** [comment]
@kewubenduben we're working on the fix, thank you for reporting!

**Comment by KacperMekarski** [comment]
@kewubenduben
Did You reproduce the bug? I can't.

I installed it loccally (not using docker).

@brunovelasco:
I'm using ruby version 2.6.3. Which one do You use?
What do You mean by modifying any app/models file?
When You don't modify any file or it's content from that directory, bug does not appear?

**Comment by brunovelasco** [comment]
@KacperMekarski Sorry, I forgot to mention the ruby version: ruby 2.6.5 (updated problem description)
> What do You mean by modifying any app/models file?

This is a problem with the reloader (classic), therefore, if you touch any model/controller file (by simply adding a blank line, for instance), and after reloading the app (refreshing page, for instance), the problem appears.

If no file is changed at all, there is no bug.

**Comment by kewubenduben** [comment]
@KacperMekarski,
You can test with cli.

```
➜ bundle exec rails c
Loading development environment (Rails 6.0.2.1)
[1] pry(main)> module SpreeReturnItemDecorator
[1] pry(main)*   def self.prepended(base)
[1] pry(main)*   end
[1] pry(main)* end
=> :prepended
[2] pry(main)>
[3] pry(main)> Spree::ReturnItem.prepend SpreeReturnItemDecorator
=> Spree::ReturnItem(id: integer, return_authorization_id: integer, inventory_unit_id: integer, exchange_variant_id: integer, created_at: datetime, updated_at: datetime, pre_tax_amount: decimal, included_tax_total: decimal, additional_tax_total: decimal, reception_status: string, acceptance_status: string, customer_return_id: integer, reimbursement_id: integer, acceptance_status_errors: text, preferred_reimbursement_type_id: integer, override_reimbursement_type_id: integer, resellable: boolean, manual_additional_tax_total: boolean)
[4] pry(main)> reload!
Reloading...
NameError: uninitialized constant Spree::ReturnItem::EligibilityValidator::RMARequired
from /home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spree_core-4.1.8/app/models/spree/return_item/eligibility_validator/default.rb:9:in `<class:Default>'
[5] pry(main)>
```

**Comment by kewubenduben** [comment]
Edited previous comment with better info.

**Comment by KacperMekarski** [comment]
> @KacperMekarski,
> You can test with cli.
> 
> ```
> ➜ bundle exec rails c
> Loading development environment (Rails 6.0.2.1)
> [1] pry(main)> module SpreeReturnItemDecoratorator
> [1] pry(main)*   def self.prepended(base)
> [1] pry(main)*   end
> [1] pry(main)* end
> => :prepended
> [2] pry(main)>
> [3] pry(main)> Spree::ReturnItem.prepend SpreeReturnItemDecorator
> => Spree::ReturnItem(id: integer, return_authorization_id: integer, inventory_unit_id: integer, exchange_variant_id: integer, created_at: datetime, updated_at: datetime, pre_tax_amount: decimal, included_tax_total: decimal, additional_tax_total: decimal, reception_status: string, acceptance_status: string, customer_return_id: integer, reimbursement_id: integer, acceptance_status_errors: text, preferred_reimbursement_type_id: integer, override_reimbursement_type_id: integer, resellable: boolean, manual_additional_tax_total: boolean)
> [4] pry(main)> reload!
> Reloading...
> => true
> [5] pry(main)> module SpreeReturnItemDecorator
> [5] pry(main)*   def self.prepended(base)
> [5] pry(main)*   end
> [5] pry(main)* end
> => :prepended
> [6] pry(main)>
> [7] pry(main)> Spree::ReturnItem.prepend SpreeReturnItemDecorator
> NameError: uninitialized constant Spree::ReturnItem::EligibilityValidator::RMARequired
> from /home/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spree_core-4.1.8/app/models/spree/return_item/eligibility_validator/default.rb:9:in `<class:Default>'
> [8] pry(main)>
> ```
> 
> EDIT: _Changed the cli test steps to reproduce_
> 
> So basically, if you have this code on some `app/models/spree/return_item_decorator.rb`, doing a `reload!` will raise that error.

@kewubenduben You named first module SpreeReturnItemDecoratorator, but prepended SpreeReturnItemDecorator. That's probably a typo, right? It should be Spree::ReturnItem.prepend SpreeReturnItemDecoratorator.

I made same steps, but I can't receive any error:
```
Loading development environment (Rails 6.0.2.1)
2.6.5 :001 > module SpreeReturnItemDecoratorator
2.6.5 :002?>   def self.prepended(base)
2.6.5 :003?>     end
2.6.5 :004?>   end
 => :prepended 
2.6.5 :005 > Spree::ReturnItem.prepend SpreeReturnItemDecoratorator
 => Spree::ReturnItem(id: integer, return_authorization_id: integer, inventory_unit_id: integer, exchange_variant_id: integer, created_at: datetime, updated_at: datetime, pre_tax_amount: decimal, included_tax_total: decimal, additional_tax_total: decimal, reception_status: string, acceptance_status: string, customer_return_id: integer, reimbursement_id: integer, acceptance_status_errors: text, preferred_reimbursement_type_id: integer, override_reimbursement_type_id: integer, resellable: boolean) 
2.6.5 :006 > reload!
Reloading...
/Users/eleguest/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.8/app/models/spree/preferences/store.rb:9: warning: already initialized constant DB_EXCEPTIONS
/Users/eleguest/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.8/app/models/spree/preferences/store.rb:9: warning: previous definition of DB_EXCEPTIONS was here
   (0.1ms)  SELECT sqlite_version(*)
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/confirmable"], ["LIMIT", 1]]
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/validatable"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/confirmable"], ["LIMIT", 1]]
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
 => true 
2.6.5 :007 > module SpreeReturnItemDecorator
2.6.5 :008?>   def self.prepended(base)
2.6.5 :009?>     end
2.6.5 :010?>   end
 => :prepended 
2.6.5 :011 > Spree::ReturnItem.prepend SpreeReturnItemDecorator
 => Spree::ReturnItem(id: integer, return_authorization_id: integer, inventory_unit_id: integer, exchange_variant_id: integer, created_at: datetime, updated_at: datetime, pre_tax_amount: decimal, included_tax_total: decimal, additional_tax_total: decimal, reception_status: string, acceptance_status: string, customer_return_id: integer, reimbursement_id: integer, acceptance_status_errors: text, preferred_reimbursement_type_id: integer, override_reimbursement_type_id: integer, resellable: boolean) 
2.6.5 :012 > reload!
Reloading...
/Users/eleguest/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.8/app/models/spree/preferences/store.rb:9: warning: already initialized constant DB_EXCEPTIONS
/Users/eleguest/.rvm/gems/ruby-2.6.5/gems/spree_core-4.1.8/app/models/spree/preferences/store.rb:9: warning: previous definition of DB_EXCEPTIONS was here
   (0.1ms)  SELECT sqlite_version(*)
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/confirmable"], ["LIMIT", 1]]
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/validatable"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/auth_configuration/confirmable"], ["LIMIT", 1]]
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
  CACHE Spree::Preference Load (0.0ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = ? LIMIT ?  [["key", "spree/app_configuration/admin_path"], ["LIMIT", 1]]
 => true
```

Which database do You use?

**Comment by KacperMekarski** [comment]
Variant no. 1 (create SpreeReturnItemDecoratorator module through console, prepend, reload, create some changes to other model e.g. Spree::Address, reload):
```
Loading development environment (Rails 6.0.2.1)
2.6.5 :001 > module SpreeReturnItemDecorator
2.6.5 :002?>   def self.prepended(base)
2.6.5 :003?>     base.attr_accessor :custom_items
2.6.5 :004?>     end
2.6.5 :005?>   end
 => :prepended 
2.6.5 :006 > Spree::ReturnItem.prepend SpreeReturnItemDecorator
 => Spree::ReturnItem(id: integer, return_authorization_id: integer, inventory_unit_id: integer, exchange_variant_id: integer, created_at: datetime, updated_at: datetime, pre_tax_amount: decimal, included_tax_total: decimal, additional_tax_total: decimal, reception_status: string, acceptance_status: string, customer_return_id: integer, reimbursement_id: integer, acceptance_status_errors: text, preferred_reimbursement_type_id: integer, override_reimbursement_type_id: integer, resellable: boolean) 
2.6.5 :007 > reload!
Reloading...
 => true 
2.6.5 :008 > module Spree
2.6.5 :009?>     module AddressDecorator
2.6.5 :010?>         def example_message
2.6.5 :011?>             puts "Example example"
2.6.5 :012?>           end
2.6.5 :013?>       end
2.6.5 :014?>   end
 => :example_message 
2.6.5 :015 > Spree::Address.prepend Spree::AddressDecorator
 => Spree::Address(id: integer, firstname: string, lastname: string, address1: string, address2: string, city: string, zipcode: string, phone: string, state_name: string, alternative_phone: string, company: string, state_id: integer, country_id: integer, created_at: datetime, updated_at: datetime, user_id: integer, deleted_at: datetime) 
2.6.5 :016 > reload!
Reloading...
 => true
```
P.S Reloading code in console only one time at the end doesn't throw any error either.

Variant no. 2
1. Add module:
`app/models/spree/return_item_decorator.rb`
```
module SpreeReturnItemDecorator
  def self.prepended(base)
    base.attr_accessor :custom_items
  end
end

Spree::ReturnItem.prepend SpreeReturnItemDecorator
```
2. Run rails server, open localhost:3000
3. Prepend module in `app/models/spree/address_decorator.rb`
```
module Spree
  module AddressDecorator
    def example_message
      puts "Example"
    end
  end
end

Spree::Address.prepend Spree::AddressDecorator
```
4. Refresh page with disabled cache, no errors

@brunovelasco @kewubenduben do You use some Spree extensions?

**Comment by brunovelasco** [comment]
@KacperMekarski 

```
gem 'spree', '~> 4.1'
gem 'spree_gateway', '~> 3.7'
gem 'spree_product_assembly', git: 'https://github.com/spree-contrib/spree-product-assembly.git', branch: 'master'
gem 'spree_multi_currency', git: 'https://github.com/spree-contrib/spree_multi_currency.git', branch: 'master'
gem 'spree_analytics_trackers', github: 'spree-contrib/spree_analytics_trackers'
gem 'spree_related_products', github: 'spree-contrib/spree_related_products'
```

Did you make sure you are using the classic reloader, and not Zeitwerk Mode?

**Comment by brunovelasco** [comment]
I was able to fix it by copying `core/app/models/spree/return_item/eligibility_validator/r_m_a_required.rb` into my `app/`, however, using the name `rma_required.rb`. 

Looking at the commits (631be8ffb54b1909854dda74d2890368b41cc43f), it was originally `rma_required.rb` but it has been renamed to `r_m_a_required.rb` to match `zeitwerk` mode, and to keep support for `classic` reloader, this commit d51faa22be8e1f429a3cd66ab6b32b20c51b566e requires the relative path (which doesn't work for me). So hard copying this file into the project did the trick.

Hope this helps to reproduce the error, and eventually to fix it.

**Comment by KacperMekarski** [comment]
@brunovelasco You were right, I forgot to turn off Zeitwerk Mode. Thank You for tips, I'm working on the fix!
