### ISSUE TITLE
Images not showing how do i configure nginx.conf and production.rb

### ISSUE THREAD

**Issue by mices** [spree/spree#10458]
I'm using 3.70rc1 with nginx passenger module and in production images just don't show On individual product pages the images appear as numbered empty boxes

**Comment by dlysenko** [comment]
@mices Hi, I have the same problem with spree/ nginx passenger. Have you solve it?
Regards,
Dmitry

**Comment by dlysenko** [comment]
The problem was with ImageMagick and Ubuntu
I reinstalled imagemagick according this instruction: https://gist.github.com/nickferrando/fb0a44d707c8c3efd92dedd0f79d2911
And it works
