### ISSUE TITLE
Question regarding serving images thru cloudfront

### ISSUE THREAD

**Issue by lan-nguyen91** [spree/spree#10466]
**Is your feature request related to a problem? Please describe.**

Hi Spree,
I have successfully setup ActiveStorage with s3, I would like to access product images via CloudFront to leverage CDN Edge network and caching. I couldn't find any good example out there, can you guys please give me some pointer on how to accomplish this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelfouad** [comment]
Take a look at this tutorial. 
https://dev.to/lipanski/serving-activestorage-uploads-through-a-cdn-with-rails-direct-routes-3nc2

**Comment by damianlegawiec** [comment]
Hey @lan-nguyen91 

We're relying on Rails ActiveStorage to serve files. With Rails 6.1 this will be available - https://github.com/rails/rails/pull/34477
