### ISSUE TITLE
I it possible to create API only app including admin panel (exclude customer pages)

### ISSUE THREAD

**Issue by aditya2muley** [spree/spree#10477]
I want to create spree API only app including admin panel, Is it possible?

**Comment by damianlegawiec** [comment]
Yes, please see https://github.com/spree/spree#headless-installation

You need to modify your Gemfile and include only API and admin panel, eg.

```ruby
spree_version = '~> 4.1.9'
gem 'spree_core', spree_version
gem 'spree_api', spree_version
gem 'spree_backend', spree_version
gem 'spree_auth_devise', '~> 4.2.0'
```

**Comment by matthews52180** [comment]
hey did you get an error "`block in <module:Common>': undefined method `layout' for Spree::BaseController:Class (NoMethodError)" when running sudo rails g spree:install --migrate=false --sample=false --seed=false --copy_storefront=false

**Comment by damianlegawiec** [comment]
@matthews52180 what's your `Gemfile` contents?

**Comment by vczb** [comment]
I had a similar problem, it happened because I created my project by passing the parameter --api, I tried again only with rails new my_project and it worked perfectly.
