### ISSUE TITLE
There is no option to select city for customer

### ISSUE THREAD

**Issue by aditya2muley** [spree/spree#10481]
suppose we have store located in city name **Mumbai** and country **India**  what if user of city **Kolkata** and country **India** tries to order something ?

I want to limit other people from India that we are not sale item outside Mumbai location.

**Comment by damianlegawiec** [comment]
Yes, there's no option like that at the moment. You can however limit by states/regions

**Comment by aditya2muley** [comment]
But I want to limit for cities

**Comment by damianlegawiec** [comment]
I think that will require some custom development. It would be great if you could later share and open-source that code - would help the community in the long run :)
