### ISSUE TITLE
EACCESS error on install generators

### ISSUE THREAD

**Issue by R3ll36** [spree/spree#10491]
< ✘ cosmin@Rell  ~/my_store   master  rails g spree:install --user_class=Spree::User
/home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `initialize': Permission denied @ dir_initialize - /home/cosmin/my_store/.vs (Errno::EACCES)
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `new'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `watch'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:210:in `block in watch'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:202:in `each'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:202:in `watch'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:32:in `_configure'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:45:in `block in configure'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `each'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `configure'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:63:in `start'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `start'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-watcher-listen-2.0.1/lib/spring/watcher/listen.rb:27:in `start'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:80:in `start_watcher'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:89:in `preload'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /home/cosmin/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from -e:1:in `<main>'

**Comment by damianlegawiec** [comment]
I think this is rather connected with your local environment. `.vs` directory is created by Visual Studio code, not Spree.
