### ISSUE TITLE
Custom Preferences not working

### ISSUE THREAD

**Issue by elisoncampos** [spree/spree#10497]
## Context
I'm developing an extension and needed to set some custom preferences in Spree::AppConfiguration. but following the steps in Spree guides didn't work

## Expected Behavior

After setting custom preferences, ex:

```ruby
module Spree
  module AppConfigurationDecorator
    def self.prepended(base)
      base.preference :subscribable_id, :integer
    end
  end
end

Spree::AppConfiguration.prepend Spree::AppConfigurationDecorator
```

Or, following the steps in Spree Guides:

```ruby
Spree::AppConfiguration.class_eval do
  preference :subscribable_id, :integer
end
```

I expected being able to access it via `Spree::Config.subscribable_id`

## Actual Behavior:

Instead, when I try to access te preference, this happens:

```
NoMethodError (undefined method `subscribable_id' for #<Spree::AppConfiguration:0x00007ff659d51400>)
```

## Steps to Reproduce

Just create a new extension and try to setup custom preferences.

## Your Environment

- Ruby 2.7.1
- Rails 6.0.3
- Spree 4.1.9

**Comment by kejiro** [comment]
I can confirm this doesn't work. I ran into the same issue, but I am not using an extension so I had to create my own configuration instead.

I suspect that the Spree::Config variable is initialized before Zeitwerk is loading all the files, so when the decorator is prepended, it is not done on the already existing instance.

The prepend on AppConfiguration must be done after spree have been loaded (the namespace have been created), but before the "spree.environment" initializer have been run, this can be done using an initializer in your extension's engine like this:

    initializer 'myext.environment', before: 'spree.environment' do |app|
      require File.join(File.dirname(__FILE__), '/app_configuration_decorator.rb')
    end

It's not the most convenient way to do it, but it should work.

**Comment by damianlegawiec** [comment]
@kejiro thank you for additional information, this will help a lot to fix this issue

**Comment by damianlegawiec** [comment]
So rather than creating a preferences decorator, it's better to create your own preference class:  https://guides.spreecommerce.org/developer/core/preferences.html#site-wide-preferences

**Comment by MateoLa** [comment]
I would like to say about this issue (also related to the issue #9573 opened by me) that thanks to @kejiro comments I ends with a working solution.
(( @damianlegawiec your suggestion is not enough because you could need to decorate spree preferences defined in other gems.))
So the solution is: 
1) Define your decorator file, ex 'models/spree/anothers_engine_decorator.rb':
```
module Spree::AnothersEngineDecorator
  def self.prepended(base)
    base.preference :your_preference, :type, default: def_value
  end
end
```
But prepend the original class in your engine.rb file, like so:
```
    initializer 'your_initializer_name', before: :load_config_initializers do
      Spree::AnothersEngine.prepend(Spree::AnothersEngineDecorator)
    end
```

**Comment by helmiItsavirus** [comment]
@MateoLa where do you put this code?

`    initializer 'your_initializer_name', before: :load_config_initializers do
      Spree::AnothersEngine.prepend(Spree::AnothersEngineDecorator)
    end`

**Comment by MateoLa** [comment]
Into your engine.rb file.

Example:
module "YourGemName"
  class Engine < Rails::Engine
...
  isolate_namespace ...
    engine_name ....

    engine_root = ....

    initializer 'your_initializer_name', before: :load_config_initializers
do
      Spree::AnothersEngine.prepend(Spree::Your-AnothersEngineDecorator)
    end
