### ISSUE TITLE
Whoever finished running compiled static files in production mode? rake assets:precompile

### ISSUE THREAD

**Issue by lankii** [spree/spree#10509]
Whoever finished running compiled static files in production mode, I've pretty much tried to fix the js,scss loading problem that appears later without any hint of an error location, I'm reluctant to give up using it!

setting：
  config.assets.compile =false
 config.assets.precompile += [ Proc.new { |path| File.basename(path) =~ /^[^_].*\.\w+$/ } ]

run:
RAILS_ENV=production rake assets:precompile

more error for load scss  ,you can fix those more files 

but last same error cant find these bug files

anyone had get it?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
Hey @lankii it's really hard to debug and help without any information, error logs, spree version you're using, Gemfile file
