### ISSUE TITLE
ArgumentError: Invalid route name, already in use: 'set_currency'

### ISSUE THREAD

**Issue by dani07** [spree/spree#10501]
Dependency issue:
- spree (4.2.0.beta)
- spree_frontend (4.2.0.beta)
- spree_multi_currency (3.4.0)

There are two routes defined with the same name  'set_currency' using the `:as` option.
spree_frontend-4.2.0.beta/config/routes.rb:39
spree_multi_currency/config/routes:2

`get '/currency/set', to: 'currency#set', defaults: { format: :json }, as: :set_currency`

Stacktrace:
```
ArgumentError: Invalid route name, already in use: 'set_currency' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
/Users/daniel/.rvm/gems/ruby-2.7.1/gems/spree_frontend-4.2.0.beta/config/routes.rb:39:in `block in <main>'

```

**Comment by damianlegawiec** [comment]
@dani07 with Spree 4.2 you don't need multi currency extension - that code was pulled into core :)
