### ISSUE TITLE
Storefront Address API's v2 is not working

### ISSUE THREAD

**Issue by Mayur-Birle** [spree/spree#10502]
When I am hitting the create address of account API V2 from the Postman 'http://localhost:3000/api/v2/storefront/account/addresses' and added the body params address[firstname] = test with POST method and added bearerAuth , it is showing 
{
    "error": "The resource you were looking for could not be found."
}
![rrrr](https://user-images.githubusercontent.com/26954381/93980714-a00aa880-fd9c-11ea-8840-3a8bb66de10c.png)

 and if I have added the inputs on the params tab  address[firstname] = test  it shows:-
Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://localhost:3000/api/v1/storefront/account/addresses.json?address[firstname]=test&address[lastname]=test

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
Spree version  4.1
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
@Mayur-Birle please update to Spree `4.1.10` which includes those endpoints, thanks!
