### ISSUE TITLE
something was wrong with production include all extension

### ISSUE THREAD

**Issue by pangoo-reuse** [spree/spree#10507]
[43481] + Gemfile in context: /var/www/store/releases/4/Gemfile
[43481] Early termination of worker
[43484] + Gemfile in context: /var/www/store/releases/4/Gemfile
[43484] Early termination of worker
[43492] + Gemfile in context: /var/www/store/releases/4/Gemfile
[43492] Early termination of worker
[43504] + Gemfile in context: /var/www/store/releases/4/Gemfile

please ,please !!!!!

**Comment by pangoo-reuse** [comment]
@@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
D, [2020-09-26T12:23:53.014490 #198647] DEBUG -- :   Spree::Preference Load (0.2ms)  SELECT `spree_preferences`.* FROM `spree_preferences` WHERE `spree_preferences`.`key` = 'spree/app_configuration/show_raw_product_description' ORDER BY `spree_preferences`.`id` ASC LIMIT 1
D, [2020-09-26T12:23:53.018689 #198647] DEBUG -- :    (0.2ms)  BEGIN
D, [2020-09-26T12:23:53.018974 #198647] DEBUG -- :   Spree::Preference Exists? (0.2ms)  SELECT 1 AS one FROM `spree_preferences` WHERE `spree_preferences`.`key` = 'spree/app_configuration/show_raw_product_description' AND `spree_preferences`.`id` != 1 LIMIT 1
D, [2020-09-26T12:23:53.019789 #198647] DEBUG -- :    (0.1ms)  COMMIT
D, [2020-09-26T12:23:53.467204 #198647] DEBUG -- :   Spree::Preference Load (0.5ms)  SELECT `spree_preferences`.* FROM `spree_preferences` WHERE `spree_preferences`.`key` = 'spree/app_configuration/auto_capture_on_dispatch' ORDER BY `spree_preferences`.`id` ASC LIMIT 1
D, [2020-09-26T12:23:53.467982 #198647] DEBUG -- :    (0.1ms)  BEGIN
D, [2020-09-26T12:23:53.468239 #198647] DEBUG -- :   Spree::Preference Exists? (0.2ms)  SELECT 1 AS one FROM `spree_preferences` WHERE `spree_preferences`.`key` = 'spree/app_configuration/auto_capture_on_dispatch' AND `spree_preferences`.`id` != 3 LIMIT 1
D, [2020-09-26T12:23:53.469059 #198647] DEBUG -- :    (0.1ms)  COMMIT
D, [2020-09-26T12:23:54.831244 #198655] DEBUG -- :    (0.3ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
D, [2020-09-26T12:23:54.842812 #198655] DEBUG -- :   Spree::Preference Load (0.2ms)  SELECT `spree_preferences`.* FROM `spree_preferences` WHERE `spree_preferences`.`key` = 'spree/app_configuration/show_raw_product_description' ORDER BY `spree_preferences`.`id` ASC LIMIT 1
D, [2020-09-26T12:23:54.847963 #198655] DEBUG -- :    (0.3ms)  BEGIN
D, [2020-09-26T12:23:54.848399 #198655] DEBUG -- :   Spree::Preferenc

**Comment by damianlegawiec** [comment]
Hey @pangoo-reuse  it's really hard to debug and help without any information, error logs, spree version you're using, Gemfile file
