### ISSUE TITLE
Spree 4.1x version split order functionality not working as expected

### ISSUE THREAD

**Issue by NetViz** [spree/spree#10513]
Spree 4.1x version split order functionality not working as expected, it is not working on quantity split and in some cases, it is not working in SKU split as well in some cases.

Video Reference - https://www.youtube.com/watch?v=WCztMWsp-7M

**Comment by damianlegawiec** [comment]
Thanks for reporting this @NetViz

**Comment by NetViz** [comment]
@damianlegawiec  this issue fixed in #10541?? If, yes we can close this.

**Comment by damianlegawiec** [comment]
@NetViz yes, we need to cherry-pick this into 4.1.x patch version :)
