### ISSUE TITLE
Warnings when running migrations

### ISSUE THREAD

**Issue by ctsstc** [spree/spree#10537]
## Context

When you run migrations you'll see the console cluttered with warnings.

## Expected Behavior

There should be no warnings for devise or `DB_EXCEPTIONS` when running migrations.

Might be similar to: #4126

## Actual Behavior

You'll see these warnings come up for `Devise.secret_key` and `DB_EXCEPTIONS` already being initialized.

```
[WARNING] You are not setting Devise.secret_key within your application!
You must set this in config/initializers/devise.rb. Here's an example:
 
Devise.secret_key = "SOMEKEY123"
/home/coder/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/spree_core-4.1.9/app/models/spree/preferences/store.rb:9: warning: already initialized constant DB_EXCEPTIONS
/home/coder/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/spree_core-4.1.9/app/models/spree/preferences/store.rb:9: warning: previous definition of DB_EXCEPTIONS was here
```

## Possible Fix

I wonder if the `DB_EXCEPTIONS` has something to do with Spring preloader?

There's no `config/initializers/devise.rb` that exists.

## Steps to Reproduce

1. Run a migration
2. Watch the console
3. This is a newer install probably `v4.0` but not `4.1`

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
  * https://gist.github.com/ctsstc/b1bb4ff3b4908e0041cb0e4f4f414165
  * https://gist.github.com/ctsstc/91ecdd3e3a235c932b41121430695662
* Any relevant stack traces ("Full trace" preferred):

**Comment by hoshinotsuyoshi** [comment]
https://github.com/spree/spree/pull/10498  will solve this.
v4.2.0.rc2 contains that improvement.
