### ISSUE TITLE
Spree::FrontendHelper.asset_exists?(path) does not work well in Production

### ISSUE THREAD

**Issue by vascosantos** [spree/spree#10550]
The `asset_exists?(path)` function in `spree/frontend/app/helpers/spree/frontend_helper.rb` returns `true` in production even if I give it a path that doesn't exist.

For example, `asset_exists?("doesnt.exist")` returns `false` in development but returns `true` in production.

A possible solution that seems to work can be found here: https://github.com/rails/sprockets-rails/issues/298#issuecomment-168927471

My current setup is:

```
ruby 2.7.1p83
bundler 2.1.4
spree 4.1.11
```

**Comment by damianlegawiec** [comment]
The plan is to get rid off this method completely in 4.3 as navigation menu management will be completely done via Admin Panel UI
