### ISSUE TITLE
Documentation on compare_at_price seems outdated.

### ISSUE THREAD

**Issue by Tashows** [spree/spree#10559]
## Context
While going through the user [documentation](https://guides.spreecommerce.org/user/products/creating_products.html#product-details) I saw a product attribute being mentioned, called "Compare at price". It is supposed to display a discount as a strikethrough. I didn't recall seeing this anywhere in the latest spree (4.1) admin panel, or in previous installations I made for my customers.

I tried searching in the issues or commits, but the only mention of compare_at_price was a recent commit ( #10448 ),  which didn't really help figure out what's going on. Searching through the repository, I only ended up hitting views and methods that don't seem to be reachable or used by current codebase.

Am I missing something? Is this left for backward compatibility? Should this be removed from documentation?

**Comment by damianlegawiec** [comment]
@Tashows this feature is available in Spree 4.2, will update the documentation to reflect it

**Comment by Tashows** [comment]
Ok thanks!
