### ISSUE TITLE
Give Stores Unique Internal Names

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#10565]
**Is your feature request related to a problem? Please describe.**
Parts of Spree, and some extensions such as Static Content or the Analytics Tracker, ask you to pick a store for Payment Method, or Tracker Code, but because the name is displayed on the frontend, I often keep it the same name on each store instance, so there is no way in the admin UI to distinguish what store I am picking, without some trial and error.

For example if you ran the Nike online store and you want international stores, but you don't want Nike AU, Nike EN, Nike US in the page titles, other parts of the frontend, or customer emails, so you set all your stores names to Nike.

Then you go to set up payments and you get this:
<img width="1170" alt="Screenshot 2020-10-29 at 20 45 10" src="https://user-images.githubusercontent.com/1240766/97630533-a76e4300-1a27-11eb-9fd6-f3a1492cd829.png">

**Describe the solution you'd like**
Add a unique internal name field to the Stores and use this in the admin for Store related options, allowing the freedom to use the same store name for the frontend regardless of the region settings, and Stores are then easily identifiable in the admin UI by their unique internal name.

Alternatively you could create method that takes attributes of each store like the language, currency and joins it onto the name as an identifier, so you get a generated internal name like:  Nike EN GBP, or use the Name and code, as the code is unique.

**Comment by damianlegawiec** [comment]
@MatthewKennedy we have the `code` attribute for that, I suppose that both name and code should be used in those dropdowns, what do you think about this solution?

**Comment by MatthewKennedy** [comment]
@damianlegawiec That would work just fine.
