### ISSUE TITLE
Admin: Delete user with associated order 

### ISSUE THREAD

**Issue by rawandsaeed** [spree/spree#10567]
## Context

I can not delete a user with an associated order. 
## Expected Behavior

Delete a user by clicking delete button in User section in Admin.  
## Actual Behavior

When you try to delete a user who has an order associated it gives error "User associated with orders cannot be destroyed"
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):
ruby '2.7.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'spree', '~> 4.1'
gem 'spree_auth_devise', '~> 4.1'
gem 'spree_gateway', '~> 3.7'

**Comment by damianlegawiec** [comment]
This is not a bug, that's the way it should work
