### ISSUE TITLE
[4.2.0.rc1] when user updates their own addresses via `PATCH /addresses/:id` , it will disappear

### ISSUE THREAD

**Issue by hoshinotsuyoshi** [spree/spree#10569]
Hi there,
I found a bug-like behavior.

--------

## Context

When a  user updates their own addresses via `PATCH /addresses/:id` , it will disappear.

## Expected Behavior

The address is updated.

## Actual Behavior

The address disappears.

## Possible Fix

I think that `PATCH /addresses/:id` , `AddressesController#update` has a problem.

After https://github.com/spree/spree/commit/cd03d00867e2db00697193e44d4e5c62444e5b84 , which is introduced by `4.2.0.rc1`, does not exist in `4.2.0.beta` , `Address#clone` does not copy the attribute `user_id` .

As a result, the new address will not have `user_id`.

So, Possible Fix:

```diff
diff --git a/frontend/app/controllers/spree/addresses_controller.rb b/frontend/app/controllers/spree/addresses_controller.rb
index c34c1851b5..1001ed9864 100644
--- a/frontend/app/controllers/spree/addresses_controller.rb
+++ b/frontend/app/controllers/spree/addresses_controller.rb
@@ -37,6 +37,7 @@ module Spree
       else
         new_address = @address.clone
         new_address.attributes = address_params
+        new_address.user_id = @address.user_id
         @address.update_attribute(:deleted_at, Time.current)
         if new_address.save
           flash[:notice] = Spree.t(:successfully_updated, scope: :address_book)
```

## Steps to Reproduce

1. Log in.
2. Complete an order.
3. Start another order. Add a product to cart, and click `checkout`.
4. Click editi-address link.
5. Submit the form. (You don't have to edit anything in the form)
6. You can see that address is blank.

4-6 gif:
![100](https://user-images.githubusercontent.com/1394049/98269441-11ab5880-1fd1-11eb-93c9-cc67fdad5c61.gif)

## Your Environment

* Version used: 4.2.0.rc1
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/hoshinotsuyoshi/95a7b91c42e005a7042595d9983f56f8
* ~Any relevant stack traces ("Full trace" preferred):~

**Comment by hoshinotsuyoshi** [comment]
Created PR. https://github.com/spree/spree/pull/10570 

I would be happy if you could see it. Thank you.

**Comment by MatthewKennedy** [comment]
@hoshinotsuyoshi That missing address bug has been in since spree 4.1 when the address book feature was added.

cd03d00 Did not add the bug, I made an attempt to fix it in that PR, but reverted it back, as it was mentioned that the address is cloned out of the address book and into order somewhere else in Spree, possibly the admin.

**Comment by hoshinotsuyoshi** [comment]
> That missing address bug has been in since spree 4.1 when the address book feature was added.

@MatthewKennedy 

Oh, thanks for telling me about it. I didn't know that.

I haven't tried it in 4.2.0.beta, so I can't tell anything.

Anyway, I'm hoping to figure it out in some way...
