### ISSUE TITLE
ActiveRecord::RecordNotFound in Spree::TaxonsController#show can't find record with friendly id: "new-collection/summer-2019"

### ISSUE THREAD

**Issue by marklegend** [spree/spree#10579]
Hello there, first time using spree commerce, just installed it and testing the UI and I got this wonderful error
## Expected Behavior

I should get an error page right after a fresh install.
## Steps to Reproduce

1. I'm using linux ubuntu 20.04
2.rbenv ruby 2.7.2, rails 6.0.3
3.sqlite 1.4
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by zm801** [comment]
I got the same issue. Did you fix it?

**Comment by s3749653** [comment]
It basically means that you don't have a page with that path. Thats the default path when you create the application, to update it head to config -> spree_storefront.yml and you can edit the file to whatever path you want

**Comment by marklegend** [comment]
Will do

**Comment by fstdesk** [comment]
> It basically means that you don't have a page with that path. Thats the default path when you create the application, to update it head to config -> spree_storefront.yml and you can edit the file to whatever path you want

Hi, Why it does not return 404?
