### ISSUE TITLE
Does Spree Comemrce have a way just do an ADD TO CART BUTTON on a specific page?

### ISSUE THREAD

**Issue by staycreativedesign** [spree/spree#10605]
Is there a method or something just to add an item to the cart??? variant_id , quantity, and thats it.

**Comment by AwakenTheJaken** [comment]
There is a service method that is being used in orders_controller.rb here is a snip:
`Spree::Cart::AddItem.call(order: @order,
                                      variant: @variant,
                                      quantity: 1)`
Where @order = current_order and @variant = Spree::Variant.find(ID). Hope that helps!

**Comment by staycreativedesign** [comment]
you can run this

``` Spree::Cart::AddItem.call(order: current_order, variant: variant, quantity: 1)```
