### ISSUE TITLE
Translate sorting type "words"

### ISSUE THREAD

**Issue by ufukayyildiz** [spree/spree#10619]
i can not find any way to translate words of sorting feature.

Example;
SORT BY
Sorting - Default, Newest First etc.

Thank you.

![image](https://user-images.githubusercontent.com/23309320/102703156-630b6080-427c-11eb-916d-5e553d2d0c2d.png)

**Comment by ufukayyildiz** [comment]
i am not sure this is the tru way but fixed my problem.

`<%= link_to Spree.t('plp.newest_first'), url_for(permitted_params.merge(sort_by: 'newest-first')) %> ` to
`<%= link_to "MY WORD", url_for(permitted_params.merge(sort_by: 'newest-first')) %>`

**Comment by ufukayyildiz** [comment]
there were missing words in my locale file. i added belows.

 plp:
      best_selling: BEST SELLING
      clear_all: CLEAR ALL
      collection: COLLECTION
      color: COLOR
      done: DONE
      default: DEFAULT
      filter_by: FILTER BY
      newest_first: NEWEST FIRST
      no_results: No results
      no_results_found: No results found
      not_found_filters1: We couldn’t find a match for these filters.
      not_found_filters2: Please try another choose.
      not_found_text1: We couldn’t find products for '%{keywords}'.
      not_found_text2: Please try another search.
      price: price
      price_high_to_low: PRICE (HIGH - LOW)
      price_low_to_high: PRICE (LOW - HIGH)
      result: RESULT
      results_for: RESULTS FOR
      size: SIZE
      sort_by: SORT BY
      top_sellers: TOP SELLERS
      type: TYPE

**Comment by przemosk** [comment]
hey @ufukayyildiz for using multi language in your store you can use this gem: https://github.com/spree-contrib/spree_globalize
