### ISSUE TITLE
`parse_peek': No value provided for option '--port' (Thor::MalformattedArgumentError)

### ISSUE THREAD

**Issue by ufukayyildiz** [spree/spree#10612]
hi,

my app was working but sundenly it refused the connection.

`curl http://0.0.0.0:3000`  works

and when i run 

`rails server -p`

i get

`Traceback (most recent call last):
        30: from bin/rails:3:in `<main>'
        29: from bin/rails:3:in `load'
        28: from /home/ubuntu/she/bin/spring:15:in `<top (required)>'
        27: from /home/ubuntu/she/bin/spring:15:in `require'
        26: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        25: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        24: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        23: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        22: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        21: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        20: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        19: from /home/ubuntu/she/bin/rails:9:in `<top (required)>'
        18: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
        17: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        16: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        15: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        14: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        13: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        12: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        11: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        10: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
         9: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
         8: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
         7: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor.rb:383:in `dispatch'
         6: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor.rb:383:in `new'
         5: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:127:in `initialize'
         4: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/shell.rb:45:in `initialize'
         3: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/invocation.rb:25:in `initialize'
         2: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/base.rb:70:in `initialize'
         1: from /home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/parser/options.rb:100:in `parse'
/home/ubuntu/.rvm/gems/ruby-2.7.1/gems/thor-0.20.3/lib/thor/parser/options.rb:218:in `parse_peek': No value provided for option '--port' (Thor::MalformattedArgumentError)

Any idea please.

`thanks

**Comment by damianlegawiec** [comment]
Updating to Spree 4.2 will help. You're using an old Thor version which can have issues on Ruby 2.7
