### ISSUE TITLE
Product is not available after created

### ISSUE THREAD

**Issue by zolzaya** [spree/spree#10635]
I'm using 4.2.rc2. When I create a product it's not available. I select available on admin UI. But it's not working. But when I go to `console` and set `available_on = Time.now`. Then it's working.

Here is the some logs:
`Spree::Product Create (100.5ms)  INSERT INTO "spree_products" ("name", "slug", "shipping_category_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "fsdkfsjadfk"], ["slug", "fsdkfsjadfk"], ["shipping_category_id", 1], ["created_at", "2020-12-30 03:40:37.583509"], ["updated_at", "2020-12-30 03:40:37.583509"]]                                                 Spree::Variant Load (1.5ms)  SELECT "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."product_id" = $1 AND ("spree_variants"."position" IS NOT NULL) ORDER BY "spree_variants"."position" DESC LIMIT $2  [["product_id", 118], ["LIMIT", 1]]                                                                 Spree::Variant Create (283.0ms)  INSERT INTO "spree_variants" ("is_master", "product_id", "position", "cost_currency", "updated_at", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["is_master", true], ["product_id", 118], ["position", 1], ["cost_currency", "USD"], ["updated_at", "2020-12-30 03:40:37.690099"], ["created_at", "2020-12-30 03:40:37.690099"]]                       Spree::Price Create (54.7ms)  INSERT INTO "spree_prices" ("variant_id", "amount", "currency", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["variant_id", 234], ["amount", "34000.0"], ["currency", "USD"], ["created_at", "2020-12-30 03:40:37.984856"], ["updated_at", "2020-12-30 03:40:37.984856"]]`

It looks `available_on` is not passing to server.

Here is the my Gemfile
```
25 gem 'spree', '4.2.0.rc2'
26 gem 'spree_auth_devise', '4.2.0'                                            
27 gem 'spree_gateway', '3.9.2'
28 # Spree add-ons
29 gem 'spree_static_content', github: 'spree-contrib/spree_static_content'
30 gem 'spree_analytics_trackers', '~> 2.0'
31 gem 'spree_social', github: 'spree-contrib/spree_social'
32 gem 'spree_sitemap', github: 'spree-contrib/spree_sitemap'
33 gem 'spree_multi_vendor', github: 'spree-contrib/spree_multi_vendor'
```

### UPDATE:
I set spree to `master` branch and test it. Result is **SAME!**

**Comment by damianlegawiec** [comment]
I've tested it on master and it works
