### ISSUE TITLE
Select UI broken in admin panel

### ISSUE THREAD

**Issue by channainfo** [spree/spree#10631]
In the admin panel, select UIs break at the first load, however if I hit refresh on the same page, the browser start to render correctly.

Login to the admin -> Product -> Choose a product to  edit 

![Spree Administration: Products 2020-12-29 15-04-59](https://user-images.githubusercontent.com/4484749/103269439-73dc7480-49e8-11eb-87a2-9ea87d69faa8.png)
It happens on any page that contains select input. 

After hitting refresh
![refresh](https://user-images.githubusercontent.com/4484749/103270598-e51d2700-49ea-11eb-9978-d2d663e7d167.png)

Below is in my Gemfile.
```
gem 'spree', '~> 4.2.0.rc2'
gem 'spree_auth_devise', '~> 4.2'
gem 'spree_gateway', '> 3.9'
```

Tested on macOS Catalina with  Chrome 87, Opera 73, Firefox 84.

**Comment by damianlegawiec** [comment]
@channainfo please update to the master branch - 

```ruby
gem 'spree', github: 'spree/spree', branch: 'master'
```

**Comment by channainfo** [comment]
@damianlegawiec Thanks. After updating the gem above, I still have the same issue.

**Comment by damianlegawiec** [comment]
<img width="1212" alt="Screenshot 2021-01-04 at 11 13 45 AM" src="https://user-images.githubusercontent.com/55154/103524459-eb455480-4e7d-11eb-9889-d5392c7a8b22.png">

current master branch
