### ISSUE TITLE
ActionView::SyntaxErrorInTemplate after rails g spree:backend:copy_views

### ISSUE THREAD

**Issue by Piyush-Chaudhary** [spree/spree#10659]
## Context
I am setting up a new rails e-commerce website. 
## Actual Behavior

After I run `rails g spree:backend:copy_views` I can't go to the [http://localhost:3000/admin/properties](URL) 
It's giving me an error:

`ActionView::SyntaxErrorInTemplate in Spree::Admin::PropertiesController#index
Encountered a syntax error while rendering template: check <% content_for :page_title do %> <%= plural_resource_name(Spree::Property) %> <% end %> <% content_for :page_actions do %> <%= button_link_to Spree.t(:new_property), new_object_url, { class: "btn-success", icon: 'add', 'data-update' => 'new_property', id: 'new_property_link' } %> <% end if can?(:create, Spree::Property) %> <% content_for :table_filter do %> <div data-hook="admin_property_sidebar"> <%= search_form_for [:admin, @search] do |f| %> <%- locals = {f: f} %> <% if current_spree_user.respond_to?(:has_spree_role?) && current_spree_user.has_spree_role?(:admin) && params[:vendor_name_not_null] %><div class="row"> <div class="col-12 col-lg-6"> <div data-hook="admin_property_index_search" class="form-group"> <%= f.label :name_cont, Spree.t(:name) %> <%= f.text_field :name_cont, class: "form-control js-quick-search-target js-filterable" %> </div> </div> <div class="col-12 col-lg-6"> <div class="form-group"> <%= f.label :presentation_cont, Spree.t(:presentation) %> <%= f.text_field :presentation_cont, class: "form-control js-filterable" %> </div> </div> </div> <div class="form-actions" data-hook="admin_pproperties_index_search_buttons"> <%= button Spree.t(:search), 'search' %> </div> <% end %> </div> <% end %> <% if @properties.any? %> <table class="table" id="listing_properties" data-hook> <thead> <tr data-hook="listing_properties_header"> <th><%= Spree.t(:name) %></th> <th><%= Spree.t(:presentation) %></th> <% if current_spree_user.respond_to?(:has_spree_role?) && current_spree_user.has_spree_role?(:admin) && params[:vendor_name_not_null] %><th class="actions"></th> </tr> </thead> <tbody> <% @properties.each do |property| %> <tr id="<%= spree_dom_id property %>" data-hook="listing_properties_row"> <td><%= property.name %></td> <td><%= property.presentation %></td> <% if current_spree_user.respond_to?(:has_spree_role?) && current_spree_user.has_spree_role?(:admin) && property.respond_to?(:vendor) %><td class="actions actions-2 text-right"> <%= link_to_edit(property, no_text: true) if can?(:edit, property) %> <%= link_to_delete(property, no_text: true) if can?(:delete, property) %> </td> </tr> <% end %> </tbody> </table> <% else %> <div class="alert alert-info no-objects-found"> <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Property)) %>, <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::OptionType) %>! </div> <% end %> <%= paginate @collection, theme: 'twitter-bootstrap-4' %>`

## Your Environment

* Version used: **spree-4.1.9**

**Comment by zolzaya** [comment]
I have a same problem

**Comment by Piyush-Chaudhary** [comment]
@zolzaya Did you get resolved it by somehow?

**Comment by Piyush-Chaudhary** [comment]
I am not quite sure about this particular solution but I had resolved by deleting the project all and started now with the **spree', '~> 4.2.0.rc4'** as it's docker based setup is already there.
After doing all the setup mentioned in [guide](https://guides.spreecommerce.org/developer/tutorials/getting_started_tutorial.html#installation), you can run **docker-compose run web rails g spree:backend:copy_views** under the project folder to generate the backend views as of earlier and this time it's not giving any syntax error in opening the  http://localhost:3000/admin/properties.
Although I am not quite very sure that it's not giving any error in any other link but at least not in admin/properties.
