### ISSUE TITLE
Getting Validation failed: Currency Must match order currency 

### ISSUE THREAD

**Issue by Piyush-Chaudhary** [spree/spree#10660]
I am getting below error while running `rake spree_sample:load`

```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Currency Must match order currency
```

## Context
I am building a new application.

## Expected Behavior
Should not give me an error or detailed error that what needs to change.

## Your Environment

* Version used: **spree-4.1.9**

**Comment by damianlegawiec** [comment]
Can't reproduce this, could you try with Spree 4.2?

**Comment by Piyush-Chaudhary** [comment]
Closing for now, as I don't remember the whole thing and already moved to the 4.2 and can't replicate it here.
