### ISSUE TITLE
How to have a different language on backoffice ?

### ISSUE THREAD

**Issue by mgcostaParedes** [spree/spree#10709]
Hello spree community!

After researching for some time, i couldnt find any solution to that, can i set a language to my store which is different from the backoffice? if yes, how can i?

Thanks.

**Comment by damianlegawiec** [comment]
Hi @mgcostaParedes 

You can set it in `config/initializers/spree.rb`

```ruby
Spree::Backend::Config[:locale] = 'fr'
```

**Comment by mgcostaParedes** [comment]
Hi @damianlegawiec , after upgrading to the version 4.2, and having the following:

`Spree::Backend::Config[:locale] = 'en'
Spree::Frontend::Config[:locale] = 'pt'`

It doesnt work, the Frontend remain in en language!

Thanks.

**Comment by damianlegawiec** [comment]
Frontend locale depends on Store settings set in the Admin UI, go to Configuration -> Stores -> Edit Store and select Language
