### ISSUE TITLE
How to customize the emails templates (logo)

### ISSUE THREAD

**Issue by mgcostaParedes** [spree/spree#10705]
Hello, i am new to spree!

I couldnt find any documentation on the spreecommerce website about that, but how can i change the spree emails templates, for example, the logo, or the paragraphs? is that possible?

Thank you.

**Comment by damianlegawiec** [comment]
In Spree 4.2 you can just swap the logo in the Admin Panel UI

**Comment by mgcostaParedes** [comment]
Thank you @damianlegawiec , do you also know how to customize the styles of the emails? i tried to customize on views/layouts/mailer.html.erb but without success!

Best regards.

**Comment by damianlegawiec** [comment]
Template customization is the same for emails or any other view files - https://guides.spreecommerce.org/developer/customization/view.html#template-replacement
