### ISSUE TITLE
 Customization Not Working. ( $enable-rounded: true; )

### ISSUE THREAD

**Issue by MateoLa** [spree/spree#10719]
Adding $enable-rounded: true to the variables.scss file into the application does not work.

## Context

Clean app install.

## Expected Behavior

I shoutl see rounded inputs corners.

## Actual Behavior

They are still square.

## Steps to Reproduce

1. Clean install.
2. Add $enable-rounded:true to variables.scss application file.
3. Clear cache (just in case).
4. Restart your server.

## Your Environment

* Version used:     spree', '~> 4.2.0.rc4'

**Comment by marcelobarreto** [comment]
Same here

**Comment by marcelobarreto** [comment]
@MateoLa I figured out how to use this variable, you need to create the file `bootstrap-overrides.scss` inside the variables folder.

![image](https://user-images.githubusercontent.com/1276556/106676060-fb437780-6594-11eb-8aba-c09c4c7f3a36.png)

Reference: https://github.com/spree/spree/blob/8c3b8a174dcb9ee46e40914f96b24690649b6317/frontend/app/assets/stylesheets/spree/frontend/variables/bootstrap-overrides.scss

I'll also create a PR updating the docs.

**Comment by MateoLa** [comment]
> @MateoLa I figured out how to use this variable, you need to create the file `bootstrap-overrides.scss` inside the variables folder.
> 
> ![image](https://user-images.githubusercontent.com/1276556/106676060-fb437780-6594-11eb-8aba-c09c4c7f3a36.png)
> 
> Reference: https://github.com/spree/spree/blob/8c3b8a174dcb9ee46e40914f96b24690649b6317/frontend/app/assets/stylesheets/spree/frontend/variables/bootstrap-overrides.scss
> 
> I'll also create a PR updating the docs.

Great Marcelo!! Thank you very much, I will try it soon.

**Comment by MateoLa** [comment]
Hi @marcelobarreto Your solucion didn't work for me.
If I add the bootstrap-overrides in the variables folder I get the error: "SassC::SyntaxError in ... Error: Undefined variable: "$font-color"."  If I @import "spree/frontend/variables/variables"; at the top of the bootstrap-overrides to avoid this error I can't see rounded corners in my app.
I tryed the following: I loaded spree from my locals setting $enable-rounded=true in boostrap-overrides.scss file and I coudn't see rounded corners either. 
Seems a bootstrap problem for me. Are you loading any bootstrap in your Gemfile or are you loading the spree defaults?
Thanks, Mateo.

**Comment by marcelobarreto** [comment]
@MateoLa have you tried to clear your `tmp/cache` folder after change the variable?

**Comment by MatthewKennedy** [comment]
Hi @MateoLa 

Are you working in the app/assets folder not the vendor folder? 

I've attached 2 images of a standard rails app named flappy and showing the exact locations of the files mentioned by @marcelobarreto 

File Path and showing enable rounding changed to true:
<img width="898" alt="Screenshot 2021-02-07 at 14 49 43" src="https://user-images.githubusercontent.com/1240766/107150094-ff381680-6953-11eb-9979-4c15652a6371.png">


File Path of Variables with border radius amped up:
<img width="835" alt="Screenshot 2021-02-07 at 14 49 56" src="https://user-images.githubusercontent.com/1240766/107150119-20990280-6954-11eb-90d1-968192e9962b.png">

**Comment by MatthewKennedy** [comment]
@MateoLa I have a possible fix for you, it happened randomly on me just now:

Try removing `*= require_tree .` from `app/assets/stylesheets/spree/frontend/variables/application.css`

That did it for me.

**Comment by damianlegawiec** [comment]
Please use https://github.com/spree/spree_starter or run

```shell
bundle exec rails g spree:frontend:install
```
