### ISSUE TITLE
New products does not load until cache clear

### ISSUE THREAD

**Issue by J4im3x0** [spree/spree#10712]
I am running spree on nginx, with cloudflare for protection. For any reason when I add new products, those products are not shown until I clear spree cache and browser cache.

## Steps to Reproduce
1. Create a new product
2. Search the product
3. The product is not visible yet
4. Clear cache of spree and browser
5. The product must be shown now

## Your Environment
* Version used: 4.0.0.alpha2 (not pretty sure, I am new on this)
* Ruby version: ruby 2.6.5p114

**Comment by damianlegawiec** [comment]
Hey @J4im3x0 please update your version to stable 4.0.0. Using alpha versions is not recommended :)
