### ISSUE TITLE
when use docker to deploy spree and find this issue

### ISSUE THREAD

**Issue by 121213tjfgalfjaf** [spree/spree#10717]
**FROM the docker install log,Found this warning info :**

  | [Scout] [01/25/21 02:53:10 +0000 8fd8250664de (1)] INFO : Couldn't find configuration in /app/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.

postgres_1   | 2021-01-25 02:59:13.278 UTC [43] FATAL:  database "spree_starter_development" does not exist

## Context

click the site menu docker installed .each category will got error.the error message is :
**can't find record with friendly id: "men".**
![image](https://user-images.githubusercontent.com/5094727/105656027-4954dd00-5efc-11eb-9d24-c526f79b5776.png)

## Expected Behavior

hope the spree each instlallation will get tested and more detail about the underground things. we are the spree applier not the developer so the unexpected error may make the spree not easy to use.
From the first time we met spree ,we never install spree sucessed by ourself.
it's too  diffcult.

thanks for fix the deploy issues.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by jarforce** [comment]
Hi,
I got the same error too, with latest spree_starter

```
The Gemfile's dependencies are satisfied
[Scout] [02/17/21 01:49:17 +0000 67c4e13bd2ca (11)] INFO : Couldn't find configuration in /app/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "spree_starter_development" does not exist
/app/config/environment.rb:5:in `<main>'

Caused by:
PG::ConnectionBad: FATAL:  database "spree_starter_development" does not exist
/app/config/environment.rb:5:in `<main>'
Tasks: TOP => db:drop => db:load_config => environment
(See full trace by running task with --trace)
ERROR: 1
```

**Comment by LucasKuhn** [comment]
Same thing here, with any taxon: 
![image](https://user-images.githubusercontent.com/26127185/109714294-003e1b80-7b81-11eb-8087-3a3968b9b997.png)

**Comment by damianlegawiec** [comment]
> Same thing here, with any taxon:
> ![image](https://user-images.githubusercontent.com/26127185/109714294-003e1b80-7b81-11eb-8087-3a3968b9b997.png)

did you imported sample data? https://github.com/spree/spree_starter#import-sample-data-such-as-products-categories-etc-optionally

**Comment by LucasKuhn** [comment]
I followed the description on main spree repo, didn't know about the starter guide.
Thank you for linking this Damian! 👍👍
The taxon links are now working with the sample data. Got another Docker problem - but that's another issue 😆
