### ISSUE TITLE
API V2 - account creation fails. After creation sending account confirmation instructions is bugged

### ISSUE THREAD

**Issue by giugrilli** [spree/spree#10759]
Trying to register a new user through API V2

Spree::Api::V2::Storefront::AccountController#create

FAILS. 

The user is created correctly, however, after the creation, the method send_confirmation_instructions is triggered without any arguments (which is supposed to be the "current_store" ). The webview instead works.

## Context
Spree v4.2.0.rc5
User with devise confirmable = true
User registration works in the browser, fails via api

## Expected Behavior
User is able to register and receives confirmation email

## Actual Behavior
`
ArgumentError (wrong number of arguments (given 0, expected 1)):
spree_auth_devise (4.3.2) app/models/spree/user.rb:45:in 'send_confirmation_instructions'
`

## Possible Fix
The storefront registration webview controller has these two methods in the controller Spree::UserRegistrationsController:

-- BEFORE USER SAVE --
`
resource.skip_confirmation_notification! if Spree::Auth::Config[:confirmable]
`

-- AFTER USER SAVE --
`
resource.send_confirmation_instructions(current_store) if Spree::Auth::Config[:confirmable]
`

These two methods allow the user to be registered and the confirmation email to be sent.
**This mechanism is not present in the API controller**

## Steps to Reproduce
1. Enable devise confirmable
2. Try to register a user via API

## Your Environment

* Version used: v4.2.0.rc5

**Comment by damianlegawiec** [comment]
Should be resolved by https://github.com/spree/spree_auth_devise/pull/516
