### ISSUE TITLE
multi_vendor NoMethodError in Spree::Products#show 

### ISSUE THREAD

**Issue by splatt92** [spree/spree#10769]
Hello,
I don't know if I'm doing something wrong or is it a bug, but when I assign a product to a vendor and want to show a product, there occur an error:

## Context

**NoMethodError in Spree::Products#show**
Showing /home/splatt/Documents/t_3/app/views/spree/products/show.html.erb where line #14 raised:
undefined method `vendor_path' for #<ActionView::Base:0x0000000003b3a8>
Did you mean?  video_path

simultaneously the server goes:

  ↳ app/views/spree/products/show.html.erb:4:in `_5ea03ef43ecad46eb04594da6af00584'
**Unpermitted parameter: :id
Unpermitted parameter: :id**
 

## Expected Behavior
Show a product assigned to vendor.

## Actual Behavior
Showing an error **NoMethodError in Spree::Products#show**

## Steps to Reproduce
1. Install multi_vendor extension
2. Add vendors
3. Add product and assign it to vendor
4. Show this product

## Environment
Ubuntu 20.04.2 LTS
Local instance (not docerized)
Ruby 3.0.0, Rails 6.1.1
Spree gems:

`gem 'spree', '~> 4.2.0.rc5'`
`gem 'spree_auth_devise', '~> 4.3'`
`gem 'spree_gateway', '~> 3.9'`
`gem 'sassc', github: 'sass/sassc-ruby', branch: 'master'`
`gem 'spree_multi_vendor', github: 'spree-contrib/spree_multi_vendor'`

**Comment by damianlegawiec** [comment]
Please update `spree_multi_vendor`, this is fixed in new version :)
