### ISSUE TITLE
Can not switch the language after upgrading to the rc5

### ISSUE THREAD

**Issue by channainfo** [spree/spree#10761]
I try to switch the locale both backend and frontend using locale params, for instance, locale=es. I set two stores, one using EN locale and the other using ES locale.

I built an admin and store front menu to allow users to be able to switch locale which worked well before upgrading. I think spree must have intercepted the locale somewhere.

What is the best possibly way to handle this in spree 4.2.0-rc5? I have only one domain for my site.

**Comment by damianlegawiec** [comment]
As discussed on slack - to switch between locales that locale needs to be marked as supported in any of the existing Stores 

https://github.com/spree/spree/blob/b89d0200dba3a6a76fda0e3f870d2141357c471e/core/lib/spree/core/controller_helpers/currency.rb#L19

**Comment by channainfo** [comment]
@damianlegawiec I set two stores one in **es** and the other in **en**. I have the default locale set in **en**. when I try any URL in the storefront for example http://example.com?locale=es it did not work.

**Comment by damianlegawiec** [comment]
@channainfo Sorry I've mixed up currencies with locales - you are correct, we are missing this ATM, but we'll be added back before the final 4.2 release

**Comment by damianlegawiec** [comment]
This is now available in 4.2.0 🚀
