### ISSUE TITLE
Exists project + Spree Commerce. Error on action_policy

### ISSUE THREAD

**Issue by helmiItsavirus** [spree/spree#10790]
Rails 6.0.3
Ruby 2.6.6
Spree 4.2.0rc5
Action_policy 0.4.4

## Problem
**wrong number of arguments (given 2, expected 0..1)** 

    # Raises `ActionPolicy::Unauthorized` if check failed.
    def authorize!(record = :__undef__, to: nil, **options)
      to ||= :"#{action_name}?"

      super(record, to: to, **options)

## Summary
I tried to mix my project with Spree commerce and I had a problem if my exists project use action_policy. I think action policy for rails 6.0.3 doesn't fit with action policy Spree commerce.

**Comment by damianlegawiec** [comment]
Spree uses CanCanCan for authorization. It will not be possible to use CanCanCan and Action Policy at the same time
