### ISSUE TITLE
Redirect (301) in routes

### ISSUE THREAD

**Issue by skydev2020** [spree/spree#10805]
I worked with Spree and I found this line in while doing 'rake routes'.

> api GET|POST|PUT|PATCH|DELETE /api/v:api/*path(.:format)      redirect(301) {:format=>"json"}
>       GET|POST|PUT|PATCH|DELETE /api/*path(.:format)            redirect(301) {:format=>"json"}
> 
What does it mean? what is v:api and what is redirect(301)? I know what redirect(301) is but what will be the new urls?
And does it mean all v1/ v2/ apis will be redirect to api/ ?

**Comment by damianlegawiec** [comment]
Before Spree 3.1 there was only one not-versioned API under `/api/`. For legacy integrations there is a redirect from `/api/something` to `/api/v1/something`. This redirect of course skips URLs such as `/api/v1/something` or `/api/v2/something`

**Comment by skydev2020** [comment]
@damianlegawiec
What is this statement exactly?
redirect(301) {:format=>"json"}
What will above statement return/generate?

We usually specify the url inside parameter like this 
redirect('/articles')
