### ISSUE TITLE
Promotions no longer work with Spree 4.2 Stable

### ISSUE THREAD

**Issue by s3749653** [spree/spree#10856]
Hey, after using spree 4.2 RC4 promotions were working perfectly fine, after updating to spree 4.2 stable it appears the promotions are no longer working. After entering the code, no response is given and no adjustment is applied.

## Expected Behavior
adjustment is applied to cart after entering code, or error message explaining why it didn't work.

## Actual Behavior
no adjustment is applied if code is entered

## Possible Fix
Not really sure at this point, still working through the code

## Steps to Reproduce
1. Set up spree 4.2
2. Set up a promotion
3. Enter code for the promotion

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use sqlite3 as the database for Active Record
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'spree_dynamic_variants', github: 'hefan/spree_dynamic_variants', branch: 'master'

gem 'spree', '~> 4.2.0'
gem 'spree_auth_devise', '~> 4.3'
gem 'spree_gateway', '~> 3.9'
gem 'spree_i18n', '~> 5.0'

gem 'pg'
gem 'coffee-rails'
gem 'spree_analytics_trackers', '~> 2.0'
gem 'spree_slider', github: 'spree-contrib/spree_slider'
gem 'dalli-elasticache'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'
gem 'aws-sdk-s3'
gem 'spree_reviews', github: 'TruemarkDev/spree_reviews', branch: 'spree4'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content'
gem 'spree_paypal_express', github: 's3749653/better_spree_paypal_express'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

**Comment by damianlegawiec** [comment]
@s3749653 how are you applying promos? Storefront? Admin Panel? API? what kind of promos?

**Comment by s3749653** [comment]
Hey, sorry for not being more clear, promotions are added via the admin panel, I've just downgraded to the 4.2 RC4 and the promotions are now working as normal.

**Comment by damianlegawiec** [comment]
@s3749653 are you talking about new promotions or existing ones?

**Comment by s3749653** [comment]
Both, I've tried creating a new promotion via the admin panel as well as the old promotions are no longer working. Specifically the promotion I've create is where a user has cart with a total over $59 a $19.95 adjustment is applied

**Comment by damianlegawiec** [comment]
@s3749653 please paste a screenshot of your promotion edit screen, can't reproduce this, fresh install:

![Screenshot 2021-03-08 at 12 38 47](https://user-images.githubusercontent.com/55154/110316597-41b04a00-800b-11eb-893d-571fa4f48677.png)
![Screenshot 2021-03-08 at 12 38 37](https://user-images.githubusercontent.com/55154/110316601-4248e080-800b-11eb-95d3-3dd29dd338e4.png)

**Comment by damianlegawiec** [comment]
also what kind of customizations have you created in your store?

**Comment by s3749653** [comment]
<img width="1137" alt="Screen Shot 2021-03-08 at 10 44 12 pm" src="https://user-images.githubusercontent.com/49256154/110317154-d5ac0100-805f-11eb-8c1a-57a027aaeb19.png">

**Comment by s3749653** [comment]
Customisation wise, it is mainly done so that products with variants are created dynamically as opposed to creating when creating the product. Other then this no real customisations were added

**Comment by damianlegawiec** [comment]
@s3749653 are you using some extension for that `Coverlads` path?

**Comment by s3749653** [comment]
the coverlads path was just a test to see if the path made a difference(wasn't really sure what it did), but I tried it without the path and the issue still remains.

**Comment by damianlegawiec** [comment]
@s3749653 did you set the `default currency` of your Store to `AUD` ?

**Comment by s3749653** [comment]
Yep, default currency is set to AUD

**Comment by damianlegawiec** [comment]
@s3749653 

1. what about supported currencies? 
2. what value does `Spree::Configp[:currency]` is set to?
3. what `currency` is set for `Order` records?

**Comment by s3749653** [comment]
1) only supported currency on my store is AUD
2) my spree.rb is
`  # Configure Spree Preferences
#
# Note: Initializing preferences available within the Admin will overwrite any changes that were made through the user interface when you restart.
#       If you would like users to be able to update a setting with the Admin it should NOT be set here.
#
# Note: If a preference is set here it will be stored within the cache & database upon initialization.
#       Just removing an entry from this initializer will not make the preference value go away.
#       Instead you must either set a new value or remove entry, clear cache, and remove database entry.
#
# In order to initialize a setting do:
# config.setting_name = 'new value'
require('spree/searcher_class.rb')
Spree.config do |config|
  config.logo = 'logo.png'
  config.admin_interface_logo = 'logo.png'
  config.currency = "AUD"
  config.disable_sku_validation = true
  config.products_per_page = 32
  config.shipping_instructions = true
  config.searcher_class= Spree::SearcherClass
end
Spree::PermittedAttributes.line_item_attributes << :notes
Spree::PermittedAttributes.line_item_attributes << :model

# Configure Spree Dependencies
#
# Note: If a dependency is set here it will NOT be stored within the cache & database upon initialization.
#       Just removing an entry from this initializer will make the dependency value go away.
#
Spree.dependencies do |dependencies|
  # Example:
  # Uncomment to change the default Service handling adding Items to Cart
  # dependencies.cart_add_item_service = 'MyNewAwesomeService'
end

# Spree::Api::Dependencies.storefront_cart_serializer = 'MyRailsApp::CartSerializer'

Spree.user_class = "Spree::LegacyUser"
`

Currently investigating 3.

**Comment by s3749653** [comment]
I've deleted the views folder and it seems as though the promotion is now working. It looks like part of my customisation must of inhibited it. Thank your for the help, I will now work to find and fix the issue :)

**Comment by s3749653** [comment]
For anyone experiencing a similar issue, after removing the _head partial(no customisations were done anyway) the issue was resolved.

**Comment by damianlegawiec** [comment]
@s3749653 thanks, I've added that information to [4.2 upgrade guide](https://github.com/spree/spree/commit/8d4ff978e19032ce3963b4878682d780e6c193ef)
