### ISSUE TITLE
Remove jQuery completely

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#10855]
TODO:

- [ ] replace jQuery ajax code with `fetch` in Storefront - https://github.com/spree/spree/issues/10849 
- [ ] replace all remaining jQuery code from Storefront - https://github.com/spree/spree/issues/10853
- [ ] replace jquery ajax code with `fetch` in extensions
- [ ] replace jquery ajax code with `fetch` in Admin Panel
- [ ] replace all remaining jQuery code from extensions
- [ ] replace all remaining jQuery code from Admin Panel

**Comment by zolzaya** [comment]
Hey @damianlegawiec, how about stimulus?
