### ISSUE TITLE
Migrate from Turbolinks to Hotwire Turbo

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#10850]
[Hotwire Turbo](https://turbo.hotwire.dev/) is the spiritual successor of [Turbolinks](https://github.com/turbolinks/turbolinks) which we use extensively in the Storefront.

We should use the [turbo-rails gem](https://github.com/hotwired/turbo-rails).

References:

* https://github.com/hotwired/turbo-ios/blob/main/Docs/Migration.md

**Comment by zolzaya** [comment]
Yeey awesome. Turbo is awesome.
