### ISSUE TITLE
Admin Panel: Misplaced checkboxes in the Payment Provider Settings window

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10902]
## Context
In Admin Panel there are two misplaced checkboxes overlapping with the text in Payment Method's edit view, in the "Payment Provider Settings" window.
![payment provider set](https://user-images.githubusercontent.com/74255636/112126387-b0bd9f00-8bc4-11eb-8b9b-1a020c6de559.png)

## Expected Behavior
No checkboxes overlapping with text

## Actual Behavior
There are two checkboxes overlapping with text on the top and the bottom of the Payment Provider Settings window.

## Steps to Reproduce
1. Go to Admin Panel
2. Open the Configurations menu on the left side
3. Open the Payment Methods
4. Click the blue pencil icon to edit the payment method

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_i18n’

**Comment by grzeszet** [comment]
This is an issue found on Spree Demo Staging.
 @agnieszkajacek commented on it on 02/18/21:
 HTML/CSS are different in locally and in staging - below you can see, that div in staging has class form-group  and we have different order in input and label   
 
![image (1)](https://user-images.githubusercontent.com/74255636/112128177-70f7b700-8bc6-11eb-8818-37abacf87a3d.png)

It should look like this (like in local env): 

![image (1) (1)](https://user-images.githubusercontent.com/74255636/112128242-8371f080-8bc6-11eb-9e8a-68332a3e35ca.png)

How to recreate the staging problem locally?
https://github.com/spree/spree/blob/master/backend/app/helpers/spree/admin/base_helper.rb#L150 in this line change contition to: if object.preference_type(key) != :boolean → somehow, checkbox values ​​aren't considered boolean. I checked both locally and on staging and these values ​​are boolean values. 

 

I couldn't find a solution to this, and I couldn't find out why these values ​​are different from boolean, even though they are such a value.
But IMO this problem lies in the code above

**Comment by MatthewKennedy** [comment]
Hi @grzeszet,

I feel responsible for this issue as it is from a change I made, but I am having trouble to recreate it locally and in production.

My first guess is to ensure that the comparison is a symbol against a symbol, but it's a long shot. Is there a way you can test the PR: Ensure comparison is on a symbol. #10914 in the environment where the issue occurs?
