### ISSUE TITLE
Admin Panel - edit/delete buttons inconsistent placement on Relation Types & Stock Transfer lists

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10910]
## Context
Currently, in Admin Panel it was observed that the placement of edit/delete or look buttons is inconsistent with other Tabs in Admin Panel:

- Relation Types
- Stock Transfers
<img width="1440" alt="Zrzut ekranu 2021-01-22 o 11 52 35 (1)" src="https://user-images.githubusercontent.com/74255636/112182802-e763db80-8bfd-11eb-8dbf-be6cd2985edf.png">
<img width="1439" alt="Zrzut ekranu 2021-01-22 o 11 54 23 (1)" src="https://user-images.githubusercontent.com/74255636/112182796-e632ae80-8bfd-11eb-9aaf-3b75fe6da0c3.png">

## Expected Behavior
All edit/delete/look buttons should be alligned to right in the lists, as for example here in tax rates

## Actual Behavior
Some tabs have inconsistent placement of edit/delete or look buttons

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by aneskap** [comment]
@grzeszet let's test this on our env
