### ISSUE TITLE
No results are shown in the search field if we add "space" before or after the name of the product

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10921]
## Context
Adding a space character before or after searched term gives no search results.
See the 3 screenshots (with space before, after, and with no space)

![Zrzut ekranu 2020-10-08 o 11 06 10](https://user-images.githubusercontent.com/74255636/112468614-c5d33300-8d68-11eb-8308-b06771b7ab2f.png)
![Zrzut ekranu 2020-10-08 o 11 40 59](https://user-images.githubusercontent.com/74255636/112468643-cf5c9b00-8d68-11eb-89c2-2a1c37913337.png)
![Zrzut ekranu 2020-10-08 o 11 05 47](https://user-images.githubusercontent.com/74255636/112468647-d08dc800-8d68-11eb-9f03-e8e3c67f9229.png)

## Expected Behavior
As a user, when I use the search field & enter space before or after the product I should get the same results as without it.

## Actual Behavior
Adding space character gives no results in search results.

## Steps to Reproduce
1. Go to Homepage, hit search
2. In Search write for example “Wool Blend Short Coat”, 
3.See that you get the results, if you have such product listed
4.Go back to Search field and add “space” before or after “Wool Blend Short Coat”, observe
5.“ Wool Blend Short Coat” or “Wool Blend Short Coat “ both, will show no results.

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by SylarRuby** [comment]
@damianlegawiec maybe on line [125](https://github.com/spree/spree/blob/c47e591882d79e766847c627773d29186aa2224b/core/lib/spree/core/search/base.rb#L125) we could use strip?

```rb
@properties[:keywords] = params[:keywords].strip
```
I have not tried this 🙈

**Comment by damianlegawiec** [comment]
> @damianlegawiec maybe on line [125](https://github.com/spree/spree/blob/c47e591882d79e766847c627773d29186aa2224b/core/lib/spree/core/search/base.rb#L125) we could use strip?
> 
> ```ruby
> @properties[:keywords] = params[:keywords].strip
> ```
> 
> I have not tried this 🙈

that would solve it - please submit a PR with that fix :)
