### ISSUE TITLE
Multi Currency - Admin Panel - Wrong calculations in User's Lifetime Stats if user has orders in different currencies

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10938]
## Context
The amount of all orders value in Lifetime Stats in AP is presented in one currency, even if different orders were placed in various currencies. Additionally, the whole amount changes accordingly with set Default Currency without any conversion, which finally makes the presented value incorrect.

https://user-images.githubusercontent.com/74255636/112814451-99c4f400-907f-11eb-8089-a507fe479c1b.mov

On the screen attached below we can observe the scenario when the user has placed the first and only order in GBP currency, despite that, in Lifetime Stats the order is presented in Euro (default currency).
![Screenshot 2021-03-11 at 16 49 41](https://user-images.githubusercontent.com/74255636/112814550-b19c7800-907f-11eb-8623-5899b37e6d3d.png)

## Expected Behavior
User Lifetime Stats should be presented divided into different currencies. Changing the default currency should not affect the order's whole amount currency.

## Actual Behavior
The orders made in different currecies are merged as one, with incorrect conversion. 

## Steps to Reproduce
1.Go to Admin Panel/users/edit/orders
2. Observe the Lifetime Stats tab
3. Change the default currency in Confugurations/General Settings
4. Go back to the 'edit user' page and observe the issue. 

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by aneskap** [comment]
Solved in https://github.com/spree/spree/pull/11208
