### ISSUE TITLE
Mobile - Overlapping line separator in some languages

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10947]
## Context
On mobile devices the line separator in the Cart is not adjusted to the words longer than "OR". Those situations are connected with translations. After switching to a different language than English, we can observe that the line is overlapping the word inside. 

![IMG_45663158A132-1](https://user-images.githubusercontent.com/74255636/112995960-0c130280-916c-11eb-8f9e-6f38aa4b0307.jpeg)
![IMG_E198D12CFE95-1](https://user-images.githubusercontent.com/74255636/112996620-9bb8b100-916c-11eb-9c50-a4164b2c732e.jpeg)
The proper look in English:
![IMG_C6D92A3374B5-1](https://user-images.githubusercontent.com/74255636/112996681-ab37fa00-916c-11eb-81dc-9c7b57c67936.jpeg)

## Steps to Reproduce

1. On mobile change language to SE
2. Add a product to cart
3. Go to cart
4. Observe the issue 

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by Miktom123** [comment]
Fix implemented on staging ver. 4.3.0.alpha. Verified on Chrome / Windows - desktop and mobile view. 
![image](https://user-images.githubusercontent.com/74255917/121533524-a8754300-ca00-11eb-9692-8e02b27b3a98.png)
