### ISSUE TITLE
Footer - Store name is not adjusted to center of the footer [MOBILE]

### ISSUE THREAD

**Issue by EmailZen** [spree/spree#10954]
## Context
On mobile devices, footer section text should be adjusted to the center, contrary to the desktop where it is adjusted to the left. 
Please refer to the screenshot attached.

## Expected Behavior
Store name should be adjusted to the center of the footer on mobile devices.

## Actual Behavior
The store name is not adjusted to the center of the footer on mobile devices.

## Steps to Reproduce
1. Go to Homepage
2. Scroll to the bottom of the Homepage
![store name](https://user-images.githubusercontent.com/36955251/113288224-f67a1600-92ee-11eb-8ea7-2aedfe433381.jpg)

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by leonid1035** [comment]
www.https://smartphoneluck.com

**Comment by leonid1035** [comment]
smartphoneluck.com
