### ISSUE TITLE
Spree::NumberAsParam#to_param broke resource_path method

### ISSUE THREAD

**Issue by sergiy-koshoviy** [spree/spree#10957]
Models which include `Spree::NumberAsParam` have problem with `resource_path` helper.

## Context
This helper use default ActiveRecord method `to_param` 
`resource_path(spree_order) # => /spree_order/#{spree_order.to_param}`
https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activerecord/lib/active_record/integration.rb:57
The helper  overwritted by `include` [Spree::NumberAsParam](https://github.com/spree/spree/blob/c47e591882d79e766847c627773d29186aa2224b/core/app/models/concerns/spree/number_as_param.rb)

It's problem when you use some other gems which use `resource_path(resource)` and you can't replace it by `resource_path(resource.id)`, for example.

## Expected Behavior
`resource_path(spree_order) # => /spree_order/1`

## Actual Behavior
`resource_path(spree_order) # => /spree_order/R365442852`
As result `link 'Show', resource_path(resource)` will be broken

## Your Environment

* Version used: 
    spree (4.1.0)
      spree_api (= 4.1.0)
      spree_backend (= 4.1.0)
      spree_cmd (= 4.1.0)
      spree_core (= 4.1.0)
      spree_frontend (= 4.1.0)
      spree_sample (= 4.1.0)

**Comment by damianlegawiec** [comment]
Spree routes should be used via spree helper eg. `spree.resource_path(resource)`

I would also recommend updating 4.1.0 to https://github.com/spree/spree/releases/tag/v4.1.11 for security reasons. Enabling [dependabot](https://dependabot.com/) in your GitHub repo will auto-generate security update PRs automatically

**Comment by sergiy-koshoviy** [comment]
it's good solution, but when `resource_path(resource)` inside in the other gem, using `spree.resource_path(resource)` is impossible.

**Comment by sergiy-koshoviy** [comment]
Also it doesn't work for example for Active Admin
```
> spree.resource_path(resource) =>

app/admin/spree_orders.rb:6:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `resource_path' for #<ActionDispatch::Routing::RoutesProxy:0x00007ff2665bbc00>
...gems/actionpack-6.0.2.1/lib/action_dispatch/routing/routes_proxy.rb:50:in `method_missing'```

**Comment by sergiy-koshoviy** [comment]
Some variant for avoid the error

```
module Spree
  module OrderDecorator
    Spree::Order.class_exec do
      class << self
        def find(*args)
          return super if block_given?

          if args.is_a?(Array) && args.first.is_a?(String)
            find_by(number: args.first)
          else
            super
          end
        end
      end
    end
  end
end

```

But if you would like to use ActiveAdmin for some Spree entity with filter it can generate error
`undefined method 'created_by_id_eq' for #<Ransack::Search`
