### ISSUE TITLE
*** ArgumentError Exception: missing keyword: :variant

### ISSUE THREAD

**Issue by HumzahChoudry** [spree/spree#10965]
Getting an error here when using the `remove_promotion_line_items` method. Seems like it should be using variant rather than item
https://github.com/spree/spree/blob/8ca9ec736a471b66f66d718b157be69946f8c5fc/core/app/models/spree/promotion_handler/coupon.rb#L78

**Comment by damianlegawiec** [comment]
Thanks for reporting @HumzahChoudry - you are correct, this should be `variant: item.variant`, could you prepare a PR with a fix?

**Comment by HumzahChoudry** [comment]
I made a merge request here https://github.com/spree/spree/pull/10970. Not sure if I have done so correctly. Let me know if there are any issues.
