### ISSUE TITLE
How To Override a Class In Spree Commerce

### ISSUE THREAD

**Issue by helmiItsavirus** [spree/spree#10998]
Hy guys, I just want to know how to override Class on Spree commerce, I already set the Dependency Injection, and all things on Docs but Still doesn't work.

**Comment by damianlegawiec** [comment]
What version are you using? 

* http://rubylearning.com/satishtalim/ruby_overriding_methods.html
* https://www.geeksforgeeks.org/ruby-method-overriding/

You can also just re-define the entire class in your project
