### ISSUE TITLE
support direct buy item and cart select some item to buy

### ISSUE THREAD

**Issue by tianlu1677** [spree/spree#10990]
When I use it, sometimes direct buy product item, but now we have to put it on cart, then to buy.

When people put many thing on cart, but she only want buy some items. Now all thing on one order, so what can i do ?

**Comment by damianlegawiec** [comment]
Maybe you could use https://github.com/spree-contrib/spree_wishlist ?

**Comment by tianlu1677** [comment]
> Maybe you could use [spree-contrib/spree_wishlist](https://github.com/spree-contrib/spree_wishlist) ?

Thanks, I try add column to line_item set is choose or not.
