### ISSUE TITLE
As an admin user v2 addresses endpoint returns all addresses

### ISSUE THREAD

**Issue by imella** [spree/spree#11003]
## Context
By making a request to `/api/v2/storefront/account/addresses` as an admin user, it returns addresses from all users.

## Expected Behavior

It should only return addresses associated with the current user

## Actual Behavior

Returns addresses related to all users

## Possible Fix

Maybe revert to the old behaviour from v4.1

```ruby
# api/app/controllers/spree/api/v2/storefront/account/addresses_controller.rb
def scope
  spree_current_user.addresses
end
```
Unless this is the actual expected behaviour

## Your Environment

* Version used: spree 4.2.2

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/11085
