### ISSUE TITLE
Integrate ActionText by default

### ISSUE THREAD

**Issue by zolzaya** [spree/spree#11039]
Integrate [action_text ](https://edgeguides.rubyonrails.org/action_text_overview.html) by default in products form in admin

**Comment by damianlegawiec** [comment]
Hi @zolzaya we're planning on adding a WYSIWYG editor in Spree 4.3, we're still discussing with @MatthewKennedy which one to use. Action Text / Trix is quite simplistic and lacks many features of TinyMCE/FCKEditor.
