### ISSUE TITLE
too big cache size after updating from 3.7 to 4.2

### ISSUE THREAD

**Issue by ajahongir** [spree/spree#11103]
After updating spree from 3.7 to 4.2 having issue with cache leaking. it increasing upto 10gb on my server that cause to stop working as out of HD usage.

in generally not too much products on store - about 250pcs. and before worked well.
now viewing is not too much, only 30-40visitors per a day but issue is raising.

is there any way to control cache size and caching parts?

**Comment by damianlegawiec** [comment]
Configure auto expiring old cache - `expires_in` option https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-store and set it to 1 day or 1 week and see results

Spree 4.1+ includes full page caching which can take a lot of space. Also don't use file-based caching, that's not recommended - use Memcached/Redis instead.

**Comment by ajahongir** [comment]
well. changed caching to redis store and assign expire time to 1 week. lets see how it works. as before every 2-3days my server failed with disk is full

**Comment by ajahongir** [comment]
after couple days of using. cache size is about 2gb instead of 9gb file based cache before.
