### ISSUE TITLE
SECURITY.md hyperlink redirects to 404 page

### ISSUE THREAD

**Issue by raiyansayeed** [spree/spree#11116]
Link on SECURITY.md and the [actual site](https://guides.spreecommerce.org/developer/upgrades/#security) redirects to a 404 page instead of a page outlining the security policy. 

## Expected Behavior

Redirects to page that outlines Spree's Security policy

## Actual Behavior

Redirects to 404 page

## Possible Fix

Create a page on the [site](https://guides.spreecommerce.org/developer/security/security.html) website or link to the new security policy if it is hosted elsewhere. 

## Steps to Reproduce

1. Go to https://github.com/spree/spree/blob/master/SECURITY.md
2. Click on link

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
Thanks, fixed!
