### ISSUE TITLE
Error when creates product without Shipping Categorie

### ISSUE THREAD

**Issue by rjurado01** [spree/spree#11200]
When you try to create new product with Shipping Categorie `None` value it throw an error.

## Context

I try to create new product with this information:

![image](https://user-images.githubusercontent.com/1703608/128179810-918434c0-4852-42e7-a6c9-8c5e6ace6c8a.png)

## Expected Behavior

Create new product or show required error on Shipping Categories field.

## Actual Behavior

I get this error:

![image](https://user-images.githubusercontent.com/1703608/128179645-c411f8b8-e304-4860-b46d-17271a7b04d9.png)

## Your Environment

* Version used: 4.2.1
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/rjurado01/edde178560cb408facb42a4f5ca6f52a

**Comment by damianlegawiec** [comment]
Could you upgrade to 4.2.5 and test it there? Also, it doesn't appear to be surfacing in 4.3

**Comment by rjurado01** [comment]
It is solved on 4.3
