### ISSUE TITLE
4.3.0.alpha - multi store questions

### ISSUE THREAD

**Issue by rjurado01** [spree/spree#11220]
I'm checking 4.3.0.alpha functionality and I have some questions.

I'm traying to build a system of three stores, each one for a brand.

* I see that a Menu is related to a Language. If I have some stores in the same language.
  How I can create a custom menu for each store?

* When I try to access to a secondary store, I have an error `can't find record with friendly id: "categories/women"`.
  I have checked that Taxonomy model has a `belongs_to` relation with store. I can't find the option in the admin panel to select the Taxomomy store. Do I have to duplicate Taxomomies for each store ?

**Comment by damianlegawiec** [comment]
> I'm checking 4.3.0.alpha functionality and I have some questions.
> 
> I'm traying to build a system of three stores, each one for a brand.
> 
> * I see that a Menu is related to a Language. If I have some stores in the same language.
>   How I can create a custom menu for each store?

Each Store has their own separate list of Menus

> * When I try to access to a secondary store, I have an error `can't find record with friendly id: "categories/women"`.

Does that happen in Storefront? Or Admin Panel?

>   I have checked that Taxonomy model has a `belongs_to` relation with store. I can't find the option in the admin panel to select the Taxomomy store. Do I have to duplicate Taxomomies for each store ?

Admin Panel is scoped by Store, in the top left corner you have a Store switcher which tells you which Store resources are you managing at the moment

**Comment by rjurado01** [comment]
You are right, I'have not seen the Store switcher. Thanks !!
