### ISSUE TITLE
[Guides] Code blocks have text that don't pass bg/fg contrast

### ISSUE THREAD

**Issue by vfonic** [spree/spree#11249]
I noticed that it's hard to read some of the code blocks because the text is too dark on a dark background.

For example:
<img width="921" alt="Screen Shot 2021-08-16 at 12 05 31 PM" src="https://user-images.githubusercontent.com/67437/129547228-3e041ee6-3ac4-4f38-a1a5-5b03068daf53.png">

I've used this online tool to check if these color combinations are accessible:
https://color.a11y.com/ContrastPair/?bgcolor=0066cc&fgcolor=282a36

After that, I used this tool to get the first lightened color:
https://www.hexcolortool.com/#0066cc

It turns out that, in order to get all the contrast tests to pass, the color has to be lightened by 40%.

Here's the end result:
<img width="814" alt="Screen Shot 2021-08-16 at 12 05 41 PM" src="https://user-images.githubusercontent.com/67437/129547248-5a14575e-c7cd-4bc0-8737-6badb7694dbc.png">

I've noticed that this color might be some Spree's primary color or similar. So it might not be as simple as changing this one color value.
Also, I noticed that `#0066ff` color is used as a value in several other places in the CSS. Should all of these be changed?

**Comment by MatthewKennedy** [comment]
Hi @vfonic 

A good point, but all the Spree guides are moving over to Gitbook as we speak so I think this issue will be resolved in the process.

**Comment by vfonic** [comment]
Ah, good to know! Is there any place where it's possible to track this move/progress and to contribute?
