### ISSUE TITLE
CANNOT LOGIN TO THE DEMO SPREE ECOMMERCE ADMIN PANEL ON HEROKU

### ISSUE THREAD

**Issue by faraimupfuti** [spree/spree#11251]
## Context
I just installed the demo spree ecommerce on Heroku platform.
I am struggling to use my default ADMIN_EMAIL & ADMIN_PASSWORD to access my Admin panel.

## Expected Behavior
When i use my default ADMIN_EMAIL & ADMIN_PASSWORD, i should login to the Admin Panel instantly.

## Actual Behavior
When i try to login to the  Admin Panel using my default ADMIN_EMAIL & ADMIN_PASSWORD, the below error pops up. 
![spree](https://user-images.githubusercontent.com/19797552/129571228-6d073abf-7f80-4716-816c-5a08528ccbdc.PNG)

## Steps to Reproduce
I followed the below instructions by simply clicking on the link that deploys spree on heroku
![git](https://user-images.githubusercontent.com/19797552/129571705-cb5c95ca-dd68-4226-8b56-ccb8ede34921.PNG)

## Your Environment
Heroku Environment with the below dependencies
![env](https://user-images.githubusercontent.com/19797552/129572032-fa91b1fb-1306-4baf-b014-7209894b3f2a.PNG)

**Comment by vfonic** [comment]
Can you try it again, but first open `heroku logs -t --app onecartzim` and there you can get a more detailed error message.

You can also try creating admin user again like this:

```shell
heroku run rake spree_auth:admin:create --app onecartzim
```

**Comment by damianlegawiec** [comment]
Thanks for reporting, the issue is resolved, you will need to however create a new app with the heroku button

**Comment by faraimupfuti** [comment]
Thanks alot.....

I re-deployed the app...and it worked. I now have access to the admin panel
