### ISSUE TITLE
Might be dependencies issue with Rails 6.1.4.1

### ISSUE THREAD

**Issue by tzoro** [spree/spree#11294]
Rails 6.1.4.1, install from rails app cant install. Bit mixing of gems produced this:
![Screen Shot 2021-08-29 at 7 31 58 PM](https://user-images.githubusercontent.com/941998/131258082-054aee88-2f04-4d93-b971-2d501b520f5e.png)

**Comment by damianlegawiec** [comment]
`bundle update` will solve that issue

**Comment by tzoro** [comment]
Yes. Thank you!
