### ISSUE TITLE
Extract API v1 into `spree_api_v1` gem

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#11314]
As we're moving the Admin Panel to Platform API, we're abandoning any feature development of the API v1 which will be completely superseded by Platform API.

Our plan is to extract API v1 into its separate gem `spree_api_v1`, so anyone still using that API will be able to do so.

**Comment by mrbrdo** [comment]
@damianlegawiec so where is `spree_api_v1`?

**Comment by damianlegawiec** [comment]
@rafalcymerys we need to set up that API v1 as a separate gem for backwards compatibility

**Comment by rafalcymerys** [comment]
This is now done in https://github.com/spree/spree_api_v1 repo!
