### ISSUE TITLE
ArgumentError (wrong number of arguments (given 1, expected 0)) on .display_total caused by display_money.rb concern

### ISSUE THREAD

**Issue by mdavo6** [spree/spree#11326]
**Context**
I have recently updated from Spree 4.2.5 to Spree 4.3.0.rc3.

**Expected Behavior**
Load admin orders page successfully.

**Actual Behavior**
I am unable to load the admin orders page on login, due to the following error:
`ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):`

I have tracked this down to the following line:
`<td><%= order.display_total.to_html %></td>`

Indeed, this appears to be a wider issue related to the money_methods method in the `Spree::DisplayMoney` concern, as calling:
`Spree::Order.last.display_total`
in the rails console raises the following:
`ArgumentError (wrong number of arguments (given 1, expected 0))`

**Possible Fix**
The issue appears to have been introduced in #11208 , as reverting back to the Spree::DisplayMoney concern in Spree 4.2.5 resolves the issue.

**Your Environment**
Spree 4.3.0.rc3
Ruby 2.6.7
Rails 6.0.3

Thanks again team!

**Comment by damianlegawiec** [comment]
Hmm, this is indeed the case in Ruby < 2.7, moving to 2.7 or 3.0 resolves this issue
