### ISSUE TITLE
PG::NotNullViolation: ERROR:  column "created_at" contains null values running migrations

### ISSUE THREAD

**Issue by mdavo6** [spree/spree#11325]
**Context**
Upgrading from Spree 4.2.5 to Spree 4.3.0.rc3 following recommended approach.
Running migrations after installation using 
`bin/rails db:migrate`

**Expected Behavior**
Successfully run migrations

**Actual Behavior**
'PG::NotNullViolation: ERROR:  column "created_at" contains null values' error

**Possible Fix**
Update line 9 of the CreateSpreeProductsStores migration, to add a default time.
For example, change
`add_timestamps :spree_products_stores`
to 
`add_timestamps :spree_products_stores, default: Time.current`

This resolved the issue for me, and migrations were able to run successfully.

**Steps to Reproduce**
As noted above, upgrade from Spree 4.2.5 to Spree 4.3.0.rc3 following recommended approach: https://dev-docs.spreecommerce.org/upgrades/upgrades/fout-dot-two-to-four-dot-three

**Your Environment**
Spree 4.3.0.rc3
Ruby 2.6.7
Rails 6.0.3

Thanks for the great work guys!

**Comment by damianlegawiec** [comment]
Hey @mdavo6 thanks for reporting this!

1. could you create a PR with that fix?
2. What DB engine are you using?

**Comment by mdavo6** [comment]
Sure @damianlegawiec . I have just submitted the PR above. 

I could not see the relevant line on the main branch. Seems there has been a change to the migrations during the "squash", so I have submitted the PR based on the v4.3.0 branch.

Using Postgres.

**Comment by albertoalmagro** [comment]
This happened to me because of `insert_all` not having `created_at` values. I fixed it by changing:

```ruby
Spree::StoreProduct.insert_all(records)
```
with:
```ruby
records.each do |record|
  Spree::StoreProduct.create!(record)
end
```

**Comment by albertoalmagro** [comment]
Added pull request #11595 for branch `4-3-stable`. The `main` branch looks good to me already.
