### ISSUE TITLE
Simply following installation instructions not working

### ISSUE THREAD

**Issue by papiro** [spree/spree#11480]
Following the instructions at https://dev-docs.spreecommerce.org/getting-started/installation, I get to the part about "Logging into the admin panel" and there is no server running at `http://localhost:3000/admin`. I am guessing there is a step which starts up such a server but why isn't it mentioned in "Installation"?

## Expected Behavior
I would expect to be able to visit `http://localhost:3000/admin` successfully after following the previous installation steps.

**Comment by damianlegawiec** [comment]
Thanks for reporting, this is a typo in the docs.

You need to use `http://localhost:4000/admin` URL, port `4000`, not `3000`
