### ISSUE TITLE
installation from starter kit with docker

### ISSUE THREAD

**Issue by zimmerx** [spree/spree#11559]
Hi, 
I'm having issue with installation. 
When I run command bin/setup 

after some time I'm getting this error: 

```
 => ERROR [ 7/10] RUN yarn install                                         1.1s
------                                                                          
 > [ 7/10] RUN yarn install:
#12 0.926 /bin/sh: 1: yarn: not found
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn install]: exit code: 127
```

I'm on MacOS BigSur with Docker client.

**Comment by damianlegawiec** [comment]
@zimmerx thanks for bringing that to our attention - this is now fix, please re-download new spree_starter version and it will work

**Comment by zimmerx** [comment]
Million thanks @damianlegawiec  Can confirm that issue resolved :)
