### ISSUE TITLE
Milestones for 4.4 Release

### ISSUE THREAD

**Issue by joeytheman** [spree/spree#11612]
Do you have a list of tasks that are necessary for completion in order to release 4.4.0? 

The current release is missing endpoints supported by latest version of the javascript SDK ( https://github.com/spree/spree-storefront-api-v2-js-sdk/tree/v5.1.2 )

**Comment by damianlegawiec** [comment]
Hey @joeytheman 

v4.4 release is finalized, no new features will be added to that release.

What API endpoints do you have in mind?

**Comment by joeytheman** [comment]
The addPayments endpoint. Do you have an eta for releasing the a non-rc release on rubygems?

**Comment by damianlegawiec** [comment]
Hey @joeytheman 

The final release is happening tomorrow 🚀

**Comment by joeytheman** [comment]
I look forward to it. Thanks!

**Comment by damianlegawiec** [comment]
@joeytheman 4.4 is live!
