### ISSUE TITLE
SPREE sample not loading images

### ISSUE THREAD

**Issue by abbasahmad** [spree/spree#11671]
## Context

When doing the  "bundle exec rake spree_sample:load" the taxonomies and taxon load good with all the items. But i get no images. See the picture below:
![Capture d’écran 2022-03-30 160840](https://user-images.githubusercontent.com/8807863/160925152-41648086-d414-43eb-b062-f9c185a33ff3.png)

## Expected Behavior

The images should be loaded. 
## Actual Behavior

No images are loaded in the database and we get a frontend with no pictures as you can see in the next.js front end example: 
![image](https://user-images.githubusercontent.com/8807863/160925465-65cfa2ef-2f3c-4028-9258-f6fe7c12c7ed.png)

## Possible Fix

Maybe the pictures are not free of use ? then we should sugest modify the sample data pictures to free use images. i can help with that if this is the case (Provide images). As a matter of fact i need the demo with pictures. so if not present i will need to fetch from internet licence free picture to include in demo. 
## Steps to Reproduce

1. clone spree starter repo (on windows)
2. Setup the docker-compose with the setup file : FOR WINDOWS
Delete the coresponding files + copy rename : rm -rf .env && cp -f .env.sample .env
docker-compose pull
docker-compose build web
docker-compose run --rm web bash -c "bin/wait-for-services && (bundle check || bundle install) && bundle exec rails db:drop && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rake spree_sample:load && rm -rf tmp/latest.dump"
docker-compose up
3. Everything works but no images in items. 

## Your Environment

* Version used: Latest spree starter
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/abbasahmad/49bd631e7462ff0066387d95e9878a66
* Any relevant stack traces ("Full trace" preferred):

**Comment by abbasahmad** [comment]
Nothing on this ? No one has this issue ? No one can replicate ?

**Comment by abbasahmad** [comment]
Hello ?

**Comment by MateoLa** [comment]
Is not a bug. Images are not longer loaded through the Sample

**Comment by abbasahmad** [comment]
@MateoLa Thanks for the info. So my logical follow up question is : How are images loaded now ?

**Comment by ryanmk54** [comment]
Related issue: https://github.com/spree/spree/issues/10865
