### ISSUE TITLE
OrderMerger merges other order but does not destroy it, causing cart bugs

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree#11682]
`set_current_order` which is called for example in OrdersController (frontend), will attempt to merge all incomplete orders of current user.
https://github.com/spree/spree/blob/7a5b20d466a648152c806cd651a198a6f5e19884/core/lib/spree/core/controller_helpers/order.rb#L65
However the merger does not check if destroy of the other order was successful or not:
https://github.com/spree/spree/blob/7a5b20d466a648152c806cd651a198a6f5e19884/core/app/models/spree/order_merger.rb#L23

This causes the other order line items to be merged into current order every time `set_current_order` is called, while the other order is not destroyed - meaning the cart contents just randomly get changed. For example the user cannot anymore decrease the quantity of any line item present the other order, as it keeps getting added every time the user tries to decrease the quantity.

One reason why destroy can fail is (I guess another bug by itself) `dependent: :destroy` on `bill_address` and `ship_address`. If the same address is assigned to the User himself (as default), it can't be destroyed and `other_order.destroy` fails.

**Comment by damianlegawiec** [comment]
This was fixed via https://github.com/spree/spree/pull/12082
