### ISSUE TITLE
Do not require ruby-vips explicitly

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree#11707]
This should be left to the Rails project, as it should be up to the user to decide weather to use vips or image_magick, which are both supported by image_processing.

https://github.com/spree/spree/blob/main/core/lib/spree/core.rb#L17

When ruby-vips is `require`d, it will look for the native library (so/dll/...), and if not present, there will be a runtime exception. This means it is now necessary to install libvips just to run spree, even if you are not using it. libvips and dependencies are 500+ MB on Debian.

**Comment by rafalcymerys** [comment]
Hi @mrbrdo I think this makes sense in general, we'll just need to make sure that the spree_starter project includes at least one of them :)
