### ISSUE TITLE
Custom Spree.user_class of `User` does not escape `Spree::User` namespace in some contexts

### ISSUE THREAD

**Issue by dylanfisher** [spree/spree#11731]
I'm working on an app that users a custom user class `User` and follows the [authentication guide](https://dev-docs.spreecommerce.org/customization/authentication) to set this up.

I have this line in `spree.rb`: `Spree.user_class = "User"`

Everything seems to work find until I try to manually reference an order's user from the console. The `spree_users` table is loaded instead of my custom `users` table.

```ruby
[1] pry(main)> Spree::Order.last.user
  Spree::Order Load (1.9ms)  SELECT "spree_orders".* FROM "spree_orders" ORDER BY "spree_orders"."id" DESC LIMIT $1  [["LIMIT", 1]]
  Spree::Preference Load (0.4ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/auth_configuration/confirmable"], ["LIMIT", 1]]
  Spree::Preference Load (0.3ms)  SELECT "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/auth_configuration/validatable"], ["LIMIT", 1]]
  Spree::User Load (0.8ms)  SELECT "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
=> nil
```

If I make a change in `Spree::Order` and instead define the `belongs_to` association like this, breaking out of the namespace, the correct `Spree.user_class` is loaded:

```ruby
if Spree.user_class
  belongs_to :user, class_name: "::#{Spree.user_class.to_s}", optional: true
else
  belongs_to :user, optional: true
end
```

```ruby
[1] pry(main)> Spree::Order.last.user
  Spree::Order Load (4.2ms)  SELECT "spree_orders".* FROM "spree_orders" ORDER BY "spree_orders"."id" DESC LIMIT $1  [["LIMIT", 1]]
  User Load (1.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 14], ["LIMIT", 1]]
=> #<User id: 14, email: "test@gmail.com", first_name: nil, last_name: nil, slug: nil, created_at: "2022-07-16 13:12:52.629476000 -0400", updated_at: "2022-07-16 13:28:07.910989000 -0400", spree_api_key: nil, ship_address_id: nil, bill_address_id: nil, settings: nil>
```

Is this something that is easily repeatable on your end? Does it make sense to make this change to avoid the incorrect class getting loaded?

## Environment

```ruby
ruby "3.0.4"

gem "rails", "~> 6.1"

gem "spree", "~> 4.4"
gem "spree_frontend", "~> 4.4.0"
gem "spree_backend"
gem "spree_emails"
gem "spree_gateway", "~> 3.9"
gem "spree_auth_devise"
```

**Comment by dylanfisher** [comment]
There appears to be one other area of the code that already references the `Spree.user_class` in an association as I suggested: https://github.com/spree/spree/blob/d894358e49b8c3a7f6944e838de7cd92510e31d0/core/app/models/spree/promotion/rules/user.rb#L5

https://github.com/spree/spree/commit/f297ad5d9c3c20149633497fe38a3d954c18f650

Does it make sense to reference the `Spree.user_class` like this in all places that a user reference is specified?

**Comment by damianlegawiec** [comment]
@dylanfisher good catch, I think the way it was handled in https://github.com/spree/spree/commit/f297ad5d9c3c20149633497fe38a3d954c18f650 should be the way to go everywhere, could you prepare a PR with a fix?
