### ISSUE TITLE
Resolve issue with Psych::DisallowedClass on Ruby 3.0 and Rails 7.0

### ISSUE THREAD

**Issue by rafalcymerys** [spree/spree#11735]
When loading YAML files with Ruby 3.0 and Rails 7.0, the application fails because of the following error:

```
Psych::DisallowedClass (Tried to load unspecified class: Symbol)
```

We need to update configuration to allow Symbol, BigDecimal, ActiveSupport::HashWithIndifferentAccess in the configuration files.

**Comment by asecondwill** [comment]
I'm still getting this trying to set up a basic rails demo, 

```
 bin/rake spree_sample:load

Psych::DisallowedClass: Tried to dump unspecified class: Symbol(:dummy_key) (Psych::DisallowedClass)

```

Spree 4.10.1
Rails 7.1.4
Ruby 3.3

**Comment by damianlegawiec** [comment]
> I'm still getting this trying to set up a basic rails demo,
> 
> ```
>  bin/rake spree_sample:load
> 
> Psych::DisallowedClass: Tried to dump unspecified class: Symbol(:dummy_key) (Psych::DisallowedClass)
> ```
> 
> Spree 4.10.1 Rails 7.1.4 Ruby 3.3

hey @asecondwill 

are you using https://github.com/spree/spree_starter ?
