### ISSUE TITLE
Unable to load Spree default page

### ISSUE THREAD

**Issue by blackyzero** [spree/spree#11781]
Hello,

Just fresh install Spree following this instruction here https://dev-docs.spreecommerce.org/advanced/existing_app_tutorial
But i can't get the default Spree page, it always show Rails default page (screenshot)
<img width="1528" alt="Screen Shot 2022-10-16 at 12 53 36 AM" src="https://user-images.githubusercontent.com/4286063/196018894-8bfaf021-34bd-4d0c-b773-944563a0f45f.png">

Console log:
```

root@spree1:/opt/services/spree# ./bin/rails server --binding=0.0.0.0
=> Booting Puma
=> Rails 6.1.7 application starting in development
=> Run `bin/rails server --help` for more startup options
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.0.0-p0) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 8173
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 192.168.168.41 at 2022-10-16 00:59:54 -0400
   (4.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/rvm/gems/ruby-3.0.0/gems/railties-6.1.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/rvm/gems/ruby-3.0.0/gems/railties-6.1.7/lib/rails/templates/rails/welcome/index.html.erb (Duration: 16.2ms | Allocations: 411)
Completed 200 OK in 34ms (Views: 19.3ms | ActiveRecord: 0.0ms | Allocations: 4060)


```

Any idea how could i make it works?
Thank you.

**Comment by rafalcymerys** [comment]
Hi @blackyzero - did you also install `spree_frontend` gem?

**Comment by blackyzero** [comment]
Hi @rafalcymerys 
Yes, this is already installed.
`root@spree1:/opt/services/spree# bin/rails g spree:backend:install
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
Running via Spring preloader in process 8788
   identical  app/javascript/spree-dashboard.js
   identical  vendor/assets/javascripts/spree/backend/all.js
   identical  vendor/assets/stylesheets/spree/backend/all.css
         run  yarn add @spree/dashboard from "."
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@spree/dashboard > stimulus-sortable@3.2.0" has incorrect peer dependency "@rails/request.js@^0.0.5".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @spree/dashboard@0.2.1
info All dependencies
└─ @spree/dashboard@0.2.1
Done in 13.17s.
root@spree1:/opt/services/spree#`

I also tried to reboot the machine, start ruby server, but still getting same issue.

**Comment by blackyzero** [comment]
@rafalcymerys you're right
it was missed frontend, after installed it, i can get the index page.

Thank you.

**Comment by rafalcymerys** [comment]
I'm glad that it helped 🙂
