### ISSUE TITLE
Routing error - uninitialized constant Spree::UserSessionsController

### ISSUE THREAD

**Issue by blackyzero** [spree/spree#11782]
Hello,

I am getting following error when accessing menu /login or /signup

```
Routing error
uninitialized constant Spree::UserSessionsController
```

<img width="1480" alt="Screen Shot 2022-10-16 at 9 55 43 PM" src="https://user-images.githubusercontent.com/4286063/196073080-a76bfd0e-cd05-4be2-afc1-308724b1af96.png">

Console error show as below

```
root@spree1:/opt/services/spree# rails s -b 0.0.0.0
=> Booting Puma
=> Rails 6.1.7 application starting in development
=> Run `bin/rails server --help` for more startup options
[WARN] FriendlyId::Slug is calling acts_as_paranoid more than once!
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.0.0-p0) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 4302
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop

Started GET "/login" for 192.168.168.41 at 2022-10-16 21:56:44 -0400

ActionController::RoutingError (uninitialized constant Spree::UserSessionsController):

```

The product pages and admin page can show properly.

What could be the issue? Thank you.

**Comment by navaneethkp36** [comment]
hi, @blackyzero I would like to contribute to this.

**Comment by blackyzero** [comment]
I found this who has same error, but it doesn’t work for me

https://stackoverflow.com/questions/24885793/spree-uninitialized-constant-spreeusersessionscontroller

Anyone has idea to fix this issue. 
Thank you.

**Comment by blackyzero** [comment]
It works now after move the "gem 'spree_frontend'" below "gem 'spree'

but i hit another issue, the menu doesn't show when click on user icon, it only shows empty box (screenshot),

Anyone has idea how to fix it? Thank you.
![Screen Shot 2022-10-18 at 2 36 39 PM](https://user-images.githubusercontent.com/4286063/196516196-0ec7a642-ac6d-43fc-89d9-850fc4e584ee.png)

**Comment by rafalcymerys** [comment]
For future reference, the README for spree_rails_frontend provides steps to fix such issues (related to recompiling the frontend javascript bundle): https://github.com/spree/spree_rails_frontend#disabled-add-to-cart-button-issue
