### ISSUE TITLE
Support docker compose plugin

### ISSUE THREAD

**Issue by dnk8n** [spree/spree#11826]
**Is your feature request related to a problem? Please describe.**
My system does not have `docker-compose` as a recent docker is installed, it is now `docker compose` (no hyphen)

**Describe the solution you'd like**
Allow install CLI to work, use `docker compose version` to run version check if `docker-compose version` fails.

```
$ docker compose version
Docker Compose version v2.14.1
```

**Describe alternatives you've considered**
I tried making an alias or a scrip `exec docker compose "$@"` but that does not work as expected.

**Additional context**

**Comment by dnk8n** [comment]
See https://docs.docker.com/compose/install/linux/ for details on current compose installation procedure

**Comment by rafalcymerys** [comment]
@dnk8n Ive just pushed a change to spree_cli, to use the new docker compose syntax. Could you please download the latest version (1.2.0) and let me know if that fixed the issue for you?
