### ISSUE TITLE
Image not display from rails active storage

### ISSUE THREAD

**Issue by buithehien1991** [spree/spree#11853]
I tried upload logo on local environment, but it always not display

![image](https://user-images.githubusercontent.com/577666/219937467-471d2b4c-b8cf-45a8-9224-cd504d0f64bd.png)

Also not display on frontend
![image](https://user-images.githubusercontent.com/577666/219937497-c8f093ac-ec78-4508-8be1-74044940c4c2.png)

Here is error from console. I used rails 7 and ruby 3.2 as setup from starter.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/577666/219937538-466e0d86-63c4-4ac2-9501-b12b25cc46e0.png">

It seemly error from active storage. I also checked file on my_app/storage and database record. Everything is OK
<img width="426" alt="image" src="https://user-images.githubusercontent.com/577666/219937648-5fefbf31-ae2b-42f3-959e-7d1cf0405f52.png">
<img width="681" alt="image" src="https://user-images.githubusercontent.com/577666/219937669-324d42c5-d694-4513-b5d4-ab2cfee766f5.png">

I found the url can work with image is
```
http://localhost:4000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d197229dceca55628178ff432e67bb242b7850d1/logo-tda.png
```

That mean replace `representations` by `blobs`. Image can be work. 

I also installed vips and mini_magick on my pc. It's normal 

Please help me resolve it. Thank you so much

**Comment by buithehien1991** [comment]
It's so magic

I change from vips to image_magic. And everything work

From
```
Rails.application.config.active_storage.variant_processor = :vips
```
To 
```
Rails.application.config.active_storage.variant_processor = :mini_magick
```

**Comment by VuQuoc18** [comment]
Thanks, it's helping me alot 🙏

**Comment by JeromeRiffier** [comment]
@buithehien1991 Thank you, this was driving me crazy.

**Comment by zavan** [comment]
This seems to still be an issue as the starter template uses vips by default. It should be reopened.
