### ISSUE TITLE
Mysql2::Error: Can't DROP INDEX 

### ISSUE THREAD

**Issue by akillar** [spree/spree#11890]
hello,
i'm getting this error when running the migration command.

Mysql2::Error: Can't DROP INDEX `stock_item_by_loc_var_id_deleted_at`; check that it exists

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP INDEX `stock_item_by_loc_var_id_deleted_at`; check that it exists

## Your Environment
------
rails version = 7.0.4.3
spree version 4.5.3
nginx + systemd service unit
mariadb  Ver 15.1 Distrib 10.6.13-MariaDB

it is a fresh installation. any help is greatly appreciated.

**Comment by nicksterious** [comment]
FYI that is only the first error you'll run into while trying to use Mysql. There are others that will pop up later. Might as well use PG.

**Comment by rafalcymerys** [comment]
@nicksterious @akillar could you share the full stack trace and the exact migration that throws this error?

**Comment by damianlegawiec** [comment]
This was fixed via https://github.com/spree/spree/commit/0e03446377fef1f57b183a3841fba6c9a3e4888e#diff-a2e95e1511d8ecfe6d424415526c57e8a574fa6fca3ffaf4c3fd64233e07b502
