### ISSUE TITLE
Can't add new preference with rails 7 app from a gem

### ISSUE THREAD

**Issue by lethunder** [spree/spree#11905]
## Context

I customize spree address auto complete gem to make it work with my rails 7 app. It was outdated.
this gem needs to add a new preference to app configuration

`module Spree::AppConfigurationDecorator
  def self.prepended(base)
    base.preference :google_maps_api_key, :string
  end
end
::Spree::AppConfiguration.prepend(Spree::AppConfigurationDecorator)`

## Expected Behavior

It should add preference

## Actual Behavior

It raises error 
 uninitialized constant Spree::AppConfiguration 
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: spree 4.5.1, Rails 7.0.4.1
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by rafalcymerys** [comment]
Hi @lethunder - do you have any stack trace of this? I'm wondering if that's a matter of changes in Spree, or in Rails 7 autoloader

**Comment by lethunder** [comment]
Hey @rafalcymerys i went through  spree doc to create plugin. I transfer old plugin code to new one and everything works now. Thanks

**Comment by rafalcymerys** [comment]
Great :)
