### ISSUE TITLE
Sample data load error

### ISSUE THREAD

**Issue by dtdionne** [spree/spree#11915]
[rails@rails-01 SpreeSSH2]$ rake spree_sample:load --trace
.
.
Loaded Variants samples
rake aborted!
NoMethodError: undefined method `size' for nil:NilClass
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:46:in `concise_options'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/abstract/schema_definitions.rb:27:in `initialize'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:44:in `new'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:44:in `block in indexes'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/result.rb:69:in `each'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/result.rb:69:in `each'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:9:in `filter_map'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:9:in `indexes'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/schema_cache.rb:137:in `block in indexes'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/schema_cache.rb:135:in `fetch'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/connection_adapters/schema_cache.rb:135:in `indexes'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/insert_all.rb:129:in `unique_indexes'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/insert_all.rb:119:in `find_unique_index_for'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/insert_all.rb:31:in `initialize'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/persistence.rb:146:in `new'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/persistence.rb:146:in `insert_all'
(eval):6:in `block in insert_all'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:881:in `_scoping'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/relation.rb:428:in `scoping'
(eval):6:in `insert_all'
/usr/local/share/gems/gems/activerecord-7.0.7.2/lib/active_record/associations/collection_proxy.rb:1114:in `insert_all'
/usr/share/gems/gems/spree_core-4.6.1/app/services/spree/stock_locations/stock_items/create.rb:19:in `call'
/usr/share/gems/gems/spree_core-4.6.1/lib/spree/service_module.rb:51:in `call'
/usr/share/gems/gems/spree_core-4.6.1/lib/spree/service_module.rb:5:in `call'
/usr/share/gems/gems/spree_sample-4.6.1/db/samples/stock.rb:14:in `<main>'
/usr/share/gems/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/gems/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/share/gems/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
/usr/share/gems/gems/spree_sample-4.6.1/lib/spree/sample.rb:13:in `load_sample'
/usr/share/gems/gems/spree_sample-4.6.1/lib/spree_sample.rb:27:in `load_samples'
/usr/share/gems/gems/spree_sample-4.6.1/lib/tasks/sample.rake:20:in `block (2 levels) in <main>'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/share/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:25:in `load'
/usr/local/bin/rake:25:in `<main>'
Tasks: TOP => spree_sample:load
[rails@rails-01 SpreeSSH2]$

**Comment by rafalcymerys** [comment]
Hi @dtdionne could you provide some more details regarding the stack that you use (the specific version of Spree, Rails, what type of SQL database etc.)?

**Comment by dtdionne** [comment]
It's a brand new centos 9 vm.  Totally fresh stock install and I followed the spreed dev docs on how to add spree to an existing application.

It couldn't have been a more sterile, pristine installation env.  I struggled for hours before switching to solidus which took about 9 min to get up and running.
