### ISSUE TITLE
Error on linux: bash: line 2: bin/wait-for-services: No such file or directory

### ISSUE THREAD

**Issue by artoodeeto** [spree/spree#11931]
## Context

Im trying to run spree. This is a fresh install. but when i try to run `bin/docker-setup` it throws this error `bash: line 2: bin/wait-for-services: No such file or directory`

I also tried a fresh install on mac and get no error. I can run and login as an admin

## Expected Behavior

Complete the setup, install all gems and run migrations

## Actual Behavior

actual error:
```
➜ bin/setup-docker
[+] Running 2/0
 ✔ Container dentca-spree-latest-redis-1     Running                                                                                                                                     0.0s 
 ✔ Container dentca-spree-latest-postgres-1  Running                                                                                                                                     0.0s 
Connection to 127.0.0.1 5432 port [tcp/postgresql] succeeded!
PostgreSQL is up and running!
[+] Creating 2/0
 ✔ Container dentca-spree-latest-redis-1     Running                                                                                                                                     0.0s 
 ✔ Container dentca-spree-latest-postgres-1  Running                                                                                                                                     0.0s 
bash: line 2: bin/wait-for-services: No such file or directory

```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
```
# Spree gems
gem 'spree', '~> 4.6'
gem 'spree_sample', '~> 4.6'
gem 'spree_emails', '~> 4.6'
gem 'spree_backend', '~> 4.6'
gem 'spree_gateway', '~> 3.10'
gem 'spree_auth_devise', '~> 4.5'
gem 'spree_i18n', '~> 5.3'
gem 'spree_dev_tools', require: false, group: %w[test development]
```
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

OS env:

```
OS: Pop!_OS 19.10 x86_64 
Kernel: 5.3.0-7629-generic 
Uptime: 2 days, 5 hours, 57 mins 
Packages: 2369 (dpkg), 8 (snap) 
Shell: zsh 5.7.1 
Resolution: 1920x1200, 1920x1200, 1920x1200 
DE: GNOME 3.34.3 
WM: GNOME Shell 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-4820K (8) @ 3.900GHz 
GPU: AMD ATI Radeon R9 290X/390X 
Memory: 4718MiB / 15953MiB 
```

**Comment by rafalcymerys** [comment]
@artoodeeto is `bin/wait-for-services` present in your setup? 
Or if you change https://github.com/spree/spree_starter/blob/main/bin/setup-docker#L12 this line to `/app/bin/wait-for-services`, does it fix it?

**Comment by artoodeeto** [comment]
Hello, Thank you so much. i think this works. I have just have to keep changing this when using MacOs, I have linux for work. But thank you. postgres is running. But the web server couldn't. I have this error. 

`Could not locate Gemfile or .bundle/ directory` not sure where to change this. Thank you.
