### ISSUE TITLE
custom domain

### ISSUE THREAD

**Issue by obaviet** [spree/spree#11939]
Hello
I intend to create a marketplace with multiple vendors, each of which will be able to use their domain name. I have read the documentation but don't see how this can be done. I mean each provider just needs to point their domain name, the admin doesn't have to do anything behind that.

**Comment by arvind4501** [comment]
Hi @obaviet you can use the apartment gem [https://github.com/rails-on-services/apartment](url) . it can solve your problem, go through it, if you face any issue feel free to discuss.
