### ISSUE TITLE
DEPRECATION WARNING: `currency` is deprecated.

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree#11985]
The "currency" and "admin_path" settings were deprecated in this commit:
https://github.com/spree/spree/commit/c8304d04d46940e8d391ccc6af79e5d1c039c8cc

But there is no explanation what they are replaced with or what should be used now. admin_path is still used in in the Rails frontend and I don't see any indication of a "newer" equivalent.

@damianlegawiec might know?

**Comment by rafalcymerys** [comment]
Hi @mrbrdo , the currency preference is now defined per `Spree::Store`, whereas the admin_path preference has been moved to spree_backend configuration: lib/spree/backend/configuration.rb

**Comment by mrbrdo** [comment]
Thanks, I will check it later but I think this answers my question so closing.
(although it would be nice to have a note about this in the Upgrading guide or in the warning text, unless I missed it)
