### ISSUE TITLE
Same Taxonomies in different stores

### ISSUE THREAD

**Issue by chuckyuee** [spree/spree#12019]
## Context
Same Taxonomies in different stores, rails raise an error:

ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_permalink_per_locale"
DETAIL:  Key (locale, permalink)=(en, categories) already exists.
):

Default store has a taxonomy named 'Categories', change to other store again create a taxonomy named 'Categories', then raise an error like above. These store are same locale 'en' but different currency and VAT rules.

## Expected Behavior
Different stores had same Taxonomies.

## Actual Behavior
Server error 500

## Possible Fix
Maybe taxonomies can apply to all stores.

## Steps to Reproduce
1. Create a taxonomy in default store named 'Categories'
2. Change to other store, same locale different currency and VAT zone, like US and UK country
3. Again Create a taxonomy in default store named 'Categories'

## Your Environment
4.8.0.Beta

**Comment by damianlegawiec** [comment]
Thanks for reporting, I see this DB migration is to blame:

https://github.com/spree/spree/blob/d3927a3f646f0b4e72b137bf72606c885ec59829/core/db/migrate/20230514162157_add_index_on_locale_and_permalink_to_spree_taxons.rb#L3

this should be a combined index on`permalink`, `locale, `parent_id` and `taxonomy_id`

**Comment by pkatek** [comment]
We are creating a shop for a client and there is a big problem with taxonomies.
We have a product store and there are products intended for the Slovak market, others for the Czech market and still others for the German market, and there are common products. Now, if we want to separate products using stores, we must have separate taxa, although they are already assigned and I do not see the need to separate them, and if I change/add new ones or items only for the German language, the names of the taxa are not visible in the rest of the products and this can be standardized. Is it possible to quickly fix this error? I wouldn't want the client to change the platform or wonder why there is a loophole in this topic.

Do you have another idea to solve the problem mentioned in this thread?

**Comment by pkatek** [comment]
@damianlegawiec I am definitely in favor of taxonomies being applied to all stores. Then the products will not show errors or holes in their names after changing the store.

**Comment by chuckyuee** [comment]
> Thanks for reporting, I see this DB migration is to blame:
> 
> https://github.com/spree/spree/blob/d3927a3f646f0b4e72b137bf72606c885ec59829/core/db/migrate/20230514162157_add_index_on_locale_and_permalink_to_spree_taxons.rb#L3
> 
> this should be a combined index on`permalink`, `locale, `parent_id`and`taxonomy_id`

Why need to translate permalink field?

**Comment by chuckyuee** [comment]
> Thanks for reporting, I see this DB migration is to blame:
> 
> https://github.com/spree/spree/blob/d3927a3f646f0b4e72b137bf72606c885ec59829/core/db/migrate/20230514162157_add_index_on_locale_and_permalink_to_spree_taxons.rb#L3
> 
> this should be a combined index on`permalink`, `locale, `parent_id`and`taxonomy_id`

`parent_id` and `taxonomy_id` not in table `spree_taxon_translations`. This table only store for mobility's translate column content. Can I remove this unique constraint?

**Comment by pkatek** [comment]
Please, do it xD i need this for my Client.

**Comment by pkatek** [comment]
@damianlegawiec  What are the possibilities for a fix to be released soon?

**Comment by damianlegawiec** [comment]
> @damianlegawiec What are the possibilities for a fix to be released soon?

we're planning to fix this with v4.8 releasing this week/early next week, we're also reviewing other translation migrations

**Comment by pkatek** [comment]
Hello!

What are our chances of completing this task?

**Comment by chuckyuee** [comment]
It's awesome! Has been successfully updated to the latest version.
