### ISSUE TITLE
Edit taxonomy error

### ISSUE THREAD

**Issue by chuckyuee** [spree/spree#12048]
## Context

http://localhost:3000/admin/taxonomies/1/taxons/1/edit

![截屏2024-05-29 12 25 00](https://github.com/spree/spree/assets/161027936/fac92442-0a63-47d3-835b-760404127447)

## Steps to Reproduce

1. Create new taxonomy
2. Then edit this row
3. Edit taxonomy
4. Ruby raise error @taxon.permalink is nil

## Your Environment

* Version used: 4.8.1

**Comment by damianlegawiec** [comment]
v4.8.2 has a fix for this @chuckyuee
