### ISSUE TITLE
Translation error after updating from 4.7 to 4.8.1

### ISSUE THREAD

**Issue by pkatek** [spree/spree#12047]
## Context
I am reporting an error in the application after updating to 4.8.1. 
By default, my language is set to English (US).
And there are the following errors: 

1. Products incorrectly interpret the default store language in an existing store with several language versions.
2. Translations from the default language are not loaded in the store configuration. In the console in Spree::Store.first.translations there are correct translations for the "en" and other languages. 

s = Spree::Store.first.
In the console: 
irb(main):016> s.seo_title_en
=> nil
irb(main):017> s.seo_title_cs
=> "Vylepšete svůj styl s YES: Nádherné šperky pro každou příležitost."

Translations are indicated in s.translations, everything worked fine before the update. 
After the update, should I do any additional rake task migrations or anything else apart from the basic ones?

**Comment by damianlegawiec** [comment]
Hey @pkatek 

In your spree initializer please set:

```ruby
Spree::RuntimeConfig.always_use_translations = true
```

I've missed this one in the upgrade guide if you're upgrading from 4.7, will add it shortly

**Comment by pkatek** [comment]
Thanks!

**Comment by pkatek** [comment]
In intializer i have 
Spree::RuntimeConfig.always_use_translations = true
And in rails console 

3.2.2 :001 > Spree::RuntimeConfig.always_use_translations
 => true 
 
 But in spree admin I don't have translations. 

<img width="1783" alt="Zrzut ekranu 2024-05-28 o 12 16 38" src="https://github.com/spree/spree/assets/7334927/0ac8b84f-7fe0-4658-b003-f395350ff357">

**Comment by pkatek** [comment]
When I switch to another store that uses only one language (CS), everything is fine.

**Comment by pkatek** [comment]
When I enter the values and change the default language, an entry like this is made in Store translations @damianlegawiec 


` #<Spree::Store::Translation:0x00007fb1df55ac88
  id: 6,
  name: "a",
  meta_description: nil,
  meta_keywords: nil,
  seo_title: nil,
  facebook: nil,
  twitter: nil,
  instagram: nil,
  customer_support_email: nil,
  description: nil,
  address: nil,
  contact_phone: nil,
  new_order_notifications_email: nil,
  locale: "EN",
  spree_store_id: 2,
  created_at: Tue, 27 Feb 2024 12:15:07.499612000 UTC +00:00,
  updated_at: Tue, 27 Feb 2024 12:15:07.499612000 UTC +00:00,
  deleted_at: nil>]`

**Comment by chuckyuee** [comment]
@pkatek I manually copied the default locale from the translation table to the main table and remove then.

**Comment by pkatek** [comment]
Translating the store is the least of the problems, it's the same with all translations, products, taxonomies, variants, keys in properties. And if I have 7,000 products and a lot of other parameters, I wouldn't want to do anything manually.Wiadomość napisana przez CHUCKYUEE ***@***.***> w dniu 29.05.2024, o godz. 02:40:﻿
@pkatek I manually copied the default locale from the translation table to the main table and remove then.

**Comment by chuckyuee** [comment]
Because Mobility plugin column_fallback default locale content was store main table, other locale store in translation table. If you use default locale :en, only in form to change it. other language can be use translate form to change. 

So I use this migration code at core/db/migrate/20230117121303_transfer_taxonomy_data_to_translatable_tables.rb:

```
Spree::TranslationMigrations.new(Spree::Taxonomy, 'en').revert_translation_data_transfer
```

**Comment by damianlegawiec** [comment]
@pkatek @chuckyuee please upgrade to v4.8.2

**Comment by pkatek** [comment]
Now it works great! Thanks!
