### ISSUE TITLE
Docker build throws an error

### ISSUE THREAD

**Issue by Gursehaj** [spree/spree#12109]
I get the following error when I run docker build -t name:tag .

 > [build 3/6] RUN bundle install &&     rm -rf ~/.bundle/ "/usr/local/bundle"/ruby/*/cache "/usr/local/bundle"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile:
0.421
0.421 [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby-version. Bundler cannot continue.
0.421
0.421  #  from /rails/Gemfile:3
0.421  #  -------------------------------------------
0.421  #
0.421  >  ruby File.read('.ruby-version').strip.to_s
0.421  #
0.421  #  -------------------------------------------

I am using WSL2 on windows. I did try to run File.read() in irb and it works.

**Comment by damianlegawiec** [comment]
@Gursehaj which Dockerfile are you using? The one from spree starter? https://github.com/spree/spree_starter/blob/main/Dockerfile

**Comment by Gursehaj** [comment]
Yes, the issue is in Gemfile. WSL is not able read the file .ruby-version. If I hard code the value of ruby, it works but then it fails later with some other relative path. I feel either I missed something while setting up WSL or WSL is not able to map the drive correctly.

**Comment by damianlegawiec** [comment]
> Yes, the issue is in Gemfile. WSL is not able read the file .ruby-version. If I hard code the value of ruby, it works but then it fails later for some other relative path. I feel either I missed something while setting up WSL or WSL is not able to map the drive correctly.

thanks for reporting, indeed there are issues with the docker build, I'm working on fixing them

**Comment by damianlegawiec** [comment]
hey @Gursehaj 

Docker issues are fixed now!

**Comment by Gursehaj** [comment]
Perfect, will give it a try!
