### ISSUE TITLE
How to enable different payment method with stripe payment gateway.

### ISSUE THREAD

**Issue by EdisonNetcon** [spree/spree#12252]
As I am referring official document (https://spreecommerce.org/integrations/stripe-integration-with-spree/) it says admin can choose payment type.

> Search ‘Stripe’ in Providers drop down and select Spree :: :: Gateway StripeGateway.
> 
> In the next steps you will be asked to:
> 
> **Choose payment method name that will be displayed to your customers e.g. Credit Card**
> Set display value, whether you want the payment method to appear on the front-end or the back-end of your store, or both.
> Choose auto capture

But for me `Choose payment method name that will be displayed to your customers e.g. Credit Card` did not appear.

![image](https://github.com/user-attachments/assets/926b6839-8627-4871-bedc-c5987a05c256)

I am using Spree version **4.8.3**

Can anyone help me?

**Comment by damianlegawiec** [comment]
That's the `name` field from your screen. 

Also, Spree 5 will have a different, better UI for this:

<img width="1235" alt="Screenshot 2024-12-02 at 10 06 48" src="https://github.com/user-attachments/assets/bd10e181-9933-4c90-98b2-be47d13407ec">
