### ISSUE TITLE
respond_override for OrdersController#populate breaks OrdersController#update

### ISSUE THREAD

**Issue by laurens** [spree/spree#2210]
I want to use a respond_override for displaying a flash message, after an item has been added to the cart.
So I added an orders_controller_decorator.rb with the following line:

`respond_override :populate => { :html => { :success => lambda { redirect_to cart_path, :notice => 'item added' } } }`

This works, however it breaks the update action. When I update the quantity of an item in the cart, the page gets redirected to the order url instead of going back to the cart.

I am on Spree 1.2, Ruby 1.9.2p290

Tested on a fresh spree install including spree_auth_devise

Server Log: https://gist.github.com/4069200

**Comment by JDutil** [comment]
triage:verified
