### ISSUE TITLE
Promotions don't work correctly if they have more than one adjustment

### ISSUE THREAD

**Issue by frankmt** [spree/spree#4295]
I've been trying to setup a promotion in my website that gives free shipping AND a discount, and while it lets me set it up like that in the admin section, it doesn't work as expected during checkout.

I've reproduced the problem in a fresh instance of spree (2.1.4).

Steps to reproduce:
- Create a promotion based on a coupon code
- Add adjustment of type "Free Shipping" to the promotion
- Add adjustment of type "Flat Rate (per order)" to the promotion (I've used 10 USD)
- Add an item to the shopping cart and apply the coupon code in the shopping cart

The system will return a "The previously applied coupon code results in a better deal" message, and only one of the adjustments will be applied.

Looking through the code, it seems like the adjustments are applied in sequence and are considered as separate ones, while (in my understanding) they should be considered together as part of one promotion.

Does anyone have some insight into this?

Thanks for your help

Cheers
Francisco

**Comment by JDutil** [comment]
I think this issue may be resolved by 439c80c0ff28d1fde4087446d961184429c5361f if it's still an issue please open a new one following our contributing guidelines.
