### ISSUE TITLE
Logged in user rule for promotions doesn't update promotion if user signs in after events have fired

### ISSUE THREAD

**Issue by maxfolley** [spree/spree#4555]
For reference, I created a free shipping promotion that used the "Add to cart" event and "Available to only logged in users" rule. It works great if the user is logged in while adding items to the cart. However, if the user logs in after adding items to the cart and immediately proceeds to checkout, the free shipping promotion never gets applied.

I was able to get around it be creating a before filter in the checkout_controller that fires a custom event. I then added that custom event in my promotions decorator and used this event instead of the "Add to cart" event.

This seems to be a very odd caveat with no solution in the current promotion system (correct me if I am wrong). I am on spree 2.1.6.

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this.

**Comment by Mafi88** [comment]
I can't replicate it either.
