### ISSUE TITLE
Payment Profiles Allow Users to Checkout with Deleted Payment Methods

### ISSUE THREAD

**Issue by gmacdougall** [spree/spree#4701]
Steps to reproduce:

1. Spin up a new spree sandbox
2. Login as a user
3. Checkout with the bogus payment method
4. Delete the bogus payment method
5. Checkout again, select Use an existing card on file 

This checkout succeeds, despite the payment method no longer being available

The root cause of this is that the credit card attached to my account has a valid payment profile, and it doesn't validate that the payment_method is still valid, or enabled.

**Comment by nishant-cyro** [comment]
Not able to replicate in master.
