### ISSUE TITLE
2-0-stable Spree::Order statement machine issues

### ISSUE THREAD

**Issue by bbuchalter** [spree/spree#4729]
I'm seeing an issue where any attempts to use "remove_checkout_step" AFTER
using an after_transition to complete will cause those callbacks to not
fire.

Specifically:
```
######
# Must be called BEFORE setting state machine callbacks
self.remove_checkout_step(:address)
self.remove_checkout_step(:delivery)
self.remove_checkout_step(:payment)
######

state_machine.after_transition :to => :complete,
:do => [:create_subscriptions,
:capture_payment, :apply_referral_credits]
```
Gems like spree_store_credits which are initialized *before* my
modifications to the Order's state machine, causes those state machine
callbacks to fail to be triggered. This seems like a fairly major bug.
Hopefully there is a work around?

This seemed like a strange failure so I took a screen capture to
demonstrate the problem. Sorry, it's kind of long, and mostly waiting
around, but it proves the issue.

https://www.youtube.com/watch?v=cWcyPMecxkk&feature=youtu.be

**Comment by priyank-gupta** [comment]
@bbuchalter I can replicate this issue.
A fix is to move `remove_checkout_step :delivery` to `initializers/spree.rb` as `Spree::Order.remove_checkout_step(:delivery)`.

**Comment by priyank-gupta** [comment]
@damianlegawiec @Mafi88 
`Spree::Order` methods like remove_checkout_step etc. can be part of spree.rb as they can be considered as configuration changes.
Not sure if this is an issue. Instead we can update spree doc to replicate this information.
Thoughts ?
