### ISSUE TITLE
migrations for adjustments with Spree::Order as source

### ISSUE THREAD

**Issue by peterberkenbosch** [spree/spree#4732]
Between the upgrade from 1-3-stable to 2-2-stable there can be a situation still where there are `Spree::Adjustment` instances that still have a `Spree::Order` as the `source`. 

```ruby
Spree::Adjustment.where(source_type: "Spree::Order")
```

The `source` needs to be a `Spree::PromotionAction`, or we need to always close this adjustment. 

With `Spree::Order` as source and when the adjustment is open, the [update!](https://github.com/spree/spree/blob/23efd6149f51e4b90ca4b3d331c9c6a631cecda4/core/app/models/spree/adjustment.rb#L76) call is blowing up since there is no more `compute_amount` method on `Spree::Order` anymore.

**Comment by JDutil** [comment]
Closing this out as we're not really supporting these versions anymore, and this is stalled.

**Comment by peterberkenbosch** [comment]
Yeah, "fixed" it backed then with some custom scripts.

**Comment by filipeamoreira** [comment]
I'm running into the same issue OP described. This is a 1-3-stable to 2-3-stable upgrade. 
Can you share an appropriate way to fix this? Thanks. 
/cc @peterberkenbosch @JDutil
