### ISSUE TITLE
"Available On" still available?

### ISSUE THREAD

**Issue by dfreerksen** [spree/spree#4754]
In the Spree admin when adding or editing a product there is a field labeled "Available on." If you do not enter a value, the product does not show in the listing of products or taxons. If you know the slug for the product you can go directly to it, add it to your cart, and check out.

Is this a bug or was this done for a good reason that I'm not aware of? Is it supposed to be a pseudo way of enabling/disabling products?

**Comment by priyank-gupta** [comment]
I can replicate this issue. Working on a fix.
