### ISSUE TITLE
Tax needs to be adjusted if a promo is applied

### ISSUE THREAD

**Issue by dam13n** [spree/spree#4760]
Currently, if an order-wide promotion is applied, taxes reflect the order total before the promotion is applied instead of afterwards!

Seems like this issue was resolved some time ago with Spree, but now that taxes are calculated on line items, the problem is back.

**Comment by PatLeb** [comment]
@dam13n  is right about the order-wide promotion. I've digged a little bit and, I'm sorry, but I don't have time to create a pull request with tests at that time for the correction. Although, there are my findings :
1- promotion adjustments are now calculated per line items which uses the field promo_total to do so
2- promo_total is set by polymorphism
3- when the promotion is of order-wide type, promo_total is set on Order, but not distributed on Line Items
4- the discounted_amount method of the line item uses promo_total to adjust the amount which is always 0.00$

So, what I've done so far as a quick workaround is to override the promo_total accessor and apply only a fraction of the promotion if the promotion is of type Spree::Order.

```ruby
    promotion = order.promotion
    return 0.0 unless promotion
    promo_total = promotion.try(:amount).to_f
    order_total = order.item_total
    return 0.0 unless order_total != 0.0
    (promo_total * amount) / order_total

**Comment by greinacker** [comment]
For what it's worth, I can confirm this is still happening in 2.4, for order-wide promotions.

**Comment by kknd113** [comment]
@PatLeb  Is there any PR on this issue with your solution?

**Comment by PatLeb** [comment]
No, sorry, this is a workaround, not a good fix.

**Comment by Ruxton** [comment]
This is also an issue with line-item promotions.

* Our tax is configured @ 10%, prices include tax
* Our promotion is a bulk discount > 10 = 10% off,  > 20 = 20% off and it's applied to line items.

The email is sent with the following totals:
![](http://puu.sh/j5wnq/fd6f4d11cd.png)

Tracked this down to the default tax calculator https://github.com/spree/spree/blob/master/core/app/models/spree/calculator/default_tax.rb#L30 calculating tax on pre_tax_amount is correct, until there's a promotion applied to the line item.

**Comment by priyank-gupta** [comment]
Discussion on https://github.com/spree/spree/issues/4709.

**Comment by jochemsiegel** [comment]
This still seems to be an issue, even on 3.1. 
When i apply an order level promotion to an order, the taxes are still based on the amount of the order before the order had its promotion applied. 
Or am i missing something?

**Comment by danielricecodes** [comment]
Just left [a comment](https://github.com/spree/spree/issues/4709#issuecomment-406616714) in #4709.  It looks like the Tax calculator does not incorporate promotions?

<img width="898" alt="spree_administration__orders" src="https://user-images.githubusercontent.com/169038/43008082-1e039e6c-8c08-11e8-8059-f8f444c280d1.png">

The tax in my example should be $40.50, but its taxing the shipping - which is free.  You can see in the summary table the total shipment amount is $7.00 - not $0.  Its even a tad confusing during checkout too - you have to pick $7/shipping even though by the time you get to the checkout page the promotion engine should be able to tell that the shipping would be free and should present it to the user properly.  (I'm referring to the Radio Buttons where you pick shipping options in the default `spree_frontend` checkout workflow).
