### ISSUE TITLE
Admin Order#new crashes when email doesn't match known user

### ISSUE THREAD

**Issue by brchristian** [spree/spree#4769]
In a blank/new Spree 2.1 store, I created a new order on the backend.

I notice that if I put in an email address that doesn't match any known users, but leave the `Guest Checkout` box checked to `No`, then the page will throw a 500 error.

Could we have a model validation or something that catches this instead?

**Comment by priyank-gupta** [comment]
Still persists in master.

**Comment by aishmita-aggarwal** [comment]
Looking into it.
