### ISSUE TITLE
adaptive admin menu problems

### ISSUE THREAD

**Issue by alepore** [spree/spree#4824]
Hi,
is that adaptive admin menu stuff still active (the "more.." dropdown menu)?
i have problems when i add more tabs after the default ones.

this screenshot show a clean spree 2.2 with 10 additional `<%= tab(:users, icon: 'user') %>` added:
![screen shot 2014-06-16 at 14 33 54](https://cloud.githubusercontent.com/assets/557414/3287060/8676dfc8-f552-11e3-8b4e-851df5a83f6e.png)

i'm on latest chrome

/cc @kennyadsl @devilcoders

**Comment by JDutil** [comment]
Should be easier to work with after the bootstrap rewrite now.
