### ISSUE TITLE
Promotion not removed on empty cart action

### ISSUE THREAD

**Issue by jswencki** [spree/spree#4908]
NOTE: I will try to do a PR against this in the next week, but because of schedule being crazy, wanted to submit issue so all are aware of it in case I can not.

**Branch: 2-2-stable**

**Issue**:
If promotion (coupon) has been added to a cart, then the cart is cleared, the user can't receive that promotion going forward.

**Steps**:
* Verify a valid promotion exists in admin
* Add Item to cart
* Apply valid promotion code
* Click the empty cart button
* Add another item to cart
* Apply same promotion code from above

**Expected**:
Promotion code should be applied again -OR- automatically applied once the product is added to cart since the code already exists.

**Actual**:
Error Received: "The coupon code has already been applied to this order" and the customer can not get the discount.

**Nice To Have** (Will get feedback on IRC)
Clear code from input box on error so customer can continue without manually clearing

**Screenshots**
![screen shot 2014-07-03 at 3 22 37 pm](https://cloud.githubusercontent.com/assets/4863463/3476639/c9d4a548-0303-11e4-9f2b-8f94f16b82a7.png)

![screen shot 2014-07-03 at 3 23 07 pm](https://cloud.githubusercontent.com/assets/4863463/3476642/d135c4f2-0303-11e4-9839-d72021539eea.png)

![screen shot 2014-07-03 at 3 23 59 pm](https://cloud.githubusercontent.com/assets/4863463/3476645/d6a164f0-0303-11e4-81c7-9a2265e144f6.png)

**Comment by robinboening** [comment]
Can someone confirm this is resolved now? /c @jswencki

**Comment by JDutil** [comment]
No I don't think so since it's still an open issue.

**Comment by nishant-cyro** [comment]
I am working on this.
