### ISSUE TITLE
Adjustments that update to zero aren't destroyed

### ISSUE THREAD

**Issue by brchristian** [spree/spree#4930]
In Spree, there is a general policy not to create an Adjustment (e.g., a tax adjustment) when the `amount == 0`.

This seems quite sound to me. I noticed, however, that when updating, an Adjustment could _become_ zero without being destroyed:

https://github.com/spree/spree/blob/2-2-stable/core/app/models/spree/adjustment.rb#L87-L91

I've noticed this in my app where, when I change my shipping address, sales tax may become zero. For the sake of consistency, perhaps we should self-destruct when `source.compute_amount` returns zero?

**Comment by priyank-gupta** [comment]
@damianlegawiec @Mafi88 I think this makes sense. The only scenario I see here is the case when admin wants to see the type of adjustments applicable to order (irrespective of amount), but then we should also create adjustment with 0 amount.
Thoughts ?

**Comment by Mafi88** [comment]
@priyank-gupta I think it makes sense to destroy such adjustments. They won't change anything and will be unnecessarly computed.

**Comment by VygovskySergey** [comment]
@brchristian We could not reproduce it on master, so it seems it was fixed already
