### ISSUE TITLE
API: PUT /api/products/:id, product_properties with same name/value create duplicate properties instead of updating

### ISSUE THREAD

**Issue by jamesmartinduffy** [spree/spree#4938]
Spree version: 2.2 stable

**Steps to reproduce:**
1. Log in to your Spree store with an account that has an admin API key, open Chrome dev tools, and execute the following jQuery command:
   
   ```
   $.ajax({
   url: "/api/products/1",
   type: "PUT",
   data: {
     "product": {
       "product_properties_attributes": [
          {
            "property_name": "brand",
            "value": "Brand Name"
          }
        ]
     }
   }
   });
   ```
2. Send the exact same command again
3. Visit `/api/products/1/product_properties`. Notice that the same entry is duplicated. It will duplicate itself as many times as you send that PUT request.

**Expected behavior**
I would expect that a product property is unique (only one brand per product), or at least that it not create a duplicate property if the name/value pair is an exact match.

Happy to include Gemfile.lock or other details but don't think it's necessary in this case. Let me know if you need anything else!

**Comment by priyank-gupta** [comment]
@dilpreet92 is working on the validation part related to this issue, https://github.com/spree/spree/pull/6849.
