### ISSUE TITLE
Redesign product form for easier variant editing

### ISSUE THREAD

**Issue by isaacfreeman** [spree/spree#5010]
Here's a proposed redesign of the product form.

The main objectives were:
- show novice users a simple form they can use to make a basic product without having to think about variants
- guide novice users to understand how to make variants when they're ready
- don't get in the way of experienced users

## Initial product form
For a new product, the form looks like this:

![1-single-variant](https://cloud.githubusercontent.com/assets/342659/3622284/d9a65a62-0e2e-11e4-8d1b-9bf1621d33e1.png)

The top section shows fields that relate to the product itself.
The second section is for managing variants, and initially shows fields for the master variant. Note that we don't use the jargon term "master variant" at this stage, but the grouping implies that these fields are different from the ones above. If the user needs more variants, they can click on the Add Variants button.

## Managing multiple variants

![2-multiple-variants](https://cloud.githubusercontent.com/assets/342659/3622291/04ca53ba-0e2f-11e4-8782-995a75784ce1.png)

Using Add Variants replaces the variant fields with a table of variants, and shows the Option Types field. The section now also has a heading "Variants".
Adding Option Types will add corresponding columns to the table.

## Editing a variant

![3-editing-a-variant](https://cloud.githubusercontent.com/assets/342659/3622294/0d0f5d68-0e2f-11e4-860e-b842484a63e0.png)

Clicking on the Edit button for a variant replaces the variant's table row with a form. This uses the same fields in the same layout as for the master variant.

## Questions
- Is this a feasible way to handle variants? 
- Any disadvantages compared with the current design?
- Is it suitable for the numbers of variants and option types in typical stores?

**Comment by JDutil** [comment]
close:discussion
