### ISSUE TITLE
Can't remove out of stock items from the cart

### ISSUE THREAD

**Issue by joshhepworth** [spree/spree#5100]
If an item has negative stock, it can't be removed from the cart. I think the following change would fix the issue and be appropriate, though I'm looking for confirmation to make sure as I'm not familiar with all the places `Spree::Stock::Quantifier` is used. I figure it's reasonable to assume that we can _always_ supply 0 of a thing.

```
# core/app/models/spree/stock/quantifier.rb
# Current file here: https://github.com/spree/spree/blob/master/core/app/models/spree/stock/quantifier.rb
# ...
      def can_supply?(required)
        required == 0 || total_on_hand >= required || backorderable?
      end
# ...
```

**Comment by JDutil** [comment]
This should be fixed by https://github.com/spree/spree/commit/3ae91e0b96b345380a13082201c20483b5f127fc
