### ISSUE TITLE
Skipping checkout delivery step but shipping physical product 

### ISSUE THREAD

**Issue by erikaxel** [spree/spree#5537]
Hi,

I would like to skip the delivery step in the check out since I only have one way of shipping, however from my short check in the code it seems that the current Spree assumes that skipping the delivery step means that you are not shipping a physical product, and therefore there should be no delivery address. 

Is this behaviour something that you would consider changing? So that it is possible to skip the delivery step in the checkout process, but still be able to specify a delivery address (in the address step) and a (default) shipment?

I would of course be happy to help if you consider this.

Regards,

-- Erik Axel

**Comment by JDutil** [comment]
close:discussion

**Comment by tonytonyjan** [comment]
I wonder how to do this in spree 3.

**Comment by JDutil** [comment]
Nothing was done to improve this for Spree 3.  My previous suggestion above is still likely best way to handle it.
