### ISSUE TITLE
Rails 4 enums in Spree::Orders

### ISSUE THREAD

**Issue by stahor** [spree/spree#5612]
This is part of my order_decorator
```
Spree::Order.class_eval do
  enum status: {
    pending: 2, already_shipped: 3, completed: 5, in_progress: 8
  }
              ...
```
When I try to call `some_order.pending!` I get ArgumentError: wrong number of arguments (1 for 0)
from /home/vkhvistik/.rvm/gems/ruby-2.1.3/gems/spree_core-2.3.4/app/models/spree/order.rb:219:in 'update!'.
The problem is that in enum.rb such methods are defined as `define_method("#{value}!") { update! name => value }` but in Spree::Order method `update!` is defined as
```
    def update!
      updater.update
    end
```

**Comment by nishant-cyro** [comment]
Looking into this.
