### ISSUE TITLE
Returns and Exchanges Feedback

### ISSUE THREAD

**Issue by jordan-brough** [spree/spree#5633]
![returns-and-exchanges](https://cloud.githubusercontent.com/assets/23050/5097743/b925a7b0-6f4b-11e4-9782-9077c832705a.jpg)
- [ ] Customer returns should have many exchanges
- [ ] Reimburse cost of return, cost of prop cost of shipment
- [ ] Shipping method on exchanges?
- [ ] Add return item to customer return edit view
- [ ] Expedite exchanges on a per return authorization level or return item, not global level. No shipment created. Option to ship now or ship and charge.
- [ ] Split auth items and return items
- [ ] Base classes that raise errors
- [ ] Lost in transit on shipment level
- [ ] Reason for return to return item
- [ ] Document extensibility & configuration
- [ ] Consider removing callbacks
- [ ] Consider whether to split ReturnItems into multiple models (ReturnAuthorizationItem/ReturnItem/ReimbursementItem)

**Comment by JDutil** [comment]
@BenMorganIO there are pages under configuration tab that allow you to edit the refund & return reasons.

**Comment by BenMorganIO** [comment]
@JDutil awesome!
