### ISSUE TITLE
Can add first variant to product without option types

### ISSUE THREAD

**Issue by JDutil** [spree/spree#5639]
The link to "add one" variant is appearing on the variants page for products without option types assigned. This should not be possible, and correctly goes away once the first variant is added...

**Comment by nishant-cyro** [comment]
@priyank-gupta @Mafi88 @damianlegawiec @JDutil - This one is working fine in master branch now.

<img width="1198" alt="screen shot 2016-02-10 at 2 19 19 pm" src="https://cloud.githubusercontent.com/assets/1930749/12942465/5f78afb0-d001-11e5-83e0-ec4b1ec0e4bd.png">

**Comment by nishant-cyro** [comment]
@priyank-gupta @Mafi88 @damianlegawiec @JDutil - Able to replicate this one. Looking into it.
