### ISSUE TITLE
Significant speed drop when quantity > 1000 on line item

### ISSUE THREAD

**Issue by mtomov** [spree/spree#5706]
Hello guys,

I would like to report a performance issue when a line item has more than > 1000 inventory units assigned to it. 

With 2500 inventory units, a page refresh on an incomplete order in the admin, which is handled by [`OrdersController#edit`](https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/orders_controller.rb#L59) and makes a call out to refresh the shipment rates takes around **11 seconds**

A similar slow down is observed at the frontend as well when adding a line item to the cart, though I am not sure it is the exact same cause.

Commenting out [`unless find_item(inventory_unit)`](https://github.com/spree/spree/blob/master/core/app/models/spree/stock/package.rb#L14) brings the page load back to normal.

The problem is on [`Package.rb#find_item`](https://github.com/spree/spree/blob/master/core/app/models/spree/stock/package.rb#L44)

The detect used becomes very expensive. 

Thank you for looking at it!

Regards,
Martin

**Comment by damianlegawiec** [comment]
This should be resolved via #7790
