### ISSUE TITLE
Infinite loop when a create line item promotion attempts to add an out of stock product (2-2-stable)

### ISSUE THREAD

**Issue by Hates** [spree/spree#5787]
When a promotion is set to add a line item, if the line item is not backorderable and is out of stock an infinite loop and eventual `stack level too deep` error is raised. We are currently experiencing this on `2-2-stable` https://github.com/spree/spree/tree/2-2-stable

![spree_administration__promotions](https://cloud.githubusercontent.com/assets/4784/5454192/82c0c2f4-8526-11e4-8d95-b974ee22a8ed.png)

![spree_administration__products](https://cloud.githubusercontent.com/assets/4784/5454193/8cd410ca-8526-11e4-8767-2dfc17ed1f98.png)

![action_controller__exception_caught](https://cloud.githubusercontent.com/assets/4784/5454227/0b49a5aa-8527-11e4-8220-ca2a0e0090f0.png)

I believe the problem is that `CreateLineItems` fails to add the line item but doesn't return `false`, so is continually applied. So `Promotion#activate` will always fire the promotion action. Ideally the promotion should show an error to the user, saying the promotion is no longer available.

My current Gemfile and Gemfile.lock are here: https://gist.github.com/Hates/e871d12d05a0f97008a0

**Comment by fmd** [comment]
This is also the case on 2-4-stable.

**Comment by Hates** [comment]
Possible to have this merged into 2-2-stable?

**Comment by JDutil** [comment]
@Hates done
