### ISSUE TITLE
Exchange for select input doesn't support master variants

### ISSUE THREAD

**Issue by adaddeo** [spree/spree#5802]
1. Create a product that uses a master variant
2. Attempt to create an exchange for the item on an order

The offending line is:
```
<%= item_fields.collection_select :exchange_variant_id, return_item.eligible_exchange_variants, :id, :options_text, { include_blank: true }, { class: "select2 fullwidth return-item-exchange-selection" } %>
```

The options_text field returns nothing if the variant is a master. I will be happy to submit a PR, I just wasn't sure what the approach would be. A helper method that users the name or the option value?

**Comment by darbs** [comment]
This can be close due to 890841f31420141bcdbf31f2655cca1e7c77d3bb.

**Comment by JDutil** [comment]
Thanks!
