### ISSUE TITLE
[feature] Introducing a UI that is more user-friendly for the larger screen resolutions

### ISSUE THREAD

**Issue by paulhuisman** [spree/spree#5831]
Dear Spree contributors,

While Spree proves to be extremely extendible, the navigation menus in the top prevent the creation of new menu items due to a lack of vertical space.

We propose the following fix:
Move the navigational menus to the left, like --for instance-- WordPress does it (see the following image).  

![screen shot 2014-12-24 at 13 47 53](https://cloud.githubusercontent.com/assets/37524/5548546/44ccb152-8b74-11e4-9160-7d9fb11d3886.png)

As the number of menu items grow, they will extend into the scrolling direction.  Therefor they will have unlimited space to grow in case one like to extend Spree with a lot of functionality that needs to be accessible from the navigation menu.  

Solving this navigation menu problem would also help to fill the abundance of horizontal space that is available on modern monitors that use a resolution higher than 1280px wide.

We'd like to hear what you think of this idea! If you are interested, we could propose a interaction design of the UI to make everything a more specific. 

Happy holidays,
Paul Huisman
www.hoppinger.com

**Comment by JDutil** [comment]
@paulhuisman we've made a change to this in the backend rewrite for Spree 3 it's currently on the master branch to check out.
