### ISSUE TITLE
human(count: :many) raises exception for locales with specific pluralization, such as :ru and is unsafe for :en

### ISSUE THREAD

**Issue by dieselpower** [spree/spree#5842]
rails 4.1.8
config.i18n.default_locale = :en
2.1.5 :001 > Spree::Order.model_name.human(:count=>:one)
 => "Orders"  #used :other
2.1.5 :002 > Spree::Order.model_name.human(:count=>:many)
 => "Orders" #used :other

config.i18n.default_locale = :ru
.human(count: :many)- causes error:
"undefined method `%' for :many:Symbol"

For example, in rails console:
Spree::Order.model_name.human(count: :one)- error
Spree::Order.model_name.human(count: :many)- error
Spree::Order.model_name.human(count: :1)- works right
Spree::Order.model_name.human(count: :5)- works right

**Comment by futhr** [comment]
Quoted from issue (Mars 2014) in: [i18n gem](https://github.com/svenfuchs/i18n) concerning CLDR v24:

_These rules have been released for several months now. (http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html) and the changes to Russian at least are breaking the gem. The "few" rule for Russian is not the "other" rule. Translation services that follow the new spec don't return "few" for Russian anymore which then throws a missing key exception._

**Comment by futhr** [comment]
Note that the title for the issue is a bit misleading due to that it only seems to affect Russian and other languages with specific pluralization. 

This was ActiveAdmin's solution to same pluralization problem: https://github.com/activeadmin/activeadmin/pull/2791. So it could be good idea to add a similar (monkey) patch to `spree_i18n` with a regression spec until `i18n` got a more solid solution for this.

**Comment by dieselpower** [comment]
It affects :en also:
2.1.5 :001 > Spree::Order.model_name.human(:count=>:one)
=> "Orders" #used :other
2.1.5 :002 > Spree::Order.model_name.human(:count=>:many)
=> "Orders" #used :other

**Comment by futhr** [comment]
There are zero occurrences of `Spree::Order.model_name.human(count: :one)` in the source code just `Spree::Order.model_name.human` for singular and that works.

**Comment by dieselpower** [comment]
I provided this example to show, that using :one will not raise exception in :en, as using :many. But both are incorrect.

**Comment by futhr** [comment]
So when you actually work with pluralization of model translations for Russian sites you do like this?

```ruby
# singular
Spree::Order.model_name.human(count: 1)
# plural
Spree::Order.model_name.human(count: 5)
# or
Spree::Order.model_name.human(count: '')
```

**Comment by dieselpower** [comment]
I am a beginner and can mistake. As i understand:
# singular, value from one: in locales yaml: en.yml- "Order", ru.yml- "Заказ"
Spree::Order.model_name.human # Singular by default
Spree::Order.model_name.human(count: 1)

#plural. For :en plural is everything, other than 1, so in en.yml- other: Orders. :ru has several plural #forms, but the correct form is also in other:. So, ru.yml- other: "Заказы"
Spree::Order.model_name.human(count: 2) # en.yml- "other: Orders"
Spree::Order.model_name.human(count: :many) # en.yml- "other: Orders", ru.yml- exception in i18n
Spree::Order.model_name.human(count: '')  # en.yml- "other: Orders", ru.yml- other: "Заказы"- right

In rails-i18n:
en:
def self.rule
  lambda { |n| n == 1 ? :one : :other }   #numbers and symbols will work
end

ru:
def self.rule
  lambda do |n|
    n ||= 0
    mod10 = n % 10               #exception if Symbol is provided
    mod100 = n % 100

    if mod10 == 1 && mod100 != 11
      :one
    elsif FROM_2_TO_4.include?(mod10) && !FROM_12_TO_14.include?(mod100)
      :few
    elsif mod10 == 0 || FROM_5_TO_9.include?(mod10) || FROM_11_TO_14.include?(mod100)
      :many
    else
      :other
    end
  end
end

**Comment by futhr** [comment]
ActiveAdmin's solution to this was in short:

```ruby
I18n::PLURAL_MANY = 2.1
Spree::Order.model_name.human(count: I18n::PLURAL_MANY)
```

**Comment by dieselpower** [comment]
in spree-i18n for en.yml there is no many:
one: Order
other: Orders
can we use human(count: :other) for all locales where other: exists?

**Comment by dieselpower** [comment]
or i can change this constant to needed value for :ru?

**Comment by dieselpower** [comment]
I agree, it's a workaround, can we do this?

**Comment by dieselpower** [comment]
changed title

**Comment by JDutil** [comment]
I'm okay with the workaround ActiveAdmin used unless there are any objections.

**Comment by RaVbaker** [comment]
I have similar issue with polish locales (`:pl`). And it's crucial to me so I plan to invest some time today to prepare a patch. Should we store the `PLURAL_MANY` setting as ActiveAdmin (in custom constant) or as extra Spree::AppConfiguration option? 

@JDutil What do you recommend?
