### ISSUE TITLE
Asset path error (sprocket-rails 2.1.4) not fixed in spree 2.3.6

### ISSUE THREAD

**Issue by janmetten** [spree/spree#5851]
When running spree 2.3.6 I get the following error:

Asset names passed to helpers should not include the "/assets/" prefix. Instead of "/assets/favicon.ico", use "favicon.ico"

According to this it has been fixed in the master branch of spree: http://stackoverflow.com/questions/25633822/asset-path-error-in-spree-ruby-on-rails

Apparently this fix didn't make it into 2.3.6.
Can this fix also be merged into spree 2.3?

**Comment by JDutil** [comment]
This is fixed on 2-3-stable.  You might be overriding the template, and need to update it yourself. Or using an extension that does, and needs to be updated.

The change looked like this:
https://github.com/spree/spree/commit/75191b4dd28f575f743be6fec4bbd97a11e1b933
