### ISSUE TITLE
ActiveRecord::RecordInvalid in Spree::OrdersController#populate

### ISSUE THREAD

**Issue by alepore** [spree/spree#5856]
This is to bring up [this discussion](https://github.com/spree/spree/commit/9ac714e357cd7374709fab2c275012d697d57e4d#diff-d72e49d7a94cadb626e4e07dff3137abL87) .
If i'm not missing something this was a very bad idea: the user that add too much quantity to cart gets an exception and the raw server error page, instead of the normal validation error message.
I don't think this is acceptable for any store.
Thoughs?

**Comment by JDutil** [comment]
Could you submit a PR making the desired changes?

**Comment by alepore** [comment]
@jhawthorn any thoughts on removing the bang?
sorry if already discussed somewhere else

**Comment by JDutil** [comment]
Fixes w/ b4c5583be6c91fc9388587caa8fb76235be9bd08
