### ISSUE TITLE
Admin: Orders aren't editable after deleting tax rates

### ISSUE THREAD

**Issue by schmijos** [spree/spree#5858]
![image](https://cloud.githubusercontent.com/assets/245443/5629487/69b57126-95b4-11e4-9f5e-0ab06bff1a2d.png)

---

In our shop we introduced new tax rates and deleted the old ones per Admin GUI. The orders executed until this time weren't accessible after that anymore from the admin gui. The error message was `undefined method 'compute_shipping_rate' for nil:NilClass` at line 15 of *core/app/models/spree/shipping_rate.rb*.

The problem seems to be that deleting tax rates cascades the deletion to the dependent calculator which is still needed for old orders.

`TaxRate` is extended by a `calculator` in the file *core/lib/spree/core/calculated_adjustments.rb* on line 6:

    has_one   :calculator, class_name: "Spree::Calculator", as: :calculable, inverse_of: :calculable, dependent: :destroy, autosave: true

We should remove the `dependent: :destroy` part for it to look like that (but I'm not sure about the implications):

    has_one   :calculator, class_name: "Spree::Calculator", as: :calculable, inverse_of: :calculable, autosave: true

**Comment by JDutil** [comment]
Could you submit a PR?

**Comment by alepore** [comment]
i can confirm, i removed a tax rate and now all old admin orders are broken :)

**Comment by alepore** [comment]
what about adding tax rates soft-delete?

**Comment by JDutil** [comment]
Definitely need to add acts_as_paranoid PR welcome if you want to beat me to it.

**Comment by alepore** [comment]
oh, looks like it's already paranoid... so the real problem is the calculator:

```
2.1.4 :006 > order.shipments.first.shipping_rates.first.display_price
  Spree::Shipment Load (0.4ms)  SELECT  "spree_shipments".* FROM "spree_shipments"  WHERE "spree_shipments"."id" = $1 LIMIT 1  [["id", 357]]
  Spree::Order Load (0.6ms)  SELECT  "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."id" = $1 LIMIT 1  [["id", 698]]
  Spree::TaxRate Load (0.7ms)  SELECT  "spree_tax_rates".* FROM "spree_tax_rates"  WHERE "spree_tax_rates"."id" = $1 LIMIT 1  [["id", 1]]
  Spree::Calculator Load (0.5ms)  SELECT  "spree_calculators".* FROM "spree_calculators"  WHERE "spree_calculators"."calculable_id" = $1 AND "spree_calculators"."calculable_type" = $2 LIMIT 1  [["calculable_id", 1], ["calculable_type", "Spree::TaxRate"]]
NoMethodError: undefined method `compute_shipping_rate' for nil:NilClass
```

**Comment by JDutil** [comment]
The calculator should be paranoid as well.
