### ISSUE TITLE
Unlock jquery-rails from 3.1.2

### ISSUE THREAD

**Issue by niedfelj** [spree/spree#5860]
Is it still necessary to have jquery-rails locked to ~> 3.1.2?  We would like to be able to use jquery-rails 4.0.3 because it includes jquery 1.11.2.  I believe 3.1.2 was locked into spree due to an attributes bug that was resolved?

**Comment by JDutil** [comment]
You could try running the specs to see if they still pass, and if they do we could loosen the dependency.

We're close to having the rails 4.2 branch merged to master, and that bumps jquery-rails so this will probably happen sometime soon.

**Comment by ccschmitz** [comment]
Any word on when the 4.2 branch might get merged or is there anything I can do to help move that along?
