### ISSUE TITLE
Failure/Error: within("table#listing_orders") { expect(page).not_to have_content("R200") }

### ISSUE THREAD

**Issue by lanrion** [spree/spree#5877]
I have sent a pull request #5875 recently, it just have one line change to optimize search, but it fail random by the same problem with #5874 #5837 .  But it can check successful after re-run.
Maybe we need to try to fix it. How do you see?

```sh
Failures:

  1) Orders Listing searching orders filter on promotions only shows the orders with the selected promotion
     Failure/Error: within("table#listing_orders") { expect(page).not_to have_content("R200") }
       expected not to find text "R200" in "COMPLETED AT NUMBER RISKY STATE PAYMENT STATE SHIPMENT STATE CUSTOMER E-MAIL TOTAL 2015-01-10 R100 Risky cart balance due pending freida@grady.com $110.00 2015-01-08 R200 Safe cart luciano@oconner.biz $0.00"
     # ./spec/features/admin/orders/listing_spec.rb:145:in `block (5 levels) in <top (required)>'
     # ./spec/features/admin/orders/listing_spec.rb:145:in `block (4 levels) in <top (required)>'

Finished in 6 minutes 27 seconds (files took 4.12 seconds to load)
417 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/features/admin/orders/listing_spec.rb:140 # Orders Listing searching orders filter on promotions only shows the orders with the selected promotion
Building: sample
```

Thanks,
Dylan

**Comment by JDutil** [comment]
I've already spent some time trying to make this less frail, but haven't come up with a permanent fix yet.  Definitely need to fix it though.

**Comment by lanrion** [comment]
I will try to fix , too.

**Comment by JDutil** [comment]
I'm buying whoever makes this spec un-frail so it doesn't keep randomly failing a beer.

**Comment by tvdeyen** [comment]
I think this can easily be fixed with some css refactoring. I have it working in my current branch for fixing #6143 \o/ 

Can't wait to drink a :beer: with you @JDutil :tada:

**Comment by JDutil** [comment]
Nice! I had tried tweaking the capybara selectors many different ways and nothing seemed to help.

We'll definitely have to get another beer and hamburger at the next Spreeconf. I know how much you Hamburgs (no idea how to properly pluralize) love your hamburgers.

Thanks @tvdeyen @changetip 1 beer

**Comment by changetip** [comment]
Hi @tvdeyen, @JDutil sent you a Bitcoin tip worth 1 beer (11,903 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/612120)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by tvdeyen** [comment]
:tada: Thanks!

Yeah, we definitely will get a chance to drink :beer: and eat :hamburger: again! 

PS: We are actually called Hamburgers :laughing:
