### ISSUE TITLE
Free Shipping promotion removed from the order when navigating back to "address" 

### ISSUE THREAD

**Issue by nimashariatian** [spree/spree#5881]
Steps to produce:
1. Create a free shipping promotion
2. Add an item to cart and proceed to checkout until the payments page
3. Apply the promotion to the order with out filling the credit card information
4. Navigate back to the "address" state 
5. Continue navigating to checkout 
6. The promotion has disappeared, user is unable to apply the promotion again (code is already used)
7. Confirm the order went through without any promotions.. 

Screenshots below 

![step1](https://cloud.githubusercontent.com/assets/210358/5727864/2ac06b44-9b34-11e4-9255-1e57d2cc0726.png)
![step2](https://cloud.githubusercontent.com/assets/210358/5727863/2ac00f1e-9b34-11e4-99a1-70b1c90645ad.png)
![step3](https://cloud.githubusercontent.com/assets/210358/5727865/2ac1caca-9b34-11e4-9b04-c70fc7ee32ba.png)
![step4](https://cloud.githubusercontent.com/assets/210358/5727862/2abd1e9e-9b34-11e4-8f17-f2a28cb3dd14.png)
![step5](https://cloud.githubusercontent.com/assets/210358/5727867/2ac762be-9b34-11e4-8cad-447a9f1de71d.png)
![step6](https://cloud.githubusercontent.com/assets/210358/5727866/2ac77498-9b34-11e4-813b-fa98eeede9c7.png)

Verified on spreecommerce.com as well as 2.4 stable branch

Gemfile:
https://gist.github.com/nimashariatian/892f17e8fa79b8a2d3e8

**Comment by bvalentino** [comment]
:+1: for fixing this bug
