### ISSUE TITLE
Spree[2.4.2] Payment refunds are not reflected in payment total

### ISSUE THREAD

**Issue by darbs** [spree/spree#5907]
Currently refunds created directly on the payment are not reflected in the payment total, causing 'credit owed' to constantly be displayed.

It seems like we should include each payments own refunds if they have any. Something along the lines of:
```
# order_updater.rb
def update_payment_total
      order.payment_total = payments.completed.inject(0) {|sum, payment| sum + payment.amount - payment.refunds.sum(:amount) }
end
```
or 
```
# payment.rb
def amount
      self[:amount] - refunds.sum(:amount)
end
```

**Comment by JDutil** [comment]
Can you provide steps to reproduce the problem, and which version of spree your using?  IIRC this was an issue in older versions of Spree that has already been fixed. triage:steps

**Comment by darbs** [comment]
Sorry, 2.4.2. To reproduce, just create a partial return on a payment. After the refund is processed there is still an 'credit owed'.

**Comment by adaddeo** [comment]
Just tried this is a sandbox store.

Create an order, capture the payment, adjust the order to have a credit due, create a refund for this amount on the previously captured payment.

Refund goes through, order is still in credit owed state.

**Comment by niedfelj** [comment]
We are having the same issue on 2.4.2.  There are actually 2 issues going on:

1) Payment refunds are not reflected in the payment total (no deduction)

2) If you create an order adjustment, the methods that previously existed to just click the checkbox next to existing payments to "credit" is now gone and replaced with this silly refund business where you would need to recalculate adjustments.

What is the purpose of refund vs RMA?
