### ISSUE TITLE
undefined method `line_items' for nil:NilClass

### ISSUE THREAD

**Issue by farrukhny** [spree/spree#5944]
Hello Guys
I really need help with one issue it is not Spree issue.
Basiclly i am working to make cart popup and it is same as cart info just on header of the page when you click popup will show with list of your items with product title, price image etc.. I try to copy /spree_frontend/view/spree/order/edit  file but i got a error

```

<% @body_id = 'cart' %>
<div data-hook="cart_container">
  <h1><%= Spree.t(:shopping_cart) %></h1>

  <% if @order.line_items.empty? %>

    <div data-hook="empty_cart">
      <div class="alert alert-info"><%= Spree.t(:your_cart_is_empty) %></div>
      <p><%= link_to Spree.t(:continue_shopping), products_path, :class => 'btn btn-default' %></p>
    </div>

  <% else %>

    <div data-hook="outside_cart_form">
      <%= form_for @order, :url => update_cart_path, :html => {:id => 'update-cart'} do |order_form| %>
        <div data-hook="inside_cart_form">

          <div data-hook="cart_items" class="table-responsive">
            <%= render :partial => 'form', :locals => { :order_form => order_form } %>
          </div>

          <div class="links col-md-6 navbar-form pull-right text-right" data-hook="cart_buttons">
            <div class="form-group">
            <%= order_form.text_field :coupon_code, :size => 10, :placeholder => Spree.t(:coupon_code), class: "form-control form-control-inline" %></div>
            <%= button_tag :class => 'btn btn-primary', :id => 'update-button' do %>
              <%= Spree.t(:update) %>
            <% end %>
            <%= button_tag :class => 'btn btn-lg btn-success', :id => 'checkout-link', :name => 'checkout' do %>
              <%= Spree.t(:checkout) %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div id="empty-cart" class="col-md-6 pull-left" data-hook>
      <%= form_tag empty_cart_path, :method => :put do %>
        <p id="clear_cart_link" data-hook>
          <%= submit_tag Spree.t(:empty_cart), :class => 'btn btn-default' %>
          <%= Spree.t(:or) %>
          <%= link_to Spree.t(:continue_shopping), products_path, :class => 'continue' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

```

Can not find where is method `line_items' ?

please help need your advise.

PS: I am new in ROR and Spree

Thank you

**Comment by JDutil** [comment]
Please use the spree-user mailing list to ask questions:
https://groups.google.com/forum/#!topic/spree-user

close:question

**Comment by JDutil** [comment]
The error is because your `@order` variable is nil and line_items method belongs to Order.

**Comment by FadliKun** [comment]
hai @JDutil, sorry for open again the closed case...

i got same problem like farrukhny, i'm trying to costumized the cart on spree to slide cart, so the cart will call in every page..

i know the problem is because @order variable get nil on any page except /cart, so i try to declare in my project spree/order/edit like this :

<% @order = simple_current_order %>,


but i got a new problem...
![checkout my account login error](https://cloud.githubusercontent.com/assets/14267591/10134751/56b58f78-6612-11e5-9ba9-281692c535bb.jpg)

can you help me ? :D

best regards, fadli
