### ISSUE TITLE
Image sorting not working

### ISSUE THREAD

**Issue by jonmast** [spree/spree#5947]
I have a product with 3 images and when I try to reorder them in the admin it doesn't work. Sometimes the position will change but not to what I selected. I experimented on the console and got the same results. It seems that acts_as_list is messing with the update_attributes call. The positions don't always change to what you specify and the other images' positions change too. Switching to set_list_position instead of update_attributes(position) in resources_controller seems to fix the issue.

<a href=https://gist.github.com/jonmast/67156057d6869f013bc0>Gemfile & Gemfile.lock</a>

**Comment by mleglise** [comment]
This fix breaks positioning for ANY model that does not include acts_as_list. There have already been 2 separate patches to fix Variants and OptionTypes. Currently ProductProperties are still broken, plus possibly other models too. How about resources_controller checks `responds_to(:set_list_position)` to decide which method to call?
