### ISSUE TITLE
stock_location.name will give an error in the admin if it isn't set

### ISSUE THREAD

**Issue by MisinformedDNA** [spree/spree#5960]
If you create a shipment with the code below, you won't get an error.

```
shipment = order.shipment.create!([
  {
    number: shipment_number,
    order_id: order_number,
    state: "ready",
  }
])
```

But if you visit admin/orders/[orderNumber]/edit, you will get an error message

```
undefined method `name' for nil:NilClass
```

on the line 

```
<strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.stock_location.name %>'</strong>
```

`stock_location` should either be required and give an error or the view should do a check. I believe `stock_location` or `stock_location_id` should be required. Not sure how you would ship otherwise.

**Comment by GeekOnCoffee** [comment]
I agree, any chance you could send a pull request to add this validation?

**Comment by MisinformedDNA** [comment]
@JDutil It doesn't look like you merged your work. Can you merge into master and stable-2-4?

**Comment by JDutil** [comment]
Um I can check again but if I didn't merge it was probably because of broken tests.
