### ISSUE TITLE
Product filter rendering too tightly coupled with ActiveRecord

### ISSUE THREAD

**Issue by MattDunbar** [spree/spree#5964]
I was looking into adding the ability to manage product filters by property and option from the admin.

This lead me to another issue though - in some cases its essential to use another provider (such as Elastic Search). With the code in its current state the approach we have taken in the past is to ditch the existing product filters and implement our own filtering system. This isn't quite ideal. I wouldn't want to implement product filters in the admin that we can't use for clients needing elasticsearch.

I'm happy to address this underlying issue, but looking for some feedback on potential approaches.

This would be a breaking change for many existing Spree builds so I'd expect it to live in master only to make its way into the next major release.

I've included my initial thoughts below, please provide feedback both on possible adjustments and the likelihood of this being accepted.

--

Get rid of [product_filter.rb](https://github.com/spree/spree/blob/master/core/lib/spree/core/product_filters.rb). Its often quite messy and confusing.

Ship with default filters for options and properties (detailing properties for this example).
Spree::Core::ProductFilters::PropertyFilter would be a module containing a class for a match any filter and another for a match all filter.

Spree::Core::ProductFilters::PropertyFilter::MatchAll would be a class with any generic settings (e.g. should this filter show options that aren't available in the current taxon, any other common info) and implements a base class which provides a means of accessing provider specific implementations (e.g. match_all_filter.provider('activerecord') would return the object that can be used to apply our activerecord filters, detailed next).

Spree::Core::ProductFilters::PropertyFilter::MatchAll::ActiveRecord would be a provider specific implementation class with the actual query logic inside. The ActiveRecord filters implementation would know how to work with this class.

From here it would be possible to bake ElasticSearch functionality into the core if desired - but its beyond the scope of the time I can initially commit to this.

I would shortly after this in a follow up pull request add the ability to manage filters globally and from within a taxon in the admin.

**Comment by JDutil** [comment]
It wouldn't hurt to overhaul the product filtering abstraction if your interested, but please use the [spree-user](https://groups.google.com/forum/#!topic/spree-user) mailing list for feature request discussions.

close:discussion

**Comment by MattDunbar** [comment]
I'd be happy to post in the spree-user mailing list, if it was solely used for issues like this and not general questions about spree, people looking for devs, etc. Its not exactly ideal to have to submit to a mailing list that encompasses so many other things in order to solicit feedback so that we can build something thats adding a fairly significant amount of value to Spree. Especially when the lack of any decent filters implementation results in us throwing away what ships with the core in a large majority of the builds we handle.

It also appears that there are several other similar discussions open - could you clarify what I should be doing differently with this issue to make it more suitable like the others seen here: https://github.com/spree/spree/issues?q=is%3Aopen+is%3Aissue+label%3Adiscussion

**Comment by MattDunbar** [comment]
Also, to clarify I've spoken about this a few times and there seems to be some confusion as to exactly what I mean by the rendering being too tightly couple with activerecord.

In product_filters.rb the actual filter labels / etc are returned from the same method(s) as the actual scopes. There is no room in the current approach to cleanly add the appropriate data to filter in with another provider. As a result, even though I only want to throw away the activerecord filters portion of the filters code, I end up getting rid of it entirely.

**Comment by JDutil** [comment]
Matt I think the idea itself is great, but it's pretty general to say hey lets abstract this component of spree better than it is now...

We are no longer leaving issues open just to discuss what we want to do.  Please discuss what you would like to do on the spree-user mailing list.  I'm not saying that this idea is good or bad, but it is a distraction to leave dozens of issues open.  We want the issues to either be actionable or not, and to discuss what you'd like to do is not actionable for us.  Feel free to open a pull request with your suggested improvements for people to review if you would like or this should be discussed on the mailing list.

I will be closing the other discussion issues as well so that this doesn't feel like your being singled out.
