### ISSUE TITLE
How to hide images that are attached to 'All' variants?

### ISSUE THREAD

**Issue by vernondegoede** [spree/spree#5967]
Right now I've the following piece of code, which retrieves all images attached to Spree products.

```ruby
<% @product.images_by_variant.each do |variant_id,images| %>
    <ul class="gallery gallery-<%= variant_id %>" data-variant="<%= variant_id %>">
        <% images.each do |image| %>
            <li>
                <%= image_tag(image.attachment.url(:single)) %>
            </li>
        <% end %>
    </ul>
<% end %>
```
However, there are also images displayed that represent all variants. I want to hide those.

How can I only show variant (different colors for example) for products?

Cheers!

**Comment by JDutil** [comment]
You can query based on the images viewable association.

Please use the [spree-user](https://groups.google.com/forum/#!topic/spree-user) mailing list to ask questions. close:question
