### ISSUE TITLE
Merging a Cart Breaks Login/Checkout Because Combined Line_Item Quantities Exceed Inventory

### ISSUE THREAD

**Issue by stephenhmarsh** [spree/spree#5976]
Jumped from 2.3.6 to 2_4_stable... it broke our checkout for some customers trying to merge carts because the combined carts' line_item quantities exceeded present inventory...

**To reproduce**:  
1) Using a (spree_auth_devise) user account, login and add a product to your cart where you know its quantity.  For example's sake let's say we know we have only 1 of a certain painting.
2) Logout
3) As an anon user, add the same painting/product/whatever to your cart.
4) Try to checkout.  As you log back in, the cart merge fails with ``ActiveRecord::RecordInvalid: Validation failed: Quantity Sorry, we don’t have enough stock available.`` because it tries to combine the two quantites and we only have 1 of the painting to begin with

The problem seems to be from calling ``.save!`` instead of the previous ``.save``in this commit: https://github.com/spree/spree/commit/43ee0edec2c13eac2b9bf9a05a8e415fe5e5da02

Why would I want my app to throw this error in production ? 

Shouldn’t it either **A)** silently fail and effectively revert to the line_item that was in the current_order (2.3.x and previous way of handling this?) or at least **B)** include logic around calculating availability of quantities and only merge in max available amount of inventory???

**Comment by stephenhmarsh** [comment]
Also this is a problem: https://github.com/spree/spree/commit/9ac714e357cd7374709fab2c275012d697d57e4d#diff-d72e49d7a94cadb626e4e07dff3137abR87

**Comment by mleglise** [comment]
+1

**Comment by onedanshow** [comment]
+1

This seems like a major issue.  It's happening once every day or two for us.  Any time someone fills in a cart and then tries to log in with an old cart. (See #6257)

Is anyone working on a solution that removes out-of-stock line items and sends a message to the customer about what happened?

**Comment by JDutil** [comment]
I don't believe anyone is currently working on this.

**Comment by JDutil** [comment]
I believe we should remove the line item or reduce the quantity to what is available, and display a message to the customer explaining what happened if anyone wants to tackle this.

**Comment by vernondegoede** [comment]
+1
I'm having the same issue. We're adding line items through the Spree API, no errors are shown.
However, when I'm trying to log into the admin, I get the following error:

Exception ActiveRecord::RecordInvalid in Rack application object (Validation failed: Quantity selected of "Aminia Shopper (Colour: Green)" is not available.)

**Comment by dangerdogz** [comment]
Would redirecting to the /cart page and displaying the error be an acceptable behavior? (Same as what happens when you try to checkout and old cart and some items are unavailable)

**Comment by JDutil** [comment]
Yea :+1:

**Comment by tesserakt** [comment]
Any update on this? We are going from 2.3 to 3.0 (by way of 2.4) and would be thrilled if this was not an issue.

**Comment by onedanshow** [comment]
It still appears to be in 2.4. Not sure about 3.0

**Comment by crystalized** [comment]
@darbs Thank you so much for this fix! I tried it out in 2.4 and it works great. 
I too was having the login break if the user and guest carts were attempting to merge.

**Comment by onedanshow** [comment]
Yes! Nice work @darbs!

**Comment by JDutil** [comment]
Thank you @darbs I've merged to master.

**Comment by mtomov** [comment]
Thank you @darbs so much indeed! This has been plaguing a lot of Spree carts.
