### ISSUE TITLE
Removing all functionalities except Product Catalog Engine

### ISSUE THREAD

**Issue by yomishra** [spree/spree#5977]
Hi all,I was trying to create an e-commerce website with multiple sellers.I didn't knew about spree at that time.So developed other components myself.But recently i saw spree and specifically I want to make use of its taxonomy,product,variants service, in short its product catalog management module.

Thus can someone guide me,how I can remove all the other functionalities of spring from its admin interface.How I can modify the gem,I have cloned the source code already.

Any help would be appreciated.

**Comment by JDutil** [comment]
Only include spree_core or whatever other modules you want in your Gemfile instead of saying spree which includes all of them.  Please use the spree-user mailing list if you have further questions. close:question

**Comment by JDutil** [comment]
close:question

**Comment by JDutil** [comment]
close:discussion
