### ISSUE TITLE
Save oringiator type on stock movement by Spree::ReturnAuthorization

### ISSUE THREAD

**Issue by mcarreiro** [spree/spree#5981]
Hi, 
   I'm working with Spree 2.3.2 and I made a patch to save the originator_type and its id when creating a StockMovement on ReturnAuthorization -> process_return

def process_return
    inventory_units(include: :variant).each do |iu|
      iu.return!

      if iu.variant.should_track_inventory?
        if stock_item = Spree::StockItem.find_by(variant_id: iu.variant_id, stock_location_id: stock_location_id)
          Spree::StockMovement.create!(stock_item_id: stock_item.id, quantity: 1, originator_id: self.id, originator_type: 'Spree::ReturnAuthorization')
        end
      end
    end

    Spree::Adjustment.create(adjustable: order, amount: compute_amount, label: Spree.t(:rma_credit), source: self)
    order.update!

    order.return if inventory_units.all?(&:returned?)
  end

I would like to know why you didn't save this data on the original method (maybe i'm missing something), and if it will be added to another version.

Thanks,
Martin

**Comment by JDutil** [comment]
It was probably just an oversight not intentional as far as I can tell.  Could you submit a PR?
