### ISSUE TITLE
api_key cannot be found

### ISSUE THREAD

**Issue by arthurtalkgoal** [spree/spree#5993]
Hi, I found that latest commit in 2-4-stable removed the AJAX JS codes for setting the 
```
  token: Spree.api_key
```
e.g. at 
https://github.com/spree/spree/blob/07aa6ea89e4c9e2691f5af65497cb3979315edea/backend/app/assets/javascripts/spree/backend/option_value_picker.js

Line 35 has the above codes. But this file is removed and more importantly, how can my backend pass the api_key to the api server to avoid the error?

```
// http://mydomain.com/shopapi/taxons?ids=11,13

{"error":"You must specify an API key."}
```

I have added the following in my layout:
```
<%= "Spree.api_key = '#{current_user.try(:spree_api_key).to_s.html_safe}';"%> 
```

which successfully set up the api_key value from viewing the html source.

**Comment by JDutil** [comment]
When in the backend you should already be logged in as an admin user so your API key would be taken from the logged in user.  If your not logged in than you need to pas the api key like you've done in the layout.
