### ISSUE TITLE
Using an array instead of a hash for line item creation in the order importer

### ISSUE THREAD

**Issue by BenMorganIO** [spree/spree#5996]
When creating an order with line items, you would have to do an POST to `/api/orders` with:

```json
{
  "order": {
    "line_items_attributes": {
      "1": {
        "variant_id": 113,
        "quantity": 1
      }
    }
  }
}
```

The key for the line item attributes is not very useful and it requires some hacking on the frontend to get, what could have been an array, into a hash.

This issue is here to bring attention to a design flaw, particularly the use of a hash instead of an array. The optimal way, or rather what some JS frontend developers want, is:

```json
{
  "order": {
    "line_items_attributes": [
      {
        "variant_id": 113,
        "quantity": 1
      }
    ]
  }
}
```

---

There was also a change the `Spree::Api::OrdersController` as well. I had decided that I would decorate/overwrite the `Spree::Api::OrdersController#create` with the OrderPopulator. This was the spec I used to ensure it still worked:

```ruby
describe Spree::Api::OrdersController do
  routes { Spree::Core::Engine.routes }

  let!(:user) { create :user }
  let(:admin) { create :admin_user }
  let!(:order) { create :order, user: user }

  describe "#create" do
    let!(:variant) { create :variant }
    let(:order_params) do
      {
        line_items: [
          { variant_id: variant.id, quantity: 1 }
        ]
      }
    end

    it "user does not have an order" do
      post :create, order: order_params
      expect(response.status).to eql 201
    end
  end
end
```

I then decided to take notice of the Deprecation Warning for the OrderPopulator (which I can agree with) and use the Importer. The issue is that my spec is failing even though I've decorated and Spree is still backwards compatible. Maybe we can carry over the array design to the order importer? I'm thinking this will allow for a nice refactor in code as well.

**Comment by JDutil** [comment]
Yea I think making the API change to an Array makes sense, but need to update docs etc...

**Comment by BenMorganIO** [comment]
@JDutil that should be a lot easier than asking a JS dev to change their arrays into hashes with indexes as keys...
