### ISSUE TITLE
Documentation: No explanation on how `#preferences` is serialized

### ISSUE THREAD

**Issue by vinnicc** [spree/spree#6002]
The developer guide on [Preferences](https://github.com/spree/spree/blob/master/guides/content/developer/core/preferences.md) can be improved by explaining how the `preferences` attribute is expected to work when added to a class that doesn't inherit from `Spree::Base`, such as the user class provided by `spree_auth_devise`.

At least the following code is required to make things work properly (taken from `Spree::Base`):
 
```ruby
include Spree::Preferences::Preferable

serialize :preferences, Hash

after_initialize do
  self.preferences = default_preferences.merge(preferences) if has_attribute?(:preferences)
end
```

**Comment by JDutil** [comment]
Would you mind sending a pull request with your suggested improvements to it.
