### ISSUE TITLE
Admin loading indication is gone

### ISSUE THREAD

**Issue by reinaris** [spree/spree#6003]
The admin loading indication isn't showing up when needed.
https://github.com/spree/spree/blob/master/backend/app/views/spree/layouts/admin.html.erb#L12

This loading should show up on ajax requests, see: https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/progress.coffee

**Comment by romul** [comment]
+1
Looks like AJAX-support for all new-forms is also gone. I think, it should be restored, b/c it's not convenient to reload whole page to open smth like /admin/shipping_categories/new.

**Comment by reinaris** [comment]
:+1:
