### ISSUE TITLE
Later pages of product lists won't show when they include deleted products

### ISSUE THREAD

**Issue by ecerta** [spree/spree#6005]
I followed the instructions on [this page] (https://guides.spreecommerce.com/user/deleting_products.html) to display our list of deleted and active products on our website. We have a large number of deleted projects, such that a page 2 is required to list all of them along with our current products. However, when I click the links for page 2 or later, I am redirected to a page that says "NO PRODUCTS FOUND, ADD ONE!"

The only way to get to page 2 or beyond showing these products seems to be manually adjusting the querystring. Here's the URL for page 1 (works automatically)

https://ourwebsite.com/admin/products?utf8=%E2%9C%93&q%5Bname_cont%5D=&q%5Bvariants_including_master_sku_cont%5D=&q%5Bdeleted_at_null%5D=1&q%5Bdeleted_at_null%5D=0&button=

Here's what comes up when I try to click the link for page 2 (doesn't work)

https://ourwebsite.com/admin/products?button=&page=2&q%5Bname_cont%5D=&q%5Bs%5D=name+asc&q%5Bvariants_including_master_sku_cont%5D=&utf8=%E2%9C%93

Here's how we manually adjust the querystring to get to page 2. We just added &page=2 to page 1's querystring (works)

https://ourwebsite.com/admin/products?utf8=%E2%9C%93&q%5Bname_cont%5D=&q%5Bvariants_including_master_sku_cont%5D=&q%5Bdeleted_at_null%5D=1&q%5Bdeleted_at_null%5D=0&button=&page=2

We're using spree 2-4-stable, and while we've put some custom development into our Spree store, none of it is anywhere near these pages.

**Comment by TrangPham** [comment]
@ecerta I have created a test spec to reproduce the issue https://github.com/TrangPham/spree/pull/1/files

Though in my test if I check `page.html` after selecting "Show Deleted" I see that the pagination urls both don't have `deleted_at_null=0` in the url. Thus even clicking on "1" in the pagination list returns "NO PRODUCTS FOUND, ADD ONE!"

I'm also not sure why your link has both `deleted_at_null=1` and `deleted_at_null=0`

**Comment by ecerta** [comment]
I'm no expert on Spree's API, so pardon me if this is a really off-base guess: maybe my example has `deleted_at_null=1` and `deleted_at_null=0` is because I have both non-deleted products and deleted products in my list, whereas your test only has deleted products.

**Comment by priyank-gupta** [comment]
@ecerta This is not longer an issue with 3-0-stable and master branch.
