### ISSUE TITLE
Spree API keys vulnerable to timing attacks

### ISSUE THREAD

**Issue by eliotsykes** [spree/spree#6009]
Spree API users are found with a query that is vulnerable to timing attacks:

```ruby
Spree.user_class.find_by(spree_api_key: api_key.to_s))
```
(from Spree 3.0.0.rc1: [`Spree::Api::BaseController#load_user`](https://github.com/spree/spree/blob/v3.0.0.rc1/api/app/controllers/spree/api/base_controller.rb#L67)).

An attacker can discover API keys through trial and error of API keys and analysis of the speed of response. 

Devise had this vulnerability (reported by @yfeldblum I believe, who also originally discovered and reported [this same vulnerability with Spree in 2012](https://github.com/spree/spree/issues/2330)). There is a solution given in #2330 and a similar solution was suggested for Devise in [this gist](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6#file-2_safe_token_authentication-rb) (see the 2nd option, not the 1st one which is insecure).

**Comment by schof** [comment]
Please do not report security vulnerabilities (or suspected vulnerabilities) via GH issues.  Please report any suspected issues to security@spreecommerce.com.

Thanks
