### ISSUE TITLE
ssl_required? in spree/core/lib/spree/core/controller_helpers/ssl.rb is missing configs for QA environments

### ISSUE THREAD

**Issue by jasonfb** [spree/spree#6018]
In spree 2.1-2.4, the file at spree/core/lib/spree/core/controller_helpers/ssl.rb is missing options for Rails QA environments. 

the method looks like so:
```
    def ssl_supported?
            return Spree::Config[:allow_ssl_in_production] if Rails.env.production?
            return Spree::Config[:allow_ssl_in_staging] if Rails.env.staging?
            return Spree::Config[:allow_ssl_in_development_and_test] if (Rails.env.development? or Rails.env.test?)
    end
```

This method is missing options for the QA environments, which is a valid Rails environment. We rely heavily on our QA environments and need to test the SSL features of the website against our QA environments. 

Unfortunately I am unable to over-ride this method in my own application, when I do so, I get the error below. 

Can you suggest a way to override this? If I am unable to do so, I will need to patch the Spree core to include an option for QA. 

Circular dependency detected while autoloading constant Spree::Core::ControllerHelpers::SSL
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:461:in `load_missing_constant'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/app/helpers/spree/core/controller_helpers/ssl.rb:1:in `<top (required)>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:330:in `require_or_load'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:463:in `load_missing_constant'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/bundler/gems/spree-cdb4c5a50a58/api/app/controllers/spree/api/base_controller.rb:8:in `<class:BaseController>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/bundler/gems/spree-cdb4c5a50a58/api/app/controllers/spree/api/base_controller.rb:5:in `<module:Api>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/bundler/gems/spree-cdb4c5a50a58/api/app/controllers/spree/api/base_controller.rb:4:in `<module:Spree>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/bundler/gems/spree-cdb4c5a50a58/api/app/controllers/spree/api/base_controller.rb:3:in `<top (required)>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:330:in `require_or_load'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:463:in `load_missing_constant'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/bundler/gems/spree-cdb4c5a50a58/api/config/initializers/metal_load_paths.rb:1:in `<top (required)>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `each'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `block in <class:Engine>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `each'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/config/environment.rb:5:in `<top (required)>'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
       /tmp/build_f78bcd867c275c154b4caab0ce2291c0/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !

 !     Push rejected, failed to compile Ruby app

**Comment by JDutil** [comment]
Most people use staging as their qa environment.  If you'd like to change it I would override the entire file rather than trying to class eval it or module prepend to avoid the circular dependency.
