### ISSUE TITLE
uninitialized constant Paperclip::Storage::S3::AWS

### ISSUE THREAD

**Issue by jaemo** [spree/spree#6021]
As the name suggests, I am having issues getting spree to work with S3. 

I am using 2.4.1 (branch 2-4-stable)
I have paperclip 4.2.0
I have aws 2.0.22

I have followed the guide here: https://guides.spreecommerce.com/developer/s3_storage.html
I have manually created my buckets (just to be sure they exist)

When I try to update an image I get:

NameError in Spree::Admin::ImagesController#update
uninitialized constant Paperclip::Storage::S3::AWS

Please help!

**Comment by jaemo** [comment]
I've reverted to 2-3-stable. It works fine there.

**Comment by peterberkenbosch** [comment]
You have to use the v1 gem from aws-sdk. Also see http://peterberkenbosch.nl/store-your-spree-images-on-s3/
