### ISSUE TITLE
fresh install spree 2.4 stable problem

### ISSUE THREAD

**Issue by ccfiel** [spree/spree#6023]
Hello,

I have followed the step in how to install spree
1. gem install rails -v 4.1.8
2. gem install bundler
3. sudo apt-get install imagemagick 
4. gem install spree_cmd
5. rails _4.1.8_ new mystore
6. cd mystore
7. spree install --auto-accept
then after that I got this error

git://github.com/spree/spree_auth_devise.git (at 2-4-stable) is not yet checked out. Run `bundle install` first.

I tried to bundle install after that I got the same error.

Any Ideas?

**Comment by peterberkenbosch** [comment]
try removing Spring from you gemfile. There has been an issue with the
recent Spring version.

On Mon, Feb 9, 2015 at 1:09 AM, Chris Ian Fiel <notifications@github.com>
wrote:

> Hello,
>
> I have followed the step in how to install spree
> 1. gem install rails -v 4.1.8
> 2. gem install bundler
> 3. sudo apt-get install imagemagick
> 4. gem install spree_cmd
> 5. rails *4.1.8* new mystore
> 6. cd mystore
> 7. spree install --auto-accept
> then after that I got this error
>
> git://github.com/spree/spree_auth_devise.git (at 2-4-stable) is not yet
> checked out. Run bundle install first.
>
> I tried to bundle install after that I got the same error.
>
> Any Ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spree/spree/issues/6023>.
>



-- 

Peter Berkenbosch
Spree Commerce, Inc.

**Comment by AKovtunov** [comment]
same issue

**Comment by funkdified** [comment]
I had this issue too... Are you using RVM?

**Comment by ccfiel** [comment]
@funkdified yes im using rvm. how did you solve the problem?

**Comment by ccfiel** [comment]
@peterberkenbosch I tried your suggestion but still got the error :( any other ideas?

**Comment by funkdified** [comment]
@ccfiel I haven't actually had time to look at the issue yet.. but I did some googling, and thought this issue might be related http://stackoverflow.com/questions/22554365/bundle-doesnt-want-to-install-a-gem-not-yet-checked-out

**Comment by ccfiel** [comment]
@funkdified Thanks it works! :+1:

**Comment by funkdified** [comment]
You're very welcome! There should probably be some mention of RVM in the wiki...

**Comment by AKovtunov** [comment]
Just for other users: for me everything was fixed with method from @peterberkenbosch suggestion

**Comment by redglory** [comment]
@peterberkenbosch suggestion solved my problem. Couldn't start rails console, just for reference...

**Comment by leckylao** [comment]
Tried @funkdified suggestion on stackoverflow doesn't work. Then tried remove spring as @peterberkenbosch suggest and it works. interesting issue. :+1:

**Comment by dankex** [comment]
agree with @leckylao 

removing the gem "spring" works.
