### ISSUE TITLE
Attachment has an extension that does not match its contents

### ISSUE THREAD

**Issue by igorkrup** [spree/spree#6026]
When trying to add image to product i get an flash error "Attachment has an extension that does not match its contents". I'm uploading jpg file (every jpeg). Running development enviroment locally (Windows 7, ImageMagick Installed). Also no images after demo installation. Any ideas where to start solving the problem.

**Comment by mtomov** [comment]
Have a look at the content type of the image. I am not sure how to look it up on Windows. It must be `image/jpeg`, `image/jpg`, basically any one of those listed on the `[Image.rb validation](https://github.com/spree/spree/blob/master/core/app/models/spree/image.rb#L13)`

Run the console and try assigning image manually. Something like that:
```
image=Spree::Image.new :attachment => File.new(Rails.root + 'public/image.jpeg')
image.viewable = Spree::Variant.take
image.save!
```

If that fails, try comment out the above validation on image and try again (maybe you could do that first even).

Good luck!

**Comment by JDutil** [comment]
Yup you'll need to make sure the content type meets that linked imbage.rb validation.  Otherwise you can modify the image class to use your own validation definition if you'd like to open up to more content types.

**Comment by igorkrup** [comment]
Thanks a lot guys. None of the above worked ;) , but they were a HUGE help.
That was problem with PaperClip gem and Windows :worried:, which has problems with determining mime type.
I've found a solution [here](http://blogs.pigrider.com/blogs/57)

**Comment by mtomov** [comment]
Good find! Give a linux machine a try ; ) The [Elementary OS](http://beta.elementaryos.org/) distro has a brand new release, which is very beautiful and easy to use.
