### ISSUE TITLE
Spree::Product.updated_at should be modified after PATCH /api/products/{id}

### ISSUE THREAD

**Issue by edmondchui** [spree/spree#6035]
In the [Spree::API::ProductController#update](https://github.com/spree/spree/blob/master/api/app/controllers/spree/api/products_controller.rb#L74-L86) method
```ruby
@product = find_product(params[:id])
authorize! :update, @product
options = { variants_attrs: variants_params, options_attrs: option_types_params }
@product = Core::Importer::Product.new(@product, product_params, options).update
if @product.errors.empty?
  respond_with(@product.reload, :status => 200, :default_template => :show)
else
  invalid_resource!(@product)
end
```

The ```updated_at``` is not modified by the call ```Core::Importer::Product#update```.

Also, the ```@product.reload``` call seems unnecessary in the ```respond_with``` line.

I think the fix includes two parts:

1. Set the ```updated_at``` to ```Time.now``` before ```update``, i.e. change

    ```ruby
    @product = Core::Importer::Product.new(@product, product_params, options).update
    ```
    to
    ```
    @product = Core::Importer::Product.new(@product, product_params, options)
    @product.updated_at = Time.now
    @product.update
    ```

2. Get rid of the necessary reload, i.e. change

    ```ruby
      respond_with(@product.reload, :status => 200, :default_template => :show)
    ```
    to
    ```
      respond_with(@product, :status => 200, :default_template => :show)
    ```

**Comment by JDutil** [comment]
Would you mind submitting a PR?

**Comment by edmondchui** [comment]
1. A better place to fix the issue is within ```Spree::Core::Importer::Product#update```. We just touch the product before returning at the end of the ```update``` method. Touching the product has the benefit of calling the ```after_touch``` callbacks on ```Spree::Product```.

2. We cannot get rid of the ```@product.reload``` call at the end of ```Spree::Api::ProductController#update``` because the ```reload``` call actually reload all updated associations.

**Comment by JDutil** [comment]
Could you submit another PR against this repo?

**Comment by nishant-cyro** [comment]
@edmondchui - This one is working fine for me in master branch.

cc: @priyank-gupta @Mafi88 @damianlegawiec
