### ISSUE TITLE
better_spree_paypal_express spree_core dependency failure

### ISSUE THREAD

**Issue by bmurtagh** [spree/spree#6045]
I'm attempting to contribute to the better_spree_paypal_express extension, however when initiating a `bundle install` as part of their starting point instructions, the bundle fails because `spree_core (~> 3.0.0.beta` cannot be found. 

I've opened https://github.com/spree-contrib/better_spree_paypal_express/issues/150 as a result, but not sure if the issue should be opened here since I'd consider this the 'spree_core'. Also, as mentioned in issue 150, I viewed all versions on the rubygems.org site for spree_core and attempted to replace:

`s.add_dependency 'spree_core', '~> 3.0.0.beta'`
with
`s.add_dependency 'spree_core', '~> 3.0.0.rc1'` in `spree_paypal_express.gemspec` 

The same error was produced, just with the rc1 version mentioned.

**Comment by JDutil** [comment]
Issues with better_spree_paypal_express should be opened there not here.  I would attempt to use `bundle update` rather than bundle install.  If that still doesn't work make sure the Gemfile is pointing the proper git branch.
