### ISSUE TITLE
README.md fast installation instructions uses an incompatible version of rails

### ISSUE THREAD

**Issue by Rayhul** [spree/spree#6067]
The installation instructions in the readme file seem to contain an error where it is implied that a "gem install spree" command will work with rails 4.2.0.  The spree that is currently installed using this command utilizes spree_core 2.4.3 which depends on rails 4.1.8 to work--not rails 4.2.0.

**Comment by JDutil** [comment]
If you read the first line of the readme:
`THIS README IS FOR THE MASTER BRANCH OF SPREE AND REFLECTS THE WORK CURRENTLY EXISTING ON THE MASTER BRANCH. IF YOU ARE WISHING TO USE A NON-MASTER BRANCH OF SPREE, PLEASE CONSULT THAT BRANCH'S README AND NOT THIS ONE.
`

We note that this is for the current state of work, and not of the latest release. Please see the readme on the 2-4-stable branch for version 2.4.3:
https://github.com/spree/spree/tree/2-4-stable
