### ISSUE TITLE
2-3-stable gem release?

### ISSUE THREAD

**Issue by urbanautomaton** [spree/spree#6071]
We're currently using Spree 2.3, and have been depending directly on the 2-3-stable branch of the git repo, since there have been [a number of fixes](https://github.com/spree/spree/compare/v2.3.6...2-3-stable) since the last gem release of the 2.3 branch, 2.3.6.

However, we'd really like to switch back to using the gem, not least because the spree repo is quite large, and pulling it on deploy tends to be slow (as is storing and fetching it from the heroku cache).

Would it be possible to make a 2.3.7 gem release? It'd be a big help.

Thanks,
Simon

**Comment by JDutil** [comment]
@urbanautomaton there are 1 or 2 bugs I'm working to resolve today before doing the latest 2.4.x and 3.0.x releases, and I'll see about doing 2.3.x as well.

**Comment by urbanautomaton** [comment]
Thanks very much, appreciate it. :+1:

**Comment by JDutil** [comment]
Done
