### ISSUE TITLE
Spree::Variant aftercreate set_position does not work properly on productduplicator

### ISSUE THREAD

**Issue by u007** [spree/spree#6076]
need to reevaluate used of set_position on after create when used in productduplicator.
the max value does not take array of variants that has been saved or does not take updated variants of the current product when after create.

**Comment by priyank-gupta** [comment]
@u007 Can you please elaborate with specimen code ? Will help us replicating the issue.

**Comment by priyank-gupta** [comment]
@u007 Seems like this issue is a part of 2.x as `Variant#set_position` has been removed in 3.x.

**Comment by u007** [comment]
yes,im using 2.4-stable
is it totally being replaced i 3.x?

**Comment by priyank-gupta** [comment]
@u007 Not exactly, but its been used via `acts_as_list` which seems to fix this issue.

**Comment by u007** [comment]
is it available on 2.4?
how do i use it?

**Comment by priyank-gupta** [comment]
@u007 Yeah, its available in spree version 2.4.8.
https://github.com/spree/spree/blob/v2.4.8/core/app/models/spree/variant.rb#L4
and `set_position` is remove here https://github.com/spree/spree/commit/01fd680c412dece66974f0c300081702c23e6bc6.
