### ISSUE TITLE
'Hide Cents' option still shows cents in cart price

### ISSUE THREAD

**Issue by redconfetti** [spree/spree#6084]
@radar I'm really disappointed. The cents is still showing in the cart price in the header, idiot!!

:goberserk: :-1: :poop: :rage2: :rage3:  :no_smoking:

![image](https://cloud.githubusercontent.com/assets/746759/6364752/303de1b2-bc60-11e4-9971-cf66b42fa67c.png)

:trollface:

**Comment by redconfetti** [comment]
P.S. I'm totally kidding. Just pointing this possible over-sight out.

Just a note, it might be smart to make this feature only hide the decimal if there is no tenth or hundredth value. I couldn't imagine the calculated tax being an exact dollar amount even if the products are all configured with a whole dollar amount.

**Comment by JDutil** [comment]
This feature has been removed from newer versions so going to close this out as I don't expect us to remove the feature from older stable branches.

**Comment by redconfetti** [comment]
Thanks @JDutil . BTW, I just realized that Ryan left last year. Doh!
