### ISSUE TITLE
User Model  error for spree_api_key in customized user model

### ISSUE THREAD

**Issue by cdesch** [spree/spree#6091]
In spree 3.0.0rc4, when customizing the `Spree.user_class` to `User` such that spree uses the devise rails host app as shown in [this customization](https://guides.spreecommerce.com/developer/authentication.html). 

    #initializers/spree.rb
    Spree.user_class = "User"

I get this error from the `Spree::Auth::Engine.load_seed if defined?(Spree::Auth)` line in `db/seeds.rb`
 
     Spree::Core::Engine.load_seed if defined?(Spree::Core)
     Spree::Auth::Engine.load_seed if defined?(Spree::Auth)

        loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-6d8721e0e19d/core/db/default/spree/countries.rb
	loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-6d8721e0e19d/core/db/default/spree/roles.rb
	loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-6d8721e0e19d/core/db/default/spree/states.rb
	loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-6d8721e0e19d/core/db/default/spree/stores.rb
	loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree-6d8721e0e19d/core/db/default/spree/zones.rb
	loading ruby /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/spree_auth_devise-07f16255c8e8/db/default/users.rb
	Create the admin user (press enter for defaults).
	Email [spree@example.com]: 
	Password [spree123]: stty: stdin isn't a terminal
	stty: stdin isn't a terminal

	stty: stdin isn't a terminal

	rake aborted!
	NoMethodError: undefined method `spree_api_key=' for #<Spree::User:0x007f83eb057578>

I've double checked and my `User` model has the `spree_api_key` as I have run `bundle exec rails g spree:custom_user User` and `bundle exec rake db:migrate` commands and confirmed the fields in the database. Why am I getting this error?

If I change the `db/seeds.rb` by removing the ` Spree::Auth::Engine.load_seed if defined?(Spree::Auth)` line and adding the following lines

     user = User.create(email:'example@example.com', password:'password', password_confirmation: 'password')
     user.spree_roles << Spree::Role.find_or_create_by(name: "admin")

I get the following error:

       NoMethodError: undefined method `spree_roles' for #<User:0x007f84079078a0>

Doing it in the rails console doesnt seem to have an effect

	Loading development environment (Rails 4.2.0)
	[1] pry(main)> User.first.spree_roles << Spree::Role.find_or_create_by_name("admin")
	  User Load (0.1ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
	NoMethodError: undefined method `spree_roles' for #<User:0x007fbce1532140>
	from /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
	[2] pry(main)> 

Is there something I need to add to my `User` model or was this a change from spree 2.4 to spree 3.0 with the documentation being out of date? I see that there is a `spree_roles_users` table where I am assuming the association should go. How can I assign an admin role to my user in the `seeds.rb`?

these are the gems I'm using for spree ` 3.0.0.rc4`

     gem 'spree', github: 'spree/spree', branch: '3-0-stable'
     gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
     gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

**Comment by cdesch** [comment]
this does seem to worth either 

        Loading development environment (Rails 4.2.0)
	[1] pry(main)> User.create(email:'example1@example.com', password:'password', password_confirmation: 'password', spree_roles: Spree::Role.find_or_create_by(name: "admin") )
	  Spree::Role Load (0.1ms)  SELECT  "spree_roles".* FROM "spree_roles" WHERE "spree_roles"."name" = ? LIMIT 1  [["name", "admin"]]
	ActiveRecord::UnknownAttributeError: unknown attribute 'spree_roles' for User.
	from /Users/cj/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'

**Comment by JDutil** [comment]
```
rake aborted!
NoMethodError: undefined method `spree_api_key=' for #<Spree::User:0x007f83eb057578>
```
That's indicating it was trying to use Spree::User not your User model.

The spree_roles association should be being added by:
https://github.com/spree/spree/blob/master/core/config/initializers/user_class_extensions.rb

Since you haven't provided the information requested in [contributing guidelines](https://github.com/spree/spree/blob/master/CONTRIBUTING.md#filing-an-issue) it's difficult to say, but I'm guessing that you're trying to mix using spree_auth_devise with using your own user class instead. That is not how it's meant to be used.  spree_auth_devise will set your Spree.user_class = 'Spree::User' and maybe overriding your custom User class.  So remove spree_auth_devise if you've included it in your application.

**Comment by cdesch** [comment]
Yes!! That is what fixed it. Thank you. 

I removed the `gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'` from the `Gemfile`

    gem 'spree', github: 'spree/spree', branch: '3-0-stable'
    gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
    #gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'


Another issue was that the order in which the models were created in the  `seeds.rb`.  I needed to have the `user` setup after the `Spree::Core....` and remove the `Spree::Auth...` line, like this:

	Spree::Core::Engine.load_seed if defined?(Spree::Core)
	#Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
	user = User.create(email:'example@example.com', password:'password', password_confirmation: 'password')
	user.spree_roles << Spree::Role.find_or_create_by(name: "admin")

The documentation isn't quiet clear in that respect for using your own authentication mechanisms. Would you mind if I made a pull request to update that?

Thank you again for your help!!

**Comment by JDutil** [comment]
Yes please do submit a PR to help clear up any confusion.  I believe someone else had a similar issue because they read the "background" section and thought it meant to add spree_auth_devise, but in reality that section is saying that's how it's done if you don't want to roll your own auth.  Probably adding a big warning block to the background section indicating that's not a step to follow would help along with any other suggestions you have.
