### ISSUE TITLE
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_spree_preferences_on_key

### ISSUE THREAD

**Issue by BenMorganIO** [spree/spree#6092]
When accessing promotions or starting up the rails application, sometimes, users will receive this error. It happened to me randomly when I was trying to apply a promotion. Recently, a developer has been receiving this when he boots up his rails application. This seems to be an error in the wild. No one knows where it comes from, but it happens in postgres and I'm absolutely not sure why or how it gets produced.

Since I do not know why it is being produced, I'm posting it as an issue. The fix for this is simple:

``` sql
SELECT setval('spree_preferences_id_seq', (SELECT MAX(id) FROM spree_preferences));
```

But we shouldn't have to do that. I do not believe this issue application specific. If I can make a reproduction, I'll post it. If anyone else has experienced this, please +1.

**Comment by masterkain** [comment]
This might happen on startup when some gems attempts to write/set preferences.

Last one for me originated here: https://github.com/spree-contrib/spree_editor/blob/master/lib/spree_editor/engine.rb#L9

**Comment by BenMorganIO** [comment]
You're right. Might, a) be an issue with Rails application loading (or Spree's) or b) SoL.
