### ISSUE TITLE
Default from address for Spree::BaseMailer can't be edited in the admin panel

### ISSUE THREAD

**Issue by romul** [spree/spree#6096]
This setting looks outdated: https://github.com/spree/spree/blob/3-0-stable/core/app/mailers/spree/base_mailer.rb#L5
I think, `Spree::Store.current.mail_from_address` should be instead of Spree::Config[:mails_from], b/c it should be editable from the admin panel.

**Comment by JDutil** [comment]
Yes it should begin using store setting, but need to update specs etc.. to work.  Not sure best solution to that to avoid constantly setting up store record before every spec.  Will want to have a spec helper to mock/stub it out.
