### ISSUE TITLE
`x64_mingw` is not a valid platform

### ISSUE THREAD

**Issue by Julyyq** [spree/spree#6098]
When I follow the installation instructions on __Working with the edge source (latest and greatest features)__, I got the following error after `bundle install`, I checked [Gemfile man](http://bundler.io/v1.3/man/gemfile.5.html) and find `x64_mingw` is not a platform option.  Then I remove the `x64_mingw` option It works fine. But why this happens? Thank you.

    `x64_mingw` is not a valid platform. The available options are: [:ruby, :ruby_18,
    :ruby_19, :ruby_20, :mri, :mri_18, :mri_19, :mri_20, :rbx, :jruby, :mswin, :mingw,
    :mingw_18, :mingw_19, :mingw_20]
 
My ruby version: `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

My Rails version: `Rails 4.2.0`

My platform: Mac 10.10 yosemite

**Comment by JDutil** [comment]
I'm not sure why this would be causing you a problem, but I would guess it's from using an outdated ruby and/or rubygems version.  Edge spree requires ruby 2.1+ https://github.com/spree/spree/blob/master/core/spree_core.gemspec#L11 so you'll want to update to ruby 2.2.0 and give that a shot.

**Comment by Julyyq** [comment]
I update the ruby version to 2.2.1, but the problem still exists. I think I have to just remove `x64_mingw `.
