### ISSUE TITLE
Should JSONP still be available?

### ISSUE THREAD

**Issue by mvz** [spree/spree#6105]
The commit message for the recent security fix (committed to master as bfb5f907219d6f8f879ca940882befe89b58a1a4) suggests JSONP support is removed. However, the `set_jsonp_format` filter is still present. Shouldn't this have been removed as well?

**Comment by JDutil** [comment]
Hmm not sure how that change wasn't still included must not have properly squashed it into the commit.  The security problem is still resolved, but yea we wanted to remove jsonp too thanks for pointing that out.

**Comment by JDutil** [comment]
Good catch thanks.
