### ISSUE TITLE
API Routes using concern instead of redirect

### ISSUE THREAD

**Issue by BenMorganIO** [spree/spree#6110]
Noticed that when #6046 was merged, it didn't include the redirect.

https://github.com/spree/spree/pull/6046/files#diff-cec8b31590fabd58186af04b474be177L9

vs

https://github.com/spree/spree/blob/4bd99d9d3bb500d92660c006738324ce7cab0f6f/api/config/routes.rb

**Comment by BenMorganIO** [comment]
If we want to keep the `concern`, we should `scope module: v1`, otherwise, I think the specs should be failing for the versioned api.

**Comment by BenMorganIO** [comment]
Yeah, this should be failing, but its not: https://github.com/spree/spree/blob/master/api/spec/requests/version_spec.rb#L7

**Comment by BenMorganIO** [comment]
And I don't think we'll be doing:

```ruby
namespace :v2 do
  concerns :api
end
```

I can say that because I'm thinking some Ember/Angular guys are going to want to make the API more flexible and/or follow some better practices. But by and large, there will probably be duplication. Maybe we could make chunks of concerns?

**Comment by JDutil** [comment]
Definitely don't want to use the concerns :api, but doing smaller concerns would be alright if we don't want to change it from v1 to v2.  We certainly aren't going to have all the same exact routes between new and old version, and I'd rather give us the freedom to make changes to v2 as we see fit without worrying about v1 being effected.
