### ISSUE TITLE
Registered as guest order appears on new account

### ISSUE THREAD

**Issue by paulhuisman** [spree/spree#6117]
When i'm ordering a product in the shop, and i checkout as a guest, everything goes swell. 

Once this is finished, i want to start a new order and during the checkout process i register a new account with a new email address. Once my account is created, i view my "account page" (i'm automatically logged in) and i see the order that was made with the first email address (as guest). 

Of course, this is not suppose to happen since i have entered two different email addresses. 

Are you able to reproduce this? I reckon this might have something to do with a "guest session" not being reset when creating a new account.

PS: I'm using 2-3-stable with Rails 4.1

**Comment by JDutil** [comment]
This would be because the orders were linked with the cookie tracking your device, and once you created your account it linked your orders:
https://github.com/spree/spree_auth_devise/blob/master/config/initializers/warden.rb

**Comment by paulhuisman** [comment]
Thanks for your quick reponse. I'll adjust it my code where necessary.

**Comment by JDutil** [comment]
If you'd like to submit a PR we may want to make that optional with a configuration setting.
