### ISSUE TITLE
product_option_type_ids - Filter chain halted as :authenticate_user rendered or redirected

### ISSUE THREAD

**Issue by connecticus** [spree/spree#6122]
When I try to add a option types error occurs.

Started GET "/api/option_types?ids=2,3" for 127.0.0.1 at 2015-03-05 17:01:04 -0800
Processing by Spree::Api::OptionTypesController#index as JSON
  Parameters: {"ids"=>"2,3"}
  Spree::User Load (1.1ms)  SELECT  "spree_users".* FROM "spree_users"  WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."spree_api_key" = '' LIMIT 1
  Rendered /home/kate/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/spree-828e23e00e40/api/app/views/spree/api/errors/must_specify_api_key.v1.rabl (0.8ms)
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 1118ms (Views: 1112.1ms | ActiveRecord: 1.1ms)

Outwardly, it appears that additional options are not displayed (although I can create variants).

**Comment by connecticus** [comment]
temporary fix - add Spree::Api::Config[:requires_authentication] = false

**Comment by JDutil** [comment]
which spree version/branch?  this is caused by the security patch, and not picked up in the regression tests

**Comment by connecticus** [comment]
Hi, dear Jeff,

last 2.3, 2.4 (3.X - not sure)

Regards, Kate.
