### ISSUE TITLE
New Admin Order does not assign a Store ID

### ISSUE THREAD

**Issue by davekiss** [spree/spree#6126]
In Spree 2.4, creating a new order from the frontend assigns a store ID to the order thanks to the [`current_order_params` helper](https://github.com/spree/spree/blob/bb06fca0a0efb6b6e915a1ac95a21ece767b8253/core/lib/spree/core/controller_helpers/order.rb#L81-L83), but when creating an order in the backend, the only parameter provided to the new order is the [`created_by_id`](https://github.com/spree/spree/blob/bb06fca0a0efb6b6e915a1ac95a21ece767b8253/backend/app/controllers/spree/admin/orders_controller.rb#L128-L131), which is much less explicit. This is causing orders created on the backend to fail when attempting to be loaded on the frontend due to a mismatched `store_id` of `1` vs `nil` 

Can the new admin order reuse the code in the `current_order_params` helper?

To reproduce:
- Log in to a fresh Spree install, visit the orders page and click +New Order
- Inspect the Order's `store_id` in the rails console

Related:
https://github.com/spree/spree/commit/15df7e7133c77e6724eb5ad1fb8f7cf755c42799

**Comment by JDutil** [comment]
I don't think using current_order_params would be appropriate as it contains customer specific information like user_id and guest_token.  Would be fine to submit a PR that assigns the store_id though.
