### ISSUE TITLE
Cart link not showing when spree is mounted on '/shop'

### ISSUE THREAD

**Issue by casalgado** [spree/spree#6131]
When routes are set to: 
         mount Spree::Core::Engine, :at => '/shop' 
the cart link disappears. If set back at '/ ', the cart link is revealed and working correctly. How can this be fixed?

**Comment by JDutil** [comment]
You may need to recompile your assets in order for the changed mount point to take effect, but once it's set in your js this resolves itself:
https://github.com/spree/spree/blob/master/core/app/assets/javascripts/spree.js.coffee.erb#L7

**Comment by casalgado** [comment]
I get this error when trying to precompile:

ActionController::RoutingError (No route matches [GET] "/cart_link"):
