### ISSUE TITLE
Impossible to implement new European tax law for digital goods (as of 1/1/2015)

### ISSUE THREAD

**Issue by mamhoff** [spree/spree#6154]
As of the 1st of Jan, 2015, the European Commission has blessed us with the following fine piece of [legislation](http://monadsolutions.co.uk/solutions/eu-mini-one-stop-shop-vat-solution.html):

> ### Key regulatory changes
>
> - Taking effect on 1 January 2015, EU VAT regulatory changes impact companies supplying telecommunications, broadcasting and electronic services to EU customers.
> - Member States must allow suppliers to register on a MOSS from 1 October 2014.
> - Instead of companies applying VAT according to VAT rates for the country in which they are registered, the VAT on these services becomes payable where their end customer belongs.

This is currently almost, but not quite possible with Spree's zone-based taxation system. We have to output prices including VAT, and depending on which type of good (digital vs physical), different VAT rules apply:

- Physical goods: Regardless of destination, all prices carry the VAT of the **origin** country.
- Digital goods: If sold to consumers, all prices carry the VAT rate of the **destination** country.

### Example:

A cart containing a shirt and a music file to be downloaded ordered from Denmark in a web store based in Germany has to apply two different VATs:

 - 19% German VAT on the shirt, as it is a physical good
 - 25% Danish VAT on the downloaded music file.

### Difficulties with Spree's current taxation model

In order to achieve correct taxation, we created tax rates and corresponding zones for each individual EU member state (for digital goods). We also created a tax rate and zone for all EU countries with the German VAT (as our client is based in Germany).

This works, but only as long as we display prices excluding VAT, which is not allowed in the EU. If we switch to prices including tax, Spree has difficulty calculating the correct tax rate: Because we can only set one "default tax zone" (EU for physical goods), with digital goods the net price changes depending on which country you order from, which can not possibly be correct (a download with a gross price of 10 EUR would have a net price of 8.10 when ordered from Germany and of 7.50 when ordered from Denmark.

We need Spree to calculate the net price always from the zone in which the retailer is based. To achieve this, we propose the following:

The default tax zone should be a `belongs_to` relation on the `TaxCategory` model. This way, Spree should be able to correctly assess which `TaxRate` to use to calculate the net price for different kinds of products.

This only makes sense for VATs which have to be displayed as included in the price. Thus, if it is not set, that would mean the tax is normal ('Sales') tax which is applied additionally.

As you would expect, this is a big change deep in Spree's taxation code. This is the only way we could think of to solve this difficult problem so far, we'd love to have your feedback on this issue.

We started [work on a branch](https://github.com/magiclabs/spree/tree/better-tax-zones), and will publish a (probably breaking) PR shortly to illustrate our proposal and work this out collaboratively.

**Comment by JDutil** [comment]
I :heart: Taxes :-/

**Comment by tvdeyen** [comment]
@JDutil especially in the EU!

**Comment by JDutil** [comment]
I'm actually in favor of the EU approach over US our sales tax system is a mess, and makes VAT look easy peasy.

**Comment by tvdeyen** [comment]
Ah, tax sucks everywhere ;)

The problem is, that we currently focus on some other features in our next sprint. So, sadly this has to wait until the week after next. If someone has some great ideas on how to refactor this, please feel free to put in some advices in here, so we can respect them.

BTW: Magento (the shop system we are replacing right now) DOES NOT make it right either. It is actually a big mess here in Europe, that nearly no shopping system can handle this messy law right correctly. 

So, if we (the spree community) get this right, this is a real advantage over lots of shopping systems!

**Comment by jpmacca** [comment]
@mamhoff Try our [Taxamo](http://www.taxamo.com/how-it-works/) solution.

Repo [here](https://github.com/taxamo).

@tvdeyen we have just released a Magento module to handle EU VAT compliance. 

Available from Magento Connect [here](http://www.magentocommerce.com/magento-connect/taxamo-for-new-eu-vat-calculation-and-moss-reporting-1.html).

**Comment by tvdeyen** [comment]
@jpmacca Wow, this is a whole new level of marketing! Scanning GitHub issues? Thanks for mentioning your **product**, but I think you are wrong here....

**Comment by mamhoff** [comment]
I've been spending quite some time over the last couple of days in looking at the tax calculation code in Spree, and I've found some issues. I now think that the solution we outlined above, that of having different ```default_tax_zones``` for item categories, would be a hacky way of dealing with Spree's current handling of taxes that are "included in price". 

### Current situation

The fundamental issue is that the ```pre_tax_amount``` - which is the shop's base price for an item - is calculated dynamically every time an order is updated, using whatever ```Spree::TaxRate``` is set as ```included_in_price```. Included tax rates then generate an adjustment which does not change the (gross) price, unless the order's zone is outside the default zone, in which case the following happens: 

- The tax rate from the default zone is [deleted from the array of applicable rates](https://github.com/spree/spree/blob/master/core/app/models/spree/tax_rate.rb#L51-L61)
- The VAT from another tax zone is applied, does ***not*** change the gross price, ***but*** [changes the ```pre_tax_amount```](https://github.com/spree/spree/blob/master/core/app/models/spree/tax_rate.rb#L67-L79) - the ***net*** price of the item. This can only be correct if the two VATs (destination VAT and default VAT) have the same amount.

### Desired situation

VATs, in real life, do not change how much a merchant charges. VATs change what prices look like. More technically: ```TaxRate.adjust``` should change the ```price``` of a line item depending on which ```TaxRate```s are included in price for that ```Zone```. The price of the line item should then be calculated as the ```pre_tax_amount``` plus whatever ```included_in_price``` rates apply. 

This should fulfil the following requirements: 
An order with one line item (a download) priced at 100 € to Germany should cost 100€ if sent to Germany. At 19% German VAT, that means a price of 100 Euros, a ```pre_tax_amount``` of 84,03 Euros, and 15,97 Euros VAT as an included adjustment. 

If the same order is ordered from the US, the price of the CD on the invoice should simply be 84,03 Euros, with no adjustments (as no taxes apply for that transaction). Currently, Spree handles this as 100 Euros ***minus*** a 15,97 VAT refund adjustment. No need. 

If that same order would be now sent to a country with a different VAT of, say, 25%, we should have again: a price of ```84,03 * 1,25 = 105,04``` with an included adjustment of 21,01 Euros. The ```pre_tax_amount``` for this line item does not, and should not, change. 

### Configuring Spree for MOSS with this setup

If things were implemented like this, the MOSS mess could be accommodated for with the following set-up: 

You have zones for all EU countries, including the shop's residence country. 
The shop's residence zone is the default zone.

Now, for different tax categories to be taxed with different VATs you simply create TaxRates that apply to digital products, are ```included_in_price```, and have an ```amount``` reflecting VAT rates in this country. 

For all normal products, you create TaxRates with the German VAT and zones inside the EU, but outside Germany. 

### Call for community participation

While we believe that this is correct, we do not know what the requirements of other shops are. Can you reach out to people and find out whether our reading of what VAT is would fulfill their needs?

### Implementation details

Currently, ```TaxRate.potential_rates_for_zone``` [always includes](https://github.com/spree/spree/blob/master/core/app/models/spree/tax_rate.rb#L51-L61) the default_tax_zone rate for that product category. I believe it's easier if we just do this: 

```
    def self.potential_rates_for_zone(zone)
      self.where(zone_id:
        Spree::Zone.potential_matching_zones(zone).pluck(:id))
    end
```

The default_zone should only be used for

1. showing prices in the front-end to users without an address (those prices have to include VAT, so they'll have to be calculated dynamically)
2. (optional) If in the backend prices have to be ***entered*** including VAT, it should be used to calculate the ```pre_tax_amount``` on line items. Once, when they're created. Spree's input label translations hint at [that being the default anyway](https://github.com/spree-contrib/spree_i18n/blob/master/config/locales/de.yml#L799).


I did look at the threads https://github.com/spree/spree/issues/4397 and https://github.com/spree/spree/issues/4327, as well as at https://github.com/spree/spree/issues/4318#issuecomment-34723428 

Stuff that will need changes: 
https://github.com/spree/spree/blob/master/core/app/models/spree/adjustable/adjustments_updater.rb#L43

**Comment by mamhoff** [comment]
We will now start to implement something along the lines of the stuff I mentioned above. The idea is the following: 

 - Prices, discounts, shipping rates, etc. will *always* be entered without VAT (just like in the US). 
 - Variants and Line items both will get a method that presents the price including VAT for the default zone or the order's user zone. 
 - In the course of this, we'll be have to be changing some tests, too. 

The difference between VAT and sales tax is really an issue of displaying prices, discounts and shipping rates to users. In terms of how calculation is done, it is actually very similar to sales tax - especially for the merchant herself.
