### ISSUE TITLE
Promotion Actions won't create a per line item promotion

### ISSUE THREAD

**Issue by acreilly** [spree/spree#6156]
I tried to create a per line item adjustment, but after I update the promotion, it always resets back to a whole order adjustment.

1. Create a promotion
2. In actions, create per line item adjustment & add
3. Fill in percent per item
4. Create

Then you will see that the action is whole order adjustment, not per line item adjustment.

https://gist.github.com/acreilly/b67f80c441ba582ceeba

Stack trace
https://gist.github.com/acreilly/29220a4828f99716ea75

**Comment by JDutil** [comment]
Please provide the information we request in our [filing an issue contributing guidelines](https://github.com/spree/spree/blob/master/CONTRIBUTING.md#filing-an-issue) or we won't be able to troubleshoot this.

**Comment by acreilly** [comment]
Issue updated
