### ISSUE TITLE
Admin Sorting Broken (for any models that do not include acts_as_list)

### ISSUE THREAD

**Issue by mleglise** [spree/spree#6157]
Bug introduced by #5947.
OptionTypes fixed by #6114.
Variants fixed by #6155.
ProductProperties still broken.
Any other model that does not include `acts_as_list` is broken as well.

Instead of adding acts_as_list to every model, how about `resources_controller` checks `responds_to?(:set_list_position)` to decide which method to call?

**Comment by JDutil** [comment]
I'd prefer we fixed each model to have acts_as_list if that's the intention.  Sorry it broke, but I'd rather we solve things properly.
