### ISSUE TITLE
In 2-3-stable Ajax request without token

### ISSUE THREAD

**Issue by alejandromangione** [spree/spree#6166]
When added taxon in product, it don't show the taxons. Because in ajax request doesn't sent the token api. Please add: `token: Spree.api_key` in line 10 in taxon_autocomplete.js.erb file. This issue was resolved in 2-4-stable.

**Comment by JDutil** [comment]
Fixed w/ 0d9b4da

**Comment by amalrik** [comment]
TY man!!
