### ISSUE TITLE
Impossible to Ugprade from 2.2 - 2.3 because reference to missing table exists in boot file

### ISSUE THREAD

**Issue by jasonfb** [spree/spree#6171]
It is impossible for me to upgrade my Spree 2.2 store to 2.3 because inside of core/app/models/spree/app_configuration.rb there is a reference to the explicitly defined Store object.

This reference makes the app unable to boot when running `rake db:migrate` because the rake task will crash because the spree_stores table doesn't exist yet

Fixed with this patch:

https://github.com/spree/spree/pull/6170

Please note: this is pull against 2-3-stable only because it is only a problem for 2.2 -> 2.3 upgrade, once you successfully run the rake task you no longer need to worry about missing the table.

**Comment by JDutil** [comment]
FYI no need to open another issue on top of a PR.  Has been merged w/ 3a8d9faa13b5de45be022a443e55ff906e88e4da
