### ISSUE TITLE
Force Confirmation Step When Payment Is Not Required

### ISSUE THREAD

**Issue by joshhepworth** [spree/spree#6176]
It seems like it is not possible to use the built in Spree confirmation step if the order total is zero. Even if I override the `Order#confiration_required?` method to return `true`, the step is skipped if `Order#payment_required?` returns false.

The line of code that seems responsible seems to be a [change introduced a long time ago](https://github.com/spree/spree/commit/fa1d66c42e4c04ee7cd1c20d87e4cdb74a226d3d#diff-434de9976fbb9c7d9358f1cb3d401019R12). That line seems to make it impossible to go from delivery to confirm, which is exactly what needs to happen when payment is not required.

I've tried to do the following, which looks like it would undo the line linked to above, but it does not fix the issue:

``` ruby
Spree::Order.class_eval do
  add_transition from: :delivery, to: :confirm
end
```

If I simply [comment out the line](https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L33) I am able to get to the confirmation step during checkout with a total of 0.

Should this line be removed? What is it meant to do? How should I work around this issue? 
### Extra Info

Currently using Spree 2.4.5, but the original issue seems to have been introduced in v1.2.0.

**Comment by JDutil** [comment]
I think it would be okay to remove that line.  It shouldn't be possible for a user to transition to complete if payment is required. So I don't think it's the end of the world to have a state machine transition that allows skipping payment step.  Not sure if anyone else can think of a reason why this would be bad.

**Comment by mdavo6** [comment]
@joshhepworth Did you get anywhere with this? I'm coming up against this same issue at the moment....

**Comment by joshhepworth** [comment]
@mdavo6 we ended up working around it by just having some dummy info that we saved while displaying something along the lines of "no payment information required" to the user. _Far_ from the most ideal solution, but it allowed us to move forward.
