### ISSUE TITLE
Unpermitted parameter: existing_card during checkout

### ISSUE THREAD

**Issue by farneman** [spree/spree#6203]
When running through the checkout process in development with `config.action_controller.action_on_unpermitted_parameters = :raise` after choosing to checkout with an existing card (using Spree::Gateway::Bogus) the following error is thrown:
```
ActionController::UnpermittedParameters at /checkout/update/payment
found unpermitted parameter: existing_card
```

This is the result of `existing_card` being sent in the params and later removed (used only to retrieve/set the payment method). However when `.permit` is run on [line 232](https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L232) of the Spree::Order Checkout module `:existing_card` is not whitelisted so it logs or throws an error depending on your settings.

**Comment by JDutil** [comment]
Going to close in favor of your PR
