### ISSUE TITLE
API, Add :description to available payment methods on Order 

### ISSUE THREAD

**Issue by erikaxel** [spree/spree#6212]
Hi,

I'm using the API to create a angularjs based checkout. To be able to create the payment step, it would be great if the "available_payment_methods:" on the Order in the API, could have the description returned as well as id, name and method_type. The fix is simple, in the file:
spree/api/app/views/spree/api/v1/orders/payment.v1.rabl
change line 2 to 
attributes :id, :name, method_type, :description

I'm sorry for not creating a pull request just for this small edit, hope you will accept it anyway.

**Comment by JDutil** [comment]
Which branch are you using?

**Comment by JDutil** [comment]
Feel free to submit a PR if you want to beat me to it.

**Comment by nishant-cyro** [comment]
@erikaxel - I guess description for a payment method is not required in all cases and if someone needs it he/she can override the response.

Any thoughts?

cc: @priyank-gupta @Mafi88 @damianlegawiec

**Comment by bbonislawski** [comment]
That's true. If you need it, just add it into your application.
