### ISSUE TITLE
[2-4-stable] AdtiveAdmin 1.0.0pre and Spree in one app - integration problem

### ISSUE THREAD

**Issue by Salet** [spree/spree#6224]
I encountered a name conflict trying to integrate ActiveAdmin 1.0.0pre and Spreecommerce 2.4 into one Rails 4 app. The issue here is that ActiveAdmin searches for object display methods in following order:

    :display_name, :full_name, :name, :username, :login, :title, :email, :to_s

and Spree defines a global helper display_name here:
https://github.com/spree/spree/blob/master/backend/app/helpers/spree/admin/stock_locations_helper.rb

That leads to errors in said helper when accessing ActiveAdmin. I already described it in deatils on SO:
http://stackoverflow.com/questions/28583008/spreecommerce-and-activeadmin-display-name-conflict

This is a crosspost from ActiveAdmin issue tracker (AA developer blames Spree for this problem):
https://github.com/activeadmin/activeadmin/issues/3805

Application Gemfile.lock can be found here: 
https://gist.github.com/Salet/a2d5dc70b49fc757fc4d

I managed to bypass this problem by monkey-patching Stock locations helper like that:
```
Spree::Admin::StockLocationsHelper.module_eval do 
  def display_name(stock_location)
    if stock_location.is_a? Spree::StockLocation
      name_parts = [stock_location.admin_name, stock_location.name]
      name_parts.delete_if(&:blank?)
      name_parts.join(' / ')
    else
      if stock_location.respond_to? :name
        stock_location.name
      elsif stock_location.respond_to? :email
        stock_location.email
      else
        stock_location.to_s
      end
    end
  end
end
```
This solution doesn't feel clean however. Let me know if more info is required to reproduce the issue.

**Comment by JDutil** [comment]
Rather than having display_name in the stock locations helper module you could move display_name method to StockLocation model that way you'd just call stock_location.display_name rather than display_name(stock_location).

**Comment by Salet** [comment]
I already menaged to bypass this, I opened the issue to let you (and other people) know of the problem. Feel free to close if you don't feel like changing anything in this regard. Cheers :)
