### ISSUE TITLE
Browser's freeze in the filter by orders for large stores.

### ISSUE THREAD

**Issue by romul** [spree/spree#6225]
That's really nasty issue in filter orders by SKU. It was introduced by https://github.com/spree/spree/pull/5494
It could lead to a complete freeze of a browser or even to OS freeze (when you click on select), if you have dozens thousands of SKU and orders. And even if you have less SKU's and orders this select have very poor performance.

I think, that we should proceed from the idea that the Spree should be suitable primarily for large stores. Because for small shops there is a bunch of more primitive solutions. So, the such performance downgrades should be fixed for all supported versions as soon as possible. 
In this case, select could be replaced with simple text field without any loss of functionality.

**Comment by JDutil** [comment]
Does your store have this patch applied? https://github.com/spree/spree/pull/6187 may help resolve this for you

**Comment by romul** [comment]
@JDutil Yes, I've tested this revision https://github.com/spree/spree/commit/68119442e6b79267f2cba58d520e51b9c7967936 of 2-4-stable.
The mentioned patch could help only until you have small count of orders. 
And it's even not a server-side issue (although SQL takes about 180 ms in my case), but browser just can not handle creation a select2 with such count of options.
