### ISSUE TITLE
Line Item adjustment without source

### ISSUE THREAD

**Issue by smartacus** [spree/spree#6231]
Is there a reason why an order adjustment does not require a source but a line item adjustment does?

We are moving to Spree and we have a business requirement to move our past order data (including line item adjustments) from our old e-commerce provider. The problem I'm running into is that the line item adjustments won't apply without a source but the source of the adjustments are not present in Spree.

**Comment by JDutil** [comment]
Where do you see that a line item adjustment requires a source?  I'm not seeing it for either.

**Comment by smartacus** [comment]
PR #6236 should have a failing spec where I'm seeing the issue. The comments in [adjustment_source.rb](https://github.com/spree/spree/blob/master/core/app/models/concerns/spree/adjustment_source.rb#L43-L58) also indicate that an adjustment with no source_id will not be applied.

**Comment by JDutil** [comment]
Sorry I'm not sure offhand why that would be the case.

**Comment by JDutil** [comment]
I have the feeling at the order level when doing total, promo, tax, shipping etc... calculations we determine that by what the source is.  I believe you'd be ok leaving a source off, but that could cause the adjustment to not be recognized as you'd like it to be depending on the scenario.

**Comment by smartacus** [comment]
I worked around this by adding a source type of Spree::PromotionAction to the line item adjustments. Thanks for your help.
