### ISSUE TITLE
Required field asterisk outside of label

### ISSUE THREAD

**Issue by farneman** [spree/spree#6232]
A question out of curiosity: I was wondering why most (if not all) of the frontend forms have required fields output like:
```erb
<%= label_tag "card_expiry", Spree.t(:expiration) %><span class="required">*</span><br />
```
as opposed to having the `.required` span inside the label without the `<br />` similar to:
```erb
<%= label_tag "card_expiry" do %>
   <%= Spree.t(:expiration) %><abbr class="required" title="required">*</abbr>
<% end %>
```

What is the justification for the former as compared to the latter? It seems to go against common practice in other contexts. It also makes styling more complicated than it could otherwise be.

**Comment by JDutil** [comment]
Most likely there is no reason other than that's what the developer at the time did.  Feel free to submit a PR making everything uniform.

**Comment by farneman** [comment]
I've submitted a PR for this at #6233
