### ISSUE TITLE
Shipping Rate Taxes Calculated Wrong

### ISSUE THREAD

**Issue by schmijos** [spree/spree#6234]
When calculating `calculate_shipping_rates`, the order of the *tax_rates* in the *shippments* *tax_category* matters. The code I'm talking about is in *Spree::Stock:Estimator*

```ruby
def calculate_shipping_rates(package)
  shipping_methods(package).map do |shipping_method|
    cost = shipping_method.calculator.compute(package)
    tax_category = shipping_method.tax_category
    if tax_category
      tax_rate = tax_category.tax_rates.detect do |rate|
        # If the rate's zone matches the order's zone, a positive adjustment will be applied.
        # If the rate is from the default tax zone, then a negative adjustment will be applied.
        # See the tests in shipping_rate_spec.rb for an example of this.d
        rate.zone == order.tax_zone || rate.zone.default_tax?
      end
    end

    if cost
      rate = shipping_method.shipping_rates.new(cost: cost)
      rate.tax_rate = tax_rate if tax_rate
    end

    rate
  end.compact
end
```

The problem is that *detect* returns to early if the *rate* is in the default tax zone before a match is found.

I'm not that sure, but the following should solve the problem:

```ruby
def calculate_shipping_rates(package)
  shipping_methods(package).map do |shipping_method|
    cost = shipping_method.calculator.compute(package)
    tax_category = shipping_method.tax_category

    if tax_category
      default_tax_zone = tax_category.tax_rates.detect do |rate|
        rate.zone.default_tax?
      end

      tax_rate = tax_category.tax_rates.detect do |rate|
        rate.zone == order.tax_zone
      end

      tax_rate ||= default_tax_zone
    end

    if cost
      rate = shipping_method.shipping_rates.new(cost: cost)
      rate.tax_rate = tax_rate if tax_rate
    end

    rate
  end.compact
end
```

**Comment by JDutil** [comment]
Would you mind submitting a PR please?

**Comment by mamhoff** [comment]
I am working on [this PR](https://github.com/spree/spree/pull/6227), which would make asking for the default zone obsolete. Can you wait until next week? I haven't gotten to shipping rates estimation yet...

**Comment by schmijos** [comment]
No problem. Good enough if somebody does it right.

**Comment by mamhoff** [comment]
@schmijos Can you checkout the PR in its current state and try whether it solves your problem? Careful: All prices have to be entered without VAT! :)

**Comment by schmijos** [comment]
Unfortunately not before next week.

**Comment by schmijos** [comment]
@mamhoff I can't test your PR without a lot of effort because I'm still on Spree 2.4. I don't think you're going to backport your changes, aren't you?

**Comment by mamhoff** [comment]
No, I wasn't planning to do that. Since the PR relies on a couple of changed conventions, it would also probably not be accepted for 2.4, so it would have to live in a branch and would be a maintenance... well, not so nice thing.

The one major change to 3.0 is just the Bootstrap frontend though - it might be possible to upgrade a branch of project to 3.0 just for testing? 

Another possibility would be to seed a sample store with just the data you need for replicating your case.

For 2.4, I think your approach might actually be a better fit than the wholesale overhaul I'm doing in #6227.
