### ISSUE TITLE
Deleting a product screws up ordering within taxons

### ISSUE THREAD

**Issue by pelargir** [spree/spree#6238]
When a product gets soft deleted, its classifications get hard deleted. This causes a problem when the user tries to manually sort the remaining products within a given taxon since the classifications within that taxon now have a gap in the position numbers.

As an example, say we have the following products with the given positions with a taxon:

name=A position=1
name=B position=2
name=C position=3
name=D position=4

Let's say product B gets deleted. This leaves a gap in the list:

name=A position=1
name=C position=3
name=D position=4

Now when the user tries to manually sort the remaining products within the taxon, unpredictable results occur. Dragging C to be before A, for example, sets C's position to 2 which means it still comes *after* A. But this isn't obvious unless the user refreshes the admin page.

The classification positions should instead be re-numbered whenever a product gets deleted. This will eliminate the gaps and ensure proper behavior when manually sorting.

**Comment by JDutil** [comment]
Could you submit a PR to address this?

**Comment by jacemonje** [comment]
Hi, how does one replicate this? I've tried and it works fine on my end. I may not have done it right.

**Comment by JDutil** [comment]
@jacemonje it's quite possible this isn't actually a bug I haven't tried to reproduce it.  As far as I know reordering things should work fine whether there are gaps or not as it should reorder everything.

**Comment by pelargir** [comment]
Our team does plan on fixing this at some point and we'll certainly re-contribute the fix as a PR. It's definitely a bug, reproducible multiple times, but I haven't verified whether it's still present in Spree 3.0 yet. It might just be a problem in 2.3.

**Comment by pelargir** [comment]
Verified that this is happening for us in Spree 3.0 as well. To reproduce:

1) bring up the admin backend
2) bring up a taxon by navigating to Products > Taxons
3) select a taxon from the list
4) choose a product in the middle of the list, click down arrow, then click "Delete From Taxon"

Now try moving a product that appeared *after* the deleted product. The new position will appear to be correct after clicking-and-dragging, but if you refresh the page and re-select the taxon you'll notice the product is actually one behind where you sorted it to be. This is because deletion of the original product has introduced a gap in the sequential positions, verifiable by examining the results of this query:

select position from spree_products_taxons where taxon_id=X;

Where X is the database ID of the taxon you've been attempting to sort products inside.

**Comment by jasonfb** [comment]
@pelargir 

this should be fully remediated by https://github.com/spree/spree/pull/6692 in which I have completely backed-out of the bad design (anti-) pattern of deleting objects in Rails. I have not checked to see how my new discontinue_on features interact with the Taxon-to-Product association, but at the very least the objects should no longer be seen as ```nil```

**Comment by JDutil** [comment]
should be fixed by https://github.com/spree/spree/pull/6744
