### ISSUE TITLE
Deleting an option value while editing another nullifies the update action

### ISSUE THREAD

**Issue by teeg82** [spree/spree#6250]
This can be observed while editing the option values of any type (admin/option_types/1/edit for example). Delete an option value, and change one of the fields of another option value, then submit the update. The field you changed is not updated.

This is because the "deleted" row still exists in the form, it is merely hidden. Therefore when the update is submitted, the deleted row is sent back to the server for update, and naturally causes a failure and rollback because the row no longer exists.

The culprit is [this function from backend/app/assets/javascripts/spree/backend/admin.js.erb](https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/admin.js.erb#L281). 

Is there a reason for hiding the deleted row, rather than removing it entirely?

**Comment by JDutil** [comment]
I think it would be okay to remove it [here](https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/admin.js.erb#L296) this was probably just an oversight by the developer at the time.

**Comment by teeg82** [comment]
Alright, fair enough. I figured it was just an oversight. I can submit a patch for that a little later if there's no objection.

**Comment by JDutil** [comment]
Pull requests welcome.
