### ISSUE TITLE
Visiting the /accounts path while not logged in produces blank screen

### ISSUE THREAD

**Issue by brchristian** [spree/spree#6254]
It seems (as of the tip of the `2-3-stable` branch) that visiting the `/accounts` path while not logged in results in a blank screen.

What I'd expect is to be prompted with a login screen, and then redirected to my proper `/accounts` path once I log in.

**Comment by JDutil** [comment]
The proper path is `/account`

**Comment by brchristian** [comment]
@JDutil Whoops, apologies for the typo, but in fact the more I look into this the more I think it's something quirky with my app. It only occurs on our production servers, and I can't even reproduce it in production mode locally. So, I don't think it's a Spree issue, but will just have to hope it goes away when we move up to 2.4. Sorry for the false alarm!

**Comment by JDutil** [comment]
Do you have Spree routing mounted anywhere besides `/` like `/shop` or something?  Maybe related to:
https://github.com/spree/spree/pull/6197
