### ISSUE TITLE
BrainTree gateway issue with credit owed wrong calculation.

### ISSUE THREAD

**Issue by heridev** [spree/spree#6265]
I just found out the wrong calculation for credit owed amount using the braintree gateway.

The steps to reproduce the issue:
1.- Follow all the checkout process and complete an order that contains more than 2 different line items, in my case:
![Alt text](https://www.evernote.com/shard/s250/sh/f8c9c35d-6a10-4488-8bae-fba368065075/1d41eee339948fbdc30b5a79125465bb./res/8082439e-760b-41a0-a51a-e16372a26e39/skitch.png?resizeSmall&width=832)

2.- Go to Spree admin section and edit the order that you just completed.

At this point you should see the order as completed and with one payment completed.
3. Remove one item from the order.
![Alt text](https://www.evernote.com/shard/s250/sh/f19c0626-d673-428d-80cc-663d3fdd458c/9c2a00bc633e755a50be33490696d4c1/res/f6a1443a-6e35-4cae-8dd3-26a6bb8871db/skitch.png?resizeSmall&width=832)

4. After to do that you should see a credit owed amount.
![Alt image](https://www.evernote.com/shard/s250/sh/b8474abf-d2ca-48bd-b5da-f345f1cd2e96/803a24cf02add1ddbee1afd81409ba2b/res/ced7e18c-cc52-4599-a3bc-ea2c43b9d6bd/skitch.png?resizeSmall&width=832)

5. clic on the “payments” option in the right sidebar.
6. Now you will see something as follow and clic on the “Credit” icon:
![Alt image](https://www.evernote.com/shard/s250/sh/36629266-21d2-4cb6-907f-ad232c35d582/1e1f3e0e0ee6398467eb63126f3b3ed7/res/09c98c34-b7db-47d6-9100-c8c8fd57b5ba/skitch.png?resizeSmall&width=832)

After the credit icon is clicked the problem is shown:
![Alt image](https://www.evernote.com/shard/s250/sh/0ff26543-0c6a-493e-a963-57be4d77ca90/1e62b9491a32725dd58975ace41ad0f3/res/b2a2bdcd-a69c-4436-ae75-085c6529a884/skitch.png?resizeSmall&width=832)

What I'm expecting here is the negative value for $25.86 instead of the total of the order($148.05)
It seems like the wrong calculation is made here:
https://github.com/spree/spree/blob/2-2-stable/core/app/models/spree/payment/processing.rb#L87

By the way I’m working with the 2-2-stable branch, but that code is the same in other branches as well.

**Comment by nishant-cyro** [comment]
Not able to replicate it in master.
