### ISSUE TITLE
Calculators failing on unimplemented Package.currency method

### ISSUE THREAD

**Issue by brchristian** [spree/spree#6273]
I'm trying to get the [spree_tax_cloud](https://github.com/spree-contrib/spree_tax_cloud) specs green again and something appears to have changed that's making all of my specs fail at the [following line from Spree's Flat Rate calculator](https://github.com/spree/spree/blob/2-3-stable/core/app/models/spree/calculator/flat_rate.rb#L13): 

```ruby
if object && preferred_currency.upcase == object.currency.upcase
```

The exception is `undefined method 'upcase' for nil:NilClass` because `object.currency` is returning `nil`.

In this case, my `object` is a [Spree::Stock::Package](https://github.com/spree/spree/blob/2-3-stable/core/app/models/spree/stock/package.rb).

I notice that the `currency` method appears [never to have been implemented](https://github.com/spree/spree/blob/2-3-stable/core/app/models/spree/stock/package.rb#L58)!

```ruby
def currency
  #TODO calculate from first variant?
end
```

I'm not understanding what might have changed in the `2-3-stable` branch to cause these specs to start failing, which were green several months ago, but what do you recommend here? Do we implement this currency method or at least allow it to degrade gracefully to ```Spree::Config[:currency]```?

Or is the `spree_tax_cloud` extension doing something wrong by passing a `Package` to the `Calculator`?

Any advice here is greatly appreciated!

**Comment by JDutil** [comment]
The currency method should implement:
```
def currency
  order.currency
end
```

**Comment by JDutil** [comment]
Should be better w/ 9eadb6304fe078af65686cc2ad6843e0d1fa3241

**Comment by brchristian** [comment]
Thanks, @JDutil ! :+1:
