### ISSUE TITLE
Failures in model specs

### ISSUE THREAD

**Issue by brchristian** [spree/spree#6276]
I'm trying to set up some model specs for a Spree extension and am having a lot of trouble getting the factories to work. When I went to spree/core itself and ran `be rspec spec` to see how Spree uses mocks and so forth for their model tests, I was surprised to see the following:

    Finished in 22.39 seconds (files took 4.73 seconds to load)
    1473 examples, 1041 failures, 3 pending

Am I doing something wrong here, that's causing 2/3rds of the model specs to fail? This is just from `git clone`ing the latest `2-3-stable` branch and then

```
bundle update
cd core/
bundle update
be rspec spec
```

Maybe I'm missing an important step. Thanks!

**Comment by JDutil** [comment]
You also need to do `rake test_app` before rspec spec.  Check out the build.sh file to see how to run everything: https://github.com/spree/spree/blob/master/build.sh

**Comment by brchristian** [comment]
@JDutil Knew I was missing something simple -- thanks a million! :+1:
