### ISSUE TITLE
2.4 to 3.0 Upgrade guide missing

### ISSUE THREAD

**Issue by snowmoonsoftware** [spree/spree#6283]
The url `https://guides.spreecommerce.com/developer/upgrades/two-dot-four-to-three-dot-zero.html` referenced from `https://guides.spreecommerce.com/release_notes/spree_3_0_0.html` is 404'd.

**Comment by JDutil** [comment]
Deployed latest guides.

**Comment by snowmoonsoftware** [comment]
Still 404'd. Is there a propagation delay, or is the link in the release notes wrong?

**Comment by JDutil** [comment]
The page doesn't and will not exist.  See the updated release notes.

**Comment by snowmoonsoftware** [comment]
Perfect, thanks. I can see them now.

Jeff Paquette
508 667 1205
jeff@snowmoonsoftware.com
www.snowmoonsoftware.com
skype: snowmoonsoftware

**Comment by ziyan-junaideen** [comment]
https://guides.spreecommerce.com/release_notes/spree_3_0_0.html is not reachable.

**Comment by priyank-gupta** [comment]
@ziyan-junaideen Try http://guides.spreecommerce.com/release_notes/spree_3_0_0.html (without https)

**Comment by Mafi88** [comment]
@ziyan-junaideen It's temporary
