### ISSUE TITLE
204 API Response Returns " " in Rails 4.2

### ISSUE THREAD

**Issue by edmondchui** [spree/spree#6285]
I'm using Spree 3.0.0. I just upgrade to Rails 4.2 and add responders gem per Rails 4.2 upgrade notes
```
gem 'responders', '~> 2.0'
```
My APIs for DELETE used to return empty body is now returning " " in the respond body.

How should we fix that?

On the other hand, should we use
```
head(status: 204)
```
in all DELETE API respond instead?

**Comment by JDutil** [comment]
I think doing 204 makes sense.

**Comment by edmondchui** [comment]
After further investigation, I found out this is a bug in ActionPack that is fixed in Rails version 4.2.1.

https://github.com/rails/rails/commit/2910956fc9006d3c26f56992dab630fa97b7f7bc#diff-700a06dbd99ef1fb4b25bd1201827b14

With Rails upgraded to version 4.2.1 the issue does not exist. So we should recommend all Spree 3.0.0 developers to use Rails version 4.2.1 instead.
