### ISSUE TITLE
New lines in line-item description show up as html entities.

### ISSUE THREAD

**Issue by Good4m** [spree/spree#6288]
When you add new lines to a product's description they display as html entities in the cart's line-item description.

![ss](https://cloud.githubusercontent.com/assets/1824966/7128594/771d2998-e209-11e4-8300-789159ee35e6.png)

For now I'm just removing the description entirely because I don't see a need for it in the cart anyway.

**Comment by berkes** [comment]
If you need a temporary workaround untill this patch lands in a stable release, you can add a quick `squish` to your `_line_item` partial. If you don't have this partial, copy it to `app/views/spree/orders/_line_item.html.erb`.

Then:
    -    <%= line_item_description_text(line_item.description) %>
    +    <%= line_item_description_text(line_item.description.squish) %>

**Comment by JDutil** [comment]
Wish I had thought of squish...
