### ISSUE TITLE
Model references in the api should always use the Spree:: namespace to avoid conflict an apps rails's models

### ISSUE THREAD

**Issue by williscool** [spree/spree#6292]
I.e. here

https://github.com/spree/spree/blob/2-4-stable/api/app/controllers/spree/api/orders_controller.rb#L10

Should use `Spree::Order`

Have an issue now with an app that already has an `Order` model declared

so spree could not find the `checkout_steps` defined on the Order model

so I hit this
```

ActionController::RoutingError (undefined method `checkout_steps' for nil:NilClass):
  spree_api (2.4.3) app/controllers/spree/api/orders_controller.rb:10:in `<class:OrdersController>'
  spree_api (2.4.3) app/controllers/spree/api/orders_controller.rb:3:in `<module:Api>'
  spree_api (2.4.3) app/controllers/spree/api/orders_controller.rb:2:in `<module:Spree>'
  spree_api (2.4.3) app/controllers/spree/api/orders_controller.rb:1:in `<top (required)>'
  activesupport (4.1.9) lib/active_support/dependencies.rb:443:in `load'
  activesupport (4.1.9) lib/active_support/dependencies.rb:443:in `block in load_file'
  activesupport (4.1.9) lib/active_support/dependencies.rb:633:in `new_constants_in'
  activesupport (4.1.9) lib/active_support/dependencies.rb:442:in `load_file'
  activesupport (4.1.9) lib/active_support/dependencies.rb:342:in `require_or_load'
  activesupport (4.1.9) lib/active_support/dependencies.rb:480:in `load_missing_constant'
  activesupport (4.1.9) lib/active_support/dependencies.rb:180:in `const_missing'
...
```

**Comment by JDutil** [comment]
Please submit a PR

**Comment by williscool** [comment]
For every controller in the directory or just the orders one?

**Comment by williscool** [comment]
nvr mind pulled

**Comment by JDutil** [comment]
Merged w/ d30847ab7f60f8942e28f0517a53529a50416aa1 to 2-4-stable and 3-0-stable but it doesn't apply cleanly to master branch which is being v1 name spaced now.

**Comment by williscool** [comment]
So I see the commit in the spree repo but its not showing up on the 2-4-stable branch

**Comment by JDutil** [comment]
It's there under April 20th https://github.com/spree/spree/commits/2-4-stable the above sha I linked to in last comment you can see 2-4-stable branch under commit message.
