### ISSUE TITLE
Order state does not got to awaiting_return when return authorization is created

### ISSUE THREAD

**Issue by jungbunzlav** [spree/spree#6297]
Spree 2.4.6

Steps to reproduce:
- Create an order
- Go to backoffice and  captured payments and ship items
- Create return authorization for at least one shipped item

Result: Order state is still complete - as a result the filter in the orders overview für orders awaiting returns does not work

Expected result: The order state should be awaiting_return. Moreover, the order overview's filter for orders awaiting customer returns should return order with open return authorizations

[Gemfile](https://gist.github.com/jungbunzlav/48d37cd850b25a55bcb4)
[Gemfile.lock](https://gist.github.com/jungbunzlav/2e2b7731ecd4e6c15a7a)

Note: We forked spree for fixing an issue with locked active merchant gem version. This issue also occurs with the "real" spree gem

**Comment by jungbunzlav** [comment]
Any news on this issue?

**Comment by JDutil** [comment]
If no one has responded sorry there is no news.

**Comment by yf6** [comment]
Hey I'm noticing the same in Spree 2-4. I dug around the code a little and found an order get the `awaiting_return` status when event `authorize_return` happens https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order/checkout.rb#L69

But it seems that the return authorization has the initial state `authorized` https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/return_authorization.rb#L28 

So I'm not sure how to trigger the `authorize_return` event. 

@jungbunzlav Have you found a way around this?
@JDutil I'm happy to contribute to fix this, if you can help me understand the design of this.

**Comment by jungbunzlav** [comment]
@yf6 No, have you found a way?

**Comment by yf6** [comment]
@jungbunzlav yeah, i think i added a callback after return creation to call `order.authorize_return!`

**Comment by jungbunzlav** [comment]
@yf6 would you be so kind to post your code? that would be great! thanks

**Comment by yf6** [comment]
@jungbunzlav try this
```
module Spree
  ReturnAuthorization.class_eval do
    after_create :process_return
    def process_return
      # This only changes the order status to be awaiting return,
      # doesn't actually do anything to the return authorization
      order.authorize_return!
    end
  end
end
```
