### ISSUE TITLE
Stop using js or coffee .erb in the backend

### ISSUE THREAD

**Issue by erikaxel** [spree/spree#6313]
Hi,

I have noticed that quite some of the js and coffee files for the backend have an .erb-extension. Using .erb for js and coffee files can create unexpected results when precompiling assets. One common use case of precompiling assets is on Heroku. 

For a concrete example, the file spree/backend/shipments.js.erb has the following code on line 137:

``` javascript
show.find('.tracking-value').html($("<strong>").html("<%= Spree.t(:tracking) %>: ")).append(data.tracking);

```

In this case, Spree.t() will be use the language set at the moment of precompilation, not at runtime. I don't think this is what is expected. Even worse, this line caused compilation issues when using uglifier to optimize the code. (also on Heroku and probably because of missing environment language settings, see also https://github.com/lautis/uglifier/issues/61).

Luckily most of the .erbs seems to be not using this kind of code, and should simply be renamed. 

1) Would you be interested in accepting pull requests renaming the simple cases to remove the .erb postfix?

2) I would like to fix the specific case above, since it breaks my deployment. I can of course create a pull requests which just replaces the translation with a simple string if that is ok. But if you do have a general way of translation that can be used in javascript I will be happy to code that as well, as long as somebody somebody could direct me to an example of usage of this elsewhere in the backend.

**Comment by JDutil** [comment]
1) Yes
2) Yea we should be translating in javascript like this https://github.com/spree-contrib/spree_i18n/blob/master/app/assets/javascripts/spree/backend/taxon_tree_menu.js.coffee#L19-L34 but not sure exactly where those translations are being set off the top of my head.

**Comment by bbonislawski** [comment]
Outdated
