### ISSUE TITLE
Metadata product overview pages is not correct

### ISSUE THREAD

**Issue by paulhuisman** [spree/spree#6317]
The single product page is currently showing correct metadata, like this:

![screen shot 2015-04-21 at 16 17 49](https://cloud.githubusercontent.com/assets/37524/7254244/141aadfe-e842-11e4-96b9-b0a965091448.png)

But the product overview page (/products) is showing incorrect metadata:

![screen shot 2015-04-21 at 16 17 44](https://cloud.githubusercontent.com/assets/37524/7254251/1fa84744-e842-11e4-818f-962fc929d2ee.png)

The price option is incorrect and should be the same as the single product page metadata ("offer" instead of "price")

**Comment by kushniryb** [comment]
This was fixed by @damianlegawiec in edad155990e08492456db522a047a98b99e2451a and 053eaed161c55d0b4b875253bea786379184ca73
@bbonislawski Can we close it?
