### ISSUE TITLE
3-0-stable backend: JavaScript console Uncaught TypeError in view admin/products/edit

### ISSUE THREAD

**Issue by cindyward1** [spree/spree#6319]
Is anyone else getting the JavaScript console error "Uncaught TypeError: Cannot read property 'replace' of undefined" on the backend view admin/products/edit? It occurs in the following jQuery method:

// Convert dashed to camelCase; used by the css and data modules
// Microsoft forgot to hump their vendor prefix (#9572)
camelCase: function( string ) {
	return string.replace( rmsPrefix, "ms-" ).replace( rdashAlpha, fcamelCase );
},

The error doesn't seem to affect the little bit of jQuery I use in the view. I am seeing it with live data, but my co-worker is seeing it using the sample store.

I imagine this is a jQuery error, not a Spree error, but I want to make sure others are seeing it before I try to track it down further. Thanks in advance for any help.

P.S. I am seeing this using Chrome Version 42.0.2311.90 (64-bit) on MacOS X Mavericks. My co-worker has the same version of Chrome but is running Yosemite.

**Comment by liwei78** [comment]
@cindyward1  I got the same error. Is it fixed in other version ?

**Comment by cindyward1** [comment]
Thank you for your reply. I don't know whether the error occurs on 3.1 or later versions, sorry. I never got the chance to implement a Spree 3.1 test environment. I am no longer being paid to work on Spree which has hampered my progress significantly on this and all other Spree-related issues ... Cindy


     On Friday, May 22, 2015 2:53 AM, liwei <notifications@github.com> wrote:
   

 @cindyward1 I got the same error. Is it fixed in other version ?—

**Comment by JDutil** [comment]
I also receive this.  Perhaps we can try updating jquery to newer version to resolve it?

**Comment by edwardsharp** [comment]
I was also having this problem. The commit above (008050d01a1386a4d5e5a4f425063abab5f52756) worked for me.
