### ISSUE TITLE
2.x Backend: payment method fieldset do not appear on payment method selection

### ISSUE THREAD

**Issue by cveneziani** [spree/spree#6322]
Hello,

I'm facing an issue when I try to select a payment method in back-office. Here is my usecase: I have 3 payment methods (cheque, credit card, paypal). On new payment page, by default cheque is pre-selected. When I select Credit card, nothing happens. Its related fieldset stays hidden.

It looks like two JS files are trying to do the same job.

### 1. [payments/new.js](https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/payments/new.js#L12-L21)
```
    $('.payment_methods_radios').click(
      function() {
        $('.payment-methods').hide();
        $('.payment-methods :input').prop('disabled', true);
        if (this.checked) {
          $('#payment_method_' + this.value + ' :input').prop('disabled', false);
          $('#payment_method_' + this.value).show();
        }
      }
    );
```
If I click on the radio button of a payment method, it hides other payment method fieldsets and shows the one corresponding to the selected payment method. Great.

### 2. [select_payments.js.coffee](https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/select_payments.js.coffee#L3-L7)
```
$ ->
  if $('.new_payment').is('*')
    $('.payment-method-settings fieldset').addClass('hidden').first().removeClass('hidden')
    $('input[name="payment[payment_method_id]"]').click ()->
      $('.payment-method-settings fieldset').addClass('hidden')
      id = $(this).parents('div.radio').data('id')
      $("fieldset[data-id='#{id}']").removeClass('hidden')
```

If I click on the radio button of a payment method, it add `hidden` class to other payment method fieldsets and removes `hidden` class from the one corresponding to the selected payment method **BUT** its based on `data-id` of parent "radio" div and `data-id` of fieldset.

### Div "radio" side

```
<div class="radio" data-id="<%= Spree.t(method.name, :scope => :payment_methods, :default => method.name).parameterize %>">
```
See [app/views/spree/admin/payments/_form.html.erb](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/payments/_form.html.erb#L9)

### Fieldset side

Here is an example with payment method with credit card type:

```
<fieldset data-id="credit-card">
```

See [app/views/spree/admin/payments/source_forms/_gateway.html.erb](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/payments/source_forms/_gateway.html.erb#L1)

### I18n vs hardcoded id

I'm building a French speaking app so my payment method names are in French. Here, we're trying to translate in French a parameterized name that is in French.

The problem is that my translation of a French parameterized name will never match a hardcoded `credit-card`.

## 2 guys for one job

I think the first approach is just fine.
What do you think about removing the second one?

**Comment by JDutil** [comment]
Yup it looks like during the admin design update the second approach was added not knowing the first existed perhaps.  The first approach may need to be tweaked to work properly after removing the second, which I'm fine with definitely don't want more code than necessary. Could you submit a PR?

**Comment by cveneziani** [comment]
Thanks :)
