### ISSUE TITLE
missing upgrade guide for 2-4 to 3-0 stable

### ISSUE THREAD

**Issue by ivar** [spree/spree#6332]
On the [upgrade docs page](https://guides.spreecommerce.com/developer/upgrades/) it says to file an issue if the docs are erroneous or incomplete. Unfortunately, docs for the upgrade from 2.4 to 3.0 are not linked and the [upgrade documentation directory](https://github.com/spree/spree/tree/master/guides/content/developer/upgrades) doesn't have any files.

The [release notes for 3.0](https://github.com/spree/spree/blob/master/guides/content/release_notes/3_0_0.md) are pretty good and have upgrading tips - perhaps link those for now?

**Comment by JDutil** [comment]
The release notes contain the upgrade doc it doesn't make sense to keep them separate so I'm not doing that anymore.

**Comment by JDutil** [comment]
Feel free to submit a PR linking to it.
