### ISSUE TITLE
Use HTTPS for schema.org if SSL is turned on

### ISSUE THREAD

**Issue by sepastian** [spree/spree#6333]
Hello,

The URLs for schema.org, as generated by Spree, are always starting with HTTP - even if an SSL certificate is used and SSL has been turned on with `config.force_ssl = true` in `config/environments/production.rb`.

For example:

    <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">

should read:

    <span itemprop="offers" itemscope itemtype="https://schema.org/Offer">

This results in the browser showing an error message.

How can I force HTTPS urls for schema.org? I think that using `//schema.org/Offer` instead of specifying a protocol explicitly should do the trick.

**Comment by sepastian** [comment]
For example, in https://github.com/spree/spree/blob/master/frontend/app/views/spree/products/show.html.erb, change

    4 <div data-hook="product_show" itemscope itemtype="http://schema.org/Product">

to

    4 <div data-hook="product_show" itemscope itemtype="https://schema.org/Product">

As far as I know, always using HTTPS would not do any harm, even if a site does not use HTTPS otherwise.

I could create a PR for this, if chances are that this would be merged and used. Any objections?

**Comment by JDutil** [comment]
Please submit a PR updating them.

**Comment by sepastian** [comment]
I have been digging deeper.

According to [this link](http://webmasters.stackexchange.com/questions/68709/secure-and-non-secure-schema-org-markup), using `//schema.org` and letting the browser decide which protocol to use causes problems with validation tools.

Specifying `https://schema.org` explicitly looks like a better option.

However, I just found that, besides schema.org, Spree is also referencing `http://data-vocabulary.org`, for example here:

    app/helpers/spree/frontend_helper.rb:      crumbs = [content_tag(:li, content_tag(:span, link_to(Spree.t(:home), spree.root_path, itemprop: "url") + separator, itemprop: "title"), itemscope: "itemscope", itemtype: "http://data-vocabulary.org/Breadcrumb")]

The problem with data-vocabulary.org is that, unlike schema.org, it does not offer an `HTTPS` variant.

So this problem can be fixed partly only, by replacing `http://schema.org` with `https://schema.org`. There is nothing that can be done about the references to `http://data-vocabulary.org`.

My question now is: does it make sense to fix the schema.org references only? Should I submit a PR for that? Or, since the problem can't be solved 100 %, should we just leave everything the way it is?

**Comment by JDutil** [comment]
We should probably switch to using schema.org's bread crumb format:
http://schema.org/BreadcrumbList

**Comment by sepastian** [comment]
Sounds good, I will provide a PR.

**Comment by sepastian** [comment]
See #6341.

**Comment by sepastian** [comment]
:+1: 

Just wondering: I fixed 3-0-stable, did you merge this into master as well?

**Comment by JDutil** [comment]
Yea
