### ISSUE TITLE
Can't search deleted products by SKU via the API using show_deleted=true

### ISSUE THREAD

**Issue by cdion** [spree/spree#6343]
I need to be able to search for a deleted product from Spree, using a SKU.  I'm running 3-0-stable.

Doing this:
/api/products/?q[master_sku_eq]=MySku&token=MyToken&show_deleted=true

Always returns 0 results.  The SQL generated looks like this:

SELECT  DISTINCT "spree_products".* FROM "spree_products" LEFT OUTER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = 't' AND "spree_variants"."deleted_at" IS NULL WHERE "spree_variants"."sku" = 'MySku' LIMIT 25 OFFSET 0

Note that while the usual 'deleted_at IS NULL' criteria on the product has been suppressed by show_deleted=true, the same criteria on the (master) variant association remains.  This means that the left outer join returns nothing, and the ransack query for master_sku_eq matches no records.

Is there another way to achieve what I am trying to do?  Would this be easy to fix?

**Comment by damianlegawiec** [comment]
`Spree 3.1.0` introduced product discontinuation which should "fix" this use case.
