### ISSUE TITLE
UX bug in the admin main menu

### ISSUE THREAD

**Issue by romul** [spree/spree#6348]
When you work in the admin panel, menu is collapsed on any page.
It should be opened on current tab, and current item should be highlighted as it was in the previous versions of Spree.

**Comment by romul** [comment]
Besides, two items can be highlighted in the same time: http://monosnap.com/image/1DUeR1xNoh00b1UaTaAl7N6LV5p7YQ
But only one should be.

**Comment by romul** [comment]
And configuration submenu markup is different compared to other `main_menu_tree`.
So we should choose what is preferred: `li.sidebar-menu-item.selected` or `li.active`?

**Comment by JDutil** [comment]
Definitely would be good to choose a preferred markup. ping @reinaris

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/7522
