### ISSUE TITLE
Change Spree::Image attachment_styles in 3-0-stable

### ISSUE THREAD

**Issue by sepastian** [spree/spree#6356]
It used to be possible to [change attachment styles](https://guides.spreecommerce.com/developer/products.html#images) in `config/initializers/spree.rb`.

How do you do this in 3-0-stable (an possibly later)? The configuration option `attachment_styles` is no longer there.

**Comment by JDutil** [comment]
Use `Spree::Image.attachment_definitions[:attachment][:styles] = {}`

**Comment by aravindratna93** [comment]
i tried the same but it is not working out for me
we can use this method for overriding or just adding new styles??

**Comment by sepastian** [comment]
Thank you @JDutil, works for me.

@aravindratna93, what exactly isn't working as expected? What are you trying to achieve?

This method will override all of Spree's default styles. You need to specify styles in `config/initializers/spree.rb`; then restart your server; this will affect new images only.

For existing images, you need to refresh the thumbnails with `RAILS_ENV=production bin/rake paperclip:refresh:thumbnails CLASS=Spree::Image`. Don't forget to specify your `RAILS_ENV`.

Does this solve your problem?

**Comment by aravindratna93** [comment]
actually i want an image of 350x340 dimensions on the product_show page 
![image](https://cloud.githubusercontent.com/assets/8010770/7748102/1d1c9570-ffdf-11e4-9ac2-785a0fa55a66.png)

even after using this method
i had restarted the server then
deleted the existing image and 
uploaded a new image from the back-end
this makes no change in the attachment sizes when uploaded
![image](https://cloud.githubusercontent.com/assets/8010770/7748106/40bdd0f2-ffdf-11e4-86cc-78f3e3a2c79d.png)

**Comment by JDutil** [comment]
@aravindratna93 Do that outside of the Spree.config block not within it the block is only for setting preferences.

**Comment by aravindratna93** [comment]
Coool!!! Thanks a Lot Mahn!!! @JDutil
