### ISSUE TITLE
Spree::Variant - acts_as_list not scoped to Spree::Product

### ISSUE THREAD

**Issue by Domenoth** [spree/spree#6361]
The call to [acts_as_list](https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb#L4) does not provide a scope. This leads to attempting to adjust the order of variants for one product screwing with the ordering of variants for every other product (in very strange ways):
```
2.1.2 :015 > Spree::Product.find_by(name: 'Name').variants.pluck('id, position')
 => [[119, 5], [120, 6], [121, 7], [122, 8], [123, 9], [124, 10], [125, 11]]

...order variants from a different product via the UI...

2.1.2 :016 > Spree::Product.find_by(name: 'Name').variants.pluck('id, position')
 => [[125, 18], [124, 18], [122, 18], [121, 18], [119, 18], [120, 18], [123, 18]]
```
I suggest adding:
`acts_as_list scope: :product`

**Comment by JDutil** [comment]
Please submit a PR
