### ISSUE TITLE
Deleted products break the user#items view

### ISSUE THREAD

**Issue by adaddeo** [spree/spree#6411]
To reproduce on 3-0-stable:

1. Place a new order saved to a user account (spree@example.com is fine) with any item
2. Delete the item used in the order
3. View the items page for spree@example.com user

The error has to do with the variant not being found due to the deleted_at IS NULL scope. I am not sure why this is happening as I see the special definition of variant in line_item.rb (which if I find this LineItem in the console and call variant it works fine), but for some reason in the view it is using the scoped call.

I'll be happy to submit a PR if someone can give me a pointer on the proper way to fix.

*Edit*
Looks like it's related to https://github.com/rails/rails/issues/10643

**Comment by adaddeo** [comment]
Looks like it's related to https://github.com/rails/rails/issues/10643

**Comment by jasonfb** [comment]
I think we should move to a discontinued_at instead of deleted_at model because deleting products & variants still creates bugs all over the place

**Comment by dhonig** [comment]
+1 for soft delete.  Ive done this without submitting a patch at least once.

**Comment by jasonfb** [comment]
@adaddeo + @dhonig  please see https://github.com/spree/spree/pull/6692 -- that should fully remediate this (*and all other product/variant deletion bugs*)

**Comment by damianlegawiec** [comment]
`Spree 3.1.0` introduced product discontinuation, thanks to @jasonfb :)

https://github.com/spree/spree/blob/master/guides/content/release_notes/3_1_0.md
