### ISSUE TITLE
Main sidebar navigation hidden for extra small devices v3.0-stable?

### ISSUE THREAD

**Issue by tomaswitek** [spree/spree#6417]
There is a `hidden-xs` class on the `main-sidebar` element.
Does it mean that extra small devices are not supported in v3?

![spree_administration_](https://cloud.githubusercontent.com/assets/340649/7756346/e668bc0e-fffa-11e4-8bff-c12458cb5d70.png)

**Comment by LaurensN** [comment]
Same issue here on mobile device.

spree (3.0.6.1)
      spree_api (= 3.0.6.1)
      spree_backend (= 3.0.6.1)
      spree_cmd (= 3.0.6.1)
      spree_core (= 3.0.6.1)
      spree_frontend (= 3.0.6.1)
      spree_sample (= 3.0.6.1)

**Comment by damianlegawiec** [comment]
@tomaswitek  @LaurensN  `Spree 3.2.0` will have fully responsive admin panel

**Comment by mohsen-alizadeh** [comment]
@damianlegawiec Merge this one please.
