### ISSUE TITLE
Which version of spree is running in my store?

### ISSUE THREAD

**Issue by guangyu-shi** [spree/spree#6431]
After trying to upgrade from 2.4.2 to 2.4-stable, I'm not sure which version of spree is running.

1.~$ spree version
3.0.1

2. In Gemfile.lock, it shows

GIT
  remote: git://github.com/spree/spree.git
  revision: 1dd43f22b630dc8840234d59abe4d4eaa2c43623
  branch: 2-4-stable
  specs:
    spree (2.4.8.beta)
      spree_api (= 2.4.8.beta)
      spree_backend (= 2.4.8.beta)
      spree_cmd (= 2.4.8.beta)
      spree_core (= 2.4.8.beta)
      spree_frontend (= 2.4.8.beta)
      spree_sample (= 2.4.8.beta)
------
I'm new to spree, ruby, rails... so pls shed light to what is actually running in my app(i.e. runtime image)?

Bliss,
--G

**Comment by radar** [comment]
`spree version` will be finding the locally `gem install`'d version of Spree, which can be different to your application, as you can see.

The version that your application is using is commit 1dd43f2, from the 2-4-stable branch.

**Comment by JDutil** [comment]
Yup using branches you can see which git commit your on in the Gemfile.lock contents, and whatever version is specified at the time of the commit is what the version is considered.

**Comment by guangyu-shi** [comment]
Both of you are right; its 2-4 stable after I look at the production.log.

But I got another issue now; after upgrading from 2.4.2 to 2.4-stable, I couldn't edit products properly; like, when clicking "Taxons" or "Option Types " on Editing Product page, it shows "loading failed"; looking at the log, it shows:

/ruby/lib/ruby/gems/2.0.0/bundler/gems/spree-1dd43f22b630/api/app/views/spree/api/errors/must_specify_api_key.v1.rabl (0.5ms)

I'm not sure why this happens after upgrading to 2-4-stable; is there any changes between the revisions causing the issue?

Btw, spree makes me very happy, though I'm totally new to the whole system :)); ofbiz could not reach this level, which is too big and buggy.

Bliss,
--G

**Comment by JDutil** [comment]
Ensure that your user has an api key generated, which you can do through the admin users section or manually in the rails console.

**Comment by guangyu-shi** [comment]
Oh, yes, there was a key for the user; tried to regenerate a new key and restart the app, it still got the same problem.

**Comment by JDutil** [comment]
Well the error is indicating that your api key isn't being sent in the request. Please make sure your on the latest 2-4-stable commit, and that your javascript is up to date.  Perhaps you need to recompile it if you've precompiled it.  This is definitely not a bug anymore as it's been fixed, but your javascript may not be up to date.

**Comment by guangyu-shi** [comment]
Yes, its on the latest 2-4-stable commit; not sure why it happens after upgrading...

the more info from the log:

I, [2015-05-27T20:15:16.590140 #5308]  INFO -- : Started GET "/api/taxons?per_page=50&page=1&without_children=true&q%5Bname_cont%5D=&_=1432757793598" for 142.166.197.186 at 2015-05-27 20:15:16 +0000
I, [2015-05-27T20:15:16.591670 #5308]  INFO -- : Processing by Spree::Api::TaxonsController#index as JSON
I, [2015-05-27T20:15:16.591726 #5308]  INFO -- :   Parameters: {"per_page"=>"50", "page"=>"1", "without_children"=>"true", "q"=>{"name_cont"=>""}, "_"=>"1432757793598"}
I, [2015-05-27T20:15:16.594817 #5308]  INFO -- :   Rendered /opt/bitnami/ruby/lib/ruby/gems/2.0.0/bundler/gems/spree-1dd43f22b630/api/app/views/spree/api/errors/must_specify_api_key.v1.rabl (0.5ms)
I, [2015-05-27T20:15:16.594959 #5308]  INFO -- : Filter chain halted as :authenticate_user rendered or redirected
I, [2015-05-27T20:15:16.595075 #5308]  INFO -- : Completed 401 Unauthorized in 3ms (Views: 1.3ms | ActiveRecord: 0.1ms)

**Comment by JDutil** [comment]
Your api key isn't being passed because your javascript is out of date. Make sure it is up to date by recompiling or removing your compiled assets or whatever.  That is the cause of the problem you'll just have to figure out how to make sure your up to date.

**Comment by guangyu-shi** [comment]
Yes, its old javascript causing the issue; but I couldn't find where the actual taxon related js files are located; have rename relevant taxon files to different names, like taxons.js.coffee to   taxons.js.coffee.bak; yet have no any changes.

Strange? where "_"=>"1432834503936"  comes from? 

Parameters: {"per_page"=>"50", "page"=>"1", "without_children"=>"true", "q"=>{"name_cont"=>""}, "_"=>"1432834503936"}

from taxon_autocomplete.js.erb 
 ajax: {
        url: Spree.routes.taxons_search,
        datatype: 'json',
        data: function (term, page) {
          return {
            per_page: 50,
            page: page,
            without_children: true,
            q: {
              name_cont: term
            },
            token: Spree.api_key
          };

the taxon_autocomplete.js.erb of 2.4.2 has : 

ajax: {
        url: Spree.routes.taxons_search,
        datatype: 'json',
        data: function (term, page) {
          return {
            per_page: 50,
            page: page,
            without_children: true,
            q: {
              name_cont: term
            }
          };

So either it should show "token"=>"1432834503936" or nothing for 2.4.2; but why "_"=>"1432834503936"?

--G

**Comment by JDutil** [comment]
It should be sending the token parameter, but your javascript is out of date. You need to sort out your asset pipeline issue to get the up to date javascript.  I don't know exactly what you need to do for your application, but I know that's the problem so once you solve that problem you will be alright.  This isn't a bug that I can help you with.

**Comment by guangyu-shi** [comment]
This is to help some people who are new to rail, spree; I update the old js files with the following command:

$ rake assets:precompile

Bliss,
--G
