### ISSUE TITLE
Unnecessary data retrieved in /api/countries/

### ISSUE THREAD

**Issue by ridem** [spree/spree#6440]
In /api/app/controllers/spree/api/v1/countries_controller.rb, line 10, the states are included but are not rendered in the rabl. Should the states be rendered or should the index action not include the states?
This makes an API call unnecessarily long IMO.

**Comment by JDutil** [comment]
Shouldn't include the states as those are done in a separate api call.  Please submit a PR if you could.

**Comment by ridem** [comment]
Ok thanks! Closing the issue then
