### ISSUE TITLE
Automatically convert item prices when changing default currency in settings

### ISSUE THREAD

**Issue by jacemonje** [spree/spree#6471]
(Using Ruby 2.2.2p95 and Rails 4.2.1)

Initially, changing default currency resets product prices to zero and does not show products from the old currency. It would be a great option to have should owners move their operations elsewhere and need to change currencies without having to manually edit and/or re-add every product back in the database.

**Comment by JDutil** [comment]
If you add prices for each currency you want to switch to the products will show.
