### ISSUE TITLE
bug on variant weight saving on different locales

### ISSUE THREAD

**Issue by alepore** [spree/spree#6480]
On Spree 3.0, 2.4
I noticed error on weight saving from the admin (each time value is multiplied by 10!!)

Reproduction:

``` ruby
2.2.0 :006 > I18n.locale = :it
:it
2.2.0 :007 > Spree::LocalizedNumber.parse("175.0")
1750.0 # <---- wrong!
2.2.0 :008 > I18n.locale = :en
:en
2.2.0 :009 > Spree::LocalizedNumber.parse("175.0")
175.0
```

**Comment by alepore** [comment]
so.. i think the base problem is that i'm on `:it` and i shouldn't get `"175.0"` on the view, but `"175,0"`.

Solutions:
* remove the whole `weight=` Variant method override (number still not locale-formatted)
* transform the value on the view (`number_with_precision()` it's the best choice i think)

Thoughts?
ping to some non-english guys @tvdeyen @mamhoff @kennyadsl

**Comment by tvdeyen** [comment]
Spree should never ever store localized values in the database (It actually does **a lot**, but that's another story). 

So, I vote for the `number_with_precision` usage. :+1:

**Comment by mamhoff** [comment]
Perfect, I concur wholeheartedly. `LocalizedNumber.parse` is - if I understand correctly - only supposed to be used when reading user input, not database values. While you're at it: There's the same issue with `cost_price` https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb#L63 :dancers:

**Comment by tvdeyen** [comment]
@mamhoff but these setters read user input ;)

**Comment by mamhoff** [comment]
@tvdeyen Yep, but at the model level? Shouldn't this be at the controller level?

**Comment by mamhoff** [comment]
This can be so trippy when scripting Spree :8ball:

**Comment by alepore** [comment]
the difference is that, on the admin template, prices are already formatted for the current locale: https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/products/_form.html.erb#L43 , but the weight is not https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/products/_form.html.erb#L43

uhm wait... and height? width? depth? :confused:

**Comment by tvdeyen** [comment]
@mamhoff no, the controller should just give the model the attributes. The model has to decide how to store them. It's its domain.

**Comment by alepore** [comment]
model domains makes sense, but this still looks like an hack to me.
i'm a bit astonished there's not an easy rails way to do this.

**Comment by mamhoff** [comment]
@tvdeyen hm, i disagree. I think this should be handled when you cleanse out the params hash for use in a `save`; but it's true that Rails currently doesn't do this. I think the model layer shouldn't have to know what locale the current user has.

**Comment by tvdeyen** [comment]
You mean some kind of parameter value normalizer? Yeah, that would be great. 

The Spree::LocalizedNumber class does a very well job and this needs to know about the current locale. The locale is a system wide constant for the current request, so I don't see any violations in using it. Not in the model, that's true, but inside the localizer class?

It would be preferable to use a parameter cleaning, sanitizing, normalizing mechanism in the controller layer, but hey, it's ok IMO.

**Comment by mamhoff** [comment]
So then, the right way to go about it would be making sure all view fields are populated with localised values. Also, to provide good examples, all DB columns should have zero as default...

**Comment by tvdeyen** [comment]
:+1: for all number fields to be localized. It would be preferable to introduce a form helper for that, wouldn't it?

But I don't think it's a good idea to default all number values with `0.0`. `nil` values are great for cases where it is important to know if it's even set at all. Zero is not nothing, `nil` is. 

Image code like `product.weight ? do_something_weight_related : skip_weight_stuff_completely`. That wouldn't be possible with default values.

**Comment by mamhoff** [comment]
Coming to think of it: that's actually right. Consensus! :cake:
Am 13.06.2015 12:13 schrieb "Thomas von Deyen" <notifications@github.com>:

**Comment by tvdeyen** [comment]
Es ist immer wieder Ehre mit Ihnen zu diskutieren 😅

**Comment by mmintel** [comment]
I am not sure if my bug is related to this issue.. whenever I save a product it appends another "0" to weight, height and such. I am also using i18n.

so when I have 1500.0 as height and I save the product it becomes 15000.0

**Comment by alepore** [comment]
@mmintel yes it's definitely the same bug

**Comment by maximedelpit** [comment]
Hi there, 

I dont get your final recommandation on this. Should we create a helper for non-currency field and override it with Deface

Or add method such as def weight= / def height= etc. to models such as Product and Variant using LocalizedNumber

It also seems (I'm on Spree 3.0.0) that input field such as height, weight, etc are text_fields.

Thanks a lot for your help

**Comment by tvdeyen** [comment]
Unfortunate there is no final recommendation. [Spree is dead](https://spreecommerce.com/blog/future-of-spree-oss) and everybody is heading over to https://github.com/solidusio/solidus

This is still an issue in Solidus I guess, didn't checked, but you will more likely become a relevant answer and solution to this topic if you join the Solidus community.

**Comment by maximedelpit** [comment]
Woaw, I missed this one. My day wasn't great, you definetly made it ;)

Thanks anyway @tvdeyen

**Comment by tvdeyen** [comment]
I didn't want to make your day worse. The spree death is a bummer but the Solidus community is great.

If you can manage it to upgrade, I would recommend to do so.

**Comment by maximedelpit** [comment]
Thanks a lot for your feedback @tvdeyen

**Comment by damianlegawiec** [comment]
Hi @maximedelpit  Spree is not dead :) This is the [roadmap for 2016](https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016)

**Comment by fabiode** [comment]
Had the same problem here, using pt-BR locale. I used an override in variant and product form with number_to_currency for weight, height, width and depth values on each input, as long as we don't have a correct fix for it.

But I was thinking if LocalizedNumber always using currency format isn't kind of a wrong behavior.

```ruby
separator, delimiter = I18n.t([:'number.currency.format.separator', :'number.currency.format.delimiter'])
```
The scope is always *number.currency*...

If in a specific locale, prices and numbers are displayed in different ways, any resolution in view will still mess things up.

What you think about it?

**Comment by bbonislawski** [comment]
Works properly on master. Closing.
