### ISSUE TITLE
Admin order with default card causes invalid payment created when order is discounted to zero.

### ISSUE THREAD

**Issue by darbs** [spree/spree#6482]
In the backend if you create and order with with line_items and customer info set. If the customer has a default card set and the order is discounted to $0.00, there is an invalid payment created for the $0.00 amount. This was done on 3-0-stable branch.

I believe this has to do with [assign_default_credit_card] (https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/app/models/spree/order/checkout.rb#L288-293) in checkout.rb, but shouldn't the payment step not be created unless payment is [required](https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L44-51)? This never seems to happen via the front end checkout process(for me), only during the admin checkout process. I am not too familiar with the checkout/state_machine inner workings so any help would be appreciated.

**Comment by fiftin** [comment]
I have similar problem, but with frontend too.

**Comment by JDutil** [comment]
Closed by 894d5966e47ed5ba188553c78d40fcf7cd2e99d4
