### ISSUE TITLE
Zero payment for each order

### ISSUE THREAD

**Issue by fiftin** [spree/spree#6499]
For each order creates 2 payments. First payment is zero and invalid. Second payment is correct.
I found method assign_default_credit_card that create this payment, but I do not understand why?

**Comment by JDutil** [comment]
I think the issue is:
1) assign_default_credit_card creates an initial payment
2) when the payment step is submitted the payment attributes https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L239-L256 end up creating a new payment rather than updating existing payment since there is no id attribute passed
3) since new payment is created it invalidates the original https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L31 & https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L203-L209

**Comment by darbs** [comment]
@JDutil would only creating the initial payment in ```assign_default_credit_card``` only if ```payment_required?``` suffice? Or is that only treating the symptom and not the disease?

**Comment by JDutil** [comment]
Would fix just that symptom because this happens whether you need payment or not.

**Comment by fiftin** [comment]
@JDutil What reasons to create an initial payment?

**Comment by fiftin** [comment]
I have overrided method assign_default_credit_card with empty body. Now I have no zero payment. But I don't sure whether it is the right way

**Comment by darbs** [comment]
@JDutil Is there a reason that [existing_card_id](https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L235) defaults to nil instead of the default card payment since its auto created?

**Comment by JDutil** [comment]
I believe that would be because if there wasn't one submitted in the params then that means the user did not select one.

**Comment by darbs** [comment]
@JDutil What about only creating a payment in ```assign_default_credit_card``` if ```payment_required?```. Then defaulting to the ```order.user.default_card``` in ```update_from_params ``` if there is one defined and there is already a payment created from ```assign_default_credit_card```?

**Comment by JDutil** [comment]
@darbs sounds okay to me to skip assign_default_credit_card if  payment_required? is false, but I would not default to anything in update_from_params as that method should be receiving what the user has selected and they could have any number of saved cc's to choose from whether assigned as default or not.

**Comment by darbs** [comment]
@JDutil Not to bump a stale issue but is there any reason for ```assign_default_credit_card```? This auto payment generation just makes weird things happen since the backend is sprinkled with ```order.next``` and ```Spree.advanceOrder```.

**Comment by JDutil** [comment]
It's there so that people can have a default cc assigned to their account that was the purpose, but I don't care if it's changed or removed.

**Comment by JDutil** [comment]
Fixed on master by https://github.com/spree/spree/commit/7a35c69c6f550f435018c67816feba64fe75af0a

**Comment by vmueller71** [comment]
@fiftin I'm trying to override the method assign_default_credit_card in checkout_decorator.rb as well, but can't get it to work. Would you mind sharing your code with me?

**Comment by fiftin** [comment]
@vmueller71 https://gist.github.com/fiftin/411e58bdedd69020a3ce
