### ISSUE TITLE
Error installing Spree with Rails 4.2.2

### ISSUE THREAD

**Issue by jkalef** [spree/spree#6505]
I am getting the following error when trying to install spree in a fresh Rails 4.2.2 app.  I have tried the fixes in issue #6216, along with following the guides step-by-step on github and the spreecommerce tutorials.  

[WARNING] Could not load generator "generators/spree/install/install_generator". Error: uninitialized constant Bundler::Thor::Base.
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.0/lib/bundler/vendor/thor-0.19.1/lib/thor.rb:468:in `<class:Thor>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.0/lib/bundler/vendor/thor-0.19.1/lib/thor.rb:4:in`<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.0/lib/bundler/vendored_thor.rb:4:in `<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.0/lib/bundler/cli.rb:2:in`<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/spree_core-3.0.1/lib/generators/spree/install/install_generator.rb:4:in `<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:334:in`block (2 levels) in lookup'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:330:in `each'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:330:in`block in lookup'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:329:in `each'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:329:in`lookup'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:138:in `find_by_namespace'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/generators.rb:155:in`invoke'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in`require_command!'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:50:in`generate'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in`<top (required)>'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/jaredbranson/.rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/Users/jaredbranson/codecore/mystore/bin/rails:8:in `<top (required)>'
/Users/jaredbranson/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
/Users/jaredbranson/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in`<main>'
Could not find generator 'spree:install'.

Any assistance would be greatly appreciated!

**Comment by vfonic** [comment]
The tutorial pages have been updated. You can check that it works now if you want.

@damianlegawiec you could close this issue as well.
