### ISSUE TITLE
Can't find products by names using ransack

### ISSUE THREAD

**Issue by mbajur** [spree/spree#6506]
Hello,
i have encountered an issue with my spree instalation. I need to find a product by name using ransack params (it's actually related to the fact, that "Add product to order" select2 widget can't find products by it's names, just searching with SKU works). Let's say there is a **Spree t-shirt** in the database and i want to search for it using:

    Spree::Product.ransack(name_cont: 'Spree').result

and that gives me:

    Spree::Product Load (1.3ms)  SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products"."name" LIKE '%Spree%')
     => #<ActiveRecord::Relation []>

which is obviously wrong. However, that SQL query looks totally fine so the only probable part of it that can be broken is the deleted_at IS NULL. I had some troubles with querying for null/not null in the past but i can't remember what the reason was right now. Does anyone has any idea what's going on in here or why it is broken?

ps. i'm using master branch of spree and sqlite database.

**Comment by JDutil** [comment]
Are you using spree_i18n? Probably related to https://github.com/spree-contrib/spree_i18n/issues/530
