### ISSUE TITLE
Can't run test suite successfully

### ISSUE THREAD

**Issue by carlesjove** [spree/spree#6512]
I've been trying to get the test suite to run for a few days, but I'm getting errors.

After bundling all components, if I `cd {component}`, and `bundle exec rake test_app`, I get the error: `Skipping installation no generator to run...` I get this error in all components.

If I `bash build.sh`, all test pass for the `api` component, but I get random failures on the `backend` component. Sometimes 3, sometimes 5, sometimes 6…

I'm os OSX, Ruby 2.2.2. Any help would be appreciated. I'd like to contribute with a PR but I'm stuck with this…

**Comment by JDutil** [comment]
The backend has known frail tests so unfortunately that's not always reliable.  Which components can't you have rake test_app on? It shouldn't be a problem to run each component on it's own.

**Comment by carlesjove** [comment]
I can't `rake test_app` on any component (tried them all). Always get this `Skipping installation no generator to run...`.

**Comment by JDutil** [comment]
It's normal for them to say `Skipping installation no generator to run` since there are no generators to run for these components. I'm not have any issues on using OSX & Ruby 2.2.2 either so I'm not really sure.  Maybe try `bundle update; bundle exec rake test_app; bundle exec rspec` in one of the components.

**Comment by carlesjove** [comment]
Oh Jeff, I'm a bit embarassed right now… I thought `Skipping installation…` was an error message, and that kept me thinking that the script was failing for me. I've done as you said, and it works. Shit, I'm so sorry for this.

If it is ok, I'll add a note about this message to the Testing documentation.

Thank you.

**Comment by JDutil** [comment]
:beers:
