### ISSUE TITLE
precompiling assets

### ISSUE THREAD

**Issue by JohnnyBrofish** [spree/spree#6513]
I tried running 

rake asset:precompile

This doesn't seem to include all the assets. So I included this in development.rb

config.assets.precompile = ['*.js', '*.css']

Running rake asset:precompile now gives the error

Sass::SyntaxError: ".btn.action-void" failed to @extend ".btn-danger".
The selector ".btn-danger" was not found.
Use "@extend .btn-danger !optional" if the extend should be able to fail.
{user}/.rvm/gems/ruby-2.2.1/gems/spree_backend-3.0.1/app/assets/stylesheets/spree/backend/components/_buttons.scss:35

**Comment by singhraj-india** [comment]
i am also having the exact same error. Any solution/workarounds.

**Comment by cdesch** [comment]
+1

**Comment by singhraj-india** [comment]
Try playing with the order in which you have "required" the css assets in your all.css. Reordering it helped me get rid of the issue.

**Comment by AKnopf** [comment]
+1


@singhraj-india What do you mean by playing with the ordering? I only have the generated one, thats pretty simple:
```
/*
 * This is a manifest file that'll automatically include all the stylesheets available in this directory
 * and any sub-directories. You're free to add application-wide styles to this file and they'll appear at
 * the top of the compiled file, but it's generally better to create a new file per style scope.
 *
 *= require spree/frontend

 *= require_self
 *= require_tree .
*/
```

**Comment by jasonfb** [comment]
```require_tree .``` will require everything alphabetically I think. unless you have a very, very small app it is almost always a bad idea. CSS lets you get away with a lot but without explicit ordering of your CSS files, you have very little insight into which files load first and which load last (except I just told you they load alphabetically), which makes finding CSS override problems a pain.

as the error indicates, when you refactor to break out each CSS file into its own explicit line, you'll want to put things like variables and mix-ins at the top, so they can be referenced by other CSS down below (I usually do this by putting colors and variables into their own file, including that first, and then only use those as mix-ins)

in your case I'm guessing ```.btn-danger``` is defined in bootstrap so you would probably need bootstrap included above your CSS

**Comment by bitsapien** [comment]
I get the same error. I tried adding '*.scss' but that did not solve the problem. 'bootstrap' is included before all others, but I still get the error. Any solution ?

**Comment by jasonfb** [comment]
did you include the sass version of bootstrap or just the straight source files?

**Comment by bitsapien** [comment]
Yes I did, still it gives me the same error.

**Comment by bitsapien** [comment]
Is the line to `require` bootstrap added by default by spree? If no, how does I add it ? 
Bootstrap works fine without pre-compilation on my development machine.

**Comment by bitsapien** [comment]
Re-initialising the whole application, helped solve the problem for me.
