### ISSUE TITLE
Customer return: Cannot refund a transaction unless it is settled

### ISSUE THREAD

**Issue by MisinformedDNA** [spree/spree#6522]
When using Braintree in test, when I ship an order and then immediately try to run a return (via `spree_wombat` with Postman), I get the error message: `Customer return could not be fully processed, errors: Cannot refund a transaction unless it is settled. (91506)`. If I then try to submit again, it says that the order has already been processed (200), but the money wasn't actually refunded. This means that Wombat would have no idea that an error state is still active and, thus, no one would no that a refund still needs to be processed.

I'm not sure this would ever happen in Production, but I'm not sure it wouldn't either.

However, without it working in non-production, it makes it hard to determine if everything is working as it should.

Thoughts?

**Comment by JDutil** [comment]
I believe all gateways or at least most reject crediting a charge before it's settled.  I'm not sure why the first attempt is throwing an error, but the second doesn't. Also not sure what the best solution would be to prevent this other than maybe a timeliness validation that it has to have been shipped the previous day before creating the return.
