### ISSUE TITLE
Line Item adjustments are not included in tax calculation

### ISSUE THREAD

**Issue by darbs** [spree/spree#6535]
Currently the only adjustments that are counted for tax calculation are promotions. Any line_item adjustments made that aren't promotions or competing promos are not used for tax purposes. 
This is because the [default_tax](https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/app/models/spree/calculator/default_tax.rb#L28-34) calculator uses [discounted_amount](https://github.com/spree/spree/blob/master/core/app/models/spree/line_item.rb#L68-70) and that only accounts for promo_total. Ideally we should arbitrarily be able to create adjustments(+/-) for a line_item and have the changes reflected in tax.

To remedy this we do something like:
```Ruby
Spree::LineItem.class_eval do
  class_attribute :price_modifier_hooks
  self.price_modifier_hooks = Set.new
  
  def discounted_amount
    amount + promo_total + hook_totals
  end
  
  def hook_totals
    price_modifier_hooks.map { |hook|
      self.send(hook) if self.respond_to?(hook.to_sym)
    }.sum
  end
  
  def self.register_price_modifier_hook(hook)
    self.price_modifier_hooks.add(hook)
  end
end
```

While this works, I feel refactoring the totals logic to have non tax adjustments included in discounted amount would be cleaner.
```Ruby
def discounted_amount
      amount + promo_total + adjustment_total
    end

def final_amount
      amount + tax_total
    end
```

I can open a pr if you guys agree, else I am open to suggestions.

**Comment by JDutil** [comment]
Doesn't adjustment_total include promo_total? Should discounted_amount actually just equal amount + adjustment_total?

**Comment by darbs** [comment]
Currently yes, it probably would be better named as:

```Ruby
   def discounted_amount
      amount + promo_total + non_promo_total
    end

    def final_amount
      amount + adjustment_total
    end
``` 
Where non_promo_total = all adjustments that are not tax and promos. Alternatively we could rename promo_total to something more general and have it encompass all adjustments sans tax. The problem is that line_item adjustments that are not promo do not get calculated in tax.

**Comment by darbs** [comment]
To better illustrate the problem:
```Ruby

adjustment_total = promo_total + tax_adjustment + whatever_is_added_by_adjusters

discount_amount = amount + promo_total
```
Tax uses ```discounted_amount``` so ```whatever_is_added_by_adjusters``` is never used for tax purposes, but is should be if it affects the final price of the line_item.

**Comment by mamhoff** [comment]
Good point! I suggest: `adjusted_total_before_tax`. It is a little long, but says very clearly what's happening. For backwards compatibility, `discounted_amount` could be aliased. This has repercussions in `tax_rate.rb` and `default_tax.rb`.

**Comment by JDutil** [comment]
Should be addressed by https://github.com/spree/spree/commit/77558ec8c0d468a7453edbb8b403058fe16363c7
