### ISSUE TITLE
Promotion caching issue on product page

### ISSUE THREAD

**Issue by yf6** [spree/spree#6539]
When I edit a Promotion that's advertised on a Product page, the change doesn't show up on the product page unless I run `Rails.cache.clear`. 

Steps to reproduce: 
1. create a promotion - save
2. go to a product page that shows this promotion
3. change promotion description text
4. go back to the same product page

Expected: product page shows updated description
Actual result: product page still shows old description

I'm running 
  - Spree 2.4
  - Rails 4.1.8
  - with `config.action_controller.perform_caching = true`

Looking at the code: https://github.com/spree/spree/blob/2-4-stable/frontend/app/views/spree/products/show.html.erb#L1

It looks like the cache is only based on locale, currency and product, not promotions. This seems a bug for me. For my application, I added a simple deface override to include `@product.possilbe_promotions` as part of the cache key too, and that fixes the issue. I'm happy to submit a patch for it too.

**Comment by JDutil** [comment]
@yf6 please submit a PR fixing the cache key.
