### ISSUE TITLE
No RRP / MRP attribute for products / variants

### ISSUE THREAD

**Issue by andyt** [spree/spree#6544]
Hi. I believe an MRP / RRP attribute for products should be in spree-core. Many online retailers display this alongside their own price, which may or may not be a sale price.

I'm happy to give adding this a go, if there's a chance it will be accepted / incorporated.

Andy

**Comment by JDutil** [comment]
Feel free to submit a PR for review many people do use MSRPs.

**Comment by andyt** [comment]
At the moment I'm having some success using @moholtzberg's https://github.com/moholtzberg/spree_msrp on the 3-0-stable branch, so I probably won't attempt this for now.
