### ISSUE TITLE
Checkout: Can't return to 'payment' coming from 'confirm'

### ISSUE THREAD

**Issue by wdspkr** [spree/spree#6546]
On master:
In the checkout process it is not possible to return to the *payment* step once you have advanced to *confirm*. When you try to reach the *payment* step, by link or by entering the 'checkout/payment' url, the *confirm* page will be rendered. The only way to get back is by going to the *delivery* step and advance from there to *payment*.

I was able to track down why this is happening:
https://github.com/spree/spree/commit/018ab756e3c184435610a7e34e83dadf1ffbfa59 introduced an `@order.reload` here https://github.com/spree/spree/blob/master/frontend/app/controllers/spree/checkout_controller.rb#L163, which leads to a reset of the `@order.state`, which has been set by the parameters before. That's the reason why the *confirm* partial gets rendered (the `@order.state` from the DB) instead of the *payment* partial (the `@order.state` that got set with the `params[:state]`).

I might look into solving this myself, but I haven't fully understood what's happening there. So if anyone with more spree insight could look into and easily fix this it would be very much appreciated! Directions which way to walk are also welcome.

**Comment by stephenhmarsh** [comment]
have this problem as well in spree 3.0.1

**Comment by plapcity** [comment]
+1 -- same problem. Thought it was an issue with customization I did but then did a clean Spree 3.0.2.beta install and it is broken there as well.

**Comment by nielspetersen** [comment]
+1 Same problem.

**Comment by JonnieCache** [comment]
I'm seeing this on 3.0.4. Have patched the reload out for now (Project still in development) but I'm worried it will cause other problems. Could a dev clarify the comment that's next to the `reload` call in the code?

**Comment by jasonfb** [comment]
```@order.reload``` is definitely a code smell, and it is one of the worst problems in Spree. Overuse of ```reload``` causes many problems. 

Spree isn't really in active development right now, and it is unlikely anyone will address these bugs. What you are experiencing is the result of poor architecture that has led to these kinds of code-debt problems.

**Comment by nishant-cyro** [comment]
@wdspkr - This issue seems to be fixed in 3.0.5. This commit resolves this - https://github.com/spree/spree/commit/4b0945332c63dc978155b28d57b193be75972b02

cc: @priyank-gupta @Mafi88 @damianlegawiec
