### ISSUE TITLE
Cannot delete line_item through api with address

### ISSUE THREAD

**Issue by darbs** [spree/spree#6548]
Discovered this in sandbox 3-0-stable but presumably it would exist in master as well. The recent commit of #6542 makes the TaxRate be recreated after adjustments are made which seems to cause issues when attempting to delete a line_item through the api with address.

Two things:
* I am not sure [this](https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb#L43) line is necessary, because why are we creating tax before we even have a location? Any details @vrosancic?

* When a line_item is destroyed TaxRate attempts to [update_column](https://github.com/spree/spree/blob/master/core/app/models/spree/tax_rate.rb#L47) on the destroyed line_item raising a ```{ "exception": "cannot update a destroyed record" }```

Steps to replicate: 
1. add line_item to cart
2. proceed to checkout entering a valid address
3. DELETE request to api/orders/:order_number/line_items/:line_item_id with a valid token

**Comment by vrosancic** [comment]
In fact, tax is being calculated without this line that I added, but it is being calculated wrongly, as I wrote in #6475. I think VAT is calculated without location on a default tax rate. Prices with included tax have tax in it already, regardless of location. 

I think we can fix this by calling this line only on adding line item in cart and not on removing it.

**Comment by darbs** [comment]
:+1:  having it only on create 

Currently it looks like the tax adjustment is updated then recreated on every update.

**Comment by JDutil** [comment]
Just create sounds alright to me as well.

**Comment by mamhoff** [comment]
I think just calculating on create should do the trick for now. In the long run, however, we should try to look at some way to see wether we can centralize the whole calculation of adjustments business to one central location that is run on every save. This ties in with the work by @mbj and @dkubb aimed at never ever running `order.update_columns(...)` anymore. 

So yes, only on create, but it isn't clean. I'm happy we have the specs for this now in the test suite.
