### ISSUE TITLE
Double tax charge for state based tax zones

### ISSUE THREAD

**Issue by darbs** [spree/spree#6549]
There are some weird issues that rise when the user inputs an invalid address. Not entirely sure of the cause yet. Also there doesn't appear to be any feedback if the address is entered wrong. 

Steps to reproduce (sandbox 3-0-stable):
1. Create state base default zone.
2. Create two state taxes Ex:
```
North America	 California	Clothing	0.07        No	Yes	Spree/Default Tax	 
North America	 Texas	        Clothing	0.0825	No	Yes	Spree/Default Tax
```
3. Create order with a correct address except zipcode. I used a valid Texas address with a California zipcode.
4. Increment a line_item quantity

**Comment by JDutil** [comment]
I'm not sure why incorrect zip code would matter unless your using a third party tax service.  Spree's TaxRate should be using state not zip code to determine the zone...

**Comment by darbs** [comment]
@JDutil after some investigating i found another issue(?) that may have something to do with this one. Multiple state-based zones in the same [tax_category](https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/app/models/spree/tax_rate.rb#L64-66) all add their individual charge to the order until the address and the order_zone is updated. This results in a crazy amounts of tax being added to the order until its updated. Is this intentional? I feel like tax should not be calculated until the order has an address.

**Comment by darbs** [comment]
Closing with merge of #6579, zone.contains? was the issue.
