### ISSUE TITLE
Can't reduce stock

### ISSUE THREAD

**Issue by DanielBenesch** [spree/spree#6552]
You go to a product in the admin Panel. When you click Stock. There you can increase the stock. But what if you accidentally entered a too high amount? 

There should really be a way to decrease it. 

By the way - is there a way to enter an infinite stock - e.g. for a downloadable product? 

Best regards,

**Comment by darbs** [comment]
For the infinity stock you should make sure the track inventory checkbox is unchecked.

**Comment by DanielBenesch** [comment]
aaah thanks! 

& the other thing: It works when you set a negative quantity and click 'Add stock' .. just in case that somebody has the same issue.. a bit confusing, but okay, it works..
