### ISSUE TITLE
Cannot set product promotionable from admin

### ISSUE THREAD

**Issue by darbs** [spree/spree#6553]
In the views for admin there is no where on the product to set promotionable for a product. I think this got dropped somewhere in 3-0 ui revamp. Was this intentional? It appears its still used in [product.rb](https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/app/models/spree/promotion.rb#L174-182).

**Comment by mvz** [comment]
Unfortunately, the fix for this issue only exposed promotionable for products without variants.
