### ISSUE TITLE
Huge Properties issue

### ISSUE THREAD

**Issue by DanielBenesch** [spree/spree#6556]
To reproduce on 3-0-stable:

Log in as admin.

This is the properties list (if you loaded the sample data): 

![image](https://cloud.githubusercontent.com/assets/12606757/8463430/83b27900-203a-11e5-876a-bac3219962d4.png)

Then go to a product and update its properties (doesnt matter if you really change something, you can just click update if you want to):

![image](https://cloud.githubusercontent.com/assets/12606757/8463474/d25ac7a6-203a-11e5-82d6-23711a3069f3.png)

The properties panel should look the same, we didnt include new properties, but look: 

![image](https://cloud.githubusercontent.com/assets/12606757/8463518/2e831038-203b-11e5-9ec3-f3c0a22ab99a.png)

It adds the properties of the product you updated, no matter if the property already exists in the properties panel or not. So if you work with i18n you would have to update the translation for every property of every product. In addition you have no good overview about your properties. 

Whats interesting: If you look at the picture i have Manufactorer 2 times there in the list. But if I click in the search bar and filter, then i get this:

![image](https://cloud.githubusercontent.com/assets/12606757/8463603/fd0062a8-203b-11e5-835e-e4110489db6d.png)

I have absolutely no clue what is going on.

**Comment by rbngzlv** [comment]
If someone looks this issue, there are a new issue opened in the spree_i18n repository: https://github.com/spree-contrib/spree_i18n/issues/597
