### ISSUE TITLE
Promotion adjustments where adjustable is order are shown twice on overview

### ISSUE THREAD

**Issue by mvz** [spree/spree#6560]
This is with Spree 3.0.1.

The `_order_details.html.erb` partial as one section (`#price-adjustments`) where it generates a line for each promotion adjustment of an order or its line items, and a later section (`#order-charges`) where it generates a line for each adjustment of the order itself, unless the source is a tax rate.

If the order has an adjustment (on the order itself) that is a promotion, it is shown in both sections.

Since there is a check `if order.line_item_adjustments.exists?` around the first section, I _think_ that section should only render adjustments on line items, and not those on the order itself.

**Comment by kushniryb** [comment]
@mvz I'm not sure whether I've understood you correctly but it seems like everything's working like expected.

`#price-adjustments` section includes only line item adjustments applied via promotion [`adjustable_type == 'Spree::LineItem'`]

`#order-charges` section doesn't includes only order adjustments [`adjustable_type == 'Spree::Order'`]

> If the order has an adjustment (on the order itself) that is a promotion, it is shown in both sections
That is simply not true. Would you mind providing steps for replication?

@bbonislawski Can we close this for now?

**Comment by bbonislawski** [comment]
Yeah.

**Comment by mvz** [comment]
As I mentioned this bug occurred in Spree 3.0.1. I turns out it was fixed in 789ff3c51bd13aa0b738a879cc5d94fba17f1459.
