### ISSUE TITLE
Can't Use OrderContents to Add Custom, Backend Only, Options to Line items

### ISSUE THREAD

**Issue by joshhepworth** [spree/spree#6563]
In `Spree::OrderContents#add_to_line_items`, the options passed in are wrapped in the strong parameters class and then the default Spree parameters are white listed. [See here](https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb#L78-L79).

This likely should not be in this model, as the strong parameter methods are meant to be handled in the controller because context is important. The current structure forces me to duplicate this code so I can pass custom attributes to line items in extensions (these are attributes that users should not be able to sent from the front end, and hence attributes that should not be permitted parameters).

What was the original motivation for this being added here? If I were to submit a pull request that removed the `options` from being wrapped in `ActionController::Parameters`, what other areas should I look at to ensure I don't break existing Spree functionality (not sure what the test coverage is like)?

**Comment by darbs** [comment]
I believe you need ActionController::Parameters to have strong paramters work. 

You can extend without overriding code:
```ruby
Spree::PermittedAttributes.class_eval do
  class_variable_set(:@@line_item_attributes, :some_option_attribute])
end
```
You could also restrict updating with cancancan. This is what i do to handle parameters that are only allowable by admin.

**Comment by joshhepworth** [comment]
Yeah, I didn't want to extend in that fashion because that would mean any user in the system could set this value by modifying some HTML or an HTTP request. 
How would you use cancancan to accomplish this?






On Thu, Jul 2, 2015 at 2:41 PM -0700, "Darby Perez" <notifications@github.com> wrote:












I believe you need ActionController::Parameters to have strong paramters work. 



You can extend without overriding code:

Spree::PermittedAttributes.class_eval do
  class_variable_set(:@@line_item_attributes, :some_option_attribute])
end



You could also restrict updating with cancancan. This is what i do to handle parameters that are only allowable by admin.

**Comment by darbs** [comment]
As of the last time i checked cancancan doesnt handle attribute/strong parameters(not sure why not) so its a bit hackish but its something like this:

```ruby
# in ability decorator
can :admin, Spree::MyModel if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')

# wherever you need to check 
# although you could do this part without cancancan
unless can? :admin, current_api_user
  params[:some_param].delete :admin_only_param
end

# or custom admin only api actions
authorize! :admin, current_api_user
```
