### ISSUE TITLE
spec class seems wrong

### ISSUE THREAD

**Issue by masterkain** [spree/spree#6565]
hello,
https://github.com/spree/spree/blob/master/core/spec/models/spree/calculator/shipping/price_sack_spec.rb

I don't believe this is the correct test for this class, and it's a dupe of this https://github.com/spree/spree/blob/master/core/spec/models/spree/calculator/price_sack_spec.rb

**Comment by nishant-cyro** [comment]
@Mafi88 - I think the issue is already fixed by #6968 and we are good to close this one, right?

**Comment by Mafi88** [comment]
@nishant-cyro Yes, you're right.
