### ISSUE TITLE
currency_symbol_position is not an preference options in 3-0-stable, what's the best practice for add-on's that use it?

### ISSUE THREAD

**Issue by simontseng** [spree/spree#6571]
currency_symbol_position is not an preference options in 3-0-stable, what's the best practice for add-on's that use it?

currently I am facing issues with this preference option is no longer at where it was, what's the best practices for this in add-ons or in any of the customisation?

spree-contrib/better_spree_paypal_express#170

also in the readme regarding i18n it is not clear what to do with this changes

**Comment by JDutil** [comment]
You can set it either in your locale files or you can set the options hash here:
https://github.com/spree/spree/blob/master/core/lib/spree/money.rb#L10-L14

So in spree.rb something like `Spree::Money.default_formatting_rules[:currency_symbol_position] = value`

**Comment by simontseng** [comment]
thanks for the tip
