### ISSUE TITLE
2-4-stable Guest user order get's merged with previous logged in user

### ISSUE THREAD

**Issue by peterberkenbosch** [spree/spree#6578]
On a fresh sandbox in 2-4-stable, when a guest checkout is completed it is assigned to the previous logged in user.

Steps to reproduce: (Chrome in incognito mode)

1) Login and complete an order
2) logout
3) complete an order, but choose guest checkout now
4) Login again and go to "My Orders", there are 2 orders now

**Comment by JDutil** [comment]
That would be from https://github.com/spree/spree_auth_devise/blob/master/config/initializers/warden.rb#L2-L10
