### ISSUE TITLE
api not working unless spree mounted at / for 3-0 stable

### ISSUE THREAD

**Issue by blset** [spree/spree#6584]
The urls generated for api calls  do not take into account the fact that spree is mounted somewhere else than /

for a newly installed site, spree mounted at /spree and nothing otherwise in the rails app

**Comment by blset** [comment]
that was not a bug here is the explanation 

In the javascript assets, used by all ajax call, there is a Spree.mountedAt() function which was set so '/' instead of '/spree' because the mount point had been changed several times and the assets were not regenerated

rake assets:clean solved the problem

**Comment by JDutil** [comment]
Yea was going to say there is some weird asset pipeline issues around where spree is mounted, but it should work once assets are properly recompiled.
