### ISSUE TITLE
can_go_to_state? bug

### ISSUE THREAD

**Issue by vrosancic** [spree/spree#6589]
I think there is a bug in this line:

https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L218

It should be like this:
checkout_step_index(self.state) > checkout_step_index(state)

**Comment by vrosancic** [comment]
Can anyone verify this? Also, in spree frontend, there is a line that uses this method and it is strange. It is in set_state_if_present_method and it goes:
redirect_to checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?

Why should we redirect to order.state path if order can go to params[:state]?

**Comment by nishant-cyro** [comment]
@vrosancic - can_go_to_state? functionality seems fine to me, its use in set_state_if_present method is quite confusing.

Created a PR #7120 to create an alias for this. I hope it makes better sense now.
