### ISSUE TITLE
login errors during checkout should redirect to registration page and not the login page

### ISSUE THREAD

**Issue by crystalized** [spree/spree#6591]
When someone tries to checkout their shopping cart and they are not logged in, it redirects them to the <b>/checkout/registration</b> page. If there is a login error when they click the "login" button, it redirects them to the <b>/login</b>. The <b>/login</b> page doesn't have the "checkout as guest" option and the customer wonders where the option went. The "checkout as guest" option is only on the <b>checkout/registration</b> page so the customer has to go back through the shopping cart to get to it. 
Wouldn't it be better if they are already on the <b>checkout/registration</b> page and they get a login error, that it simply redirects to <b>checkout/registration</b> instead of <b>/login</b> ?

I've looked through spree and auth_devise code to try to find out where this happens, but I need some help. Anyone know where this stuff takes place?

**Comment by nishant-cyro** [comment]
@crystalized - The login page is rendered through this line(https://github.com/spree/spree_auth_devise/blob/master/lib/controllers/frontend/spree/user_sessions_controller.rb#L28) in spree_auth_devise upon unsuccessful login.

You need to override create action of user_sessions_controller.

Please let me know if this helps and resolves the issue.
