### ISSUE TITLE
Clean install of 3-0-Stable following readme guidelines results in gem dependency issue

### ISSUE THREAD

**Issue by Koldof** [spree/spree#6597]
This is pretty simple, when creating a clean install of 3-0-Stable you say to run:

    rails _4.2.1_ new my_store

however:

    spree (>= 0) ruby depends on
          spree_core (= 3.0.2.beta) ruby depends on
            rails (~> 4.2.2) ruby

This creates obvious issues when running bundle install/etc.

If you can't recreate it ensure to follow exactly you're guide after you've installed rails, because that's pretty much what I did, the only other install work I did on the new clean install of the server was for passenger and apache.

I'm using Ruby 2.2.2 with rbenv.

**Comment by JDutil** [comment]
Updated readme w/ https://github.com/spree/spree/commit/c4eadc621e55d9b682128e9f7306eb54bc8c9f80
