### ISSUE TITLE
InventoryUnitBuilder creates double inventory units in 3.0

### ISSUE THREAD

**Issue by tesserakt** [spree/spree#6605]
with Rails 4.2.3 I started seeing double inventory_units on Spree 3.0 that would get assigned when this line is called

```
 self.shipments = Spree::Stock::Coordinator.new(self).shipments
```

By changing the InventoryUnitBuilder to the following I fixed it 

```
module Spree
  module Stock
    class InventoryUnitBuilder
      def initialize(order)
        @order = order
      end

      def units
        @order.line_items.flat_map do |line_item|
          line_item.quantity.times.map do |i|
            InventoryUnit.new(
              pending: true,
              variant: line_item.variant,
              line_item: line_item,
              order: @order
            )
          end
        end
      end
    end
  end
end
```

**Comment by tesserakt** [comment]
basically all the includes that I removed was causing the doubling. I couldn't tell whether it was happening just in rails or whether it was also happening due to the states_machine active record plugin which redefines the around_save method which I kept running into when debugging

**Comment by darbs** [comment]
:+1: This was kind of pain to find. If it helps anyone this double inventory unit issue is highlighted when you update a line_item(for exampled through api) on a completed order. It checks the line_item quantity against the doubled inventory units when verifying shipments and then proceeds to remove them resulting in the line_item being removed from shipment.

**Comment by darbs** [comment]
I can successfully replicate this in 3-0-stable sandbox. 

1. Remove all tax zones and create 2 overlapping state based tax zones.
  * USA(Default): Texas, California 
  * Texas: Texas
2. Assign a default tax calculator for Texas.
3. Create/update a shipping method that uses both overlapping zones.
4. Create order with an address that uses the overlapping zones. Eg. state = Texas

**Comment by tesserakt** [comment]
@darbs good find! So it looks like we have a replicatable bug.

**Comment by darbs** [comment]
If anyone comes across this i was able to resolve it by using @tesserakt described method and adding a reload call to the order prior to generating the inventory units.

```ruby
      def units
        @order.reload.line_items.flat_map do |line_item|
          line_item.quantity.times.map do |i|
            InventoryUnit.new(
              pending: true,
              variant: line_item.variant,
              line_item: line_item,
              order: @order
            )
          end
        end
      end
```

**Comment by brunovelasco** [comment]
Inspired by both solutions, I simply reloaded and it worked.

```ruby
module SpreeStockInventoryUnitBuilderDecorator
  def units
    @order = Spree::Order.find(@order.id) # @order.reload didn't work
    super
  end
end

Spree::Stock::InventoryUnitBuilder.prepend SpreeStockInventoryUnitBuilderDecorator
```
