### ISSUE TITLE
3.0.2beta  cancelling an order paid by check  triggers a no method error

### ISSUE THREAD

**Issue by blset** [spree/spree#6609]
it's because the cancel method of Spree::PaymentMethod::Check return nil where it should return an ActiveMerchant::Billing::Response

a solution is to make cancel return what's needed
 def cancel(response)
    simulated_successful_billing_response
  end

instead of currently
   def cancel(response); end

**Comment by tanmay3011** [comment]
@blset Can you elaborate a bit more. Replication steps or anything specific you tried. Since it works fine for me tried payment by check from both frontend and admin end, cancel order and resuming both worked fine.

**Comment by blset** [comment]
Hello


I will do that. But I thought spree was discontinued and was migrating to solidus
is spree 3 finally continued ?

**Comment by tanmay3011** [comment]
@blset Spree is back in development and active again. :)
https://spreecommerce.com/blog/spree-roadmap-announcement

**Comment by blset** [comment]
make an order in back office
make a payment by check
capture the payment
do not ship anything
cancel the order
that triggers an error


line 128 because response is nil

and response is nil because 
line 21 of Spree::PaymentMethod::Check in spree/core/app/models/spree/payment_method/check.rb
cancel method returns nil where it should return simulated_successful_billing_response



the patch is to replace 

def cancel(response)
end

with 
def cancel(response)
simulated_successful_billing_response
end


<img width="1217" alt="capture d ecran 2016-02-11 a 10 44 29" src="https://cloud.githubusercontent.com/assets/567550/12973448/ad308902-d0ac-11e5-93dd-2c71a211df39.png">

**Comment by blset** [comment]
PS with spree 3.05 beta

**Comment by Mafi88** [comment]
Cannot replicate on newest stable (3.0.6.1). Tried with order (paid by check) created from both checkout and admin panel.

**Comment by priyank-gupta** [comment]
The issue was fixed with https://github.com/spree/spree/pull/6790 merge.
