### ISSUE TITLE
Extension pricing hook passes junk data to Active Record

### ISSUE THREAD

**Issue by sfcgeorge** [spree/spree#6610]
Hooks were added to the order process so extensions can affect order pricing, without endless monkeypatching. This was largely for [spree_product_customizations](https://github.com/spree-contrib-variants/spree_product_customizations) (that I'm currently updating, trying to get to work again).

The flow is:

An extension will deface inject fields into a product page's add to cart form. E.g. "length" field for a fabric pricing extension. They are namespaced under the extension name within options key in params. E.g. `name="options[fabric_pricing][length]"`.

The LineItem [`options=`](https://github.com/spree/spree/blob/6b6df854d17e2850f5121d405bc4f1272255f555/core/app/models/spree/line_item.rb#L114) method calls [`update_price_from_modifier `](https://github.com/spree/spree/blob/6b6df854d17e2850f5121d405bc4f1272255f555/core/app/models/spree/line_item.rb#L124) method which passes those options to Variant [`price_modifier_amount_in`](https://github.com/spree/spree/blob/9003b68edede54566dfe7d0ec54d3bd07a246ff4/core/app/models/spree/variant.rb#L162) or [`price_modifier_amount`](hhttps://github.com/spree/spree/blob/9003b68edede54566dfe7d0ec54d3bd07a246ff4/core/app/models/spree/variant.rb#L175) (the duplication here should probably be DRYed up, but that's not the issue).

In either of those methods (they do roughly the same thing) each option key is checked to see if there's a method that's been added to Variant by an extension starting with that name, e.g. `"#{"fabric_pricing"}_price_modifier_amount".to_sym` and calls it.

All this works great, extension price modifications can happen. But now back to the `options=` method it takes all those same options and hands them over to Active Record [`assign_attributes`](https://github.com/spree/spree/blob/6b6df854d17e2850f5121d405bc4f1272255f555/core/app/models/spree/line_item.rb#L115). The problem is we have an extra key from the extension that isn't in LineItem so AR refuses to save! Even if the extension happens to add a field with that name (spree_product_customizations does) it still won't save because the value is just an instance of Active Parameter whatevers.

Anyway, the hotfix I applied was to [monkeypatch `price_modifier_amount_in`](https://github.com/spree-contrib-variants/spree_product_customizations/blob/f1b1392eae368faa97b7661e6dc4eb2abc15e03d/app/models/spree/variant_decorator.rb#L30) and have it delete the key if the method with that name was found. Then AR is happy and everything works. Of course because of the duplication, `price_modifier_amount` would have to be fixed too.

Does this seem like the sensible fix? If so could it be made to core please so I can remove the safety pig. Should probably be done to 3.0 stable and master, the methods have changed slightly but the issue and fix is the same. Thanks :)

**Comment by JDutil** [comment]
Could you submit a PR with a spec? Your patch looks good.

**Comment by sfcgeorge** [comment]
Ok I'll see what I can do :)

**Comment by sfcgeorge** [comment]
I looked at the specs and found this is actually [expected behaviour](https://github.com/spree/spree/blob/77558ec8c0d468a7453edbb8b403058fe16363c7/core/spec/models/spree/line_item_spec.rb#L267) and works for one case. I was misunderstanding a few things, but it still isn't workable for my more complex case.

## Simple Attribute Case

A product page will have extra fields added corresponding to attributes added to `LineItem`. E.g. "inscription_message". When the product is added to cart, the `assign_attributes` call sets this additional attribute on the model.

Other hooks may also be used to adjust the price, e.g. a custom inscription costs $5.

This simple case works great. It's easy to just deface inject an extra field into a product page and add a field to the model and it will be automatically added with no extra logic necessary. 

## Complex Attribute Case

Extra fields on product page are for calculating and adjusting the product's price, but can't be added directly to `LineItem`. This is what happens with spree_product_customizations which needs to set a more complex association on the line item. I was wrong about not needing to set any attributes on the line item—it does otherwise the shop owner can't tell why the price has been adjusted on an order. But the extension was never finished to do this.

I thought the option could be deleted and the hook method could then do the adding to the line item, but the hook is in variant not line item so that can't work. Maybe hooks should be moved to line item?

Really the only way I see to do it currently is for the hook method to have access to the [original options](https://github.com/spree-contrib-variants/spree_product_customizations/blob/23b4ca7f8ff57d911835dad55e983e897b205bbd/app/models/spree/variant_decorator.rb#L33) hash, rather than just its relevant key, then it can [modify its own key](https://github.com/spree-contrib-variants/spree_product_customizations/blob/23b4ca7f8ff57d911835dad55e983e897b205bbd/app/models/spree/variant_decorator.rb#L45) if it needs to. It could also be passed the line item to work with, but then it would need to delete its options to prevent whatever attributes it sets getting clobbered.

It feels like a bit of a hack, but I can't really see a way around it with the current hooks.

This would unfortunately be a breaking change, requiring any hooks to use `options["hook_name"]` rather than just `options`. Github can't (?) do wildcard searched so I have no idea how many people actually use this pricing adjustment hook.

Thoughts? cc/ @metade who [worked on this](https://github.com/spree/spree/commit/181fafab9bcbb365725de41ce765ff29e0743c0f)

**Comment by metade** [comment]
Sorry, I'm a bit confused about what you're proposing...

Are you saying that you don't want the options saved against the line item record? In your example then where do you store how much length of fabric a user requested?

There is a spec for adding gift wrap option against a line item:
https://github.com/spree/spree/blob/181fafab9bcbb365725de41ce765ff29e0743c0f/core/spec/models/spree/line_item_spec.rb#L246

It's expecting to store the gift wrap in the line item record: 
```
expect(line_item).to receive(:gift_wrap=).with(true)
```

If you delete the key from the option, how would this happen?

**Comment by sfcgeorge** [comment]
Yes you are right and I didn't understand the intended behaviour at first. There is still an issue though as detailed in my comment, that I want an extension to be able to modify the options (not necessarily delete).
