### ISSUE TITLE
Error with sidekiq in spree 3-0-stabe

### ISSUE THREAD

**Issue by danielalvarenga** [spree/spree#6625]
When include sidekiq in new project spree 3-0-stable, returns the error "**Cannot define multiple 'included' blocks for a Concern**" ( https://gist.github.com/danielalvarenga/9d7f3a1004541bcb80e2 ).

In example project ( https://github.com/danielalvarenga/spree_new_project_default300 ) you can see the error when execute the command "bundle exec sidekiq".

However if enable "config.cache_classes = true" on "config/environments/development.rb" it works.

**Comment by cedarstarr** [comment]
Hi, take a look at PR https://github.com/spree/spree/pull/6614
