### ISSUE TITLE
How can we set a promotion for add a LineItem with 0 price to order?

### ISSUE THREAD

**Issue by caiqinghua** [spree/spree#6642]
#1. Spree guide

https://guides.spreecommerce.com/user/promotions.html

Product variants added through Line Item Action Promotions will be priced as usual. If your intention is to add a free product, you should do both a Line Item action to add the product, and an Adjustment action to discount the cost of that variant.
#2. Issue

But we can't find  any adjustment action that can discount the cost of variant. And there is no Event Name in Spree 3.0.1?

**Comment by wuboy0307** [comment]
IMHO, I think current promotion action that create line item to cart is quite useless. If I want to add a product with original price to my cart, I can just buy it by myself. This promotion actually doesn't discount anything to customer. 

In my project I add a new promotion action called <a href ="https://gist.github.com/wuboy0307/e0a521486d1b7fbc419a">create_adjust_line_item</a>. The basic idea is to combine create_line_item and create_adjustment together. So once you eligible for this promotion. It will not only add a specific line item, but also create adjustment to it (in your case, it would be a 100% off discount). Hope this help.

**Comment by jasonfb** [comment]
We have done this by adding the line item and then also adding an adjustment for the same amount as the cost of the line item

I agree that a "create free line item" like the one @wuboy0307 has above in CreateAdjustLineItems would be more useful

**Comment by kurapatijayaram** [comment]
Can I achieve the following example promotion :
Rule: Product A
Action: Product A with zero price ?

Thank u,
