### ISSUE TITLE
Admin login redirecting to home after enabling email confirmation module from "devise"

### ISSUE THREAD

**Issue by guangyu-shi** [spree/spree#6656]
After adding "Spree::Auth::Config[:confirmable] = true" to config/initializers/spree.rb, I couldn't login to admin console; it always redirects to the home page; even I comment out the added line, it still redirect to the home page; this happens for both 2.4.2 and 2.4.8.

As a workaround, How can I remove the feature if it doesn't work for now?

Any ideas?
--GS

**Comment by guangyu-shi** [comment]
Found the issue is due to spree_users.confirmed_at not being updated after enabling email confirmation module; you need to update 'confirmed_at' with a date stamp; I use phpmyadmin to do the job; very easy :)

--GS

**Comment by JDutil** [comment]
This sounds like a spree_auth_devise issue.  You can either set confirmable to false or set the confirmed_at timestamp.
