### ISSUE TITLE
Admins should always have api keys

### ISSUE THREAD

**Issue by alepore** [spree/spree#6658]
The backend is not usable without an api key (authenticated API calls everywhere) so we have to ensure all admins users have their api key.
Imho this should be totally automatic and transparent to the end user.

Thoughts?

**Comment by JDutil** [comment]
When you either seed an admin or use the rake task to create them it is handled automatically.  If your adding an admin manually you'll need to generate a key.  This behavior could probably be changed to be a callback/validation in the user model if you wanted, but closing this as a question.
