### ISSUE TITLE
Edit states

### ISSUE THREAD

**Issue by alexandre025** [spree/spree#6674]
Hi !

I've found an issue when clicking on edit state button : 
This is the path for edit state view : /admin/countries/:country_id/states/:id/edit
Link is generated in states list view with the helper "link_to_edit" but :id is nil and record isn't found.

The request generated : 
Spree::State Load (0.2ms)  SELECT  `spree_states`.* FROM `spree_states` WHERE `spree_states`.`country_id` = 94 AND `spree_states`.`id` = 0  ORDER BY name ASC LIMIT 1

I've temporary fixed it by defacing the view, but I hope for a fix in the helper's method

Thanks,

**Comment by jasonfb** [comment]
can you stacktrace that to tell us where that query is generated from? This is useful for that kind of stuff:

https://github.com/ruckus/active-record-query-trace

(hint: you will want to set ```ActiveRecordQueryTrace.level = :rails``` or  ```ActiveRecordQueryTrace.level = :full```)

**Comment by nishant-cyro** [comment]
Not able to replicate in master.

cc: @priyank-gupta @Mafi88 @damianlegawiec
