### ISSUE TITLE
What does the clear_product_properties param do?

### ISSUE THREAD

**Issue by reinaris** [spree/spree#6687]
I was working on Spree core and had no clue why this is there, see:
https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/products_controller.rb#L129

Its defined here:
https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/product_properties/index.html.erb#L30

Does it do anything, I don't get the note above the code and while testing I dind't found any usecase. But maybe I'm missing something.

I could create a PR to remove this.

**Comment by JDutil** [comment]
I'm not sure what it's for. Probably some legacy code used back in the day, and never updated.  I'd try to just remove it, and see what happens.
