### ISSUE TITLE
Spree::User and ransack whitelisting

### ISSUE THREAD

**Issue by alepore** [spree/spree#6707]
I'm having problems to add custom User fields to the ransack whitelist. 
Spree::User doesn't include `Spree::RansackableAttributes` and i'm not able to override `User.ransackable_attributes` because https://github.com/spree/spree/blob/master/core/config/initializers/user_class_extensions.rb comes last.

Should we move all the ransack stuff to `spree_auth_devise`? Any idea?

**Comment by Hates** [comment]
Sorry if this is a bit of a hijack, but we're having the same problem but with products. I can't see a clear way to add attributes to ransackable attributes, especially when I want to add some that are used on the admin side vs customer side. It would probably be easier if this functioned in a similar fashion to permitted attributes.

Any ideas @athal7 ?

**Comment by alepore** [comment]
@Hates for Product and most models it's easy: https://spreecommerce.com/blog/security-updates-2015-8-19

`Spree::Product.whitelisted_ransackable_attributes |= ['presale']`

But there isn't a distinction between frontend and backend ransack at the moment

**Comment by Hates** [comment]
@alepore Brilliant, thanks for the link :+1: I really should RTFB more :cold_sweat:

**Comment by picazoH** [comment]
Hello @alepore did you find a solution for the user model? I'm having the same problem. Thank you in advance

**Comment by athal7** [comment]
for the user model you would have to override the class methods. i would recommend using alias_method_chain so you can maintain supported whitelisting as well.

https://github.com/spree/spree/blob/3-0-stable/core/config/initializers/user_class_extensions.rb#L19:L25

**Comment by picazoH** [comment]
@athal7 thank you I'll try it.

**Comment by fabiode** [comment]
@alepore I've used:
```ruby
Rails.application.config.to_prepare do
  Spree.user_class.whitelisted_ransackable_attributes = ...
end
```

See if it works for you!

**Comment by alepore** [comment]
the only solution i found is to use `config.after_initialize do`...
[this was fixed on master in a proper way] (https://github.com/spree/spree/commit/03c62698451d76e5a970a0a0422c6e39863aa806#diff-452bec49b31c1cb1a9aae26b617f42b3R22) but it's probably too late to port on stable versions

**Comment by ducnguyenhuy** [comment]
I'm having the same problem. How to fix that on 3.0 version. My site was living and I can't convert to master.

Thanks.

**Comment by neverlosty** [comment]
For anyone still on Spree 3, this worked for me in application.rb
`
class Application < Rails::Application  
  config.after_initialize do
      Spree.user_class.class_eval do
        def self.ransackable_attributes(auth_object=nil)
          %w[id email updated_at]
        end
      end
    end
end
`

**Comment by neverlosty** [comment]
For anyone still on Spree 3, this worked for me in application.rb

```ruby
class Application < Rails::Application  
  config.after_initialize do
      Spree.user_class.class_eval do
        def self.ransackable_attributes(auth_object=nil)
          %w[id email updated_at created_at]
        end
      end
    end
end
```

**Comment by sandy1987** [comment]
Hi folks,
When I am trying add attribute with ransack i am getting issues. Please help me I am stuck in last two days but i am not getting any solution.
I am applying in below line in user_decorator.rb file
self.whitelisted_ransackable_attributes = %w[email firstname]

Then i am getting `method_missing': undefined method `whitelisted_ransackable_attributes=' for #<Class:0x00000007796290> (NoMethodError)

Please help me What should I do ?

**Comment by mdavo6** [comment]
@sandy1987 
Just came across the same issue. For anyone else - Try adding the following to the spree.rb initializer:
```
config.after_initialize do
   Spree.user_class.class_eval do
      self.whitelisted_ransackable_attributes =  %w[id email sign_in_count last_sign_in_at created_at]
   end
end
```
