### ISSUE TITLE
Deleting information in product_description_field in backend and saving an empty field

### ISSUE THREAD

**Issue by connecticus** [spree/spree#6710]
Hello! There are a problem in 2.4 branch with deleting data in product_description_field and saving an empty field. 

I use CK editor. By adding once a text in product_description_field I cannot delete it after and save an empty field. I can edit text, but cannot save an empty field.

Thank you.

**Comment by priyank-gupta** [comment]
@connecticus This is working fine in master.

**Comment by aishmita-aggarwal** [comment]
I am too unable to replicate on master.
