### ISSUE TITLE
Ransack whitelist reload problem?

### ISSUE THREAD

**Issue by alepore** [spree/spree#6712]
On some 2.4 and 3.0 projects i have a problem, *only in development environment*, with the ransack whitelists.

I add a custom field:
`Product.whitelisted_ransackable_attributes |= ['offer']`

all works as expected, but when i change any code and refresh the page i get 
`undefined method 'offer_true' for #<Ransack::Search:0x007f87574755f0>`

The whitelist is actually reverted to the default. If i restart the server all is working again.

Seems a reloading problem, any idea?

**Comment by alepore** [comment]
i think `class_attribute` changes just doesn't survive a code reload /cc @athal7

**Comment by alepore** [comment]
This is probably the same thing, with console reload!:

```
2.2.1 :001 > Spree::Product.whitelisted_ransackable_attributes
[
    [0] "description",
    [1] "name",
    [2] "slug",
    [3] "kit",
    [4] "new_arrival",
    [5] "available_on"
]
2.2.1 :002 > reload!
Reloading...
true
2.2.1 :003 > Spree::Product.whitelisted_ransackable_attributes
[
    [0] "description",
    [1] "name",
    [2] "slug"
]
2.2.1 :004 >
```

**Comment by mamhoff** [comment]
I have a similar issue with a custom 'GatewayOptions' class for Payments. If the class attribute is set in an initializer, when the class is reloaded, my shiny class is gone. In what file is your custom class attribute defined? Is it a decorator in `app` or an initializer? If the latter, move it to the former.

**Comment by alepore** [comment]
Yeah, using decorators is the way to go, not initializers.

I think https://spreecommerce.com/blog/security-updates-2015-8-19, which is the only documentation for this breaking change should be updated /cc @JDutil

**Comment by alepore** [comment]
Example:

```ruby
module Spree
  Product.class_eval do
    self.whitelisted_ransackable_attributes |= %w[new_arrival featured available_on]
    self.whitelisted_ransackable_associations |= %w[classifications]
  end
end
```

**Comment by athal7** [comment]
yep decorator works, or you can put it in an initializer inside of a to_prepare block e.g.

```ruby
Rails.application.config.to_prepare do
  Spree::Product.whitelisted_ransackable_attributes |= %w[new_arrival featured available_on]
end
```

**Comment by nishant-cyro** [comment]
@priyank-gupta @Mafi88 @damianlegawiec - We can close this one as decorator seems the correct way of overriding whitelisted_ransackable_attributes.
