### ISSUE TITLE
Slug related validation and clone errors

### ISSUE THREAD

**Issue by cshapeshifter** [spree/spree#6713]
In a fresh spree installation (with the i18n, multi-domain, mail-settings and auth-device extensions), I notice the following two problems and I think they are related hence I'm opening only one issue.
1. [Animated gif here](https://cloud.githubusercontent.com/assets/3042135/9763289/23cb3576-5709-11e5-98d1-9300375adde3.gif). When editing a product and leaving the slug field empty, spree does not give a graceful validation error but instead throws an error 500:
   
   ```
   ActionView::Template::Error (No route matches {:action=>"index", :controller=>"spree/admin/translations", :id=>"1", :resource=>"products", :resource_id=>nil} missing required keys: [:resource_id]):
   ```
   
   Full trace [here](https://gist.github.com/cshapeshifter/b1ad0f9f0e3993d8ef4f#file-stacktrace-500-when-slug-empty). The exact same error occurs when editing translations for a product and leaving all translations for the slug empty. No validation error given, instead it crashes. If I don't use the back button in the browser and fix the product, it remains broken and any pages referencing the product crash as well. I should add that if I for example leave all translations of the product name empty, I don't get a crash but instead the product page is shown and a validation error "Name can't be blank", which makes more sense.
2. [Animated gif here](https://cloud.githubusercontent.com/assets/3042135/9764003/eb045e26-570c-11e5-92f1-a669adc8362b.gif). When trying to clone a product which has translated slugs, it crashes with
   
   ```
   ActiveRecord::RecordInvalid (Validation failed: Slug has already been taken):
   ```
   
   Full trace [here](https://gist.github.com/cshapeshifter/b1ad0f9f0e3993d8ef4f#file-stacktrace-500-when-cloning-product). In the gif I first clone the product when it doesn't have any translated slugs. Then I enter a translation and try to clone again. Note that the translations are identical ("test"). If the translations are not identical, the clone works fine. But that doesn't make sense. Translations should be allowed to be identical. Also, if I enter a translation and the clone fails, and then I remove one translation, the clone continues to fail, unlike before. I saw a bunch of related issues [here](https://github.com/spree/spree/pull/4634) and in [spree-i18n](https://github.com/spree-contrib/spree_i18n/issues/386) but they've all been fixed long ago.

Gemfile, Gemfile.lock and the stacktraces [here](https://gist.github.com/cshapeshifter/b1ad0f9f0e3993d8ef4f)

I've done almost no customizations at all, the install is pretty much vanilla. The only customizations are `config.i18n.default_locale = :de` in `config/application.rb` and the following in `config/initializers/spree.rb`

```
Spree::Backend::Config[:locale] = :en
SpreeI18n::Config.available_locales = [:de, :en]
SpreeI18n::Config.supported_locales = [:de, :en]
```

I also noticed that when I enter an empty product name and hit update, it simply uses the existing name. If I enter an empty master price, it enters 0.00. Imo doing these things should provide a validation error to the user and should not re-use the previous product name or just set the master price to 0. Not sure if this is intentional or related to this bug.

Please let me know if I should open this bug for spree_i18n instead.

**Comment by antoineayoub** [comment]
Hello @cshapeshifter, 

Did you get any answer for your second question ?
I have the same issue and It's seems that the slugs must be uniq and the slug translations must be different. Is that your conclusion ?

Thx
Antoine

**Comment by fbmiranda7** [comment]
@cshapeshifter I can confirm that the first issue still happens, just installed from scratch and had the same issue.
