### ISSUE TITLE
NumberGenerator concurrency issues

### ISSUE THREAD

**Issue by jeffblake** [spree/spree#6719]
I'm seeing a handful of occasions where the unique database constraint on the number column is triggering an exception when many concurrent users are creating orders. I am using Puma, with 18 workers, and 10 threads per worker.

I imagine there is an issue using a singleton method to issue out unique numbers. Perhaps this should be refactored into an instance based method, rather than class/singleton level? Otherwise there would need to be some sort of lock that dequeues out a generated number ensuring that a number is never given to a request twice.

**Comment by fabiode** [comment]
I've encountered a similar problem, using unicorn with 4 workers. But in my case, order number does not have a unique constraint on database. Is this default for Spree?

**Comment by jdatti** [comment]
I've seen the same issue a few days back. We could see they got created almost at the same second.

`2.3.1 :009 > Spree::Payment.group(:number).having("count(1) > 1").count
 => {"PGLJJWET"=>2} 
2.3.1 :010 > Spree::Payment.where(number: "PGLJJWET")
 => #<ActiveRecord::Relation [#<Spree::Payment id: 77953, amount: #<BigDecimal:14097270,'0.13492E3',18(27)>, order_id: 52506, source_id: 30114, source_type: "Spree::CreditCard", payment_method_id: 1, state: "checkout", response_code: nil, avs_response: nil, created_at: "2017-02-11 15:59:43", updated_at: "2017-02-11 15:59:43", number: "PGLJJWET", cvv_response_code: nil, cvv_response_message: nil>, #<Spree::Payment id: 77954, amount: #<BigDecimal:140963e8,'0.15224E3',18(27)>, order_id: 52509, source_id: 30115, source_type: "Spree::CreditCard", payment_method_id: 1, state: "checkout", response_code: nil, avs_response: nil, created_at: "2017-02-11 15:59:44", updated_at: "2017-02-11 15:59:44", number: "PGLJJWET", cvv_response_code: nil, cvv_response_message: nil>]> 
`
