### ISSUE TITLE
Unreachable alert server handled badly

### ISSUE THREAD

**Issue by mvz** [spree/spree#6722]
When http://alerts.spreecommerce.com/alerts.json is unreachable, all of the admin pages fail with a 500 error.

**Comment by Migweld** [comment]
Also seeing this. admin pages fail with the error

**Comment by mvz** [comment]
I worked around this now by disabling these checks from the Rails console:

> Spree::Config[:check_for_spree_alerts] = false

**Comment by mvz** [comment]
This also causes the entire frontend to crawl to a halt, probably because Passenger processes are being kept busy.

**Comment by Migweld** [comment]
I've bypassed it with a decorator
```
module Spree
    module Admin
        BaseController.class_eval do
            def check_alerts
                #Service is no longer available. Skip
            end
        end
    end
end
```
Seems to be relatively quick. YMMV

**Comment by MattFenelon** [comment]
This is happening to us too.

**Comment by esergion** [comment]
Same here.

```ruby
# config/initializers/spree.rb
...
  config.check_for_spree_alerts = false
...
```
removes alerts checking.
Thanks @mvz

**Comment by secoint** [comment]
Same issue. All customers' projects on Spree fail when accessing an admin area. `check_for_spree_alerts = false` solves the issue.

**Comment by GarPit** [comment]
Ebat'!!!

**Comment by secoint** [comment]
@GarPit Igor, :+1: 
Других слов нет (((

**Comment by mr-koww** [comment]
Will Spree fix method to bypass when http://alerts.spreecommerce.com/alerts.json it is not available ???
You broken thousands of its stores around the world !!!

**Comment by aiman-alsari** [comment]
Another solution that doesn't require a restart of a running system is to add an entry to your hosts file to point to some other web server e.g.

127.0.0.1 alerts.spreecommerce.com

**Comment by mvz** [comment]
@aiman-alsari note that my solution also does not require a restart: Just run `rails c production` and type:
> Spree::Config[:check_for_spree_alerts] = false

**Comment by aiman-alsari** [comment]
ah right, of course, I always forget about the rails console. Thanks.

**Comment by JDutil** [comment]
Please set `Spree::Config[:check_for_spree_alerts] = false` if your application is non responsive.  These alert checks should fail gracefully not halt your application.  Which versions are you guys running that are not working?

**Comment by mvz** [comment]
@JDutil I'm running 3.0.4.

**Comment by secoint** [comment]
@JDutil 0.70

**Comment by JDutil** [comment]
Our CoreOS cluster all rebooted for upgrades last night, and caused us some issues with spreecommerce.com / guides.spreecommerce.com / alerts.spreecommerce.com / demos etc... We've restored most of this, and working on the rest. We don't use alerts.spreecommerce.com anymore though so I'd recommend disabling this feature to prevent this from happening. 

@mvz I'm going to cherry-pick / push the change that removes Spree::Alert from all supported versions soon.

Anyone on a version older than 2.2+ should implement one of the workaround such as: `Spree::Config[:check_for_spree_alerts] = false` to disable the feature.

**Comment by JDutil** [comment]
Just pushed update to 2-2-stable, 2-3-stable, 2-4-stable, and 3-0-stable that removes checking for alerts altogether.

**Comment by djones** [comment]
Same issue here.

**Comment by JDutil** [comment]
@djones please update to latest of the stable branches i just mentioned or disable the check altogether with `Spree::Config[:check_for_spree_alerts] = false` in your spree.rb initializer.

**Comment by djones** [comment]
Yup, done. And it's now working again.

**Comment by jasonfb** [comment]
Do you guys use spree-user list? Am I the only non-noob on there? (This has been addressed on the list by now)

re : Process

Seems like an unavailability problem at Spree Commerce can be addressed over email and we could keep Github issues focused solely on the Spree code itself. Perhaps this might be a good opportunity to consider setting up a spree-developer Google group for these kinds of momentary (immediate) issues ?

**Comment by jasonfb** [comment]
(no offense to the noobs on the list but in my defense I have been answering a lot of basic questions lately)

**Comment by dkubb** [comment]
> We don't use alerts.spreecommerce.com anymore though so I'd recommend disabling this feature to prevent this from happening.

@JDutil I'd *strongly* recommend adding a stub file at alerts.spreecommerce.com/alerts.json instead of forcing everyone to disable alerts in the config. Something like this that is a breaking change should be gradually backed out over the course of several months, rather than just switched off without any warning.

In fact, you could probably use the alert system itself to notify people to disable the configuration, and then allow your user base to catch up to the point where you can actually remove the file altogether.

**Comment by AdnanTheExcellent** [comment]
Getting a 500 error too. figured out the problem and found my way to this post. setting check_for_spree_alerts to false fixed the issue for now. Thanks.

**Comment by jasonfb** [comment]
@dkubb --- I don't think a "stub file" will do much good if the whole server is down. Or if spreecommerce.com accidentally messes up their DNS records. Or if the server infrastructure it is running on goes down, etc.

**Comment by jspizziri** [comment]
+1

**Comment by jasonfb** [comment]
@dkubb --- Also Jeff told me once that another reason they want to just get this out Spree is they are paying for the bandwidth to support it (Spree Commerce is, that is). In the eco system of Spree it doesn't feel like it sustainable to have Spree Commerce paying for bandwidth incurred by all the Spree stores on the planet checking the alert system. I will let Jeff speak for himself but I think that's another reason we may want to consider this episode an opportunity just to remove the feature entirely.

**Comment by JDutil** [comment]
We're aware of the problem and have provided a solution which is to set `Spree::Config[:check_for_spree_alerts] = false` or to upgrade to latest 2-2-stable+ 

This service is no longer used, and needs to die this service interruption wasn't intentional, but is just as good a time as any to kill the service altogether. Please no more +1's to this being a problem we know, and it distracts people from reading the solutions.

**Comment by JDutil** [comment]
@jasonfb bandwidth isn't an issue, but the fact that we've had multiple bugs like this and #6465 caused by this feature that we don't even use it needs to be removed so that it is permanently no longer an issue rather than doing stop gaps.
