### ISSUE TITLE
Admin Controllers doesn't work, unicorn timeout

### ISSUE THREAD

**Issue by mr-koww** [spree/spree#6723]
Hi! Since today ALL controllers doesn't work in the admin panel in spree in ALL storefronts (also on different VSP).

production.log:
INFO -- : Started GET "/admin/orders" for *.*.*.* at 2015-09-10 09:58:51 +0000
INFO -- : Processing by Spree::Admin::OrdersController#index as HTML
freeze... and nothing more

unicorn.stderr.log:
ERROR -- : worker=0 PID:26942 timeout (61s > 60s), killing
ERROR -- : reaped #<Process::Status: pid 26942 SIGKILL (signal 9)> worker=0

Everything works locally

All admin controllers doesn't work, but frontend is OK

**Comment by Migweld** [comment]
Possibly related to #6722?

**Comment by mr-koww** [comment]
Yes, thanks!

**Comment by JDutil** [comment]
closing duplicate
