### ISSUE TITLE
Wrong order state after a failed payment with confirm step

### ISSUE THREAD

**Issue by dangerdogz** [spree/spree#6724]
## Version:

Spree 3.0.4 without any third-party or other gems

## Prerequisites:

Spree::Config.always_include_confirm_step = true

## Problem

If the payment is not successful after the confirm step, correct_state redirect the order to the payment state as per intended : 

```ruby
    def correct_state
      if unknown_state?
        @order.checkout_steps.first
      elsif insufficient_payment?
        'payment'
      else
        @order.state
      end
    end
```

Then, ensure valid state set the @order.state to payment instead of complete but it does not save the change, it's only for this request

```ruby
   def ensure_valid_state
      if @order.state != correct_state && !skip_state_validation?
        flash.keep
        @order.state = correct_state
        redirect_to checkout_state_path(@order.state)
      end
    end
```

But the before_payment filter reload the order thus invalidating the state change from ensure_valid_state :

```ruby
def before_payment
      if @order.checkout_steps.include? "delivery"
        packages = @order.shipments.map(&:to_package)
        @differentiator = Spree::Stock::Differentiator.new(@order, packages)
        @differentiator.missing.each do |variant, quantity|
          @order.contents.remove(variant, quantity)
        end

        # @order.contents.remove did transitively call reload in the past.
        # Hiding the fact that the machine advanced already to "payment" state.
        #
        # As an intermediary step to optimize reloads out of high volume code path
        # the reload was lifted here and will be removed by later passes.
        #@order.reload
      end

      if try_spree_current_user && try_spree_current_user.respond_to?(:payment_sources)
        @payment_sources = try_spree_current_user.payment_sources
      end
    end
```

Thus, you have PAYMENT as a url params but before the state is rendered, @order.reload resets the state back to confirm since the ensure_valid_state doesn't save the value. So edit.html render confirm instead of payment and you're stuck with the wrong view for the correct state and there is all kinds of undefined behavior depending on what you try to do with the order after that

If believe #6700 fix the issue but it's master only and there might other implications

**Comment by aishmita-aggarwal** [comment]
I am looking into this.
