### ISSUE TITLE
Shipments AJAX API html should have in single quotes

### ISSUE THREAD

**Issue by adalbertoteixeira** [spree/spree#6730]
File `spree_backend-3.0.0/app/assets/javascripts/spree/backend/shipments.js.erb`,  in line `137`, should be

``` javascript
show.find('.tracking-value').html($("<strong>").html('<%= Spree.t(:tracking) %>: ')).append(data.tracking);
```

instead of 

``` javascript
show.find('.tracking-value').html($("<strong>").html('<%= Spree.t(:tracking) %>: ')).append(data.tracking);
```

The current code resulted in an error when compiling assets for Heroku in a situation where a translation was missing.

**Comment by fiftin** [comment]
May me use method ````j()````:
```
show.find('.tracking-value').html($("<strong>").html('<%= j(Spree.t(:tracking)) %>: ')).append(data.tracking);
```

**Comment by adalbertoteixeira** [comment]
It doesn't work. I get `JSON::GeneratorError: only generation of JSON objects or arrays allowed`.

**Comment by bbonislawski** [comment]
We don't use .erb anymore in `shipments.js` so it's outdated.
