### ISSUE TITLE
Spree CK editor error when upload image 

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree#6734]
I have installed spree_editor and try to upload image. When I choose an image and click "send it to server" button. I got an error "ArgumentError in Ckeditor::PicturesController#create
A copy of Spree::Ability has been removed from the module tree but is still active!". And the console log shows this:
Spree::User Load (1.2ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = ?  ORDER BY "spree_users"."id" ASC LIMIT 1  [["id", 1]]
   (1.0ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = ? AND "spree_roles"."name" = ?  [["user_id", 1], ["name", "admin"]]
Completed 500 Internal Server Error in 103ms (ActiveRecord: 37.6ms)

ArgumentError (A copy of Spree::Ability has been removed from the module tree but is still active!):
  activesupport (4.2.2) lib/active_support/dependencies.rb:479:in `load_missing_constant'
  activesupport (4.2.2) lib/active_support/dependencies.rb:184:in `const_missing'
  spree_core (3.0.4) app/models/spree/ability.rb:63:in `initialize'
  ckeditor (4.1.3) lib/ckeditor/hooks/cancan.rb:42:in `new'
  ckeditor (4.1.3) lib/ckeditor/hooks/cancan.rb:42:in `current_ability'
  ckeditor (4.1.3) lib/ckeditor/hooks/cancan.rb:14:in `initialize'
  ckeditor (4.1.3) lib/ckeditor.rb:184:in `new'
  ckeditor (4.1.3) lib/ckeditor.rb:184:in `block in authorize_with'
  ckeditor (4.1.3) lib/ckeditor/helpers/controllers.rb:13:in `instance_eval'
  ckeditor (4.1.3) lib/ckeditor/helpers/controllers.rb:13:in `ckeditor_authorize!'

Could you please let me know how to fix this?

Thanks.

**Comment by JDutil** [comment]
This is not spree_editor please file your issue there.
