### ISSUE TITLE
Spree REST API returning successful status code on image request, but not creating image and assigning it a null id.

### ISSUE THREAD

**Issue by tommymh** [spree/spree#6741]
I'm sending a file to /api/products/123/images and getting this as a response:

{"id":null,"position":null,"attachment_content_type":"","attachment_file_name":"apple-2.jpg","type":"Spree::Image","attachment_updated_at":"2015-09-19T01:54:03.676Z","attachment_width":1200,"attachment_height":1065,"alt":null,"viewable_type":"Spree::Variant","viewable_id":143,"mini_url":"/spree/products//mini/apple-2.jpg?1442627643","small_url":"/spree/products//small/apple-2.jpg?1442627643","product_url":"/spree/products//product/apple-2.jpg?1442627643","large_url":"/spree/products//large/apple-2.jpg?1442627643"}

As you can see it lists no ID in any of the urls, and no ID for the image.  Is this a mistake I'm making somewhere?

**Comment by vishalzambre** [comment]
@tommymh  Could you please post your request json here. I'm looking into this. will raise PR for same
