### ISSUE TITLE
spree inventory not updating

### ISSUE THREAD

**Issue by krypt2005** [spree/spree#6748]
Hi,
    I have a product with default stock location , it is not back ordered item but when i am buying the product the stock in the product i mean count on ahnd in admin not at all updating but it is showing error when buying the product (out of stock) . stock location is also not back ordered .

M
![stocklocation](https://cloud.githubusercontent.com/assets/845032/10020855/b19f4aaa-6162-11e5-89c1-c29b02303eb4.png)
![stock](https://cloud.githubusercontent.com/assets/845032/10020861/b6b1b514-6162-11e5-90f5-fff148ae54ee.png)

ine is 2.1-stable branch.

Can you please let me know the issue.

Thanks.

**Comment by JDutil** [comment]
Your version is no longer supported, but it should work fine.

**Comment by jasonfb** [comment]
@krypt2005 you  might try debugging inside of the ```finalize!``` method on the ```Spree::Shipment``` object

FYI in the future you may wish to note that general debugging questions can be fielded at the user list https://groups.google.com/forum/#!forum/spree-user
