### ISSUE TITLE
Glyphicon font not loading

### ISSUE THREAD

**Issue by jparr** [spree/spree#6770]
A clean build and bundle of 3-0-stable uses bootstrap-sass 3.3.5 which has a problem.

https://github.com/twbs/bootstrap-sass/issues/920

Changing the dependency in spree_frontend fixes it.
```
s.add_dependency 'bootstrap-sass',  '>= 3.3.5.1', '< 3.4'
```

**Comment by jparr** [comment]
I also fixed it by updating sass in my project.

```
sass (~> 3.3.0)
sass-rails (~> 5.0.4)
```

**Comment by mplewis** [comment]
I am also seeing Glyphicons fail to render.

<img width="805" alt="spree_administration__users" src="https://cloud.githubusercontent.com/assets/1829094/10207580/da7101cc-6792-11e5-81f5-40b0688ce9ca.png">


Gemfile.lock:
```
    spree_frontend (3.0.5.beta)
      bootstrap-sass (~> 3.3.1)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.0.3)
      spree_api (= 3.0.5.beta)
      spree_core (= 3.0.5.beta)
      sprockets-rails (~> 2.2)
```

**Comment by JDutil** [comment]
Please submit a PR updating the dependency.
