### ISSUE TITLE
Update product property always creates new properties even if already exists 

### ISSUE THREAD

**Issue by varandasi** [spree/spree#6778]
Steps:
------

* Create a new product with properties
* Edit product and change property

Expectations:
-------------
It should be reusing the already persisted property, but instead, always creates a new one.

Problem:
------------
There's an issue with find_by_id and globalize. It's documented here: https://github.com/globalize/globalize/issues/423 

It creates a strange query SELECT  "spree_properties".* FROM "spree_properties" INNER JOIN "spree_property_translations" ON "spree_property_translations"."spree_property_id" = "spree_properties"."id" WHERE "spree_property_translations"."name" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' AND "spree_property_translations"."locale" IN ('pt', 'en') LIMIT 1

Solution:
---------
To fix it, in spree_core-3.0.4/app/models/spree/product_property.rb line 23, instead of

```
unless property = Property.find_by(name: name)
```

We can use:
```
unless property = Property.where(name: name).take
```

Gemfile + Gemfile.lock:
-----------------------
https://gist.github.com/varandasi/0d8c29d8191ff109309a
https://gist.github.com/varandasi/50e99d80ab11b3912a7d

Stack traces
------------
https://gist.github.com/varandasi/33cc45eb1df1a271a79c

**Comment by ijohn** [comment]
Hi @varandasi 

I believe this issue is fixed in __3-0-stable__. As reference, you could refer to [spree-contrib/spree_i18n#597](https://github.com/spree-contrib/spree_i18n/issues/597).

**Comment by varandasi** [comment]
Hi @ijohn you're right, sorry about the duplicated issue. I was not using the github branch.
