### ISSUE TITLE
Spree thinks my Rails 4 app is not a rails project

### ISSUE THREAD

**Issue by snoblenet** [spree/spree#6788]
My Rails 4 was working fine until I tried to install spree.

I added `gem 'spree_cmd'` to my `gemfile`, then ran:

````
$ bundle install
$ spree install testivate
testivate is not a rails project.
$ cd ..
$ spree install testivate
Would you like to install the default gateways? (Recommended) (yes/no) [yes] yes
Would you like to install the default authentication system? (yes/no) [yes] yes
Would you like to run the migrations? (yes/no) [yes] yes
Would you like to load the seed data? (yes/no) [yes] yes
Would you like to load the sample data? (yes/no) [yes] yes
     gemfile  spree
     gemfile  spree_gateway
     gemfile  spree_auth_devise
         run  bundle install from "./testivate"
y--migrate=true is not a rails project.
$ spree -v
3.0.4
$ rails -v
Rails 4.2.3
$ cd testivate
$ spree install --auto-accept
     gemfile  spree
     gemfile  spree_gateway
     gemfile  spree_auth_devise
         run  bundle install from "."
--migrate=true is not a rails project.
````

What's going on?

Thanks,

Steven.

**Comment by snoblenet** [comment]
For my own purposes, I was able to fix this by removing `spree_cmd` from my Gemfile, adding in `spree` instead, and running `rails generate spree:install --user-class = User` at the command line, but I'm leaving this issue open for the broader community's benefit unless someone else wants to closer it.

**Comment by damianlegawiec** [comment]
Hi @snoblenet you shouldn't add spree_cmd to your project just `gem install spree`. Spree cmd will be deprecated in future releases, though.
