### ISSUE TITLE
Spree::Store#clear_cache prevents saving a store if nothing deleted from cache

### ISSUE THREAD

**Issue by jumski** [spree/spree#6818]
This given method is used as an `before_save` callback and looks like this:

```ruby
def clear_cache
  Rails.cache.delete("default_store")
end
```

source:
[Spree::Store](https://github.com/spree/spree/blob/master/core/app/models/spree/store.rb#L46-L48)
[Spree::Tracker](https://github.com/spree/spree/blob/master/core/app/models/spree/tracker.rb#L13-L15)

We all know returning false in the callback prevents latter callbacks/actions from running.

According to [rails docs for cache store](http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-delete), the `delete` method will return false if nothing from cache was removed, which makes saving a store impossible.

Not sure if this is a bug tho, because it seems so obvious that it should be catched multiple times already. I can provide PR when someone confirms my reasoning.

Cheers

**Comment by priyank-gupta** [comment]
@jumski As per the rails doc it seems to return `true` if an entry is deleted but I think it will return `nil` (not `false`) if nothing from cache was removed. Which will not prevent the record from being saved.

**Comment by jumski** [comment]
kinda strange, i needed to fix it in current app because it was halting the chain

could not verify atm :( lets keep it closed, thanks
