### ISSUE TITLE
search for state by abbr returns all states

### ISSUE THREAD

**Issue by carchrae** [spree/spree#6826]
using latest 2.3 - just working through a lot of issues caused by the ransackable whitelist security fix.

one thing i noticed was my orders were all coming from sweet home alabama.  the reason was the search for state by abbr returns all states.  

calls to lookup a state by abbr would return all states, eg `api/states?q[abbr_cont]=ny` 

the issue is that there is no ransackable info for state.  resolved with the following 

`initializers/spree.rb`
```ruby
if (Spree::State.whitelisted_ransackable_attributes)
    Spree::State.whitelisted_ransackable_attributes |= 'abbr'
  else
    Spree::State.whitelisted_ransackable_attributes = %w'abbr name'
  end
```

**Comment by carchrae** [comment]
the if is there in case this gets fixed in a later version (the else clause fires right now)

**Comment by damianlegawiec** [comment]
Thanks @carchrae for spotting this!

**Comment by nishant-cyro** [comment]
PR #6989 resolves the issue.
