### ISSUE TITLE
HTML5 Microdata recognises the URL of the product as name

### ISSUE THREAD

**Issue by felipekk** [spree/spree#6839]
I noticed this problem after using Google's webmaster tools to check the structured data that it was able to detect on my spree store. Basically the way the products are marked up when being presented on the home page or inside a Taxon means that Google recognises the url as the product name.

You can see that using [this tool](http://foolip.org/microdatajs/live/) and pasting the markup generated by spree:
````
<div id="product_22" class="col-md-3 col-sm-6 product-list-item" data-hook="products_list_item" itemscope="" itemtype="https://schema.org/Product">
        <div class="panel panel-default">
            <div class="panel-body text-center product-body">
              <a itemprop="url" href="https://loja.coisasdekely.com.br/products/batom-3ce"><img itemprop="image" alt="Batom 3ce" src="https://cdn.coisasdekely.com.br/spree/images/76/small/IMG-20151017-WA0021.jpg?1445119547"></a><br>
              <a class="info" itemprop="name" title="Batom 3ce" href="https://loja.coisasdekely.com.br/products/batom-3ce">Batom 3ce</a>
            </div>
            <div class="panel-footer text-center">
              <span itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
                <span class="price selling lead" itemprop="price">R$35,00</span>
              </span>
            </div>
        </div>
      </div>
````

The JSON tab will show that the name property's content is the URL. According to [this thread](http://stackoverflow.com/questions/6805419/how-to-add-name-and-url-properties-to-the-same-tag) the proper way to do it is to use a span tag inside the a tag:

````
<a itemprop="url" href="http://www.ABCCompany.com/">
        <span itemprop="name">ABC Company</span>
    </a>
````

I'm using spree 3.0, I'm not sure this problem exists on the other versions.

**Comment by felipekk** [comment]
Apparently same code is used on 2.3, 2.4 and master. This seems to be the culprit:

https://github.com/spree/spree/blob/master/frontend/app/views/spree/shared/_products.html.erb#L28

**Comment by damianlegawiec** [comment]
Good catch @felipekk - can you do a pull request with a fix? Thanks :)

**Comment by priyank-gupta** [comment]
Closing wrt #6986
