### ISSUE TITLE
Gem Dependancy Issue using spree 3.0 stable with rails 4

### ISSUE THREAD

**Issue by jigarbhatt** [spree/spree#6841]
I have used 

gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

i have tried & i can not install 
gem 'spree_loyalty_points'

**Comment by jasonfb** [comment]
Looks like https://github.com/vinsol/spree-loyalty-points has no branch after Spree 2.2

I would recommend you fork the gem, upgrade it to be compatible with the latest Spree

Generally GH issues are for problems with the core itself. you can also get general help here https://groups.google.com/forum/#!forum/spree-user
