### ISSUE TITLE
Production mode is not running on port 80 (Rails)

### ISSUE THREAD

**Issue by 99cm** [spree/spree#6861]
rails server -e production -p 80
=> Booting WEBrick
=> Rails 4.2.4 application starting in production on http://localhost:80
=> Run 'rails server -h' for more startup options
=> Ctrl-C to shutdown server
Existing
./Ruby22-x64/lib/ruby/2.2.0/socket.rb:206: in 'bind': Permission denied - bind(2) for 127.0.0.1:80 (Errno::EACCES)

**Comment by jonmast** [comment]
Only root is allowed to bind to port 80 by default. You need to run the command with sudo.

**Comment by 99cm** [comment]
Re: [spree] Production mode is not running on port 80 (Rails) (#6861)


Hello Jonathan,

First of all, thank you for your time for reviewing my post and reply.

It's not easy to solve the issue which is the first raised issue to spree development team.

I installed and developed spree project on one site hosted in our dedicated server provided by SingleHop.
The server is equipped with Windows 2012 Standard Server as OS, IIS 8.5 as web server (including asp.net v 4.5 as framework), Parallels' Plesk Control Panel 12 as admininistration / users interface.

My spree project, mystore, runs at http://localhost:3000 as development mode without problem, and production mode.
But I can't make it run public since IIS 8.5 web server exists at port 80 and asp.net 4.5 provides framework.

I searched and studies online articles and posts online for a while.

Most of articles and posts talking about issues of ruby on rails on linux, apache. Run the command with sudo is one method.
Most of articles and posts about Windows are how to install ruby on rails on windows and a simple rails project. Obviously spree commerce is not a simple rails project.
Few articles and posts tell how to install spree on windows, but at the end http://localhost:3000
I even doubt that there are users who actually run spree production website on windows server.

In windows 'runas' equals with linux 'sudo', but can't recognize command rails server -e production -p 80, etc.
https://technet.microsoft.com/en-us/library/cc771525.aspx 

I opened a ticket of this web issue to request SingleHop Support. SingleHop escalated the ticket to its senior and advanced technician support, who spent a couple of days to investigate the issue, at the end, he said "


Ports below 1024 are privileged ports, and on Linux they require root privileges to run. However, Windows does not use the same permissions model so it's not necessarily compatible. Either way, we can get Rails to run on port 80 if we need to.

That being as it is, it doesn't answer the question that I had posed previously. If we run Rails on port 80, we can't run IIS on port 80 as well -- we can only have one or the other, because only once service can be on a port at the same time.

Unfortunately almost all of the experience we have with Ruby on Rails is within a Linux environment -- within Windows the situation is trickier, and the fact that you're running Plesk makes it even more complicated.

Because Plesk doesn't have a native implementation of Ruby on Rails we would have to install Ruby on Rails through IIS, but Plesk would strip away the configuration changes we made because it rebuilds the IIS config every time a change is made. 

If you can provide details and instructions on how to do this in Plesk I'd be happy to implement this, however as it stands we don't have the ability to implement this. You are, of course, welcome to work on this on your own if you're comfortable making such changes."



Therefore I continue to search online. There are some articles and posts from Microsoft and users that may contain some clues to solve the issue:

1. Announcing: Running Ruby on Rails on IIS8 (or anything else, really) with the new HttpPlatformHandler
http://www.hanselman.com/blog/AnnouncingRunningRubyOnRailsOnIIS8OrAnythingElseReallyWithTheNewHttpPlatformHandler.aspx

2. Helicontech ruby on rails web.config file example
http://www.helicontech.com/zoo/docs/ruby-on-rails.html 

3. Web.config for Ruby on Rails Azure Web Sites 
https://gist.github.com/shibayan/9579313

I have studied and tried a few of days, and concluded, for spree running on windows, web.config file should contains two import parts: one is <handlers>...</handlers>, another <rewrite>...</rewrite>.

I compiled a web.config file, but run into 
HTTP Error 500.19 - Internal Server Error

According to this blog Troubleshooting HTTP 500.19 Errors in IIS 7

http://blogs.msdn.com/b/webtopics/archive/2010/03/08/troubleshooting-http-500-19-errors-in-iis-7.aspx    

Refer to Scenario 3 :

"Another instance where the error code remained “0x8007000d” but the “Config Error” didn’t complain the mal formed XML, rather was about Configuration section encryption. "

I believe, in my case, need to work on configuration section encryption, or malformed XML, or both, if spree team can help or some experienced windows user can.

Tuesday, November 10, 2015, 8:44:07 AM, you wrote:





Only root is allowed to bind to port 80 by default. You need to run the command with sudo.
—
Reply to this email directly or view it on GitHub.





-- 
Best regards,
 China                            mailto:zyizyao@china-guide.com

**Comment by jasonfb** [comment]
I would recommend against running a production Rails environment on Windows. Nearly everybody runs on linux servers. I'm not sure about China but in the West I can't think of a single app I've ever heard of in 10 years of working with Rails that runs a Production Rails app on a Windows server.

**Comment by jasonfb** [comment]
If you, as a developer, feel more comfortable in Windows then running Rails locally on a Windows machine for development is generally accepted, but it is a headache. All the developers I know who run Rails on Windows for development say it is extremely frustrating, there are few resources, and spend a LOT of time configuring their setup.

**Comment by jasonfb** [comment]
@dhonig reminds me that you can also virtualize a Linux distribution (like Ubuntu) inside of a Windows machine. This will probably be a better approach.

**Comment by dhonig** [comment]
@jasonfb or another great solution for this problem could be running it in Docker.
https://rossfairbanks.com/2015/03/06/rails-app-on-docker-using-passenger-image.html

Something makes me think the problem will require understanding how to properly setup a virtual host that proxies requests correctly to the docker container.  This takes 10 minutes in Nginx to setup and an uncertain amount of time clicking around in the IIS console taking guesses in IIS.
