### ISSUE TITLE
Currency doesn't display correctly

### ISSUE THREAD

**Issue by kmolchanov** [spree/spree#6863]
I'm using 3-0-stable of spree. When currency selected to Russian Ruble, symbol doesn't appear near the price.
![selection_001](https://cloud.githubusercontent.com/assets/604392/10903733/ee143c12-821d-11e5-9b8e-7836c9ec75f2.png)
Maybe there is way to configure it and change symbol, and it's not a bug.

**Comment by kmolchanov** [comment]
What do you think about it?

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by damianlegawiec** [comment]
![screen shot 2016-01-31 at 10 21 19 am](https://cloud.githubusercontent.com/assets/55154/12701268/6b00b648-c804-11e5-8cc8-d2e6f4d37b84.png)

On 3.1.0.beta

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this.

**Comment by priyank-gupta** [comment]
@kmolchanov Are you still seeing this issue ?

**Comment by kmolchanov** [comment]
The problem is not in spree. I try it on another computer with Windows OS and it works correctly. So the problem in the browser or fonts maybe I think.

**Comment by priyank-gupta** [comment]
@kmolchanov Maybe you should look into CORS setting from where assets are being served. Not sure but can be the cause.
