### ISSUE TITLE
Admin does not refresh shipping rates if Order is created by frontend

### ISSUE THREAD

**Issue by fabiode** [spree/spree#6864]
Hi there!

I have noticed two behaviors that may confuse some admin users:
- When a order is completed on front-end, if its line items are modified on back-end, the shipping rates of the order (using refresh_shipment_rates method) are refreshed using the default parameter, which is only front-end shipping methods.
- When a order is completed on front-end, the available shipping rates are front-end viewable shipping methods only, _unless admin user updates customer details, even if nothing is changed._

I don't know, but I think this behavior is kind of strange for admin users...

I thought that maybe a **force "refresh shipping rates" button** would be nice and very didactic and would solve this particular problem easily, what do you think? I could make a pull request for it.

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by damianlegawiec** [comment]
Hi @fabiode - please feel free to do a pull request. Spree is back in active development and we'll welcome any contributions done by the community :)

**Comment by fabiode** [comment]
@damianlegawiec oh, that's good news! I'm going to create the PR! Thanks!

**Comment by VygovskySergey** [comment]
@fabiode I can't reproduce these bugs on master, i think it was fixed previously
