### ISSUE TITLE
Spree.admin_path do not affect js hard coded path

### ISSUE THREAD

**Issue by odk211** [spree/spree#6865]
Some request path is hard coded in spree/backend.js.

https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend.js#L60

So Spree.admin_path do not applied.

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by damianlegawiec** [comment]
Thanks @odk211 - this will be fixed in the upcoming 3.1 release (this is the only release where you can set a custom admin path)
