### ISSUE TITLE
They said signup for Github and start using spree because it is easy... 10 hours later, I'm still STUCK!!! Help Me Please.

### ISSUE THREAD

**Issue by Msaibos** [spree/spree#6867]
1stly: I have downloaded all there is to download. Ruby, things call gems, notepad++, etc. I try to follow the instructions (https://github.com/spree/spree#installation) but I can't seem to be getting anywhere. This is frustrating.

Can someone please explain to me what I should do exactly because I can't browse the store. And what is goes in place of 'nnnn' in http://localhost:nnnn?

I am so frustrated because I thought by now I would have set up my store.

Help me please.

=========================================================================
Additional Info that could be helpful in helping me:
----------------------------------------------------------------------------
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

C:\Users\Engineer2\Documents\GitHub> gem list

*** LOCAL GEMS ***

actionmailer (4.2.4, 4.2.2)
actionpack (4.2.4, 4.2.2)
actionview (4.2.4, 4.2.2)
activejob (4.2.4, 4.2.2)
activemerchant (1.47.0)
activemodel (4.2.4, 4.2.2)
activerecord (4.2.4, 4.2.2)
activesupport (4.2.4, 4.2.2)
acts_as_list (0.7.2)
addressable (2.3.8)
arel (6.0.3)
autoprefixer-rails (6.1.0.1)
awesome_nested_set (3.0.2)
bcrypt (3.1.10 x86-mingw32)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
bootstrap-sass (3.3.5.1)
builder (3.2.2)
bundler (1.10.6)
byebug (8.0.0)
camertron-eprun (1.1.0)
cancancan (1.10.1)
canonical-rails (0.0.11)
carmen (1.0.2)
cldr-plurals-runtime-rb (1.0.1)
climate_control (0.0.3)
cocaine (0.5.7)
coffee-rails (4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
colorize (0.7.7)
css_parser (1.3.7)
debug_inspector (0.0.2)
deface (1.0.1)
devise (3.4.1)
devise-encryptable (0.1.2)
erubis (2.7.0)
execjs (2.6.0)
ffaker (1.32.1)
font-awesome-rails (4.4.0.0)
friendly_id (5.1.0)
globalid (0.3.6)
highline (1.6.21)
htmlentities (4.3.4)
httparty (0.13.7)
i18n (0.7.0)
io-console (0.4.3)
jbuilder (2.3.2)
jquery-rails (4.0.5)
jquery-ui-rails (5.0.5)
json (1.8.3, 1.8.1)
kaminari (0.16.3)
loofah (2.0.3)
mail (2.6.3)
mime-types (2.6.2)
mini_portile (0.6.2)
minitest (5.8.2, 5.4.3)
monetize (1.3.1)
money (6.6.1)
multi_json (1.11.2)
multi_xml (0.5.5)
nokogiri (1.6.6.2 x86-mingw32)
orm_adapter (0.5.0)
paperclip (4.2.4)
paranoia (2.1.4)
polyamorous (1.2.0)
polyglot (0.3.5)
power_assert (0.2.2)
premailer (1.8.6)
premailer-rails (1.8.2)
psych (2.0.8)
rabl (0.9.4.pre1)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.4, 4.2.2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.4, 4.2.2)
rake (10.4.2)
ransack (1.4.1)
rdoc (4.2.0)
responders (2.1.0)
sass (3.4.19)
sass-rails (5.0.4)
sdoc (0.4.1)
select2-rails (3.5.9.1)
spree (3.0.4)
spree_api (3.0.4)
spree_backend (3.0.4)
spree_cmd (3.0.4)
spree_core (3.0.4)
spree_frontend (3.0.4)
spree_sample (3.0.4)
sprockets (3.4.0)
sprockets-rails (2.3.3)
sqlite3 (1.3.11 x86-mingw32)
state_machines (0.4.0)
state_machines-activemodel (0.3.0)
state_machines-activerecord (0.3.0)
stringex (2.5.2)
test-unit (3.0.8)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
truncate_html (0.9.2)
turbolinks (2.5.3)
twitter_cldr (3.2.1)
tzinfo (1.2.2)
tzinfo-data (1.2015.7)
uglifier (2.7.2)
versioncake (2.3.1)
warden (1.2.3)
web-console (2.2.1)

---------------------------------------------------------------------------------------------

**Comment by jasonfb** [comment]
I don't know who told you this but clearly "they" gave you bad information.

You need to start by learning Ruby on Rails. A good course will run you through the basics in about 1-2 months, but becoming a good developer takes years of practice.

As far as your set up, most people who use Ruby on Rails on Windows wind up being extremely frustrated, to the point where they spend so much time fighting against their setup that it is prohibitively time consuming to use Rails on Windows. Having said that, it IS possible, but you should seek out help specifically for your set up of Rails on Windows. Most Rails developers use Mac OS X or Linux.

One good place for you to start is http://guides.rubyonrails.org. Spend about a month getting comfortable with installing Rails first before starting on Spree, at the very least.

If you want something "easy" and WYSIWYG you should consider one of the hosted E-Commerce platforms, like Shopify, Bigcommerce, or Wix.

**Comment by yragnos** [comment]
You should probably start with Shopify or get a developer team to assist
you building your store.
Shopify is great for starter stores and you can get the basics up and
running quickly.
Spree gives you more control but you need to be a developer, hacker or hire
a team like w3villa.com to help you.

Regards

Gary Ferguson
619-991-7020

**Comment by Msaibos** [comment]
Thank you so much @yragnos and @jasonfb for the feedback guys. I guess I have no other option but to learn. I wish I was like yo'll guys who have the knowledge already.

**Comment by jasonfb** [comment]
No problem! This forum might be helpful for basic rails setup questions: https://groups.google.com/forum/#!forum/rubyonrails-talk

**Comment by Msaibos** [comment]
Thanks @jasonfb, I will check it out now.

**Comment by dhonig** [comment]
One more thing that @jasonfb didn't mention that would be helpful....
Is if you are going to do rails on Windows, you might look into using Virtual VM and easy to use Linux such as Ubuntu.  Its simply not worth fighting to make rails work reliably in Windows, though I'm sure it has gotten better in recent years...

**Comment by Msaibos** [comment]
I guess the overall effectiveness of Windows has decreased and it has become a necessity to get a high performance PC from Apple. Thanks alot @dhonig

**Comment by dhonig** [comment]
Absolutely not......Get yourself something nice and reasonable, use windows to burn the Linux distro of your choice and get off the the races...Tons of great distros to try, Linux Mint and Ubuntu are ones that are easy to get going with...but experimenting is all part of the fun...Free yourself form c:\ and come to /usr/home :)

**Comment by Msaibos** [comment]
@dhonig I am super clueless I have to say when it comes to developing OS and other softwares... but I am willing to learn. I appreciate the feedback and  I have just researched now what "distros" are. It seems to me that these are other operating systems that can be downloaded on my Windows OS. But won't that create complications? Will the files that I currently have still be there? Do files that run on Windows also run on say Ubuntu?
