### ISSUE TITLE
Failing test: Spree::Api::ProductsController as a normal user with caching enabled returns unique products

### ISSUE THREAD

**Issue by berkes** [spree/spree#6870]
When running the tests on `3-0-stable` the following failure is shown

    1) Spree::Api::ProductsController as a normal user with caching enabled returns unique products
       Failure/Error: product_ids = json_response["products"].map { |p| p["id"] }
       NoMethodError:
         undefined method `map' for nil:NilClass
       # ./spec/controllers/spree/api/products_controller_spec.rb:43:in `block (4 levels) in <module:Spree>'

This spec fails consistently.

**Comment by nishant-cyro** [comment]
@berkes - Can you try it running again in latest 3-0-stable? Because it is working fine for me in both master and 3-0-stable branch.

cc: @priyank-gupta @Mafi88 @damianlegawiec

**Comment by berkes** [comment]
Nope, still failing:

Here's what I did:
```
git checkout 3-0-stable
git pull origin # https://github.com/spree/spree.git
bundle # teach yourself a new language or two while waiting for bundler
```

Now:
````
bundle exec rake test
````

reports
````
  1) Spree::Api::ProductsController as a normal user with caching enabled returns unique products
     Failure/Error: product_ids = json_response["products"].map { |p| p["id"] }
     
     NoMethodError:
       undefined method `map' for nil:NilClass
     # ./spec/controllers/spree/api/products_controller_spec.rb:43:in `block (4 levels) in <module:Spree>'
     # /home/ber/.rbenv/versions/2.1.2/bin/rspec:23:in `load'
     # /home/ber/.rbenv/versions/2.1.2/bin/rspec:23:in `<main>'
````

**Comment by Mafi88** [comment]
@berkes It also works for me and on circleci: https://circleci.com/gh/spree/spree/tree/3-0-stable

Maybe you could try running test by
```
bash build.sh
```

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this @berkes on master as well as on 3-0-stable.

**Comment by priyank-gupta** [comment]
@berkes Not able to replicate this with above steps provided.
Is there anything specific your are doing around this ?
Try syncing 3-0-stable with latest spree:3-0-stable (may be fixed with some code).

**Comment by berkes** [comment]
Thanks for looking into this. 

The people who could not replicate it: are your running all tests with `bundle exec rake test` or are you using another script, binary or tool to run them?

**Comment by aishmita-aggarwal** [comment]
@berkes Yes, I used the above mentioned steps to replicate.
