### ISSUE TITLE
Failing test: Rabl Cache doesn't create a cache key collision for models with different rabl templates

### ISSUE THREAD

**Issue by berkes** [spree/spree#6871]
1) Rabl Cache doesn't create a cache key collision for models with different rabl templates
         Failure/Error: expect(response.status).to eq(200)
           
           expected: 200
                got: 422
           
           (compared using ==)
         # ./spec/requests/rabl_cache_spec.rb:14:in `block (2 levels) in <top (required)>'

This spec fails consistently in spree `3-0-stable` HEAD.

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this @berkes on master as well as on 3-0-stable.

**Comment by Mafi88** [comment]
Also can't replicate.
