### ISSUE TITLE
Sort products via drug and drop at taxons page

### ISSUE THREAD

**Issue by Pofigist** [spree/spree#6876]
When i try to sort products  server return 401 (Unauthorized).
 <code>Rendered /home/pofigist/.rvm/gems/ruby-2.2.3/gems/spree_api-3.0.0/app/views/spree/api/errors/must_specify_api_key.v1.rabl (0.8ms)</code>
<code>Filter chain halted as :authenticate_user rendered or redirected</code>
<code>Completed 401 Unauthorized in 5ms (Views: 2.3ms | ActiveRecord: 0.5ms)</code>
Api key generated and present for current user. 
I use Spree branch '3-0-stable'

**Comment by jasonfb** [comment]
The API Key itself should be visible in your request/response logs (the rails logs). Can you inspect that to see if it is being passed by the front-end correctly?

Did you try debugging directly inside of authenticate_user and stepping through the method line-by-line to see exactly why it thinks there is no API key?

-Jason

**Comment by Pofigist** [comment]
data from front end:
product_id:90
taxon_id:13
position:0
And api key not passed to server

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by Pofigist** [comment]
Sorry, in version 3.0.1 this bug was fixed
