### ISSUE TITLE
Cannot delete RMA reasons or refund reasons

### ISSUE THREAD

**Issue by cshapeshifter** [spree/spree#6878]
Not sure if this is a bug or a feature, I'm honestly confused. New refund reason or return authorization reasons created through the back-end show up in the list of reasons and can be edited (name and active yes/no), but they cannot be deleted.

![2015-11-14-213041_839x642_scrot](https://cloud.githubusercontent.com/assets/3042135/11165694/02e112b2-8b17-11e5-83d2-9988b58ccd2a.png)

Should I destroy such records via the rails console? Are there any consequences to deleting a reason (assuming it hasn't been used by any returns/refunds)?

**Comment by jasonfb** [comment]
If the object is not linked to any other object, yes you can safely delete it. Otherwise, I think you can mark them "inactive"

Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by cshapeshifter** [comment]
I didn't realize that. This is off topic to the issue, but... there's no indication on the spree sites that spree is no longer under development. What does it mean? We only recently chose Spree for our shop project for various reasons but I always assumed that spree was being worked on and the community seems alive enough. Is there some sort of roadmap or any other source of information regarding the present and future of spree? I apologize for asking these questions here.

**Comment by jasonfb** [comment]
see https://spreecommerce.com/blog/future-of-spree-oss

also https://github.com/solidusio/solidus

**Comment by priyank-gupta** [comment]
@cshapeshifter Spree is back in development and active again. :)
https://spreecommerce.com/blog/spree-roadmap-announcement

I can verify this and agree that we should have something like you mentioned above.

**Comment by tanmay3011** [comment]
Working on the same feature, will create a PR.

**Comment by jasonfb** [comment]
I would strongly advise that moving forward we adopt two concepts for this, which could apply (relatively) universally:

deleted_at -- uses paranoid gem to do "soft-deleting", objects are deleted in object graph but left in database

retired_at (or another nomenclature, like discontinued_at, etc) -- this was an object used in the past (and is referenced by other objects) and now is no longer used


In this way, you should create a parallel scope for the object that restricts only to the non-retired ones.

The problem with deleting objects once other objects reference them is that you will undoubtedly create many ```nil``` reference bugs. 

For this reason, I almost always add ```before_destroy``` validation, which applies to the soft-delete, which checks to make sure no other objects reference this object. So basically, the premise it, if no other objects reference this object it is OK to delete, if it is referenced, use the retired flag instead. 

You will note that some work I did on the unreleased 3.1 line applies this pattern to variants and products.

**Comment by tanmay3011** [comment]
@jasonfb Using deleted_at seems right to me as well

retired_at seems to be a complex way of handling the issue which you are pointing to, I would like to handle it in a much easier way by using `dependent: restrict_with_error` on association(restricting objects to be deleted if they associated). Thus this won't create any `nil` reference bugs.

Sounds good?
