### ISSUE TITLE
Order merge on login can still fail

### ISSUE THREAD

**Issue by mvz** [spree/spree#6880]
There are still cases where bad data can make order merge on login fail due to bad, old, data. We are seeing issues where Adjustments no longer have a valid adjustable, causing their after_destroy callback to fail.

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by tanmay3011** [comment]
@mvz Can replicate this. Looking into it.

**Comment by fabiode** [comment]
That can also happen when a adjustable was a Promotion that does not exist anymore, during merge or just viewing the incomplete order. In this specific case, I think the adjustment should be removed from order when adjustable returns nil and order is incomplete.
