### ISSUE TITLE
Admin modify product form adds zeros to weight, height, width, depth and price when store language is set to other than English

### ISSUE THREAD

**Issue by GerardGarcia** [spree/spree#6883]
When updating a product each time you update the product a zero is appended to each of these five fields.The store is configured in Spanish, English and Catalan and this only happens when the language is set to Spanish or Catalan.

**Comment by jasonfb** [comment]
Spree isn't really in active development right now, and it is unlikely anyone will address these bugs.

**Comment by dhonig** [comment]
@jasonfb, I didn't realize Solidus.io had a velvet rope :)  But I'm sure Mr. Garcia will find his way :)

**Comment by GerardGarcia** [comment]
@jasonfb Oh I didn't realize that Spree has been acquired. I'll have to solve this myself.. or wait for a upgrading procedure from Spree 3 to Solidus.

**Comment by damianlegawiec** [comment]
Good catch @GerardGarcia - could you propose a patch? 

BTW. Spree is back in active development, read the [roadmap for 2016](https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016)

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this, @GerardGarcia. Could you please share steps to replicate? :)
