### ISSUE TITLE
#6567 "spree install" hangs while "bundle install from

### ISSUE THREAD

**Issue by udit7590** [spree/spree#6884]
I can replicate the issue when I use database as mysql or postgres for my rails app and then try to spree install. Trying with rails 4.2.5.

**Comment by jasonfb** [comment]
there's actually a NUMBER of non-spree related reasons why bundler hangs, have you tried deleting ~/.bundle in your home directory?

Did you recently upgrade to Mac OS X El Capitan? Several of the devs I work with, including myself, experienced hanging after the upgrade.

As well, have you read through this SO post: http://stackoverflow.com/questions/9467756/bundler-when-attempting-to-update-or-install-will-hang-forever

This is mostly likely unrelated to Spree and caused by your system setup

**Comment by iqbalhasnan** [comment]
I'm having the same issue as well. I'm on Rails 4.2.5

I can create new rails project and run `bundle install` without any problem

but when I add `gem 'spree'` to my gemfile and run `bundle install` it will stuck there forever
```Ruby
$ bundle install                                                                                                   
Fetching git://github.com/spree/spree.git
```

**Comment by udit7590** [comment]
@jasonfb No I didnt update to El Capitan yet. I went on debugging the issue myself at some level and after inserting some debugging points observed that problem was not with bundle install but with 'spree install generator' not getting called after the bundle install. I observed that it is stuck at spring. On removing the spring gem I was able to proceed further. Any ideas now? Perhaps integration issues with spring?

 Here is what the stacktrace looks like on interrupt

     gemfile  spree
      append  Gemfile
     gemfile  spree_gateway
      append  Gemfile
     gemfile  spree_auth_devise
      append  Gemfile
         run  bundle install from "."
         run  rails generate spree:install --migrate=true --seed=true --sample=true --user_class=Spree::User --auto_accept from "."
^C/Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:254:in `system'/Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/run.rb:98:in `gets': Interrupt
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:254:in `run'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spree_cmd-3.0.4/lib/spree_cmd/installer.rb:122:in `block in initialize_spree'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spree_cmd-3.0.4/lib/spree_cmd/installer.rb:121:in `initialize_spree'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
: Interrupt
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/run.rb:98:in `verify_server_version'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/run.rb:56:in `run'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/run.rb:37:in `warm_run'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/run.rb:26:in `call'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/command.rb:7:in `call'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/rails.rb:24:in `call'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spree_cmd-3.0.4/lib/spree_cmd.rb:14:in `<top (required)>'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client/command.rb:7:in `call'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/client.rb:28:in `run'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/bin/spring:49:in `<top (required)>'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spree_cmd-3.0.4/bin/spree:2:in `<top (required)>'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/binstub.rb:11:in `load'
	from /Users/vinmac33/.rbenv/versions/2.2.0/bin/spree:23:in `load'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.4.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/vinmac33/.rbenv/versions/2.2.0/bin/spree:23:in `<main>'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vinmac33/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vinmac33/Desktop/SPREE/apps/first_spree/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by jasonfb** [comment]
I believe that issue got reported on https://github.com/spree/spree/issues/6567

although I have not seen that specific issue myself, in many cases bundler hanging is caused by corrupted gems that are stored locally on your hard drive. Try to remove & reinstall bundler along with all of its gems, forcing them to be re-downloaded from ruby gems.

**Comment by damianlegawiec** [comment]
Not a spree issue, like @jasonfb wrote it happends when you have some corrupted gems on your local drive. Try with different version of ruby with the help of rvm/rbenv
