### ISSUE TITLE
Cannot install spree_static_content.

### ISSUE THREAD

**Issue by bishisht** [spree/spree#6885]
I cannot install spree_static_content. My gem file is as follows. 
source 'https://rubygems.org'
gem 'rails', '4.2.1'
ruby '2.2.2'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'spree', '3.0.1'
# gem 'spree_core', '~> 3.0', '>= 3.0.4'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'rails_12factor', group: :production
gem 'pg', group: :production
gem 'aws-sdk', '< 2.0'
gem 'paperclip'
#gem 'unicorn'
gem 'spree_liqpay', github: 'kukareka/spree_liqpay'
# gem 'spree_static_content', '3.8.0'
# gem 'spree_static_content'
# gem 'spree_editor'
gem 'puma', group: :production
gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express', branch: '3-0-stable'
gem 'newrelic_rpm'

i get following error when i tried to install spree_static_content
Updating git://github.com/spree/spree_gateway.git
Updating git://github.com/spree/spree_auth_devise.git
Updating git://github.com/kukareka/spree_liqpay.git
Updating git://github.com/spree-contrib/better_spree_paypal_express.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    spree_core (>= 3.0.4, ~> 3.0) ruby depends on
      rails (~> 4.2.2) ruby

    rails (= 4.2.1) ruby

**Comment by jasonfb** [comment]
your Gemfile specifies RAils as 4.2.1 but spree-core needs it at 4.2.2.

to fix this you just run ```bundle update rails```

This is not a spree bug, you just need to get more comfortable with bundler

**Comment by jasonfb** [comment]
actually that is bad advice, you will want to change the rails version in ```Gemfile``` (to ```4.2.2```) and then also run ```bundle install```

**Comment by bishisht** [comment]
now i am getting another error :(
spree_static_content-0.60.1/lib/spree_static_content_hooks.rb:1:in `<top (required)>': uninitialized constant Spree::ThemeSupport (NameError)

**Comment by priyank-gupta** [comment]
@bishisht Not able to replicate this.

**Comment by bishisht** [comment]
@priyank-gupta neither can  I. I think i have mismatched versions.
