### ISSUE TITLE
Admin: Bottom per-page drop down non-functional

### ISSUE THREAD

**Issue by jheilema-nerdery** [spree/spree#6887]
Steps to reproduce:

* Load any index screen in the Spree Admin that has two per-page selects (top and bottom of the list). /admin/orders is a fine example.
* Change the value of the second per-page select. Observe that the page does not reload.
* Change the value of the first per-page select. The page reloads and the per-page selection is honored.

Expected result:
* the second per-page drop down submits the form and reloads the page, changing the amount of items displayed.

I can reproduce from a vanilla install of Spree, in Chrome 46.0. Gist of the /Gemfile(\.lock)?/ for anyone interested: https://gist.github.com/jheilema-nerdery/f189c4508b61e0cc264e

I have an idea that this is caused by the JS for the page not reading multiple duplicated DOM ids. I can potentially submit a pull request if someone else doesn't get it first.

**Comment by damianlegawiec** [comment]
Thanks @jheilema-nerdery for reporting - fixed & waiting for pull accept of another team member(s), will be backported to 3.0.x also
