### ISSUE TITLE
Bundler could not find compatible versions for gem "rails"

### ISSUE THREAD

**Issue by saimon69** [spree/spree#6896]
Can you please help? I am confused because 'rails -v' returns 'Rails 4.2.5'

Thank you for your help!

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    spree (= 3.0.4) ruby depends on
      spree_core (= 3.0.4) ruby depends on
        rails (~> 4.2.2) ruby

    rails (= 4.0.2) ruby

**Comment by damianlegawiec** [comment]
Install the newest version of rails 
```
gem install rails
```

Spre 3.0 required at least 4.2.2
