### ISSUE TITLE
order.shipments.first.inventory_units.count != order.line_items.count

### ISSUE THREAD

**Issue by trungnguyenhuu** [spree/spree#6897]
In admin portal, Spree use inventory_units in shipments to display list of products that user bought, but Spree use order.line_items to caculate order's total. For some reason, size of inventory_units of shipment  is smaller than the size of line_items, so admin just see a sub list of product, so order's total don't match total of this sub list. How can I resolve this?

**Comment by tanmay3011** [comment]
@trungnguyenhuu Tried replicating your issue but wasn't able to replicate it. Can you elaborate a bit more or replication steps will be very helpful in replicating the issue.

**Comment by trungnguyenhuu** [comment]
Thank you. I can't replicate this issue too. What I did updated cart, then
inventory units in shipment will equal line items count.
Vào Th 4, 10 thg 2 2016 lúc 19:11 Tanmay Sinha <notifications@github.com>
đã viết:

**Comment by trungnguyenhuu** [comment]
By the way, can you explain me about inventory unit in shipment? What is
main different between inventory unit and line item?. If you have any
document about inventory unit, can you give it for me? Thank you.
Vào Th 4, 10 thg 2 2016 lúc 23:17 trung nguyen huu <
trungnguyenhuu262@gmail.com> đã viết:

**Comment by nishant-cyro** [comment]
@trungnguyenhuu - Each inventory unit record tracks one "physical" item in an order. It's used to track individual items against an order, similar to how line_items does it, except inventory units are for each individual item, rather than for each unique grouping of items.

I hope this explains about Inventory unit.

**Comment by tanmay3011** [comment]
@nishant-cyro :+1: 
@trungnguyenhuu  Explanation given above is a appropriate one.

**Comment by trungnguyenhuu** [comment]
Great explanation, thank Tanmay, Nishant.
Vào Th 5, 11 thg 2 2016 lúc 02:19 Tanmay Sinha <notifications@github.com>
đã viết:

**Comment by tanmay3011** [comment]
@trungnguyenhuu Can you please close this issue incase it helped you.
