### ISSUE TITLE
Order#empty! should restart_checkout_flow

### ISSUE THREAD

**Issue by jalada** [spree/spree#6901]
I encountered a bug when using `Order#empty!`. It clears the shipments, but it doesn't `restart_checkout_flow` so the order remains in the `confirm` step. That means you never go through the delivery state, so shipments are never recreated, amongst other things.

I might be wrong, but I feel like `empty!` should `restart_checkout_flow`?

**Comment by damianlegawiec** [comment]
Hi @jalada - could you propose a patch to fix this behaviour? Thanks :)

**Comment by priyank-gupta** [comment]
@damianlegawiec @tanmay3011 has provided a PR against this issue (merged now). I think we can close.
