### ISSUE TITLE
taxons not loading says "searching"

### ISSUE THREAD

**Issue by ducinc** [spree/spree#6909]
I am on the admin side of spree and have new products to add to website. I've added all style info, images, variants etc. Then I'm clicking a specific style, clicking product details and trying to select a taxon but when I place cursor in text box it just keeps saying "searching" and eventually times out. Please help.

**Comment by yragnos** [comment]
Check your settings are taxonomies and taxons set up correctly?

ᐧ

Regards

Gary Ferguson
619-991-7020

**Comment by ducinc** [comment]
Gary, as far as I know yes. We had contracted out a web developing company that launched our site originally and made the skeleton to spree for us so we could then easily add things and make edits. I am trying to add new styles to existing categories already created on the site.

**Comment by ducinc** [comment]
I see categories under taxonomies, but when I checked the taxon tab and clicked "find taxon" its doing the searching thing again.

**Comment by ducinc** [comment]
After reading the user guide for spree, I'm not seeing the "tree" display for me to add taxons. I am only on the admin side of spree not coding or anything, very basic. Can you assist?

**Comment by krzysiek1507** [comment]
@ducinc have you got API key for your user? You can generate API key in ```admin panel -> Users -> selected user -> Generate API key```

**Comment by Mafi88** [comment]
I believe @krzysiek1507 is right.
Did it solve your problem @ducinc?

**Comment by ducinc** [comment]
Yes that's what it was! thanks!
Now having issues re-arranging taxons. Whatever you load last is seen last, I'm loading new merchandise and want the items to show first! I'm able to rearrange but it doesn't save, it defaults back to old sequence. Any advice on this?

**Comment by priyank-gupta** [comment]
@ducinc Not able to replicate. Can you please give a use case around this ?
