### ISSUE TITLE
API: checkouts_controller, load_order does not render the error if insufficient stock.

### ISSUE THREAD

**Issue by priyank-gupta** [spree/spree#6915]
Steps to reproduce:

Create a cart with some item using api.
Move to address state.
From admin console decrease the available product quantity for the item.
Move to next state. Instead of returning an error for insufficient quantity it moves to the next state.

**Comment by tanmay3011** [comment]
@priyank-gupta I can replicate this. Working on a fix for the same.

**Comment by tanmay3011** [comment]
@priyank-gupta There seems to be functionality of unshippable line_items in spree if we move from address to delivery and variant is out of stock but still backorderable. It will be added to the list of unshippable items which when available at backend can be shipped again.
