### ISSUE TITLE
Out of stock (OOS) product pages

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#6941]
Currently, on OOS product pages there is still rendered cart form which leads to misinformation for the user (user can try to add it but will get an error which will lead to frustration and lower conversion rates).

Cart form should be  hidden if variant cannot be added to cart. If all variants are out of stock there shouldn't be cart form at all on this page. 

@Mafi88 @jitendra @priyank-gupta - what our your thoughts guys?

**Comment by Mafi88** [comment]
I agree, cart form should only be visible when variant can actually be added to cart.

**Comment by priyank-gupta** [comment]
:+1:
