### ISSUE TITLE
Spree Address book merged into Core

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#6942]
In our experience https://github.com/romul/spree_address_book is one of the most common extensions that we integrate for our customers and it isn't even moved to spree-contrib. This extensions features are  highly connected to the core experience and maybe we should think about merging it into the spree gem itself. It's really a basic set of features for any e-commerce platform.

@Mafi88 @jitendra @priyank-gupta - what are your thoughts, guys?

**Comment by Mafi88** [comment]
I think it's a good idea. Spree saves all addresses in database anyway, so merging this extension will just provide better usage of them.

**Comment by dhonig** [comment]
This makes sense very common feature.  Its a rare case whre I would agree it should be core.  But it will need some updates to make it into 3.0

**Comment by nishant-cyro** [comment]
I believe we should keep original spree code as lean as possible. There are many projects in which I haven't used this extension.

In my opinion we should keep it out of spree code, if we think it is that usable extension we should keep it updated.

**Comment by priyank-gupta** [comment]
@damianlegawiec I think, keeping this as an extension seems fine to me. Also, may be we can move this to spree-contrib and give a full support for the same.

**Comment by odk211** [comment]
I'm trying to use spree_address_book in spree 3.1-beta now, so I'm glad when spree_address_book is moved to spree-contrib. :)
I like spree_address_book's Address model feature.
- Order do not clone Address.
- Address is immutable when some order use it.

It looks nice that original spree-core adopt these feature, even if address_book feature is an extension.

**Comment by fabiode** [comment]
I think it's an awesome idea moving to spree-contrib, but had my thoughts with merging into core. I had to adapt it to use with 3.1-beta... Maybe moving to spree-contrib and updating the extension could be the first step before making a built-in feature.

**Comment by damianlegawiec** [comment]
@odk211 @fabiode  @priyank-gupta Thanks for the input

1. We will move/fork it to spree-contrib - it's too important to be left behind
2. Update it for 3.1 release

**Comment by fabiode** [comment]
@damianlegawiec anytime! I'm so happy spree core team is active again.

**Comment by damianlegawiec** [comment]
@romul can we talk about moving address book to spree-contrib? :)

**Comment by damianlegawiec** [comment]
@fabiode @odk211 @dhonig 

@romul moved Address Book to [spree-contrib/spree_address_book](https://github.com/spree-contrib/spree_address_book)  :tada: :tada: :tada: 

I've spent some and have fixed it for **Spree 3.0** and **Spree 3.1**

**Comment by fabiode** [comment]
@damianlegawiec great news!  :tada: nice work!

**Comment by bbonislawski** [comment]
@damianlegawiec IMHO we shouldn't add more things to core. It's nice to have this as an extension and our core is already huge. 
We should keep Spree modular and this is module that you can add if you want. It'll add unnecessary complexity for people that don't want to use it and won't be big help for people that want to use it. 
ATM spree_address_book works with every spree 3.1 version and adding it is ultra-simple. 
I agree with @nishant-cyro and @priyank-gupta that we should keep this as an extension
