### ISSUE TITLE
Cannot install using spree install --auto-accept

### ISSUE THREAD

**Issue by sanjaygoel** [spree/spree#6965]
In the Gemfile, it is creating spree version to be 3.0.5, however in rubygems, the latest available version is 3.0.4 only.
So bundle install throws an error, cannot find spree 3.0.5

**Comment by damianlegawiec** [comment]
This will be fixed later today - sorry about that :(

In the meantime just change your gemfile to:
```
gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
```
and run
```
bundle install
bundle exec rails g spree:install
bundle exec rake railties:install:migrations
```
This will the preferred way of installing future versions (spree_cmd will be deprecated).

Once again we're sorry for the inconvenience.

**Comment by sanjaygoel** [comment]
Thanks for quick reply. Another error when I run bundle exec rails g spree:install

loading ruby /home/sanjay/.rvm/gems/ruby-2.2.1/bundler/gems/spree-6b8d76caaee0/core/db/default/spree/states.rb
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xC4\x81n' for column 'name' at row 8:     INSERT INTO spree_states (`name`, `abbr`, `country_id`)
    VALUES ('Canillo', '02', 1), ('Encamp', '03', 1), ('La Massana', '04', 1), ('Ordino', '05', 1), ('Sant Julià de Lòria', '06', 1), ('Andorra la Vella', '07', 1), ('Escaldes-Engordany', '08', 1), ('\'Ajmān', 'AJ', 2), ('Abū Ȥaby [Abu Dhabi]', 'AZ', 2), ('Dubayy', 'DU', 2), ('Al Fujayrah', 'FU', 2), ('Ra’s al Khaymah', 'RK', 2), ('Ash Shāriqah', 'SH', 2), ('Umm al Qaywayn', 'UQ', 2), ('Balkh', 'BAL', 3), ('Bāmyān', 'BAM', 3), ('Bādghīs', 'BDG', 3), ('Badakhshān', 'BDS', 3), ('Baghlān', 'BGL', 3), ('Dāykundī', 'DAY', 3), ('Farāh', 'FRA', 3), ('Fāryāb', 'FYB', 3), ('Ghaznī', 'GHA', 3), ('Ghōr', 'GHO', 3), ('Helmand', 'HEL', 3), ('Herāt', 'HER', 3), ('Jowzjān', 'JOW', 3), ('Kābul', 'KAB', 3), ('Kandahār', 'KAN', 3), ('Kāpīsā', 'KAP', 3), ('Kunduz', 'KDZ', 3), ('Khōst', 'KHO', 3), ('Kunar', 'KNR', 3), ('Laghmān', 'LAG', 3), ('Lōgar', 'LOG', 3), ('Nangarhār', 'NAN', 3), ('Nīmrōz', 'NIM', 3), ('Nūristān', 'NUR', 3), ('Panjshayr', 'PAN', 3), ('Parwān', 'PAR', 3), ('Paktiyā', 'PIA', 3), ('Paktīkā', 'PKA', 3), ('Samangān', 'SAM', 3), ('Sar-e Pul', 'SAR', 3), ('Takhār', 'TAK', 3), ('Uruzgān', 'URU', 3), ('Wardak', 'WAR', 3), ('Zābul', 'ZAB', 3), ('Saint George', '03', 4), ('Saint John', '04', 4), ('Saint Mary', '05', 4), ('Saint Paul', '06', 4), ('Saint Peter', '07', 4), ('Saint Philip', '08', 4), ('Barbuda', '10', 4), ('Redonda', '11', 4), ('Berat', '01', 6), ('Durrës', '02', 6), ('Elbasan', '03', 6), ('Fier', '04', 6), ('Gjirokastër', '05', 6), ('Korçë', '06', 6), ('Kukës', '07', 6), ('Lezhë', '08', 6), ('Dibër', '09', 6), ('Shkodër', '10', 6), ('Tiranë', '11', 6), ('Vlorë', '12', 6), ('Aragacotn', 'AG', 7), ('Ararat', 'AR', 7), ('Armavir', 'AV', 7), ('Erevan', 'ER', 7), ('Gegarkunik\'', 'GR', 7), ('Kotayk\'', 'KT', 7), ('Lory', 'LO', 7), ('Sirak', 'SH', 7), ('Syunik\'', 'SU', 7), ('Tavus', 'TV', 7), ('Vayoc Jor', 'VD', 7), ('Bengo', 'BGO', 8), ('Benguela', 'BGU', 8), ('Bié', 'BIE', 8), ('Cabinda', 'CAB', 8), ('Cuando-Cubango', 'CCU', 8), ('Cunene', 'CNN', 8), ('Cuanza Norte', 'CNO', 8), ('Cuanza Sul', 'CUS', 8), ('Huambo', 'HUA', 8), ('Huíla', 'HUI', 8), ('Lunda Norte', 'LNO', 8), ('Lunda Sul', 'LSU', 8), ('Luanda', 'LUA', 8), ('Malange', 'MAL', 8), ('Moxico', 'MOX', 8), ('Namibe', 'NAM', 8), ('Uíge', 'UIG', 8), ('Zaire', 'ZAI', 8), ('Salta', 'A', 10), ('Buenos Aires', 'B', 10), ('Ciudad Autónoma de Buenos Aires', 'C', 10), ('San Luis', 'D', 10), ('Entre Rios', 'E', 10), ('Santiago del Estero', 'G', 10), ('Chaco', 'H', 10), ('San Juan', 'J', 10), ('Catamarca', 'K', 10), ('La Pampa', 'L', 10), ('Mendoza', 'M', 10), ('Misiones', 'N', 10), ('Formosa', 'P', 10), ('Neuquen', 'Q', 10), ('Rio Negro', 'R', 10), ('Santa Fe', 'S', 10), ('Tucuman', 'T', 10), ('Chubut', 'U', 10), ('Tierra del Fuego', 'V', 10), ('Corrientes', 'W', 10), ('Cordoba', 'X', 10), ('Jujuy', 'Y', 10), ('Santa Cruz', 'Z', 10), ('La Rioja', 'F', 10), ('Burgenland', '1', 12), ('Kärnten', '2', 12), ('Niederösterreich', '3', 12), ('Oberösterreich', '4', 12), ('Salzburg', '5', 12), ('Steiermark', '6', 12), ('Tirol', '7', 12), ('Vorarlberg', '8', 12), ('Wien', '9', 12), ('Australian Capital Territory', 'ACT', 13), ('New South Wales', 'NSW', 13), ('Northern Territory', 'NT', 13), ('Queensland', 'QLD', 13), ('South Australia', 'SA', 13), ('Tasmania', 'TAS', 13), ('Victoria', 'VIC', 13), ('Western Australia', 'WA', 13), ('Abşeron', 'ABS', 16), ('Ağstafa', 'AGA', 16), ('Ağcabədi', 'AGC', 16), ('Ağdam', 'AGM', 16), ('Ağdaş', 'AGS', 16), ('Ağsu', 'AGU', 16), ('Astara', 'AST', 16), ('Bakı', 'BA', 16), ('Balakən', 'BAL', 16), ('Bərdə', 'BAR', 16), ('Beyləqan', 'BEY', 16), ('Biləsuvar', 'BIL', 16), ('Cəbrayıl', 'CAB', 16), ('Cəlilabab', 'CAL', 16), ('Daşkəsən', 'DAS', 16), ('Füzuli', 'FUZ', 16), ('Gəncə', 'GA', 16), ('Gədəbəy', 'GAD', 16), ('Goranboy', 'GOR', 16), ('Göyçay', 'GOY', 16), ('Göygöl', 'GYG', 16), ('Hacıqabul', 'HAC', 16), ('İmişli', 'IMI', 16), ('İsmayıllı', 'ISM', 16), ('Kəlbəcər', 'KAL', 16), ('Kürdəmir', 'KUR', 16), ('Lənkəran', 'LA', 16), ('Laçın', 'LAC', 16), ('Lənkəran', 'LAN', 16), ('Lerik', 'LER', 16), ('Masallı', 'MAS', 16), ('Mingəçevir', 'MI', 16), ('Naftalan', 'NA', 16), ('Neftçala', 'NEF', 16), ('Naxçıvan', 'NX', 16), ('Oğuz', 'OGU', 16), ('Qəbələ', 'QAB', 16), ('Qax', 'QAX', 16), ('Qazax', 'QAZ', 16), ('Quba', 'QBA', 16), ('Qubadlı', 'QBI', 16), ('Qobustan', 'QOB', 16), ('Qusar', 'QUS', 16), ('Şəki', 'SA', 16), ('Sabirabad', 'SAB', 16), ('Şəki', 'SAK', 16), ('Salyan', 'SAL', 16), ('Saatlı', 'SAT', 16), ('Şabran', 'SBN', 16), ('Siyəzən', 'SIY', 16), ('Şəmkir', 'SKR', 16), ('Sumqayıt', 'SM', 16), ('Şamaxı', 'SMI', 16), ('Samux', 'SMX', 16), ('Şirvan', 'SR', 16), ('Şuşa', 'SUS', 16), ('Tərtər', 'TAR', 16), ('Tovuz', 'TOV', 16), ('Ucar', 'UCA', 16), ('Xankəndi', 'XA', 16), ('Xaçmaz', 'XAC', 16), ('Xocalı', 'XCI', 16), ('Xızı', 'XIZ', 16), ('Xocavənd', 'XVD', 16), ('Yardımlı', 'YAR', 16), ('Yevlax', 'YE', 16), ('Yevlax', 'YEV', 16), ('Zəngilan', 'ZAN', 16), ('Zaqatala', 'ZAQ', 16), ('Zərdab', 'ZAR', 16), ('Federacija Bosne i Hercegovine', 'BIH', 17), ('Brčko distrikt', 'BRC', 17), ('Republika Srpska', 'SRP', 17), ('Christ Church', '01', 18), ('Saint Andrew', '02', 18), ('Saint George', '03', 18), ('Saint James', '04', 18), ('Saint John', '05', 18), ('Saint Joseph', '06', 18), ('Saint Lucy', '07', 18), ('Saint Michael', '08', 18), ('Saint Peter', '09', 18), ('Saint Philip', '10', 18), ('Saint Thomas', '11', 18), ('Barisal', 'A', 19), ('Chittagong', 'B', 19), ('Dhaka', 'C', 19), ('Khulna', 'D', 19), ('Rajshahi', 'E', 19), ('Rangpur', 'F', 19), ('Sylhet', 'G', 19), ('Bruxelles-Capitale, Région de;Brussels Hoofdstedelijk Gewest', 'BRU', 20), ('Vlaams Gewest', 'VLG', 20), ('wallonne, Région', 'WAL', 20), ('Boucle du Mouhoun', '01', 21), ('Cascades', '02', 21), ('Centre', '03', 21), ('Centre-Est', '04', 21), ('Centre-Nord', '05', 21), ('Centre-Ouest', '06', 21), ('Centre-Sud', '07', 21), ('Est', '08', 21), ('Hauts-Bassins', '09', 21), ('Nord', '10', 21), ('Plateau-Central', '11', 21), ('Sahel', '12', 21), ('Sud-Ouest', '13', 21), ('Blagoevgrad', '01', 22), ('Burgas', '02', 22), ('Varna', '03', 22), ('Veliko Tarnovo', '04', 22), ('Vidin', '05', 22), ('Vratsa', '06', 22), ('Gabrovo', '07', 22), ('Dobrich', '08', 22), ('Kardzhali', '09', 22), ('Kyustendil', '10', 22), ('Lovech', '11', 22), ('Montana', '12', 22), ('Pazardzhik', '13', 22), ('Pernik', '14', 22), ('Pleven', '15', 22), ('Plovdiv', '16', 22), ('Razgrad', '17', 22), ('Ruse', '18', 22), ('Silistra', '19', 22), ('Sliven', '20', 22), ('Smolyan', '21', 22), ('Sofia-Grad', '22', 22), ('Sofia', '23', 22), ('Stara Zagora', '24', 22), ('Targovishte', '25', 22), ('Haskovo', '26', 22), ('Shumen', '27', 22), ('Yambol', '28', 22), ('Al Manāmah (Al ‘Āşimah)', '13', 23), ('Al Janūbīyah', '14', 23), ('Al Muḩarraq', '15', 23), ('Al Wusţá', '16', 23), ('Ash Shamālīyah', '17', 23), ('Bubanza', 'BB', 24), ('Bujumbura Rural', 'BL', 24), ('Bujumbura Mairie', 'BM', 24), ('Bururi', 'BR', 24), ('Cankuzo', 'CA', 24), ('Cibitoke', 'CI', 24), ('Gitega', 'GI', 24), ('Kirundo', 'KI', 24), ('Karuzi', 'KR', 24), ('Kayanza', 'KY', 24), ('Makamba', 'MA', 24), ('Muramvya', 'MU', 24), ('Mwaro', 'MW', 24), ('Ngozi', 'NG', 24), ('Rutana', 'RT', 24), ('Ruyigi', 'RY', 24), ('Atakora', 'AK', 25), ('Alibori', 'AL', 25), ('Atlantique', 'AQ', 25), ('Borgou', 'BO', 25), ('Collines', 'CO', 25), ('Donga', 'DO', 25), ('Kouffo', 'KO', 25), ('Littoral', 'LI', 25), ('Mono', 'MO', 25), ('Ouémé', 'OU', 25), ('Plateau', 'PL', 25), ('Zou', 'ZO', 25), ('Belait', 'BE', 28), ('Brunei-Muara', 'BM', 28), ('Temburong', 'TE', 28), ('Tutong', 'TU', 28), ('El Beni', 'B', 29), ('Cochabamba', 'C', 29), ('Chuquisaca', 'H', 29), ('La Paz', 'L', 29), ('Pando', 'N', 29), ('Oruro', 'O', 29), ('Potosí', 'P', 29), ('Santa Cruz', 'S', 29), ('Tarija', 'T', 29), ('Bonaire', 'BO', 30), ('Saba', 'SA', 30), ('Sint Eustatius', 'SE', 30), ('Acre', 'AC', 31), ('Alagoas', 'AL', 31), ('Amazonas', 'AM', 31), ('Amapá', 'AP', 31), ('Bahia', 'BA', 31), ('Ceará', 'CE', 31), ('Distrito Federal', 'DF', 31), ('Espírito Santo', 'ES', 31), ('Fernando de Noronha', 'FN', 31), ('Goiás', 'GO', 31), ('Maranhão', 'MA', 31), ('Minas Gerais', 'MG', 31), ('Mato Grosso do Sul', 'MS', 31), ('Mato Grosso', 'MT', 31), ('Pará', 'PA', 31), ('Paraíba', 'PB', 31), ('Pernambuco', 'PE', 31), ('Piauí', 'PI', 31), ('Paraná', 'PR', 31), ('Rio de Janeiro', 'RJ', 31), ('Rio Grande do Norte', 'RN', 31), ('Rondônia', 'RO', 31), ('Roraima', 'RR', 31), ('Rio Grande do Sul', 'RS', 31), ('Santa Catarina', 'SC', 31), ('Sergipe', 'SE', 31), ('São Paulo', 'SP', 31), ('Tocantins', 'TO', 31), ('Acklins', 'AK', 32), ('Bimini', 'BI', 32), ('Black Point', 'BP', 32), ('Berry Islands', 'BY', 32), ('Central Eleuthera', 'CE', 32), ('Cat Island', 'CI', 32), ('Crooked Island and Long Cay', 'CK', 32), ('Central Abaco', 'CO', 32), ('Central Andros', 'CS', 32), ('East Grand Bahama', 'EG', 32), ('Exuma', 'EX', 32), ('City of Freeport', 'FP', 32), ('Grand Cay', 'GC', 32), ('Harbour Island', 'HI', 32), ('Hope Town', 'HT', 32), ('Inagua', 'IN', 32), ('Long Island', 'LI', 32), ('Mangrove Cay', 'MC', 32), ('Mayaguana', 'MG', 32), ('Moore\'s Island', 'MI', 32), ('North Eleuthera', 'NE', 32), ('North Abaco', 'NO', 32), ('North Andros', 'NS', 32), ('Rum Cay', 'RC', 32), ('Ragged Island', 'RI', 32), ('South Andros', 'SA', 32), ('South Eleuthera', 'SE', 32), ('South Abaco', 'SO', 32), ('San Salvador', 'SS', 32), ('Spanish Wells', 'SW', 32), ('West Grand Bahama', 'WG', 32), ('Paro', '11', 33), ('Chhukha', '12', 33), ('Ha', '13', 33), ('Samtee', '14', 33), ('Thimphu', '15', 33), ('Tsirang', '21', 33), ('Dagana', '22', 33), ('Punakha', '23', 33), ('Wangdue Phodrang', '24', 33), ('Sarpang', '31', 33), ('Trongsa', '32', 33), ('Bumthang', '33', 33), ('Zhemgang', '34', 33), ('Trashigang', '41', 33), ('Monggar', '42', 33), ('Pemagatshel', '43', 33), ('Lhuentse', '44', 33), ('Samdrup Jongkha', '45', 33), ('Gasa', 'GA', 33), ('Trashi Yangtse', 'TY', 33), ('Central', 'CE', 35), ('Ghanzi', 'GH', 35), ('Kgalagadi', 'KG', 35), ('Kgatleng', 'KL', 35), ('Kweneng', 'KW', 35), ('North-East', 'NE', 35), ('North-West', 'NW', 35), ('South-East', 'SE', 35), ('Southern', 'SO', 35), ('Brèsckaja voblasc\'', 'BR', 36), ('Horad Minsk', 'HM', 36), ('Homel\'skaja voblasc\'', 'HO', 36), ('Hrodzenskaja voblasc\'', 'HR', 36), ('Mahilëuskaja voblasc\'', 'MA', 36), ('Minskaja voblasc\'', 'MI', 36), ('Vicebskaja voblasc\'', 'VI', 36), ('Belize', 'BZ', 37), ('Cayo', 'CY', 37), ('Corozal', 'CZL', 37), ('Orange Walk', 'OW', 37), ('Stann Creek', 'SC', 37), ('Toledo', 'TOL', 37), ('Alberta', 'AB', 38), ('British Columbia', 'BC', 38), ('Manitoba', 'MB', 38), ('New Brunswick', 'NB', 38), ('Newfoundland and Labrador', 'NL', 38), ('Nova Scotia', 'NS', 38), ('Northwest Territories', 'NT', 38), ('Nunavut', 'NU', 38), ('Ontario', 'ON', 38), ('Prince Edward Island', 'PE', 38), ('Quebec', 'QC', 38), ('Saskatchewan', 'SK', 38), ('Yukon Territory', 'YT', 38), ('Bas-Congo', 'BC', 40), ('Bandundu', 'BN', 40), ('Équateur', 'EQ', 40), ('Katanga', 'KA', 40), ('Kasai-Oriental', 'KE', 40), ('Kinshasa', 'KN', 40), ('Kasai-Occidental', 'KW', 40), ('Maniema', 'MA', 40), ('Nord-Kivu', 'NK', 40), ('Orientale', 'OR', 40), ('Sud-Kivu', 'SK', 40), ('Ouham', 'AC', 41), ('Bamingui-Bangoran', 'BB', 41), ('Bangui', 'BGF', 41), ('Basse-Kotto', 'BK', 41), ('Haute-Kotto', 'HK', 41), ('Haut-Mbomou', 'HM', 41), ('Haute-Sangha / Mambéré-Kadéï', 'HS', 41), ('Gribingui', 'KB', 41), ('Kémo-Gribingui', 'KG', 41), ('Lobaye', 'LB', 41), ('Mbomou', 'MB', 41), ('Ombella-M\'poko', 'MP', 41), ('Nana-Mambéré', 'NM', 41), ('Ouham-Pendé', 'OP', 41), ('Sangha', 'SE', 41), ('Ouaka', 'UK', 41), ('Vakaga', 'VK', 41), ('Bouenza', '11', 42), ('Pool', '12', 42), ('Sangha', '13', 42), ('Plateaux', '14', 42), ('Cuvette-Ouest', '15', 42), ('Lékoumou', '2', 42), ('Kouilou', '5', 42), ('Likouala', '7', 42), ('Cuvette', '8', 42), ('Niari', '9', 42), ('Brazzaville', 'BZV', 42), ('Aargau', 'AG', 43), ('Appenzell Innerrhoden', 'AI', 43), ('Appenzell Ausserrhoden', 'AR', 43), ('Bern', 'BE', 43), ('Basel-Landschaft', 'BL', 43), ('Basel-Stadt', 'BS', 43), ('Fribourg', 'FR', 43), ('Genève', 'GE', 43), ('Glarus', 'GL', 43), ('Graubünden', 'GR', 43), ('Jura', 'JU', 43), ('Luzern', 'LU', 43), ('Neuchâtel', 'NE', 43), ('Nidwalden', 'NW', 43), ('Obwalden', 'OW', 43), ('Sankt Gallen', 'SG', 43), ('Schaffhausen', 'SH', 43), ('Solothurn', 'SO', 43), ('Schwyz', 'SZ', 43), ('Thurgau', 'TG', 43), ('Ticino', 'TI', 43), ('Uri', 'UR', 43), ('Vaud', 'VD', 43), ('Valais', 'VS', 43), ('Zug', 'ZG', 43);

**Comment by damianlegawiec** [comment]
@sanjaygoel  are you using `encoding: utf8`  for mysql in your database.yml?

**Comment by damianlegawiec** [comment]
Spree install is fixed so I'm closing this issue - if something else popups please file another one, thanks!
