### ISSUE TITLE
Facing issue filter chain halted as :load_order_with_lock rendered or redirected

### ISSUE THREAD

**Issue by dinshawr** [spree/spree#6974]
I have included given code

    = form_for @order, :url => update_checkout_path(:payment), :html => { :id => "checkout_form_payment" } do |form|    
    	- @order.available_payment_methods.each do |method|
            %li.list-group-item{"id"=> "#{method.method_type}"}
              %label
                = radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first
                = Spree.t(method.name, :scope => :payment_methods, :default => method.name)
        %li.list-group-item.codMobile#cashondelivery1
    	    %label
    	      %input#order_payments_attributes__payment_method_id_216{:name => "order[payments_attributes][][payment_method_id]", :type => "radio", :value => "216", :checked => 'checked'}
    	      Cash On Delivery   
    
    	= submit_tag Spree.t(:order_now), :class => 'order-now btn btn-danger'   

when I click on order now button it gives me following error

        Started PATCH "/checkout/update/payment" for 127.0.0.1 at 2016-01-29 10:42:45 +0100 Processing by Spree::CheckoutController#update as HTML  Parameters: {"utf8"=>"✓", "authenticity_token"=>"FwxEDP2e/sMJ1EReuIw/yIH4X0pYuVXAcmX8T6RLqho=", "order"=>{"payments_attributes"=>[{"payment_method_id"=>"216"}], "cod_pay"=>"true"}, "cardHolder"=>"Dinshaw Raje", "cardNumber"=>"[FILTERED]", "credit"=>"2016", "cardCode"=>"", "commit"=>"Order Now", "payment_source"=>{"16"=>{"encrypted_data"=>"adyenjs_0_1_2$RMfk4WICZqzAtK4SR54Yf843tyKctKZHrZOElewJL+CMTkJI3Sn6BiNcVXtGJCE5ftrw2EWkngoKn40GiEn050wkhDHhSO+R5n0zoxhdQxP9KSHGgu/Qo3a5+gSA/SWWD9qAKyBSEgLbH6X2kHV0STp5DrnLR05/jrj+N12KtoAeTaJSQPEfGNEz5bnldl2ctUB6NI9KA0P90WFTilxjUvDgsx6c7K91iHf1ozKss7bDzuXeQHp+WGxHs0z+/+VPDCjxe1R8N5t6MldyHTfkMsd6D3DR6BjyQ1LSbRpM4n7gmXYYYLw1+V6kkZhxA00akDDdRnBdtXKLmFTVCEKybg==$9JflZhG1vjFCjRdWuJ1MMWoApU6Frn5EH3KB+mXaIC0ek2y2Bngd7oSMsn8BWW6WvClVIgxRVCXJGdIJmeFd5HyvQ3X7AVL/m88K7Y7XiXTmWld/xkdO2H7FOnZsRLEUWW/B0cDZEB2Hod4RiouuJNTi70dOrV90BwrpSlN8HbNIA8iqBwp1LVdzle7IqjfAmXeeowGZgxYu"}}, "state"=>"payment"}  
     Spree::Country Load (1.1ms)  SELECT  "spree_countries".* FROM "spree_countries"  WHERE "spree_countries"."name" = 'N/A' LIMIT 1   Spree::Order Load (3.2ms)  SELECT  "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = 'AED' AND "spree_orders"."guest_token" = 'D2dIKPb9llIco2itPqTl6g' AND "spree_orders"."user_id" IS NULL LIMIT 1 FOR UPDATE   Spree::Adjustment Load (1.4ms)  SELECT "spree_adjustments".* FROM "spree_adjustments"  WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (6102)  ORDER BY spree_adjustments.created_at ASC    (0.9ms)  BEGIN   Spree::Order Load (1.4ms)  SELECT  "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."id" = $1 LIMIT 1 FOR UPDATE  [["id", 6102]]    (1.4ms)  COMMIT 
    
    Redirected to http://localhost:3000/checkout/address Filter chain halted as :load_order_with_lock rendered or redirected Completed 302 Found in 18ms (ActiveRecord: 9.3ms)
        
        Started GET "/checkout/address" for 127.0.0.1 at 2016-01-29 10:42:45
        +0100 Processing by Spree::CheckoutController#edit as HTML   Parameters: {"state"=>"address"}   Spree::Country Load (1.3ms)  SELECT "spree_countries".* FROM "spree_countries"  WHERE "spree_countries"."name" = 'N/A' LIMIT 1   Spree::Order Load (2.6ms)  SELECT  "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = 'AED' AND "spree_orders"."guest_token" = 'D2dIKPb9llIco2itPqTl6g' AND "spree_orders"."user_id" IS NULL LIMIT 1 FOR UPDATE   Spree::Adjustment Load (1.7ms)  SELECT "spree_adjustments".* FROM "spree_adjustments"  WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (6102)  ORDER BY spree_adjustments.created_at ASC    (1.0ms)  BEGIN

Please guide where I am wrong. Thank in advance

**Comment by priyank-gupta** [comment]
This might be related to https://github.com/spree/spree/issues/6766

**Comment by nishant-cyro** [comment]
@dinshawr - I have tries to replicate this issue. And the only scenario I am able to replicate this one is when we are doing guest checkout and clears off browser cookies or particularly guest_checkout cookie of the browser for this domain.

Let me know if this is your case, or it will be good help if you can explain your scenario a little bit more.

**Comment by dinshawr** [comment]
no actually this isuue is occuring in my private window also I followed the same question of stackoverflow
`http://stackoverflow.com/questions/35127177/facing-filter-chain-halted-as-load-order-with-lock-rendered-or-redirected-issue/35170640?noredirect=1#comment58070539_35170640`

**Comment by Mafi88** [comment]
@dinshawr Also can't replicate... Could you please provide  ```current_order.inspect``` from before and after clicking this button?
