### ISSUE TITLE
Creating promotion code without linking to order but to users

### ISSUE THREAD

**Issue by kavitakanojiya** [spree/spree#6977]
I have a requirement to give some credit to users when he invite users from his friend's circle.
Basically, I am planning to create promotional codes. Whenever, users invites their friends in bulk, I should be able to create promotional codes on the fly and link them to users. 

Hence, I am planning to add another table wherein these codes could be linked to users. Whenever user want to check how many coupons he owns, this can be easily done. while checking out, only one code could be used.

Let me know if I am doing this right way!

**Comment by nishant-cyro** [comment]
@kavitakanojiya - Looks good to me!

**Comment by priyank-gupta** [comment]
@kavitakanojiya https://github.com/kinduff/spree_reffiliate might come in handy (for spree 2.3). You may have to upgrade this or get an idea.
Hope this helps. :)

**Comment by kavitakanojiya** [comment]
Hey @priyank-gupta, thanks I will check on this. Helpful.

**Comment by priyank-gupta** [comment]
@kavitakanojiya Please do the honour to close this issue if the info is helpful. Thanks :)

**Comment by kavitakanojiya** [comment]
Sure :)
