### ISSUE TITLE
Can not add some custom Spree API due to redirection loop

### ISSUE THREAD

**Issue by odk211** [spree/spree#7006]
I can not add custom route under /api , because of
https://github.com/spree/spree/blob/master/api/config/routes.rb#L118

It cause redirection loop when I add custom action to Spree::API module.
Is there any chance to remove these redirect line?

**Comment by tanmay3011** [comment]
@odk211  Can you please share your routes.rb?  So that we can get to the root of the issue. 

I tried adding utilities to api and it works fine for me

`routes.rb`
```Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
    namespace :api do
      resources :utilities, only: [:index, :show]
    end
  end
end```

and got these routes
```
  api_utilities GET     /api/utilities(.:format)         spree/api/utilities#index
     api_utility GET     /api/utilities/:id(.:format)    spree/api/utilities#show
```

**Comment by damianlegawiec** [comment]
@tanmay3011 in 3.1 there is /v1/api - see https://github.com/spree/spree/blob/master/guides/content/release_notes/3_1_0.md

**Comment by tanmay3011** [comment]
@damianlegawiec Earlier I did tested against 3.0.5.

Just a correction it should be /api/v1 (Also given in the reference). 
Re-tried against master. And still works for me.

**routes.rb**

```
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
    namespace :api, defaults: { format: 'json' } do
      namespace :v1 do
        resources :products do
          get :online, on: :collection
        end
      end
    end
  end
end
```

and got this route
```
online_api_v1_products GET   /api/v1/products/online(.:format)                                             spree/api/v1/products#online {:format=>"json"}
```

**Comment by odk211** [comment]
@tanmay3011 @damianlegawiec 

I use append_routes to customize api.
I think append_routes is official way to append custom route.

```
Spree::Core::Engine.append_routes do
   ....
end
```

Sorry I can not try it now, but I think it cause some redirect loop...

**Comment by odk211** [comment]
I checked. it cause redirection loop.

**Comment by tanmay3011** [comment]
@odk211 Thanks! For those steps. Now I can replicate this.

You can use add_routes helper instead of append_routes for the time being.

**Comment by odk211** [comment]
@tanmay3011 Thank you for your Feedback!
add_routes works for me!
