### ISSUE TITLE
Where can I find Spree Extension Registry official page?

### ISSUE THREAD

**Issue by imshashi** [spree/spree#7023]
Hello,

I was going through official Spree extensions tutorial here https://guides.spreecommerce.com/developer/extensions_tutorial.html

There is a link mentioned "Spree Extension Registry" which should redirect to https://spreecommerce.com/extensions but when I tried to click that link it shows 404 error. 

Can somebody let me know if that page is referenced to some new location/link? 

Thanks

**Comment by priyank-gupta** [comment]
@imshashi the old extension registry wasn’t updated for a long time and is finally closed. Right now we’re focusing on spree + spree-contrib extensions but extension directory is definitely something we will think about after releasing 3.1.
Is there anything particular you are looking for ?

**Comment by imshashi** [comment]
Thanks @priyank-gupta for the quick response. I was going through the Spree developer tutorials and found that broken link. I was just curious to look into available spree extensions on that page. 

Thanks again!!
