### ISSUE TITLE
unable to setup Spree.user_class

### ISSUE THREAD

**Issue by kubido** [spree/spree#7046]
in my initializer file:
`Spree.user_class = "User"`
but when access the store it got error undefined method `last_incomplete_spree_order`, it's because the `last_incomplete_spree_order` method is not existed in `User` model.

then I checked the `Spree.user_class` is `Spree:User`

I'm curious why the class override didn't work?

**Comment by priyank-gupta** [comment]
@kubido Are you using `spree_auth_devise` extension ?

**Comment by priyank-gupta** [comment]
@kubido This is probably related to https://github.com/spree/spree/issues/5194.
