### ISSUE TITLE
Spree installation not going through

### ISSUE THREAD

**Issue by abugida** [spree/spree#7054]
Hello,

I've been starting to get into Rails and Spree for the last two weeks, and much to my embarassment I still don't have a running default installation of Spree. I hope someone can help!

As you can see on the screenshot below, through trial and error I've managed to install an incomplete storefront, and I'm not really sure what to try next.

Homepage is loading, but no products listed, Admin cannot login. Customers can sign up and log out and and in again. Search and cart pages respond, but all empty of course.

I'm running a vanilla Linode, with Debian 8, rbenv, Apache, Passenger. I've also installed MySQL/PHP with Pr***ashop, which is working fine (I hope that doesn't matter).

apache's error.log has no entries.
production.log shows 200 OK for every request

Any suggestion would be welcome! Some gists:

[What I did to reach that point:](https://gist.github.com/abugida/0dc714de1e1eb8c71d4d)

[My Gemfile and Gemfile.lock](https://gist.github.com/abugida/addcf28c6e2e50f87fc5)

![bildschirmfoto 2016-02-12 um 23 29 56](https://cloud.githubusercontent.com/assets/16980470/13022295/9efdc18a-d1e0-11e5-961f-fdedcbefb8e9.png)

**Comment by crazyyi** [comment]
I got this error which prevents me from processing: (This happens when I run ` bundle exec rake db:seed` or `rails g spree:auth:install`. )

```
loading ruby /usr/local/rvm/gems/ruby-2.3.0/gems/spree_core-3.0.5/db/default/spree/countries.rb
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: near ",": syntax error:   INSERT INTO spree_countries ("name", "iso3", "iso", "iso_name", "numcode", "states_required")
  VALUES ('Andorra', 'AND', 'AD', 'ANDORRA', '020', 't'), ...
```

Some statements are incorrect for SQLite3 so it didn't go through. Hope there will be a quick fix soon.
I am using SQLIite version 3.8.7.3 and my sqlite3 gem is 1.3.11.

**Comment by aishmita-aggarwal** [comment]
@abugida Have you seeded and loaded the sample data?

**Comment by aishmita-aggarwal** [comment]
@crazyyi I am unable to replicate your issue. Please provide replication steps. Thank you.
