### ISSUE TITLE
Custom User model, `payment_sources` method override

### ISSUE THREAD

**Issue by sushil10018** [spree/spree#7073]
**Scenario**: I'm implementing Spree as an engine on an existing rails app with User model. I could successfully setup Spree and have it running with a mounted route as well.

**Problem**: Spree includes this method `payment_sources` to the `User` model but I already have a model `PaymentSource` with `belongs_to` association with `User`. 

So, now when I call `User.first.payment_sources` it doesn't return `PaymentSource` rather `Spree::CreditCard` is returned which is included by Spree itself.

One solution I could find is to override the method of Spree such that it accepts parameter if it's of spree or from our app only.

``` ruby
# app/models/concerns/spree/user_payment_source.rb 

def payment_sources(spree = true)
  if spree
    credit_cards.with_payment_profile
  else
    super
  end
end
```

This does seem to work but forces us to replace all the existing method in the app with params provided. 

**My concern here**: Is there any better way to namespace the methods such that spree gets the namespaced methods and use them whereas our app can still work on pre-existing methods not being overridden by Spree Methods.

Please suggest.

**Comment by Mafi88** [comment]
@sushil10018 I don't think there is a good way to rename spree methods. Maybe it would be better to change original relation name?

**Comment by sushil10018** [comment]
@Mafi88 wouldn't it be better if we could namespace the spree methods when using an existing `User` model. How could we achieve this with spree as well as existing app functioning as expected?

**Comment by bbonislawski** [comment]
It's outdated probably so I'm closing it now. If you have questions, please ask them at our slack
