### ISSUE TITLE
Broken links in the tutorial

### ISSUE THREAD

**Issue by yeonhoyoon** [spree/spree#7079]
In the [Extensions Tutorial](https://guides.spreecommerce.com/developer/extensions_tutorial.html#finding-useful-spree-extensions-in-the-extension-registry), the links to 'Spree Extensions Registry' and 'Spree Community' are broken.

**Comment by yeonhoyoon** [comment]
The following line also appears when running `spree extension` command from command line:
`Consider listing your extension in the official extension registry http://spreecommerce.com/extensions`

https://github.com/spree/spree/blob/45cec5215763da26e0089415f4c49afffd683bd9/cmd/lib/spree_cmd/extension.rb#L41

**Comment by tanmay3011** [comment]
@yeonhoyoon Currently 'Spree Extensions Registry' is down. This will be fixed by core team.

**Comment by priyank-gupta** [comment]
@yeonhoyoon the old extension registry wasn’t updated for a long time and is finally closed. Right now we’re focusing on spree + spree-contrib extensions but extension directory is definitely something we will think about after releasing 3.1.
Is there anything particular you are looking for ?

**Comment by yeonhoyoon** [comment]
@priyank-gupta No, I was just going through the tutorials and noticed that.

**Comment by priyank-gupta** [comment]
@yeonhoyoon You can also refer [Spree community](http://slack.spreecommerce.com) for support and general discussions.
