### ISSUE TITLE
spree installed but getting 'spree command not found` error

### ISSUE THREAD

**Issue by iamrahulroy** [spree/spree#7080]
I installed spree by adding `gem 'spree'` to rails project and running `bundle install`.

Then I tried running `spree install --auto-accept` as instructed in getting started tutorial but, it didn't work. I got `zsh: command not found: spree` even though spree was already installed.

I ran `bundle list | grep 'spree'` and got the list of different components of spree but, with version `0.40.0`. Here's the detailed output:

```
  * spree (0.40.0)
  * spree_api (0.40.0)
  * spree_auth (0.40.0)
  * spree_core (0.40.0)
  * spree_dash (0.40.0)
  * spree_promo (0.40.0)
  * spree_sample (0.40.0)
```

Is this expected or is it some kind of bug? Judging from README, it should be 3.0. Am I missing something?

EDIT: I was on ruby 2.3, so I switched to ruby 2.2 and it worked. Maybe, Spree's not compatible with Ruby 2.3, yet?

**Comment by damianlegawiec** [comment]
@iamrahulroy to use the `spree` command you have to install spree gem globally via `gem install spree`

**Comment by iamrahulroy** [comment]
@damianlegawiec Thanks for quick response. I was following [official getting started guide](https://guides.spreecommerce.com/developer/getting_started_tutorial.html) and had no idea about installing spree globally. Don't you think it should be highlighted in docs?

**Comment by jitendra** [comment]
@iamrahulroy did you follow 'Installing Spree' step in the guide?
i.e. gem install spree_cmd

**Comment by iamrahulroy** [comment]
@jitendra Not sure! I may have skipped it in favor of bundle install. I thought it wouldn't make a difference, but it did. I'll go ahead and close the issue. Thanks!

**Comment by JenniferVanderputten** [comment]
I did the "gem install spree_cmd" as per the getting started guide, but I also saw this error.  Then I ran "gem install spree" and received the same error.  The problem is that both spree_cmd and spree were installed to the bin/ directory where I ran those commands.  This is fine, but the installation did not modify $PATH to suit.  I modified $PATH and it worked.
