### ISSUE TITLE
Adjustment Amount should be using LocalizedNumber?

### ISSUE THREAD

**Issue by fabiode** [spree/spree#7086]
I was asking my self if **Spree::Adjustment** if _amount_ setter (or writer) method should be using **Spree::LocalizedNumber** _parse_ method, just as **Spree::Price**.

Since it's dealing with currency, for me it makes sense.

What you guys think about it?

**Comment by nishant-cyro** [comment]
@fabiode - Yeah, it looks good to me, we should have this change in Spree::Adjustment :+1: 

@priyank-gupta @Mafi88 @damianlegawiec - ?

**Comment by priyank-gupta** [comment]
Seems reasonable to me. :+1: 
@fabiode We will appreciate if you can do a PR for this.

**Comment by fabiode** [comment]
@priyank-gupta Sure! I will do it!
