### ISSUE TITLE
Instance method "invalid?" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true

### ISSUE THREAD

**Issue by isantoshsingh** [spree/spree#7096]
I am new to rails and spree and not sure where to post.
When I am starting rails server with spree version `3.0.6.1`, it shows below message-

`Instance method "invalid?" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true`

**Comment by deepakm-webonise** [comment]
@isantoshsingh you found any solution for this?

**Comment by isantoshsingh** [comment]
Nope.
