### ISSUE TITLE
Ubuntu deployment guide uses outdated capistrano

### ISSUE THREAD

**Issue by MarkMT** [spree/spree#7119]
The guide for deploying spree to Ubuntu:

[https://github.com/spree/spree/blob/master/guides/content/developer/deployment/manual-ubuntu.md
](https://github.com/spree/spree/blob/master/guides/content/developer/deployment/manual-ubuntu.md
)
includes instructions for setting up capistrano that looks to me like it uses capistrano v2.x. The latest v3.x versions break earlier deploy.rb definitions.

Ultimately it would be good to update the guide with instructions for 3.x, but in the meantime I suggest explicitly specifying the latest 2.x version in the instructions for installing the gem. Also, the instructions currently recommend using 'gem install', which I'm sure is fine, though I think adding the gem to the development group in the Gemfile is probably a more common approach.

**Comment by damianlegawiec** [comment]
@MarkMT feel free to do a PR :)

**Comment by priyank-gupta** [comment]
Thanks @MarkMT
