### ISSUE TITLE
Duplicate error messages then update Product on Staging/Production env

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree#7143]
I have added a new field (X) to `spree_products` table and then add validate for that X field in `product_decorator.rb`. On the update product page, I add a new input for that X field. When I leave that field empty and submit, it shows the error as followings:

2 errors prohibited this record from being saved:
- <X> can't be blank
- <X> can't be blank

This only happens on staging and production. On Staging, I added the invoke callbacks: `update.before`, `update.fails` and see that the function `update` ran more than one time when I submit.

I'm using Spree 3.0 and Postgresql, Ruby version 2.2.2, Rails version 4.2.4

Please suggest me how to fix above error.

Note: This problem happened on Staging/Production env on Server. not local

Thanks.

**Comment by vinayvinsol** [comment]
@ducnguyenhuy can you tell me exact versions in your `Gemfile.lock` for spree, rails , ruby and
Also how you have shown the field 'X' in html file . 

Thanks.

**Comment by ducnguyenhuy** [comment]
@vinayvinsol: Here you go:
spree (3.0.4)
rails (~> 4.2.2)

I don't find the ruby version in `Gemfile.lock` but command line `ruby -v` showed me `2.2.2`.

I used Deface (https://guides.spreecommerce.com/developer/deface_overrides_tutorial.html) to show the field 'X'.

Let me know if you have more questions.

Thanks.

**Comment by vinayvinsol** [comment]
@ducnguyenhuy  if you can post code written in `deface override` that would be much helpful :smile: 

Thanks.

**Comment by ducnguyenhuy** [comment]
@vinayvinsol: See at below pls.

`Deface::Override.new(
  :virtual_path => 'spree/admin/products/_form',
  :name => 'add_X_to_product_edit',
  :insert_after => "[data-hook='admin_product_form_slug']",
  :text => '
    <div>
      <%= f.field_container :X, class: ["form-group"] do %>
        <%= f.label :X%>
        <%= f.text_field :X %>
        <%= f.error_message_on :X %>
      <% end %>
    </div>
  '
)`

Do you think that's deface issue?

Thanks.

**Comment by vinayvinsol** [comment]
@ducnguyenhuy I am getting error only 1 times by running your deface code and your gemfile versions .
Can you post product_decorator code also. 

Thanks.

**Comment by ducnguyenhuy** [comment]
Sorry, I forgot to mention that it happened on Staging and Production, not local. That meant it works on my Laptop but when I deploy my code to Staging (on server) and Production (on server) I got that error.

**Comment by vinayvinsol** [comment]
@ducnguyenhuy I ran it on production environment by specifying RAILS_ENV=production on rails server. And still i got error only one times.
Can you please post here your decorator code.

Thanks.

**Comment by ducnguyenhuy** [comment]
@vinayvinsol Thanks for trying.  Yes, it worked on local (Dev, Staging and Production environment) but was not on server. I don't have any idea why.

Could you please try to deploy your code to any server and take a look?

Thanks,
Duc.

**Comment by tonyvince** [comment]
@ducnguyenhuy did solve this issue? I am having the same problem and could not find a workaround

**Comment by ducnguyenhuy** [comment]
@tonyvince To simple fix, I used the solution here https://stackoverflow.com/a/4207916 because it took time to debug on server.

Hope it helps you.
