### ISSUE TITLE
Can't change sidebar taxonomies

### ISSUE THREAD

**Issue by dwash93** [spree/spree#7145]
I want to change "Shop by (Taxonomy)" to just "(Taxonomy)". I've been searching through the source files for days. I don't really understand how it is coded.

**Comment by tanmay3011** [comment]
@dwash93 Please look into file `core/config/locales/en.yml` you will find the locale set here `shop_by_taxonomy: Shop by %{taxonomy}`.

This is being used in 
`frontend/app/views/spree/shared/_taxonomies.html.erb`
`<%= Spree.t(:shop_by_taxonomy, :taxonomy => taxonomy.name) %>`

**Comment by dwash93** [comment]
Thanks so much. One last question. When I copy the en.yml text to my project and change `shop_by_taxonomy: Shop by %{taxonomy}` to `shop_by_taxonomy: %{taxonomy}`, I get an error.
![taxonomyerror](https://cloud.githubusercontent.com/assets/7655248/13368512/b26822ee-dcb0-11e5-8303-dc2a7df1f69e.PNG)

**Comment by Mafi88** [comment]
@dwash93 It probably needs to be ```shop_by_taxonomy: "%{taxonomy}"``` in this case. If not, could you paste an actual error from server logs?

**Comment by tanmay3011** [comment]
@dwash93  Any update? Is your issue fixed?
