### ISSUE TITLE
UserApiAuthentication should be moved to spree_api

### ISSUE THREAD

**Issue by tanmay3011** [spree/spree#7150]
`UserApiAuthentication` methods should be moved from `spree_core gem` to `spree_api gem` since `spree_core` doesn't have any migration related to `spree_api_key`. Migrations related to `spree_api_key` are present in `spree_api`

So `spree_core` shouldn't have methods related to `spree_api_key`.

@priyank-gupta, @damianlegawiec, @Mafi88 , @nishant-cyro, @jitendra   Any thoughts?

**Comment by Mafi88** [comment]
I think it is a good point in general, but isn't the ```spree_api_key``` also needed in ```spree_backend```? It might actually be better to move the ```spree_api_key``` migration to ```spree_core```.

What are your thoughts @priyank-gupta @damianlegawiec @nishant-cyro @jitendra ?

**Comment by tanmay3011** [comment]
@Mafi88 `spree_backend`  Gemfile: https://github.com/spree/spree/blob/master/backend/Gemfile#L4 and spree_backend.gemspec: https://github.com/spree/spree/blob/master/backend/spree_backend.gemspec#L21

Since spree_backend already uses spree_api gem so API authentication won't be a problem in backend

**Comment by Mafi88** [comment]
@tanmay3011 Right. Yes, I think it can be moved, but lets wait for other opinions.

**Comment by priyank-gupta** [comment]
@tanmay3011 This seems right to me.

**Comment by bbonislawski** [comment]
It's already done on master. https://github.com/spree/spree/commit/287c97b08276132878e55a6640a63a2abcf5eda1#diff-03eba92d54cc437b282ef2e562b78b80
