### ISSUE TITLE
New Centralized Public Roadmap

### ISSUE THREAD

**Issue by sahal2080** [spree/spree#7155]
> ## Goals 
...
7\. Stimulate the community around Spree for more active participating in Spree development
  - feature requests from community (polls, discussions)
  - quickly review all incoming pull requests (leave no commit behind.. if it's acceptable)
  - work with the community on future roadmaps

Couldn't be written more beautifully. In that spirit I suggest having a public place for the project roadmap rather than scattered announcements/issues. There used to be a Trello board for Spree but it's there no more. Something like that would allow the satisfaction of most of the goals mentioned above. 

I hope I don't get the [solidus treatment](https://github.com/solidusio/solidus/issues/777#issuecomment-180072680) from the new Spree team. Either way, long live FOSS!

**Comment by tanmay3011** [comment]
@sahal2080 There is a Trello board for Spree https://trello.com/b/ML4e1KN1/spree-commerce.

**Comment by priyank-gupta** [comment]
@sahal2080 We understand your concerns and acted on these even before starting on Spree. You can find Spree roadmap [here](https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016). As @tanmay3011 mentioned we also have a [Trello board](https://trello.com/b/ML4e1KN1/spree-commerce) and [Slack Channel](http://slack.spreecommerce.com). Also read Spree [announcement](https://github.com/spree/spree#new-spree-commerce-roadmap-announcement) to know more.

**Comment by sahal2080** [comment]
First time I'm seeing this board (don't think it's anywhere on the GitHub repo/wiki). It should be mentioned in the wiki page for sure.

Taking a look at it though, it looks like you guys are using it more for project management than as a roadmap. I truly suggest you take a look at [ZenHub](https://www.zenhub.io/) as it does this and more within GitHub and it's free for open source!

Imho, having another, _open_ Spree board on trello _with voting and commenting enabled_, and that's dedicated to major features/issues where you guys want to get the community input would be the way to go.

**Comment by damianlegawiec** [comment]
@sahal2080 that's a really fine idea :+1:

**Comment by damianlegawiec** [comment]
@sahal2080 done :100: 

https://trello.com/b/ta4WU3AX/spree-roadmap
