### ISSUE TITLE
Precompiled views present and Deface is enabled, this can result in overrides being applied twice

### ISSUE THREAD

**Issue by shivabhusal** [spree/spree#7181]
Hey guys, please help
Why I am seeing `Login` button twice??  
![image](https://cloud.githubusercontent.com/assets/8004593/13589598/18d1db8a-e501-11e5-9409-890ac4a7a5ea.png)
![image](https://cloud.githubusercontent.com/assets/8004593/13589608/3699c98e-e501-11e5-890f-b854915f7b21.png)

also there is a warning shown.
```
=> Booting WEBrick
=> Rails 4.2.5.1 application starting in development on http://localhost:3001
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[WARNING] Precompiled views present and Deface is enabled, this can result in overrides being applied twice.
[2016-03-08 07:36:01] INFO  WEBrick 1.3.1
[2016-03-08 07:36:01] INFO  ruby 2.2.1 (2015-02-26) [x86_64-linux]
[2016-03-08 07:36:01] INFO  WEBrick::HTTPServer#start: pid=31697 port=3001
```

Is there any way to get rid of this.. Any link / blog post or something??

**Comment by shivabhusal** [comment]
:ok: I got the answer
```bash
$ rake deface:clean                                   # Removes all precompiled override templates
```
But I don't know if there is any complications associated with this in production environment. For now it works.

**Comment by damianlegawiec** [comment]
@shivabhusal what version of Spree are you using ? Stable or Beta (master) ?

**Comment by priyank-gupta** [comment]
@shivabhusal You may find this, https://github.com/spree/deface#production--precompiling, useful.

**Comment by shivabhusal** [comment]
@damianlegawiec  I am using spree from RubyGems.org `gem 'spree', '3.0.5'`
```
spree_auth_devise (3.0.0)
spree (3.0.5)
rails (4.2.5.1)
```
@priyank-gupta thanks for the link, it is very much helpful. :+1:
