### ISSUE TITLE
SKU not editable for after cloning product with variants 

### ISSUE THREAD

**Issue by SixDenier** [spree/spree#7229]
Hi,

It seems that the SKU attribute is no more editable after cloning a product with variants. Even if it is not used for our logistic, it's helpful for the marketing.
Thanks
![capture](https://cloud.githubusercontent.com/assets/17931909/13884637/232a2f34-ed2f-11e5-8c26-53c8d58a34e0.PNG)

![skunoteditableafterduplicate](https://cloud.githubusercontent.com/assets/17931909/13884605/fa378cd4-ed2e-11e5-9da5-ec11109649bc.PNG)

**Comment by nishant-cyro** [comment]
I am able to replicate this issue. @SixDenier - can you create a PR to fix this one?

**Comment by SixDenier** [comment]
Hi  @nishant-cyro 
As you can see, it was my first post, and I am not used to create PR. I have tried but i don't understand how to fill the fields. Sorry for that

**Comment by nishant-cyro** [comment]
@SixDenier - Created a PR to Fix this issue #7232.

**Comment by SixDenier** [comment]
@nishant-cyro Thank you

**Comment by Mafi88** [comment]
@SixDenier 
As @priyank-gupta said ```SKU represents a physical entity which represents product (master variant) when no variant and represents variants otherwise.```

It is not editable not only for cloned products, but also for the original one (as there is no more physical entity of the product itself - now it is just a collection of variants).

I'm not sure what you meant by 'marketing' value, but you can edit cloned product variant SKU's.
You can also edit name of cloned product and it's slug (so all data displayed for users).

**Comment by SixDenier** [comment]
@Mafi88 
Ok, I understand your point and @priyank-gupta's one . 
The marketing team use the master product SKU's value as a shortcut (when they talk) to describe all the variants linked to it (even if it doesn't represent any physical entity) . It's very helpful when you manage hundreds of products with variants.
Nevermind, if you think it's better not to edit master product's SKU value on a cloned product, I'll explain them the reason.
The text "copy of" on a SKU value is a bit "weird" in a backend, maybe, it's better to nullify the value. 

I am wondering, if there were a csv file import to create products with variants, how will the link between product masters and its variants will be managed if the product master's SKU value is empty ?
Thanks

**Comment by rohitnick** [comment]
@SixDenier : If I understand your point correctly. Marketing team can use product's slug as identifier to describe all linked variants.

As for the scenario for importing csv file, I am currently using "spree-import-products" gem which imports csv file to create products with variants and it links between them using the same slug and different SKU values for product and variants.

**Comment by isindexer** [comment]
@rohitnick ok that's a good point. I'll check how we will manage the product's slug identifier.
What about the text "copy of" in the SKU value of the cloned master product ?

**Comment by SixDenier** [comment]
@rohitnick ok that's a good point. I'll check how we will manage the product's slug identifier.
What about the text "copy of" in the SKU value of the cloned master product ? Nullify the value or just hide it ?

**Comment by rohitnick** [comment]
@SixDenier : Even I haven't figured out that bit yet. But I feel either nullifying or hiding it should be fine.
