### ISSUE TITLE
Promotions admin screen doesn't match documentation

### ISSUE THREAD

**Issue by kimadactyl** [spree/spree#7236]
Spree Promotions (3.0.5) were having no effect. I updated to Spree 3.0.8, and realised that I have a different fieldset to the ones in the documentation. I have not knowingly made any changes to the admin logic.

The [documentation here](http://guides.spreecommerce.com/user/promotions.html) has an "event name" field, which is missing on my admin screen. In it's place is a "path" field that doesn't seem to do anything.

![screenshot from 2016-03-22 18-56-53](https://cloud.githubusercontent.com/assets/511734/13964046/db6fe27c-f05f-11e5-8222-bcb28a2f9150.png)

Not sure if this is a documentation problem or something else?

**Comment by tanmay3011** [comment]
@kimadactyl Documentation is for Spree 2.4 and it needs to be updated for the changes in updated versions.

**Comment by kimadactyl** [comment]
Great ok! Thanks a lot, will close this ticket. Maybe going forward docs should have "last updated with version number" stuff in. Cheers for letting me know it's not me!
