### ISSUE TITLE
Spree::StockItem#count_on_hand not updating/being used

### ISSUE THREAD

**Issue by ayb** [spree/spree#7240]
Spree::StockMovement adjusts Spree::StockItem#count_on_hand

But Spree::Variant#stock_items_count doesn't seem to be doing anything.

The guide says "Count On Hand is no longer an attribute on variants. It has been moved to stock items, as those are now used for inventory management."

However Spree::Variant#stock_items_count is a field in the DB schema.

I'm happy to do a PR to resolve this if needed but not sure which approach to take.
- Should this field be removed?
- Or should the guide be updated + a PR be done so that Spree::Variant#stock_items_count is updated when Spree::StockItem#count_on_hand changes?

**Comment by damianlegawiec** [comment]
@ayb I think `stock_items_count` column should be removed

What do you think @priyank-gupta @Mafi88 ?

**Comment by Mafi88** [comment]
I agree, it's not needed anymore.

**Comment by ayb** [comment]
To follow up - I just discovered that this was removed from Solidus by @jhawthorn last year

Here is the relevant commit:

https://github.com/solidusio/solidus/commit/3acea32c2ac0a6caf82c76eed78153a09f15152c#diff-e1e482f5445beaac0a94638b870a8543

**Comment by damianlegawiec** [comment]
@ayb nice - can you cherry-pick those? Of course, you have to change the migration date to current so it will be run in proper order

**Comment by mauazua** [comment]
I believe this issue was resolved by this PR #7340
