### ISSUE TITLE
helper decorators not loaded in development

### ISSUE THREAD

**Issue by blset** [spree/spree#7241]
hello 

helper decorators for example app/helpers/spree/frontend_helper_decorator.rb are not loaded in dev mode, but do work in production

any idea how to make them work in development ?

**Comment by priyank-gupta** [comment]
@blset This is working for me. Please share your `environments/development.rb`, spree version and `frontend_helper_decorator.rb`.

**Comment by blset** [comment]
It’s working for me too, the problem was a duplication of the physical file containing the helper class, one located in app/helper/spree, the good one, the other in app/helper that was in the way

it seems that  the helper is loaded regardless of its location in the app/helper path, it’s loaded even if the class name does not match the file position in the hierarchy, provided it’s in app/helpers
