### ISSUE TITLE
git fsck warnings

### ISSUE THREAD

**Issue by pjar** [spree/spree#7242]
This repo has failed git fsck. I'm not able to push to create a fork

spree# git fsck
Checking object directories: 100% (256/256), done.
warning in tree 816b15c1be8993c832ca25cbe3fddc2595836698: contains zero-padded file modes
warning in tree e28ae52f361836df3a4bea3ed3a2d98254471f60: contains zero-padded file modes
warning in tree d7c8d1989db7d967bcb8f7c671b399539f30c7e1: contains zero-padded file modes
warning in tree 0ddeb2cd4fc7eb368d97eebb31efea671b30347b: contains zero-padded file modes
Checking objects: 100% (226865/226865), done.

**Comment by bbonislawski** [comment]
These are just warnings and AFAIK this cannot be fixed without rewriting commits SHA which we definitely don't want to do.
