### ISSUE TITLE
/admin/products/:id/clone should not be GET

### ISSUE THREAD

**Issue by crypticsymbols** [spree/spree#7247]
I may submit a PR for this later, but I wanted to document this before I forgot:

One of our admins had an offline browser crawling and saving pages (why is unknown), which kept triggering `GET` requests to the product clone endpoint, creating thousands of product copies that ended up showing to end users on production.

This particular case is mostly user error, but it might be good to move the clone endpoint to `POST`. IMHO, `GET` should never create, modify or destroy a record.

**Comment by damianlegawiec** [comment]
:+1: 

Good catch @crypticsymbols - feel free to submit a PR - thanks!

**Comment by crypticsymbols** [comment]
Opened #7248 - let me know if anything needs changing :)
