### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by PascalPencil** [spree/spree#7252]
Can't get S3 working, using Heroku so writing locally disables backups, must be missing something simple?

The following code does not error and works, but the files are not on S3:
```ruby
# config/initializers/s3.rb
Rails.env.production? do
  attachment_config = {
    s3_credentials: {
      access_key_id:     aws_access_key_id,
      secret_access_key: aws_secret_access_key,
      bucket:            bucket_name
    },

    storage:        :s3,
    s3_headers:     { "Cache-Control" => "max-age=31557600" },
    s3_protocol:    "https",
    bucket:         bucket_name,
    url:            ":s3_domain_url",

    path:           "/spree/:class/:id/:style/:basename.:extension",
    default_url:    "/spree/:class/:id/:style/:basename.:extension",
    default_style:  "product"
  }
  attachment_config.each do |key, value|
    Spree::Image.attachment_definitions[:attachment][key.to_sym] = value
  end
end
```

Thanks to anyone giving this consideration :100:

**Comment by priyank-gupta** [comment]
@PascalPencil You may find this, http://stackoverflow.com/questions/36063670/unable-to-connect-spree-app-with-s3/36278534#36278534, useful.

**Comment by PascalPencil** [comment]
@priyank-gupta thank you! I was able to upload images to S3 now, which seem to be in my S3 container, however, the app cannot seem to retrieve that image, it requests `http://s3.amazonaws.com/APP-NAME/app/public/spree/products/50/product/CehKQ5CW8AESGLs.jpg?1459335605` but that is not the correct path, any ideas?

**Comment by priyank-gupta** [comment]
@PascalPencil Can you paste your updated config and `action_controller.asset_host` config for reference ?

**Comment by PascalPencil** [comment]
```ruby
# config/initializers/s3.rb (there is no spree.rb)
Spree.config do |config|
end
Spree.user_class = "Spree::User"
attachment_config = {
  s3_credentials: {
    access_key_id:     aws_access_key_id,
    secret_access_key: aws_secret_access_key,
    bucket:            bucket_name
  },
  storage:        :s3,
  s3_protocol:    "http"
}
attachment_config.each do |key, value|
  Spree::Image.attachment_definitions[:attachment][key.to_sym] = value
end
```

I hadn't set assets_host, but since you mentioned it I tried setting it to `config.action_controller.asset_host = "//APP-NAME.s3.amazonaws.com"` resulting in Rails assuming all assets were up there

**Comment by priyank-gupta** [comment]
@PascalPencil Try adding 
````
url: '/spree/:class/:id/:style/:basename.:extension',
path: '/spree/:class/:id/:style/:basename.:extension'
````

**Comment by PascalPencil** [comment]
@priyank-gupta Thank you for your continued replies!

The view generates:
`http://s3.amazonaws.com/rommydebommy/spree/spree/images/1/mini/IMG_8142.JPG?1459408348`
The link should be:
`http://rommydebommy.s3.amazonaws.com/spree/spree/images/1/mini/IMG_8142.JPG?1459408348`

**Comment by PascalPencil** [comment]
@priyank-gupta Seems to be related to this issue: https://github.com/spree/spree/issues/1840
As I am using eu-west-1

**Comment by priyank-gupta** [comment]
@PascalPencil Yeah, you got it right.
You link should be something, http://s3-eu-west-1.amazonaws.com/rommydebommy/spree/spree/images/1/mini/IMG_8142.JPG?1459408348

**Comment by PascalPencil** [comment]
Fixed, thank you @priyank-gupta for helping out!
The final code for reference:

```ruby
Spree.config do |config|
end
Spree.user_class = "Spree::User"
attachment_config = {
  s3_credentials: {
    access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    bucket:            ENV['S3_BUCKET_NAME']
  },

  storage:        :s3,
  s3_protocol:    'http',
  s3_host_name:   's3-eu-west-1.amazonaws.com',

  url:            '/spree/:class/:id/:style/:basename.:extension',
  path:           '/spree/:class/:id/:style/:basename.:extension'
}
attachment_config.each do |key, value|
  Spree::Image.attachment_definitions[:attachment][key.to_sym] = value
end
```

**Comment by lucasocon** [comment]
I put a solution that worked for me [here](https://github.com/spree/spree/commit/b1d6c5e4b9801d888cc76c05116b814945122207#commitcomment-33520536)

Hope it works for someone else.
