### ISSUE TITLE
Variant name or SKU is not ransack searchable through API

### ISSUE THREAD

**Issue by fabiode** [spree/spree#7256]
Hi! I think I found a problem using the new Stock Transfer form.

While searching for the Variants using SKU or name, the API responds wrongly. It does not apply the ransack filter and, testing here, I think it's because StockItem model does not have _variant_ association in **whitelisted_ransackable_associations**.

Maybe there are others models that can't be ransacked through API because of the whitelist filter.
Does anybody know any of them?

I will do a pull request for this!

Thanks!

**Comment by priyank-gupta** [comment]
@fabiode Agreed. Please do a PR for this. Thanks!!!

**Comment by fabiode** [comment]
@priyank-gupta Did it! #7301

**Comment by fabiode** [comment]
@priyank-gupta The PR has been merged! https://github.com/spree/spree/pull/7301
Closing the issue.
