### ISSUE TITLE
_head.html.erb error when add new css.erb file

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree#7267]
Hi,

I'm using Spree 3.0.7. For now, I'm getting a error when I try to add a new css file (main.css.erb). This worked for me in Spree 3.0.4. does It seems error cause by extension file ".css.erb"? Below is more detail about error.

/usr/local/rvm/gems/ruby-2.2.2/gems/spree_frontend-3.0.7/app/views/spree/shared/_head.html.erb where line #8 raised:

undefined method `start_with?' for nil:NilClass

Thanks

**Comment by damianlegawiec** [comment]
@ducnguyenhuy could you try update to `3.0.8` or `3.1.0rc1` ?
