### ISSUE TITLE
Master variant appears in store back-end cart autocomplete when Product has other variants

### ISSUE THREAD

**Issue by fabiode** [spree/spree#7302]
I think this behavior is kind of strange, since in store front-end, after you create variants for a certain product, you cannot add the master variant to the cart, and if I think in old versions of Spree, you actually could not add master variant if the Product had other variants. 

This is caused by the ••Spree::Api::V1::VariantsController•• which uses as base scope _@product.variants_including_master_.

I don't know if this is an expected behavior. If it isn't, I think changing the scope, maybe passing a parameter to include master or not, could be a solution.

What you think about it?

**Comment by cjcruz** [comment]
+1
