### ISSUE TITLE
Can't update ransack

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree#7307]
I'm using version 3.0.7, and when I check 'ransack' by command line `bundle show ransack`, it shows me ransack version 1.4.1. For now, I want to update ransack version, I have try to `bundle update ransack` but ransack is not updated. Could you tell me how to update ransack to newer version that it still works on spree version 3.0.7. Thanks.

**Comment by krzysiek1507** [comment]
@ducnguyenhuy ransack is locked on version `~> 1.4.1`
https://github.com/spree/spree/blob/3-0-stable/core/spree_core.gemspec#L39

**Comment by ducnguyenhuy** [comment]
@krzysiek1507 So can't I update it?

**Comment by krzysiek1507** [comment]
@ducnguyenhuy Nope, but you can send pull requests to master and 3-0-stable with updated ransack.

**Comment by ducnguyenhuy** [comment]
@krzysiek1507: If I create pull request and they merged them, then how to update ransack on my server?

**Comment by krzysiek1507** [comment]
@ducnguyenhuy Then you can update spree and ransack  to newest 3.0.x version if released.

**Comment by ducnguyenhuy** [comment]
@krzysiek1507: Yes, I c. But your site is live, so I only want to update ransack, not others. So updated new released maybe maybe bug on my live site. Right?

**Comment by krzysiek1507** [comment]
@ducnguyenhuy It is possible if changes in new versions conflict with your custom code.
