### ISSUE TITLE
Error when i upload/delete image

### ISSUE THREAD

**Issue by ttibau** [spree/spree#7313]
Hello, before this issue  issue i apologize for my English. 
In production, my application its works, but when i upload or delete a new image, i receive this message:  "We're sorry, but something went wrong."
I check the logs and i received this: (https://gist.github.com/ttibau/6cc13847fdcca537de7446b3ef7d81ac)
I do not find the solution.
Sorry for my english. Thanks.

**Comment by damianlegawiec** [comment]
@ttibau this is actually `acts_as_list` issue, please update this gem to `0.7.4` or downgrade to `0.7.2`

**Comment by ttibau** [comment]
Please tell me how i can change this gem. Thanks! 
I tried, but no got success.

**Comment by ttibau** [comment]
@damianlegawiec Please reopen this issue.
