### ISSUE TITLE
update act_as_list

### ISSUE THREAD

**Issue by ttibau** [spree/spree#7323]
How i can update the gem 'act_as_list' to ` 0.7.4 ` or ` 0.7.3 `. In RubyGems the act_as_list are in 0.6 version in spree_core gem, i have errors because this gem. Sorry for my English

**Comment by markfinlaybonkers** [comment]
From what I can see spree/core use is already using acts_as_list '0.7.4' which is the the same as the version in current master for acts_as_list.
