### ISSUE TITLE
installing spree extensions

### ISSUE THREAD

**Issue by radha290884** [spree/spree#7331]
Hello! 
Im trying to install different exxtensions but always have problems. 
For example, when Im installing spree_email_to_friend this is the error. 

C:\Bitnami\spree-3.0.4-1\shop>bundle install
Fetching git://github.com/spree/spree_i18n.git
Fetching https://github.com/spree-contrib/spree_email_to_friend.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies........
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.2.2) x86-mingw32

    spree_email_to_friend x86-mingw32 was resolved to 1.3.0, which depends on
spree_core (~> 3.1.0.beta) x86-mingw32 was resolved to 3.1.0.rc1, which
depends on
        rails (~> 4.2.6) x86-mingw32

How can I solved it? 

Thank uuu!

**Comment by fiftin** [comment]
spree_email_to_friend.gemspec:
```
s.add_dependency 'spree_core', '~> 3.1.0.beta'
```
You can update your Spree to version 3.1

**Comment by Mafi88** [comment]
@radha290884 If your store is running on spree 3-0-stable, you should install extensions for this version, for example: https://github.com/spree-contrib/spree_email_to_friend/tree/3-0-stable

**Comment by radha290884** [comment]
Thanks both of u! Ill try it and tell u what finally happend!!

-------- Mensaje original --------
De: Mafi88 <notifications@github.com> 
Fecha: 10/05/2016  19:34  (GMT+01:00) 
Para: spree/spree <spree@noreply.github.com> 
Cc: radha290884 <radha290884@hotmail.com>, Mention <mention@noreply.github.com> 
Asunto: Re: [spree/spree] installing spree extensions (#7331) 

@radha290884 If your store is running on spree 3-0-stable, you should install extensions for this version, for example: https://github.com/spree-contrib/spree_email_to_friend/tree/3-0-stable
