### ISSUE TITLE
Cannot transition state via :next from :cart (Reason(s): State is not included in the list)

### ISSUE THREAD

**Issue by antoineayoub** [spree/spree#7337]
Hello guys,

I am new to rails and I have an issue i could not solved due to an upgrade from spree 3-0-stable to 3-1-stable.

```ruby
ruby '2.2.2'
gem 'rails', '4.2.6'

gem 'spree', github: 'spree/spree', branch: '3-1-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-1-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-1-stable'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-1-stable'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
```

**Issue Explanation**
I create a new checkout process quick_checkout to allow customers already logged to finalize there order in 2 clicks : cart => quick_checkout => complete.

To do it I override the order model to insert and remove steps :
```ruby
Spree::Order.class_eval do
  remove_checkout_step :confirm
  remove_checkout_step :delivery
  insert_checkout_step :quick, before: :address, if: ->(order) { order.user && order.user.orders.any? && order.user.billing_address && order.user.payment_sources.any?}
end
```
I also add the needed template view _quick.html.erb

Everything works well when i did the process for the first time cart => quick => complete. But, when I go back from quick to cart or quick to an other page of my app, it doesn't work anymore. When I try to pass from my cart to my quick_checkout step i've got the following issue :

<img width="1279" alt="capture d ecran 2016-05-06 a 11 39 47" src="https://cloud.githubusercontent.com/assets/12274713/15071016/d4f18094-1388-11e6-9662-d2ea40e4f052.png">

<img width="1277" alt="capture d ecran 2016-05-06 a 11 40 03" src="https://cloud.githubusercontent.com/assets/12274713/15070998/adbc86b8-1388-11e6-8455-62b7e82c8e34.png">

Is that clear for you ? Am I enough exhaustive ?

Thanks for your help
A

**Comment by joryhatton** [comment]
👍

I'm seeing the same issue in 3-1-stable.  I can no longer transition to a custom state added with `insert_checkout_step`.  I get the 'State is not included in the list' error, although `Spree::Order.state_machine.states` now includes my custom state.

**Comment by damianlegawiec** [comment]
@antoineayoub @joryhatton thanks for reporting this - we're looking into it

**Comment by damianlegawiec** [comment]
@antoineayoub @joryhatton thanks to @mauazua and @krzysiek1507 this issue is fixed on `3-1-stable` and `master` branches, `3.1.0.rc3` containing this fix will be released later today :)

**Comment by antoineayoub** [comment]
thanks for your reactivity @damianlegawiec it is working now.
