### ISSUE TITLE
Wrong currency displayed

### ISSUE THREAD

**Issue by PascalPencil** [spree/spree#7338]
On the product page:
<img width="238" alt="screenshot 2016-05-08 21 51 10" src="https://cloud.githubusercontent.com/assets/3094044/15097902/2c31c4f6-1567-11e6-8ed8-bfccbf99b599.png">

On the cart page and payment pages:
<img width="475" alt="screenshot 2016-05-08 21 51 20" src="https://cloud.githubusercontent.com/assets/3094044/15097904/32387dcc-1567-11e6-8ed0-44d71abdfc60.png">

This is on 3-0-stable
Correct currency is €
Only happens on admin account

**Comment by damianlegawiec** [comment]
@PascalPencil please test it against `3.1` - it should be fixed in this version :)
