### ISSUE TITLE
Question: Spree on Rails 5

### ISSUE THREAD

**Issue by SylarRuby** [spree/spree#7339]
Is there a branch I could play around with for Rails 5? I know I could use Rails 4 but I'll be doing some deep modification.

**Comment by damianlegawiec** [comment]
Hey @SylarRuby , the master branch which will become `3.2.0` is going to be ported to Rails 5 in coming weeks. The latest stable release - `3.1.0` is still Rails 4.2.

**Comment by onpaws** [comment]
Any news on this? 
Would love to contribute to getting us running smoothly on Rails 5.

**Comment by damianlegawiec** [comment]
Hey @onpaws there is few last specs failing for Rails 5 , take a look at the PR https://github.com/spree/spree/pull/7555

Any help getting it fixed really appreciated!
