### ISSUE TITLE
Can we add Tagging module in spree for products

### ISSUE THREAD

**Issue by vishalzambre** [spree/spree#7343]
Can we add tagging module for products.

If yes I'll ready to send PR for same.

**Comment by damianlegawiec** [comment]
Hey @vishalzambre  - how would this differ from `Taxons`? :)

**Comment by vishalzambre** [comment]
@damianlegawiec Taxons are different that tags a tag is a non-hierarchical keyword or term assigned to a piece of information (such as an Internet bookmark, digital image, or computer file).

You can call it as structure of non-hierarchical taxonomies

Taxons are nothing but the categories of products correct me if I'm wrong. But tags can be used to group data not only products it could be anything in system.

**Comment by damianlegawiec** [comment]
@vishalzambre please submit a PR than :)

**Comment by vishalzambre** [comment]
yes :+1:

**Comment by parhs** [comment]
This could be nice, since other platforms have this feature too
