### ISSUE TITLE
Performance Problem - Home - Index - Retrieving records from database having 5000+ products

### ISSUE THREAD

**Issue by gitrepo4koresol** [spree/spree#7346]
Hi -
We are using spree 3-0-stable for one of our clients eCommerce portal.

We observed that performance was good till 1000 products in database.
When we uploaded 5000+ products, it took more than 32500 ms to render the home/index page.
After further debugging we found that below query took significant long time to execute, please could anyone provide pointers to refine the below query or suggest any Spree tweaks to enhance the performance - Thank You !!:
__________________________________________________________

(32337.7ms)  SELECT  DISTINCT "spree_products"."id" FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = "t" AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL LEFT OUTER JOIN "spree_products_taxons" ON "spree_products_taxons"."product_id" = "spree_products"."id" WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".deleted_at IS NULL or "spree_products".deleted_at >= "2016-05-11 09:23:43.131421") AND ("spree_products".available_on <= "2016-05-11 09:23:43.132976") AND "spree_products_taxons"."taxon_id" = 111 AND (spree_prices.amount IS NOT NULL) AND "spree_prices"."currency" = "INR"  ORDER BY spree_products_taxons.position ASC LIMIT 12 OFFSET 0

___________________________________________________________________________

**Comment by damianlegawiec** [comment]
@gitrepo4koresol what are your database server specs? (CPU/RAM)

**Comment by gitrepo4koresol** [comment]
Hi Damian 
Please find below the server specs:

Ubuntu 12.x OS
2GB Memory
2 CoreProcessor
40 GBSSD Disk
3 TBTransfer
Tested this with SQLite 3 and Mysql 

Thank you in advance for your help ..

**Comment by damianlegawiec** [comment]
@gitrepo4koresol if you're running also your web app on the same machine it won't be sufficient against this kind of number of SKUs.
