### ISSUE TITLE
Exception when adding an item to empty order through the admin panel

### ISSUE THREAD

**Issue by tommiller1** [spree/spree#7349]
Hi,

Removing all items from an order through the admincp and then adding a new item to it causes this error:
(undefined method `set_up_inventory' for nil:NilClass) inside /order_inventory.rb:69:in`block in add_to_shipment'

Regards.

**Comment by damianlegawiec** [comment]
@tommiller1 thanks for reporting this

**Comment by cjcruz** [comment]
i have the same problem, how can i fix it??? help please...

**Comment by 3minus1** [comment]
Has this been fixed?
