### ISSUE TITLE
Redundant scopes for products

### ISSUE THREAD

**Issue by gauravmahajan31** [spree/spree#7351]
In the [scopes.rb](https://github.com/spree/spree/blob/master/core/app/models/spree/product/scopes.rb), the scope `active` is redundant as it is using `not_discontinued` chained by `available`. The `available` scope itself includes the `not_discontinued` scope. Also, we are passing currency in the arguments for both `active` and `available` scopes. But, currency is not being used anywhere in the scopes. I am going to create a PR for this. Please let me know what is the supposed correct behavior for these two scopes.

**Comment by vishalzambre** [comment]
@gauravmahajan31 Result may same of both scope but arguments are different. And the purpose of both is different I think. What is your thought here @damianlegawiec
