### ISSUE TITLE
shipment states are frozen

### ISSUE THREAD

**Issue by tommiller1** [spree/spree#7352]
Hi,

We need to add a new state to shipments: processing

However SHIPMENT_STATES is frozen and we cant add our new state to it even in a class_eval, is there any way to bypass this issue? We cant unfreeze the array and the order validates the shipment_state in a lambda so we cant override the validation either.

Regards.

**Comment by damianlegawiec** [comment]
Thanks again for reporting @tommiller1 ! :)
