### ISSUE TITLE
Cannot transition state via :return from :resumed (Reason(s): State cannot transition via "return")

### ISSUE THREAD

**Issue by tommiller1** [spree/spree#7356]
Hi,

Steps to reproduce:
1. create an order with just 1 item.
2. cancel the order through admincp.
3. resume the order (should be in the resumed state)
4. add a payment through admincp (state is still resumed, shouldnt it be completed?)
5. ship the order (state is still resumed, shouldnt it be completed?)
6. create return authorization
7. create new customer return -> this will cause this error: Cannot transition state via :return from :resumed (Reason(s): State cannot transition via "return")

The resumed state causes other issues too (ex. have to add resumed? || completed? everywhere instead of just completed?) because it runs in parallel to the completed state.

Regards.

**Comment by tommiller1** [comment]
Other issues with resumed state:

Its not possible to cancel a resumed order.
Shipments state is cancelled even after order is resumed.

In my opinion it would be much simpler to just provide a 'clone order' button after an order has been cancelled and remove the resumed state entirely.

**Comment by mauazua** [comment]
hi @tommiller1, thanks for reporting this issue. I think that adding a transition from `resumed` to `return` will be a better approach to resolving the issue with transitions. About the payment and shipment states in order, the order needs to be updated (`update_with_updater` would be the best) after the `resume` transition is complete.

**Comment by tommiller1** [comment]
Hi, we submitted a PR for this which fixes the issues. I was under the impression the return state is for when all items have been returned? An order cant be cancelled after it has been shipped anyway.

**Comment by damianlegawiec** [comment]
@tommiller1 in your solution to this issue the `resumed` state is kinda useless and non-existent which would break many businesses customer service workflows - they wouldn't know which orders are resumed and which are new. Like @mauazua suggested, better approach would be to just add additional transitions

**Comment by tommiller1** [comment]
Alright, thanks for the feedback.

**Comment by 0902074** [comment]
[http://www.chuyensuadogotainha.com/2016/06/noi-that-anh-nghia0902240304-son-pu-gia.html](url)

**Comment by krzysiek1507** [comment]
Fixed with #7554
