### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by AlexMcConnell** [spree/spree#7358]
https://guides.spreecommerce.com/developer/getting_started_tutorial.html

rails _4.2.0_ new mystore
cd mystore
spree install --auto-accept

Could not find gem 'spree (~> 3.0.9)' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by AlexMcConnell** [comment]
So, I get past that error when I use Rails version 4.2.2 instead, but then it hangs on
'bundle install from "."'

**Comment by the-widget** [comment]
This issue has been resolved via PR #7230, which has updated the getting_started_tutorial.html on the Master branch. This tutorial works perfectly as of today.

But the changes have not been applied to the public URL: https://guides.spreecommerce.com/developer/getting_started_tutorial.html
I have been trying to see how I can make the change the public documentation but haven't found a solution yet.

**Comment by vfonic** [comment]
@damianlegawiec the new version of guides has been deployed long ago. You could close this issue.

Some issue maintenance might come in handy.
