### ISSUE TITLE
Home page error after installation of  3.1.0.rc3

### ISSUE THREAD

**Issue by alexkirill** [spree/spree#7359]
After installation of 3.1.0.rc3 
ExecJS::ProgramError in Spree::Home#index
Showing C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/spree_frontend-3.1.0.rc3/app/views/spree/shared/_products.html.erb where line #28 raised:

    25:           <% cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : cache_key_for_product(product)) do %>
    26:             <div class="panel-body text-center product-body">
    27:               <%= link_to url, itemprop: "url" do %>
    28:                 <%= small_image(product, itemprop: "image") %><br/>
    29:                 <%= content_tag(:span, truncate(product.name, length: 50), class: 'info', itemprop: "name", title: product.name) %>
    30:               <% end %>
    31:               <br/>

TypeError: Object doesn't support this property or method
Trace of template inclusion: C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/spree_frontend-3.1.0.rc3/app/views/spree/home/index.html.erb

**Comment by SylarRuby** [comment]
Install 3.1 stable and close this issue.

**Comment by santhosh18** [comment]
I am getting the same error.. what should I install?

**Comment by santhosh18** [comment]
ExecJS::ProgramError in Spree::Home#index
Showing C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/spree_frontend-3.3.0/app/views/spree/shared/_head.html.erb where line #7 raised:

TypeError: Object doesn't support this property or method
Extracted source (around line #39):
        begin
          extract_result(@runtime.exec_runtime(filepath), filepath)
        ensure
          File.unlink(tmpfile)
        end

Trace of template inclusion: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/spree_frontend-3.3.0/app/views/spree/layouts/spree_application.html.erb

Rails.root: C:/Users/aravinth0812/mystore

Application Trace | Framework Trace | Full Trace
execjs (2.7.0) lib/execjs/external_runtime.rb:39:in `exec'
execjs (2.7.0) lib/execjs/external_runtime.rb:21:in `eval'
execjs (2.7.0) lib/execjs/external_runtime.rb:46:in `call'
coffee-script (2.4.1) lib/coffee_script.rb:78:in `compile'
sprockets (3.7.1) lib/sprockets/coffee_script_processor.rb:21:in `block in call'
