### ISSUE TITLE
 undefined method `spree_api_key=

### ISSUE THREAD

**Issue by SylarRuby** [spree/spree#7363]
**Spree 3.1.0.rc3**

On development, I have switched to postgreSQL db. Then ran:

`rake db:reset db:seed db:migrate` then got the error just after it asked for the spree admin details:

> NoMethodError: undefined method `spree_api_key=' for #<Spree::User:0x007f8dc5fa7be8>
Did you mean?  spree_role_ids=

Before this, [following this guide](https://guides.spreecommerce.com/developer/authentication.html#the-user-model) to add a custom user model. The guide needs updating because I do not see `Spree.user_class = "Spree::User"` in my app, I see this instead `Spree.user_class = "Spree::LegacyUser"`

I've opened up the spree core with `bundle show spree` but I can't find the method anywhere. I think this is a bug.

**Comment by reelman** [comment]
Seems like I had similar issue. In my case I didn't install api migrations
`bundle exec rake spree_api:install:migrations`
