### ISSUE TITLE
Spree product status "Discontinued" after a Spree upgrade

### ISSUE THREAD

**Issue by antoineayoub** [spree/spree#7365]
Hello everyone,

after an upgrade from Spree 3-0-stable to 3-1-stable it seems that all my "Deleted" product take the status "Discontinued". 

The problem is that I'm still seing  these products in my admin product page even if the checkbox in the filter navbar is unselected.
<img width="325" alt="capture d ecran 2016-05-20 a 15 28 30" src="https://cloud.githubusercontent.com/assets/12274713/15429130/a30b0c22-1e9f-11e6-9754-b10f92e07002.png">

I could not delete the files. Why i'm still seing it ? Is it possible to delete all the Discounted product with a ruby script ? If yes could you help me with it ? 

NB : I saw this warning during the upgrade migration and i did the asked rake : 

```
Warning: This migration changes the meaning of 'deleted'. Before this change, 'deleted' meant products that were no longer being sold in your store. After this change, you can only delete a product or variant if it has not already been sold to a customer (a model-level check enforces this). Instead, you should use the new field 'discontinue_on' for products or variants which were sold in the past but no longer for sale. This fixes bugs when other objects are attached to deleted products and variants. (Even though acts_as_paranoid gem keeps the records in the database, most associations are automatically scoped to exclude the deleted records.) In thew meaning of 'deleted,' you can still use the delete function on products & variants which are *truly user-error mistakes*, specifically before an order has been placed or the items have gone on sale. You also must use the soft-delete function (which still works after this change) to clean up slug (product) and SKU (variant) duplicates. Otherwise, you should generally over ever need to discontinue products.

Data Fix: We will attempt to reverse engineer the old meaning of 'deleted' (no longer for sale) to the new database field 'discontinue_on'. However, since Slugs and SKUs cannot be duplicated on Products and Variants, we cannot gaurantee this to be foolproof if you have deteled Products and Variants that have duplicate Slugs or SKUs in non-deleted records. In these cases, we recommend you use the additional rake task to clean up your old records (see rake db:fix_orphan_line_items). If you have such records, this migration will leave them in place, preferring the non-deleted records over the deleted ones. However, since old line items will still be associated with deleted objects, you will still the bugs in your app until you run:
rake db:fix_orphan_line_items
```

**Comment by joeswann** [comment]
In regard to the first issue, I think part of the issue is that `discontinue_on` needs to be added to `whitelisted_ransackable_attributes` on `Spree::Product`

Another issue is that by default loading admin product index shows discontinued products on first load. I'm fixing this by adding a default `discontinue_on_null` value to `Spree::Admin::Productscontriller.collection`

**Comment by damianlegawiec** [comment]
Hi @joeswann can you submit a PR with those fixes? Thanks!

**Comment by joeswann** [comment]
Haven't done a PR before, think I have it right now. Last three of the above are the relevant ones.

Let me know if I messed up. Thanks!
