### ISSUE TITLE
rails g spree:install --user_class=Spree::User Hangs in terminal

### ISSUE THREAD

**Issue by chris-barklem** [spree/spree#7368]
I attempted the usual fix, removing spring ... 

Basically I removed the version control on the spree gems in the gem file and ran a bundle update. Bundle downgraded the versions on spree to the stable:

```
Installing spree_core 3.0.9 (was 3.1.0.rc3)
Installing spree_api 3.0.9 (was 3.1.0.rc3)
Installing spree_sample 3.0.9 (was 3.1.0.rc3)
Installing spree_auth_devise 3.0.6 (was 3.1.0)
Installing spree_gateway 3.0.0 (was 3.1.0)
Installing spree_backend 3.0.9 (was 3.1.0.rc3)
Installing spree_frontend 3.0.9 (was 3.1.0.rc3)
Installing spree 3.0.9 (was 3.1.0.rc3)
Bundle updated!
```

It now installs.

**Comment by damianlegawiec** [comment]
@chris-barklem `3.1.0` stable is out so this shouldn't be an issue anymore

**Comment by cptncrnch** [comment]
I'm seeing this issue with `3.1.0`

```
...
Installing spree_core 3.1.0
Installing spree_api 3.1.0
Installing spree_sample 3.1.0
Using spree_auth_devise 3.1.0
Using spree_gateway 3.1.0
Installing spree_backend 3.1.0
Installing spree_frontend 3.1.0
Installing spree 3.1.0
Bundle complete!
```
And then running `rails g spree:install --user_class=Spree::User` just hangs at the terminal.

I made a rails `4.2.6` project using `rails _4.2.6_ new appname`

**Comment by acrolink** [comment]
Same here..

**Comment by loco-ola** [comment]
Same here with 4.2.8 & 3.1.0

**Comment by beckah** [comment]
Same.

**Comment by liangjingyang** [comment]
About `rails g spree:install --user_class=Spree::User` hanging at the terminal, maybe this can help: rails/spring#265

**Comment by digitalextremist** [comment]
Also seeing this with Rails `4.2.7.1` and `3.1.5`
