### ISSUE TITLE
Locales are being loaded after decorators, which can cause missing translation exceptions.

### ISSUE THREAD

**Issue by travishaynes** [spree/spree#7372]
To reproduce this issue, follow the [getting started guide](https://github.com/spree/spree#getting-started) so you have a completely new Spree installation, then add a new decorator for a model that accesses the locales. `LineItem` is one of them:

```ruby
# file: app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do
end
```

Turn on the missing translation exception rule in `config/environments/development.rb`:

```ruby
config.action_view.raise_on_missing_translations = true
```

Then start Rails. You should get a `translation missing: en.spree.validation.must_be_int` exception, which is coming from `lib/spree/i18n.rb`, line 18.

This is because the decorators are being loaded in `config/application.rb`:

```ruby
    config.to_prepare do
      # Load application's model / class decorators
      Dir.glob(Rails.root.join('app', '**', '*_decorator*.rb')) do |c|
        Rails.configuration.cache_classes ? require(c) : load(c)
      end
    end
```

This code is evaluated before Rails loads any of the locales, so even adding the missing translation to the project's `config/locales/en.yml` doesn't fix the issue. If you manually load the Spree core locales before the decorators, the exception disappears:

```ruby
    config.to_prepare do
      # Load Spree locales.
      path = Bundler.load.specs.find{|s| s.name == 'spree_core'}.full_gem_path
      I18n.load_path << File.join(path, 'config', 'locales', 'en.yml')
      I18n.backend.load_translations

      # Load application's model / class decorators
      Dir.glob(Rails.root.join('app', '**', '*_decorator*.rb')) do |c|
        Rails.configuration.cache_classes ? require(c) : load(c)
      end
    end
```

**Comment by mauazua** [comment]
hi @travishaynes, thank you for reporting this issue.

**Comment by zambrevishal** [comment]
@mauazua  @travishaynes  Can I raise PR for same?

**Comment by damianlegawiec** [comment]
@zambrevishal sure - go ahead! :)

**Comment by akestner** [comment]
I've inherited a Spree 3.0 codebase and have run up against this issue as well.  @travishaynes's manual fix isn't working for me, any ideas?

**Comment by damianlegawiec** [comment]
@akestner go ahead and do a PR with this change against `3-0-stable` - we'll merge it :)

**Comment by vishalzambre** [comment]
@damianlegawiec @akestner  I have same branch in my spree repository, Let me send PR against ```3-0-stable```

**Comment by akestner** [comment]
Thanks guys!
