### ISSUE TITLE
OrderContents#remove_line_item do not restock item.

### ISSUE THREAD

**Issue by odk211** [spree/spree#7375]
`OrderContents#remove_line_item` is used by `Spree::Api::V1::LineItemsController#destroy`

This method do not re-stock item, because `Spree::LineItem#update_inventory` method is not called actually.
Because `if (changed? || target_shipment.present?) && order.has_checkout_step?("delivery")` is false
when simply destroy line_item in OrderContents#remove_line_item.

https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb#L22
https://github.com/spree/spree/blob/master/core/app/models/spree/line_item.rb#L128

**Comment by damianlegawiec** [comment]
Fixed
