### ISSUE TITLE
 spree  load routes by sort

### ISSUE THREAD

**Issue by Baozi2** [spree/spree#7379]
when I use  spree_auth_devise and  spree, when I ran  rake routes ,I found that the spree_auth_devise' routes  is loaded before frontend , frontend by backend.Do have rule  for  load routes?

**Comment by joneslee85** [comment]
If this is not about a particular issue, please use chat or mailing list.

There is a good way to see the loading order, please see the suggestion using `TracePoint` in http://stackoverflow.com/questions/8672803/in-what-order-are-the-config-files-loaded-for-rails
