### ISSUE TITLE
HTTP DELETE method with payload is not good.

### ISSUE THREAD

**Issue by odk211** [spree/spree#7381]
Some backend code use HTTP DELETE method with payload. But It is better not to use DELETE with payload if we can. You can see discussion [here](http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request).

I found Spree token is send in payload, but we can use 'X-Spree-Token' header.
https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/line_items.js.coffee#L55-L59
In my case [teatro](https://teatro.io) do not accept DELETE method with payload (I use Webrick in teatro).

**Comment by damianlegawiec** [comment]
@odk211 - good catch - can you submit a PR with a fix?

**Comment by odk211** [comment]
@damianlegawiec I checked backend code, and maybe this is the only code to use DELETE method with payload.
