### ISSUE TITLE
Address zipcode wrong validation

### ISSUE THREAD

**Issue by azranel** [spree/spree#7389]
Right now on master branch there is validation for Address model for zipcode. It's always check it even though this may be problem because for example Hong Kong doesn't have zipcodes.

**Comment by krzysiek1507** [comment]
@azranel you can disable zipcode validation https://github.com/spree/spree/blob/master/core/app/models/spree/address.rb#L97-L99

**Comment by azranel** [comment]
@krzysiek1507 I know that but still I think that by default zipcode validation should be turned off for countries that doesn't have zipcodes 😄

**Comment by damianlegawiec** [comment]
Yep, it should be turned off in this kind of scenarios. @azranel  could you submit a PR with a fix for this problem?

**Comment by priyank-gupta** [comment]
@azranel Are you working on the PR for this bug ?

**Comment by azranel** [comment]
@priyank-gupta didn't have time yet so far. If you want, please take care of it 😄

**Comment by damianlegawiec** [comment]
Fixed in master branch :)
