### ISSUE TITLE
 could not find compatible versions for gem "spree_core":

### ISSUE THREAD

**Issue by danyline** [spree/spree#7393]
Hello, 
running bundle install on my spree_simple_sales extension app produces,

https://cl.ly/121927120q2B
https://cl.ly/1P2f1n001T01

Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.2.0.alpha)

  In Gemfile:
    spree_auth_devise was resolved to 3.2.0.alpha, which depends on
      spree_core (~> 3.2.0.alpha)

    spree was resolved to 3.2.0.alpha, which depends on
      spree_frontend (= 3.2.0.alpha) was resolved to 3.2.0.alpha, which depends on
        spree_core (= 3.2.0.alpha)

    spree was resolved to 3.2.0.alpha, which depends on
      spree_frontend (= 3.2.0.alpha) was resolved to 3.2.0.alpha, which depends on
        spree_core (= 3.2.0.alpha)

    spree was resolved to 3.2.0.alpha, which depends on
      spree_frontend (= 3.2.0.alpha) was resolved to 3.2.0.alpha, which depends on
        spree_core (= 3.2.0.alpha)

    spree_simple_sales was resolved to 3.1.0.rc3, which depends on
      spree_core (~> 3.1.0.rc3)

So when I do change,

Gem::Specification.new do |s|
  s.platform    = Gem::Platform::RUBY
  s.name        = 'spree_simple_sales'
  s.version     = '3.2.0.alpha'
  s.authors     = ["User"]
  s.add_dependency 'spree_core', '~> 3.2.0.alpha'

I get Error running bundle install on my main application.

Any advice would be appreciated.
Thank you

**Comment by priyank-gupta** [comment]
@danyline What error are you seeing while running bundle on main app ?

**Comment by ammit** [comment]
Try `bundle update`.
And are you sure `3.2.0.alpha` version is available ?

**Comment by pymevirtual** [comment]
HELP Please I´m stuck on this error , on windows 10 and c9.io the same

Could not find gem 'spree (~> 3.1.0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by joneslee85** [comment]
There is no release 3.2.0.alpha, the spree_auth_devise gem is wrong. 

@priyank-gupta you bumped it to this version as of https://github.com/spree/spree_auth_devise/commits/master/spree_auth_devise.gemspec, I think you should revert this change.

What we normally do is to use `Gemfile` instead of `gemspec` in the unrelease case. `Gemfile` allows you to specify git branch of a specific gem.

**Comment by priyank-gupta** [comment]
@joneslee85 Spree 3.2.0.alpha version is on master branch. There is no release for that as of yet. Thats why I have pointed spree to master branch in Gemfile and specified spree version 3.2.0.alpha in gemspec.

**Comment by joneslee85** [comment]
I do not believe this issue is relevant to this spree repo as it is more related to spree_auth. And that simple_sale repo. @danyline please create issue on the other repo.
