### ISSUE TITLE
Variant#clear_in_stock_cache do not run when stock_item is destroyed

### ISSUE THREAD

**Issue by odk211** [spree/spree#7399]
I check in spree 3-1-stable but it should occur at master.

Because StockItem `after_touch` callback do not run when destroyed.
https://github.com/spree/spree/blob/master/core/app/models/spree/stock_item.rb#L23

Also, `counter_cache` do not touch Variant in spree 3-1-stable.
https://github.com/spree/spree/blob/3-1-stable/core/app/models/spree/stock_item.rb#L7

`clear_in_stock_cache` is called by `after_touch` callback.
https://github.com/spree/spree/blob/3-1-stable/core/app/models/spree/variant.rb#L53

**Comment by odk211** [comment]
maybe `touch: true` option is enough.
```
    with_options inverse_of: :stock_items do
      belongs_to :stock_location, class_name: 'Spree::StockLocation'
      belongs_to :variant, class_name: 'Spree::Variant', touch: true
    end
```

**Comment by priyank-gupta** [comment]
@odk211 👍 `touch: true` works fine. Can you submit a PR against this ?

**Comment by odk211** [comment]
@priyank-gupta Thanks, check please :) #7400
