### ISSUE TITLE
how to remove bootstrap css from spree frontend

### ISSUE THREAD

**Issue by dinshawr** [spree/spree#7412]
Recently, I tried to remove all instances of Bootstrap from the front end of Spree by overriding frontend_boostrap.css.scss

I have just included this file in app/assets/stylesheets/spree/frontend/frontend_boostrap.css.scss and kept it blank but still application loads bootstrap css. Please guide me how to remove  this from frontend.

**Comment by arvindvyas** [comment]
Hi @dinshawr , As per your question it is looking like you don't want bootstrap with your frontend, so if you will remove <%= stylesheet_link_tag 'spree/frontend/all', media: 'screen' %> from head file   https://github.com/spree/spree/blob/master/frontend/app/views/spree/shared/_head.html.erb  , I hope that will also work.
