### ISSUE TITLE
Deployed Spree to Heroku - No products found on the main page

### ISSUE THREAD

**Issue by tzurcan** [spree/spree#7413]
Hi, i am new to Rails
Have built a Spree-Rails app, deployed it onto Heroku, no issues
Can add new products from the admin panel, and see them from same admin panel, 
but no products will show if i just open the main page - just plain text - no products found
Any ideas? Would highly appreciate any help, it is a college project that i am trying to build, Thanks in advance

**Comment by theinbetweens** [comment]
Hi, have you set the "available on" date in admin?

**Comment by tzurcan** [comment]
:+1: 
Silly me :) Thanks a lot, all sorted !
Am new to ROR/Github/Heroku, but love working with it.
Thanks a mill for the help :)

**Comment by tzurcan** [comment]
Have managed to add the paperclip + S3 today, bunch of goods tutorials and documentation on the web, Thanks a lot, community, thanks theinbetweens !
