### ISSUE TITLE
Unable to get cvv_response_code and avs_response while using Stripe

### ISSUE THREAD

**Issue by rohanpujaris** [spree/spree#7414]
When using stripe cvv_response_code and avs_response is nil. Its due to activemerchant gem 1.47.0 used by spree.
This issue is fixed in following PR in activemerchant https://github.com/activemerchant/active_merchant/pull/1659. This PR is part of activemerchant 1.49.0.

Line that fixes this issue https://github.com/activemerchant/active_merchant/pull/1659/files#diff-8299be227de5ba32c34c30c42a828c9cR411

Is there any plan to upgrade activemerchant gem for spree? I can try this next weekend if we need to update activemerchant for spree.

**Comment by damianlegawiec** [comment]
@rohanpujaris thanks for reporting this issue!

@mauazua updated `activemerchant` for `master` and `3-1-stable` :)

**Comment by rohanpujaris** [comment]
np @damianlegawiec

Thanks @mauazua
