### ISSUE TITLE
uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)

### ISSUE THREAD

**Issue by sai43** [spree/spree#7420]
I tried to create new rails application and added spree gems to my application.
When I ran this command  'rails g spree:install --user_class=Spree::User', I got below error.

/home/saich/Workspace/Spree/practice/bazar/config/environments/development.rb:51:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
	from /home/saich/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `instance_eval'
	from /home/saich/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `configure'
	from /home/saich/Workspace/Spree/practice/bazar/config/environments/development.rb:2:in `<top (required)>'
	from /home/saich/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/saich/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/saich/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'

this is my gemfile:

# Use Spree for ecommerce development
gem 'spree', '~> 3.1.0.rc1'
gem 'spree_auth_devise', '~> 3.1.0.rc1'
gem 'spree_gateway', '~> 3.1.0.rc1'

**Comment by mauazua** [comment]
Hi, @sai43. Could you post your whole Gemfile and Gemfile.lock here?

**Comment by hammadxcm** [comment]
any solution?

**Comment by jaredchu** [comment]
I have the same problem when using this command: rails generate shopify_app

**Comment by rezapci** [comment]
I have the same problem when using this command: bin/rails generate controller Say hello goodbyeclear
