### ISSUE TITLE
How to add a new action in spree/api/orders_controller

### ISSUE THREAD

**Issue by pkumarmis** [spree/spree#7422]
Hi I am using spree api to develop a mobile app but when I add a new action in orders_controller and try accessing it from postman it raise an error.
**"error": "The resource you were looking for could not be found."**
I have override orders controller in my app.

**Comment by damianlegawiec** [comment]
@pkumarmis you have to add it to routes also, eg.

```
Spree::Core::Engine.routes.draw do
    namespace :api, defaults: { format: 'json' } do
      namespace :v1 do
        get '/orders/custom' => 'orders#custom', as: :orsers_custom
     end
  end
end
```

**Comment by pkumarmis** [comment]
@damianlegawiec Thanks man for your support, it's working,
But I found one another way also.
I override order_routes concern in config/routes.rb.
