### ISSUE TITLE
When adding a line item promotion to an order taxes are not re-adjusted with TaxCloud.

### ISSUE THREAD

**Issue by Lyonsclay** [spree/spree#7426]
When using the Spree::Calculator::DefaultTax an additional tax total is recalculated after applying a line item promotion to an order, however when using the Spree::Calculator::TaxCloudCalculator the taxes are not adjusted after applying the promotion.

Gemfile.lock -- https://gist.github.com/Lyonsclay/2480bf8229afc1a07a0a123343875c28

I have created a repo with a default Spree 3.0.8 app and added a test that demonstrates the behavior.

https://github.com/Lyonsclay/spree_3-0-stable_app

Clone the repo, run `bundle install`, and `rspec`.

**Comment by Lyonsclay** [comment]
After looking at the source code for the TaxCloudCalculator, I believe the issue is with spree_tax_cloud.

The following comment explains the problem;

  # TODO take discounted_amount into account. This is a problem because TaxCloud API does not take discounts nor does it return percentage rates.

I'm hoping to find an elegant work around if anybody can suggest one I would be grateful.

**Comment by damianlegawiec** [comment]
As this is `spree_tax_cloud` issue, closing it here
