### ISSUE TITLE
How to get product IDs for Facebook tracking pixel

### ISSUE THREAD

**Issue by partiallypro** [spree/spree#7427]
How do I pull in product IDs into the Facebook tracking pixel string?

Example:

`    content_type: 'product',
    content_ids: ['1234', '2345'],`

Where 1234, 2345 are the product IDs so we can see which products converted?

I am not familiar with this platform, and can't find anything from searching.

**Comment by damianlegawiec** [comment]
@partiallypro for questions please use http://slack.spreecommerce.com
