### ISSUE TITLE
install gem i18t  error translate Spanish Es

### ISSUE THREAD

**Issue by kasnino** [spree/spree#7434]
Error install extension i18t Es:
please help or recommendation.
tutorials or guides to read
Thank you.

![screenshot from 2016-06-20 22 24 00](https://cloud.githubusercontent.com/assets/16484156/16216140/2245b15e-3732-11e6-86b2-48f95d0c650f.png)
![screenshot from 2016-06-20 22 24 21](https://cloud.githubusercontent.com/assets/16484156/16216141/2282ebfa-3732-11e6-906a-54257be6fe0a.png)

![screenshot from 2016-06-20 22 28 56](https://cloud.githubusercontent.com/assets/16484156/16216155/425542c0-3732-11e6-80de-1cb23d196753.png)

**Comment by joneslee85** [comment]
please lodge issue on https://github.com/spree-contrib/spree_i18n/issues instead. 

besides, can you please describe the context on what does not work? (not here, please create issue in i18n repo)
