### ISSUE TITLE
Error "Could not find generator"

### ISSUE THREAD

**Issue by Magnusvb** [spree/spree#7443]
I have a fresh and clean Rails app. Have added to the gemfile:

```
gem 'spree', '~> 3.1.0'
gem 'spree_auth_devise', '~> 3.1.0'
gem 'spree_gateway', '~> 3.1.0'
```

Did a  'bundle install'. 
But when I run the rails generator:
`rails g spree:install --user_class=Spree::User`

I get the error:
[WARNING] Could not load generator "generators/spree/install/install_generator". Error: uninitialized constant Bundler::Thor::Base

and also:

Could not find generator 'spree:install'. Maybe you meant 'devise:install', 'spree:auth:install' or 'spree:dummy'

Tried with
`bundle exec rails g spree:install`
But it's the same error

Using Rails 4.2.6 and Ruby 2.2.1

Best

**Comment by Magnusvb** [comment]
An update: I tried several solutions, but in the end I had to remove RVM (rvm implode) and reinstall it. Then the rails generator worked. Yay!

**Comment by damianlegawiec** [comment]
Great to hear @Magnusvb 👍  RVM sometimes causes some strange issues...
