### ISSUE TITLE
API sorting orders by updated_at

### ISSUE THREAD

**Issue by debopamsengupta** [spree/spree#7449]
I'm trying to use the Spree API as documented in http://guides.spreecommerce.org/api/orders.html
I'm trying to use the endpoint ```/api/orders``` like ```GET /api/orders?q[s]=updated_at%20desc```
but the results are not sorted by ```updated_at```.

I can sort by other fields including ```created_at```, ```completed_at``` etc.
Any help is appreciated, thanks !

**Comment by vishalzambre** [comment]
@debopamsengupta  Hey If you want to add new parameter to sort or search in ransanck you need to add that attributes to ``` whitelisted_ransackable_attributes ```

like as follows
```
self.whitelisted_ransackable_attributes + =  %w[updated_at]
```

**Comment by damianlegawiec** [comment]
@vishalzambre I think it would be great to add also `updated_at` globally, this should be a common use case for the API

**Comment by vishalzambre** [comment]
@damianlegawiec  let me send PR for same
