### ISSUE TITLE
Spree with rails 5.0.0 is not compatible?

### ISSUE THREAD

**Issue by Faisal-nfl** [spree/spree#7513]
I 'm using ruby 2.3.1 and rails 5.0.0.
when I add gems of spree and run `bundle`, it says
```
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_core (= 3.1.0) was resolved to 3.1.0, which depends on
        rails (~> 4.2.6)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

But when I use rails 4.2.6 than it works ok.
Whats wrong with that?

**Comment by krzysiek1507** [comment]
Hi @Faisal-nfl we're working on compatibility with Rails 5.0.0.

**Comment by Faisal-nfl** [comment]
ok!

**Comment by onpaws** [comment]
@krzysiek1507 @damianlegawiec 
Thanks guys for your efforts on Rails 5 compatibility. 
I'm interested in helping out. Is there a branch I could check out?

**Comment by krzysiek1507** [comment]
Hi @onpaws. You can check the progress here: #7555

**Comment by theasteve** [comment]
Hi just run into this problem, just wondering when would this be released?
