### ISSUE TITLE
PaymentMethods aren't ordered

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#7515]
We can order the PaymentMethods in our Backoffice, but the Frontend will ignore the Order

the scope won't ordert. sha'll i make a pull request is is this expected behavior? if so, i don't get the point of ordering.
`scope :available_on_front_end, -> { active.where(display_on: [:front_end, :both])}
`

**Comment by damianlegawiec** [comment]
Hey @krtschmr - nice catch, please submit a PR with the fix, thanks!

**Comment by krtschmr** [comment]
https://github.com/spree/spree/pull/7516

**Comment by corny** [comment]
The order is also broken at the back end.

**Comment by krtschmr** [comment]
@corny this will fix both https://github.com/spree/spree/pull/7538
