### ISSUE TITLE
bundle install errors

### ISSUE THREAD

**Issue by Chaniel** [spree/spree#7521]
Resolving dependencies....
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.1.0)

  In Gemfile:
    spree_core (~> 3.1.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_api (= 3.1.0) was resolved to 3.1.0, which depends on
        spree_core (= 3.1.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_api (= 3.1.0) was resolved to 3.1.0, which depends on
        spree_core (= 3.1.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_api (= 3.1.0) was resolved to 3.1.0, which depends on
        spree_core (= 3.1.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_api (= 3.1.0) was resolved to 3.1.0, which depends on
        spree_core (= 3.1.0)

    spree (~> 3.1.0) was resolved to 3.1.0, which depends on
      spree_api (= 3.1.0) was resolved to 3.1.0, which depends on
        spree_core (= 3.1.0)

    spree_gateway (~> 3.0.0) was resolved to 3.0.0, which depends on
      spree_core (~> 3.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by damianlegawiec** [comment]
@Chaniel you need to also change `spree_gateway` to `~> 3.1.0`, check https://github.com/spree/spree#getting-started
