### ISSUE TITLE
Large Orders (> 1000 items) Cause Spree To Hang On Checkout Process

### ISSUE THREAD

**Issue by StrangeWill** [spree/spree#7531]
- Add 1000 items to cart (quantity, not individual line items)
- Go to checkout
- Try to get past shipping

My benchmarks are showing calls like this:

<pre>
MethodProfiler results for: Spree::Stock::Coordinator
+----------------------+--------------+--------------+--------------+--------------+-------------+
| Method               | Min Time     | Max Time     | Average Time | Total Time   | Total Calls |
+----------------------+--------------+--------------+--------------+--------------+-------------+
| #shipments           | 14725.381 ms | 14725.381 ms | 14725.381 ms | 14725.381 ms | 1           |
| #packages            | 14624.458 ms | 14624.458 ms | 14624.458 ms | 14624.458 ms | 1           |
| #prioritize_packages | 9548.671 ms  | 9548.671 ms  | 9548.671 ms  | 9548.671 ms  | 1           |
| #build_packages      | 4425.508 ms  | 4425.508 ms  | 4425.508 ms  | 4425.508 ms  | 1           |
| #initialize          | 950.874 ms   | 950.874 ms   | 950.874 ms   | 950.874 ms   | 1           |
| #estimate_packages   | 649.859 ms   | 649.859 ms   | 649.859 ms   | 649.859 ms   | 1           |
| #build_packer        | 0.053 ms     | 3.815 ms     | 1.934 ms     | 3.868 ms     | 2           |
| #splitters           | 0.016 ms     | 0.027 ms     | 0.022 ms     | 0.043 ms     | 2           |
| #inventory_units     | 0.005 ms     | 0.007 ms     | 0.006 ms     | 0.042 ms     | 7           |
| #order               | 0.005 ms     | 0.006 ms     | 0.005 ms     | 0.011 ms     | 2           |
+----------------------+--------------+--------------+--------------+--------------+-------------+
</pre>

Appears to be caused by this call: https://github.com/spree/spree/blob/1077e100268b911bcdad267154fc30a1fd0a4a51/core/app/models/spree/order.rb#L492

Not sure what can be done to create bulk records to make this more efficient, it appears I can cause Spree to error out of the box trying to do stuff like this.

Same issue appears to happen when attempting to ship out items from the admin backend, individual item updates result in long page stall times and buried CPUs.

**Comment by fabiode** [comment]
@StrangeWill it's a massive structure problem in Spree, Inventory Units are a nightmare for big orders. 

Some solutions has already been proposed, but not merged: https://github.com/spree/spree/pull/5776

There is a solution approached by Solidus team (which is a fork from Spree), but I never got the chance to test it: https://github.com/solidusio/solidus/pull/574

Some PR has been merged that made some difference though, but I think it's not enough: https://github.com/spree/spree/commit/0d4e9f01eb3fcc45d4a0ca52a9a1650c2a786188

As I can't change the store structure at the moment, so I'm using Sidekiq to process the items (and you should lock at least the order record) in each step. I know it's just a patch and not a real solution, but it works for now. 

I'm eager to see the day that it will be finally solved!

**Comment by priyank-gupta** [comment]
@StrangeWill What spree version are you using ? This was fixed here, https://github.com/spree/spree/pull/7222

**Comment by StrangeWill** [comment]
@priyank-gupta 3.0, and sadly due to heavy modifications we can't simply upgrade to 3.2. I'll have to check that change out and see if I can't backport it or take a serious swing at upgrading to 3.2.

**Comment by krzysiek1507** [comment]
@priyank-gupta can we backport that fix to 3.0 and 3.1?

**Comment by chileap** [comment]
Hello, I also have this problem too. But not for 1000, it appear when I try to add 5000 items in one order. Spree stop working. It freeze system and won't go anywhere.

Did anyone have solution yet?
