### ISSUE TITLE
i18n problem of 'state'

### ISSUE THREAD

**Issue by orbit-dna** [spree/spree#7534]
In these files:
1. [backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb #11](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb#L11)
  `<th class="text-center"><%= Spree.t(:state) %></th>`
2. [backend/app/views/spree/admin/shared/_address_form.html.erb #56](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/shared/_address_form.html.erb#L56-L62)
`<%= f.label :state_id, Spree.t(:state) %>`
3. [backend/app/views/spree/admin/stock_locations/_form.html.erb #80] (https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/stock_locations/_form.html.erb#L80-L84)
`<%= f.label :state_id, Spree.t(:state) %>`
4. [backend/app/views/spree/admin/stock_locations/index.html.erb #14] (https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/stock_locations/index.html.erb#L14)
`<th><%= Spree.t(:state) %></th>`

there are some `Spree.t(:state)`s, however, these *:state* have different meaning:
 - in 1 and 4, it means kind of status,
 - in 2 and 3, it means like province/country.

while the word *state* has these two meanings in English, but when translated, other language may have to use 2 words.
So, should these *:state* be split?

other files found using `Spree.t(:state)`:
  - [backend/app/views/spree/admin/shared/named_types/_index.html.erb #14](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/shared/named_types/_index.html.erb#L14)
  - [backend/app/views/spree/admin/return_authorizations/_form.html.erb #13](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/return_authorizations/_form.html.erb#L13)
  - [backend/app/views/spree/admin/return_index/return_authorizations.html.erb #50](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/backend/app/views/spree/admin/return_index/return_authorizations.html.erb#L50)
  - [frontend/app/views/spree/address/_form.html.erb #51](https://github.com/spree/spree/blob/7ca3b70ed5ac5f712435649b49f59f6b23829971/frontend/app/views/spree/address/_form.html.erb#L51)

**Comment by damianlegawiec** [comment]
@orbit-dna good catch. For `state_id` I think we can use `Spree::State.model_name.human`

**Comment by krtschmr** [comment]
That's the reason why we kept Admin in english langauge rather then german. So many things got a `Bundesland`, it was so confusing

**Comment by orbit-dna** [comment]
@damianlegawiec nice, that works for me.
@krtschmr nice idea. but our people not used to english, have to localize.

**Comment by damianlegawiec** [comment]
@orbit-dna please submit a PR with this change if you can, thanks! 👍
