### ISSUE TITLE
Master Variant not created

### ISSUE THREAD

**Issue by GarPit** [spree/spree#7540]
I create Products (importing from XLS) like this:

```
product = taxon.products.where("1c_code" => product_code).first_or_create(
  name: prepare_product_name,
  price: price,
  available_on: Time.zone.today,
  shipping_category: Spree::ShippingCategory.first
)
```

Product saved, but it has master variant as new record (id: nil) after this line

**Comment by mauazua** [comment]
hi @GarPit, thanks for reporting this issue.

**Comment by GarPit** [comment]
My current workaround:

        master_variant = product.master || product.build_master
        master_variant.product_id = product.id
        master_variant.price = price
        master_variant.save

But I guess this is not how things should happen

**Comment by mauazua** [comment]
@GarPit you wrote before, that you have a master variant, but it is not persisted - maybe you could just save the existing master variant for now? could you post here your variant and the version of Spree you are currently using?

**Comment by GarPit** [comment]
`gem 'spree', '~> 3.1.0'`
