### ISSUE TITLE
Options ain't displayed in Stock Transfer

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#7544]
Always guessing...

![image](https://cloud.githubusercontent.com/assets/13366714/17813204/940c012a-6654-11e6-8eac-b2df77064315.png)

**Comment by krtschmr** [comment]
I see in the Demo store, that the SKU is displayed. Should that be changed if no SKU is set so it returns then option values? (example doesn't use SKU)

**Comment by mauazua** [comment]
maybe we could display the option values in addition to SKU. @damianlegawiec any thoughts?

**Comment by damianlegawiec** [comment]
@mauazua 👍 

@krtschmr can you submit a PR with fix for this problem? Thanks!

**Comment by krtschmr** [comment]
@Legawiec

@mauazua


yes, i can do that - but i have no idea how to write a test. so if it's 
just extending the display, yeah, then i'm the men

**Comment by damianlegawiec** [comment]
Done via https://github.com/spree/spree/pull/7951
