### ISSUE TITLE
Promotion validity not checked on item removal

### ISSUE THREAD

**Issue by mayank111255** [spree/spree#7547]
I created a promotion 'TREBOGO' with following action and rule:

  promotion action:  Create Line Items  (adds 'Gift Bag' to cart)
  promotion rule:  Type -> Product(s) (at least one 'Polo Shirt' should be present in the cart)

Now I add 1 'Polo Shirt' to the cart and apply promo. I get a gift, that's fine as I already have at least 1 'Polo Shirt' in my cart.

But when I remove 'Polo Shirt' from the cart i.e my cart no longer has any 'Polo Shirt', the 'Gift Bag' added by the promotion still persists in the cart and the order is placed successfully.

This way the user can get a 'Gift Bag' without buying 'Polo Shirt'.

This is clear that the promotion is no longer valid as my cart does not meet promotion rule anymore.

I looked into the code and found that the case when the promotion is not eligible on the order anymore, is not handled.

Here is the snippet:

``` ruby
  def activate
    promotions.each do |promotion|
      if (line_item && promotion.eligible?(line_item)) || promotion.eligible?(order)
        promotion.activate(line_item: line_item, order: order)
      end
    end
  end
```

I could raise a PR to fix this. Please let me know.

**Comment by mauazua** [comment]
hi, @mayank111255. thank you for reporting this issue. could you make a PR with a fix? :)

**Comment by mayank111255** [comment]
hi @mauazua, I am working on this and will make a PR soon.

**Comment by wildtangent** [comment]
@mauazua did you get anywhere with this? I have an idea for it - will put in a PR and see if it is similar to your thinking

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/7705
