### ISSUE TITLE
Thiết lập an giới hạn for an PAYMENTMETHOD tối đa Amount # 7533

### ISSUE THREAD

**Issue by 0902074** [spree/spree#7560]
Chúng tôi gần đây đã có một vấn đề mà chúng tôi không muốn các đơn đặt hàng lớn beeing trả bằng thẻ tín dụng (nếu ai đó mua 20 phím chơi game và trả tiền với creditcard, có một nguy cơ cao cao của gian lận).
Vì vậy, chúng tôi hạn chế nó xuống theo cách này

 def useable_payment_methods
    Spree::PaymentMethod.available_on_front_end.reject{|x|
      x.type == "Spree::Gateway::StripeGateway" && total > 250 
    }
  end

  def available_payment_methods
    @available_payment_methods ||= useable_payment_methods
  end
Tôi nghĩ rằng, nó có thể rất hữu ích để thiết lập một số tiền tối đa trong các phụ trợ cho mỗi PAYMENTMETHOD.

Đây có phải là bằng cách nào đó quan tâm cho lõi Spree? sau đó tôi có thể làm cho một yêu cầu kéo, nếu không tôi chỉ để nó ở đây.[http://www.chuyensuadogotainha.com/2016/06/noi-that-anh-nghia0902240304-son-pu-gia.html](url)

**Comment by parhs** [comment]
Use english please.

**Comment by pravipati** [comment]
Translation attempt (via google translate) 👇 

We recently had a problem where we do not want large orders being paid by credit card ( if someone buys 20 gaming keys and pay with credit card , there is a high risk of fraud high ) .

So we limited it this way:

```
def useable_payment_methods
  Spree::PaymentMethod.available_on_front_end.reject{|x|
  x.type == "Spree::Gateway::StripeGateway" && total > 250 
}
end

def available_payment_methods
  @available_payment_methods || = useable_payment_methods
end
```

Is this somehow the core concern Spree ? then I can make a last request , if not I just leave it at day.http : //www.chuyensuadogotainha.com/2016/06/noi-that-anh-nghia0902240304-son-pu-gia.html

**Comment by mauazua** [comment]
Currently not, but this PR #7536 will add the possibility to set minimum and maximum transaction limit for each payment method.
