### ISSUE TITLE
Large orders (>600 inventory_units) long finalizing also caused by touch chain between Stock Item, Variant, Product and Taxons

### ISSUE THREAD

**Issue by fabiode** [spree/spree#7567]
Hi! I know large orders are a common problem in spree. But I noticed analyzing logs that `order.finalize!` is resulting in absolutely unnecessary touch chaining in each product taxon, making a LOT of n+1 queries during the process. When you got a few items, ok, but large orders, is one more thing to result in a 5 minutes process.

Basically it occurs this way:

`order.finalize!` inserts some StockMovements and changes count_on_hand on each StockItem, which triggers `conditional_variant_touch`, touching then the variant, the product and finally the taxons. So, for each stock movement it will touch all taxons related, if we got like 30 products on the order and all of them are in 5 taxons, I think it will make 150 updates, even if they are repeated bewteen those products.

this is the part on the log where you can see the pattern.

![image](https://cloud.githubusercontent.com/assets/916839/18297675/ce9b8ada-7488-11e6-8670-9519e8a8d9d9.png)

in https://github.com/spree/spree/blob/master/core/app/models/spree/product.rb#L359 is the touch taxon that causes these additional updates.

**Comment by codered** [comment]
@fabiode - Can you share what mode you are running in? (Dev / Prod?) Also, what are the specs of the system?

**Comment by bbonislawski** [comment]
We tried to reproduce it with current master on development and it works properly. Closing for now until we get proper reproduction steps
