### ISSUE TITLE
Support for prototypes in API?

### ISSUE THREAD

**Issue by ravensorb** [spree/spree#7574]
Is there currently support for creating prototypes programmatically?  Ideally through the API or via some sort of bulk import?

My scenario is: I have around 200 categories of products, each category has a specific set of properties/attributes.  I would like to create 1 prototype per category to make it easier to create/manage my inventory (over 20,000 items across the different categories).  I am really hoping that I do not need to manually create 200 prototypes :)

**Comment by bbonislawski** [comment]
It's quite custom feature and I'm pretty sure that everyone will need it implemented in different way.

**Comment by ravensorb** [comment]
Not sure I understand?  Wouldn't it be a matter of an api that allows a prototype to be created with a specific base type and then define a set of properties with their corresponding types?  I would think this would be rather easy and straight forward (there are a lot of other systems that support this type of thing).
