### ISSUE TITLE
Admin layout unusable in small windows (it isn't responsive)

### ISSUE THREAD

**Issue by whitmanc** [spree/spree#7584]
My guess is that this isn't exactly a top priority task, but here you go...

Also, is this something that might be good if I opened a PR for if I have some time to?
- Left sidebar menu doesn't show (the main menu for admins))
- The hamburger menu moves the content on the screen left and right (probably because the left column is hidden from view, but still being manipulated)
- The title of the page is cut off
- Hamburger menu is flush to the right of the screen, right padding should probably match left padding of the logo

<img width="402" alt="screen shot 2016-09-16 at 9 06 28 am" src="https://cloud.githubusercontent.com/assets/1023159/18592714/0d1f8aa2-7bed-11e6-9f67-2458cd18a0c8.png">

<img width="771" alt="screen shot 2016-09-16 at 9 35 27 am" src="https://cloud.githubusercontent.com/assets/1023159/18593590/f9fb3d78-7bf0-11e6-8a28-d67bd0ee8dd2.png">

**Comment by renatocn** [comment]
Hi @whitmanc, that is correct. The admin is not responsive yet.

It seems to be planned for 3.2 version, according to the roadmap:
https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016

In the meantime, I suggested a change to make admin panel usable in small devices here: #7388

**Comment by whitmanc** [comment]
@renatocn thank you for the heads up! Will close this issue since it's addressed in their roadmap

**Comment by renatocn** [comment]
Hi @whitmanc, I suggest you keep it open and address it to the version you currently use, because it is an issue.

If the good responsive comes in the 3.2 version, the past versions probably won't have it.
