### ISSUE TITLE
On checkout Delivery step let's 1) display Shipping Total amount and 2) auto-recalculate Order Total + refresh Shipping Total on Shipping Method change by user

### ISSUE THREAD

**Issue by mradfaber** [spree/spree#7585]
This is obviously confusing - on Delivery checkout step no Shipping Total amount and no auto-refresh of the Shipping Total after shipping method change:

<img width="1182" alt="screen shot 2016-09-16 at 12 44 45 pm" src="https://cloud.githubusercontent.com/assets/12614496/18594143/c7edc956-7c3e-11e6-84cb-25a419591c45.png">

I agree it’s not the best UX right now (see attached screen by eroy4u, thanks!) so we probably should fix it

On checkout Delivery step let's 1) display Shipping Total amount and 2) auto-recalculate Order Total + refresh Shipping Total on Shipping Method change by user

**Comment by krtschmr** [comment]
shipping *can't* be shown there because it's not selected. this is a weakness of spree from the beginning imo. could only be done via javascript or we need to "pre-select" a shipping rate before we go to the shipping state. 
any other thoughts?

**Comment by tanmay3011** [comment]
@mradfaber @krtschmr  I'm working on this. Will raise a PR soon.
