### ISSUE TITLE
Fresh local Spree installation: cannot login as admin

### ISSUE THREAD

**Issue by fapowell** [spree/spree#7587]
Hello,
I followed the Getting Started guide and successfully launched a seeded Spree app locally.  However, when I try to login either in the checkout or /admin, it gives me the error:

Invalid %{authentication_keys} or password.  (Looks like I have to set up i18n)

I have the default admin and then I added two more admins with `rake spree_auth:admin:create` and made different passwords for each, but I get the same error for each.  I see the three spree_users when I SELECT \* in sqlite.  Am I forgetting something here?
Thanks!
Andy

edit: I should note that this is what's in my Gemfile:

```
gem 'spree', '~> 3.1.0'
gem 'spree_auth_devise', '~> 3.1.0'
gem 'spree_gateway', '~> 3.1.0'
```

**Comment by magic-stick-420** [comment]
hey, 
need more infos... 
can you paste here log from server during login action?
