### ISSUE TITLE
Line Item with quantity equal 0

### ISSUE THREAD

**Issue by fabiode** [spree/spree#7589]
Ok, so I've been asking my self lately if there's any reason for Spree::LineItem validating quantity as integer, but no validation for greater than 0. 

In `update_cart` method, we even have a select step for line_items that quantity are greater than 0, but why not avoid this validating in the line item creation?
(https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb#L28)

I'm trying to find out, but I need some help here to understand it.

Thanks!

**Comment by priyank-gupta** [comment]
@fabiode Agreed. But not sure why this is happening.
We can keep a check on this by adding `order.line_items = order.line_items.select { |li| li.quantity > 0 }` in `after_add_or_remove` here, https://github.com/spree/spree/blob/master/core/app/models/spree/order_contents.rb#L45.
@damianlegawiec thoughts ?

**Comment by priyank-gupta** [comment]
@damianlegawiec @fabiode I am available to submit a PR regarding my suggestion above.

**Comment by bbonislawski** [comment]
Already fixed on master.
