### ISSUE TITLE
How to upload images for products using Spree Commerce REST API

### ISSUE THREAD

**Issue by bbrangeo** [spree/spree#7595]
Can you give me an example?

ex: 
curl -i -X POST -H 'X-Spree-Token: 7b9f789b3b90f66f26a62de477159fbd4950459c30b42ba1' -d 'product[name]=toto&product[price]=100&product[shipping_category_id]=1&product[description]="Description"&_**product[image]=...... ?????**_

Thanks

**Comment by vkdimitrov** [comment]
something new here?

**Comment by bbrangeo** [comment]
Hi Vladimir
I prefer to develop my own solution with symfony2. I no longer use spree.
Good luck

**Comment by vkdimitrov** [comment]
Here is the working curl, i was missing the type parameter
```
-F "type=image/jpeg" 
```
```
curl -i -X POST -H "X-Spree-Token: 6e1593067160f81bd22b7a2ba13a20920b57a0880d98c906" -H "Content-Type: multipart/form-data" -F "image[attachment]=@/home/vkdimitrov/asd.jpg" -F "type=image/jpeg" http://localhost:3001/api/v1/products/21/images 
```

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8134
