### ISSUE TITLE
Duplicated Products on Taxon display 

### ISSUE THREAD

**Issue by elsilentforce** [spree/spree#7597]
Greetings everyone,
I got this trouble using Spree 3-0, when I open any product category I see multiple pages with duplicated products. Example, some product shows on first and sixth page.

Anyone know why whis happen?

Thank you very much!

**Comment by priyank-gupta** [comment]
@elsilentforce Working fine for me on 3-0-stable. I would recommend to check your app's taxons_controller#show action for any customisation made which may cause this.

**Comment by alter-sachin** [comment]
@elsilentforce facing the same issue. Were you able to solve this ?
