### ISSUE TITLE
selected_shipping_rate_id

### ISSUE THREAD

**Issue by bonekost** [spree/spree#7600]
Hello, 
please, can somebody explain me how `selected_shipping_rate_id` parameters works?
Every order got different shipping rate ids.

How can I get selected shipping method for order?

Thanks

**Comment by priyank-gupta** [comment]
@bonekost When you transit from `address` to `delivery` step in Spree checkout, shipments are created with multiple shipping rates applicable based on the shipping methods available for that user's zone (zone is identified from shipping address given in `address` state). A user can then select a shipping rate for a particular shipment which then is marked as selected. So a shipment can have multiple shipping rates but only one selected.
Shipping rates are associated to shipping method.
- For all shipping methods, `shipment.shipping_methods`, https://github.com/spree/spree/blob/master/core/app/models/spree/shipment.rb#L22
- For selected shipping method, `shipment.shipping_method`, https://github.com/spree/spree/blob/master/core/app/models/spree/shipment.rb#L258

**Comment by bonekost** [comment]
@priyank-gupta many thanks. 
Right now I try to solve this problem: http://stackoverflow.com/questions/39817668/spree-3-1-adding-select-tag-to-shipment-form-in-delivery-step with shipment

**Comment by priyank-gupta** [comment]
@bonekost Sure.
Please close this issue if you have your query answered.
