### ISSUE TITLE
Spree::Taxon doesn't use Spree::Image for icon

### ISSUE THREAD

**Issue by whitmanc** [spree/spree#7628]
Hi folks,

I noticed that Spree:Taxon has an icon, and the way that icon is handled varies from how images are handled in Spree::Product, using Spree::Image. Should Spree::Taxon use Spree::Image for its attachment? The main reason I bring this to your attention is that when setting up to use S3 for uploads, it will not apply to taxons unless some adjustments are made. If Spree::Taxon used Spree:Image, S3 setup would work more easily.

Either way, got it working, just wanted to point it out! Feel free to close if this is non-issue. 

As a note, I did a quick-fix by simply overriding the taxon model's definition of the attachment: 

`taxon_decorator.rb`:

```
Spree::Taxon.class_eval do
  ...

  has_attached_file :icon,
    s3_credentials: {
      access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      bucket:            ENV['S3_BUCKET_NAME']
    },

    storage:        :s3,
    s3_headers:     { "Cache-Control" => "max-age=31557600" },
    s3_protocol:    "https",
    bucket:         ENV['S3_BUCKET_NAME'],
    url:            ":s3_domain_url",

    styles: {
        mini:     "48x48>",
        small:    "100x100>",
        product:  "240x240>",
        large:    "600x600>"
    },

    path:           "/:class/:id/:style/:basename.:extension",
    default_url:    "/:class/:id/:style/:basename.:extension",
    default_style:  "product"

    ##
    # The code below is what was overwritten above
    #  to support uploads to S3.
    ##
    # styles: { mini: '32x32>', normal: '128x128>' },
    # default_style: :mini,
    # url: '/spree/taxons/:id/:style/:basename.:extension',
    # path: ':rails_root/public/spree/taxons/:id/:style/:basename.:extension',
    # default_url: '/assets/default_taxon.png'
end
```

**Comment by danielstrimpel** [comment]
I don't know if this is still relevant but taxon.rb still handles icons without reference to the Image class, unlike products.rb. Maybe someone can clarify the logic behind that, vis-a-vis S3 and otherwise?
