### ISSUE TITLE
spree install error: "rails g spree:install --user_class=Spree::User" not doing anything

### ISSUE THREAD

**Issue by mimani** [spree/spree#7635]
Hi,

I have create a new rails app using this command:

`rails new store`

rails version is: 4.2.

Ruby Version: 
`rvm rubies

   ruby-2.1.2 [ x86_64 ]
   ruby-2.2.0 [ x86_64 ]
=* ruby-2.2.2 [ x86_64 ]`

Following is the Gemfile: 

     source 'https://rubygems.org'
     # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
     gem 'rails', '~> 4.2.6'
     # Use sqlite3 as the database for Active Record
     gem 'sqlite3'
     # Use Puma as the app server
     gem 'puma', '~> 3.0'
     # Use SCSS for stylesheets
     gem 'sass-rails', '~> 5.0'
     # Use Uglifier as compressor for JavaScript assets
     gem 'uglifier', '>= 1.3.0'
     # Use CoffeeScript for .coffee assets and views
     gem 'coffee-rails', '~> 4.2'
     # See https://github.com/rails/execjs#readme for more supported runtimes
     # gem 'therubyracer', platforms: :ruby
     
     # Use jquery as the JavaScript library
     gem 'jquery-rails'
     # Turbolinks makes navigating your web application faster. Read more:                     https://github.com/turbolinks/turbolinks
     gem 'turbolinks', '~> 5'
     # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
     gem 'jbuilder', '~> 2.5'
     # Use Redis adapter to run Action Cable in production
     # gem 'redis', '~> 3.0'
     # Use ActiveModel has_secure_password
     # gem 'bcrypt', '~> 3.1.7'

     # Use Capistrano for deployment
     # gem 'capistrano-rails', group: :development

     group :development, :test do
       # Call 'byebug' anywhere in the code to stop execution and get a debugger console
       gem 'byebug', platform: :mri
     end
     
     group :development do
       # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
       gem 'web-console'
       gem 'listen', '~> 3.0.5'
       # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
       gem 'spring'
       gem 'spring-watcher-listen', '~> 2.0.0'
     end

     gem 'spree', '~> 3.1.0'
     gem 'spree_auth_devise', '~> 3.1.0'
     gem 'spree_gateway', '~> 3.1.0'

     # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
     gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Bundle install works fine, But when I try to follow [getting started](https://github.com/spree/spree#getting-started) and run this command

`rails g spree:install --user_class=Spree::User`

Nothing happens at all.

Please let me know what can be wrong?

**Comment by mimani** [comment]
I figured out what the problem was:

I had to create a rails app with 4.2.6 version of rails, using following command:
 
    rails _4.2.6_ new store

When I was just running `rails new store`, it used to create dependency using rails 5 version, which was breaking with spree.

**Comment by acrolink** [comment]
I am having the exact same issue now when using Rails 6.0.0. and PostgreSQL. When using default SQLite, it works.
