### ISSUE TITLE
[spree-2.4] high memory with puma after several days up

### ISSUE THREAD

**Issue by u007** [spree/spree#7640]
can eat up to 800+mb before i restart the instance,
my puma configurations:
threads, [2, 12]
worker: 1

**Comment by damianlegawiec** [comment]
Hi @u007 you can play around with puma configuration (https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) and look at tools like:

https://github.com/schneems/puma_worker_killer
