### ISSUE TITLE
problem with migration renaming /20150314013438_add_missing_indexes.rb

### ISSUE THREAD

**Issue by blset** [spree/spree#7641]
commit a3d4e792ee61703f55fb657d2cb6780792b39b29

this rename clashes in the following way :

spree_promotion_rules_users have been renamed to spree_promotion_rule_users (no s) in a later migration

when updating spree from 3.1. beta to 3.1 stable, the message missing migration shows up 
[Spree WARNING] Missing migrations.
[Spree WARNING] add_missing_indexes_on_spree_tables from spree is missing.
[Spree WARNING] Run bundle exec rake railties:install:migrations to get them.

and if I install the new migration, it chokes because spree_promotion_rules_users does not exist anymore

so i just deleted this migration but cannot get rid of the missing migration message now

why the clash with other gem ? was the filename of the two migrations exactly the same, I guess no, what was the conflict ?

**Comment by niharika88** [comment]
working on it

**Comment by AnuragBhardwaj1** [comment]
I think it has been fixed here: https://github.com/spree/spree/pull/7796
