### ISSUE TITLE
AdjustmentsUpdater persist_totals issue

### ISSUE THREAD

**Issue by jkelleyj** [spree/spree#7643]
I'm working on some custom adjustments and came across this bit in the AdjustmentsUpdater
Maybe this is just old code that got left behind, but it seems that this code will fail to set the updated at timestamp or the adjustment_total because attributes is never used.

https://github.com/spree/spree/blob/master/core/app/models/spree/adjustable/adjustments_updater.rb#L29

```
def persist_totals(totals)
  attributes = totals
  attributes[:adjustment_total] = totals[:non_taxable_adjustment_total] +
                                        totals[:taxable_adjustment_total] +
                                        totals[:additional_tax_total]
  attributes[:updated_at] = Time.current
  @adjustable.update_columns(totals)
end
```

The adjustment total is later set on the Order object (the one I actually care about at the moment) via the OrderUpdater, but we should clean this up one way or the other.

**Comment by tanmay3011** [comment]
@jkelleyj It will update the timestamp as `attributes` will carry the reference of `totals` hash and any key-value pair added to `attributes` hash will also be reflected on the `totals` hash.

**Comment by jkelleyj** [comment]
@tanmay3011 ah, I see, totally missed that.  you're right.  Why not call update_columns with attributes to be less confusing to the reader?

**Comment by tanmay3011** [comment]
@jkelleyj That won't fix anything. But for the readability purpose, we would consider changing it in future.
