### ISSUE TITLE
Unclear/Outdated documentation on setting promotion events.

### ISSUE THREAD

**Issue by hxegon** [spree/spree#7647]
I've been trying to get a free shipping promotion to automatically apply for a while now, and after much research I figured out that you have to keep the 'code' and 'path' fields empty. I found this out by reading the promotion user guide, figuring out that it's section on 'event names' (and screenshots) are outdated, and then googling through change logs (A spree 2.2something changelog explains the change).

I would be happy to submit a PR myself if the user guide is in a repo, just point me in the right direction.

**Comment by danielstrimpel** [comment]
The screenshot and explanation is still out of date. 

Unless I hear otherwise, I will fix this and submit a PR with an updated file: guides/content/user/promotions.md

**Comment by damianlegawiec** [comment]
Should be fixed via https://github.com/spree/spree/pull/8256

**Comment by hxegon** [comment]
Sorry about not closing this myself, just saw the notification email buried in my inbox. Thanks @wojtekwisniewski, @damianlegawiec 🍻
