### ISSUE TITLE
Rails 5 Rabl hack needs updating/removing

### ISSUE THREAD

**Issue by aaronrussell** [spree/spree#7649]
Trying the 3.2.beta in a Rails 5 app, the app won't initialise due to this hack:

https://github.com/spree/spree/blob/master/api/config/initializers/rails5_rabl_hacks.rb

Rabl is now it version 0.13.1.

I don't know the story behind that hack, but it either needs to be removed or the version conditional updated.

Temporary _solution_ is to explicitly set `gem 'rabl', '0.13.0'` in gemfile.

**Comment by tanmay3011** [comment]
@aaronrussell Working on it. Rabl was recently bumped to 0.13.1, Will provide a fix soon.
