### ISSUE TITLE
Could not sort by SKU

### ISSUE THREAD

**Issue by tranhv** [spree/spree#7658]
Hi,

I use spree 3.1.0.
I trying to sort by sku. I use `GET /api/products?q[s]=sku%20asc` but it didn't work.
Then i use GET /api/products?q[s]=master_sku%20asc and i get error
`
PG::InvalidColumnReference: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 1: ...ble_on <= '2016-10-28 16:48:28.685733') ORDER BY "spree_var... ^ : SELECT DISTINCT "spree_products".* FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".discontinue_on IS NULL or "spree_products".discontinue_on >= '2016-10-28 16:48:28.685588') AND ("spree_products".discontinue_on IS NULL or "spree_products".discontinue_on >= '2016-10-28 16:48:28.685742') AND ("spree_products".available_on <= '2016-10-28 16:48:28.685733') ORDER BY "spree_variants"."sku" ASC LIMIT 25 OFFSET 0
`

Could you help me?

Thanks,

**Comment by rsiddle** [comment]
@tranhv you should be sorting the results from the API on your client rather than on the API endpoint. JSON structures do not maintain ordering for Arrays.

**Comment by nut707** [comment]
http://stackoverflow.com/questions/40689750/sorting-in-spree/40691867#40691867 may be this can help you
