### ISSUE TITLE
Change default store

### ISSUE THREAD

**Issue by bonekost** [spree/spree#7677]
Could someone please help me with changing default store in Spree 3.1 migration?
After a few tries I can't figured out what this code in migration do:
```
Spree::Store.new do |s|
        s.name              = preference_store.get 'spree/app_configuration/site_name' do
          'Spree Demo Site'
        end
        s.url               = preference_store.get 'spree/app_configuration/site_url' do
          'demo.spreecommerce.com'
        end
        s.mail_from_address = preference_store.get 'spree/app_configuration/mails_from' do
          'spree@example.com'
        end

        s.meta_description = preference_store.get('spree/app_configuration/default_meta_description') {}
        s.meta_keywords    = preference_store.get('spree/app_configuration/default_meta_keywords') {}
        s.seo_title        = preference_store.get('spree/app_configuration/default_seo_title') {}
        s.default_currency = preference_store.get('spree/app_configuration/currency') {}
        s.code             = 'spree'
      end.save!
```
I tried to change name in migration and even in core gem but nothing... after `db:migrate` there is still store with name "Spree Demo Site". From where??
Many thanks

**Comment by tanmay3011** [comment]
@bonekost You can change your store name from admin end -> Configurations -> General Settings

**Comment by bonekost** [comment]
@tanmay3011 no no you don't understand me... I need to change it by first migration. I know I can change it in admin

**Comment by rsiddle** [comment]
@bonekost Try exporting your database and searching for that string within the database dump.

**Comment by bonekost** [comment]
I just delete `preference_store.get 'spree/app_configuration/some_config'`  because I didn't find out from where Spree get values  and changed whole migrations with needed values.
