### ISSUE TITLE
undefined method `manual_entry' for Spree::CreditCard

### ISSUE THREAD

**Issue by bpuklich** [spree/spree#7682]
Using the Spree 3-1-stable I'm getting an undefined method manual_entry for Spree::CreditCard when checking out using Authorize.net as a gateway. ActiveMerchant 1.61.0 now uses an accessor called manual_entry in ActiveMerchant::Billing::CreditCard. I believe commit 282fdb7f1ac92492533329dc57c5bdeaa1090cac for ActiveMerchant added this use to the Authorize.net gateway.

Attached is the head of the stack trace.

```
F, [2016-11-15T17:49:29.257272 #12493] FATAL -- : 
NoMethodError (undefined method `manual_entry' for #<Spree::CreditCard:0x007fc7baf95590>):
  activemodel (4.2.7.1) lib/active_model/attribute_methods.rb:433:in `method_missing'
  activemerchant (1.61.0) lib/active_merchant/billing/gateways/authorize_net.rb:430:in `add_market_type_device_type'
  activemerchant (1.61.0) lib/active_merchant/billing/gateways/authorize_net.rb:215:in `block in add_auth_purchase'
  nokogiri (1.6.8.1) lib/nokogiri/xml/builder.rb:391:in `call'
  nokogiri (1.6.8.1) lib/nokogiri/xml/builder.rb:391:in `insert'
  nokogiri (1.6.8.1) lib/nokogiri/xml/builder.rb:375:in `method_missing'

```

**Comment by vishalzambre** [comment]
@bpuklich @damianlegawiec  I verified above issue, Sending PR regarding same.

**Comment by calebyk** [comment]
I have the same problem..
could you mention more detail about creating decorator.. example.. where it should be located. what is the file name.. etc..
thank you in advance..

**Comment by calebyk** [comment]
create a decorator file and add the content on the file..
mystore/app/models/spree/credit_card_decorator.rb

module Spree
  CreditCard.class_eval do
    include ActiveMerchant::Billing::CreditCardMethods
  
    def manual_entry   
    end

  end
end
