### ISSUE TITLE
string contains null byte in CreateStoreFromPreferences

### ISSUE THREAD

**Issue by deepakm-webonise** [spree/spree#7690]
I am getting:

>  string contains null byte

in CreateStoreFromPreferences migration

    == 20161109154093 CreateStoreFromPreferences: migrating =======================
    rake aborted!
    StandardError: An error has occurred, this and all later migrations canceled:

    string contains null byte
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `block in _create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:142:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
    /home/deepak/workspace/Project/db/migrate/20161109154093_create_store_from_preferences.spree.rb:35:in `change'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
    ArgumentError: string contains null byte
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `block in _create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:142:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
    /home/deepak/workspace/Project/db/migrate/20161109154093_create_store_from_preferences.spree.rb:35:in `change'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    /home/deepak/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => db:migrate
    (See full trace by running task with --trace)

The problem is 

    Spree::Store.new do |s|
      s.name = preference_store.get 'spree/app_configuration/site_name' do
        'Spree Demo Site'
      end
      #...
    end

The value in `s.name` is `"\x04\bI\"\x0EMY SHOP\x06:\x06EF"`

**Comment by vishalzambre** [comment]
@deepakm-webonise  Did this error thrown with fresh setup of spree?

**Comment by deepakm-webonise** [comment]
@vishalzambre No, I am getting this error only while upgrading my existing application.

I think it's because I already have values in configuration while in fresh setup it sets the value from the block

    s.name = preference_store.get 'spree/app_configuration/site_name' do
      'Spree Demo Site'
    end

**Comment by priyank-gupta** [comment]
@deepakm-webonise Above code will only pick value from block if there is not preference defined for `spree/app_configuration/site_name`. So, as you said that you already have values for these configurations it seems like you have them in some format other than UTF-8.
Try cleaning/correcting that config and rerun the migration.
