### ISSUE TITLE
#9c2307ae was omitted in 3.1-stable!

### ISSUE THREAD

**Issue by gcauchon** [spree/spree#7693]
We've been working on a ecomm website for some weeks now. It came too our attention the shipping related values have been creeping slowly each time changes were made to a Product when the Admin was used in locale other than `:en`. Another clue was those same fields were displayed in a `.` decimal format instead of the `locale`'s `,`!

![spree_product_form](https://cloud.githubusercontent.com/assets/801045/20453079/53c225e6-ade8-11e6-80ab-569a1477a933.gif)

We found the problem to be caused by the missing `number_with_precision` in [`admin/products/_form.html.erb#L110-L138`](https://github.com/spree/spree/blob/3-1-stable/backend/app/views/spree/admin/products/_form.html.erb#L110-L138)...

# The fix already exists in `master`...

However, we soon after realized the issue have been fixed in `master` a long time ago, but the fix [#9c2307ae](https://github.com/spree/spree/tree/9c2307ae6e7361b0cb3b7bfd8ea74615bde59820) was never merged to the current stable `branch`...

**Comment by damianlegawiec** [comment]
@gcauchon we'll backport this fix in `3.1.3` next week :)

**Comment by damianlegawiec** [comment]
@gcauchon backported to `3-1-stable`
