### ISSUE TITLE
column spree_promotion_actions.deleted_at does not exist in UpgradeAdjustments

### ISSUE THREAD

**Issue by deepakmahakale** [spree/spree#7697]
I am currently upgrading **Spree 2.1** to **Spree 2.2**. I got the following error in [**`db/migrate/20130807024301_upgrade_adjustments.rb`**](https://github.com/spree/spree/blob/2-2-stable/core/db/migrate/20130807024301_upgrade_adjustments.rb)

    PG::UndefinedColumn: ERROR:  column spree_promotion_actions.deleted_at does not exist
    LINE 1: ..._actions".* FROM "spree_promotion_actions"  WHERE "spree_pro...
                                                             ^
    : SELECT  "spree_promotion_actions".* FROM "spree_promotion_actions"  WHERE "spree_promotion_actions"."deleted_at" IS NULL AND "spree_promotion_actions"."id" = $1 LIMIT 1

and the migration to add `deleted` column is [**`db/migrate/20140609201656_add_deleted_at_to_spree_promotion_actions.rb`**](https://github.com/spree/spree/blob/2-2-stable/core/db/migrate/20140609201656_add_deleted_at_to_spree_promotion_actions.rb) there are 30+ migrations in between

**Comment by elfedy** [comment]
I think this is the same issue as [#5152](https://github.com/spree/spree/issues/5152)
