### ISSUE TITLE
spreecommerce.org down?

### ISSUE THREAD

**Issue by Inkybro** [spree/spree#7700]
Probably not at all the right place to report this, but I don't know where would be the correct place.

I'm trying to access the links http://guides.spreecommerce.org/creating_extensions.html & http://guides.spreecommerce.org/testing.html

I cannot access these links. I'm getting 403 Forbidden on both.

I may be jumping the gun by posting here (hope I'm not.) Is this a simple, temporary issue with the spreecommerce.org site? Are you guys, here, even affiliated with that site?

I really need to read those pages. Any ideas?

**Comment by mauazua** [comment]
hi @Inkybro, I believe you have outdated links. Is this what you are looking for?
[testing](http://guides.spreecommerce.org/developer/testing.html)
[extensions](http://guides.spreecommerce.org/developer/extensions_tutorial.html)
