### ISSUE TITLE
wrong number of arguments (given 3, expected 1)

### ISSUE THREAD

**Issue by catalin88** [spree/spree#7713]
I randomly keep getting this error, on more than one page:

```
ArgumentError in Spree::CheckoutController#update

wrong number of arguments (given 3, expected 1)

Extracted source (around line #133):
def instance_delegate(hash)
    hash.each{ |methods, accessor|
      methods = [methods] unless methods.respond_to?(:each)
      methods.each{ |method|

Parameters:
{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"5NQdEN7DZuepEobprlE3nQok0va517C+oftsoLqe8uL5DCv3pVmS9PMItV5BnEH+x+AXh3pt5K+1p+X5mzunuw==",
 "order"=>{"email"=>"noreply@gmail.com",
 "state_lock_version"=>"0",
 "bill_address_attributes"=>{"firstname"=>"Catalin",
 "lastname"=>"Catalin",
 "address1"=>"Catalin,
 nr 2",
 "city"=>"City",
 "country_id"=>"1",
 "state_name"=>"Something",
 "zipcode"=>"000000",
 "phone"=>"000000",
 "id"=>"13"},
 "use_billing"=>"1",
 "ship_address_attributes"=>{"id"=>"14"}},
 "commit"=>"Salvează și continuă",
 "save_user_address"=>"1",
 "state"=>"address"}
```

If I restart the server and then refresh the page, everything goes fine. But in production this is not acceptable
Any ideas ?

**Comment by priyank-gupta** [comment]
@catalin88 More info please. Backtrace will help.

**Comment by catalin88** [comment]
@priyank-gupta Can you give me a more specific hint on how to do this ? On this particular error, I don't even get a console at the bottom... Might be silly what I'm saying, but literally have no idea where to start, so anything would help

**Comment by bonekost** [comment]
@catalin88 I had same problem and I found out it was because I used buybug...

**Comment by catalin88** [comment]
@bonekost Can you tell me how you found out it was `byebug`, the process behind it, so I can make sure this is my problem as well ? And actually, how did you solve it ? Because other gems (`oauth`) depend on `byebug`, so did you simply uninstalled `byebug` and all gems that had it as a dependency, or found another solution ? All input is appreciated!

**Comment by catalin88** [comment]
@priyank-gupta So I have found some additional info:

```
ArgumentError (wrong number of arguments (given 3, expected 1)):
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/forwardable.rb:133:in `instance_delegate'
  spree_core (3.1.2) app/models/spree/stock/content_item.rb:12:in `block in <class:ContentItem>'
  activesupport (4.2.6) lib/active_support/core_ext/object/with_options.rb:67:in `instance_eval'
  activesupport (4.2.6) lib/active_support/core_ext/object/with_options.rb:67:in `with_options'
```

This is where it's called: https://github.com/spree/spree/blob/master/core/app/models/spree/stock/content_item.rb

```
with_options allow_nil: true do
        delegate :line_item,
                 :variant, to: :inventory_unit
```

**Comment by lsantobuono** [comment]
Have you tried skipping the  delivery state by commenting it in the checkout_flow instead of deleting it?


```
module Spree
  Order.class_eval do

    checkout_flow do
      go_to_state :address
      go_to_state :confirmar, if: ->(order) { !order.creado_por_admin? }
      # go_to_state :delivery
      go_to_state :confirm
      go_to_state :confirm, if: ->(order) { order.confirmation_required? }
      remove_transition from: :delivery, to: :confirm
    end
```

**Comment by brsoff** [comment]
We had this issue after adding the gem [spree_print_invoice](https://github.com/spree-contrib/spree_print_invoice) to our project (Rails 5.0.1 / Spree 3.2.0.rc1).

The fix was to remove/overwrite references to the`Forwardable` module and any of its methods (ex. `def_delegators`) in the vendor code and replace it with `ActiveSupport`'s `delegate` method. 

There is some more in-depth discussion here about the cause:

https://github.com/elastic/elasticsearch-rails/issues/6
https://github.com/cequel/cequel/issues/193

**Comment by rdaniels** [comment]
> @catalin88 I had same problem and I found out it was because I used buybug...

Removing pry-byebug worked for me, seems like this error is gone
