### ISSUE TITLE
consider adding Github Issue Template??

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7720]
Has the core team considered an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)? 

The [guidelines for contributing](https://github.com/spree/spree/blob/master/CONTRIBUTING.md) fit nicely into a template. 

I'd be glad to submit a PR.

**Comment by damianlegawiec** [comment]
@joshRpowell sure! Please submit a PR :)

**Comment by joshRpowell** [comment]
@damianlegawiec will do!
