### ISSUE TITLE
removing Admin::RootController breaks redirect when mounted in a subdirectory

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7722]
## Context

We have spree mounted: 
```ruby
mount Spree::Core::Engine, at: '/store'
```
Removing Admin::RootController [here](https://github.com/spree/spree/commit/2f28b6dc20cdbb6bac02d08d7cb2ee5711d57ede#diff-7c6d89956aa66bc9ee5dc2edd38e026dR185) in PR #7445 results in a broken redirect when upgrading from 3.1.2 to Master

## Expected Behavior

On **3.1.2** redirects from `Spree.admin_path` go to `/store/admin/orders`

## Actual Behavior

On **Master** redirects from `Spree.admin_path` go to `/admin/orders` failing to recognize the engine scope at: `/store`

## Possible Fix

No sure one is needed.  Am I missing a config option that was introduced as a result of the change in #7445? 

Our monkey patch was to replace:
```ruby
get Spree.admin_path, to: redirect(Spree.admin_path + '/orders'), as: :admin
```
 with
```ruby 
get Spree.admin_path, to: 'admin/orders#index', as: :admin 
```

## Steps to Reproduce

1.  Upgrade an app with Spree mounted as an engine from 3.1.2 to Master
2.  Test Spree.admin_path links
3.  Observe engine scope is ignored, redirecting to `admin/orders`

## Your Environment

* Version used: 3.1.2 upgrading to Master
* Gemfile and Gemfile.lock as text in a Gist: [Gemfile](https://gist.github.com/joshRpowell/c3b0ea13b1f1b96c5e5fe979e0df7e75), [Gemfile.lock](https://gist.github.com/joshRpowell/2b399fef45cda246a1704148b22af956)
* Any relevant stack traces ("Full trace" preferred): none

**Comment by damianlegawiec** [comment]
Thanks @joshRpowell for reporting 👍
