### ISSUE TITLE
As an admin I cannot edit guest user addresses in admin/orders

### ISSUE THREAD

**Issue by ubudzisz** [spree/spree#7729]
## Context
As an Admin, I should be able to update guest user data.

## Expected Behavior
Data should be updated.

## Actual Behavior
I go message `User not found` (tested on spree 3.1 i 3.2.)
![update](https://cloud.githubusercontent.com/assets/9639111/20882148/d6d5e388-badf-11e6-9cf4-c8cd0148578a.png)

## Steps to Reproduce
1.Create guest checkout.
2.Log as an Admin and update guest user data.

**Comment by priyank-gupta** [comment]
@ubudzisz Submitted a fix for this.

**Comment by askl56** [comment]
@priyank-gupta can you please reference the commits when fixes are made?
