### ISSUE TITLE
Store Credit creates a duplicate zero dollar payment against Existing Credit Card preventing checkout

### ISSUE THREAD

**Issue by jkelleyj** [spree/spree#7732]
## Context
When checking out and using store credit to completely pay for an order, a second payment is created for zero dollars and that payment method (I think this will be whatever is actually selected in the normal payment form) will be processed against the gateway.  This causes no issues for the bogus gateway because a zero dollar payment is acceptable, but for some gateways (like Authorize.Net CIM) this will raise an exception as zero does not fit within their API's XSD (min value is greater than 0).

When applying a store credit to completely pay for an order, it should not add a second payment to the order when running the update on the checkout controller.  This would allow the order to proceed forward without processing the second payment.

## Expected Behavior
Order should be completed (or move to confirm) with a single payment from the Store Credit that is the full amount of the order.

## Actual Behavior
A correct payment is created for the Store Credit, but a second payment with a zero dollar total is created based on whatever remains on the payment form below the Store Credit block.

## Possible Fix
Ideas:
A. take measures on the update action to remove other payment attributes when the store credit completely covers the order 
B. on Spree frontend, handle selection of payment type whenever applying a Store Credit.  If the full amount is covered, the frontend JS could deselect any existing cards so that it does not try to bill that card.
B. fix gateways such that they handle zero dollar totals gracefully.

I'd prefer A, since in (B) the JS seems error prone as stores are customized and in (C) the zero dollar payments agains a credit card are misleading.  I believe A could be accomplished by replacing:
```
# Remove other payment method parameters.
params[:order].delete(:payments_attributes)
params.delete(:payment_source)
```
with:

```
# Remove other payment method parameters.
params[:order].delete(:payments_attributes)
params[:order].delete(:existing_card)  
params.delete(:payment_source)
```

## Steps to Reproduce
Using the basic spree 3.1 installation,
1. Given a user with an existing payment source (credit card) and the Authorize.Net CIM gateway as the payment source
2. Add $50 of store credit for the user in the admin
2. Buy something worth less than $50
3. At the payment step choose to apply Store Credit
4. You should remain on the payment step and see an Authorize.Net exception with text similar to the following:
The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:amount' element is invalid - The value '0.00' is invalid according to its datatype 'Decimal' - The MinInclusive constraint failed.
If you examine the order in console, you will see two payments and the order will 

## Your Environment

* Version used: 3.1.1

**Comment by jkelleyj** [comment]
I just tested this with a checkout decorator and it does indeed fix the issue.  I'll submit a quick PR if that's helpful.  I haven't contributed to this repo before, so please advise if I should dev the PR against a branch other than master

**Comment by priyank-gupta** [comment]
@jkelleyj Not able to replicate this. This is handled via https://github.com/spree/spree/commit/ec15e93f.
Same commit is available on version 3.1.1.

Let me know if I am missing something here.

**Comment by damianlegawiec** [comment]
@jkelleyj please submit PR against master and we'll backport it to `3-1-stable`, thanks!

**Comment by jkelleyj** [comment]
Hey @priyank-gupta I just submitted a PR - this only applies when using an existing card as the payment source.  You'll only see the issue if you have a payment method that balks at a zero total payment (like auth.net CIM).  The other place you'll see it with a payment method that allows a zero total payment is a second payment of $0 amount.
