### ISSUE TITLE
Two promotion codes can be applied and lead to minus order sum.

### ISSUE THREAD

**Issue by karolfraczkowski** [spree/spree#7734]
Issue affects spree 3.2 and 3.1
![spree demo site](https://cloud.githubusercontent.com/assets/23167379/20919255/29663196-bb9b-11e6-9837-3b87c6ad0986.png)

**Comment by niharika88** [comment]
i can take this up?

**Comment by damianlegawiec** [comment]
@niharika88 sure!

**Comment by AnuragBhardwaj1** [comment]
@karolfraczkowski  Can you please specify step to replicate ?

**Comment by vaidashi** [comment]
Hi there! @djtrujillo and I are first-time contributors and were hoping to help out with this issue. We noticed nobody was assigned to it, but if there’s already a solution in progress we're happy to try helping out elsewhere. Thanks!
