### ISSUE TITLE
Adding PaymentRequest API support

### ISSUE THREAD

**Issue by madmath** [spree/spree#7741]
Would it be possible to support the PaymentRequest API in Spree?

Most browsers have committed to implement it, with support being landed in Edge, Chrome, Opera, Firefox. It doesn't require new payment processors; it's a different UI meant to replace forms.

Let me know what you think.

Web Payments API W3C spec: https://w3c.github.io/browser-payment-api/

Browser support:
Edge
https://twitter.com/RReverser/status/804451484758749184

Chrome (shipping to all users)
https://developers.google.com/web/updates/2016/07/payment-request

Firefox
https://github.com/mozilla-payments/

**Comment by damianlegawiec** [comment]
Spree Gateway 3.4.0 supports Stripe Payment Request API implementation:
https://github.com/spree/spree_gateway/releases/tag/v3.4.0
