### ISSUE TITLE
Reimbursment mailer is text only, lacking HTML view

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#7744]
## Expected Behavior
Should render nice HTML email

## Actual Behavior
![screen shot 2016-12-07 at 17 07 34](https://cloud.githubusercontent.com/assets/55154/20975764/baa1a018-bca0-11e6-927f-77e5d4080ac5.png)

## Your Environment

* Version used: Spree 3.1

**Comment by mohsen-alizadeh** [comment]
![reimbursement_email_html](https://cloud.githubusercontent.com/assets/4325532/23466633/eee35f40-feb0-11e6-9022-9894424a931a.png)

I added a nice HTML template for it
