### ISSUE TITLE
pre_tax_amount on line_items is always zero

### ISSUE THREAD

**Issue by catalin88** [spree/spree#7749]
Something weird is going on. On all orders each line_item has its pre_tax_amount equal to zero.

Unless, and this is the weird part, I copy this file https://github.com/spree/spree/blob/master/core/app/models/spree/tax_rate.rb to my app /models/spree directory, then the pre_tax_amount gets updated just fine.

No idea why that is...

**Comment by priyank-gupta** [comment]
@catalin88 Please share you `Gemfile`. I think some other extension is overriding `TaxRate` class to introduce this issue.

**Comment by jkelleyj** [comment]
@priyank-gupta this is related to #7357 Items that did not have a tax rate never had their pre_tax_amount set.  FYI this impacts return authorizations, as any item with a zero dollar pre_tax_amount will lead to a zero dollar amount suggested on the return auth form in the admin.  In looking at spree 3.1 this commit does not seem to be backported.

**Comment by priyank-gupta** [comment]
@jkelleyj Seems like it.
@damianlegawiec We should include this with 3.2.x ?

**Comment by jkelleyj** [comment]
Hey @priyank-gupta, @damianlegawiec it was already pulled into 3.2 from what I can see.  What's the policy for backporting things like this to 3-1-stable?
