### ISSUE TITLE
How to override include Spree::Core::NumberGenerator in 3.1+

### ISSUE THREAD

**Issue by joeswann** [spree/spree#7750]
So before 3.1 it was possible to control the order number settings by overriding the generate_number function. Since then it has been updated to an include of `NumberGenerator`.

What is the best way to override the settings for this include? In this case I just want to replace the first line below with the second.

```
include Spree::Core::NumberGenerator.new(prefix: 'R')
include Spree::Core::NumberGenerator.new(prefix: 'R', length: 6)
```

I'm having some trouble finding the 'Rails way' of doing this within class_eval.

**Comment by joeswann** [comment]
Not entirely related but also, how would I generate a new order number without calling save? For example inside `empty!`

**Comment by joeswann** [comment]
Okay so this appears to work, but it also means anything else that might want to update the order number (eg inside empty!) needs to also have the prefix and number setting instead of `Spree::Order.number_generator`. Doesn't feel right somehow?

```
before_validation(on: :create) do
    self.number = Spree::Core::NumberGenerator.new(prefix: 'R', length: 6).send(:generate_permalink, Spree::Order)
  end
```

**Comment by joeswann** [comment]
@damianlegawiec is this a solved problem or just not important?

**Comment by achilles-tee** [comment]
I came across this issue.
I found an answer on Stackoverflow. I shared it here, just in case someone needs it in the future.
https://stackoverflow.com/a/40388800

I added the following source code in OrderDecorator instead of NumberGenerator so it just overwrote the order's number instead of whole system NumberGenerator.

```
    def generate_permalink(host)
      new_candidate(host)
    end

    def new_candidate(host)
      max_number = host.maximum(:number) || STARTING_NUMBER
      'R' + (max_number.gsub('R', '').to_i + 1).to_s
    end
```
