### ISSUE TITLE
Update friendly_id to 5.2 for proper Rails 5 support

### ISSUE THREAD

**Issue by ezekg** [spree/spree#7756]
When trying to use the latest version of friendly_id along with Spree 3.2.0.rc1 using Rails 5, I get the following dependency error:

```
Bundler could not find compatible versions for gem "friendly_id":
  In Gemfile:
    friendly_id (~> 5.2.0)

    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc1, which depends on
      spree_core (= 3.2.0.rc1) was resolved to 3.2.0.rc1, which depends on
        friendly_id (~> 5.1.0)
```

Gemfile:

```ruby
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg'
gem 'puma', '~> 3.0'
gem 'rack-attack'
gem 'rack-cors'
gem 'spree', '~> 3.2.0.rc1'
gem 'friendly_id', '~> 5.2.0'
```

Version 5.1 of friendly_id has [issues](https://github.com/norman/friendly_id/issues/755) with finder methods, [which is resolved in the latest release](https://github.com/norman/friendly_id/issues/766). This doesn't effect Spree since internally it's using `friendly.find()`, but it limits 5.2 from being used.

Do you want me to provide a pull request to update friendly_id to 5.2?

**Comment by damianlegawiec** [comment]
@ezekg thanks for reporting this - please submit a PR 👍
