### ISSUE TITLE
Spree add admin user in apartment gem tenant

### ISSUE THREAD

**Issue by nwoow** [spree/spree#7757]
Hey I have installed a spree and on top of that  have created a tenant using apartment gem each tenant has different db in mysql. I can access a general login area but How can I create an admin user in my case. And which table I need to edit to make normal user admin. Thanks for reply

**Comment by damianlegawiec** [comment]
@nwoow please ask such questions on our slack channel (http://slack.spreecommerce.com) , issues are only for reporting bugs/suggestions etc
