### ISSUE TITLE
Expose 'meta_title' and 'meta_description' for Spree::Taxon in API

### ISSUE THREAD

**Issue by vernondegoede** [spree/spree#7765]
We're using the Spree API for all of our projects. We noticed that `meta_description` and `meta_title` are missing in the taxon RABL.

We currently fixed this by pushing `meta_title` and `meta_description` manually in the spree.rb initializer. It would be great if this would be exposed by default though.

## Expected Behavior
I expect the meta_title and meta_description to be exposed using a taxon "show" call.

## Actual Behavior
Not present. :-(

## Possible Fix
I added meta_title and meta_description to the API helpers for `Spree::Taxon`.

## Steps to Reproduce
1.  `curl http://ethnicchic.backend.coqtailtest.com/shop/api/v1/taxons | python -m json.tool`

## Your Environment

* Version used: 3.3.0.alpha

**Comment by damianlegawiec** [comment]
@vernondegoede nice catch, please submit a PR today and it will make it way to `3.2.0` release 👍

**Comment by vernondegoede** [comment]
@damianlegawiec I submit a PR but some backend tests are failing and I can't figure out how to make them pass. I added the attributes to the API specs, which are now passing. Could you help me fix those tests? :)

**Comment by damianlegawiec** [comment]
@vernondegoede merged via https://github.com/spree/spree/pull/7766 :)

**Comment by vernondegoede** [comment]
Nice! Thanks :)

**Comment by damianlegawiec** [comment]
@vernondegoede Thank you! :)
