### ISSUE TITLE
Api for customer return and reimbursement.

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [spree/spree#7770]
There is no api for reimbursement, customer return and cancel salesorder.

**Comment by MuhammadAhmed1994** [comment]
found cancel sales order API but still reimbursement and customer return API are missing.

**Comment by MuhammadAhmed1994** [comment]
can you please tell me the estimated time for these two API's.
Thanks,

**Comment by MuhammadAhmed1994** [comment]
Hi Damian ,
is there any update?
Thanks,

**Comment by mohsen-alizadeh** [comment]
Can i pick this issue ?

**Comment by damianlegawiec** [comment]
@mohsen-alizadeh sure!

**Comment by mohsen-alizadeh** [comment]
@MuhammadAhmed1994 I'm working on this issue. I will complete and create a merge request in one month surely.

**Comment by mohsen-alizadeh** [comment]
@damianlegawiec please merge!
