### ISSUE TITLE
Cannot find form registration using spree 3.1

### ISSUE THREAD

**Issue by chileap** [spree/spree#7773]
Hello

I am quite new here with spree commerce. And I try to add field into user but I could not find file registration for customer.

I wonder where it has gone since I have read document and it said that file is in spree/checkout/registration but I could not find it in 3.1.

Could you tell where it is?

**Comment by jdatti** [comment]
@chileap Its not part of spree core. You either have to build your own or you can use of spree's extentions(https://github.com/spree/spree_auth_devise)
