### ISSUE TITLE
Add notes at checkout process

### ISSUE THREAD

**Issue by vincentkedison** [spree/spree#7774]
How can I add notes textbox at checkout process? thankyou

**Comment by askl56** [comment]
This is a core rails query, as it should not be a part of Spree core. Additionally, you need to provide more information as to what you require.

**Comment by jafffmen** [comment]
Closed - no specific info provided :)

**Comment by askl56** [comment]
@jafffmen I tried :(

**Comment by jafffmen** [comment]
@askl56 we can reopen this issue if there is a need for it 🙂
