### ISSUE TITLE
Add Address into User Registration form

### ISSUE THREAD

**Issue by chileap** [spree/spree#7776]
I have used gem `spree_address_book` to my project. And I want to let customer register their account with address so I want to integrate with this gem by not create other new field of address.

And I don't have any clue to add this association together. Anyone can help me with this point?

**Comment by priyank-gupta** [comment]
@chileap You can make use of `ship_address` and `bill_address` associations from user and save that address in any of the suitable field.

**Comment by chileap** [comment]
@priyank-gupta Thanks for your answer. I already found solutions. Since I used gem `spree_address_book`, it is added association between `spree_user` and `spree_addresses`. Then I just add `has_many` to `spree_user` and it worked well.
