### ISSUE TITLE
Wonder where display_price, single_money come from?

### ISSUE THREAD

**Issue by chileap** [spree/spree#7778]
I have tried to modify display_price and single_money methods but I don't know where it all come from. That's why I couldn't modify.

Anyone can help me with this?

**Comment by Mafi88** [comment]
https://github.com/spree/spree/blob/master/core/app/models/spree/price.rb#L18-L19
https://github.com/spree/spree/blob/master/core/app/models/concerns/spree/display_money.rb#L20

**Comment by chileap** [comment]
@Mafi88 Thank for your response. So if I wanna customize this method, I need to add like

`extend DisplayMoney`
 `money_methods  :amount, :price` 

`def amount`
`.....`
`end`

and 

`def price`
`.....`
`end`
