### ISSUE TITLE
Dynamic updated price depend on user login

### ISSUE THREAD

**Issue by chileap** [spree/spree#7779]
I have tried to update price depend on user login, and the process is working well untill delivery step. I got wrong price and I know it is in order model but I don't have any clues with this step.

Could anyone guide me about changing price in this step?

**Comment by priyank-gupta** [comment]
@chileap May be you can explain more about what are you trying to achieve and how ?

**Comment by chileap** [comment]
@priyank-gupta I have field `sale_price` which in `spree_varaint` model. And I want only non authentication users see that price while authentication user see master price.

And I have tried to edit LineItem model 

`old_copy_price = instance_method(:copy_price)
  define_method(:copy_price) do
    old_copy_price.bind(self).call
    return unless variant`

    if variant
      if changed? && changes.keys.include?('quantity')
        if order.user.nil?
          vprice = variant.sale_price
        end
        self.price = vprice and return
      end

      self.price = variant.price if price.nil?
    end

    self.price = variant.price if price.nil?`
`end`


and it changed well untill in delivery step of user, it turned back into master price. and I could not find any solutions with that one. 

Could you suggest some idea with that?
