### ISSUE TITLE
How to exclude tax and shipping in Spree?

### ISSUE THREAD

**Issue by chileap** [spree/spree#7780]
I wonder which part that we can disable tax in spree?

And when I try to disable it, it errors and message is `We are unable to calculate shipping rates for the selected items.`

Anyone has any idea with this?

**Comment by priyank-gupta** [comment]
@chileap You can use flat rate calculator with an amount of 0 instead of disabling it.

**Comment by chileap** [comment]
@priyank-gupta thank for answer.
