### ISSUE TITLE
As an admin I cannot edit user info in admin/orders

### ISSUE THREAD

**Issue by catalin88** [spree/spree#7786]
## Context
As an admin I cannot edit user info in admin/orders

## Expected Behavior
Data should be updated.

## Actual Behavior
"User not found" error appears.
Same error appears either the customer made the order as a guest or not

## Possible Fix
I have seen the issue has been signaled before for guest users and marked as solved, yet that solution still gives me the same error for users that are not guests (haven't tested solution for guests): https://github.com/spree/spree/issues/7729

## Steps to Reproduce
1. Log into admin panel
2. Try to update client info in order
3. Get "User not found" error

## Your Environment
Spree 3.1.3

**Comment by ubudzisz** [comment]
hi @catalin88 in 3.1. I cannot edit guest user. in 3.2 everything works fine after #7729

**Comment by mohsen-alizadeh** [comment]
I've checked on master, it works fine for both registered user, and guest users.
Admin user can edit both in orders.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/7834
