### ISSUE TITLE
Filter products by last modified date

### ISSUE THREAD

**Issue by muhammadahmed94** [spree/spree#7788]
Is there any API  filter to fetch list of products by last modified date ?

**Comment by priyank-gupta** [comment]
@muhammadahmed94 Spree uses ransack for searching so you can send params like `{ q: { updated_at_eq: modified_datetime } }` to products index api which should do the trick. Read more on ransack [here](https://github.com/activerecord-hackery/ransack)

**Comment by muhammadahmed94** [comment]
Thanks Priyank,
but i was passing filter in api like that..
http://demo10.folio3.com:3000/api/v1/products?q[updated_date_gteq]=2018-12-26T00:00:00.000Z&token=
but it didn't respond me the expected output and showing more than 40 products in response.
one more thing i also want updated_at(last modified date) in product response do i need to customize the existing spree api?


________________________________

**Comment by priyank-gupta** [comment]
@muhammadahmed94 You need to specify updated_at in `whitelisted_ransackable_attributes`, `self.whitelisted_ransackable_attributes = %w[description name slug discontinue_on updated_at]`.

Add `Spree::Api::ApiHelpers.product_attributes.push(:updated_at)` in `spree.rb`.
This should do the trick.

**Comment by muhammadahmed94** [comment]
Thanks Priyank.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/7452
