### ISSUE TITLE
How to clear cache manully in spree?

### ISSUE THREAD

**Issue by chileap** [spree/spree#7789]
I have tried to switch the price of price after login and logout. the problem is when I logout, the price is still the same as login because of cache in application since when I clear cache in admin, it worked fine.

So I want to ask if there are anyways to clear cache manully after login and logout?

**Comment by priyank-gupta** [comment]
@chileap Its not a good approach to clear cache on login/logout instead you should add `spree_user_signed_in?` as part of price cache key.

**Comment by chileap** [comment]
@priyank-gupta thank you.
