### ISSUE TITLE
How to contribute to guides.spreecommerce.org?

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7791]
Hi,

I'm just starting with Spree and started following the tutorial on guides.spreecommerce.org and would like to contribute to the documentation as I move along. How can I do that?

## Context
For example, the quote from the documentation:
http://guides.spreecommerce.org/developer/getting_started_tutorial.html
> To run Spree 3.1 you need the latest Rails version, 4.2.6.

The latest version of Rails is 5.x something. And the latest 4.2.x version is 4.2.7.1.

## Expected Behavior
It should mention Rails 5 or at least have Rails 4.2.7.1 as "latest" version or "latest" version that works for sure.

**Comment by markholmes** [comment]
Hi vfonic,

I would assume that those docs are [located here](https://github.com/spree/spree/blob/master/guides/content/developer/tutorials/getting_started_tutorial.md) - if you clone the repo and make those changes, you could submit a PR!

**Comment by damianlegawiec** [comment]
Hi @vfonic you can just contribute to this repo, guides are built based on markdown files from https://github.com/spree/spree/tree/master/guides directory.

Thanks for the support!
