### ISSUE TITLE
ActiveRecord::StatementInvalid (Could not find table 'spree_orders')

### ISSUE THREAD

**Issue by 99cm** [spree/spree#7792]
have developed a rails 5 application and just deployed it, but been unable to run. Rails can't handle public requests. 2 issues raised: one is "spree_orders" posted here, another "spree_pages" posted to "spree_static_content". Web server repeatedly logs these two errors.
## Actual Behavior

I, [2017-01-29T12:35:51.421823 #30826]  INFO -- : Started GET "/products/zishen-ningshen-wan?taxon_id=12" for 180.76.15.157 at 2017-01-29 12:35:51 -0500
I, [2017-01-29T12:35:51.425991 #30826]  INFO -- : Processing by Spree::ProductsController#show as */*
I, [2017-01-29T12:35:51.426041 #30826]  INFO -- :   Parameters: {"taxon_id"=>"12", "id"=>"zishen-ningshen-wan"}
I, [2017-01-29T12:35:51.445500 #30826]  INFO -- : Completed 500 Internal Server Error in 19ms (ActiveRecord: 0.1ms)
F, [2017-01-29T12:35:51.446874 #30826] FATAL -- :   
F, [2017-01-29T12:35:51.446908 #30826] FATAL -- : ActiveRecord::StatementInvalid (Could not find table 'spree_orders'):
F, [2017-01-29T12:35:51.446932 #30826] FATAL -- :   
F, [2017-01-29T12:35:51.446971 #30826] FATAL -- : activerecord (5.0.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:429:in `table_structure'
activerecord (5.0.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:304:in `columns'
activerecord (5.0.1) lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
activerecord (5.0.1) lib/active_record/connection_adapters/schema_cache.rb:62:in `columns_hash'
activerecord (5.0.1) lib/active_record/model_schema.rb:441:in `load_schema!'
activerecord (5.0.1) lib/active_record/attributes.rb:233:in `load_schema!'
activerecord (5.0.1) lib/active_record/attribute_decorators.rb:28:in `load_schema!'
activerecord (5.0.1) lib/active_record/model_schema.rb:436:in `load_schema'
activerecord (5.0.1) lib/active_record/model_schema.rb:349:in `attribute_types'
activerecord (5.0.1) lib/active_record/model_schema.rb:368:in `type_for_attribute'
activerecord (5.0.1) lib/active_record/table_metadata.rb:34:in `type'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:165:in `build_bind_param'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:124:in `block in create_binds_for_hash'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:100:in `each'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:36:in `create_binds'
activerecord (5.0.1) lib/active_record/relation/where_clause_factory.rb:20:in `build'
activerecord (5.0.1) lib/active_record/relation/query_methods.rb:632:in `where!'
activerecord (5.0.1) lib/active_record/relation/query_methods.rb:625:in `where'
activerecord (5.0.1) lib/active_record/relation/finder_methods.rb:328:in `exists?'
activerecord (5.0.1) lib/active_record/querying.rb:3:in `exists?'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:7:in `block in generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `loop'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/controller_helpers/auth.rb:29:in `set_guest_token'
activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
railties (5.0.1) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.1) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
versioncake (3.1.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 3.2.0
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by 99cm** [comment]
Did these lines cause the issue?
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:7:in `block in generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `loop'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/controller_helpers/auth.rb:29:in `set_guest_token'

**Comment by 99cm** [comment]
spree core token_generator.rb, controller_helper/autho.rb need to be fixed
`I, [2017-02-01T20:50:45.960615 #29391]  INFO -- : Started GET "/products/chuan-bei-ju-hong-respira-herbs?taxon_id=26" for 66.249.69.254 at 2017-02-01 20:50:45 -0500
I, [2017-02-01T20:50:45.961523 #29391]  INFO -- : Processing by Spree::ProductsController#show as HTML
I, [2017-02-01T20:50:45.961564 #29391]  INFO -- :   Parameters: {"taxon_id"=>"26", "id"=>"chuan-bei-ju-hong-respira-herbs"}
I, [2017-02-01T20:50:45.962501 #29391]  INFO -- : Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.1ms)
F, [2017-02-01T20:50:45.963869 #29391] FATAL -- :   
F, [2017-02-01T20:50:45.963902 #29391] FATAL -- : ActiveRecord::StatementInvalid (Could not find table 'spree_orders'):
F, [2017-02-01T20:50:45.963926 #29391] FATAL -- :   
F, [2017-02-01T20:50:45.963963 #29391] FATAL -- : activerecord (5.0.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:429:in `table_structure'
activerecord (5.0.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:304:in `columns'
activerecord (5.0.1) lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
activerecord (5.0.1) lib/active_record/connection_adapters/schema_cache.rb:62:in `columns_hash'
activerecord (5.0.1) lib/active_record/model_schema.rb:441:in `load_schema!'
activerecord (5.0.1) lib/active_record/attributes.rb:233:in `load_schema!'
activerecord (5.0.1) lib/active_record/attribute_decorators.rb:28:in `load_schema!'
activerecord (5.0.1) lib/active_record/model_schema.rb:436:in `load_schema'
activerecord (5.0.1) lib/active_record/model_schema.rb:349:in `attribute_types'
activerecord (5.0.1) lib/active_record/model_schema.rb:368:in `type_for_attribute'
activerecord (5.0.1) lib/active_record/table_metadata.rb:34:in `type'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:165:in `build_bind_param'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:124:in `block in create_binds_for_hash'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:100:in `each'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
activerecord (5.0.1) lib/active_record/relation/predicate_builder.rb:36:in `create_binds'
activerecord (5.0.1) lib/active_record/relation/where_clause_factory.rb:20:in `build'
activerecord (5.0.1) lib/active_record/relation/query_methods.rb:632:in `where!'
activerecord (5.0.1) lib/active_record/relation/query_methods.rb:625:in `where'
activerecord (5.0.1) lib/active_record/relation/finder_methods.rb:328:in `exists?'
activerecord (5.0.1) lib/active_record/querying.rb:3:in `exists?'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:7:in `block in generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `loop'
spree_core (3.2.0.rc2) lib/spree/core/token_generator.rb:5:in `generate_guest_token'
spree_core (3.2.0.rc2) lib/spree/core/controller_helpers/auth.rb:29:in `set_guest_token'
activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
railties (5.0.1) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.1) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
versioncake (3.1.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by octoxan** [comment]
Running into this exact same issue and don't understand what the fix was?
