### ISSUE TITLE
Update adjustments section in Spree Developers Guide

### ISSUE THREAD

**Issue by harsh-ag** [spree/spree#7793]
Currently, there are only two states of adjustments- open and closed. Third state(finalized) was removed from Spree in commit cf34db744c235420f19f8eb7297508cdb733f475.
Need to update the same in Spree Developers Guide: 
http://guides.spreecommerce.org/developer/adjustments.html

**Comment by damianlegawiec** [comment]
Hi @harsh-ag , thanks for noticing this - please submit a PR for this repository (guides directory) and we will update the docs

**Comment by nnande** [comment]
@damianlegawiec changes already merged into master in [commit](https://github.com/spree/spree/commit/28c494f191279166035c49e7d9babc653836d1e4)
