### ISSUE TITLE
Connection needs to be established 

### ISSUE THREAD

**Issue by sivagollapalli** [spree/spree#7795]
I am using rails `4.2.7.1` with `sqlite3` and spree `3.1.3`. I have loaded sample data to test demo site. But when I went to console and type `Spree::User` it gives msg as `Spree::User (call 'Spree::User.connection' to establish a connection)`. If I do `Spree::User.count` then ruby gets crashed. But when I comment `spring` gem in `Gemfile` then there are no issues. Could you help me?

**Comment by freshnewegg** [comment]
Just establish a connection with "Spree::User.connection", then make your calls

**Comment by sivagollapalli** [comment]
@freshnewegg I did but `Spree::User.connection` leads to ruby crash. I am using `ruby-2.3.1`

**Comment by nnande** [comment]
@sivagollapalli try ```spring stop``` before entering the console
