### ISSUE TITLE
Is there any use of font-awesome-rails gem in spree_core?

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7802]
I've found out that `spree_core` has `font-awesome-rails` as a dependency in its gemfile:
https://github.com/spree/spree/blob/master/core/spree_core.gemspec#L29

I couldn't find any use of FA gem in the whole `spree` project at all, especially not in `spree_core`.

I'm trying to use spree with custom frontend that I'm building and it's a bit of an issue having to load FA (or even TW bootstrap) since I'm not using it.

**Comment by nnande** [comment]
@vfonic it seems font awesome gem is not used anywhere. I think we should make a PR with the cleanup.

**Comment by vfonic** [comment]
👍
