### ISSUE TITLE
Stripe Checkout: ArgumentError in Spree::CheckoutController#update (Missing required parameter: login)

### ISSUE THREAD

**Issue by ouarez** [spree/spree#7810]
## Context

Added Payment Method for Stripe, including API Keys.

Any attempt to then checkout after adding a product to the cart is met with this error.

## Steps to Reproduce
1. Fresh install of Spree with Rails 5.0.1 
2. Add Payment Method for Stripe
3. Add product to cart, checkout
4. Error is encounted upon completing step 3 (Payment info)

### ArgumentError in Spree::CheckoutController#update

Missing required parameter: login

Extracted source (around line #305): 

```
            raise ArgumentError.new("Parameter: #{param.first} must be one of #{valid_options.to_sentence(:words_connector => 'or')}") unless valid_options.include?(hash[param.first])
          else
            raise ArgumentError.new("Missing required parameter: #{param}") unless hash.has_key?(param)
          end
        end
      end
```

It looks like this error might actually be coming from active_merchant, but I can't find anyone else who had this issue.

This error is killing me, since something as fundamental as checking out with Stripe isn't working.
After searching around, the only information I could find experienced this error because they hadn't added login information to their payment method.

But I did add the API keys from my Stripe account. I don't know what else to do.

Maybe it's because I'm using Rails 5.0.1  ? Should I start from scratch with Rails 4?

(I did install the correct versions of the gem for spree_gateway,  3.2.0)

Thanks for any assistance you can provide!
![spree-error](https://cloud.githubusercontent.com/assets/25655587/22771537/4476c476-ee65-11e6-9c8d-5dbe465eb6fe.png)

**Comment by ouarez** [comment]
Thank you!!!! That last fix worked!

I just ran bundle update and was able to pass an order both with the Stripe test API keys, and the live keys.

Your hard work is more than appreciated, and my client will be happy that the store is finally working :)

If you need any details or screenshots from my end, please let me know.

You can consider this issue resolved. Thanks again!

**Comment by VentGrey** [comment]
Issue is happening again :( is there any workaround? Both stripe keys are correct.
![image](https://user-images.githubusercontent.com/24773698/61854866-9e85dd80-ae84-11e9-9bff-5a180617312f.png)
