### ISSUE TITLE
deface gem trying to modify frozen array "eager_load_paths" when running in production

### ISSUE THREAD

**Issue by RyanQuey** [spree/spree#7812]
## Context
I'm trying to deploy my spree project to heroku, but I'm getting the following error message: "Unable to load application: RuntimeError: can't modify frozen Array"

Using the backtrace, this is because deface is calling reject! method on eager_load_paths (deface/railtie.rb:39, using deface 1.1.0). It seems like this is a problem because that eager_load_paths array has already been frozen by railties (lib/rail/engine.rb:571, using rails 5.0.1)?

This doesn't break in development, but for some reason prevents me from opening up my app in production. Any guesses?

**Comment by symarys** [comment]
@RyanQuey I think this may be a Rails configuration issue, not a problem with deface itself (reference: https://github.com/mperham/sidekiq/issues/2795).
