### ISSUE TITLE
Line item price set incorrectly when returning user is outside of the default tax zone

### ISSUE THREAD

**Issue by markdavies** [spree/spree#7816]
A new order line item price is set incorrectly when the default tax is included in the price and the current user is not in that zone.

## Context

I have a Spree site where the default tax zone is EU VAT of 20%. My client wants to show that price to EU customers, and for the price to include the VAT. They want users outside of the EU to see a reduced price which does not include any tax.

When I checkout from the site as an Australian user for example, I see the discounted rate display after I have entered my address. Subsequently when I return to the site, I see the reduced price displayed in the product index too, which is great.

When I add a product to the cart however, it shows up as the default tax zone price which in this case includes VAT.

Basically, new line items added to the order do not take into account a users current tax zone. I have tested and confirmed this on a vanilla Spree install.

## Expected Behavior

Existing non-default tax zone user enters the site
User views products at a reduced price
User adds a product to the cart
User sees the correctly reduced price in the cart line item

## Actual Behavior

Existing non-default tax zone user enters the site
User views products at a reduced price
User adds a product to the cart
User sees the default tax zone price, incorrectly

## Possible Fix

OrderContents.add should take into account a tax zone..?

## Steps to Reproduce

1. Create vanilla Spree install with seeded data
2. Create a new default tax zone in the admin for the EU zone of 20%, and set the tax to be included in price
3. Remove all other pre-existing tax rates
4. On the front end, create a new cart with any product
5. Check out with a non-EU address, note that the price has reduced correctly
6. Return to the front end and browse products, noting that the prices are reduced
7. Add any product to the cart
8. Note that the price is incorrectly the +20% tax price

## Your Environment

* Version used: 3.1.3
* Gemfile and Gemfile.lock as text in a Gist:
https://gist.github.com/markdavies/375e8d9492cbbd585b2de7aa4bf4fdd3
https://gist.github.com/markdavies/bd28477ab7c52903321be859c1d578a3

* Any relevant stack traces ("Full trace" preferred):

**Comment by nnande** [comment]
@markdavies Hello,

You precise description helped a lot, thanks for that. I was able to reproduce this bug and wrote some fixing code already. I hope that it resolves the issue. Here is the link to PR: `
https://github.com/spree/spree/pull/7888
