### ISSUE TITLE
Bug when trying to update address of guest checkout order in admin backend

### ISSUE THREAD

**Issue by charleswong28** [spree/spree#7818]
## Expected Behavior
Both billing address and shipping address could be updated for guest checkout order in admin backend.

## Actual Behavior
When admin updates either billing address or shipping address in admin backend, "User not found" error comes out after updating address. 

**Screen Capture:** 
![Screen Capture of the error](http://imgur.com/XMnOQtW.jpg)

## Possible Fix
The reason is that guest_checkout parameter is not passing after the order is completed. It will run load_user in controller when it is not guest checkout. The solution could be adding a hidden radio button in view for completed order so guest_checkout parameter will be passed into the update call.

spree/backend/controllers/spree/admin/orders/customer_details_controller.rb
```
module Spree
  module Admin
    module Orders
      class CustomerDetailsController < Spree::Admin::BaseController
        before_action :load_order
        before_action :load_user, only: :update, unless: :guest_checkout?

...

        def guest_checkout?
          params[:guest_checkout] == 'true'
        end
      end
    end
  end
end
```

**Suggested Change**
spree/backend/view/spree/admin/orders/customer_details/_form.html.erb
Add radio button on line 30: 
```
<div>
  <span class="badge">
    <%= @order.user.nil? ? Spree.t(:say_yes) : Spree.t(:say_no) %>
    <%= radio_button_tag :guest_checkout, true, @order.user.nil?, class: 'hide' %>
  </span>
</div>
```

## Your Environment
* Version used: 3-1-stable

**Comment by damianlegawiec** [comment]
It's fixed :)
