### ISSUE TITLE
[Feature] Can we introduce active model serializer for API response

### ISSUE THREAD

**Issue by vishalzambre** [spree/spree#7829]
As ```active_model_serializers```  are faster than ```rabl``` response, can we introduce this feature.
I have created extension ```https://github.com/vishalzambre/spree_active_model_serializer```.

**Comment by ouykjh** [comment]
@vishalzambre is it possible for you to create PR to merge your extension with spree? I was thinking about change it in spree, to use `active_model_serializers` natively. I can do it by yourself, but probably your solution will be ok.

**Comment by vishalzambre** [comment]
@ouykjh  Yes, I can create PR to merge this extension to spree.

**Comment by damianlegawiec** [comment]
AMS isn't stable enough ( https://github.com/rails-api/active_model_serializers#status-of-ams ) we're moving all of our efforts for API v2 into jbuilder.
