### ISSUE TITLE
How to get route info in middleware

### ISSUE THREAD

**Issue by mimani** [spree/spree#7839]
## Context
I have a [rails webapp](https://github.com/mimani/rails-spree-example) using spree, I have written a middleware to capture metrics related to performance. I want to get current route, so that I can push metrics for each route. Following is core part of [middleware](https://github.com/mimani/rails-spree-example/blob/master/app/middleware/my_statsd.rb):

```
def call(env)
  (status, headers, body), response_time = call_with_timing(env)
  statsd.timing("#{env['REQUEST_PATH']}.response", response_time)
  statsd.increment("#{env['REQUEST_PATH']}.response_codes.#{status.to_s.gsub(/\d{2}$/,'xx')}")
  # Rack response
  [status, headers, body]
rescue Exception => exception
  statsd.increment("#{env['REQUEST_PATH']}.response_codes.5xx")
  raise
end

def call_with_timing(env)
  start = Time.now
  result = @app.call(env)
  [result, ((Time.now - start) * 1000).round]
end
```

## Expected Behavior
I want to track the metrics for each API, but not able to get the exact route like this: `/api/v1/products/productId` or controller and action for that route.

## Actual Behavior
with `env["REQUEST_PATH"]` I get: `/api/v1/products/12` which is not desired as I want to club all paths of same route.

## Steps to Reproduce
Sample Github Code repo: https://github.com/mimani/rails-spree-example
SO Question with more details: http://stackoverflow.com/questions/42691729/how-to-find-current-abstract-route-in-rails-middware

## Your Environment

* Version used:
  Spree: '3.1.1'
  Rails: '~> 4.2.7.1'
* Gemfile : https://github.com/mimani/rails-spree-example/blob/master/Gemfile

**Comment by nnande** [comment]
Hi @mimani!
I think the solution for your case is explained in the above [SO Question ]( http://stackoverflow.com/questions/42691729/how-to-find-current-abstract-route-in-rails-middware)under the first **Update** section.

Having look at  ``` app/middleware/my_statsd.rb``` in your example repo,
 you may want ``` def call ``` method to use ```Spree::Core::Engine.routes.router.recognize```  instead of ```Rails.application.routes.router.recognize``` call, something like:

```
  def call(env)
    request = ActionDispatch::Request.new(env)
    Spree::Core::Engine.routes.router.recognize(request) { |route, params|
      route.defaults ##=> {:controller=>"spree/products", :action=>"show"}
    }
    (status, headers, body), response_time = call_with_timing(env)

    ...
  end

```
 
With that data statsd can successfully compute aggregations for every single spree controller action for you, regardless any parameters coming along with the request.

Good luck! :smiley:
