### ISSUE TITLE
Issue with StoreCredit payment

### ISSUE THREAD

**Issue by AnuragBhardwaj1** [spree/spree#7873]
Two payments are being created if we pay by StoreCredit.

## Context
When user has a CreditCard info saved and StoreCredit also.
Now when the user pay by store credit the order is complete but there is a new payment from credit card with amount zero.

## Expected Behavior
Only one payment should be created, i.e. of store credit.

## Actual Behavior
Two payments are being created, one from credit card(amount: 0)

## Possible Fix
We can reject attributes with zero amount if there is order payment(of store credit).

## Steps to Reproduce
1. Suppose user has credit card stored info stored and he has store credit too.
2. He proceed to checkout from cart to payment step.
3. He pays by store credit and order is complete.
4. Check order.payments(or from admin/orders) there are two payments

## Environment
Reproducable on 3-1, 3-2-stable

**Comment by nnande** [comment]
Hello @AnuragBhardwaj1,

I just followed your instruction and was unable to reproduce the issue. The final store credit payment resulted in creating an order with only one payment with ```source_type: "Spree::StoreCredit"```.
I was working both 3-1-stable and 3-2-stable branches.

It would help a lot if you could provide detailed steps to reproduce and/or environment info, maybe I am missing something.

Thanks

**Comment by AnuragBhardwaj1** [comment]
@nnande , did you try with placing first order with CreditCard and then placing another order and paying second order with StoreCredit.
In second case radio for CreditCard is checked by default.
So, additional nil payment is created.

**Comment by AnuragBhardwaj1** [comment]
PR merged: Issues Seems to be fixed.
Closing Issue.

Thanks Team.

**Comment by damianlegawiec** [comment]
Thanks @AnuragBhardwaj1 👍
