### ISSUE TITLE
ReferenceError: Spree is not defined in the checkout page

### ISSUE THREAD

**Issue by tdquan** [spree/spree#7876]
I'm on the checkout page where I can enter the Billing and Shipping address but I got that error
`ReferenceError: Spree is not defined
 /checkout/address:806`

This is apparently refer to the line:

`<script>`
 ` Spree.current_order_id = "<%= @order.number %>"`
  `Spree.current_order_token = "<%= @order.guest_token %>"`
`</script>`

in the `spree/checkout/edit.html.erb` file and I have no idea why this problem suddenly cropped up.
My suspicion is something to do with not importing certain default javascript file which define what Spree is but I don't remember messing any JavaScript file up.

Any idea what might have caused this problem?

**Comment by joshRpowell** [comment]
@tdquan This popped up for me when we upgraded to Spree 3.2.0.beta1 from 3.1.0.  We haven't been able to figure it out either.  But we haven't looked at the diff either.

**Comment by joshRpowell** [comment]
@tdquan we also started to see a similar error after this was added:  https://github.com/spree/spree/blob/master/frontend/app/assets/javascripts/spree/frontend/checkout/shipment.js.coffee#L32

**Comment by tdquan** [comment]
@joshRpowell for me I think all the JavaScripts used for form-formatting and state selection doesn't work. My colleagues using 3.2.0 still have all these working but mine is 3.3.0.alpha (installed by mistake). Let me know if you figure out a way to work around this. Thanks!

**Comment by joshRpowell** [comment]
>My colleagues using 3.2.0 still have all these working but mine is 3.3.0.alpha (installed by mistake).

@tdquan what rails versions are being used in the v3.2.0 and v3.3.0.alpha examples you noted above?

**Comment by tdquan** [comment]
@joshRpowell we are all using rails 5.0.1.

**Comment by damianlegawiec** [comment]
@joshRpowell @tdquan can you check if you're including `spree/shared/paths` partial?

This commit (mine ;) could be the culprit: https://github.com/spree/spree/commit/387b51b0f18fc82d6954db7b4c24d857b7593ac0

**Comment by joshRpowell** [comment]
@damianlegawiec yes, it looks like that is the issue. Perhaps it's related to #7722 and #7725.

We were including the `spree/shared/paths` partial in some other `view/layouts/*` to prevent the following error: 
![spree error](https://cloud.githubusercontent.com/assets/6732638/24507822/89fe258e-152f-11e7-8958-91f11d5a49ae.png)

When I remove the `spree/shared/paths` partial the error noted in this issue `ReferenceError: Spree is not defined` goes away and the error I noted above returns.

**Comment by tdquan** [comment]
@damianlegawiec Fixed the problem. Indeed it was the missing partial `spree/shared/paths`. To be more specific, this partial has to be included before loading all the javascript resources. I got this order wrong which led to the error. Cheers!

**Comment by joshRpowell** [comment]
Nice find @tdquan! 
```erb
    <%= render 'spree/shared/paths' %>
```
did you add the following like you'll find in line 11 below?
```erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]> <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]> <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]> <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="<%= I18n.locale %>">
  <!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
    <!-- add here --><%= render 'spree/shared/paths' %> <!-- add here -->
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
    <%= render partial: 'spree/shared/google_analytics.js' %>
    <%= render partial: 'spree/shared/header' %>

    <div class="container">
      <div class="row" data-hook>
        <%= breadcrumbs(@taxon) %>

        <%= render partial: 'spree/shared/sidebar' if content_for? :sidebar %>

        <div id="content" class="<%= !content_for?(:sidebar) ? " col-sm-12" : " col-sm-8 col-md-9" %>" data-hook>
          <%= flash_messages %>
          <%= yield %>
        </div>

        <%= yield :templates %>
      </div>
    </div>
  </body>
</html>
```

**Comment by danielricecodes** [comment]
Simpler answer: Be sure to check that `spree/frontend/all` is included in your application.js file or explicity loaded in your layout file.

```javascript
//= require spree/frontend/all
```

OR

```erb
<%= javascript_include_tag ''spree/frontend/all" %>
```

Problem solved for me.

**Comment by rdaniels** [comment]
`<%= javascript_include_tag "spree/frontend/all" %>` fixes it, but I didn't wall all .js. I found that putting
```
//= require spree.js
//= require spree/frontend.js
```
at the top of my .js file also fixes it
