### ISSUE TITLE
ImageMagick not workinf

### ISSUE THREAD

**Issue by shridharkalagi** [spree/spree#7879]
Hi,

Why is ImageMagick used in spree? I saw few docs where it says to upload images from admin page. In that case what is the use of ImageMagick. Please help me understand. Thanks!

**Comment by Lorel** [comment]
Spree Core is using [Paperclip](https://github.com/spree/spree/blob/master/core/spree_core.gemspec#L34)
Paperclip is using [ImageMagick to process images](https://github.com/thoughtbot/paperclip#image-processor)

**Comment by shridharkalagi** [comment]
@Lorel Thanks for the reply. Incase if ImageMagick is not there, then I won't be able to process images and still I can upload the images directly. isn't it? Also, I don't loose on any other functionality.

**Comment by Lorel** [comment]
@shridharkalagi actually, I'm not sure you can install Paperclip without ImageMagick: like it is written, ImageMagick **must** be installed, and you can see in the [gemspec file of Paperclip](https://github.com/thoughtbot/paperclip/blob/master/paperclip.gemspec#L24) that ImageMagick is given as requirement
and if you can't install Paperclip, you won't be able to install Spree Core
