### ISSUE TITLE
uninitialized constant Sequel (NameError)

### ISSUE THREAD

**Issue by mizzlala3** [spree/spree#7881]
## Context
When running `rails g spree:install --user_class=Spree::User` I get the following error ` uninitialized constant Sequel (NameError)` in reference to the config/environment.rb

I followed all steps required such ass adding the gems to my gemfile, however, I still get errors.  

`Bundler could not find compatible versions for gem "devise":
  In snapshot (Gemfile.lock):
    devise (= 4.2.1)

  In Gemfile:
    devise

    spree_auth_devise (~> 3.2.0.beta) was resolved to 3.2.0.beta, which depends on
      devise-encryptable (= 0.1.2) was resolved to 0.1.2, which depends on
        devise (>= 2.1.0)

    spree_auth_devise (~> 3.2.0.beta) was resolved to 3.2.0.beta, which depends on
      devise (~> 4.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`
 

when running `bundle update` i get back `Using devise 4.0.3 (was 4.2.1)`  why is it downgrading my devise gem?  

full output `rails g spree:install --user_class=Spree::User
/Documents/LeslieANN2/config/environment.rb:4:in `<top (required)>': uninitialized constant Sequel (NameError)
	from /.rvm/gems/ruby-2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /.rvm/gems/ruby-2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

**Comment by nnande** [comment]
Hello @mizzlala3!

It would be easier to find what went wrong if you provided some environment info, such as Ruby, Rails version, both Gemfile and Gemfile.lock snapshots. Can you share them with us? :)
