### ISSUE TITLE
2017 Development Roadmap? 

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7887]
Are there plans to refresh the 2016 roadmap?  https://github.com/spree/spree/wiki/Spree-Commerce-development-roadmap-2016

**Comment by damianlegawiec** [comment]
Hi @joshRpowell we'll propose the roadmap this week, we're in the middle of discussing what features we need in a majority of modern e-commerce projects, which should be in core and which should live as a universal extension. The big topic is 4.0 which will introduce a lot of groundbreaking changes and the path to it we want to ease as much as we can.

**Comment by krtschmr** [comment]
@damianlegawiec  where is it?

**Comment by damianlegawiec** [comment]
@krtschmr @joshRpowell you can find the roadmap here -> https://github.com/spree/spree/milestones?direction=asc&sort=due_date&state=open 

We've finally decided to keep it on github in a fully transparent matter
