### ISSUE TITLE
Spree install, rails g spree:auth:install

### ISSUE THREAD

**Issue by Dalyl09** [spree/spree#7889]
I fail to install spree, with spree install and installations recommend in your README
## Context
I run rails new myfirstapp -d mysql
I add in Gemfile ''gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta''' 
I run bundle install 
i run ''rails g spree:install --user_class=Spree::User'' i don't have a problem.
i run ''rails g spree:auth:install'', i have several errors ''Bundler::GemRequireError: There was an error while trying to load the gem 'spree'.
Gem Load Error is: superclass mismatch for class Cipher
'' 
And when i redo all the manipulations.
And i use ''spree install', but i don't write in gemfile, i write in my terminal gem install spree and spree_cmd. And bundle install, and i run ''spree install'' i don't have error, i have nothing.. 
I searched for 3 hours on Google, i try 3,4 solution and 0 does work.
I try ''installations options'' and, ''bundle exec rake db:seed'' i have a error, ''Mysql2::Error: Incorrect string value: '\xC4\x81n' for column 'name' at row 8''. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Linux Mint 64 bits, rails 5.0.2, MYSQL.
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by Lorel** [comment]
Hi @Dalyl09 

For your error on `rails g spree:auth:install`, I have no idea
But it looks like you have an encoding error when you run `'bundle exec rake db:seed`
I'd check if the tables are set for using `utf8` encoding
For my part, I didn't try Spree with MySQL, and I would recommend to use PostgreSQL

**Comment by Dalyl09** [comment]
Hi @Lorel, 
I resolved my problem, with a link : http://stackoverflow.com/questions/36641372/rails-how-to-get-sample-data-with-spree-commerce-sandbox.
Thanks you for your help. 
I'm from to Valenciennes, i would like to ask your for Spree, do you want ?
My adress email : feddal.dalyl@yahoo.fr
