### ISSUE TITLE
order displaying the wrong manifest quantity

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7897]
## Context
Math for line item total [here](https://github.com/spree/spree/blob/7fb31d3c48ab6f414a3af8c5e929b67c46f5527a/backend/app/views/spree/admin/orders/_shipment_manifest.html.erb#L17) does not match the subtotal [here](https://github.com/spree/spree/blob/7fb31d3c48ab6f414a3af8c5e929b67c46f5527a/backend/app/views/spree/admin/shared/_order_summary.html.erb#L23)

here is the manifest: 

```ruby
order.shipments.first.manifest.first =>
OpenStruct {
         :part => false,
      :product => #<Spree::Product:0x007f3e98e74950> {
                          :id => 11,
                        :name => "American Health Discount Cards (100 Count)",
                 :description => "The Discount Card Flyer must be presented with each discount card that is given to a client. ",
                :available_on => Mon, 11 Jul 2016 00:00:00 EDT -04:00,
                  :deleted_at => nil,
                        :slug => "american-health-discount-cards-100-count",
            :meta_description => "NASB, American Health Value, Discount Cards",
               :meta_keywords => "NASB, American Health Value, Discount Cards",
             :tax_category_id => nil,
        :shipping_category_id => 1,
                  :created_at => Tue, 12 Jul 2016 22:06:36 EDT -04:00,
                  :updated_at => Tue, 28 Mar 2017 15:07:22 EDT -04:00,
               :promotionable => true,
                  :meta_title => "American Health Value Discount Cards",
              :discontinue_on => nil,
                 :can_be_part => false,
             :individual_sale => true
    },
    :line_item => #<Spree::LineItem:0x007f3e98e1e7d0> {
                                  :id => 6280,
                          :variant_id => 11,
                            :order_id => 2640,
                            :quantity => 2,
                               :price => 10.0,
                          :created_at => Mon, 27 Mar 2017 09:11:03 EDT -04:00,
                          :updated_at => Mon, 27 Mar 2017 09:13:41 EDT -04:00,
                            :currency => "USD",
                          :cost_price => 6.88,
                     :tax_category_id => nil,
                    :adjustment_total => 0.0,
                :additional_tax_total => 0.0,
                         :promo_total => 0.0,
                  :included_tax_total => 0.0,
                      :pre_tax_amount => 20.0,
            :taxable_adjustment_total => 0.0,
        :non_taxable_adjustment_total => 0.0
    },
      :variant => #<Spree::Variant:0x007f3e98e1ed70> {
                     :id => 11,
                    :sku => "",
                 :weight => 1.2,
                 :height => 14.5,
                  :width => 10.0,
                  :depth => 1.5,
             :deleted_at => nil,
              :is_master => true,
             :product_id => 11,
             :cost_price => 6.88,
               :position => 1,
          :cost_currency => "USD",
        :track_inventory => true,
        :tax_category_id => nil,
             :updated_at => Tue, 28 Mar 2017 15:07:22 EDT -04:00,
         :discontinue_on => nil,
             :created_at => Fri, 16 Dec 2016 03:12:34 EST -05:00
    },
     :quantity => 1,
       :states => {
        "shipped" => 1
    }
}
```

## Expected Behavior
When an order is created, line_item quantity * line_item cost math should match summary subtotal.

## Actual Behavior
The email confirmation is reflected correctly:
![young_email_confirmation](https://cloud.githubusercontent.com/assets/6732638/24425961/ff5f5666-13d3-11e7-8c57-9124c08b2d41.PNG)
admin order view
![young_order-admin_side](https://cloud.githubusercontent.com/assets/6732638/24425962/ff6336dc-13d3-11e7-9445-6e35bc0faae8.PNG)

## Possible Fix
Unknown at this point.  But I noticed this [commit](https://github.com/spree/spree/commit/c53a36770404402d5c39d565344c3f72db5c48f2) recently made changes to the MANIFEST

## Steps to Reproduce

1. Place an order with a product quantity > 1
2. If line item quantity > 1, then order total does not match line item total

## Your Environment

* Version used: 3.3.0.alpha
* Gemfile and Gemfile.lock as text in a Gist: [Gemfile](https://gist.github.com/joshRpowell/c3b0ea13b1f1b96c5e5fe979e0df7e75) [Gemfile.lock](https://gist.github.com/joshRpowell/2b399fef45cda246a1704148b22af956)
* Any relevant stack traces ("Full trace" preferred): none

**Comment by joshRpowell** [comment]
This may be related to the addition of the default inventory_units quantity in #7790. 
We're continuing to investigate.

**Comment by symarys** [comment]
@joshRpowell I think it is connected with [spree-product-assembly gem](https://github.com/spree-contrib/spree-product-assembly). I can't see any issues when I'm testing your problem without it in Gemfile. Shipment manifest is overridden there (https://github.com/spree-contrib/spree-product-assembly/blob/master/app/models/spree/shipment_decorator.rb#L13)  - I'm investigating it.

**Comment by joshRpowell** [comment]
@symarys I added a PR that resolved the issue for us.  Let me know if it works for you as well.

**Comment by symarys** [comment]
@joshRpowell I just tested the issue again with your changes and it seems it's working fine :+1:
