### ISSUE TITLE
API error: undefined method `permit' for "quantity":String

### ISSUE THREAD

**Issue by nick9822** [spree/spree#7901]
Hi Team,

I have just requested to create stock movement via API, but it gives an error.
`undefined method permit' for "quantity":String`

My request is as follows
`response = c.session.post(c.url+"/stock_locations/1/stock_movements", jdata)` 
where jdata is
 `'{"stock_movement":{"quantity":8, "stock_item_id": 1966, "action": "received"}}'`

I have checked `api_helpers.rb` and found `@@stock_movement_attributes = [:id, :quantity, :stock_item_id]`
So I dont understand where is the problem, also I am confused whether action is permitted or not?

Thanks,
Nick

**Comment by AnuragBhardwaj1** [comment]
Hi @nick9822, can you please specify the spree version/details.
As I am able to create stock_movements using API.

**Comment by nick9822** [comment]
@AnuragBhardwaj1 
We are working with 3-0-stable. Also I did not see any changes to API after the release. 
Did you use requested in the same way as I did?

Thanks,
Nick

**Comment by AnuragBhardwaj1** [comment]
@nick9822 , 
`POST /api/stock_locations/1/stock_movements HTTP/1.1
Host: localhost:3000
Content-Type: application/json
X-Spree-Token: 8dda542dc2a90a2dfa9ebb3ff328d48e10382e6ae8d5fef8
Cache-Control: no-cache
Postman-Token: db144351-6222-5df5-abdb-fa2f1bc6e4df


{
	"stock_movement":{
		"quantity":8,
		"stock_item_id": 26,
		"action": "received"
	}
}`

<img width="1245" alt="screen shot 2017-04-03 at 2 23 58 pm" src="https://cloud.githubusercontent.com/assets/11751717/24602163/3cc2f45a-1879-11e7-8665-cf7c6e80c2d9.png">


This is what I have tried for 3-0-stable..
before I was using spree/master.
Let me know what I need to change.

**Comment by nick9822** [comment]
@AnuragBhardwaj1 
Thanks for replying. You are right its working perfectly fine. 
I figured out that headers were not passed perfectly. So now its working. :)

@damianlegawiec 
There are no bugs with respect to this, so I am closing this issue.

Thanks,
Nick
