### ISSUE TITLE
What's the best way to have proper Rails 5 support w/ friendly_id?

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7914]
Related to 3.3.x milestone PR/issue: Update friendly_id to v5.2.0: https://github.com/spree/spree/pull/7758

I'm trying to use spree on rails 5 together with friendly_id. It doesn't work well currently. If I use local fork of spree with friendly_id dependency changed to 5.2.0, then it works as expected. What can I do to be able to use friendly_id 5.2.0 and spree 3.2.1? Any chance to have friendly_id dependency updated before the guys release 5.2.1? (It's taking forever)

Fun fact: 5.1.0 was released in Jan 2015.

**Comment by vfonic** [comment]
Figured it out. I've added this initializer until this is fixed properly `config/initializers/friendly_id.rb`:

```rb
module FriendlyId
  module Finders
    def self.setup(model_class)
      model_class.instance_eval do
        relation.class.send(:include, friendly_id_config.finder_methods)
        if (ActiveRecord::VERSION::MAJOR == 4 && ActiveRecord::VERSION::MINOR == 2) || ActiveRecord::VERSION::MAJOR == 5
          model_class.send(:extend, friendly_id_config.finder_methods)
        end
      end

      # Support for friendly finds on associations for Rails 4.0.1 and above.
      if ::ActiveRecord.const_defined?('AssociationRelation')
        model_class.extend(ClassMethods)
        association_relation_delegate_class = model_class.relation_delegate_class(::ActiveRecord::AssociationRelation)
        association_relation_delegate_class.send(:include, model_class.friendly_id_config.finder_methods)
      end
    end
  end
end
```

This code is c/p-ed from this PR that fixed the bug:
https://github.com/norman/friendly_id/pull/728
https://github.com/norman/friendly_id/pull/728/files#diff-6c1e3429bcf1206c1a79aa1d516ada34R79

**Comment by damianlegawiec** [comment]
It's updated in the master (3.3) branch
