### ISSUE TITLE
Rails 5, Spree 3.2.1 rake db:seed not working properly

### ISSUE THREAD

**Issue by bansalakhil** [spree/spree#7922]
I am setting up fresh spree in new rails 5 app.

In my Gemfile I have:
```
gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'

```

```bundle install``` was successful 

Then I run 

```
bundle exec rake railties:install:migrations
bundle exec rake db:migrate
bundle exec rake db:seed
bundle exec rake spree_sample:load
```
``` rake spree_sample:load``` failed with following error

> Loaded Payment Methods samples
> Loaded Shipping Categories samples
> Couldn't find 'North America' zone. Did you run `rake db:seed` first?
> That task will set up the countries, states and zones required for Spree.

**Comment by vishalzambre** [comment]
@bansalakhil I just verified this one with above versions and working fine for me.
Could you please provide more info or try following steps once more after `rake db:drop`

**Comment by bansalakhil** [comment]
@vishalzambre I already tried with ``` rake db:drop``` . Same issue every time
Attaching Gemfile.lock for reference

**Comment by tanmay3011** [comment]
@vishalzambre Just tried a fresh install of Spree with same steps and I was able to replicate the issue.
<img width="904" alt="screen shot 2017-04-12 at 6 11 45 pm" src="https://cloud.githubusercontent.com/assets/4212447/24958122/e61bb04e-1fab-11e7-8e54-b1a81bfca018.png">

**Comment by vishalzambre** [comment]
@tanmay3011 @bansalakhil Let me try once more.

**Comment by jafffmen** [comment]
Hey @vishalzambre :)
I checked this issue, and the only problem is that you didn't run
```ruby
rails g spree:install --user_class=Spree::User
```
which is copying spree migrations into the project.

Please follow [getting started section](https://github.com/spree/spree/blob/master/README.md#getting-started)

Cheers :)
