### ISSUE TITLE
Guides: Broken link

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7927]
At the bottom of this page there's a broken link: http://guides.spreecommerce.org/api/summary.html

> Due to [the way this implemented | 404](https://github.com/spree/spree/blob/v2.3.1/api/v1/lib/spree/api/v1/responders/rabl_template.rb#L5-L18) you need to ensure the action rendering in your custom template explicitly calls `respond_with`

I've looked into `rabl_template.rb`, but I'm not sure to what L5-L18 should refer to:
https://github.com/spree/spree/blob/7fb31d3c48ab6f414a3af8c5e929b67c46f5527a/api/lib/spree/api/responders/rabl_template.rb

Someone with more background knowledge could fix this.

**Comment by muzykabart** [comment]
Hey @lani13, just create a PR with your fix and we'll merge it, thx

**Comment by lani13** [comment]
@muzykabart I created pull request to merge to branch 3-2-stable. It seems that in master the file guides/content/api/summary.md doesn't have that paragraph at all.
