### ISSUE TITLE
Guides: Possible to push new version?

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7928]
I see there are changes to the guides in the repo, but the guides pages are still using older version:
https://github.com/spree/spree/blob/master/guides/content/developer/tutorials/getting_started_tutorial.md

http://guides.spreecommerce.org/developer/getting_started_tutorial.html

Is it possible to have these changes pushed? The PR was merged 24 days ago and is misleading for new users trying to follow the guides.

**Comment by damianlegawiec** [comment]
@vfonic we will set up automatic guides deployments on every successful build on CI

**Comment by vfonic** [comment]
@damianlegawiec Sounds great! Is there any timeline/roadmap that's up to date where I can have a look?
Does it mean that [skip ci] shouldn't be used, because only guides updates won't deploy guides? I guess that should be the recommended way. It doesn't cost much (only time on Travis).

**Comment by vfonic** [comment]
ping

Is it possible to just deploy latest version of guides now, until the automatic deployment is setup?

**Comment by damianlegawiec** [comment]
Done :)
