### ISSUE TITLE
Missing partials when add a promition stratege.

### ISSUE THREAD

**Issue by ronaldoooo** [spree/spree#7929]
This happens in the edit view of promotion. When I add a promotion, like 'first order' or 'user logged in' etc.When I click 'add' button, noting happened. Then when I click 'update', it crashes. 

> ActionView::MissingTemplate in Spree::Admin::Promotions#edit
> Showing /usr/local/lib/ruby/gems/2.3.0/gems/spree_backend-3.2.1/app/views/spree/admin/promotions/_promotion_rule.html.erb where line #10 raised:
> 
> Missing partial spree/admin/promotions/rules/_user_logged_in with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :rabl], :versions=>[:v1]}. Searched in:
>  "/Users/ronaldoooo/RubymineProjects/mystore/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/bundler/gems/spree_i18n-07f2b0ff4a09/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_gateway-3.2.0.beta/lib/views/backend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_gateway-3.2.0.beta/lib/views/frontend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.2.0.beta/lib/views/backend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.2.0.beta/lib/views/frontend"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/devise-4.0.3/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_frontend-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_backend-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_api-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/spree_core-3.2.1/app/views"
>  "/usr/local/lib/ruby/gems/2.3.0/gems/kaminari-0.17.0/app/views"

To added with: I use spree 3.2.0, rails 5.0.2

**Comment by ronaldoooo** [comment]
I googled for a day and I found it's not like a general problem. If this is a issue that has been solved, plz tell me how to. Thanks a lot.

**Comment by ronaldoooo** [comment]
I found in the folder 

> /usr/local/lib/ruby/gems/2.3.0/gems/spree_backend-3.2.1/app/views/spree/admin/promotions/rules

 only 

> _country.html.erb      _item_total.html.erb   _landing_page.html.erb _option_value.html.erb _product.html.erb      _taxon.html.erb        _user.html.erb 

these 7 template in it . I’m confused where is the _first_order.html.erb and _one_use_per_user.html.erb?

**Comment by vishalzambre** [comment]
@randomecho thank for more info, let me have a look.

**Comment by pastullo** [comment]
Same problem with v3.2.3
The folder is missing those partials

**Comment by bbonislawski** [comment]
It's fixed with #8200 so no problem in 3.3+ . @damianlegawiec should we backport it to older versions?

**Comment by damianlegawiec** [comment]
@bbonislawski we should backport it, I've added proper labels to #8200
