### ISSUE TITLE
Spree_static_content install error

### ISSUE THREAD

**Issue by Nelwep** [spree/spree#7939]
I get

` bundle exec rails g spree_static_content:install
Running via Spring preloader in process 1713
      insert  vendor/assets/stylesheets/spree/frontend/all.css
         run  bundle exec rake railties:install:migrations FROM=spree_static_content from "."
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'
Would you like to run the migrations now? [Y/n] y
         run  bundle exec rake db:migrate from "."
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>' when I try to install this extension.. Can someone help me?
`

and when I get the server running it tells me 

> 
ActiveRecord::StatementInvalid in Spree::StaticContentController#show
Could not find table 'spree_pages'
Extracted source (around line #513):

511
512
513
514
515
516
              

	

        def table_structure(table_name)
          structure = exec_query("PRAGMA table_info(#{quote_table_name(table_name)})", 'SCHEMA').to_hash
          raise(ActiveRecord::StatementInvalid, "Could not find table '#{table_name}'") if structure.empty?
          structure
        end

**Comment by vfonic** [comment]
You should open this issue on the `spree_static_content` repo [here](https://github.com/spree-contrib/spree_static_content), as that's the repo for the code you're referring to.

**Comment by Nelwep** [comment]
I'll do that thanks
