### ISSUE TITLE
I can't put a buy button next to the price, along with quantity

### ISSUE THREAD

**Issue by Nelwep** [spree/spree#7952]
I get this message...

`
ActionView::MissingTemplate in Spree::Home#index

Showing /home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_frontend-3.1.5/app/views/spree/shared/_products.html.erb where line #42 raised:

Missing partial spree/home/_cart_form, spree/store/_cart_form, spree/base/_cart_form, application/_cart_form with {:locale=>[:fr], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :rabl], :versions=>[:v1]}. Searched in:
  * "/home/nelweb/rails/thirdyve/greenbar/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/bundler/gems/spree_related_products-29f563d4b590/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/bundler/gems/spree-product-assembly-abc3a5e23ebe/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/bundler/gems/spree_i18n-5c130191f9a0/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/twitter-bootstrap-rails-3.2.2/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/bundler/gems/spree_static_content-5e8d9ba3ee04/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_gateway-3.1.0/lib/views/backend"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_gateway-3.1.0/lib/views/frontend"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_auth_devise-3.1.0/lib/views/backend"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_auth_devise-3.1.0/lib/views/frontend"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_frontend-3.1.5/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_backend-3.1.5/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_api-3.1.5/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/spree_core-3.1.5/app/views"
  * "/home/nelweb/rails/thirdyve/greenbar/vendor/bundle/ruby/2.3.0/gems/kaminari-0.17.0/app/views"

Extracted source (around line #46):

44
45
46
47
48
49
              

	

    def find(*args)
      find_all(*args).first || raise(MissingTemplate.new(self, *args))
    end

    def find_file(path, prefixes = [], *args)

Trace of template inclusion: vendor/bundle/ruby/2.3.0/gems/spree_frontend-3.1.5/app/views/spree/home/index.html.erb

Rails.root: /home/nelweb/rails/thirdyve/greenbar`

**Comment by nnande** [comment]
@Nelwep Are you getting the error on the ```products#show``` page?

Could you paste Gemfile and Gemfile.lock files?
