### ISSUE TITLE
Any plans on upgrading to `cancancan`?

### ISSUE THREAD

**Issue by vfonic** [spree/spree#7971]
The last commit date to [cancan](https://github.com/ryanb/cancan) gem happened almost 4 years ago (!). The owner of the gem is not active in the community anymore and the community picked up where he left off and created [cancancan](https://github.com/CanCanCommunity/cancancan) gem.

I believe the only correct approach at this point would be to switch to `cancancan` gem. I don't know any details about how difficult the switch can be. At least at the beginning, the gem was 100% backwards compatible with `cancan` and I think the maintainers kept in mind the importance of backwards compatibility.

**Comment by krzysiek1507** [comment]
Hi @vfonic. Spree uses `cancancan` in version `~> 1.10.1`. PR with upgrade to the newest version is welcome!
