### ISSUE TITLE
Mail validation error on checkout, not on registering new account

### ISSUE THREAD

**Issue by Irru-** [spree/spree#7987]
If the local part of an email ends with "-", the email verification fails on the checkout process.

## Context
A customer tried to checkout but could not. After searching what went wrong I found out that saving her email on the admin side of the order did not work. 

I had a look at the email verification regex and it looks like if the local part of an email ends with '-' the email is considered invalid.

I tested it in my local development environment, and I was able to create an account with the email "spree-@example.com" just fine.

However, on checkout, I get an error that the "Customer E-mail is invalid".

**Comment by damianlegawiec** [comment]
@Irru- what version of Spree are you using?

**Comment by Irru-** [comment]
Currently using Spree 3.1 on Rails 4.2.6

**Comment by Irru-** [comment]
So, any news on this?

**Comment by clarke07** [comment]
@Irru-  can you tell me where the validation code is please? So I can turn it off, or modify the regex. Thanks.

**Comment by Irru-** [comment]
I've narrowed it down to the regex, so that will most likely have to be changed. Like I said in the OP, the only error I get is a popup saying "Customer E-mail is invalid" after trying to add a promotion.

**Comment by kgorazd** [comment]
This issue will be fixed in version 3.3.0.
