### ISSUE TITLE
DEPRECATION WARNING: Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in Rails 5.1.

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#7988]
## Context
running the test suite on master at [`3068902`](https://github.com/spree/spree/commit/3068902c7091c2d30906d91cb6df4754516c1408) returns the following deprecation warnings: 
```
DEPRECATION WARNING: Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in Rails 5.1. To explicitly halt the callback chain, please use `throw :abort` instead. (called from block (3 levels) in <top (required)> at /Users/jpowell/Desktop/spree/core/spec/models/spree/payment_spec.rb:126)
DEPRECATION WARNING: Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in Rails 5.1. To explicitly halt the callback chain, please use `throw :abort` instead. (called from block (3 levels) in <top (required)> at /Users/jpowell/Desktop/spree/core/spec/models/spree/payment_spec.rb:659)
DEPRECATION WARNING: Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in Rails 5.1. To explicitly halt the callback chain, please use `throw :abort` instead. (called from block in create_payments_from_params at /Users/jpowell/Desktop/spree/core/lib/spree/core/importer/order.rb:192)
```

I'm less familiar with this section of the code base. 

- **Any thoughts on how this should be handled?**

## Possible Fix
Suggestions are articulated nicely here: [Rails 5 does not halt callback chain when false is returned](http://blog.bigbinary.com/2016/02/13/rails-5-does-not-halt-callback-chain-when-false-is-returned.html)

## Steps to Reproduce

1. in `spree/core` run `bundle exec rspec spec`

## Your Environment

* Version used: master at [`3068902`](https://github.com/spree/spree/commit/3068902c7091c2d30906d91cb6df4754516c1408)

**Comment by tathspts** [comment]
can you tell me how were you able to run spree on rails 5.1 ?

**Comment by joshRpowell** [comment]
no longer an issue in 3.3.0.rc1
