### ISSUE TITLE
Spree permission checks in admin interface are not consistent

### ISSUE THREAD

**Issue by nimish-mehta** [spree/spree#7990]
## Issue

Spree admin interface permission checks are not consistent throughout the backend interface. This makes providing partial access to different parts of admin application difficult.

__For example:__

In this case spree links to product variants if the user has `admin` permission on variants:
https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/products/_form.html.erb#L89

In the configuration submenu, the permission checked is `manage` to provide a link to config option.
https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/shared/sub_menu/_configuration.html.erb#L2

Similarly in some pages, spree checks if `create` is allowed before adding create button.
https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/products/index.html.erb#L6

In other case the button is added directly:
https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/users/index.html.erb#L6

`link_to_delete`, `link_to_edit` helper methods do not check if user has delete/edit access to the resource.

## Possible Fix

Standardizing on a convention for each type of action and menu and then using it throughout the application.

**Comment by damianlegawiec** [comment]
Partially fixed via https://github.com/spree/spree/pull/8076
