### ISSUE TITLE
skip email validation while state change for payment

### ISSUE THREAD

**Issue by kumar-ravinder** [spree/spree#7994]
Hi , 
I customize user sign up and  order process for spree commerce. 
I want  user can sign up  without email  and it would be done and everything will be fine. But problem is arise when I process an order. When Order state change for  payment state , here I stuck  . Issue arise here "Customer email can't be blank". 

 Please suggest me any way or idea , that help me process a n order without user or customer email.

Thanks.

**Comment by damianlegawiec** [comment]
@kumar-ravinder you can overwrite this method https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L628 to skip email validation altogether
