### ISSUE TITLE
Hreflang / SEO / Spree commerce

### ISSUE THREAD

**Issue by ASTONLABS** [spree/spree#7995]
Has anyone used a plugin / gem or any other thing to have Hreflang tag implemented on Spree ? Is there a plugin / gem to have URL unique per language ?
thanks to everyone

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
Hi @ASTONLABS please ask this question on http://slack.spreecommerce.com/
