### ISSUE TITLE
Acts as List shuffling on zero item on Variants

### ISSUE THREAD

**Issue by jkelleyj** [spree/spree#7996]
When reordering a list in spree backend, it uses a zero index as the position for items in the list.  One example of this is on variants.  This makes the list position indexes run from 0 to N-1.  

If you later make ANY update to the item at the zero position (not just reordering), it is moved to 1 and the item at 1 is moved back to 0, swapping those two items.

The result is that we have items that inadvertently reorder.  

## Context
This issue impacts stores that rely on a specific ordering of varaints (or other reorderable object) since the first and second items in that list can reorder.  

## Expected Behavior
The list order should remain accurate for the first two items even if a property on either of them is touched.

## Actual Behavior
Item 0 and item 1 are flipped.

## Possible Fix
I think we have two options.  One is to change the implementation of sortable in the JS to use a starting index of 1 instead of 0.  The other is to update our use of `acts_as_list` to use the `top_of_list` property and set it to 0 instead of 1.  Either approach could have backwards compatibility issues since lists are currently stored in both 1 first and 0 first sequences.

Here's a simple fix we could drop in the JS in [backend/admin.js](https://github.com/spree/spree/blob/3-1-stable/backend/app/assets/javascripts/spree/backend/admin.js#L360) (just adding + 1 to the position)
```
$.each($('table.sortable tbody tr'), function(position, obj){
  reg = /spree_(\w+_?)+_(\d+)/;
  parts = reg.exec($(obj).prop('id'));
  if (parts) {
    positions['positions['+parts[2]+']'] = position + 1;
  }
});
```

A different solution which I like less is to update the ResourceController:
```
def update_positions
    ActiveRecord::Base.transaction do
      params[:positions].each do |id, index|
        model_class.find(id).set_list_position(index.to_i + 1)
      end
    end

    respond_to do |format|
      format.js { render text: 'Ok' }
    end
end
```

## Steps to Reproduce
1. Visit your variants page for a product and reorder the items. Note which item is now at top of the list
2. Edit some attribute of the item that is now at the to of the list
3. Observe in your variants list that this item has now moved to the second position

## Your Environment
Spree 3.1

**Comment by jkelleyj** [comment]
@damianlegawiec I'm curious for your take on the better approach to fix this when considering how to handle lists that could be in either a zero first or 1 first orientation now.

One thought is to go w/ 1 first (fix the JS) and then have a migration that does an update of all product variants where there is one in product's list that has a zero.  We also could ignore the migration since some stores may have some assumption built into their store about the starting index (or a dependency on specific positions).  

I'd say let's fix the JS not the acts_as_list inclusion and leave the migration alone

**Comment by damianlegawiec** [comment]
@jkelleyj fixing it on JS side + the migration seems to be the best approach! Can you submit a PR with those changes?

**Comment by krzysiek1507** [comment]
There is a [PR](https://github.com/spree/spree/pull/7785) with JS fix.

**Comment by jkelleyj** [comment]
Thank PR looks good to me.  That's the same tweak I made in my 3.1 installation.
