### ISSUE TITLE
Not able to pass additional attributes into ability.

### ISSUE THREAD

**Issue by stahor** [spree/spree#8003]
Hi there.
I want to implement abilities that depends on controller namespace as it described [here](https://github.com/ryanb/cancan/wiki/Authorization-for-Namespaced-Controllers). The problem is that it's not possible to pass additional arguments into your ability initializer. Any ideas what can be done here? Or maybe I just have to replace your abilities with my own one?

**Comment by bbonislawski** [comment]
I'd just replace abilities or override our ability initializer.
