### ISSUE TITLE
order products

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#8011]
controller does  `@products = @searcher.retrieve_products` 
but that somehow totally ignores ordering

i manually setted the orders to 1..9 and the others to 500

```

[52, 12, 70, 1]
[32, 12, 48, 2]
[23, 12, 39, 3]
[25, 12, 41, 4]
[24, 12, 40, 5]
[20, 12, 36, 6]
[19, 12, 35, 7]
[28, 12, 44, 8]
[31, 12, 47, 9]
[21, 12, 37, 500]
[18, 12, 34, 500]
[22, 12, 38, 500]
[26, 12, 42, 500]
[29, 12, 45, 500]
[30, 12, 46, 500]
[50, 12, 67, 500]

```

unfortunately the displayed order will be

`1,4,3,500, 9, 500  [....] `

anybody experienced that before?

**Comment by AnuragBhardwaj1** [comment]
spree_version ?

**Comment by krtschmr** [comment]
spree (3.1.0.rc3)
      spree_api (= 3.1.0.rc3)
      spree_backend (= 3.1.0.rc3)
      spree_cmd (= 3.1.0.rc3)
      spree_core (= 3.1.0.rc3)
      spree_frontend (= 3.1.0.rc3)
      spree_sample (= 3.1.0.rc3)

**Comment by AnuragBhardwaj1** [comment]
> i manually setted the orders to 1..9 and the others to 500
can you please explain ?

**Comment by AnuragBhardwaj1** [comment]
anyways it is working well for me with the given gemset
