### ISSUE TITLE
Spree 3.1.0.rc1 - Resource not found after enteting promotion code

### ISSUE THREAD

**Issue by atul-shimpi** [spree/spree#8021]
Environment
1) Ruby 2.3.3
2) Rails 4.2.6
3) Spree 3.1.0.rc1

Steps
1) Create promotion from admin panel
2) Check the advertise checkbox.
3) Specify any action and rule
4) Goto store and make some purchase and got to payment
5) Enter coupon code and press "Save and Continue" button

Actual Behaviour
1) Resource not found error message is displayed

Expected Behaviour
2) Coupong code should be accepted and applied

**Comment by atul-shimpi** [comment]
Also Promotions are not visible on home page when i check "Advertise" checkbox on promotion ui.
Apart form checking it, anything else needs to be done ?
This also may be bug in front end.

**Comment by atul-shimpi** [comment]
@damianlegawiec 
Even promotions are not visible.
Is this also bug ?
Any idea when both issues will be fixed?

**Comment by atul-shimpi** [comment]
@damianlegawiec 
Do you have quick fix for this. My client work is blocked for 2 weeks because of this.
His site needs to go live, but because of this its blocked.
Thanks in advance.

**Comment by symarys** [comment]
@atul-shimpi By default advertised option for promotions refers only to product pages. If you have a Product rule added for a promotion it will be visible on this specific product page. Like here:
![image](https://user-images.githubusercontent.com/10439953/27953540-769e2f7c-630c-11e7-85cf-666e6854e19d.png)

**Comment by symarys** [comment]
As for your second issue, I cannot reproduce it - I don't see this error. Can you provide more details, e.g. full trace?

**Comment by atul-shimpi** [comment]
I have given all the things in issue.

Someone has already accepted it as bug in FrontEnd.

Anyway let me see if i can get the trace.

The bug is comming on production.


With warm regards,
============================================================================
Atul Shimpi
Mobile : 9890979429 | Skype : shimpiatul | www.HiAtul.com


________________________________
