### ISSUE TITLE
Spree::Product.slug validates length to be minimum 3

### ISSUE THREAD

**Issue by vfonic** [spree/spree#8027]
I'm making an import of a store from Shopify. So far it's been going pretty well. (apart from the fact that Shopify's variants are not required to have a SKU)

But the other issue that's perplexing me is that there's a validation on product slug length. There is a product in the Shopify store that I'm importing and its Shopify handle is "4". This product's validation fails on import because the minimum slug length is 3 characters.

What's the reasoning behind this? I'm pretty sure there are valid products with one or two character-long names (3 - the mobile operator, HP, M&M...) If there's no particular reason, is it possible to get rid of this limit? I can provide a PR.

**Comment by damianlegawiec** [comment]
@vfonic let's get rid of it :)

**Comment by vfonic** [comment]
@damianlegawiec aye aye sir!

https://github.com/spree/spree/pull/8028
