### ISSUE TITLE
Could you please add a Dockerfile?

### ISSUE THREAD

**Issue by medyagh** [spree/spree#8038]
I followed every step of the developer docuemnts and I keep getting dependecy errors. I tried to find a Dockerfile. I couldnt find any Dockerfile on the project that works. could you please add one so I can give this project a try ?

**Comment by joshRpowell** [comment]
https://nanobox.io/what-is-nanobox/ could be helpful here.

**Comment by medyagh** [comment]
I need a docker so I can deploy it in kubernetes or in docker-compose or any container. plus it will best way to test locally too (since it will be same as my production). I recommend adding a Dockerfile to this project.

**Comment by jnorkus** [comment]
I am almost finished with a Dockerfile for my own development purposes. I can share it when I'm done but currently having this issue:
https://github.com/spree/spree/issues/7578

**Comment by amedrz** [comment]
@jnorkus any luck with the Dockerfile? I see the issue you linked has been closed. Will be great if you can share it.

**Comment by damianlegawiec** [comment]
We're using Docker at Spark company-wide and we're definitely incorporate Docker into Spree (for sandbox env). Thanks guys for bringing out this topic!

**Comment by bbonislawski** [comment]
Hacktoberfest update!
Maybe someone would try to create Dockerfile or share working one?

**Comment by AminArria** [comment]
Hi, I'm interested in doing the Dockerfile, but what are you looking for exactly? Do you want it to set up a basic installation in which then you would do: 
`rails new project`
`rails g spree:install`

**Comment by bbonislawski** [comment]
Hello @AminArria . Thanks for your will to help.

We'd like to have Dockerfile and docker-compose in application created with `rake sandbox` command so in future we could create image in docker hub so any person with docker could fetch image and setup own sandbox of spree. It would be good for people starting with new spree based projects too.

**Comment by AminArria** [comment]
Oh okey I think I get it. Do you prefer 1 PR for the Dockerfile and docker-compose or 1 for each?
