### ISSUE TITLE
Errno::EACCES: with rabl

### ISSUE THREAD

**Issue by ditmarbrynza** [spree/spree#8059]
Errno::EACCES: Permission denied @ rb_file_s_symlink -
(fixtures/ashared/views_rails_3/users/phone_number.json.rabl,
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashare
d/views_rails_3/users/phone_number.xml.rabl)
An error occurred while installing rabl (0.13.1), and Bundler cannot continue.
Make sure that `gem install rabl -v '0.13.1'` succeeds before bundling.

In Gemfile:
  spree was resolved to 3.2.1, which depends on
    spree_backend was resolved to 3.2.1, which depends on
      spree_api was resolved to 3.2.1, which depends on
        rabl

how i can solve this problem? i use windows 7 and rails 5. i can't install rable  '0.13.1' because

$ gem install rabl -v '0.13.1'
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (fixtures/ashared/views_rails_3/user
s/phone_number.json.rabl, c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/r
abl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl)

**Comment by erosinlove** [comment]
you can fix it by running the gem as Administrator.
(right mouse click on the terminal command and choose Run as Administrator menu)

**Comment by damianlegawiec** [comment]
Please submit this issue in https://github.com/nesquena/rabl repo

**Comment by ohiodn8** [comment]
I downgraded my _gem rabl_ to _'0.13.0'_  and followed @erosinlove advice by running `bundle install` as admin. . . Fixed it. . .

**Comment by TommyVasquez** [comment]
> you can fix it by running the gem as Administrator.
> (right mouse click on the terminal command and choose Run as Administrator menu)

solve my problem, in windows 10
