### ISSUE TITLE
Broken link in spree guide

### ISSUE THREAD

**Issue by nisanth074** [spree/spree#8066]
The Overview section in this [Spree Guide](https://github.com/spree/spree/blob/7206f1abe513779e810f5c6749c5e4e783d109bc/guides/content/developer/deployment/ansible-ubuntu.md) mentions this repo https://github.com/radar/ansible-rails-app. The repo however is not longer available. Github displays a 404 page when I click on the link.

**Comment by Qwertie-** [comment]
Maybe @radar could tell us where it went.

**Comment by Mirv** [comment]
I tried a tweet for giggles, not sure it went through - but also saw there were some failing upgrades mid 2016 ... maybe issues making it work in different versions?  http://cmdbac.cs.cmu.edu/repository/radar/ansible-rails-app/?page=11&types=Ruby+on+Rails

I'm not sure what ToS or license the ansible app was under (as it's gone), but there are other repo's out there that look like they were more current than ansible's meta tracking sites show ...

* https://github.com/aleks/ansible-rails

**Comment by radar** [comment]
Simple answer is that I deleted it because it was a few versions behind and I wasn’t maintaining it anymore.

**Comment by Mirv** [comment]
Ty!  Any recommendations for more current off the top of your head?
