### ISSUE TITLE
Sorting products by price (descending or ascending)

### ISSUE THREAD

**Issue by xdavipereira** [spree/spree#8068]
Is there any API filter to fetch list of products sorted by descend price or ascend price ?

i know that search is made by ransack like:

> /api/v1/products?q[s]=id%20asc,

 with id works nicely and a get the list of products sorted. 

but with price doesn't work.
there is any way sort products by price using api with ransack?

thanks.

**Comment by kitwalker12** [comment]
@xdavipereira you'd probably have to whitelist the price association (`Spree::Product.whitelisted_ransackable_associations |= ["prices"]`) and then have a query like `prices_amount asc`

**Comment by xdavipereira** [comment]
Thanks for the help. @kitwalker12 

I tried to add the prices on associations like tis:

spree.rb

`Spree::Product.whitelisted_ransackable_associations |= ["prices"]`

and i did this request 

`api/v1/products?q[s]=prices_amount%20asc`

i get a error 

```
ActionView::Template::Error (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...able_on <= '2017-06-16 20:02:34.258265') ORDER BY "prices_sp...
```
                                                             ^
```: SELECT  DISTINCT "spree_products".* FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL LEFT OUTER JOIN "spree_variants" "variants_spree_products_join" ON "variants_spree_products_join"."product_id" = "spree_products"."id" AND "variants_spree_products_join"."is_master" = $2 AND "variants_spree_products_join"."deleted_at" IS NULL LEFT OUTER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".discontinue_on IS NULL or "spree_products".discontinue_on >= '2017-06-16 20:02:34.258381') AND ("spree_products".available_on <= '2017-06-16 20:02:34.258265') ORDER BY "prices_spree_products"."amount" ASC LIMIT $3 OFFSET $4):```


I'm new to rails, did I do anything wrong?

**Comment by maikis** [comment]
Hi, I'm also wondering if there is some product sorting solution for product page and taxon's pages (by price, name, frequently purchased, newest, etc.)? It is vitally important for every shop to allow it's users to have at least basic sorting by price, but as far as I googled there is nothing that works by default?

**Comment by bbonislawski** [comment]
AFAIK there is no out-of-the-box solution for that and you'd have to implement it by yourself. It won't be hard! 

Create decorator for ProductsController like that(I included original index method from Spree API so you can just edit it a little bit):

```ruby
Spree::Api::V1::ProductsController.class_eval do
  def index
    if params[:ids]
      @products = product_scope.where(id: params[:ids].split(',').flatten)
    else
      @products = product_scope.ransack(params[:q]).result
    end

    @products = @products.distinct.page(params[:page]).per(params[:per_page])
    expires_in 15.minutes, public: true
    headers['Surrogate-Control'] = "max-age=#{15.minutes}"
    respond_with(@products)
  end
end
```
and add sorting params with ransack like this: https://github.com/activerecord-hackery/ransack/wiki/Sorting-in-the-Controller

**Comment by JonathanKolnik** [comment]
@bbonislawski what would be the path of a decorator like that?

Thanks!

**Comment by kitwalker12** [comment]
@JonathanKolnik `app/controllers/spree/api/v1/products_controller_decorator.rb`

**Comment by JonathanKolnik** [comment]
@kitwalker12 thanks for the quick reply! I can't seem to hit a byebug there. Maybe I am in the wrong area of the code though. I'm trying to convert the frontend search into a global search. I can't seem to figure out what I'm doing wrong so I was hoping to see what params I was passing to the backend. I rendered https://github.com/spree/spree/blob/master/frontend/app/views/spree/shared/_search.html.erb in my global nav and that is clearly causing some issues. I can't seem to get the search to include products outside of the current path.

For example if I am at the path /shop/t/categories/vegetables and I want to search for apples which is a product under the fruit taxon, I won't have any results because it is only searching products within the vegetables taxon.

Sorry for the lengthy question, any hints of which direction to go in would be awesome!
