### ISSUE TITLE
need a guide to install spree on rails 5.1 and 5.0

### ISSUE THREAD

**Issue by troias** [spree/spree#8080]
tried to install spree but to no avail. please write a short guide as the one on your website is outdated and all the responses on the issues sections are not clear. I use spree 3.21 and tried on rails 5.1 and 5 and still does not work.

**Comment by troias** [comment]
@damianlegawiec

**Comment by damianlegawiec** [comment]
Duplicate of https://github.com/spree/spree/issues/8080
