### ISSUE TITLE
Duplicate error messages on staging/production servers

### ISSUE THREAD

**Issue by tonyvince** [spree/spree#8082]
**This issue happens only on staging and production servers**

I have added a new field `my_field` to `spree_users` table and then add validation for that field in `user_decorator.rb`. 

`validates_presence_of   :my_field, message: 'Please enter MyField'`

On the update user info page, I add a new input for `my_field`. 

```
<%= f.select :my_field, [], { prompt: false }, class: 'my-class' %>
<%= f.error_message_on :my_field %>
```

When I leave that field empty and submit, it shows the error as followings:

2 errors prohibited this record from being saved:

Please enter MyField
Please enter MyField

## Expected Behavior
1 error prohibited this record from being saved:

Please enter MyField

## My Environment
spree (2.2.13)
ruby 2.1.4
Rails 4.0.13

**Comment by tonyvince** [comment]
I think this issue is similar to #7143

**Comment by damianlegawiec** [comment]
@tonyvince this was fixed in Spree 3.x, if possible please upgrade, we do not support Spree 2.2 anymore
