### ISSUE TITLE
Setting Spree::Config[:track_inventory_levels] to false does not seem to allow setting on hand values

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8097]
I have an external system which keeps track of all stock and I want to be able to simply set the stock on hand for each variant. In the docs [here](http://guides.spreecommerce.org/developer/inventory.html) it says you can add `Spree::Config[:track_inventory_levels] = false` to your config and you will able to set on hand values but after adding that and going to the products stock page I am still asked to add a stock location before adding stock.

## Possible Fix
Because I have been playing around with the stock before setting this option maybe this has caused the issue and I need to set the option before doing anything.

Edit: I set up a new database with the config line set to begin with and added new products and the issue remains.

## Your Environment
ruby '2.4.1'
gem 'rails', '\~> 5.0.2'
gem 'spree', '\~> 3.2.1'
gem 'spree_auth_devise', '\~> 3.2.0.beta'
gem 'spree_gateway', '\~> 3.2.0.beta'

**Comment by batalla3692** [comment]
+1
I have the same problem setting default logo preference. In both `spree.rb` initializer and `rails console` I cannot change the default value.
My environment is almost the same as @Qwertie-

**Comment by damianlegawiec** [comment]
@batalla3692 please upgrade to `3.4.4`
