### ISSUE TITLE
Update and show products using sku in spree api

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8102]
If you have an external system which manages stock and prices having a way to access and update products using the sku would solve a whole lot of database queries. Because the sku is the same in both systems you can just send a POST request right away rather than having to download the whole product list and work out which sku maps to which slug

**Comment by damianlegawiec** [comment]
@Qwertie- you can query products by sku like this:

```
/api/v1/products?q[sku_eq]=YOUR_SKU
```

**Comment by Qwertie-** [comment]
@damianlegawiec Does that return one result with the exact thing you search? When you search a sku in the admin panel It sometimes returns multiple results if the skus are similar.

**Comment by damianlegawiec** [comment]
@Qwertie- this will return only one result (or multiple if you've got multiple products with exactly the same SKU)

**Comment by Qwertie-** [comment]
When I run 
`curl -g -H "X-Spree-Token:  TOKEN" http://localhost:3000/api/v1/products?q[sku_eq]=168250`
I get back 58 pages of results but if I look up the product with its slug
`curl -g -H "X-Spree-Token:  TOKEN" http://localhost:3000/api/v1/products/cc-resorts-floria-multi-s41`
I get back just that one product

`{"id":168250,"name":"CC RESORTS FLORIA MULTI S41","description":null,"price":"21.99","display_price":"$21.99","available_on":"2017-07-05T04:28:50.324Z","slug":"cc-resorts-floria-multi-s41","meta_description":null,"meta_keywords":null,"shipping_category_id":1,"taxon_ids":[],"total_on_hand":null,"master":{"id":1432,"name":"CC RESORTS FLORIA MULTI S41","sku":"168250","price":"21.99","weight":"0.0","height":null,"width":null,"depth":null,"is_master":true,"slug":"cc-resorts-floria-multi-s41","description":null,"track_inventory":false,"cost_price":null,"option_values":[],"images":[],"display_price":"$21.99","options_text":"","in_stock":true,"is_backorderable":false,"is_orderable":true,"total_on_hand":null,"is_destroyed":false},"variants":[],"option_types":[],"product_properties":[],"classifications":[],"has_variants":false}`
