### ISSUE TITLE
Two Promos won't apply

### ISSUE THREAD

**Issue by quesurifn** [spree/spree#8110]
## Context
I am trying to set one blanket promo for all orders over $100 without the need for a code and have another promo with a code required that discounts 30%. 

The blanket promo works when the 30% code is not used. 

If I put in the 30 percent of promo on orders over 100, both adjustments will show in 'adjustments' under the order but the promo for orders over 100% won't actually be applied. 
## Expected Behavior

Both promos are applied. 

## Actual Behavior

Only the 30% off promo is applied. 

[Image](http://imgur.com/a/B76m4)
## Possible Fix
?

## Steps to Reproduce

1. Go into spree and create a promo for 30% off with code 30Off
2. Then create a separate promo with no code, for orders over 100% to discount shipping. 
3. Checkout with an order over $100 and use code 30Off
4. Only the 30 percent off will be applied however both adjustments will show in the order's adjustments

## Your Environment

* Version used: 3.1.0
* Gemfile and Gemfile.lock as text in a Gist: N/A

**Comment by quesurifn** [comment]
@radar Any ideas?

**Comment by krzysiek1507** [comment]
Hi @quesurifn I can see that it works on Spree 3.1.5. Are you able to upgrade your application?

**Comment by krzysiek1507** [comment]
I can also check on Spree 3.1.0 and it works too. Do you have any changes in your code for orders/promos?

**Comment by quesurifn** [comment]
@damianlegawiec Why was this issue closed before I could respond? @krzysiek1507 Thank you for taking an interest in this. The promotion system has been modified to restrict free shipping.

I placed the following code in models/spree/promotions/rules folder:

```
module Spree
     class Promotion
       module Rules
         class RestrictFreeShipping < PromotionRule
           MATCH_POLICIES = %w(all)
   
           def eligible?(order, options={})
             e = false
             if order.shipment.shipping_method.admin_name == "FedEx Standard"
               e = true
             else
               e = false
             end
            return e
           end
        end
      end
    end
  end   
```


Otherwise, look at the photo I posted in the original comment. It seems that its applied as an adjustment but the adjustment isn't added on to the total. 

Any ideas?

**Comment by krzysiek1507** [comment]
@quesurifn could you please comment it out this code and then test it locally?

**Comment by quesurifn** [comment]
@krzysiek1507 Commenting out or removing code and directories have no effect on this bug. @damianlegawiec Can you re-open issue? Nothing was figured out.
