### ISSUE TITLE
`balance_due` payment state after a partial refund

### ISSUE THREAD

**Issue by dannygreg** [spree/spree#8136]
If you initiate a partial refund on any order (for sake of example here, let's say an RMA is not possible but you still wish to partially refund the customer) the payment state becomes stuck in `balance_due`, despite being fully paid up.

I believe this is down to `outstanding_balance` [not taking refunds into account](https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L327). 

This is nearly identical to #6229 and I believe the fix used in #6249 will work here, if expanded to include `order.refunds` as well as `order.reimbursements`.

## Steps to Reproduce

1. Place an order
2. Use the `[-]` (refund) button on the payments tab in the admin view for that order
3. Make a partial refund

## Expected Results

The customer should be refunded the specified amount and the order should still be in the `paid` payment state.

## Actual Results

The customer is refunded, however the payment state of the order becomes `balance_due`.

## Environment

* Version 3.2.1

---

I'm more than willing to submit a PR to fix this but I wanted to ensure my mental model was correct before submitting a patch.

**Comment by symarys** [comment]
@dannygreg Hello Danny, your issue has been solved on master branch (https://github.com/spark-solutions/spree/commit/319f1fc665db821f7f94041f0188c3e206313666).
