### ISSUE TITLE
Feature: Clarify why a product cannot be deleted.

### ISSUE THREAD

**Issue by digitalextremist** [spree/spree#8141]
The `Products` view allows deletion of rows, but if a product is present in an order ( completed or not, could just be an uncheckedout cart ) the row cannot be deleted. The flash message at that point only says: `Product could not be deleted.`

I think it would be great if the error message said why the product cannot be deleted. At the very least, how many instances of the product existing in orders are keeping it alive.

Very minor and unimportant thing, once you know a product could only be in a cart and not even purchased for it to be undeletable. In testing, especially for new users, this can be confusing. I just began using `Spree`, and this was the first and only thing that actually made me frustrated for lack of an explanation.

**Comment by Qwertie-** [comment]
I think I hit this same issue a few days ago. Product wont delete from the admin page but will delete from the rails console (This likely breaks the cart for the user who had the item in their cart)

**Comment by bbonislawski** [comment]
Hacktoberfest update! It's quite easy to do in https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/products_controller.rb#L49

**Comment by waleolakareem** [comment]
I am having a problem with this issue, I try deleting products and it would not. What is the best way to debug this
