### ISSUE TITLE
The asset "jquery.validate/localization/messages_zhcn.js" is not present in the asset pipeline

### ISSUE THREAD

**Issue by chonglou** [spree/spree#8146]
### Versions
Ruby: 2.4.1
Rails: 5.1.2
Spree: 3.3.0.rc1

### Happen when locale is zh-CN

Rendered ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spree_frontend-3.3.0.rc1/app/views/spree/checkout/edit.html.erb within spree/layouts/spree_application (244.0ms)
Completed 500 Internal Server Error in 342ms (ActiveRecord: 15.1ms)

  
ActionView::Template::Error (The asset "jquery.validate/localization/messages_zhcn.js" is not present in the asset pipeline.):
    46: </script>
    47: 
    48: <% if I18n.locale != :en %>
    49:   <%= javascript_include_tag 'jquery.validate/localization/messages_' + I18n.locale.to_s.downcase.gsub('-', '') %>
    50: <% end %>
  
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:83:in `compute_asset_path'

```
ls ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spree_frontend-3.3.0.rc1/vendor/assets/javascripts/jquery.validate/localization/messages_zh*.js
messages_zh.js  messages_zhtw.js
```
And after I "cp messages_zh.js messages_zhcn.js", it works right.

Thanks.

**Comment by symarys** [comment]
@chonglou Your issue has been solved on the master branch (https://github.com/spree/spree/commit/e3f8750385b621514fb65667a705274c643dca5e).
