### ISSUE TITLE
Multiple price level functionality 

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8147]
Would be really helpful to have a way to set multiple price levels for products

## Context
Quite often a business might be selling to consumers and resellers and it is always a requirement that the resellers get lower prices than regular users. 

## Expected Behavior
Quite like how multiple currencies work where you get a new tab on product pages where you can enter in the prices for each level (Usually named like Level A, Level B, Level C).

Admins can then set a users price level in the user admin page (Often accounting software has a field for price level as well so it could be imported using the spree api)

When the user is logged in they now see the price according to their price level, if no price is set they see the default price

## Workaround
Currently to get this working I have been abusing the multiple currencies gem and adding in 3 currencies and overriding the display so it looks like its all the same currency on the product page.

**Comment by bbonislawski** [comment]
It's not something that everyone would use so I'd propose to create is a separate gem. Since this is not an issue with spree, I'm closing this

**Comment by jaddison** [comment]
Is there a recommended way to approach the problem as originally reported above? ie. different pricing levels per user 'type' or 'role'

https://github.com/spree-contrib/spree_price_books looks like it might have been intended for this sort of thing, but I'm not certain.
