### ISSUE TITLE
Cannot update [total_on_hand] via API

### ISSUE THREAD

**Issue by andrewkmin** [spree/spree#8151]
## Context
Using Postman to make API changes at endpoint ```/api/products/1```. Spree token is all good to go; I'm able to update all fields except for "total_on_hand" for some reason. It simply does not change.

## Expected Behavior
I'm expecting that a PUT request to the endpoint ```api/products/1?product[total_on_hand]=100``` to modify that product and give it a property ```total_on_hand``` of 100. 

## Actual Behavior
No update is made.

## Possible Fix
Not sure.

## Steps to Reproduce
1. Make requests somehow (using Postman, AJAX, etc)
2. Include spree token as header
3. Ping correct endpoint
4. Observe that for everything except for ```total_on_hand```, fields are updated.

## Your Environment
Postman

**Comment by bbonislawski** [comment]
@andrewkmin thanks for reporting but it's not a bug. `total_on_hand` is not a field in product model. It's value calculated based on stock_items so it cannot be updated like that. You should update stock items in this product instead of updating total_on_hand
