### ISSUE TITLE
Spree header takes far too much room on mobile

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8152]
![screenshot](http://i.imgur.com/ahmUwrY.png)

Most of the page is used by the header when it could just collapse with a button to expand it. I assume most people are just replacing the whole nav bar because its quite a job trying to get the current one to work properly on small screens.

**Comment by damianlegawiec** [comment]
Yes, the current frontend design isn't 100% RWD. It's going to be completely overhauled in coming releases with a mobile-first approach in mind.

**Comment by mikeyduece** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by damianlegawiec** [comment]
Hi @mikeyduece we're happy to get your help on this issue! All Contributements are always welcome! Thank you :)

**Comment by bbonislawski** [comment]
Already fixed on master
