### ISSUE TITLE
Not setting master price for product gives obscure error 'invalid value for BigDecimal(): ""'

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8161]
When creating or updating a product if you don't set a master price you get taken to the rails error page showing `invalid value for BigDecimal(): ""`.

Because this affects the user side of things there should be a simple flash showing that the product needs to have a master price before being saved.

**Comment by delphaber** [comment]
I think it's already fixed in master (https://github.com/spree/spree/commit/0edb74860b)

I have the same problem but I'm using `spree` 3.2.2

**Comment by damianlegawiec** [comment]
@delphaber backporting it to `3-2-stable` and we'll release `3.2.3` mid-week this week

**Comment by damianlegawiec** [comment]
@Qwertie- @delphaber 3.2.3 is available from RubyGems :)

**Comment by delphaber** [comment]
@damianlegawiec thanks!
