### ISSUE TITLE
Showing malformed price in Checkout (BRL)

### ISSUE THREAD

**Issue by TADebastiani** [spree/spree#8164]
My demo store is set to BRL Currency, when I change the Shipping Method on Checkout.

Before change Shipping Method.
![checkout1](https://user-images.githubusercontent.com/8689599/28541695-55e845a6-7090-11e7-8c52-524142d694d0.png)

After change Shipping Method. The Shipping value is set to 'R$26,00'
![checkout2](https://user-images.githubusercontent.com/8689599/28541694-55e5a896-7090-11e7-90da-44cbbc83acc5.png)

Sorry for bad English :)

**Comment by bbonislawski** [comment]
Can you provide more details like spree version, rails version, ruby version, browser? I've tried to reproduce it and I couldn't
![screen shot 2017-09-15 at 12 00 30](https://user-images.githubusercontent.com/7106611/30477517-b58fa57a-9a0d-11e7-988c-032e6b54d56e.png)
and after change
![screen shot 2017-09-15 at 12 00 34](https://user-images.githubusercontent.com/7106611/30477516-b571f94e-9a0d-11e7-953b-50f338e29166.png)

**Comment by bbonislawski** [comment]
AFAIK it's fixed in #8212 so updating your spree should fix the issue
