### ISSUE TITLE
Image attachment_width and attachment_height aren't set in Spree 3.3.0.rc1

### ISSUE THREAD

**Issue by dylanfisher** [spree/spree#8167]
## Context
Spree::Image

`before_save :find_dimensions, if: :saved_change_to_attachment_updated_at?`

## Expected Behavior
The before_save callback in Spree::Image should set the image `attachment_width` and `attachment_height`

## Actual Behavior
`saved_change_to_attachment_updated_at?` callback never runs, and width and height aren't set.

## Possible Fix
Revert this commit https://github.com/spree/spree/commit/a5f6147bda172a4d02bc23f621e1b669ffd5d55f

## Your Environment
Rails 5.1.2
ruby 2.4.0p0
`'spree', '~> 3.3.0.rc1'`
`'spree_gateway', '~> 3.3.0.rc1'`

**Comment by damianlegawiec** [comment]
Thanks @dylanfisher for pointing this out 👍

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8178
