### ISSUE TITLE
Gems adding failed 

### ISSUE THREAD

**Issue by augmen** [spree/spree#8168]
`gem 'spree', '~> 3.3.0.rc1'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command spree,
root@spree:~/mystore# gem 'spree_auth_devise', '~> 3.3'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command spree_auth_devise,
root@spree:~/mystore# gem 'spree_gateway', '~> 3.3'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command spree_gateway,
root@spree:~/mystore# gem add 'spree', '~> 3.3.0.rc1'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command add
`

please guide how to add the spree gems to file

**Comment by damianlegawiec** [comment]
You need to place that code in your project Gemfile not use them in command line..

**Comment by augmen** [comment]
is spree is open source ? what are alternatives ?
Swapnil Bhadade
swapnilrbhadade83@gmail.com
Nagpur
India
