### ISSUE TITLE
Shipping cost re-calculating bug when using comma as cents separator

### ISSUE THREAD

**Issue by maikis** [spree/spree#8195]
In some localisations, like German or Lithuanian, or just after setting the cent separator to comma by hand in initializer, CoffeeScript misscalculates shipping and total prices (line items + shipping).

## Context
When there is more than one shipping method allowed and buyer selects other than default (first) shipping method, the total price of order is re-calculated by CoffeeScript `(spree/frontend/checkout/shipment.js.coffee)`. This code has regexp, which removes special characters (like commas) from the costs:

```
REGEX_FOR_REMOVING_SPECIAL_CHARS = /[^0-9\.]+/g
```

This makes no problem when dot is used to separate cents in price, like: `$ 22.00`. But when it comes to using comma instead of dot (like Lithuanian: `$ 22,00`), then after removing the special characters the price becomes `$ 2200`. This results as a wrong shipping and order total prices after re-calculation.

## Expected Behavior

After selecting other than primary shipping method, prices should stay the same no matter which symbol is used to separate cents.

## Actual Behavior

If buyer select's other than primary shipping method, shipping and total prices are re-calculated wrong, because of incorrect removal of cent separator.

## Possible Fix

Maybe we should use some JavaScript or CoffeeScript library for handling currencies properly, or query Rails part to re-calculate the prices.

## Steps to Reproduce

1. Set Spree::Money currency separator in the `spree.rb` initializer to use comma as cent separator:

```
Spree::Money.default_formatting_rules[:decimal_mark] = ','
Spree::Money.default_formatting_rules[:thousands_separator] = '.'
```

2. After starting the application add some shipping methods with some price (like 1,00). More than one shipping method is needed (at least two).
3. Go to the shop and add some items to the shopping cart.
4. Click `Checkout` and navigate to `Delivery` tab.
5. First shipping method will be selected by default. Select other shipping method and watch `Shipping total` and `Order total` values change.

## Your Environment

* Version used:
```
Spree 3.2 and 3.3.0.rc1.
Rails 4.2 and 5.1
```

**Comment by damianlegawiec** [comment]
Thanks @maikis for pointing this out

**Comment by maikis** [comment]
You're welcome @damianlegawiec! We are all on the same page here. I would be willing to contribute and fix this if you could give me some insights on this, like what would be preferred way to fix it (or should I do as it looks best to me), can I use some currency libraries or should we try to avoid that, etc.

**Comment by damianlegawiec** [comment]
@maikis probably using a library like [accounting.js](https://github.com/openexchangerates/accounting.js) would be better than writing a [custom javascript](https://github.com/spree/spree/blob/master/frontend/app/assets/javascripts/spree/frontend/checkout/shipment.js.coffee) . I'm not a fan of adding more dependencies but as we move forward with a more javascript heavy UI this would be reused across frontend/backend. 

Our long-term plan for the customer frontend is to be more modern and API-based.

Any other suggestions and ideas are more than welcome :)
