### ISSUE TITLE
Update dependencies for save version of nokogiri

### ISSUE THREAD

**Issue by factor4** [spree/spree#8201]
Hello! I´m on spree 3.1 and want to update nokogiri to version 1.7.2 because older Versions are vulnerable.

## Context
Here is the output of `bundle update nokogiri`

```Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    nokogiri (~> 1.7.2)
    spree_i18n was resolved to 3.1.0, which depends on
      spree_core (~> 3.1.0.beta) was resolved to 3.1.6, which depends on
        deface (~> 1.0.0) was resolved to 1.0.2, which depends on
          nokogiri (~> 1.6.0)
```

## Expected Behavior
bundle update successfully complete

## Actual Behavior
bundle update fail

## Possible Fix
Update spree_core 3.1.x dependencies to support deface ~> 1.2.0 witch support higher versions of nokogiri: https://github.com/spree/deface/issues/170

**Comment by damianlegawiec** [comment]
Will be fixed with 3.1.7 release https://github.com/spree/spree/pull/8202

**Comment by factor4** [comment]
Thanks! 👍

**Comment by damianlegawiec** [comment]
@factor4 3.1.7 is available from rubygems :)

**Comment by factor4** [comment]
Wow! What a quick fix! Thank you!!!
