### ISSUE TITLE
Shipments are split up by backorder even if stock splitter is set to not split in spree.rb

### ISSUE THREAD

**Issue by haukurhrafn** [spree/spree#8204]
## Context

We just upgraded from Spree 3.0 -> 3.1 and are seeing shipments split up by backordered items even if we've set the stock splitter to not split them up. This was working for us in version 3.0.

## Expected Behavior

When order contains products that are in stock and backorderable products that are not in stock the shipments should not be split up if the Stock_Splitter has been configured:
`Rails.application.config.spree.stock_splitters = []`
See [documentation](https://github.com/spree/spree/blob/7fb31d3c48ab6f414a3af8c5e929b67c46f5527a/guides/content/developer/core/shipments.md)

## Actual Behavior

Shipments are split into two packages, one with products that are in stock and one with products that are not in stock but are backorderable.

## Steps to Reproduce

1. Set up a clean Spree v. 3.1
2. In spree.rb initalizer insert:
`Rails.application.config.spree.stock_splitters = []`
3. Set a product to be out of stock and backorderable.
4. Order a product that is in stock and a product that is not in stock but is backorderable.
5. At checkout you'll see two shipments with double cost.

## Your Environment

* Version used: 3.1
* Gemfile and Gemfile.lock as text in a Gist:
```
gem 'spree', '~> 3.1.0.rc1'
gem 'spree_auth_devise', '~> 3.1.0.rc1'
gem 'spree_gateway', '~> 3.1.0.rc1'
```

* Any relevant stack traces ("Full trace" preferred):

**Comment by AhmedAliIbrahim** [comment]
any updates for this issue ?

**Comment by artplan1** [comment]
I had same problem

fixed by using this code in my app's `spree.rb`:

```ruby
Rails.application.config.after_initialize do |app|
  app.config.spree.stock_splitters << Spree::Stock::Splitter::VendorSplitter
end
```

Problem is that this code ran after `spree.rb` code

```ruby
initializer 'spree.register.stock_splitters' do |app|
        app.config.spree.stock_splitters = [
          Spree::Stock::Splitter::ShippingCategory,
          Spree::Stock::Splitter::Backordered
        ]
      end
```

@bbonislawski @damianlegawiec 
It's better to update docs or maybe it's better to change `Spree::Core::Engine` `initializer 'spree.register.stock_splitters'` to run earlier?

Also I want to add tests for this issue, but not sure where
