### ISSUE TITLE
Api query search on Spree 3.3.0.rc3

### ISSUE THREAD

**Issue by xdavipereira** [spree/spree#8207]
When updating the spree version from 3.2 to 3.3.0.rc3 the following query no longer works

the query is this: 
`api/v1/products?q[s]=created_at+asc`

the error on console is this:

```
ActionView::Template::Error (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...able_on <= '2017-08-04 20:25:44.028715') ORDER BY "spree_pro...
```

in my gemfile i have this:
```
gem 'spree', '~> 3.3.0.rc3'
gem 'spree_gateway', '~> 3.3'
```
Worked perfectly with 3.2. Have there been any changes in the way queries are done in this new version?
I have to set the query params on products white list ?

**Comment by damianlegawiec** [comment]
This is probably a rails bug fixed via https://github.com/rails/rails/pull/29848 , waiting for 5.1.3 release containing this fix, until then we'll try to fix it on our end

**Comment by SylarRuby** [comment]
I see you're using PG, I suppose?
