### ISSUE TITLE
Feature: disable coupons with an app config parameter

### ISSUE THREAD

**Issue by otlaitil** [spree/spree#8211]
I was wondering if anyone else would like to see a feature to disable coupons with an app config setting. 

I have implemented two Spree-based storefronts in which both I was asked to remove coupons from checkout flow. Removing the HTML elements from DOM with Deface will break the Spree checkout javascript, so hiding them with CSS is the easiest solution at the moment (but feels a bit silly).

The setting would be something like:

`preference :enable_coupons, :boolean, default: true` (or inverse, `disable_coupons`)

If this would be something others would benefit from as well, I could sketch a PR of the feature.

**Comment by damianlegawiec** [comment]
@otlaitil sure, it would be nice to have this as a configuration option
