### ISSUE TITLE
Adding a product with a name of 2 charactors fails "slug"=>["is too short (minimum is 3 characters)"

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8227]
## Context
I have started importing my product list into spree using the api but one of my products causes an error (The movie "up") because the slug created is to short.

## Expected Behavior
Either the slug be accepted or a uuid is placed after the product name similar to what happens when you create two products with the same slug. Because I am not manually setting a slug the one created by spree should not cause an error.

## Actual Behavior
Invalid resource. Please fix errors and try again.
{"slug"=>["is too short (minimum is 3 characters)"]}

## Your Environment
gem 'spree', '\~> 3.2.1'
gem 'spree_auth_devise', '\~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'

**Comment by damianlegawiec** [comment]
@Qwertie- this is fixed in 3.3, we'll backport it to 3.2 line in later patch releases

**Comment by bbonislawski** [comment]
done with #8321
