### ISSUE TITLE
Split Order Payment by Authorizing each shipment separately

### ISSUE THREAD

**Issue by aminhs** [spree/spree#8230]
Braintree does not support partial payments in a single order authorization with more than one shipment when I set auto_capture_on_dispatch = true in Spree. It works for the first capture attempt but on second attempt will raise below error.

Gateway Error
 --- !ruby/object:ActiveMerchant::Billing::Response
params:
 braintree_transaction: 
 message: Cannot submit for settlement unless status is authorized. (91507)
 success: false 

I am working in a project where the store will have multiples sellers and trying to test this auto_capture_on_dispatch with Braintree gateway, it is not working as expected. 

I think this error can be solved if instead of authorizing the order total amount Spree authorizes each shipment separately having different transaction at the end. In other words, to create as many payment authorization as shipments in a single order. Is this technically possible? Can someone put me in the right track on this? How can I implement this approach in Spree?

I am looking multiples Spree code lines: 

https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L82

https://github.com/spree/spree/blob/master/core/app/models/spree/order/payments.rb#L22

https://github.com/spree/spree/blob/master/core/app/models/spree/payment/processing.rb#L10

https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L215

https://github.com/spree/spree/blob/master/core/app/models/spree/shipment.rb#L183

https://github.com/spree/spree/blob/master/core/app/models/spree/shipment_handler.rb#L20

**Comment by aminhs** [comment]
Any idea how to authorize order total payment by shipments instead of authorizing the entire order.total ?? 
I was thinking something like retrieving all order shipments 
shipments.each do |shipment|
   amount = shipment.final_price_with_items
  #authorize! somehow
end

**Comment by bbonislawski** [comment]
It's probably hard to achieve, but it's possible. Unfortunately, `issues` is not good place for asking questions so if you need help, please join our slack and ask questions there
