### ISSUE TITLE
pluck.sum to sum

### ISSUE THREAD

**Issue by lelelelemon** [spree/spree#8235]
core/app/models/spree/payment.rb:      offsets.pluck(:amount).sum
core/app/models/spree/tax_rate.rb:        pluck(:amount).sum

could be changed to 
offsets.sum(:amount)
sum(:amount)
it's similar with pull request https://github.com/spree/spree/pull/6950

**Comment by damianlegawiec** [comment]
Good catch 👍

**Comment by lelelelemon** [comment]
Also, 
/core/app/models/spree/shipping_calculator.rb      18: content_items.map(&:amount).sum"
core/app/./models/spree/exchange.rb:17:      Spree::Money.new @reimbursement_objects.map(&:total).sum
core/app/./models/spree/tax_rate.rb:47:        pre_tax_amount /= (1 + included_rates.map(&:amount).sum)
core/app/./models/spree/stock/package.rb:54:        matched_contents.map(&:quantity).sum

The map(:xx).sum can also be replaced by sum(xx) which will be a little bit faster.

**Comment by tanmay3011** [comment]
Hey @lelelelemon, Feel free to raise a PR.

**Comment by lelelelemon** [comment]
will do that soon
