### ISSUE TITLE
SSL link in description guides.spreecommerce.org is not working. Works without SSL

### ISSUE THREAD

**Issue by swapab** [spree/spree#8236]
![spree spree spree is a complete open source ecommerce solution for ruby on rails](https://user-images.githubusercontent.com/1291980/29484686-8c8d5140-84e1-11e7-8746-0156bbf07fe0.png)

Link in description is not working https://guides.spreecommerce.org/

## Possible Fix

1. https://guides.spreecommerce.org/ should work (Recommended)
2. OR update the link to use non-secured link http://guides.spreecommerce.org/

**Comment by damianlegawiec** [comment]
fixed
