### ISSUE TITLE
Some API returns HTML instead of an error message if you don't set the price.

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8238]
## Context
When creating a new product with the API if you send nil for the price instead of getting an error about this you get a full HTML/CSS/JS page.

## Expected Behavior
An error such as "(Must supply price for variant or master.price for product.)".

## Actual Behavior

`<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8" /> <title>Action Controller: Exception caught</title> <style> body { background-color: #FAFAFA; color: #333; margin: 0px; } body, p, ol, ul, td ` 
And so on...

## Possible Fix
Likely related to #8161.

## Steps to Reproduce
Create a product with price set to nil. I haven't tested this on a new spree application to check if it was something I modified that broke it but my spree setup is pretty close to stock and I haven't touched anything related to this.

## Your Environment
```
gem 'spree', '~> 3.2.1'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'
```

**Comment by damianlegawiec** [comment]
@Qwertie- this is fixed in 3.2.3, just run `bundle update spree`

https://github.com/spree/spree/releases/tag/v3.2.3
