### ISSUE TITLE
The admin gets 500 error when tries to add stock transfer without variant

### ISSUE THREAD

**Issue by wojtekwisniewski** [spree/spree#8251]
## Context
As an Admin I tried to add a new stock transfer. There was no information that I should fill the variants field in order to proceed further.

## Expected Behavior
The admin should be informed with a flash message that he cannot add new stock location without the variant.

## Actual Behavior
The admin experience 500 error when tries to add stock location without the variant.

## Possible Fix
A simple flash message that informs the admin about the filled variant field.

## Steps to Reproduce
1. Log in as an Admin on default 3.3 spree
2. Proceed to Stock Transfer tab
3. Press Add New Stock Transfer
4. Try to add transfer stock without adding a new variant
5. Observe the issue (you will experience 500 error)

## Your Environment
Chrome ver. 60.0.3112.101 Windows 10
Spree version: 3.3

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8254
