### ISSUE TITLE
In My Account tab there is no information about Store Credits

### ISSUE THREAD

**Issue by wojtekwisniewski** [spree/spree#8261]
## Context
Whenever the User enters My Account tab there is no information present about Store Credits. The user is not informed in any way how much Store Credits he still owns.

## Expected Behavior
For the User value of Store Credits should be present always in My Account tab.

## Actual Behavior
The user is not informed in any way how much Store Credits he still owns.

## Steps to Reproduce
1. As an Admin enter Users tab and add to the User Store Credits value
2. Log out and log in as previously mentioned user
3. Enter My Account tab and observe that Store Credits information is not present there

## Your Environment
Chrome ver. 60.0.3112.101 Windows 10
Spree version: 3.3

**Comment by tanmay3011** [comment]
Will give a PR for this soon.

**Comment by yatindrarao** [comment]
Hey @tanmay3011 
Are you working on this?

**Comment by tanmay3011** [comment]
Not right now! Was working on this earlier in spree_auth_devise extension as this is not related to Spree, but somehow couldn't complete the feature. Will pick this next week.

**Comment by tanmay3011** [comment]
Raised a PR https://github.com/spree/spree_auth_devise/pull/397
