### ISSUE TITLE
No products found

### ISSUE THREAD

**Issue by 99cm** [spree/spree#8262]
my store ypill.com, which had run about three months, run into "no products found" today. Taxonomies are displaying, but "no products found" anywhere.
ruby 2.3.0;
rails 5.0.2
spree 3.2.1

## Steps to Reproduce

1. http://www.ypill.com/
2.
3.
4.

## Your Environment

* Version used: 3.2.1
* Gemfile and Gemfile.lock as text in a Gist:
gem 'puma', '~> 3.8'
gem 'rails', '5.0.2'
gem 'spree', '~> 3.2.1'

Gemfile.lock:
    puma (3.8.2)
    rails (5.0.2)
      actioncable (= 5.0.2)
      actionmailer (= 5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      activemodel (= 5.0.2)
      activerecord (= 5.0.2)
      activesupport (= 5.0.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.2)
      sprockets-rails (>= 2.0.0)

    railties (5.0.2)
      actionpack (= 5.0.2)
      activesupport (= 5.0.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)

    spree (3.2.1)
      spree_api (= 3.2.1)
      spree_backend (= 3.2.1)
      spree_cmd (= 3.2.1)
      spree_core (= 3.2.1)
      spree_frontend (= 3.2.1)
      spree_sample (= 3.2.1)

* Any relevant stack traces ("Full trace" preferred):

**Comment by saravanak** [comment]
This is not seen in the  [referenced site](http://www.ypill.com) now; it shows the proper products. @99cm, can you confirm please?
