### ISSUE TITLE
Frontend Views Exporter

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8265]
While we're moving away from [deface](https://github.com/spree/deface) we want to ease the pain of customizing the default spree frontend for developers. That's why we're planning to add an option to spree generator to copy [views from frontend](https://github.com/spree/spree/tree/master/frontend/app/views) to your project. 

- [X] copy views generator
- [ ] update Spree documentation to recommend using views overrides rather than Deface

**Comment by kevynlebouille** [comment]
@damianlegawiec deface will still in use for contrib ?

**Comment by damianlegawiec** [comment]
@kevynlebouille deface won't be removed for a long time but for frontend customization, we recommend overwriting the views hence the exporter feature. We'll still thinking about better way to inject custom views code by extensions/developers for admin panel

**Comment by jbentes** [comment]
I use the command: 
rails generate spree:frontend:copy_views

And got this: 
Could not find generator 'spree:frontend:copy_views'. Maybe you meant 'spree:custom_user', 'devise:shared_views' or 'spree:auth:install'

**Comment by damianlegawiec** [comment]
@jbentes  what version are you using? This feature is available in `3.4.0.beta` / `master`currently which wasn't released to rubygems yet

**Comment by jbentes** [comment]
I'm using 3.3.0
When are you planning to release to rubygems?

**Comment by damianlegawiec** [comment]
@jbentes we're aiming to release `3.4.0.rc1` this week, maybe even tomorrow

**Comment by jbentes** [comment]
Great. Thank you
