### ISSUE TITLE
Multi-store management in Admin Panel

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8267]
Spree 2.3 [introduced Store model](https://github.com/spree/spree/commit/dcdb1715be5d66c2b6099e448f85270cc6641782) but still we don't have any options as a Store owner to manage multiple stores in a single instance. We only have the General Settings tab. We should extend the Admin Panel UI to let store owners manage more than one store. 

Related to https://github.com/spree/spree/pull/8078

**Comment by alexandre025** [comment]
All the [spree-multi-domain](https://github.com/spree-contrib/spree-multi-domain) features will be included ?

**Comment by MatthewKennedy** [comment]
This would be good.

**Comment by damianlegawiec** [comment]
@alexandre025 not all at in the first iteration but that's the goal + much more
