### ISSUE TITLE
Guides 2.0

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8270]
Currently, [Spree guides](guides.spreecommerce.org) are generated by [nanoc](https://nanoc.ws/) and are using the old design without responsiveness. There's also no search at all. 

Our action plan for Guides 2.0:
- [X] migrate to more modern static website generator (we've chosen [Gatsby](https://www.gatsbyjs.org))
- [X] add new RWD design
- [x] add search

👀 Preview: ➡️ https://spree-guides.now.sh/ ⬅️

**Comment by joshRpowell** [comment]
@damianlegawiec a few thoughts 

- [Netlify](https://www.netlify.com/pricing/).  Their Bronze plan would work in this case. 
- Algolia's [Docsearch](https://community.algolia.com/docsearch/) 

Also, we would be glad to help in any way.

**Comment by damianlegawiec** [comment]
@joshRpowell thank you for those links, we're implementing Docsearch with the help of Algolia team for the current guides as we speak :)

**Comment by damianlegawiec** [comment]
Also - there is a huge team effort at Spark currently to bring guides content up to date:

https://github.com/spree/spree/pull/8256

**Comment by chanmathew** [comment]
Would suggest Gatsby here with Netlify and agolia Docsearch :)

**Comment by damianlegawiec** [comment]
Hey - we have gone with Gatsby after all ;)
