### ISSUE TITLE
Move to Bootstrap 4.0

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8285]
Bootstrap 4.0 release date is getting closer and we should consider moving both Frontend and Admin Panel to the new version in future Spree releases. 

- [X] [Frontend](https://github.com/spree/spree/issues/8286)
- [X] [Admin Panel](https://github.com/spree/spree/issues/8287)

We should use [the official gem](https://github.com/twbs/bootstrap-rubygem) instead of bootstrap-sass ([details why](https://github.com/twbs/bootstrap-sass/issues/1053))

**Comment by austinklenk** [comment]
Has there been any work on bootstrap 4.0 migration yet? @damianlegawiec

**Comment by damianlegawiec** [comment]
Hey @austinklenk @abrambailey we're bringing `webpacker` / `yarn` integration with Spree 3.7 so you could easily swap out Bootstrap 3 for 4, BS4 by default will be in Spree 4.0 later this year

**Comment by devilcoders** [comment]
@damianlegawiec Should we close this in favor of #9039 ?

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/9244
