### ISSUE TITLE
New fully responsive default frontend

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8286]
The current default frontend which was introduced in `Spree 3.0` isn't fully responsive. We should consider changing theme to something modern and move it to `Bootstrap 4.0`

**Comment by krtschmr** [comment]
+1

absolutely we need bootstrap4. it's not alpha anymore but currently `v4.0.0-beta.2`

it's really safe to use it now and updates won't hurt!

**Comment by damianlegawiec** [comment]
We've moved frontend to Bootstrap 4.2 via https://github.com/spree/spree/pull/9244
