### ISSUE TITLE
New fully responsive Admin Panel

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8287]

**Comment by chanmathew** [comment]
Hi Daniel, is there any timeline on this for 4.0? Would love to contribute, I’m a designer.

**Comment by lukielukas** [comment]
Yeah let me know if we over @ Coqtail.com can help out. With designing the Admin. Working with Spree for >5 years now. Launching 2 Spree's a month. We know our way :).

**Comment by damianlegawiec** [comment]
We've moved Admin Panel to Bootstrap 4.2 https://github.com/spree/spree/pull/9244
