### ISSUE TITLE
The User cannot see uploaded Icon in the Taxonomy and is not able to delete it

### ISSUE THREAD

**Issue by piotrpanko** [spree/spree#8306]
## Context
I tried to add the Icon for my created Taxonomies. After uploading the image I was not able to see if it uploaded properly and I wasn't able to delete it.

## Expected Behavior
The User should be able to delete previously uploaded Icons to the Taxonomy.

## Actual Behavior
The User is not informed if the Taxonomy already has Icon and there is no possibility to delete Icons from the Taxonomy.

## Steps to Reproduce
1. Login to the account with administrator permissions and open Admin panel.
2. Go to the Products > Taxonomies.
3. Create new Taxonomy for testing purposes.
4. After creating new Taxonomy, click the Edit button.
5. In the Tree List, click Right Mouse Button on the previously mentioned Taxonomy and choose Edit.
6. While in the Edit window, try to add new Icon for the Taxonomy and choose Upload.
7. After saving the added Icon, once again choose Edit in the Tree List.
8. Observe that there is no information about previously uploaded Icon and User is not able to delete it.

## Your Environment
* Version used: Spree 3.3.0
* Browser: Mozilla Firefox 55.0.3

**Comment by bbonislawski** [comment]
Fixed in #8318
