### ISSUE TITLE
Use API for adding items to the cart on Frontend

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8312]
Currently, we use [OrdersController#populate](https://github.com/spree/spree/blob/master/frontend/app/controllers/spree/orders_controller.rb#L42) for adding items to the Cart. This should be handled via API. This way we won't duplicate logic across the project and we can do this by ajax call enhancing user experience. 

We should use new API endpoints from https://github.com/spree/spree/issues/8288

**Comment by Qwertie-** [comment]
Nice idea, Ajax would also allow adding to cart without reloading the page. With one of my stores we have a dropdown that comes down when you add an item to the cart which uses Ajax.

**Comment by damianlegawiec** [comment]
Done via https://github.com/spree/spree/pull/8732 💥
