### ISSUE TITLE
Stripe Gate send wrong total 

### ISSUE THREAD

**Issue by thanhtungka91** [spree/spree#8331]
Send wrong total order to stripe gate in VND currency 
## Context
With VND currency, sending the total number when check out is not correct 
Example: total order 3,000,000 -> send to Stripe Gateway is 3, 000

## Expected Behavior
it should be sent total order same with the price in web 

## Actual Behavior
from the server 

![image](https://user-images.githubusercontent.com/3795067/30494968-1d048bc2-9a85-11e7-976c-e956e562e657.png)

From stripe result 

![image](https://user-images.githubusercontent.com/3795067/30494933-f8bea7d4-9a84-11e7-88ae-50d563e6653d.png)

## Your Environment
gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2'
gem 'spree_gateway', '~> 3.2'

**Comment by Qwertie-** [comment]
Just wanted to mention, if that scribbled on info is sensitive you might want to do a better job on it because its still basically fully readable.

**Comment by WitekL** [comment]
@thanhtungka91 I've verified this issue and we will try to fix it in the nearest future
