### ISSUE TITLE
Multiple Exchanges & Returns cause invalid state transition

### ISSUE THREAD

**Issue by hf2186** [spree/spree#8332]
When exchanging for a second time or returning after an exchange and invalid state error happens. This is because the order is already in the "returned" state.

## Expected Behavior
You should be able to do as many exchanges as you wish

## Actual Behavior
During the second exchange a 500 error is produced when trying to create a customer return in the admin panel.

## Possible Fix
Add "Returned" -> "Returned" as a valid state transition.

## Steps to Reproduce
1. Create an Order / Ship
2. Create an RMA / Ship
3. Create Customer Return
4. Create an RMA / Ship
5. Create Customer Return (Fails here)

## Your Environment
* Version used: Spree 3.1
* Any relevant stack traces ("Full trace" preferred):

StateMachines::InvalidTransition (Cannot transition state via :return from :returned (Reason(s): State cannot transition via "return")):
  state_machines (0.5.0) lib/state_machines/event.rb:224:in `block in add_actions'
  state_machines (0.5.0) lib/state_machines/machine.rb:729:in `block (2 levels) in define_helper'
  spree_core (3.1.8) app/models/spree/customer_return.rb:58:in `process_return!'
  activesupport (4.2.8) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.8) lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
  activesupport (4.2.8) lib/active_support/callbacks.rb:506:in `block in call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:506:in `each'
  activesupport (4.2.8) lib/active_support/callbacks.rb:506:in `call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
  activerecord (4.2.8) lib/active_record/callbacks.rb:306:in `_create_record'

**Comment by hf2186** [comment]
https://github.com/ShopFelixGray/spree/commit/4d06975a1d11da3f5866c36fb2f4c3b58d239ebd

This fix worked for me.

**Comment by bbonislawski** [comment]
Hello @hf2186, thanks for posting the fix. Would you be interested in making PR with this fix?

**Comment by hf2186** [comment]
https://github.com/spree/spree/pull/8338 added it to 3-1 branch. Should I update other branches as well?

**Comment by bbonislawski** [comment]
@hf2186 I'll handle that. Thanks for your code.
