### ISSUE TITLE
Migrate to yarn / webpacker for Admin Panel

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8339]
[Spree 3.3 was released with Rails 5.1 support](https://guides.spreecommerce.org/release_notes/spree_3_3_0.html) so we can start migrating the Admin Panel to a newer UI with the help of modern JavaScript / frontend technologies like Yarn, React and so on. This will greatly enhance the user experience and also will allow more rapid development of the interface. The first step to that is to start using [the webpacker gem](https://github.com/rails/webpacker) and yarn package manager.

**Comment by joshRpowell** [comment]
One piece of low hanging fruit for this would be select2-rails (newest 4.0.3, installed 3.5.9.1)

**Comment by mfdeveloper** [comment]
Awesome feature @damianlegawiec !! Many thanks for your hard work!!

Please, consider integrate something like this extension: https://github.com/vinsol-spree-contrib/spree_themes to the core. It allows add custom themes to customer frontend, from **Admin Panel**.

Following this idea and combining with this feature described here, both the costumer frontend and admin panel could have custom themes, using latest JS/TS frameworks/libraries (Angular, React, Vue.js...).To do something like this, you can use something like the approach of https://lernajs.io/, to developers create custom additional themes. I saw that [webpacker gem](https://github.com/rails/webpacker) allow these many latest JS frameworks, but maybe a more flexible approach is use a "micro frontend" concept (that is growing at the last days), using a WebComponents that can be "connected" to any Component of any JS fw/lib! You can use something like: https://stenciljs.com/ or any other library for this.

Please, verify too this "theme for any e-commerce": https://www.vuestorefront.io/
It is focused on Vue.js, but your concepts and some implementation can inspire you to do something better to Spree!!
