### ISSUE TITLE
Orders become inaccessible if approver deletes their account

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8346]
## Context
If the admin who approved an order deletes their account then the orders they approved can not be viewed anymore.
 
## Expected Behavior
Not quite sure what the best option would be but making the order fail to load isn't great.

## Actual Behavior
```
FATAL -- :  ActionView::Template::Error (undefined method `email' for nil:NilClass):
FATAL -- :      98:       <% if @order.approved? %>
 99:         <tr>
100:           <td><strong><%= Spree.t(:approver) %></strong></td>
101:           <td><%= @order.approver.email %></td>
102:         </tr>
103:         <tr>
104:           <td><strong><%= Spree.t(:approved_at) %></strong></td>
```

## Possible Fix
Can work around the error by changing the order `approver_id` to another user.

## Steps to Reproduce
Accept an order then delete the account and view the order on another account.

## Your Environment
    spree (3.2.3)
      spree_api (= 3.2.3)
      spree_backend (= 3.2.3)
      spree_cmd (= 3.2.3)
      spree_core (= 3.2.3)
      spree_frontend (= 3.2.3)
      spree_sample (= 3.2.3)

**Comment by damianlegawiec** [comment]
1. We should implement `try` in the views
2. After deleting the approver it should nullify all of the `approver_id` columns

@bbonislawski any thoughts?

**Comment by bbonislawski** [comment]
@damianlegawiec It's reasonable to do both.

**Comment by wiskirz** [comment]
Is this issue closed?

**Comment by bbonislawski** [comment]
@wiskirz not really. we still don't have second part of solution:
`After deleting the approver it should nullify all of the approver_id columns.`
