### ISSUE TITLE
Add `constantize` param to Spree.user_class

### ISSUE THREAD

**Issue by bbonislawski** [spree/spree#8367]
We always convert return Class from `Spree.user_class` and we have to call `to_s` on it every time we use user_class in any relation. It would be nice to have param `constatize` (with default value `true`  to be consistent with old versions) which would tell if we should return constant or string.

It's easy to change here:
https://github.com/spree/spree/blob/master/core/lib/spree/core.rb#L24

**Comment by tegon** [comment]
Hi! Can I tackle this one?

**Comment by bbonislawski** [comment]
@tegon yeah! It's yours!

**Comment by bbonislawski** [comment]
done with #8374
