### ISSUE TITLE
Countries' seeds are not idempotent

### ISSUE THREAD

**Issue by bbonislawski** [spree/spree#8371]
Currently, if you run seeds multiple times, you'll have each country duplicated. We should use something like `first_or_create` in https://github.com/spree/spree/blob/master/core/db/default/spree/countries.rb

**Comment by harsh183** [comment]
So we basically need to check if the given countries already exist in the database before creating them. Should checking if the `spree_countries` table have any values do for a check? I can't think of anything more flexible.

**Comment by bbonislawski** [comment]
@harsh183 you don't have to use this INSERT. You can rewrite it and use ActiveRecord `first_or_create`.

**Comment by tonymadbrain** [comment]
@bbonislawski Hi, something like this #8373 is suitable?

**Comment by bbonislawski** [comment]
@tonymadbrain Yeah, it's good. Please make pull request with it! Or tell me if you need support with it. Please put `fixes #8371` in description so it'll close this issue when we merge your PR.

**Comment by bbonislawski** [comment]
Fixed with #8373

**Comment by harsh183** [comment]
Great. Looks good
