### ISSUE TITLE
S3 attachment configuration in initializer raise error

### ISSUE THREAD

**Issue by ouykjh** [spree/spree#8380]
When I add S3 configuration for my Spree application it raises exception ```method_missing': undefined method `has_attached_file' for #<Class:0x000000092fe190> (NoMethodError)```

## Solution

The solution is to move s3 configuration to `after_initialize` section in config. Thx @bbonislawski

**Comment by helmiItsavirus** [comment]
@ouykjh I had a problem

I define the s3 configuration inside of `config/initializers/spree.rb`

`Rails.application.configure do
  if ENV["AWS_S3_BUCKET"].present?
    config.after_initialize do
      attachment_config = {
        s3_credentials: {
          access_key_id:     ENV['AWS_S3_KEY'],
          secret_access_key: ENV['AWS_S3_SECRET'],
          bucket:            ENV['AWS_S3_BUCKET']
        },

        storage:        :s3,
        s3_region:      ENV['S3_REGION'],
        s3_headers:     { "Cache-Control" => "max-age=31557600" },
        s3_protocol:    "https",
        bucket:         ENV['AWS_S3_BUCKET'],
        url:            ":s3_domain_url",

        path:           "/:class/:id/:style/:basename.:extension",
        default_url:    "/:class/:id/:style/:basename.:extension",
      }

      attachment_config.each do |key, value|
        Spree::Image.attachment_definitions[:attachment][key.to_sym] = value
      end
    end
  end
end
`
