### ISSUE TITLE
Payment fails without showing any errors

### ISSUE THREAD

**Issue by Veske** [spree/spree#8384]
## Context
I am trying to test purchasing a product in development environment. I have 3 types of payment options set up:
* Spree::Gateway::Bogus
* Spree::PaymentMethod::Check
* Spree::PaymentMethod::StoreCredit

I can only select the bogus and check methods when buying from the store for some reason. Store credit is not shown.
Once I try to purchase with any of these options, the page will go to the Confirm stage and right back to payment stage. No errors are displayed when this happens, so a user would have no idea what happened.

## Expected Behavior
Even if something did go wrong with payment, the page should display an error about it.

## Actual Behavior
No error is shown. User is just redirected back to payment page.

## Steps to Reproduce
1. Add item to card
2. Checkout
3. Try to pay
![out](https://user-images.githubusercontent.com/5602603/31316745-24dd29da-ac3c-11e7-8b29-2f9bf5fc83b8.gif)

## Your Environment
* Version used: 3.3.2
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/Veske/b48f6b0d9138fcd0e0dc7e3b33cc080e

**Comment by Veske** [comment]
I can say that the validation error comes from `insufficient_payment?` method `checkout_controller`.
I am not sure why the validation fails for me. My user made one purchase and now in that method there is a check on database where it sums payments and gets some number which is not equal to current orders total. Feels like it's a check if the user has a dept to the shop? In any case... this probably should throw a proper error into the model

**Comment by Veske** [comment]
Probably I could make a quick fix for this my self also. Or you guys have some bigger plans with this method? To move the validation to model? Probably in real life scenarios this does not really happen often but I would say it's still a possibility.

**Comment by bbonislawski** [comment]
I think that making purchase without gateway connection setup really doesn't happen too often in production and we shouldn't focus now on this issue. What do you think @damianlegawiec ?
