### ISSUE TITLE
Missing insufficient_quantity api template?

### ISSUE THREAD

**Issue by zhengpd** [spree/spree#8395]
I saw `respond_with(@order, default_template: 'spree/api/v1/orders/insufficient_quantity', status: 422)` from [here](https://github.com/spree/spree/blob/906205dd0c18dc909aff6d3ac28775452808973e/api/app/controllers/spree/api/v1/checkouts_controller.rb#L72), but can't find the `insufficient_quantity` api template. Am I missing something?

**Comment by damianlegawiec** [comment]
@zhengpd good catch!

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/8439
