### ISSUE TITLE
In Admin when delete Store Credit Category, Users Store Credit page breaks 

### ISSUE THREAD

**Issue by yatindrarao** [spree/spree#8407]
## Context
In admin when we add store credit of any user and then delete the that store credit category. It breaks the page.

## Expected Behavior
It should not break.

## Actual Behavior
User's store credit page breaks so it should be handled.

## Steps to Reproduce
1. In admin create store credit category 
2. Add store credit for any user 
3. Delete the store credit category 
4. Visit user's store credit page

**Comment by yatindrarao** [comment]
https://github.com/spree/spree/blob/90bcf2d72f9d96fb5ed3b9187c577f15b2a0fb95/core/app/models/spree/store_credit.rb#L27
allow_nil in delegate will solve this with showing blank in category field.

**Comment by tanmay3011** [comment]
Hey @yatindrarao, Adding `allow_nil` would be hack rather than a proper solution

Solution: Store credit category cannot be deleted if any store credit is associated to it.
