### ISSUE TITLE
Sprockets::filenotfound in Spree::Home#index

### ISSUE THREAD

**Issue by ashishcompwiz** [spree/spree#8418]
Hi i created a spree extension and installed it. Afterwards i deleted it by removing from the gemfile and running bundle install. it didnt have any migrations. (name was spree_wallet)
After when i run it i get the following error

Showing E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_frontend-3.3.1/app/views/spree/shared/_head.html.erb where line #7 raised:

Sprockets::filenotfound in Spree::Home#index
couldn't find file 'spree/backend/spree_wallet' with type 'application/javascript'
Checked in these paths: 
  E:/Websites/Developing/MedBharat/MyStore3/app/assets/config
  E:/Websites/Developing/MedBharat/MyStore3/app/assets/images
  E:/Websites/Developing/MedBharat/MyStore3/app/assets/javascripts
  E:/Websites/Developing/MedBharat/MyStore3/app/assets/stylesheets
  E:/Websites/Developing/MedBharat/MyStore3/vendor/assets/images
  E:/Websites/Developing/MedBharat/MyStore3/vendor/assets/javascripts
  E:/Websites/Developing/MedBharat/MyStore3/vendor/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_gateway-3.3.0/lib/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_gateway-3.3.0/lib/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.3.1/lib/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_auth_devise-3.3.1/lib/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_frontend-3.3.1/app/assets/images
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_frontend-3.3.1/app/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_frontend-3.3.1/app/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_frontend-3.3.1/vendor/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_backend-3.3.1/app/assets/images
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_backend-3.3.1/app/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_backend-3.3.1/app/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_backend-3.3.1/vendor/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/spree_backend-3.3.1/vendor/assets/stylesheets
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/select2-rails-3.5.9.1/vendor/assets/images
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/select2-rails-3.5.9.1/vendor/assets/javascripts
  E:/InstalledPrograms/Ruby23-x64/lib/ruby/gems/2.3.0/gems/select2-rails-3.5.9.1/vendor/assets/stylesheets

Please solve this. using rails 5.1.4 and spree 3.3.1

**Comment by bbonislawski** [comment]
It's not a bug. Install generator of extension adds requires in 
```
vendor/assets/javascripts/spree/frontend/all.js
vendor/assets/javascripts/spree/backend/all.js
vendor/assets/stylesheets/spree/frontend/all.css
vendor/assets/stylesheets/spree/backend/all.css
```.
You should notice that.

**Comment by ashishcompwiz** [comment]
thanks also found this thread to be helpful
https://groups.google.com/forum/#!topic/spree-user/YpeGqQrPNfk

**Comment by iAaquibjawed** [comment]
run the below command
1. yarn build
