### ISSUE TITLE
Define routes for newly created static views in eCommerce Application

### ISSUE THREAD

**Issue by hassam-zahid** [spree/spree#8421]
Application routes for new Views

Hi, 
I want to add the path of my newly created static View in my application routes file but it is not working. When I add path for the same view in spree directory's frontend->config->routes.rb file, it works fine and I can easily access my new page through my application. But I want to define that route in my own application directory's routes.rb file. How can I override routes in my application directory's route file ?? Thanks

**Comment by damianlegawiec** [comment]
@hassam-zahid you can use https://github.com/spree-contrib/spree_static_content gem or you can add your custom routes like described here -> https://guides.spreecommerce.org/release_notes/spree_1_0_0.html#routes
