### ISSUE TITLE
Provide standard Draper decorators

### ISSUE THREAD

**Issue by MarkBennett** [spree/spree#8428]
I'm trying to integrate some Spree views with our custom branding and templates. As such there's a lot of work I need to do to modify the view. Typically, in other applications I'd use Draper decorators to do this. I've been doing lots of monkey patching to things like the `OrdersController` and `CheckoutController` to decorate the order myself, but it's ugly and requires a lot of hackery I'd rather not do.

Given, that I've noticed other people using Draper decorators with Spree I was curious how open the maintainers were to a PR that added some standard decorators which would be consistently used in Spree and provide a safer place for extending much of the Spree view code?

As this could be a lot of work, I thought starting with an issue to gather feedback rather than a PR would be useful. If you'd prefer I kick off this discussion in a PR please let me know and I'll close this.

Thank-you for the great work!

**Comment by MarkBennett** [comment]
I also forgot to mention that there a quite a few places where we use conditional logic and complex formatting in the standard view code that could be made simpler by using decorators. I'll share some specifics later, but almost anywhere with if-else could benefit. This would also help improve code coverage in the views.

**Comment by damianlegawiec** [comment]
Hey @MarkBennett , we don't want to add another dependency to the project (we already have so much ;) and force it on all of the spree developers out there. From a perspective of a team doing huge e-comm projects - the customer frontend is always replaced with a custom solution, either rails controllers or javascript/mobile frontend hitting the API. 

We'll be moving most of the complex logic like adding to cart or traversing the checkout to the API in future releases and phasing out the frontend controllers. 

But there's always room for improvement and in this case - creating extendable injection points in the codebase.

**Comment by MarkBennett** [comment]
Thanks for the update @damianlegawiec. I wasn't aware that the front-end controllers were being phased out but it makes sense not to add to them given that's the case.

So going forward is the recommended best practice to use what's in `spree-core` and build out your own controllers on the front-end? I've noticed some of the custom extension points in the code around things like updating the order attributes. What's the policy on deciding how and where these are added? Would you accept PR's that register new ones?

**Comment by Qwertie-** [comment]
It would be great to get everything using the API. Every spree site I have made it has been required to rewrite 80% of the views and a lot of the controllers which means it's now close to impossible to update spree without rewriting most of the website. If the API was used you could just fork the frontend and make it work how you need and freely update the rest of the spree as long as the API version stays the same.

This would also solve the problem of having some features that are only available on the web page and not the API
