### ISSUE TITLE
helper_name conflicts after adding spree to my project

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#8444]
i added spree to a recent project.
i have issues with `def icon` and `def render_breadcrumbs`. it seems that they also appear in the spree-namespace, thus giving me `wrong number of arguments (given 0, expected 1..2)` errors. 

ist there a way to namespace methods or somehow avoid these duplicates?

**Comment by bbonislawski** [comment]
Hello @krtschmr , thanks for reporting your issue. I've renamed `icon` method to `spree_icon` and `breadcrumbs` to `spree_breadcrums`. I didn't see method `render_breadcrumbs` anywhere. #8445

**Comment by krtschmr** [comment]
good work!
