### ISSUE TITLE
Weight splitter not working for backorderable items

### ISSUE THREAD

**Issue by gus4no** [spree/spree#8449]
Splitter is properly breaking up packages, but they're being removed afterwards

## Context
I wanted my heavy items to go in diff shipments each.

## Expected Behavior
When buying two items of the same product with a (200) weight I expect two shipments to be created for each item.

## Actual Behavior
Only one shipment is created with one inventory unit, and the customer is charged fully.

## Possible Fix
I've been digging deep into coordinator, prioritizer and adjuster and I think this commit may have introduced the bug.

https://github.com/spree/spree/commit/ae384197bec4656d47fc6fff5debc9c1f70a76d0#diff-30b85b91fd7936215c41294c550e6954

The way the adjuster is found or build, previously used the inventory unit itself now it uses the variant hash. This would cause the `find_adjuster` method return an already instantiated adjuster where `backorder_package` is already set thus calling `package_to_adjust.remove_item item` which would delete packages and generate one less shipment.

I fixed it in my project by just changing `build_adjuster` to use `inventory_unit` again rather than `hash_item()` since I don't have multiple stock locations seems ok for me, but I don't think this would be a complete fix.

## Steps to Reproduce

1. Configure a product with a weight of 200 and backordable stock.
2. Go to the store and add two items of this product to the cart.
3. Continue with checkout normally.
4. Go to order in admin panel, and see only one shipment instead of two.

## Your Environment

* Version used:  3.4.1

**Comment by artplan1** [comment]
@gus4no maybe it's related to same issue: https://github.com/spree/spree/issues/8204#issuecomment-363400810

**Comment by bbonislawski** [comment]
@artplan1 this is totally different issue. there is some problem with splitting shipments at the moment and I'm writing up the problems with it now

**Comment by bbonislawski** [comment]
We cannot reproduce it on master so that was probably fixed already
