### ISSUE TITLE
Spree routes, defaults subdomain to false

### ISSUE THREAD

**Issue by lucasruroken** [spree/spree#8455]
Spree version: 3.3
Rails version: 5.1
Ruby version: 2.4.1

I'm setting up a subdomain to handle different type of urls. I'm using something like this
```
  constraints subdomain: "store" do
    scope module: "store" do
      get '*slug', to: 'users#show', as: :store_link
    end
  end
```

The main idea is to use spree with subdomain set to false, but when i'm using store.localhost:3000 and i try to print a spree route, the app is printing:
```
store.localhost:3000/spree-url
```

and if i go to `localhost:3000` the app is printing
```
localhost:3000/spree-url
```

## Expected Behavior
* Url should be always localhost:3000/spree-url if i set subdomain to false

## Actual Behavior
* Url depends of the current path, if i go to `store.localhost:3000` the spree url takes the store subdomain

## Steps to Reproduce
1. Add to your routes.rb something like
```
  constraints subdomain: "store" do
    scope module: "store" do
      root to: "home#index"
    end
  end
```

and also create a home_controller under app/controllers/store/home_controller with the index method. And in index.html erb of that controller, try to print spree.root_path. Inherit HomeController from Spree::BaseController
```
class Store::HomeController < Spree::BaseController
  def index

  end
end
```

2. Don't forget to add to /etc/hosts 
```
127.0.0.1           spree.localhost
```

**Comment by kushniryb** [comment]
The default behaviour for route helpers includes subdomain which makes sense in my humble opinion. 
I don't think that it would be smart to change it due to the fact that it could potentially break a lot of apps. 
You can use `subdomain: false` option to exclude subdomain, e.g `root_url(subdomain: false)`

**Comment by bbonislawski** [comment]
As @kushniryb said. Closing for know. If you still think that it's a bug, please leave a comment
