### ISSUE TITLE
Spree::Order#apply_free_shipping_promotions should refresh order's promo totals

### ISSUE THREAD

**Issue by dl103** [spree/spree#8457]
Spree::Order#apply_free_shipping_promotions currently checks and applies eligible free shipping promotions and updates the shipment totals accordingly. However, the order itself needs its promotion totals updated or else the order's `#total` won't reflect reality. In the method's source below, I think adding a `updater.update_adjustment_total` before calling `persist_totals` should fix this bug.

https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L505

I'm currently fixing this in my project and am happy to port over the code change + tests after.

**Comment by bbonislawski** [comment]
Hello @dl103 , thanks for reporting bug and finding possible solution. 
Do you want to try making PR for that? Or should we take care of this?

I really appreciate your help!

**Comment by dl103** [comment]
certainly, i'll open up a PR in a few minutes. i wanted to double check i wasn't missing misunderstanding the method's intended use first.

**Comment by bbonislawski** [comment]
Actually, I just realized that this can lead to more bugs if promotion with FreeShipping action has more actions.  Then it will apply those actions too and (probably) order total will be even more messed. Please use `update_totals` method there

**Comment by delphaber** [comment]
@bbonislawski Should this ticket have a label 'needs backport to 3-1-stable' ?
