### ISSUE TITLE
Make image ratio on taxons page fixed

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8461]
## Context
If you have product images with lots of different image ratios the taxons admin page looks pretty broken.
## Expected Behavior
A regular grid with boxes of the same size

## Actual Behavior
![screenshot from 2017-11-15 12-52-39](https://user-images.githubusercontent.com/6601505/32815398-cca29a1a-c9ab-11e7-93c4-1bceeab09817.png)

## Possible Fix
Fix the image ratio of the images on this page.

## Your Environment
```
gem 'spree', '~> 3.2.3'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'```

**Comment by WitekL** [comment]
Hi! I will try to fix it!

**Comment by WitekL** [comment]
Will that be ok? @Qwertie- 

![screen shot 2017-11-20 at 12 38 53](https://user-images.githubusercontent.com/19196595/33017043-2247a61a-cdf1-11e7-85ff-be55ec2a2b5a.png)

**Comment by Qwertie-** [comment]
Yeah that looks great 👍
