### ISSUE TITLE
Sort by company in user list

### ISSUE THREAD

**Issue by Qwertie-** [spree/spree#8462]
When company name is used for users there should be a way to sort by that in the user list like you can with email.

## Your Environment
```
gem 'spree', '~> 3.2.3'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'```

**Comment by WitekL** [comment]
Hi @Qwertie-! Could you please provide some details? A screenshot would be awesome!

**Comment by bbonislawski** [comment]
I guess this is stale and we won't know what was idea behind this issue.
