### ISSUE TITLE
Create image from local file

### ISSUE THREAD

**Issue by DrakkenSaer** [spree/spree#8466]
I am trying to do the following:

1. Download image from remote URL
2. Read image file
3. Add said image file to a product

I am all the way up to step 3 where I get  ```ActiveRecord::AssociationTypeMismatch: Spree::Image(#82030500) expected, got File(#15271180)```.

I can't seem to find any documentation about how to add an image from a local file. Could anyone point me in the right direction or show me where in the source code I can find what to do?

Thank you

**Comment by damianlegawiec** [comment]
try sth like this:
```
image = variant.images.new
image.attachment = open(url_to_the_image)
image.save!
```
