### ISSUE TITLE
Spree crashes when I add taxonomies to backend

### ISSUE THREAD

**Issue by austinklenk** [spree/spree#8467]
When I go to add a taxonomy to the back admin of spree, then I go to the front end to view it, the site crashes with "We're Sorry, but something went wrong message"

## Context

This is the first time it has happened, if i delete the taxonomy the error goes away, and spree works fine.

I checked the production logs and i went to the tail end of the logs and i got the error or 
ActionView::Template::Error File name too long

## Expected Behavior

It should show the taxonomies on the app home page

## Actual Behavior

It doesn't show the taxonomies on the app home page.

```ActionView::Template::Error (File name too long @ rb_sysopen - /home/deploy/green-leaf-8068/releases/20171118005029/tmp/cache/.views%2Fen%2Fspree%2Ftaxons%2Fquery-31ca639365e5feaf676f5d3e30d61f7e-1-20171118164513802856%2F4e4141499cd6d80a307e6e75976f816e20171118-4097-11cnplj):
F, [2017-11-18T11:45:27.376761 #4097] FATAL -- : [2b5710fc-ffb3-4550-a095-e222984c8153]     1: <% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots %>
[2b5710fc-ffb3-4550-a095-e222984c8153]     2: <%= form_tag spree.products_path, method: :get, class: "navbar-form" do %>
[2b5710fc-ffb3-4550-a095-e222984c8153]     3:   

[2b5710fc-ffb3-4550-a095-e222984c8153]     4:     <% cache [I18n.locale, @taxons] do %>
[2b5710fc-ffb3-4550-a095-e222984c8153]     5:       <%= select_tag :taxon,
[2b5710fc-ffb3-4550-a095-e222984c8153]     6:             options_for_select([[Spree.t(:all_departments), '']] +
[2b5710fc-ffb3-4550-a095-e222984c8153]     7:                   @taxons.map {|t| [t.name, t.id]},
F, [2017-11-18T11:45:27.376869 #4097] FATAL -- : [2b5710fc-ffb3-4550-a095-e222984c8153]   
F, [2017-11-18T11:45:27.376983 #4097] FATAL -- : [2b5710fc-ffb3-4550-a095-e222984c8153] 
```

## Steps to Reproduce

1. Fresh Install of Spree
2. Create 1 product
3. Create a Taxonomy
4. You will get the error

## Your Environment

* Version used: 
```
gem 'spree', '~> 3.4.0'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
```
* Gemfile and Gemfile.lock as text in a Gist:
Gemfile
https://gist.github.com/austinklenk/045f815c6f511744e35359b9c3a2bc0b
Gemfile.lock
https://gist.github.com/austinklenk/49316e7ca48b7272a42a022f61dc96ee
* Any relevant stack traces ("Full trace" preferred):
https://gist.github.com/austinklenk/de65b841177170bf6a84725cfa0f2bd6

**Comment by bbonislawski** [comment]
Hello @austinklenk ,
what operating system do you use? I cannot reproduce this on my machine.

**Comment by austinklenk** [comment]
This is on the server it’s self, it’s works fine locally but n my laptop. But it’s running on ubuntu 16.04 VM Machine. I’ll get you a link to the server so that you can log into and see it for your self.

**Comment by austinklenk** [comment]
@bbonislawski url: mastertechstore.com
email: test@1234.com
pw: admin1234

don't worry there is no real working data on it yet.
You'll have to create the taxonomies to see that it breaks.

**Comment by Qwertie-** [comment]
Where is the code deployed on your VM? Do you think it's possible that one of the paths went over the maximum allowed path length of 4096 chars?

**Comment by austinklenk** [comment]
4096 chars? @Qwertie-

**Comment by Qwertie-** [comment]
@austinklenk Characters. https://serverfault.com/a/598267/228365 

If the website is running somewhere with a long file path you may have hit the limit on linux.
