### ISSUE TITLE
Some payment methods can't work when applying a coupon in the payments page

### ISSUE THREAD

**Issue by DethonUSAL** [spree/spree#8503]
## Context
If you apply a coupon in the payments page, the javascript in `payment.js.coffee` will call `submit()`, hijacking the flow from some payment methods which need to wait for some kind of nonce.
An example of this is the spree_braintree_vzero extension.

## Expected Behavior
It should wait for the payment method to finish before submitting.

## Actual Behavior
It submits just after processing the coupon, not waiting for anything else.

## Possible Fix
Just removing the `submit()` call should do the trick. As far as I know it's unnecessary and removing it will just restore the normal submit behavior.

## Steps to Reproduce
1. Install the spree_braintree_zero extension
2. Create a promotion with a code and an action which is NOT "create line item" (those work fine because they force you back to the address step)
3. Create a payment method that uses `Spree::Gateway::BraintreeVzeroHostedFields`
4. Purchase a product and in the payments page select the payment method you just created and fill in the coupon code
5. In the next step, when you try to confirm the payment, you will see the error

**Comment by mimilettd** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
