### ISSUE TITLE
Integrate payment gateway which not submit credit card data directly to the gateway API (bypassing the Spree Commerce server)

### ISSUE THREAD

**Issue by nvphuc1989** [spree/spree#8508]
## Context
We are integrate a new payment gateway for Spree Commerce. Here is the work flow (see see attachment):
![image](https://user-images.githubusercontent.com/11606840/33699225-6b780ef0-db44-11e7-9946-72a3544d81ec.png)

At the payment step, customer selects the “New Payment Method” and fill in credit card data.
1. Then click the “Save and Continue” button on the Checkout screen. A client JavaScript handles the submission (using Ajax) and send request to the Spree Commerce server but not include any credit card data.
2. The Spree Commerce server creates an order with Pending status then sends a “create Authentication Key” request to the Payment gateway API.
3. The Payment gateway API creates a single use time Authentication Key and returns it to the Spree Commerce server.
4. The Spree Commerce server transfers the Authentication Key to the client JavaScript.
5. The client JavaScript collects credit card data and the Authentication Key then sends them directly to the Payment gateway API, bypassing the Spree Commerce server. This is the key feature to protect customer’s credit card data.
6. The Payment gateway API processes a payment in real time and returns a “redirection” response directly to the customer’s browser with “Result Key”. The result of the payment is not included.
7. The browser sends the Result Key to Spree Commerce server.
8. The Spree Commerce server sends a “transaction result lookup” request to the Payment gateway API with the Result Key.
9. The Payment gateway API retrieves the transaction result and returns it back to the Spree Commerce server.
10. After updated the order status based on the transaction result, the Spree Commerce server sends the result to the customer.

## Expected Behavior
Please suggest if it's possible to integrate with the method above into Spree Commerce. Currently we are getting stuck at step 2: Create order and create Authentication Key. Please support. Thanks.

**Comment by damianlegawiec** [comment]
Short answer - yes, it's possible :)

You can check Braintree v.zero Spree extension for an example - https://github.com/spree-contrib/spree_braintree_vzero
