### ISSUE TITLE
Bug in order importer.

### ISSUE THREAD

**Issue by yoandrypa** [spree/spree#8514]
The id of the variant is modified in all lime_item when trying to detect the lime_item in line 97.

The current code is:

https://github.com/spree/spree/blob/84cf7adee8a1e57ca05cca80c6fef1363c8f8b7b/core/lib/spree/core/importer/order.rb#L97

This should be like that:

```ruby
line_item = order.line_items.detect { |ln| ln.variant_id == inventory_unit_param[:variant_id] }
```

**Comment by damianlegawiec** [comment]
Thanks for spotting this @yoandrypa 👍 would you care to submit a PR with a fix?
