### ISSUE TITLE
Strange assignment that looks like it should be a comparison on Frontend OrdersController

### ISSUE THREAD

**Issue by Onumis** [spree/spree#8546]
I was reading the code when I noticed [this method:](https://github.com/spree/spree/blob/master/frontend/app/controllers/spree/orders_controller.rb#L78):

```ruby
    def empty
      @order.empty! if @order = current_order

      redirect_to spree.cart_path
    end
```

I think that it should be `if @order == current_order` (a comparison) instead of the assignment.

The only case where this evaluates to false is then `current_order.nil?` is true.

If the intention is to only call `empty!` when the order exists, then this code would be a bit better:

```ruby
    def empty
      current_order.try(:empty!)
      redirect_to spree.cart_path
    end
```

**Comment by bbonislawski** [comment]
I'm not an author of this code but I think that it should be like this. `current_order` is method that returns order, so assigning it to `@order` before redirect totally makes sense for me. 

If you think that it's mistake, please mention me in comment.

**Comment by Onumis** [comment]
@bbonislawski Yeah I can see that as a use case, although I don't like that type of writing personally.
Additionally, if it's a redirect, it's useless to define a new instance variable (takes up ram, etc) `current_order.try(:empty!)`.

**Comment by bbonislawski** [comment]
Can you make pull request for that? I'll test it then and happily merge if it works 👍

**Comment by kushniryb** [comment]
@bbonislawski Can we close this?
