### ISSUE TITLE
order.last_ip_address doesn't always save

### ISSUE THREAD

**Issue by joeswann** [spree/spree#8562]
The `Spree::Core::ControllerHelpers::Order` `current_order` definition assigns a last_ip_address to the order but doesn't appear to save it.

## Details
I was working on getting the geocoder gem to derive some information from a users IP address - in doing so I discovered that the current_order function assigns a last ip address to the order but doesn't appear to immediately save it.

If the current order is later saved on then the ip address gets saved along with it, but that doesn't always happen.

## Expected Behavior
When `current_order` is called, `order.last_ip_address` is saved

## Actual Behavior
`order.last_ip_address` only gets saved if the order is updated later on

## Possible Fix
Adding or editing here https://github.com/spree/spree/blob/3-4-stable/core/lib/spree/core/controller_helpers/order.rb#L42 to save the attribute

## Steps to Reproduce
1. Create a new cart by visiting spree frontend
2. Inspect order in rails console
3. last_ip_address is nil

## Your Environment
* Version used: 3.2 - checked and 3.4 appears to behave the same way

**Comment by saravanak** [comment]
I've checked this behavior and confirm that the `last_ip_address` is saved.

The `last_ip_address` of order at the referenced `current_order` method is still in memory. So, inspecting the DB for the updated `order` will not have the  expected value for `last_ip_address` column.
 
This `order` is actually (indirectly) saved in the file `frontend/app/controllers/spree/orders_controller.rb:53`. (It calls the `save!` method after updating the line items. 

Here is the modified spec for verifying the same:  `(frontend/spec/controllers/spree/orders_controller_spec.rb)`

```
require 'spec_helper'

describe Spree::OrdersController, type: :controller do
  let(:user) { create(:user) }

  context 'Order model mock' do
    let(:order) do
      Spree::Order.create!
    end
    let(:variant) { create(:variant) }

    before do
      allow(controller).to receive_messages(try_spree_current_user: user)
    end

    context '#populate' do
      it 'should create a new order when none specified' do
        spree_post :populate, variant_id: variant.id
        expect(cookies.signed[:guest_token]).not_to be_blank
        new_order = Spree::Order.find_by(guest_token: cookies.signed[:guest_token])
        expect(new_order).to be_persisted
        expect(new_order.last_ip_address).to be_nil #Added
      end

      context 'with Variant' do
        it 'should handle population' do
          expect do
            spree_post :populate, variant_id: variant.id, quantity: 5
          end.to change { user.orders.count }.by(1)
          order = user.orders.last
          expect(response).to redirect_to spree.cart_path(variant_id: variant.id)
          expect(order.line_items.size).to eq(1)
          line_item = order.line_items.first
          expect(line_item.variant_id).to eq(variant.id)
          expect(line_item.quantity).to eq(5)
          expect(order.last_ip_address).to eq('0.0.0.0') #Added
        end
      end
    end
  end
end
```

**Comment by zhengpd** [comment]
The `order.last_ip_address` is likely designed to save "last ip which modified the order", not "last ip which read the order". This might be why it's not saved inside `current_order` method.

**Comment by joeswann** [comment]
@zhengpd I think you are correct, however here I'd consider the creation of an order to also count as 'last ip to modify order', otherwise you end up with persisted orders without any  `last_ip_address`.

To clarify my use case, I am using this as a convenient & saved IP reference for currency detection. For my purpose it makes sense to have an IP address on order creation, I imagine it would also be useful to have for logic that involves empty & abandoned carts.

I'm guessing it's intended for something like credit card security which would only be required after adding something to cart, so I can see why It's important later, but is there a good reason for not saving it earlier?

**Comment by zhengpd** [comment]
@joeswann 

> but is there a good reason for not saving it earlier?

Don't know about that.

**Comment by bbonislawski** [comment]
@joeswann probably performance since we would have to call update to DB with each page view which could result in lots of unneeded updates. 

Closing this since it's expected way of working to update last_ip_address of last person who updated order. If you need to save it always, please do it in your code.

**Comment by joeswann** [comment]
@bbonislawski Fair point, in the end my issue was the ip wasn't saved on some orders when it was newly created vs whenever the current order was retrieved, that's just where the last_ip line already was in the code.
