### ISSUE TITLE
Spree extensions tests against ruby 2.5.0 fail

### ISSUE THREAD

**Issue by artplan1** [spree/spree#8566]
I'm trying to test built extensions against ruby 2.5.0 but `Setting up dummy database...` fails.

## Context

I'm using `apprailsals` to test on travis-ci

link to example build: https://travis-ci.org/public-market/spree_multi_vendor/jobs/333226153

<details>
<summary>Travis CI log</summary>

```
$ export BUNDLE_GEMFILE=$PWD/gemfiles/spree_3_1.gemfile
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.0
$ gem --version
2.7.4
$ bundle install --jobs=3 --retry=3
...
Bundle complete! 22 Gemfile dependencies, 151 gems now installed.
$ bundle exec rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::GitError: The git source https://github.com/spree/spree is not yet checked out. Please run `bundle install` before trying to start your application
/home/travis/build/public-market/spree_batch_api/spec/dummy/config/boot.rb:6:in `<top (required)>'
/home/travis/build/public-market/spree_batch_api/spec/dummy/config/application.rb:1:in `require'
/home/travis/build/public-market/spree_batch_api/spec/dummy/config/application.rb:1:in `<top (required)>'
/home/travis/build/public-market/spree_batch_api/spec/dummy/Rakefile:4:in `require'
/home/travis/build/public-market/spree_batch_api/spec/dummy/Rakefile:4:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/rubies/ruby-2.5.0/bin/bundle:30:in `block in <main>'
/home/travis/.rvm/rubies/ruby-2.5.0/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
Running extension installation generator...
      append  vendor/assets/javascripts/spree/frontend/all.js
      append  vendor/assets/javascripts/spree/backend/all.js
      insert  vendor/assets/stylesheets/spree/frontend/all.css
      insert  vendor/assets/stylesheets/spree/backend/all.css
         run  bundle exec rake railties:install:migrations FROM=spree_batch_api from "."
rake aborted!
Bundler::GitError: The git source https://github.com/spree/spree is not yet checked out. Please run `bundle install` before trying to start your application
```
</details>

One thing is unclear to me is - why it doesn't fail using ruby 2.4.3 on CI? Build: https://travis-ci.org/public-market/spree_multi_vendor/jobs/333226154

it obviously fails locally when I'm trying to reproduce using appraisals setup using ruby 2.4.3

## Possible Fix

So I guess problem is in _spec/dummy/config/boot.rb:4_
```ruby
ENV['BUNDLE_GEMFILE'] = gemfile
```

it overrides BUNDLE_GEMFILE set by appraisal to root extension Gemfile

Generic extension Gemfile: https://github.com/spree/spree/blob/master/cmd/lib/spree_cmd/templates/extension/Gemfile

1. First solution:

simply change to
```ruby
ENV['BUNDLE_GEMFILE'] ||= gemfile
```

or 

```ruby
unless ENV['APPRAISAL_INITIALIZED']
  ENV['BUNDLE_GEMFILE'] = gemfile
end
```

or it will cause some known issues? I'm ready to submit PR

2. Second solution:

change `Gemfile` in extension from

```ruby
gem 'spree', github: 'spree/spree', branch: 'master'
```

to 

```ruby
gem 'spree'
```

or use some conditions like

```ruby
if !ENV['APPRAISAL_INITIALIZED'] && !ENV['CI']
  gem 'spree', github: 'spree/spree', branch: 'master'
else
  gem 'spree'
end
```

but it will use latest spree in rubygems (3.4)

## Your Environment

All environment related info is in travis ci builds

Thank you

**Comment by artplan1** [comment]
Official `spree_auth_devise` logs: https://travis-ci.org/public-market/spree_auth_devise/jobs/339428347

**Comment by bbonislawski** [comment]
It's probably cused by bundler version >=1.16.0(which is minimal version for ruby 2.5). I have to look into that since we cannot stick with older bundler version forever

**Comment by artplan1** [comment]
@bbonislawski any word on this? I see

**Comment by artplan1** [comment]
@bbonislawski any word on this? I see that tests are passing now, but don't see changes related to this issue

**Comment by bbonislawski** [comment]
We cannot reproduce it with current master so it was probably fixed already.
