### ISSUE TITLE
The 'paperclip' gem has security vulnerabilities and should be updated

### ISSUE THREAD

**Issue by zjullion** [spree/spree#8576]
Version 5.1.0 of paperclip has a security vulnerability: https://github.com/thoughtbot/paperclip/pull/2435

You should update to 5.2.0 as soon as possible.

**Comment by bbonislawski** [comment]
Thanks for reporting, but this issue is already fixed with https://github.com/spree/spree/commit/0131a7eb9bf94a45d88c645fa00de65fa47ebc0e . Please consider verifying issues like that before you post anything since it wastes our time to check issues like that.

**Comment by vernondegoede** [comment]
The latest version which is available on Rubygems is 3.4.4. This version still has `paperclip 4.1.0` as a dependency.

Can you publish a `3.4.4` version which uses `paperclip 5.2.0`?

**Comment by damianlegawiec** [comment]
Hey @vernondegoede `3.4.4` uses `paperclip 5.1.0` but we'll release `3.4.5` with `paperclip 5.2.0`today :)

**Comment by vernondegoede** [comment]
Great! Thanks @damianlegawiec

**Comment by vernondegoede** [comment]
@bbonislawski @damianlegawiec Any update on this issue?

**Comment by damianlegawiec** [comment]
@vernondegoede both `3.3.5` and `3.4.5` containing the fix were pushed to RubyGems yesterday - sorry for the late update!

https://github.com/spree/spree/releases/tag/v3.3.5
https://github.com/spree/spree/releases/tag/v3.4.5
