### ISSUE TITLE
Spree products not able to add taxons 

### ISSUE THREAD

**Issue by cliffcleetus** [spree/spree#8580]
In the spree backend, I am not able to add taxons to the product , it says searching...But a similar autosuggest is there for option types, which works fine.
I tried regenerating the API key , but didn't solve the issue 

![image](https://user-images.githubusercontent.com/32164133/35843074-3a83e25c-0b2c-11e8-8626-51ef84289325.png)

`Error: Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
:3000/api/taxons?per_page=50&page=1&without_children=true&q%5Bname_cont%5D=&token=477cdac328120d8a3dcb804358ec4535091366faf9e988f3&_=1517890528589`

Please help me to solve this..

**Comment by mohsen-alizadeh** [comment]
@cliffcleetus Please check logs and report here

**Comment by bbonislawski** [comment]
What is your spree version?

**Comment by dimon-k** [comment]
I've tried to reproduced the issue, but wasn't successful. More information is needed:
- Spree Version
- Steps to reproduce
@cliffcleetus
