### ISSUE TITLE
Spree Admin side , taxons not loading 

### ISSUE THREAD

**Issue by 2bspree** [spree/spree#8581]
In the spree backend, I am not able to add taxons to the product , it says searching...But a similar autosuggest is there for option types, which works fine.
I tried regenerating the API key , but didn't solve the issue

image
![image](https://user-images.githubusercontent.com/27199223/35843291-49a0d50a-0b2d-11e8-99ef-0e3945c76d6c.png)

Error: Failed to load resource: the server responded with a status of 422 (Unprocessable Entity) :3000/api/taxons?per_page=50&page=1&without_children=true&q%5Bname_cont%5D=&token=477cdac328120d8a3dcb804358ec4535091366faf9e988f3&_=1517890528589

Please help me to solve this..

**Comment by bbonislawski** [comment]
What's your version of Spree?

**Comment by 2bspree** [comment]
Fixed the issue. 
Reference : https://github.com/spree/spree/issues/3817

By replacing the config/initializers/will_paginate.rb

if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        def per_page(num)
          if (n = num.to_i) <= 0
            self
          else
            limit(n).offset(offset_value / limit_value * n)
          end
        end

        def total_pages
          (total_count.to_f / limit_value).ceil
        end

        alias_method :per, :per_page
        alias_method :num_pages, :total_pages
        alias_method :total_count, :total_entries

      end
    end
  end
end
