### ISSUE TITLE
Associate user with order after login using API

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [spree/spree#8597]
How can i associate user with order through API ?! it's working fine with sessions on my website but i want to implement it on my mobile application which uses spree API.

Description:
I'm allowing guest to create orders from my application but i don't allow checkout out the order without registration. 
I'm using Spree 3.1 & I'm creating the order through populate action.

**Comment by bbonislawski** [comment]
Can you provide more details on your case? How did you create order? What version do you use?

**Comment by AhmedAliIbrahim** [comment]
I'm using spree 3.1 & order created via populate action

**Comment by bbonislawski** [comment]
Please use API instead of controllers from Frontend part. They're meant only to be used in browser.

**Comment by AhmedAliIbrahim** [comment]
I'm creating an order with a populate action I've implemented on my orders Api controller .

**Comment by bbonislawski** [comment]
You have `orders#create` in API. Check it there

**Comment by AhmedAliIbrahim** [comment]
my question is how to associate the created order with user when user login/ register since there's no session ?!

**Comment by bbonislawski** [comment]
use `current_api_user` like in `orders#create`. If you allow to create orders without being logged in, then you have to implement it somehow. This is not issue connected to spree
