### ISSUE TITLE
Circular Argument Reference from promotion_accumulator.rb: line 35

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#8616]
spree_core-3.4.4/app/models/spree/adjustable/promotion_accumulator.rb:35: warning: circular argument reference - adjustments 

WARN -- : Creating scope :open. Overwriting existing method Spree::Adjustment.open.

## Context
Deploying to Heroku logs in paper trail show the above information.

## Expected Behavior
No issues be logged

## Actual Behavior
Warning: circular argument reference - adjustments 

## Possible Fix
Not sure if it is critical but I feel I should note the issue.

## Steps to Reproduce
Set up your spree app, using the following environment launch Heroku use Papertrail for logging and watch deploy logs.

## Your Environment
ruby 2.4.1
rails 5.1.5"
puma 3.7

**Comment by 99cm** [comment]
I have the same error when rails start.

puma log logged:
`W, [2018-03-27T18:09:55.370887 #23348]  WARN -- : Creating scope :open. Overwriting existing method Spree::Adjustment.open.`

**Comment by tibomogul** [comment]
For me it shows when running rails server in 'staging' environment (RAILS_ENV=staging) on my mac.

**Comment by 99cm** [comment]
These are actually two issues:
1. There is BUG on spree_core-3.4.4/app/models/spree/adjustable/promotion_accumulator.rb:35.
2. WARN -- : Creating scope :open. Overwriting existing method Spree::Adjustment.open. There is reference:
Fixes #436 (scope re-definition warnings)

**Comment by bbonislawski** [comment]
Fixed by #8747
