### ISSUE TITLE
Cannot use named routes for routes defined within Spree::Core::Engine.add_routes block

### ISSUE THREAD

**Issue by vernondegoede** [spree/spree#8626]
I created a Spree project using Rails 5.1.5 and Ruby 2.2.7. Somehow I’m unable to add custom routes (or link to them using named routes). However, when I create a route outside the `Spree::Core::Engine.add_routes` block it works fine.

**Expected behavior**
Named route should return the url / path of the routes which are defined within `Spree::Core::Engine.add_routes do`.

**Actual behavior**
An error is thrown when calling the named route path / url.

**Steps to reproduce:**
1. Clone https://github.com/vernondegoede/spree-broken-route-issue
2. Install dependencies
3. Start Rails server.
4. Navigate to http://localhost:3000/
5. It should render: /working
6. Edit app/controllers/home_controller.rb and comment `render_working_route` and uncomment `render_broken_route`: https://github.com/vernondegoede/spree-broken-route-issue/blob/master/app/controllers/home_controller.rb#L4
7. Navigate to http://localhost:3000/
8. It shows an error `undefined local variable or method 'broken_route_path' for #<HomeController:0x007f96f2ca0928>`.

**Comment by artplan1** [comment]
This code works

```ruby
spree.broken_route_path
```

![image](https://user-images.githubusercontent.com/9060346/36837072-5919ffee-1d4c-11e8-91f0-6d336af9fce7.png)

**Comment by vernondegoede** [comment]
That's weird, it doesn't work on my machine. Which Ruby version are you on?

**Comment by artplan1** [comment]
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by artplan1** [comment]
there was double render issue in that controller too

**Comment by vernondegoede** [comment]
Hmm, same issue when using your Ruby version (`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]`). Any idea what else could be causing this behavior?

![image](https://user-images.githubusercontent.com/2484832/36838543-c41ed34e-1d3f-11e8-8166-5d60f625ec9e.png)

**Comment by artplan1** [comment]
it's not `spree.broken_route_path` on the screen shot 🙂

**Comment by vernondegoede** [comment]
Reading is hard 😢 
Thanks for your help @artplan1
