### ISSUE TITLE
[Question] Variants are loaded twice on product page

### ISSUE THREAD

**Issue by artplan1** [spree/spree#8630]
## Context

Variants are loaded in controller once:
https://github.com/spree/spree/blob/master/frontend/app/controllers/spree/products_controller.rb#L18

But in `show` partial there is no use for `@variants`
Variants are rendered in `cart_form`, but using another query

https://github.com/spree/spree/blob/master/frontend/app/views/spree/products/_cart_form.html.erb#L7

```ruby
@variants = @product.variants_including_master.
                  spree_base_scopes.
                  active(current_currency).
                  includes([:option_values, :images])
```

vs 

```ruby
@product.variants_and_option_values(current_currency).find_each
```

Maybe I'm missing something and it should be like this?

## Possible Fix

Use one correct query in controller

**Comment by damianlegawiec** [comment]
This logic was heavily changed in 4.1+, it should be fine now
