### ISSUE TITLE
Migration from Paperclip to ActiveStorage?

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#8633]
## Context
Paperclip maintainers are encouraging migration to ActiveStorage

See: https://github.com/thoughtbot/paperclip/pull/2568

**Comment by bbonislawski** [comment]
We're already working on painless migration to ActiveStorage but they're quite different solutions and we'll need some "hacks" probably to make migration easy. If you have any ideas/code for that, I'd be really grateful

**Comment by mike-burns** [comment]
We'd love to have lessons learned along the way added to our migration guide: https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md

**Comment by bbonislawski** [comment]
We'll definitely add them. We have some custom magic done in few places and we'll have to cover these things to. Thank you for your great job @mike-burns , it'll definitely help us
