### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Jyothsna92** [spree/spree#8637]
## Context

Unable to do payment with braintree production account and order is  not completed
## Expected Behavior

Should be able to do payment successfully and order should be completed
## Actual Behavior

while doing the payment step in checkout it is going to confirmation step and after that it is again redirecting to payment step.it is halting the chain :ensure_valid_state and redirecting back again.but it is working fine with sandbox account.only the issue with the braintree production account
## Steps to Reproduce

1.Integrate spree wih braintree production paypal
2. try to place order with credit card
3.proceed to payment step
4.the confirmation will redirect to payment step again

## Your Environment

* Version used: Rails 4.1
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by bbonislawski** [comment]
How did  you integrate spree with braintree?

**Comment by bbonislawski** [comment]
I'm assuming this is stale and we don't have enough details to do something about it. Closing until moment we get some details
