### ISSUE TITLE
Address mutiplication in DB

### ISSUE THREAD

**Issue by MateoLa** [spree/spree#8647]
save_user_address on checkout/address is always adding new inputs in spree_addresses table.

## Context
For any user when a new order is placed and the check_box "save_user_address" is selected (in checkout/address state) two new inputs are added to the addresses table no matter if the user address was saved before.

If is the first order for the user then 4 new address are saved in the spree_addresses table (billing, shipping and its duplicates if "save_user_address" is selected).

## Expected Behavior
Doesn't duplicate addresses when placing the first order.
No address would be added to the table if the addresses where saved before.

## Steps to Reproduce
Use a clean install of spree, spree_auth and spree_gateway.

## Your Environment
rails 5.1
ruby 2.4.3

my Gemfile:

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.5'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

'# Windows does not include zoneinfo files, so bundle the tzinfo-data gem'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

'# Traslations'
gem 'rails-i18n', '~> 5.1'

'# spree e-commerce'
gem 'spree', '~> 3.4.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'

**Comment by bbonislawski** [comment]
Hello, thanks for reporting this, but I think that I can finally write `it's a feature, not a bug`. `Save user address` means `save user address`. How would you like to handle situation for someone going back and forth in checkout form? We cannot reuse instances of addresses since they would be shared across orders(actually, there was bug that editing address in new order would overwrite addresses in older orders).  

I think that this is expected result, not a bug. What do you think about this?

**Comment by MateoLa** [comment]
Hello Bartosz. 
Thank you for your explanation. I can see your point and you are right.
Sorry for open a wrong issue.
Thanks, Mateo.
