### ISSUE TITLE
Cart - checkout issue 

### ISSUE THREAD

**Issue by 2bspree** [spree/spree#8657]
#Steps to produce the issue

1. Login as user 
2. Add product to the cart 
3. Remove the product from the cart (Product is removed from the cart )
4. But , the product id still exist in the checkout button in the cart page [modal] , causing error ...

For Instance ,  

I have 3 items in my cart with product id's -  '400' ,' 401' ,' 402' .
Even if i remove the item '400' from the cart.. The checkout form action results in the query as below 

SELECT `spree_line_items`.* FROM `spree_line_items` WHERE `spree_line_items`.`order_id` = 195 AND `spree_line_items`.`id` IN **(400, 401, 402)** ORDER BY spree_line_items.created_at ASC .

And this causes the error page 

![scrnshot](https://user-images.githubusercontent.com/27199223/38408327-a51f65a4-399a-11e8-898e-1d682c0a7e24.png)

Please help me to solve this ..

**Comment by bbonislawski** [comment]
Hello @2bspree 

Can you provide more details about this issue? What version of Spree do you use? And what browser? I can't reproduce it on my local machine so I need to know more
