### ISSUE TITLE
Cannot create Heroku Sandbox

### ISSUE THREAD

**Issue by williammead** [spree/spree#8676]
When trying to create new app on Heroku, build fails with error below.

`Bundle Output: Fetching https://github.com/spree/spree_auth_devise.git
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java.
       Fetching gem metadata from https://rubygems.org/............
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Resolving dependencies...
       The latest bundler is 1.16.1, but you are currently running 1.15.2.
       To update, run gem install bundler
       Bundler could not find compatible versions for gem "rails":
In Gemfile:
rails (~> 5.2.0)
spree was resolved to 3.5.0.alpha, which depends on
spree_core (= 3.5.0.alpha) was resolved to 3.5.0.alpha, which depends on
rails (~> 5.1.5)
Failed to install gems via Bundler.
Push rejected, failed to compile Ruby app.
Push failed`

**Comment by yann120** [comment]
Same for me :(

**Comment by bbonislawski** [comment]
We know about the issue. We will be able to fix it after releasing of spree 3.5.0(which will happen really soon!). For now, you can use this link https://heroku.com/deploy?template=https://github.com/spark-solutions/spree/tree/rails-5-2-test

**Comment by bbonislawski** [comment]
Already fixed
