### ISSUE TITLE
Admin doesnt load javascript on the first page load (no errors or warnings)

### ISSUE THREAD

**Issue by ozkar99** [spree/spree#8683]
Has anyone encountered this problem?

The first time i load an admin action (for instance /admin/products/:id/edit)

The filter function doesnt work, until i refresh, then it works.
This happens all admin wide, affecting also the search filter drop-down, and also making the `confirm('Are you sure?')`  dialog when deleting an item pop **twice**

Doesn't log anything to console, and have no idea what could be the case, just checking if anyone has any idea what could be the cause.

Example:
(disregard the missing translation for the custom menu item)

First load:
![image](https://user-images.githubusercontent.com/4227887/39386925-65f0b7c2-4a3c-11e8-80fc-69b9fe14aad6.png)

After refresh:
![image](https://user-images.githubusercontent.com/4227887/39386957-9374fcf8-4a3c-11e8-860d-fea0238e4923.png)

This happens both on development and production, any ideas what could be the cause?

**Comment by nischay-webonise** [comment]
Hello @ozkar99 
I tried installing latest spree on my local machine and couldn't reproduce the issue. Can you provide following details about this issue?
-> Spree Version
-> Browser with version
-> Gems list you are using

**Comment by ozkar99** [comment]
@nischay-webonise , disabling turbo-links seemed to do the trick, its not critical for me to have it, so i am just gonna remove it for now. Thanks for your time.

Also, here's the requested data (atleast for the record):

Spree Version: `3.4.4`
Rails Version: `5.1.4`
Browser: `Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)`

Complete Gemfile For the record:
```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.3.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'chartkick', '~> 2.3.4'

# Spree stuff
gem 'spree', '~> 3.4.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings'

# Aws stuff
gem 'aws-record', '~> 1.0'
gem 'aws-sdk', '~> 2.5'

# delayed job for mails
gem 'delayed_job', '~> 4.1.4'
gem 'delayed_job_active_record', '~> 4.1.2'

# to compile assets without access to production database
gem 'activerecord-nulldb-adapter', '~> 0.3.8'

# prometheus metrics
gem 'prometheus-client', '~> 0.7.1'

# Job scheduler for Rails
gem 'crono', '~> 1.1.2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'rspec-rails', '~> 3.7'
  gem 'rspec-mocks', '~> 3.7'
  gem 'selenium-webdriver', '~> 3.9'
  gem 'rubocop', '~> 0.54', require: false
  gem 'byebyebug', '0.3.1', require: false
  gem 'rails-controller-testing', '~> 1.0.2'
  gem 'factory_bot_rails', '~> 4.8.2'
  gem 'ffaker', '~> 2.8.1'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 2.0.2'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'i18n_yaml_sorter', '~> 0.2.0'
  gem 'letter_opener', '~> 1.6'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

**Comment by nischay-webonise** [comment]
You are welcome @ozkar99, I will take a look if I can reproduce your issue using your version without disabling turbolinks. :+1:

**Comment by ozkar99** [comment]
@nischay-webonise , if you need anything else, feel free to comment on this, and ill help with what i can. 
(unfortunatly the repo is private so i cant share all the source code, but ill try to paste anything you need).
