### ISSUE TITLE
Unable to connect to Authorize.net Gateway

### ISSUE THREAD

**Issue by gles8705** [spree/spree#8687]
Hello!  I've been on the phone with merchant providers all day, and no one can figure out what's going on.  We haven't changed our payment method gateway in 3 years, and everything was working fine yesterday, but today for some reason we're unable to connect to Authorize.net through Spree's default gateway anymore.  

Is this an issue anyone else is running into?

**Comment by macmm** [comment]
I am having the same issue. Which version of Spree are you on? We're on 2.4.

**Comment by joekr** [comment]
It turns out they updated some cert on their end. I'm still digging into what is going on. The Customer Support person said we needed to update using the following:

> Entrust Certification Authority - L1K
> AIA: http://aia.entrust.net/l1k-chain256.cer

**Comment by bbonislawski** [comment]
As @joekr said, this is not an issue with spree. Closing
