### ISSUE TITLE
Order not found because token changed

### ISSUE THREAD

**Issue by janmetten** [spree/spree#8761]
We have occurrences where a customer returns from the payment provider (Adyen) with a different guest token than the one that is stored with the order in Spree. When this happens the order cannot be found and the payment status is not stored.

We are not sure when this happens. One possible scenario might be that the customer uses a bank app to submit the payment, and the bank app opens a new browser. This causes a new guest token to be created.

This scenario can be reproduced by creating an order and instead of clicking on the 'Pay with Adyen' link open this link in an incognito window (or copy the link and open it in a different browser).

We can solve this by instead of using the guest token, use the merchantReference we get back from the payment provider to find the order (since this contains the Spree order.number). Or only do this when the order cannot be found using the guest token. The code that needs to be changed is in find_order_by_token_or_user in order.rb (in core/controller_helpers).

I wonder if I overlook something when we do this. It seems to be simpler to find the order from the order number, so why doesn't Spree do this in the first place?

**Comment by bbonislawski** [comment]
We cannot use order number to identify guest orders since anyone could access any such order with changing order number in link. Guest token is kind of authorization thing to be sure that you're owner of order.
