### ISSUE TITLE
Shipping amount is getting changed for partial refund

### ISSUE THREAD

**Issue by GopalChavan** [spree/spree#8800]
While doing partial refund the shipping amount is getting changed.
So while tracing finally I came across the method *shipping_rates* in estimator.rb file where its call the method calculate_shipping_rates and getting default shipping amount which is deleting existing shipping rates table records and adding new records with some default shipping amount.
But I was thinking that there would be no need to call shipping update methods for refund of any order
The trace was
refund.rb file -> perform! method its calling to update_order method
refund.rb file-> update_order method its calling payment.order.updater.update
order_updater.rb ->update method its calling update_shipments and I think for refund there is no need to execute the following methods
update_shipments

**Comment by VygovskySergey** [comment]
@GopalChavan, could you provide more explanatory steps for reproduce?
