### ISSUE TITLE
Remove OrderContents usage from codebase

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#8838]
After deprecating OrderContents and introducing SOA to the codebase we need to remove all possible deprecations from the core and migrate OrderContents usage to new service objects. 

* `order_merger_spec.rb`
* Order model itself

```
DEPRECATION WARNING:         Order#add is deprecated and will be removed in Spree 4.0. Please use
        Spree::CompareLineItems service instead.
 (called from block in find_line_item_by_variant at /home/circleci/spree/core/app/models/spree/order.rb:314)
```

**Comment by bbonislawski** [comment]
I'd add that we need to migrate tests from order_contents to service objects tests since they're not covered at the moment

**Comment by damianlegawiec** [comment]
@bbonislawski let's do it :)
