### ISSUE TITLE
Upgrading From 3.4.5 to 3.5.0 PG::AmbiguousColumn: ERROR

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#8840]
## Context
When upgrading from 3.4.5 to 3.5.0 following the upgrade instructions, and running the db:migrate as instructed I run into the following error when logging into admin/orders

`PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous
LINE 1: SELECT DISTINCT "name", "spree_stores"."id" FROM "spree_stores" INNER JOIN "spree_store_translations" ON "spree_store_translations"."spree_store_id" = "spree_stores"."id" WHERE "spree_store_translations"."locale" IN ('en', 'de', 'fr', 'it', 'es', 'sv') ORDER BY "spree_store_translations"."name" ASC`

## Expected Behavior
A list of previous orders to load up.

## Actual Behavior
Rails Error page

## Your Environment

ruby-2.4.4
rails 5.1.6

`     log(sql, name, binds, type_casted_binds) do
            ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
              @connection.async_exec(sql, type_casted_binds)
            end
          end
        end`

`activerecord (5.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:616:in "async_exec"
activerecord (5.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:616:in "block (2 levels) in exec_no_cache"
activesupport (5.1.6) lib/active_support/dependencies/interlock.rb:46:in "block in permit_concurrent_loads"
activesupport (5.1.6) lib/active_support/concurrency/share_lock.rb:185:in "yield_shares"
activesupport (5.1.6) lib/active_support/dependencies/interlock.rb:45:in "permit_concurrent_loads"
activerecord (5.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:615:in "block in exec_no_cache"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:613:in "block (2 levels) in log"
/Users/Matt/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in "mon_synchronize"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:612:in "block in log"
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in "instrument"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract_adapter.rb:604:in "log"
activerecord (5.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:614:in "exec_no_cache"
activerecord (5.1.6) lib/active_record/connection_adapters/postgresql_adapter.rb:601:in "execute_and_clear"
activerecord (5.1.6) lib/active_record/connection_adapters/postgresql/database_statements.rb:79:in "exec_query"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:371:in "select"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:42:in "select_all"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:95:in "block in select_all"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:118:in "block in cache_sql"
/Users/Matt/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in "mon_synchronize"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:104:in "cache_sql"
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/query_cache.rb:95:in "select_all"
activerecord (5.1.6) lib/active_record/relation/calculations.rb:176:in "pluck"
spree_backend (3.5.0) app/views/spree/admin/orders/index.html.erb:117:in "block (2 levels) in _8a8d4def197bac7236c51433232301d8"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:39:in "block in capture"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:203:in "with_output_buffer"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:39:in "capture"
actionview (5.1.6) lib/action_view/helpers/form_helper.rb:450:in "form_for"
ransack (1.8.8) lib/ransack/helpers/form_helper.rb:34:in "search_form_for"
spree_backend (3.5.0) app/views/spree/admin/orders/index.html.erb:12:in "block in _8a8d4def197bac7236c51433232301d8"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:39:in "block in capture"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:203:in "with_output_buffer"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:39:in "capture"
actionview (5.1.6) lib/action_view/helpers/capture_helper.rb:153:in "content_for"
spree_backend (3.5.0) app/views/spree/admin/orders/index.html.erb:9:in "_8a8d4def197bac7236c51433232301d8"
actionview (5.1.6) lib/action_view/template.rb:157:in "block in render"
activesupport (5.1.6) lib/active_support/notifications.rb:168:in "instrument"
actionview (5.1.6) lib/action_view/template.rb:352:in "instrument_render_template"
actionview (5.1.6) lib/action_view/template.rb:155:in "render"
deface (1.3.0) lib/deface/action_view_extensions.rb:41:in "render"
actionview (5.1.6) lib/action_view/renderer/template_renderer.rb:52:in "block (2 levels) in render_template"
actionview (5.1.6) lib/action_view/renderer/abstract_renderer.rb:42:in "block in instrument"
activesupport (5.1.6) lib/active_support/notifications.rb:166:in "block in instrument"
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in "instrument"
activesupport (5.1.6) lib/active_support/notifications.rb:166:in "instrument"
actionview (5.1.6) lib/action_view/renderer/abstract_renderer.rb:41:in "instrument"
actionview (5.1.6) lib/action_view/renderer/template_renderer.rb:51:in "block in render_template"
actionview (5.1.6) lib/action_view/renderer/template_renderer.rb:59:in "render_with_layout"
actionview (5.1.6) lib/action_view/renderer/template_renderer.rb:50:in "render_template"
actionview (5.1.6) lib/action_view/renderer/template_renderer.rb:14:in "render"
actionview (5.1.6) lib/action_view/renderer/renderer.rb:42:in "render_template"
actionview (5.1.6) lib/action_view/renderer/renderer.rb:23:in "render"
actionview (5.1.6) lib/action_view/rendering.rb:103:in "_render_template"
actionpack (5.1.6) lib/action_controller/metal/streaming.rb:217:in "_render_template"
actionview (5.1.6) lib/action_view/rendering.rb:83:in "render_to_body"
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:52:in "render_to_body"
actionpack (5.1.6) lib/action_controller/metal/renderers.rb:141:in "render_to_body"
actionpack (5.1.6) lib/abstract_controller/rendering.rb:24:in "render"
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:36:in "render"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:44:in "block (2 levels) in render"
activesupport (5.1.6) lib/active_support/core_ext/benchmark.rb:12:in "block in ms"
/Users/Matt/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in "realtime"
activesupport (5.1.6) lib/active_support/core_ext/benchmark.rb:12:in "ms"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:44:in "block in render"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:87:in "cleanup_view_runtime"
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:29:in "cleanup_view_runtime"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:43:in "render"
actionpack (5.1.6) lib/action_controller/metal/implicit_render.rb:33:in "default_render"
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in "block in send_action"
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in "tap"
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in "send_action"
actionpack (5.1.6) lib/abstract_controller/base.rb:186:in "process_action"
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in "process_action"
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in "block in process_action"
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in "run_callbacks"
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in "process_action"
actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in "process_action"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in "block in process_action"
activesupport (5.1.6) lib/active_support/notifications.rb:166:in "block in instrument"
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in "instrument"
activesupport (5.1.6) lib/active_support/notifications.rb:166:in "instrument"
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in "process_action"
actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in "process_action"
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in "process_action"
actionpack (5.1.6) lib/abstract_controller/base.rb:124:in "process"
actionview (5.1.6) lib/action_view/rendering.rb:30:in "process"
actionpack (5.1.6) lib/action_controller/metal.rb:189:in "dispatch"
actionpack (5.1.6) lib/action_controller/metal.rb:253:in "dispatch"
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in "dispatch"
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in "serve"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in "block in serve"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in "each"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in "serve"
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in "call"
railties (5.1.6) lib/rails/engine.rb:522:in "call"
railties (5.1.6) lib/rails/railtie.rb:185:in "public_send"
railties (5.1.6) lib/rails/railtie.rb:185:in "method_missing"
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in "block in <class:Constraints>"
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in "serve"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in "block in serve"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in "each"
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in "serve"
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in "call"
versioncake (3.3.0) lib/versioncake/rack/middleware.rb:17:in "call"
warden (1.2.7) lib/warden/manager.rb:36:in "block in call"
warden (1.2.7) lib/warden/manager.rb:35:in "catch"
warden (1.2.7) lib/warden/manager.rb:35:in "call"
rack (2.0.5) lib/rack/etag.rb:25:in "call"
rack (2.0.5) lib/rack/conditional_get.rb:25:in "call"
rack (2.0.5) lib/rack/head.rb:12:in "call"
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in "context"
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in "call"
activerecord (5.1.6) lib/active_record/migration.rb:556:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in "block in call"
activesupport (5.1.6) lib/active_support/callbacks.rb:97:in "run_callbacks"
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in "call"
rollbar (2.16.2) lib/rollbar/middleware/rails/rollbar.rb:24:in "block in call"
rollbar (2.16.2) lib/rollbar.rb:146:in "scoped"
rollbar (2.16.2) lib/rollbar/middleware/rails/rollbar.rb:22:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in "call"
rollbar (2.16.2) lib/rollbar/middleware/rails/show_exceptions.rb:22:in "call_with_rollbar"
web-console (3.6.2) lib/web_console/middleware.rb:135:in "call_app"
web-console (3.6.2) lib/web_console/middleware.rb:30:in "block in call"
web-console (3.6.2) lib/web_console/middleware.rb:20:in "catch"
web-console (3.6.2) lib/web_console/middleware.rb:20:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in "call"
railties (5.1.6) lib/rails/rack/logger.rb:36:in "call_app"
railties (5.1.6) lib/rails/rack/logger.rb:24:in "block in call"
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in "block in tagged"
activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in "tagged"
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in "tagged"
railties (5.1.6) lib/rails/rack/logger.rb:24:in "call"
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in "call"
request_store (1.4.1) lib/request_store/middleware.rb:19:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in "call"
rack (2.0.5) lib/rack/method_override.rb:22:in "call"
rack (2.0.5) lib/rack/runtime.rb:22:in "call"
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in "call"
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in "call"
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in "call"
rack (2.0.5) lib/rack/sendfile.rb:111:in "call"
railties (5.1.6) lib/rails/engine.rb:522:in "call"
puma (3.11.4) lib/puma/configuration.rb:225:in "call"
puma (3.11.4) lib/puma/server.rb:632:in "handle_request"
puma (3.11.4) lib/puma/server.rb:446:in "process_client"
puma (3.11.4) lib/puma/server.rb:306:in "block in run"
puma (3.11.4) lib/puma/thread_pool.rb:120:in "block in spawn_thread"`

**Comment by dimon-k** [comment]
Before closing it we need to backport it to spree 3.5 and 3.6.
