### ISSUE TITLE
Installation: "Email is invalid"

### ISSUE THREAD

**Issue by ile** [spree/spree#8843]
## Context

I'm getting this in the installation:

![screenshot from 2018-06-17 22-20-02](https://user-images.githubusercontent.com/433707/41511442-64365a20-727f-11e8-8854-74e1c73f7fe8.png)

Also, I can't log in in the admin panel.

## Possible Fix

Seems like I don't get this error with Rails 5.2.0. Also logging in into admin panel works with Rails 5.2.0.

## Your Environment

* Version used: 3.6.0
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/ile/313a14cd17a1d1fa7f7d5380a60f04c9

**Comment by bbonislawski** [comment]
Spree 3.6.0 is running with rails 5.2 only. You said that you used 3.6.0 and it works with rails 5.2, so... when does it NOT work? I can't reproduce it

**Comment by ile** [comment]
Rails 5.1.4. The docs said to use 5.1.4.

**Comment by bbonislawski** [comment]
Yes. For spree 3.3. You used `~> 3.3` which installed Spree 3.6.

**Comment by ile** [comment]
Here the commands given are: https://guides.spreecommerce.org/developer/getting_started_tutorial.html

```
$ gem install rails -v 5.1.4
```
```
gem 'spree', '~> 3.3'
```

I'm just following the commands given there.

**Comment by VygovskySergey** [comment]
@ile Hi, there is really strange error, and its not reproducible.
