### ISSUE TITLE
Taxonomies + foreign language -> UrlGenerationError

### ISSUE THREAD

**Issue by ile** [spree/spree#8844]
## Context

I'm getting this error when I changed the language (to Finnish). The language change works in the admin panel (I see Finnish there), so I suppose it's not wrongly set up.

The shop url / gives this:

```ActionController::UrlGenerationError in Spree::Home#index```

```
     <% if taxonomy.root.children.any? %>
        <h4 class='taxonomy-root'><%= Spree.t(:shop_by_taxonomy, taxonomy: taxonomy.name) %></h4>
        <%= taxons_tree(taxonomy.root, @taxon, max_level) %>
      <% end %>
    <% end %>
  <% end %>


```

## Steps to Reproduce

Use the relevant Gemfile and it should happen.

## Your Environment

* Version used: 3.6.0
* Rails 5.2.0 (because https://github.com/spree/spree/issues/8843)
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/ile/a76ca55877b47983109b4ebc633aa614

**Comment by ile** [comment]
When I try to edit the taxonomies now (Spree 3.6.0, Rails 5.2.0) there seem to be a some kind of infinite loop. The console messages go on-and-on, and the 'loading' icon keeps spinning.

**Comment by ile** [comment]
Also I have a hard time of adding "SUPPORTED LOCALES" at http://127.0.0.1:3000/admin/general_settings/edit

I can't seem to add one. I see the select box, but selecting one doesn't actually happen (nothing happens when I try to select one).

**Comment by VygovskySergey** [comment]
@ile Hello, can you describe more steps for reproduce, because right now, I can't reproduce your bug, thanks in advance.
