### ISSUE TITLE
unable to run the taxon Icon migration  

### ISSUE THREAD

**Issue by paras-ziggletech** [spree/spree#8854]
Unabe to run the taxon icon change migration,

rails db:migrate_taxon_icons

when running this nothing happens, i think the migration is missing. but is error doesn't displays in 3.4 as the icon related columns are still there in taxon table but in 3.5 there is a migration to remove those column so the images are lost.

**Comment by bbonislawski** [comment]
You should bump version to 3.4, run migration and then bump to higher version. This migration was meant to be done during update from 3.3 to 3.4. Did you try to do it like this?

**Comment by paras-ziggletech** [comment]
yes, but no migration file was generated in 3.4
