### ISSUE TITLE
Invalid route name, already in use: 'admin'

### ISSUE THREAD

**Issue by cgcmart** [spree/spree#8861]
when run rails g spree:install the error appeared.  
 `add_route': Invalid route name, already in use: 'admin'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)

 from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_backend-3.6.1/config/routes.rb:186:in `block in main'

`get Spree.admin_path, to: redirect((spree_path + Spree.admin_path + '/orders').gsub('//', '/')), as: :admin`

## Context

/root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:584:in `add_route': Invalid route name, already in use: 'admin'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1932:in `add_route'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1903:in `decomposed_match'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1867:in `block in map_match'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1861:in `each'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1861:in `map_match'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1609:in `match'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:742:in `map_method'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:703:in `get'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_backend-3.6.1/config/routes.rb:186:in `block in <main>'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:641:in `instance_exec'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:641:in `block in with_default_scope'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:878:in `scope'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:640:in `with_default_scope'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:430:in `eval_block'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.6.1/lib/spree/core/routes.rb:38:in `eval_block'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.6.1/lib/spree/core/routes.rb:30:in `block in draw_routes'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.6.1/lib/spree/core/routes.rb:30:in `each'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.6.1/lib/spree/core/routes.rb:30:in `draw_routes'
        from /root/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spree_core-3.6.1/config/routes.rb:5:in `<main>'

## Steps to Reproduce

1. bundle install
2. rails g spree:install
3.
4.

## Your Environment

* Version used: spree 3.6.1, rails 5.2
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by aniketstiwari** [comment]
The issue is basically you have defined admin route twice
