### ISSUE TITLE
[documentation feature request] Add a postman/insomnia file to the documentation. 

### ISSUE THREAD

**Issue by kapad** [spree/spree#8881]
I've just started using Spree, and find that the API documentation is very clear and concise. One thing that I found missing (rather I have a need for) is a postman/insomnia export file that would have a template for all the API calls. I can then easily use this file to build my API test suite.

**Comment by damianlegawiec** [comment]
Hety @kapad for the new API V2 we're writing documentation in OpenAPI 3.0 (aka Swagger v3) and we're waiting for [this issue](https://github.com/postmanlabs/postman-app-support/issues/3390) to be resolved on Postman end. 

You can check the current docs here: https://github.com/spree/spree/blob/master/api/docs/v2/storefront/index.yaml

**Comment by kapad** [comment]
Hey @damianlegawiec - thanks for your response. the link helped me figure out the auth token and was helpful. 

btw, is the v2 API a part of spree v3? Or is this a WIP for a later version? I'm wondering if it would make sense to somehow convert this file so that some of my boilerplate would be reduced.

**Comment by damianlegawiec** [comment]
@kapad API v2 will be released in parts - Storefront part (public API for building storefronts) will be part of Spree 3.7. Platform API (all operations that can be done in Admin Panel plus more) will be released with Spree 3.8 and 4.0. We're working as much as we can, to ease the migration path from 3.x to 4.0.

**Comment by kapad** [comment]
Okay thanks.

Sorry if the questions were nooblike. I'm just getting started with spree
(and Ruby and rails too, for that matter) and using it for the first time.

**Comment by rhuanbarreto** [comment]
Please let's upvote the trello card on https://trello.com/c/JEgGQfvh
Then they can prioritize this!

**Comment by damianlegawiec** [comment]
Postman supports OpenAPI out of the box now - http://blog.getpostman.com/2018/12/11/postman-supports-openapi-3-0/

You can easily import the raw yaml file https://raw.githubusercontent.com/spree/spree/master/api/docs/v2/storefront/index.yaml
