### ISSUE TITLE
Undefined method thrown during S3 integration

### ISSUE THREAD

**Issue by mbalc** [spree/spree#8893]
Hey, I'm trying to implement S3 integration with an app built on Spree, but I can't get it up running according to your guides. Even a newly-built app fails.

## Steps to Reproduce
1. Set up a new app according to [Getting Started](https://guides.spreecommerce.org/developer/getting_started_tutorial.html)
2. Follow [Use S3 for storage](https://guides.spreecommerce.org/developer/s3_storage.html) guide:
  a. Append `gem 'aws-sdk'` to Gemfile
  b. Run `bundle install`
  c. Append attachment_config script from link to `config/intializers/spree.rb`
3. Run `bin/rails console` (actually, most other services, including `bin/rails server` and `bin/rails db:schema:load` end up the same way)

## Expected Behavior
The console should run fine

## Actual Behavior
The app throws a NoMethodError during initialization:

```
/home/mbalc/.gem/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_one_attached' for #<Cl
ass:0x00005648e37a6070> (NoMethodError)
```
I add full error trace in gist linked below

## Your Environment
Most no-brainer stuff I add [in this gist](https://gist.github.com/mbalc/9a90e5a40505e90673d0ffd3f1567f58); ask for any other things

### PS 
Probably related: [StackOverflow issue](https://stackoverflow.com/questions/51033335/undefined-method-has-one-attached-spree-aws-s3-product-images-rails/51307534#51307534)

**Comment by VygovskySergey** [comment]
Hello, @mbalc, thanks for your question, this documentation is working for paperclip attachment, and now we are in process of migration to ActiveStorage. So, right now you can use these docs http://edgeguides.rubyonrails.org/active_storage_overview.html#amazon-s3-service
As soon, as we update our documentation, I can send a link to this conversation

**Comment by mbalc** [comment]
Following with the knowledge concluded in the link provided helped me to configure my integration with S3, thanks for the feedback

**Comment by AhmedAliIbrahim** [comment]
@mbalc can you provide how did you did that ? i followed what's on the link but still no luck

**Comment by mbalc** [comment]
Hey @AhmedAliIbrahim 
I'm not sure what situation you're in; please provide some more info about what errors do you encounter, or are these the same as mine?

Here's a diff of a pull request of the project I work on that enabled the S3
https://gist.github.com/mbalc/4428361c985149fd3e5e7c6ac818d6f4

**Comment by mbalc** [comment]
The only other relevant change that was made there was to setup credentials via `rails credentials:edit`
