### ISSUE TITLE
Decorators stopped working after Spree update

### ISSUE THREAD

**Issue by donny741** [spree/spree#8898]
After I have updated my app from Spree 3.5 to version 3.6 every *_decorator.rb is getting ignored for some reason

## Your Environment

* Version used: Spree 3.6.2
* Gemfile and Gemfile.lock as text in a Gist: 
```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use mysql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# bootsnap
gem 'bootsnap', require: false

gem 'spree', '~> 3.6.1'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
gem 'spree_paysera', '~> 0.36', github: 'donny741/spree_paysera'
gem 'globalize', github: 'globalize/globalize'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content'
gem 'spree_social', github: 'spree-contrib/spree_social'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings'
gem 'premailer-rails'
gem 'spree_print_invoice', github: 'spree-contrib/spree_print_invoice', branch: 'master'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
`

**Comment by VygovskySergey** [comment]
@donny741 Hi, I have created application from scratch with your gems, and everything works fine with decorators

**Comment by thakurmihir** [comment]
> After I have updated my app from Spree 3.5 to version 3.6 every *_decorator.rb is getting ignored for some reason
> 
> ## Your Environment
> * Version used: Spree 3.6.2
> * Gemfile and Gemfile.lock as text in a Gist:
> 
> ```
> source 'https://rubygems.org'
> 
> git_source(:github) do |repo_name|
>   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
>   "https://github.com/#{repo_name}.git"
> end
> 
> 
> # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
> gem 'rails', '~> 5.2.0'
> # Use mysql as the database for Active Record
> gem 'pg'
> # Use Puma as the app server
> gem 'puma', '~> 3.7'
> # Use SCSS for stylesheets
> gem 'sass-rails', '~> 5.0'
> # Use Uglifier as compressor for JavaScript assets
> gem 'uglifier', '>= 1.3.0'
> # See https://github.com/rails/execjs#readme for more supported runtimes
> # gem 'therubyracer', platforms: :ruby
> 
> # Use CoffeeScript for .coffee assets and views
> gem 'coffee-rails', '~> 4.2'
> # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
> gem 'turbolinks', '~> 5'
> # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
> gem 'jbuilder', '~> 2.5'
> # Use Redis adapter to run Action Cable in production
> # gem 'redis', '~> 4.0'
> # Use ActiveModel has_secure_password
> # gem 'bcrypt', '~> 3.1.7'
> # bootsnap
> gem 'bootsnap', require: false
> 
> gem 'spree', '~> 3.6.1'
> gem 'spree_auth_devise', '~> 3.3'
> gem 'spree_gateway', '~> 3.3'
> gem 'spree_paysera', '~> 0.36', github: 'donny741/spree_paysera'
> gem 'globalize', github: 'globalize/globalize'
> gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
> gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
> gem 'spree_static_content', github: 'spree-contrib/spree_static_content'
> gem 'spree_social', github: 'spree-contrib/spree_social'
> gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings'
> gem 'premailer-rails'
> gem 'spree_print_invoice', github: 'spree-contrib/spree_print_invoice', branch: 'master'
> # Use Capistrano for deployment
> # gem 'capistrano-rails', group: :development
> 
> group :development, :test do
>   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
>   gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
>   # Adds support for Capybara system testing and selenium driver
>   gem 'capybara', '~> 2.13'
>   gem 'selenium-webdriver'
> end
> 
> group :development do
>   # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
>   gem 'web-console', '>= 3.3.0'
>   gem 'listen', '>= 3.0.5', '< 3.2'
>   # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
>   gem 'spring'
>   gem 'spring-watcher-listen', '~> 2.0.0'
> end
> 
> # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
> gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
> ```
> `

Same here, after updating to spree 3.6 and rails 5.2, decorators not working

**Comment by ElminDmitry** [comment]
The same 
gem 'rails', '~> 5.2.1'

**Comment by kimadactyl** [comment]
I have the same issue after upgrading to Spree 3.7, Rails 5.2.4.4, Ruby 2.6.6. Seems like neither the old (class_eval) or new (custom module) methods are being recognised.
