### ISSUE TITLE
Image url method not found - when loading thumbnails

### ISSUE THREAD

**Issue by kapad** [spree/spree#8901]
I get an error from the template saying `undefined method url for <object id>"

## Context
This issue is only cropping up when trying to generate the html for image thumbnails. 
The issue is seen in two separate cases of generating thumbnails. 

1. When generating a thumbnail for a product with multiple images where each image applies to all variants. 
2. When generating thumbnails for a product with multiple variants, and each variant having it's own images. (with no image attached to the master sku, and images only attached to the variant skus - clothing store)

## Expected Behaviour
I shouldn't get an error when rendering the product page. The image has been uploaded successfully and I can see the relevant entries in active_storage_attachments and spree_assets

### Case 1
1. Create a product. 
2. Add multiple images to the product. 
3. Load the product details page. 
### Case 2
1. Create a product
2. Create multiple SKUs for the product. (min 2). 
3. Add at least 1 image per sku
4. Load the product details page. 

## Your Environment
* Version used: 3.6.2
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/kapad/ff6466493cceb0a55d15d1730b431134
* Any relevant stack traces ("Full trace" preferred):
#### stack trace 1
```
ActionView::Template::Error (undefined method `url' for #<ActiveStorage::Attached::One:0x00007f0ba18d71c0>):
    3:   <ul id="product-thumbnails" class="thumbnails list-inline" data-hook>
    4:     <% @product.images.each do |i| %>
    5:       <li class='tmb-all tmb-<%= i.viewable.id %>'>
    6:         <%= link_to(image_tag(i.attachment.url(:mini), class: "thumbnail"), i.attachment.url(:product)) %>
    7:       </li>
    8:     <% end %>
    9: 
  
app/views/spree/products/_thumbnails.html.erb:6:in `block in _bf082f4225e10d0c609c3f3acc55bbaf'
app/views/spree/products/_thumbnails.html.erb:4:in `_bf082f4225e10d0c609c3f3acc55bbaf'
app/views/spree/products/show.html.erb:14:in `block in _1f53865bb942ac8547de15b8bbb228e0'
app/views/spree/products/show.html.erb:3:in `_1f53865bb942ac8547de15b8bbb228e0'
````
#### stack trace 2
```ruby
ActionView::Template::Error (undefined method `url' for #<ActiveStorage::Attached::One:0x00007f0b9000b2c8>):
    11:       <% @product.variant_images.each do |i| %>
    12:         <% next if @product.images.include?(i) %>
    13:         <li class='vtmb tmb-<%= i.viewable.id %>'>
    14:           <%= link_to(image_tag(i.attachment.url(:mini), class: "thumbnail"), i.attachment.url(:product)) %>
    15:         </li>
    16:       <% end %>
    17:     <% end %>

app/views/spree/products/_thumbnails.html.erb:14:in `block in _9fcfe31b5ed135234e4a6d35ab1b5d07'
app/views/spree/products/_thumbnails.html.erb:11:in `_9fcfe31b5ed135234e4a6d35ab1b5d07'
app/views/spree/products/show.html.erb:14:in `block in _809ca04513d85ed740693155e9422f1b'
app/views/spree/products/show.html.erb:3:in `_809ca04513d85ed740693155e9422f1b'
```

**Comment by VygovskySergey** [comment]
Hello, @kapad, I guess you have this problem because you haven't updated spree views, here is current version of this view, you can compare to what you have
https://github.com/spree/spree/blob/master/frontend/app/views/spree/products/_thumbnails.html.erb
