### ISSUE TITLE
available? never called in CustomTaxCalculator

### ISSUE THREAD

**Issue by factor4** [spree/spree#8910]
I want my custom tax calculators only be available if some conditions met. Customers who ship to a EU-Country (outside of Austria) `&&` have a valid EU-VAT number should be able to order without VAT. The VAT should therefore subtracted from the price (VAT is included in our price).

For this I created this two calculators:
```ruby
module Spree
  class Calculator::EuTax < Calculator

   ...

    def available?(line_item)
      conditions_met(line_item)
    end

    def compute_line_item(line_item)
      return 0
    end
  end
end
```
```ruby
module Spree
  class Calculator::NoEuTax < Calculator

    ...
    
    def available?(line_item)
      !conditions_met(line_item)
    end

    def compute_line_item(line_item)
      ...
    end
  end
end
```
My `conditions_met(line_item)` method return true or false if the customer have provided a EU-VAT number.

In the backend I defined two tax rates accordingly:
<img width="1060" alt="grafik" src="https://user-images.githubusercontent.com/783721/43322812-132a0ea6-91b0-11e8-911f-87d69b14441b.png">

With both tax rates active, only one of them is used no matter if the conditions met or not. If I remove one, the remaining work as expected. Also if I leave the other one in place.

To track down my issue I have done the following:
```ruby
def available?(line_item)
  Rails.logger.info '--------------------------------------------------'
  Rails.logger.info line_item.inspect
  Rails.logger.info '--------------------------------------------------'
  conditions_met(line_item)
end
```
But this never reached my console output. Is this still in use? The guides mention this and it reads as this fits my needs: https://guides.spreecommerce.org/developer/calculators.html#determining-availability 
Sorry if I misunderstood something...

Spree: 3.4.5
Rails: 5.1.6

**Comment by VygovskySergey** [comment]
@factor4  I found that `available?` only calls for `ShippingCalculators`
