### ISSUE TITLE
May I ask when the version 3.7 will be released? 

### ISSUE THREAD

**Issue by rogerluo410** [spree/spree#8913]
Because of other engine depends on it,  I have to work under Bootstrap 4.  

But, the 3.6 still uses bootstrap 3,  I noticed 3.7 could swap to bootstrap4.  

May I ask when the version 3.7 will be released?  

Reference: https://github.com/spree/spree/issues/8285

**Comment by damianlegawiec** [comment]
hey @rogerluo410 we're mostly working on the API v2 for Spree 3.7, our goal is to release it in a few weeks. Bootstrap 4 support could still be part of 3.7, we will know more in coming days if we have people available to do that switch (BS3->BS4) :)

**Comment by rogerluo410** [comment]
@damianlegawiec  thank you.

Hope BS4 used in 3.7

**Comment by MatthewKennedy** [comment]
I'd be tempted to to future proof Spree's dependency on any framework for the backend, and just create an easily updatable group of SVG icons to replace the existing Bootstrap 3 glyph icons dependency, use CSS Grid / Flexbox to replace the current Bootstrap 3 layout css and minimal amount of javascript to ad some slickness to the back end.

That way the Spree backend is never "out of date" so to speak, it's not tied to a framework version or a gem dependency or discontinued icon pack.

Using raw css html and js for the back end leaves the frontend free to use any framework gem without the risk of conflicts occurring, just a simple search and replace on the view files and you can swap out the class and ID's for any framework the front end devs intend to use.

It would take a chunk of work to do, don't get me wrong, I've attempted to update the Spree master branch to use Bootstrap 4 and that's no small job, you get 85% complete and begin to think, is it all going to be a waste of time, they probably won't accept it as a pull request and then 6 months after its finished the next bootstrap version is released.

**Comment by rogerluo410** [comment]
Hi, @MatthewKennedy ,   which version I can use without BS3?

**Comment by MatthewKennedy** [comment]
Hi @rogerluo410

Anyone looking to start a fresh Spree 3 project with Bootstrap 4 JS and SCSS on the Frontend, you can now use the following extension:
[https://github.com/MatthewKennedy/spree_bs4](url)

Be aware that your spree frontend view files will need updating from the old Bootstrap 3 classes to the new Bootstrap 4 classes where appropriate.

See the extension for more details.
