### ISSUE TITLE
Booting Spree 3.6.2 -> DB_EXCEPTIONS

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#8919]
## Context
Updating a project from Spree 3.5 running on Rails 5.1.6 to Spree 3.6.2 running on Rails 5.2.0 and when I start the rails server in development mode and visit localhost:3000 the first line in the terminal is:

.rvm/gems/ruby-2.5.1/gems/spree_core-3.6.2/app/models/spree/preferences/store.rb:9: warning: already initialized constant DB_EXCEPTIONS

followed by:

.rvm/gems/ruby-2.5.1/gems/spree_core-3.6.2/app/models/spree/preferences/store.rb:9: warning: previous definition of DB_EXCEPTIONS was here

**Comment by MatthewKennedy** [comment]
If it is just my project with the issue, can someone please point me in the right direction to fix this issue.

Thanks.

**Comment by Obi-TOB** [comment]
Hi, I have similar issues: 

I did not fully track it down, but it seems to occur only in one of these two cases:
1. Changing code while spree is running: Seems that the autoloading kicks in
2. I think I see this as well when I have WEB_CONCURRENCY > 1, but I'm not entirly sure, as it seems not always reproducible

**Comment by MatthewKennedy** [comment]
The waring is caused by this file: [https://github.com/spree/spree/blob/master/core/app/models/spree/preferences/store.rb](url)

You can stop the constant from being redefined by chancing the code slightly:
`unless defined? DB_EXCEPTIONS
  DB_EXCEPTIONS = if defined? PG
                    [PG::ConnectionBad, ActiveRecord::NoDatabaseError]
                  elsif defined? Mysql2
                    [Mysql2::Error::ConnectionError, ActiveRecord::NoDatabaseError]
                  else
                    [ActiveRecord::ConnectionNotEstablished, ActiveRecord::NoDatabaseError]
                  end
end` 

As I don't understand the full reasoning behind the constant DB_EXCEPTIONS and why it is being redefined I don't know if the above code suggestion would causing a bug to fix an already initialized constant warning.

**Comment by MatthewKennedy** [comment]
unless defined? DB_EXCEPTIONS

**Comment by MatthewKennedy** [comment]
Just a warning about a constant. after using for a while seems fine.
