### ISSUE TITLE
Cannot programmatically create product with image

### ISSUE THREAD

**Issue by Znow** [spree/spree#8920]
Hi

I have a hard time figuring out, how to create a product and assign a image to it, programmatically, with the latest version using activestorage.

There is not much info about how to do it, anywhere.

I have tried several stuff as below, but everytime I'm getting: "#<ActiveRecord::RecordInvalid: Validation failed: Attachment must be present>"

I have tried with a local file, and opening a file from a URL, and loading a file from URL to a Tempfile, all result in the above error.

```
file = open("../../spec/dummy/public/pexels-photo-823841.jpeg") 
^
2.3.4 :011 > file = open("public/pexels-photo-823841.jpeg")
 => #<File:public/pexels-photo-823841.jpeg>

image = Spree::Image.create!({:attachment => open(file), :viewable => product})
product.images << image

###

product.images << Spree::Image.create(attachment: file)

### 

image = product.images.new
image.attachment = file
image.save!

###

image = product.images.new
image.attachment.attach = file
image.save!

```

Tried this for example:
![image](https://user-images.githubusercontent.com/265719/43610033-7a436e9e-96a5-11e8-9ce6-ea76d2a5733a.png)

What am I doing wrong? :-)

Once I get it working, I will gladly write some documentation on how to do it, or a blog post or something. Have been using hours on this?

My scenario is, that im importing products from a CSV file - every product have a image URL; which needs to be created as an image for the product.

Thanks in advance,

Kind regards

**Comment by VygovskySergey** [comment]
@Znow Hey, if you want to add attachment programmatically with ActiveStorage, you should use another interface of attaching files.
Here you can find an example: https://github.com/spree/spree/blob/master/core/spec/models/spree/image_spec.rb

So, basically you need to use something like this:
```
file = open("../../spec/dummy/public/pexels-photo-823841.jpeg")
image = Spree::Image.create!(attachment: { io: file, filename: 'somename' })
product.images << image
```

Here is useful link: https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects

**Comment by Znow** [comment]
@VygovskySergey - Thanks alot, that made my day! Working as intended :-)

**Comment by Vito300187** [comment]
Спасибо большое, несколько дней не мог победить проблему, ошибка возникала при создании объекта и одновременно прокидывал картинку, с помощью path = Rails.root + 'app/assets/images' + 'bottle/1.jpg'
      Spree::Image.create!(attachment: File.open(path), viewable: product.master)

**Comment by sadfuzzy** [comment]
BTW, fetch image by URL:
```ruby
require 'open-uri'
file = URI.parse("https://placekitten.com/200/300").open
image = Spree::Image.create!(attachment: { io: file, filename: "kitten.jpg" })
```
