### ISSUE TITLE
Empty repository' when using `heroku git:clone` && repository '3-6-stable' not found

### ISSUE THREAD

**Issue by odyright** [spree/spree#8925]
**Why do I see a message 'You appear to have cloned an empty repository' when using `heroku git:clone`?**
i did :

1. `git remote add origin https://github.com/spree/spree/tree/3-6-stable` 
2. git pull origin master

but i got: `fatal: repository 'https://github.com/spree/spree/tree/3-6-stable/' not found`
![ftal](https://user-images.githubusercontent.com/4316506/43712989-9988c3ca-9967-11e8-9812-e2a32439cf56.PNG)

**Comment by VygovskySergey** [comment]
@odyright Hello, probably because remote repository looks like this `https://github.com/spree/spree.git`, and `3-6-stable` is only branch of remote rpository
