### ISSUE TITLE
ArgumentError in Spree::Home#index 

### ISSUE THREAD

**Issue by mices** [spree/spree#8940]
## Context
ArgumentError in Spree::Home#index
Showing /home/fugee/.rvm/gems/ruby-2.3.3/gems/spree_frontend-3.6.2/app/views/spree/home/index.html.erb where line #9 raised:

wrong number of arguments (given 3, expected 2)
Extracted source (around line #12):
15        attr_accessor :table

        def initialize(reflection, children)
          super(reflection.klass, children)

          @reflection = reflection

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by VygovskySergey** [comment]
The error was with `Rails 5.2.1` and `ransack` gem. Right now everything is fixed.
