### ISSUE TITLE
wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by MateoLa** [spree/spree#8941]
Migration make_existing_credit_cards_default.spree.rb gives this error.

## Context
rails 5.2.1
ruby 2.5.1

## Expected Behavior
run migrations.

## Actual Behavior
== 20180814205426 MakeExistingCreditCardsDefault: migrating ===================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 3, expected 2)
/home/mateo/mqa/db/migrate/20180814205426_make_existing_credit_cards_default.spree.rb:6:in `up'
/home/mateo/mqa/bin/rails:9:in `<top (required)>'
/home/mateo/mqa/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ArgumentError: wrong number of arguments (given 3, expected 2)
/home/mateo/mqa/db/migrate/20180814205426_make_existing_credit_cards_default.spree.rb:6:in `up'
/home/mateo/mqa/bin/rails:9:in `<top (required)>'
/home/mateo/mqa/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
mateo@mateo-HP:~/mqa$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
mateo@mateo-HP:~/mqa$ rails -v
Rails 5.2.1

## Possible Fix
I read in stackoverflow that ransack version for rails 5.2.1 must be grater than 2.0 and you are using ver 1.

## Steps to Reproduce 
In a clean install add spree gems, install or run migrations.

## Your Environment
Gemfile:

'source 'https://rubygems.org'
'git_source(:github) { |repo| "https://github.com/#{repo}.git" }
'
'ruby '2.5.1'
'
'# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
'gem 'rails', '~> 5.2.1'
'
'gem 'pg', '>= 0.18', '< 2.0'
'# Use Puma as the app server
'gem 'puma', '~> 3.11'
'# Use SCSS for stylesheets
'gem 'sass-rails', '~> 5.0'
'# Use Uglifier as compressor for JavaScript assets
'gem 'uglifier', '>= 1.3.0'
'# See https://github.com/rails/execjs#readme for more supported runtimes
'# gem 'mini_racer', platforms: :ruby
'
'# Use CoffeeScript for .coffee assets and views
'gem 'coffee-rails', '~> 4.2'
'# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
'gem 'turbolinks', '~> 5'
'# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
'gem 'jbuilder', '~> 2.5'
'# Use Redis adapter to run Action Cable in production
'# gem 'redis', '~> 4.0'
'# Use ActiveModel has_secure_password
'# gem 'bcrypt', '~> 3.1.7'
'
'# Use ActiveStorage variant
'# gem 'mini_magick', '~> 4.8'
'
'# Use Capistrano for deployment
'# gem 'capistrano-rails', group: :development
'
'# Reduces boot times through caching; required in config/boot.rb
'gem 'bootsnap', '>= 1.1.0', require: false
'
'group :development, :test do
'  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
'  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
'end
'
'group :development do
'  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
'  gem 'web-console', '>= 3.3.0'
'  gem 'listen', '>= 3.0.5', '< 3.2'
'  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
'  gem 'spring'
'  gem 'spring-watcher-listen', '~> 2.0.0'
'end
'
'group :test do
'  # Adds support for Capybara system testing and selenium driver
'  gem 'capybara', '>= 2.15'
'  gem 'selenium-webdriver'
'  # Easy installation and use of chromedriver to run system tests with Chrome
'  gem 'chromedriver-helper'
'end
'
'# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
'gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
'
'gem 'spree', '~> 3.6.1'
'gem 'spree_auth_devise', '~> 3.3'
'gem 'spree_gateway', '~> 3.3''

**Comment by damianlegawiec** [comment]
Hey @MateoLa ransack `2.0.0` still doesn't work with Rails `5.2.1` - see https://github.com/activerecord-hackery/ransack/issues/947 

For now please downgrade Rails to `5.2.0` and upgrade Spree to `3.6.3`

**Comment by MateoLa** [comment]
Ok. Thank yo Damian.

**Comment by MateoLa** [comment]
Please change   s.add_dependency 'ransack', '~> 1.8.0' to s.add_dependency 'ransack', '~> 2.0' in spree_core.gemspec.
With this change you could run migrations and use spree with rails 5.2.1.
(This also solves the same source of error in '<% cache(cache_key_for_products) %>' in home/index.html.erb view.)
Thanks, Mateo Laiño

**Comment by VygovskySergey** [comment]
The error was with `Rails 5.2.1` and `ransack gem`. Right now everything is fixed.

**Comment by neonishu** [comment]
This issue came up again.
`rails g spree:auth:install` does not work.
Rails: 6.0.3.1
Ruby: 2.7.1
Spree: 4.1.6
