### ISSUE TITLE
No spree folders in app/assets 

### ISSUE THREAD

**Issue by Altons** [spree/spree#8946]
There are no spree folders in:

```
app/assets/images/
app/assets/javascript/
app/assets/stylesheets/
```

## Context
I have a fresh install of spree 3.6 and `rails -s` render the site perfectly. However when looking at [https://guides.spreecommerce.org/developer/asset.html](https://guides.spreecommerce.org/developer/asset.html)
I have found that the above folders were **not** created as per documentation.

## Expected Behavior
```
app
|-- assets
    |-- images
    |   |-- spree
    |       |-- frontend
    |       |-- backend
    |-- javascripts
    |   |-- spree
    |       |-- frontend
    |       |   |-- all.js
    |       |-- backend
    |           |-- all.js
    |-- stylesheets
    |   |-- spree
    |       |-- frontend
    |       |   |-- all.css
    |       |-- backend
    |           |-- all.css

```

## Actual Behavior
```
app/assets
├── config
│   └── manifest.js
├── images
├── javascripts
│   ├── application.js
│   ├── cable.js
│   └── channels
└── stylesheets
    └── application.css
```

## Steps to Reproduce
1. add the following gems to Gemfile:
```
gem 'spree', '~> 3.6.3'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
```
2. `bundle _1.13.7_ install`
3. add these lines to `seeds.rb`:
```
require 'carmen'
Carmen.i18n_backend.locale = :es
```
4. run magics:
```
rails g spree:install --user_class=Spree::User
rails g spree:auth:install
rails g spree_gateway:install
rails g spree_i18n:install
```

## Your Environment
OS: Mac OSx High Sierra
ruby-version: 2.5.0

[Gemfile.lock](https://gist.github.com/Altons/436290026a9a705b1b6b8301c52662ad)

**Comment by Altons** [comment]
in addition to this there are no spree folders in either app/controllers or app/models. views is fine

**Comment by VygovskySergey** [comment]
@Altons Hi, I just bundled fresh project for `spree-3.6.4`, and after doing all your steps everything works fine.
