### ISSUE TITLE
REST API cache invalidation

### ISSUE THREAD

**Issue by mbalc** [spree/spree#8956]
We're building a custom frontend on React for your framework. We encountered an issue with cache invalidation for REST API responses that is only happening on our production-configured environments. The server responds with old data after a taxonomy name change - even hours after the change.

## Context
I also found an issue with quite similar symptoms [here](https://github.com/solidusio/solidus/issues/2237), but fixes contained there didn't seem to be relevant to a production environment, and as far as I understand Spree, they are already included in the version I use.

## Temporary fix
My quick fix was to effectively disable server-side caching with
```
config.cache_store = :memory_store, { size: 64.megabytes, expires_in: 5.seconds }
```
in `config/application.rb` - it's not recommended though, it slows down responses and increases db usage and costs

## Steps to Reproduce

1. View API response for `GET /products/`
2. Rename a taxonomy via panel
3. View API response for `GET /products/`
4. Do `rm -rf ./tmp/cache`
5. View API response for `GET /products/`

## Behavior
Product's classifications should have their name updated in the new response in 3., but API still returns an old one instead. After doing 4., response at 5. has the name updated.

## Your Environment
AWS production environment with connected S3 and MySQL services
[Gemfiles](https://gist.github.com/mbalc/90891eb185584bbadd50e50aafd3e1fb)

**Comment by damianlegawiec** [comment]
Hey @mbalc the old API v1 has more strict HTTP cache invalidation, you can check it here:

https://github.com/spree/spree/blob/master/api/app/controllers/spree/api/v1/products_controller.rb#L15

You could possibly change that to something more dynamic:

```
  def index
     if params[:ids]
            @products = product_scope.where(id: params[:ids].split(',').flatten)
          else
            @products = product_scope.ransack(params[:q]).result
          end

          @products = @products.distinct.page(params[:page]).per(params[:per_page])
  
          if stale?("#{products.ids}-#{products.maximum(:updated_at)}, public: true, expires_in: 1.day) do 
            respond_with(@products)
          end
   end
```

**Comment by mbalc** [comment]
I don't think this will be a fix for me - the issue wasn't with browser caching (and as far as I understand, the code from the link only deals with this type of cache), but rather server-sided one - i.e. server responds with old data even on totally new sessions. I'll try this patch in a minute though, just to confirm whether that's the case.

**Comment by damianlegawiec** [comment]
@mbalc if you're using https://github.com/rtomayko/rack-cache or any other CDN this cache will be used

https://guides.rubyonrails.org/caching_with_rails.html#conditional-get-support

**Comment by mbalc** [comment]
After fixing up some syntax stuff, the patch I applied to the product controller is:

```
    if stale?(etag: @products.ids, last_modified: @products.maximum(:updated_at), public: true)
      respond_with(@products)
    end
```

Unfortunately, the patch doesn't fix the issue with taxonomies. I noticed that even though changes to product names are reflected in API immediately, taxonomy names don't ever do so. 

If you want to see a live example I can PM you

**Comment by mbalc** [comment]
`taxonomies` endpoint responds with up-to-date data, though
