### ISSUE TITLE
ShippingTotalManager precision is hardcoded

### ISSUE THREAD

**Issue by ronzalo** [spree/spree#8966]
## Context
In the delivery step, when changing the delivery method, the total is recalculated in summary view but the precision of the amount is always 2.

## Expected Behavior
Amount precision must be the same of the order currency

## Actual Behavior
The amount includes decimals even if the currency of the order does not require decimals

## Possible Fix
Take the order currency format option and pass to accounting

**Comment by damianlegawiec** [comment]
To fix this we should change this line:

https://github.com/spree/spree/blob/1bbdc6727efc6bbc0fe162d4c8a70ad00665b813/frontend/app/assets/javascripts/spree/frontend/checkout/shipment.js#L11
