### ISSUE TITLE
slow loading

### ISSUE THREAD

**Issue by BadiuAlexandru** [spree/spree#8980]
I installed spree using this tutorial : https://guides.spreecommerce.org/developer/getting_started_tutorial.html . Everything was ok, but after I started the application I realized it was working very slow. Pages load after a few seconds and it is almost impossible to use. 

How can I speed up the app?

----
`Rails 5.2.1`

`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.3'

gem 'rails', '~> 5.2.1'
gem 'sqlite3'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'duktape'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'spree', '~> 3.6.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'`

**Comment by kozhin** [comment]
Hi @BadiuAlexandru !
In development it takes around 2-4s to load everything up (MacBook Pro, 4 core, 2.7 Ghz, 8Gb RAM). In production (with precompiled assets) my pages load at about ~350ms (database has only 10 products for now).

For development environment you can try set the following:

```
# config/environments/development.rb

config.assets.debug = false
```
Don't forget to restart your app.

Also you can use [webpacker](https://github.com/rails/webpacker) gem (as I do) but you will have to include all spree assets manually.
