### ISSUE TITLE
Best gateway for worldwide payment?

### ISSUE THREAD

**Issue by HElwy** [spree/spree#8981]
Hi all, I was trying to test the payment on Spree, tried using the Paypal gateway "Merchant country unsupported", and turns out Paypal on Spree only accepts from UK, US, and Canada. What is my best option to allow payment from all around the world? Thank you.

**Comment by damianlegawiec** [comment]
Take a look at the list here:
https://github.com/spree/spree_gateway#spree-gateway

most of those offer worldwide payments
