### ISSUE TITLE
Active Storage Uses Expiring Representations For Product Image URLs

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#8984]
## Context
Using Spree 3.6.4 and Active Storage to manage the product image uploads I get a representation URL in the product image views, this expires after 5 minutes making it extremely difficult to use a CDN or asset caching. 

## Expected Behavior
Generate a more permanent asset URL:
`http://localhost:3000/rails/active_storage/blobs/`

## Actual Behavior
Generates an expiring asset URL representation:
`http://localhost:3000/rails/active_storage/representations/` 

## Possible Fix
Having tested a new rails app with an implementation of Active Storage I can get a permanent asset path from active storage using `rails_blob_url` or `rails_blob_path`, but I can't find how to implement this into Spree.

## Steps to Reproduce
Using 3.6.4 standard install and the Active Storage for handling images.

**Comment by VygovskySergey** [comment]
Hi, @MatthewKennedy , this is the file where `url` has described https://github.com/spree/spree/blob/master/core/app/models/spree/asset/support/active_storage.rb

**Comment by MatthewKennedy** [comment]
I swapped out ``` attachment.variant(resize: dimensions_for_style(style)) ``` for ``` rails_blob_path(attachment, only_path: true) ```

You get a shorter and more permanent URL to the product image, but you only get the original image size.

I also tried using but it came up with errors asking for only_path: true, I couldn't get round them.
``` attachment.variant(resize: dimensions_for_style(style)).processed.service_url ```

**Comment by nick4tech** [comment]
Hello,

Did you ever solve this? I have the same problem and haven't found a solution. If I try to set the service to public in storage.yml I get an error when I try to resize the image

**Comment by damianlegawiec** [comment]
This is not an issue anymore with Rails 6.1 and Spree 4.2 - https://github.com/rails/rails/commit/94584c2510743a45d9030d1b94dd33a074518b17

**Comment by nick4tech** [comment]
I'm using rails 6.0.3 and spree 4.1, do you have any workarounds?
