### ISSUE TITLE
Cannot deploy demo to Heroku

### ISSUE THREAD

**Issue by kktam** [spree/spree#8985]
## Context

Deploy the Heroku demo package resulted in the following error in Heroku console window

## Actual Behavior

'''
-----> Ruby app detected
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.3.7.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.3.7.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
/app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/shell_helpers.rb:69:in `block in run!': Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.3.7.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/shell_helpers.rb:63:in `times'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/shell_helpers.rb:63:in `run!'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/fetcher.rb:24:in `fetch_untar'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/installers/heroku_ruby_installer.rb:22:in `block in fetch_unpack'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `chdir'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/lib/language_pack/installers/heroku_ruby_installer.rb:16:in `fetch_unpack'
	from /app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/bin/support/download_ruby:14:in `<main>'
/app/tmp/buildpacks/d9b9070fff2acfd7ccb990e60bb1b752287db13378b443bb1138765fa743d24a102b8ca60f8e2645756919779142b543b50764473133efb04c71758160d27a94/bin/compile: line 11: /tmp/tmp.80jifgCPFe/bin/ruby: No such file or directory
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
Build finished

'''

## Steps to Reproduce

1.  Goto https://github.com/spree/spree
2. Click link https://heroku.com/deploy?template=https://github.com/spree/spree/tree/3-6-stable
3. Fill in Heroku deploy form and deploy.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by VygovskySergey** [comment]
@kktam Thanks for mentioning this issue, its already fixed!
