### ISSUE TITLE
Special product discount

### ISSUE THREAD

**Issue by BertholetDamien** [spree/spree#9008]
Hi team !

I would like to know if it's possible to make a special product discount. And what the better way to do it (extension, native, etc.).

Like that:
![image](https://user-images.githubusercontent.com/2866194/46025757-a71c5480-c0b7-11e8-8795-e2a9e0363ef3.png)

Thank for your time !

**Comment by damianlegawiec** [comment]
Hey @BertholetDamien you can create a promotion for a specific product - you can use `Spree::Promotion::Rules::Product` for that:

https://github.com/spree/spree/blob/master/core/app/models/spree/promotion/rules/product.rb

**Comment by BertholetDamien** [comment]
@damianlegawiec 
Thank for your answer !

But can we do it throw the admin panel ? If not, an extension can be added to allow it ?

**Comment by damianlegawiec** [comment]
@BertholetDamien yes, you can add it in the spree admin panel

![screen shot 2018-09-26 at 6 40 11 pm](https://user-images.githubusercontent.com/55154/46094964-a79e1380-c1bb-11e8-85a5-236f8dc4da86.png)

**Comment by BertholetDamien** [comment]
@damianlegawiec 
Humm yes, I did that but these apply to the order, not directly on the item, no ?

Like in an api call 'api/v1/products/id', I haven't the information about the promotion.
There is an another way the catch the item promotion information to show it to the user?

Sorry for my english !

**Comment by BertholetDamien** [comment]
@damianlegawiec 
Any idea ? :(

**Comment by luisenrike** [comment]
Hi @BertholetDamien, you can check the `Advertise` checkbox in the admin panel and the user will see the promotion.

![spree_administration__promotions](https://user-images.githubusercontent.com/12720974/46224783-4bef9980-c325-11e8-84b2-02356b04dd0f.png)

![ruby_on_rails_tote_-_spree_demo_site](https://user-images.githubusercontent.com/12720974/46224752-3da17d80-c325-11e8-8731-387e88be9d09.png)

**Comment by BertholetDamien** [comment]
Thank @luisenrike !
That's work !

But do you know if I can have acces to this information with the REST API ?

**Comment by luisenrike** [comment]
I don't think there is but you could override this method and include the `promotions` field:

https://github.com/spree/spree/blob/master/api/app/controllers/spree/api/base_controller.rb#L151

**Comment by superchell** [comment]
@damianlegawiec Please tell me how to show discount prices on the product list page and on the product detail page? It's possible?
