### ISSUE TITLE
Rubocop deprecation warnings when using factories

### ISSUE THREAD

**Issue by SteveRedka** [spree/spree#9035]
## Context
I used factories provided by spree test helpers. They work; however, each time they are invoked, they spit out deprecation warnings:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

currency { "USD" }

To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct

 (called from <top (required)> at ~/projects/spark-test-task-solution/spec/rails_helper.rb:9)
```

## Possible Fix
```
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
```

## Steps to Reproduce
1. Setup spree
2. Require factories in `spec/rails_helper.rb`
3. Create a factory (say, `create(:admin_user)`)
It will write deprecation message whenever factory is invoked.

Example:
https://github.com/SteveRedka/spark-test-task-solution/tree/401825e59d3c53a10a51b35156bd1e3292bebf90

**Comment by damianlegawiec** [comment]
@SteveRedka all of those are fixed in the master branch
