### ISSUE TITLE
Spree extension versions compatibility list

### ISSUE THREAD

**Issue by exocode** [spree/spree#9042]
## Context

It would be nice to have a compatibility list for each plugin. This could be done in an easy markdonw table, which exists for Github. For me it is very hard to know and evaluate which Plugin extension works with which version of Spree. 

## Expected Behavior

- With a ready setup Spree Shop
- I wanna install an extension
- After executing their migrations and install scripts, it should work
- But nearby the half of the plugins listed in the `spree-contrib` repo is not working.

## Actual Behavior
I install a plugin (for example spree-multi-domain https://github.com/spree-contrib/spree-multi-domain), and run the migrations, all products are gone, and I am not able to run the backend:

```
Showing /Users/janjezek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spree_backend-3.5.0/app/views/spree/admin/orders/index.html.erb where line #117 raised:

Mysql2::Error: Column 'name' in field list is ambiguous: SELECT `name`, `spree_stores`.`id` FROM `spree_stores` INNER JOIN `spree_store_translations` ON `spree_store_translations`.`spree_store_id` = `spree_stores`.`id` WHERE `spree_store_translations`.`locale` = 'en' ORDER BY `spree_store_translations`.`name` ASC


def query(sql, options = {})       
  Thread.handle_interrupt(::Mysql2::Util::TIMEOUT_ERROR_CLASS => :never) do 
    _query(sql, @query_options.merge(options))
  end     
end
```

## Possible Fix
Create a Wiki Page, where all Plugins are listed with Markdown Checkboxes in Table: Example:

| Extension | < Version 3.5 | Version 3.5  | Version 3.6 | Version 4 | 
|---------------------------------- |---------------|---------------|----------------|-----------|
| Globalize       |  ✔︎   | ✔︎  |   | ✔︎ |
| Multi Domain   | ✔︎  |   | ✔︎ | |

**Comment by damianlegawiec** [comment]
Hey @exocode 

You can find a list of supported and updated extensions here:

https://github.com/spree/spree#extensions

As for the multi-domain issue - what Spree / Rails version are you running?
