### ISSUE TITLE
DockerHub: only latest unstable 3.7 available.

### ISSUE THREAD

**Issue by rdehuyss** [spree/spree#9055]
I'm looking into Spree and I'm using Docker to test it (and ideally also to run it with Docker in production).

However, currently only 3.7.0-alpha is available on DockerHub.

Would it be possible to make 3.6.4 and other stable builds available on DockerHub?

## Expected Behavior
docker run --rm -it -p 3000:3000 spreecommerce/spree:3.6.4 should work

## Actual Behavior
Pulling backend (spreecommerce/spree:3.6.4)...
ERROR: manifest for spreecommerce/spree:3.6.4 not found

## Possible Fix
Push docker-images to DockerHub

## Your Environment
Windows 10 (I know) with latest docker

**Comment by rdehuyss** [comment]
thanks. Can I help with something to get this done?

**Comment by bbonislawski** [comment]
Hey @rdehuyss , I just pushed `spreecommerce/spree:3.6.4` to dockerhub. Could you check if everything works fine for you?

**Comment by rdehuyss** [comment]
Perfect!

One thing though, I really struggled with adding extensions in the docker container (see github #9056).
In the end, I created my own Dockerfile as I did not succeed using your Dockerfile.

My first approach:

    FROM spreecommerce/spree

    #add spree-product-assenbly
    RUN echo "gem 'spree_product_assembly', github: 'spree-contrib/spree-product-assembly', branch: 'master'" >> Gemfile
    RUN bundle install
    RUN bundle exec rails g spree_product_assembly:install


Is there a best practice on how to add extensions when using Spree with Docker?

Thanks again!
R
