### ISSUE TITLE
Change sass-rails to sassc-rails

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#9057]
## Context
The Ruby Sass gem will be deprecated by March 26, 2019
http://sass.logdown.com/posts/7081811 so the suggestion is to use the
sassc gem. 

Boostrap 4 made the bump here https://github.com/twbs/bootstrap-rubygem/issues/159

Include this in Spree 4.0 - https://github.com/spree/spree/milestone/37

## Expected Behavior
Spree should reference `gem 'sassc-rails'` 

## Actual Behavior
Spree currently references `gem 'sass-rails'`

**Comment by damianlegawiec** [comment]
We still need to wait for some of our dependencies to catch up, moving this to `4.0` milestone

**Comment by ptonella** [comment]
Hey @damianlegawiec!
The sass-rails gem is deprecated since March. Any idea when the gem replacement will be available?
Thanks!

**Comment by damianlegawiec** [comment]
We don't need to change anything for now, `sass-rails` is just a wrapper around `sassc` in Rails 6.0

**Comment by ptonella** [comment]
@augustogoldoni FYI ☝️
