### ISSUE TITLE
updating product price for non admin role

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [spree/spree#9066]
Hello,
it's not an issue, it's just a question about giving a certain role ability to update product price.
I've created  a new role with permissions to update products and it works correctly except i can't update product price because of this line `disabled: (cannot? :update, @product.price) ` my question how can i give the role permission to update price ?! i tried `can :update, Spree::Price` but it doesn't work.

**Comment by damianlegawiec** [comment]
hey @AhmedAliIbrahim see https://guides.spreecommerce.org/developer/security.html#custom-authorization-rules
