### ISSUE TITLE
Update highline gem

### ISSUE THREAD

**Issue by chamnap** [spree/spree#9078]
## Context

Highline is currently locked to ~> 1.6.18 https://github.com/spree/spree/blob/master/core/spree_core.gemspec#L31, which is 4 or 5 years ago.

I need to use [i18n-tasks](https://rubygems.org/gems/i18n-tasks) along with `spree`, but I have to use the very old version since 3 years ago. Is there any reason why we can't just require '>= 1.6.18'?

**Comment by damianlegawiec** [comment]
hey @chamnap it was probably omitted by mistake, can you submit a pull request with this change?

**Comment by chamnap** [comment]
No, not a bug. I mean spree should use the more recent version of `highline`.

It was intented to use that version for a long time, https://github.com/spree/spree/commit/ae297004d103a5e2c6db2b9424cad7882127ca7d.
