### ISSUE TITLE
uninitialized constant Spree::Cart 

### ISSUE THREAD

**Issue by troias** [spree/spree#9086]
Hello, just started two new apps. Have not touched the back end or controllers and they are both getting this error.. Everything runs perfect but when you go to add an item to the cart it says 

NameError in Spree::OrdersController#populate 
uninitialized constant Spree::Cart
Extracted source (around line #57): 

      if quantity.between?(1, 2_147_483_647)
        begin
          result = Spree::Cart::AddItem.call(order: order, variant: variant, quantity: quantity, options: options)
          if result.failure?
            error = result.value.errors.full_messages.join(', ')
          else

**Comment by damianlegawiec** [comment]
hey @troias can you paste your `Gemfile.lock` file contents?
