### ISSUE TITLE
After applying coupon code inclusive tax adjustment is not updated

### ISSUE THREAD

**Issue by thakurmihir** [spree/spree#9118]
After applying coupon code to order, inclusive  tax is not recaluated, for order while checkout. Tax should be calculated on total after applying discount.

**Comment by factor4** [comment]
Same here with Free Shipping Promotion. Our shipping costs include tax. If the promotion apply, the tax adjustment remains.
```
Spree 3.6.4
Rails 5.2.1.1
```
I would be very happy if someone could help there!

**Comment by factor4** [comment]
Don´t know if this is related, but in my research I recognize the following:
-> Create an order in backend
-> Assign an user to the order
We have two shipping methods available in backend. One paid and one free shipping (flat rate with 0 amount). The paid one get´s applied automaticaly based on the users address/zone.
-> Changing the shipping method from the paid to the free one also leave the tax adjustment in place.
Should not the adjustment be deleted?

**Comment by factor4** [comment]
I solved the Free Shipping promotion like this in `app/models/spree/order_decorator.rb`:
```ruby
def apply_free_shipping_promotions
  Spree::PromotionHandler::FreeShipping.new(self).activate
  shipments.each { |shipment| Spree::Adjustable::AdjustmentsUpdater.update(shipment) }
  create_shipment_tax_charge! # Added this line to remove the unwanted tax adjustment.
  update_with_updater!
end
```

**Comment by factor4** [comment]
Editing the shipping costs in backend seems to be (just) a poor (backend) user experience. After changing the shipping method the tax adjustment stay in place. This let me think it´s related to my other issue. But if you add a payment and complete the order it disapears.

**Comment by factor4** [comment]
@thakurmihir With coupon codes I think this is the expected behavior. A coupon code is not a discount but something you pay for. For me it seems ok to leave the tax unchanged in this situation.

**Comment by thakurmihir** [comment]
@factor4 thanks for suggestions

**Comment by damianlegawiec** [comment]
Hey @factor4 could you create a PR with your fix? thanks :)

**Comment by factor4** [comment]
Hi @damianlegawiec I will do that the next days...

**Comment by damianlegawiec** [comment]
Thanks you @factor4 👍

**Comment by factor4** [comment]
Hi @damianlegawiec finaly my PR is there #9275. It take some time to get used with rspec. I think it is a known problem that the checks fail in building!?
