### ISSUE TITLE
NoMethodError in Spree::Admin::ImagesController#create in Rails 5.2.2

### ISSUE THREAD

**Issue by scottyeung** [spree/spree#9123]
## Expected Behavior
Image uploaded and displayed back in the Product panel.

## Actual Behavior
![screen shot 2018-12-12 at 7 57 34 pm](https://user-images.githubusercontent.com/23536187/49895389-34b24980-fe48-11e8-8a47-5ccc12203226.png)

## Steps to Reproduce

1. Upload image in Product admin panel

## Your Environment

* Version used: Rails 5.2.2, Spree 3.6.4
* Gemfile and Gemfile.lock as text in a Gist:

* Any relevant stack traces ("Full trace" preferred):

**Comment by MatthewKennedy** [comment]
I think you might have to use Spree 3.6.6 with rails 5.2.2

**Comment by MatthewKennedy** [comment]
I've just installed Spree 3.6.6 running on rails 5.2.2 and it works fine.

Did you run ```bundle update``` after changing to spree 3.6.6 in your gem file? I believe there was a dependency that needed updating when Rails 5.2.2 came out.

As for setting ```SPREE_USE_PAPERCLIP = true``` I think it would be best to join the spree Slack for support.
