### ISSUE TITLE
Rails 6.0 support

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#9170]
We should align Spree 4.0 release with Rails 6.0 release date (end of April 2019)

- [x] require Ruby 2.5
- [x] replace `update_attributes!` with `update`
- [x] drop `rspec-collection_matchers` dependency
- [x] drop `rspec-its` dependency
- [x] fix Deface for Rails 6
- [ ] make Spree Auth Devise work under Rails 6
- [ ] make Spree Gateway work under Rails 6
- [ ] target Rails 6.0.0 in Spree master

Dependencies required to be updated for Rails 6:
- [ ] acts-as-taggable-on https://github.com/mbleigh/acts-as-taggable-on/pull/937
- [X] canonical-rails https://github.com/jumph4x/canonical-rails/pull/52
- [x] paranoia
- [ ] awesome_nested_set
- [x] responders
- [X] [cancancan 3.0](https://github.com/CanCanCommunity/cancancan/wiki/Migrating-from-CanCanCan-2.x-to-3.0) https://github.com/spree/spree/pull/9307
- [X] factory_bot 5.x https://github.com/spree/spree/pull/9362
- [x] rabl https://github.com/nesquena/rabl/pull/723

**Comment by amalrik** [comment]
Paranoia has [this PR](https://github.com/rubysherpas/paranoia/pull/456) but is pending to merge for some months.
Responders is in good shape to rails 6, they already added rails 6 to their ci [PR](https://github.com/plataformatec/responders/pull/202), so I think it could be checked.

**Comment by coorasse** [comment]
Please see my comment here: https://github.com/solidusio/solidus/issues/3053#issuecomment-482542807. I think changing spree permissions is the right way to proceed. 👍 for you guys. but consider that is also a breaking change.
