### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by damianlegawiec** [spree/spree#9176]
With the [3.7 release](https://guides.spreecommerce.org/release_notes/spree_3_7_0.html) we've included the brand new [Storefront API v2](https://spree-guides.now.sh/api/v2/storefront) which is a modern lightweight REST API based on JSON Api spec. We will continue to work on REST API in the form of the [Platform API](https://github.com/spree/spree/issues/8790) but alongside that effort, we would like to include GraphQL support for the Storefront part. 

- [ ] provide a single GraphQL endpoint to expose Storefront resources
- [ ] integrate with CanCanCan authorization
- [ ] include a [GraphQL browser](https://github.com/graphql/graphiql)

**Comment by bezoar17** [comment]
Hi, I am interested in contributing to this issue. 
Can elaborate on the first point, what do you mean by a single GQL endpoint ?

**Comment by SAVE-UP** [comment]
A very good news...

**Comment by aaronsmulktis** [comment]
Beautiful! Let me know what you need and I'll be happy to log some PRs so help move this feature along

**Comment by siriushaha** [comment]
Hi. I am interested in contributing towards GraphQL support using graphql-ruby since I have been using graphql-ruby  on GraphQL backend for RoR 5.1 integrated from React 16.8/Apollo Client2.6/GraphQL. Let me know how to contribute for GraphQL support feature

**Comment by lasersox** [comment]
Is somebody working on this feature? We're looking for a GraphQL based solution for ecommerce.

**Comment by jhirbour** [comment]
The link to https://spree-guides.now.sh/api/v2/storefront  is broken:

**Comment by damianlegawiec** [comment]
> Is somebody working on this feature? We're looking for a GraphQL based solution for ecommerce.

@lasersox we plan to include GraphQL in Spree 4.2 or 4.3



> The link to https://spree-guides.now.sh/api/v2/storefront is broken:
> 
> ```
> Payment required
> 402: PAYMENT_REQUIRED
> Code: DEPLOYMENT_BLOCKED
> ```

This is the proper link: https://guides.spreecommerce.org/api/v2/storefront

**Comment by jhirbour** [comment]
My understanding of GraphQL is that it supports Json-api as a backend. Someone would need to define a graphql schema that matches the schema that the v2 api supports.

**Comment by damianlegawiec** [comment]
> My understanding of GraphQL is that it supports Json-api as a backend. Someone would need to define a graphql schema that matches the schema that the v2 api supports.

GraphQL will be a completely independent thing with JWT authentication. It will be a separate gem in the `spree/spree` repository without `spree_api` as a dependency. It's a clean start :)

**Comment by fastengineer** [comment]
I tried using Spree with Hasura GraphQL engine. It is really working good. Hasura have actions, remote schemas and triggers. So it is really easy to integrate. These are only things i need to implement in spree: 
 
- Authentication && CanCanCan authorization.
- Decoration.

If you are interested, please see how skilled the Hasura GraphQL engine is.

**Comment by lastmaj** [comment]
Hello everyone.
What is the current status of this ? any updates ?

**Comment by poudelprakash** [comment]
Meanwhile until we have official spree graphql release, we have created a extension:https://github.com/TruemarkDev/spree_graphql_base
Feel free to give it a try.

We expect to maintain this gem until graphql features are available natively in the core project.

**Comment by bastianhilton** [comment]
> I tried using Spree with Hasura GraphQL engine. It is really working good. Hasura have actions, remote schemas and triggers. So it is really easy to integrate. These are only things i need to implement in spree:
> 
> * Authentication && CanCanCan authorization.
> * Decoration.
> 
> If you are interested, please see how skilled the Hasura GraphQL engine is.

curious about this setup, how did you link hasura to spree. Was it through remote schemas, if so what url did you use from spree rest api

**Comment by fastengineer** [comment]
> > I tried using Spree with Hasura GraphQL engine. It is really working good. Hasura have actions, remote schemas and triggers. So it is really easy to integrate. These are only things i need to implement in spree:
> > 
> > * Authentication && CanCanCan authorization.
> > * Decoration.
> > 
> > If you are interested, please see how skilled the Hasura GraphQL engine is.
> 
> curious about this setup, how did you link hasura to spree. Was it through remote schemas, if so what url did you use from spree rest api

I connected directly to db, then setup permissions in hasura. Then I mapped some rest apis to remote schemas.
Authentication solved with sharing jwt on spree and hasura. Decoration solved with resp apis but it is not effective.
I think it must offically integrated to hasura, spree maintainer can accept it, because it is the strongest tool of 202X's.

**Comment by damianlegawiec** [comment]
> > > I tried using Spree with Hasura GraphQL engine. It is really working good. Hasura have actions, remote schemas and triggers. So it is really easy to integrate. These are only things i need to implement in spree:
> 
> > > 
> 
> > > * Authentication && CanCanCan authorization.
> 
> > > * Decoration.
> 
> > > 
> 
> > > If you are interested, please see how skilled the Hasura GraphQL engine is.
> 
> > 
> 
> > curious about this setup, how did you link hasura to spree. Was it through remote schemas, if so what url did you use from spree rest api
> 
> 
> 
> I connected directly to db, then setup permissions in hasura. Then I mapped some rest apis to remote schemas.
> 
> Authentication solved with sharing jwt on spree and hasura. Decoration solved with resp apis but it is not effective.
> 
> I think it must offically integrated to hasura, spree maintainer can accept it, because it is the strongest tool of 202X's.

Could you share / open source that code?

**Comment by fastengineer** [comment]
> > > > I tried using Spree with Hasura GraphQL engine. It is really working good. Hasura have actions, remote schemas and triggers. So it is really easy to integrate. These are only things i need to implement in spree:
> > 
> > 
> > > >
> > 
> > 
> > > > * Authentication && CanCanCan authorization.
> > 
> > 
> > > > * Decoration.
> > 
> > 
> > > >
> > 
> > 
> > > > If you are interested, please see how skilled the Hasura GraphQL engine is.
> > 
> > 
> > > 
> > 
> > 
> > > curious about this setup, how did you link hasura to spree. Was it through remote schemas, if so what url did you use from spree rest api
> > 
> > 
> > I connected directly to db, then setup permissions in hasura. Then I mapped some rest apis to remote schemas.
> > Authentication solved with sharing jwt on spree and hasura. Decoration solved with resp apis but it is not effective.
> > I think it must offically integrated to hasura, spree maintainer can accept it, because it is the strongest tool of 202X's.
> 
> Could you share / open source that code?

There is no code, all are configuration on hasura-ui and saved to db. To get all configurations as code, I need to find them and convert to a database migration or sql query.

**Comment by woohoou** [comment]
it could be consider it use remote schema permissions in hasura

**Comment by damianlegawiec** [comment]
We're solely focusing on REST, we don't get any requests for GraphQL anymore
