### ISSUE TITLE
Failed to load api_tokens upgrading from 3.6.6 to 3.7rc1

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9179]
Upgrading to 3.7 Release Candidate 1 from an existing 3.6.6 project I noticed while browsing the site logged in as an existing user I get an error: 

**Failed to load resource: the server responded with a status of 500 (Internal Server Error) -> localhost:3000/api_tokens**

## Context
I don't know if this is a real issue or something specific to my project, but as 3.7 is a release candidate I thought it might be worth noting.

[Action Controller: Exception caught.pdf](https://github.com/spree/spree/files/2750199/Action.Controller.Exception.caught.pdf)

**Comment by damianlegawiec** [comment]
hey @MatthewKennedy you need to install and run migrations, as detailed here:

https://github.com/spree/spree/blob/master/guides/content/developer/upgrades/three-dot-six-to-three-dot-seven.md#install-missing-migrations

**Comment by MatthewKennedy** [comment]
Hi @damianlegawiec I ran the three commands to copy across the new migrations, and ran the migrations during the upgrade process.

3 new migrations came from running ```rails spree:install:migrations```
But no other new migrations came across from running the other 2 commands.

I will check my gemlock file shortly and check that the project is using spree_auth 3.4 as described.

**Comment by damianlegawiec** [comment]
@MatthewKennedy migration that you're missing is this one:

https://github.com/spree/spree/blob/master/api/db/migrate/20180320110726_create_doorkeeper_tables.rb

**Comment by MatthewKennedy** [comment]
@damianlegawiec I have just checked, and for some reason that migration never copied across with the others.

I just tried bundle update using the spree master and then running the ```rails spree:install:migrations``` and again that one migration did not copy across.

**Comment by MatthewKennedy** [comment]
@damianlegawiec Was the aforementioned missing migration specific to the 3.7 upgrade, or was this something I had missed form say an upgrade from 3.4 to 3.5 or 3.5 to 3.6.

I have manually inserted it for now and run the migration and no longer are there any Failed to load resource messages.

**Comment by damianlegawiec** [comment]
@MatthewKennedy it's 3.7-specific. We need to check it again - but maybe it's caused that its part of the `api` gem.

**Comment by damianlegawiec** [comment]
OK - there's a bug in `spree:install:migrations` - it only copies over migrations from `spree_core` omitting those in the `spree_api`, FYI, running:

```
bundle exec rake railties:install:migrations FROM=spree_api
```

fixes this issue

**Comment by MatthewKennedy** [comment]
@damianlegawiec Glad to help. 👍
