### ISSUE TITLE
Second Payments Services EU Directive 

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9186]
New European Union directive replacing the First Payment Services Directive, which regulates payment services in Europe. The new security requirements will impact online businesses accepting card payments. While becoming compulsory in September 2019, payment service providers like card issuers will start implementing come April 2019.
## Context
It looks like there will be more hoops to jump through in 2019 for EU based online store owners to continue accepting card payments online, with the requirement of 3D secure implementation at checkout.
[Click here for more information](https://www.paypal.com/uk/webapps/mpp/psd2)
## Discussion
It may be helpful to have a discussion point about this upcoming issue to help Spree users prepare and adapt for the upcoming changes.

**Comment by damianlegawiec** [comment]
Hey @MatthewKennedy we will prepare a fix for this for the Stripe gateway in https://github.com/spree/spree_gateway
