### ISSUE TITLE
difference spree 2.2 vs 3.7 ?

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#9230]
hi there

a client is running 2.2 and asked if he can upgrade. i asked him what would be the benefit and he said _more features_ but he couldn't name me one that he wanted/needed. 

so i tried to find comparision what was done and the biggest improvement is like the store_credit thing, which he doesn't need.

is there any need to upgrade, hardcore security issues - or is it never change a running system?

**Comment by damianlegawiec** [comment]
To name the least...

- new Admin Panel
- new REST API
- massive improvements in the performance department
- thousands of bug fixes and smaller improvements - check out the release notes: https://spree-guides.now.sh/release_notes/
- current tech stack (2.2 is ancient and uses a lot of outdated gems which can lead to security issues)
