### ISSUE TITLE
Spree - What is the secret key of spree?

### ISSUE THREAD

**Issue by theshashiverma** [spree/spree#9234]
I am working on Ruby on Rails project, and I have already added the devise authentication,

and now I have added the spree in my project by following this [https://github.com/spree/spree](url)

I want to know that is there any secret key for the spree that makes it unique.

For example, if person1 is using my project and he sells mobile phones and person2 is also using my project and he sells clothes, so does the products of both the users will be shown on their websites, I mean person1's products will be shown on person2's shopping website or vice-versa, or is there any unique key that differentiates both's websites.

I have been googling about it for many hours and I found the device's config.secret_key but if I made any changes in the key or remove the key project still works.

Thank you

**Comment by amalrik** [comment]
It seems you need some sort of multi-tenancy.
Spree has support for multi vendor with [this extension](https://github.com/spree-contrib/spree_multi_vendor)

Some information about The secret key 
[here](https://guides.rubyonrails.org/security.html#encrypted-session-storage)
and [here](https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2)

What are you building? A market place?
Hope it helps.

**Comment by theshashiverma** [comment]
Thanks for the reply, I am creating an admin template and i am giving an e-commerce section in the template. Firstly I build the project using ROR then I add auth using Devise and now I have added the e-commerce section using Spree. And for that, I Followed https://github.com/spree/spree
and when I use this command `rails g spree:auth:install` it removes all the config settings of devise.rb that I have made for the devise (i followed this for devise setup https://www.sitepoint.com/devise-authentication-in-depth/) and remains only one line  `Devise.secret_key = " key value "` 
This is what I have done till now.
And suppose if person 1 buys my template and use to sell mobile phones and person 2 who also buy my template and used to sell clothes. SO HOW MY TEMPLATE DIFFERENTIATE BOTH THE BUYERS. Is there would be any specific key for both the buyers if yes how they would generate it

**Comment by krtschmr** [comment]
i don't get your question at all.
your template knows `current_user` which gives either a logged in user or nil (guests).

but i'm quite confused. it seems you want a multi vendor shop and they can activate paid templates? have a look at what shopify does and how their template engine works (with liquid). my guess is, you're better off with a custom solution rather then spree.

**Comment by theshashiverma** [comment]
@krtschmr  Thanks for the reply, let me explain once again, Suppose I have created a shopping theme using ROR and spree. To set up the spree I followed https://github.com/spree/spree. Now I want to sell my theme on the online market suppose ThemeForest ok,

 So if person1 who buy my theme uses it to sell mobiles and there is person2 who also bought my theme to sell clothes. and the theme they are using it has the same `devise.secret_key` in `config/initializers/devise.rb`

Now if they make their websites live, so how the websites of both of them would be different from each other because both have the same secret key.

so would they update their secret key? Or is there any other thing which makes their websites unique with respect to each other?
and if they have same secret keys and their websites are also live so does the product of their websites would merge with each other??

I hope you have heard about `Algolia` like in algolia they provide a unique key to everyone who uses the algolia to create an e-commerce website, which makes there websites unique.

**Comment by krtschmr** [comment]
excuse me, but _lol, wtf?!?!_

first of all, you can't make a theme using RoR and spree. You can make a theme **for spree**. So let's assume you've created _something_ for beeing a nice theme for a spree commerce shop. you have the CSS and the templates ready. 

all you can do is save them.

the secret key is unrelated and has something to do with your local rails project. of course they would update the secret key. for security reasons.

if you sell on themeforest and they buy it but use it somewhere else, that's a license violation and outside of scope regarding RoR or Spree.

whatever algolia does, it's php.

you could propably try to integrate some (illegal?) pinging in case somebody is using your template and you might be able to see if they have a license or not, but i have no idea.

**Comment by MatthewKennedy** [comment]
Can you not just sell them the view files and let them set their own Spree store up and drop in the view files? Do you have to sell them a whole Spree store?

**Comment by theshashiverma** [comment]
@krtschmr   Thanks for the reply, yeah yeah ok, I don't know much about that I'm a newbie. I just wanted to add an extra component in my admin template that's why I did this.
So, I think you are saying that adding spree to an admin template is not a good idea?
and spree commerce is made for only to integrate with fresh RoR project..?
and we should not sell the spree commerce theme on the online market..?

**Comment by theshashiverma** [comment]
@MatthewKennedy  Thanks for the reply, yeah that's not mandatory to give the spree commerce with the admin template.

**Comment by MatthewKennedy** [comment]
You would be best writing a spree extension, that has your custom view files, in, the custom JavaScript and CSS then instructing your potential customer to remove the default views from their Spree project. In app/views/spree

That way your extension view files will take effect.

That would be the simplest way.

**Comment by krtschmr** [comment]
@theshashiverma all i'm saying is: if you give them a spree commerce template, all you give them is 

    app/views
    app/assets

and maybe deface stuff. and literally - that's all they need!

you will **not** give them a spree commerce installation.

lots of projects are adding spree, but they need to do it via the gem and stuff. they can't add your rails project into their project. that's a mess.

**Comment by matissg** [comment]
@theshashiverma  I guess you need to create a gem to some extent. For example [https://rapidrailsthemes.com/](https://rapidrailsthemes.com/) sells themes for Rails projects and as I understand it's done through form of a gem.
