### ISSUE TITLE
Image is uploaded correctly, but not rendered in admin. Old default path shown

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#9247]
i've created a sample store with default seed.

i destroyed all products and taxons

I've created new taxons and products. The storage folder on my disk is empty.

I go to a product and upload an Image.

However, in the admin the following code is generated
`

<a href="http://192.168.0.211:3000/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--909043d70e11333d96a702a64b833544512bf403/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lOTWpRd2VESTBNRDRHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--cd6ff3941291d6c9e0a59757dee1d18dbd4fafde/ror_baseball_jersey_back_green.png"><img src="http://192.168.0.211:3000/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--909043d70e11333d96a702a64b833544512bf403/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lOTVRBd2VERXdNRDRHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--359c73c0d0efeef274d50c0b90be4f1dcf5dad39/ror_baseball_jersey_back_green.png"></a>`

somehow, active storage is returning the old default image stuff?!

server restarted, spring stopped.

no idea what to do

**Comment by krtschmr** [comment]
![image](https://user-images.githubusercontent.com/13366714/52610680-b0665c00-2eb4-11e9-9a30-ae9d90f685c2.png)

**Comment by krtschmr** [comment]
no matter how many stuff i upload, he just generates random stuff for the default images. this is weired.

**Comment by krtschmr** [comment]
even better: 

gave all products an image

```
Spree::Product.find_each do |product|
  file = open("/home/tim/Desktop/argon-dashboard-v1.0.0/assets/img/theme/profile-cover.jpg")
  image = Spree::Image.create!(attachment: { io: file, filename: 'somename' })
  product.images << image
end
 
```
![image](https://user-images.githubusercontent.com/13366714/52610993-02f44800-2eb6-11e9-968d-78175cbea1c1.png)

so i have 3 products who are mad

**Comment by damianlegawiec** [comment]
@krtschmr in ActiveStorage you cannot manually create the same file multiple times - 

https://github.com/rails/rails/issues/32855#issuecomment-412880377
