### ISSUE TITLE
Don't sort @order_events

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#9252]
https://github.com/spree/spree/blob/4cc2c2967352d3fe7652bd873e492c074ffcc3da/backend/app/controllers/spree/admin/orders_controller.rb#L161

we could simply override this and add our own list of actions, however the template will always order it.

https://github.com/spree/spree/blob/4cc2c2967352d3fe7652bd873e492c074ffcc3da/backend/app/helpers/spree/admin/orders_helper.rb#L7

i propose for not sorting the array. we can then control the order of the buttons by simply writing them in the correct order

**Comment by damianlegawiec** [comment]
Hey @krtschmr you're right on this, could you prepare a PR with a fix for this?
