### ISSUE TITLE
Shipping Rate Improvement

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9253]
~~I was looking into offering **Free Shipping** on orders over X amount, but this can only be achieved in Spree via the promotions section.~~
**Price sack does this** Thanks @krtschmr

**Reasons This Is Not Ideal**
~~When selecting shipping method the customer still sees full price until they get to the payment page
Blanket zeroing of rates, I might not want to offer all shipping methods free, I might want to offer free standard shipping but express shipping is still a full price option.
Increases discounts complexity slightly
Possible added tax rate complexity depending how tax is calculated on shipping and then removed via a promo discount.~~
**Most of the above is invalid**

### Still Useful Feature Suggestion
Add to the shipping rates section some rules that determining the shipping method availability at checkout based on the combined weight of products in cart

**Reason**
Shipping companies usually offer weight based pricing, Especially on international orders as prices adjust by the kilo and also if you run a trade on bulk orders, depending on your products you may want to offer a pallet service in certain scenarios.

Or

Additionally, a rule based on cart value, this would be great allowing admins show specific shipping options to the customer in certain scenarios:

**Reason**
High value carts you might not want to show basic none tracked/uninsured shipping options.

**Comment by MatthewKennedy** [comment]
I'm sure there will be an extension out there that would allow this as a feature, but it seems like it makes so much sense to allow shipping rates based on cart weight or value that in my opinion it would be nice as a standard feature.

**Comment by damianlegawiec** [comment]
This makes perfect sense , the free shipping promotion was always a hassle to setup properly and it's far from ideal.

**Comment by krtschmr** [comment]
> I was looking into offering **Free Shipping** on orders over X amount, but this can only be achieved in Spree **via the promotions section**.


*what???*

this is entirely not true. you simply choose a price sack, make it a minimum and that's it. works for us since 2013 and is still working

**Comment by MatthewKennedy** [comment]
@krtschmr Thanks for pointing out the Price Sack, how did I miss that, I’ve never heard the term Price Sack, I should of explorerd it more.

It is better than my suggestion of using rules for offering shipping methods used for free/discounted, but also it would be useful to be able to offer or not offer shipping rates based on cart value or weight.

For example if you had a cart with a high value you might only want to offer tracked or insured rates.

**Comment by krtschmr** [comment]
@MatthewKennedy  yeah, the term price sack is just ridiculous. i also had issues with finding it, years ago.

i think the best improvement for shipping methods would be to have `Order#available_shipping_methods` implemented. Similar to how we do it with payment_methods (https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L744).

i've created once a pull request that certain payment methods are only available if either a minimum or maxmimum amount is reached. same could then be one with shippings. A 10,000$ order will only go with  DHL EXpress while a 5$ order can also go for free shipping.
