### ISSUE TITLE
Destroy an Order won't delete the associated Addresses

### ISSUE THREAD

**Issue by krtschmr** [spree/spree#9256]
Spree::Order.destroy_all
    
now we still have all addresses.

why tho?

**Comment by damianlegawiec** [comment]
@krtschmr you mean addresses associated with those orders or addresses in general?

**Comment by krtschmr** [comment]
the address is staying since the order belongs to address and the address doesn't belong to order.

i wonder (i've never seen), can we use the same address for different orders? then it indeed makes sense.
so far, for our usecase, it sounds more like a bug.

**Comment by damianlegawiec** [comment]
After placing an Order Addresses are cloned and those clones are being associated with Order.

**Comment by krtschmr** [comment]
and if i call `order.destroy` the addresses are still there. no `dependent: :destroy` to find
