### ISSUE TITLE
Issue with the Spree docker build process

### ISSUE THREAD

**Issue by emiquelito** [spree/spree#9264]
The Docker build for Spree is currently failing due to an issue either in the Docker file itself within a script used by the Rake file.

This was working fine about a month ago and appears to have started to break after the stable docker image was updated 23 days ago:

https://hub.docker.com/r/spreecommerce/spree

This is the output of the build error from a local build:

```
 ---> Running in fb7906a1d666
rake aborted!
Errno::ENOENT: No such file or directory - lib/sandbox.sh
/spree/Rakefile:96:in `exec'
/spree/Rakefile:96:in `block (2 levels) in <top (required)>'
/spree/Rakefile:95:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => sandbox
(See full trace by running task with --trace)
```

And a full Squash log is here in case it helps:

[20190221194645-87e6d64789514f97bf363ea080731745.txt](https://github.com/spree/spree/files/2890938/20190221194645-87e6d64789514f97bf363ea080731745.txt)

## Context

Anyone trying to run Spree on Docker will encounter this issue.

## Expected Behavior

The docker build process needs to finish successfully.

## Actual Behavior

Build ends with an error.

## Possible Fix

culprit seems to be coming from this line:

https://github.com/spree/spree/blob/43197ee4079de59e6b245f7dfc2a7e5bb913654b/lib/sandbox.sh#L65

## Steps to Reproduce

You can reproduce this on a Squash deployment like this one:

https://fix9257-api-v1-checkout-flaky-m75mz.squash.io/

**Comment by grugcrood82** [comment]
I was testing this on WSL2 and ran into these errors too; Turns out the file exists bit got banged up by windows. Git is configured to checkout with windows line endings; The fix for me was to get rid of the windows line endings. 😡
