### ISSUE TITLE
Shipment Adjustments are not recalculated when an order's shipping method is changed.

### ISSUE THREAD

**Issue by mvanio** [spree/spree#9274]
Shipment Adjustments are not recalculated when an order's shipping method is changed. 
Is this a known bug with a fix or workaround?

## Expected Behavior
Shipment Adjustments should be recalculated when an order's shipping method is changed.

## Actual Behavior
Shipment Adjustment retains the previously calculated amount.

## Steps to Reproduce
In admin panel, create an order with at least one item.
Ensure customer address is completed.
Change the shipping method to one with a different cost.
Shipment Adjustment amount should recalculate but it does not.

## Your Environment
rails (5.2.1)
spree (3.6.4)
spree_api (3.6.4)
spree_auth_devise (3.4.1)
spree_backend (3.6.4)
spree_cmd (3.6.4)
spree_core (3.6.4)
spree_extension (0.0.5)
spree_frontend (3.6.4)
spree_gateway (3.3.3)
spree_sample (3.6.4)

**Comment by jkojro** [comment]
Seems to work as expected. Please ensure to click save after changing shipping method.

**Comment by mvanio** [comment]
Thanks. I believe this may be due in part to the Tax Category applied to the shipping method. I ensured the tax category was set to 'Standard Rate' and all seemed fine. Perhaps the tax category should be a required field.
