### ISSUE TITLE
Images blocked by ad blockers

### ISSUE THREAD

**Issue by sofianegargouri** [spree/spree#9281]
Most of the product images are blocked by an adblocker

## Context

I just started my Spree app, styled it added a few products, then images, but those images were instantly blocked by the ad blocker.
I tried to dig in it, and I found the following (best hypothesis I found): the image url generated by Active Storage contains "ad", so I think that's why they block the images.

## Expected Behavior

Images should be crystal clear

## Actual Behavior

Images are blocked by client

## Possible Fix

Maybe find a way to reload the Active Storage URL when there is `ad` in it ?

## Steps to Reproduce

I think that's a random side effect of URL generation

## Your Environment

* Version used: 3.7.1

**Comment by jkojro** [comment]
On Chrome seems to work properly with Ad Block.
