### ISSUE TITLE
Wrong usage of cancancan actions and aliases

### ISSUE THREAD

**Issue by coorasse** [spree/spree#9303]
While testing the `3.0.0.rc1` version of cancancan against major projects I noticed that solidus had problems.
Please see the complete description in my pull request on solidus: https://github.com/solidusio/solidus/pull/3148

I strongly suggest applying the same on Spree. 
If interested, I will take care of opening a PR also here ❤️, but I won't have time in the next few weeks.

I strongly raccomend adjusting the usage of rules to follow cancancan standard. It seems that the current usage was meant for ~1.0 version.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/9307
