### ISSUE TITLE
When using none default currency & logged out items will not add to cart 3.7

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9311]
Using Spree 3.7 with the multiple currency extension, while browsing the store in a **none default currency**, and **not logged in**, items will not add to cart.

``` :3000/api/v2/storefront/cart/add_item:1 Failed to load resource: the server responded with a status of 404 (Not Found) ```

What makes me think this is a bug in Spree, not the multiple currency extension is that if you then create an account as a new customer and then browse the store logged in, plus in a none default currency you can add items to cart as expected.

## Expected Behaviour
Item to add to cart as normal.

## Actual Behaviour
Page locks up, with console log error of:

``` :3000/api/v2/storefront/cart/add_item:1 Failed to load resource: the server responded with a status of 404 (Not Found) ```

## Steps to Reproduce

1. Install fresh copy of spree 3.7
2. Add the multiple currency extension as per the extension instructions
3. Login to the admin settings and add EUR to currency and allow users to change currency
4. Open the localhost:3000 in a new browser, or logout
5. Set store currency to EUR
6. Attempt to add an item to cart.

## Your Environment

*3.7.1

**Comment by damianlegawiec** [comment]
fixed via https://github.com/spree-contrib/spree_multi_currency/pull/88
