### ISSUE TITLE
Issue with Spree 3.0 payment step in Checkout process(No payment found)

### ISSUE THREAD

**Issue by lukabos97** [spree/spree#9364]
I have an issue with payment step in checkout process when want to proceed on the confirm step. When click on Save and continue button I got an error "No payment found".

This is my checkout_flow in order.rb

checkout_flow do
      go_to_state :address
      go_to_state :delivery
      go_to_state :shipping_method
      go_to_state :payment, if: ->(order) { order.payment_required? }
      go_to_state :confirm, if: ->(order) { order.confirmation_required? }
      go_to_state :complete
      remove_transition from: :delivery, to: :confirm
    end

I also checked that payment_required is true. What can be the problem?

**Comment by MatthewKennedy** [comment]
The only way I found to get round this was to remove the confirmation step in Spree config

**Comment by lukabos97** [comment]
What Spree config do you mean? Tried to delete it whole step from order model, but seems it won't work

**Comment by lukabos97** [comment]
> The only way I found to get round this was to remove the confirmation step in Spree config

What Spree config do you mean? Tried to delete whole step from order model, but seems it won't work

**Comment by MatthewKennedy** [comment]
In the config/initialisers/spree.rb set config.always_include_confirm_step = false

**Comment by MatthewKennedy** [comment]
Let me know if that worked.

**Comment by lukabos97** [comment]
Not working. Still No payment found error

**Comment by MatthewKennedy** [comment]
What payment provider are you using?

**Comment by MatthewKennedy** [comment]
Are you using ```gem 'spree_gateway', '~> 3.4'```

**Comment by lukabos97** [comment]
I installed gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable', alongside gem 'spree_braintree_vzero', github: 'spree-contrib/spree_braintree_vzero'. I'll try to change payment provider. and let you now is it working

**Comment by MatthewKennedy** [comment]
Remove the Braintree Vzero gem And it should work fine.

**Comment by lukabos97** [comment]
I deleted Braintree and again get same error msg. It should work only with Spree gateway gem and embedded gateway Bogus if I'm right? but it won't

**Comment by MatthewKennedy** [comment]
Fore sure, If you've got a standard Spree installation then it should work fine, just double check that the available payment methods are set to 'Both' or 'Frontend' in the admin/settings/payment methods?

**Comment by MatthewKennedy** [comment]
The only thing I can suggest is to create a new Spree app with no extensions other than the Payment Gateway and the Auth Devise as per the default Spree setup instructions, and test, if that works, slowly add the extensions you had previously and changes you had made and test along the way until you find exactly what broke the flow.

**Comment by damianlegawiec** [comment]
This isn't related to vanilla Spree so closing for now
