### ISSUE TITLE
APIv2 /taxons have position field always equal 0

### ISSUE THREAD

**Issue by tniezg** [spree/spree#9373]
`position` field of type `taxon` is always equal `0`. It doesn't represent the actual position of the taxonomy and taxon in relation to other taxonomies and taxons.

## Context
Taxonomies can be rearranged in the Spree admin panel by drag & drop operations. Doing so is permanent. However, this change is not reflected in the `taxon` type returned by calling the `/taxons` APIv2 endpoint. The alternative to using `position` is to use `left` and `right` attributes. These do return the correct values but are more complicated to use.

A fix to `position` will simplify the creation of menus which respect the order of taxonomies and taxons.

## Expected Behavior
`position` of taxonomies and taxons represents the actual position set in the admin panel, in relation to other taxonomies and taxons at the same `depth` (another attribute returned by APIv2).

## Actual Behavior
`position` is always `0`.

## Possible Fix

\ -

## Steps to Reproduce
1. Go to admin panel, `/taxonomies`.
2. Rearrange taxonomies.
3. Call `/taxons` APIv2 endpoint and check the values of `data[].attributes.position`.

## Your Environment
Stock spree from master branch.

**Comment by haukurhrafn** [comment]
I ran into this issue as well today. The position is always 0. Example:
http://sandkassi4.herokuapp.com/api/v2/storefront/taxons

**Comment by sebbean** [comment]
@damianlegawiec still an issue? could look into a fix (notice you have been on many recent PRs so figured i'd tag you)

**Comment by sebbean** [comment]
@tniezg https://github.com/spree/spree/blob/a66bcab45aab93444df713c5bc7ee969b8664b76/core/app/models/spree/taxon.rb#L97-L105

**Comment by tniezg** [comment]
Hi @sebbean 👋 ,
`position` in taxons is always `0` when tested with latest Spree. Based on the code you linked to I conclude `position` is not updated by stock Spree. I think that's fine. `left` and `right` values are updated and can be used to order elements. It's just slightly misleading to receive three values, `position`, `left` and `right`.
