### ISSUE TITLE
LocalHost Redirection Issues With Https

### ISSUE THREAD

**Issue by devdkumar** [spree/spree#9389]
### LocalHost Redirection Issues With Https

we are using Production `mode`
Spree Version 3.6.1
When We use http ,whole Project Works fine

But When We hit url with https For Some Action it Will redirect to localhost:3000

for eg.when we hit "abc" action with url "dummy "

for http- it will redirects Correct Url   " / dummy/abc/"

But With https
it will redirects us to localhost:3000/abc

we try our best to solve this issue but  all our effort goes in vain

**Comment by nvh0412** [comment]
@devdkumar It should be configured in WebServer layer (i.e Nginx), Spree, Rails, Puma aren't suitable place to handle this issue then

cc @damianlegawiec would it be possible for you to close this issue?
