### ISSUE TITLE
Undefined variable: "$navbar-height".

### ISSUE THREAD

**Issue by vinaymehta** [spree/spree#9395]
I am new to spree and trying to integrate it into my existing application.
My Gemfile looks like below

> ruby '2.4.1'
> gem 'rails', '~> 5.1.4'
> gem 'toastr-rails'
> gem 'rails_admin'
> gem 'devise'
> gem 'spree'
> gem 'spree_multi_domain', github: 'spree-contrib/spree-multi-domain', branch: 'tracker-fix-3-5'

Now after I ran cmds like
`rails g spree:install --migrate=false --sample=false --seed=false --copy_views=true --user_class=User`
`rails g spree_multi_domain:install`

```
After that I restarted my application and it continuosly getting error as 
Sass::SyntaxError - ActionView::Template::Error (Undefined variable: "$navbar-height".):
```

I tried many ways but nothing working. Can anyone suggest me the solution for the same?
Thanks in advance

**Comment by MatthewKennedy** [comment]
First I would suggest using Spree 3.7:

```
gem 'spree', '~> 3.7.0'

```
Rather than the branch master, using 3.7 may simply fix the issue as the master is constantly in development and never guaranteed to be stable for production. 

If that does not fix the issue, it looks to me like an SCSS variable that is undefined. Depending your existing application and what you are using for SCSS files, you may want to create a variables.scss file and import that at the top of the all.css manifest file found in the vendor folder. And in your variables.scss file you then want to define ```$navbar-height: 50px;```

Chances are that once you define that, you will then get the next undefined SCSS variable in the list that is undefined, so it is wise to find out what SCSS file is requesting these variables.

**Comment by khushbugoyal** [comment]
Thanks for your response.
I tried to use Spree 3.7 as well but no luck.
Also already tried some ways to add variables.scss file. Though in my application I am using .css file formats.
Here I want to have multiple stores in my application and so want to have my default page as usual and only at particular page, want to import Spree page for a particular store.
This is how I am using .css files in my application

```
 *= require_self
 *= require toastr
 *= require bootstrap
 *= require main
```
I event tried to add 
```
*= require spree/frontend/all
*= require spree/backend/all
```

But nothing is working. All time same error

> Undefined variable: "$navbar-height".
Please help me out here.

**Comment by vinaymehta** [comment]
Thanks for your response.
I tried to use Spree 3.7 as well but no luck.
Though in my application I am using .css file formats, I also tried some ways to add variables.scss file.
Here I want to have multiple stores in my application and so want to have my default page as usual and only at particular page, want to import Spree page for a particular store.
This is how I am using .css files in my application

```
 *= require_self
 *= require toastr
 *= require bootstrap
 *= require main
```
I even tried to add 
```
*= require spree/frontend/all
*= require spree/backend/all
```

But nothing is working. All time getting same error

> Undefined variable: "$navbar-height".
Please help me out here.

**Comment by MatthewKennedy** [comment]
Remove ``` *= require bootstrap```, save and restart the server, that will probably fix it as: ```$navbar-height``` is a bootstrap SCSS variable.

**Comment by vinaymehta** [comment]
I did same but another undefined variable error
`Undefined variable: "$line-height-computed".`

This is how my application.css file look like
`*= require_self
 *= require toastr
 *= require spree/frontend/all
 *= require spree/backend/all
`

Can it be spree/ruby version issue?

**Comment by MatthewKennedy** [comment]
You will probably want to take the spree/backend/all out too assuming this is  your front end css file.

**Comment by vinaymehta** [comment]
I did same but this also get the new undefined variable error 
`Undefined variable: "$line-height-computed".`

**Comment by causztic** [comment]
FWIW I just replicated your steps to create a new spree application and I did not encounter that error. Check your vendored css for any rule that is using it because `$line-height-computed` is most definitely a Bootstrap variable.
