### ISSUE TITLE
Blank flash while deleting country for which there are addresses attached

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [spree/spree#9416]
When you try to delete a country for which an address is already referencing, it show blank error flash so we don't get any idea what went wrong.

## Expected Behavior
It should display flash proper error message.

## Actual Behavior
![Screenshot from 2019-06-04 12-09-28](https://user-images.githubusercontent.com/1289894/58857728-8b942f80-86c3-11e9-9c6c-22a142e021bc.png)

## Steps to Reproduce
1. Create an Order
2. Delete the Country for which the Order will be shipped 

## Environment
* Spree Version: 3.7
* Rails Version: 5.2.3

**Comment by maikis** [comment]
Is anyone working on this? I am interested in fixing it.

**Comment by damianlegawiec** [comment]
Hey @maikis feel free to submit a PR - thanks!

**Comment by maikis** [comment]
Good. I'll be on it!
