### ISSUE TITLE
I cant delete a item from the cart

### ISSUE THREAD

**Issue by CharlyJazz** [spree/spree#9442]
## Context
This line of code no work:

``` ruby
<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-minus-sign'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
```

## Expected Behavior
Delete the cart item

## Actual Behavior
No Delete the cart item

## Possible Fix
I dont know, but in the controller of order there are a method to remove a item from the cart

## Steps to Reproduce

1. Click in the button
2. Nothing happen
3.
4.

## Your Environment

* Version used: gem 'spree', '~> 3.7.3'
* Gemfile and Gemfile.lock as text in a [Gist](https://gist.github.com/CharlyJazz/5976c31adaddaad953f3e00c6df777ae): 
* Any relevant stack traces ("Full trace" preferred):

**Comment by PSzyszkaSpark** [comment]
Hi @CharlyJazz
I've copied your Gemfile and created a new spree project and in my case this button works perfectly. Could you add more specific steps to reproduce this scenario and type the name of browser you're using?

**Comment by CharlyJazz** [comment]
Is it possible that I delete some JS script that is necessary for the removal of an item from the cart?

**Comment by PSzyszkaSpark** [comment]
It it possible that you could overwritten the js file that is responsible for this. Maybe you could start again with spree/project setup by running commands that are described here:
https://guides.spreecommerce.org/developer/tutorials/getting_started_tutorial.html

**Comment by CharlyJazz** [comment]
Create a new project from 0 and if the delete button works. I have no idea what my problem is. Verify all the files and I have all the important elements.
