### ISSUE TITLE
Storefront API Cart permissions problems

### ISSUE THREAD

**Issue by CharlyJazz** [spree/spree#9445]
<! --- Provide a general summary of the issue in the Title above ->

## Context
I am using the Storefront API and I am not a logged in user.

First I try to add a product to the cart using

```
Request URL: http://localhost:3000/api/v2/storefront/cart/add_item
Request Method: POST
```

I get ** 404 **:

``` JSON
    {"error": "The resource you were looking for could not be found."}
```

I don't have orderToken and / or authToken in that scenario.

I go to the documentation to know how to create an orderToken and I don't find information. Except for this phrase:

``` You can obtain it from the `/ cart` endpoint - it's part of the response (value of the` token` field). ```

So, I run this endpoint to get that token

```
Request URL: http://localhost:3000/api/v2/storefront/cart
Request Method: GET
```

But I also get ** 404 **

``` JSON
    {"error": "The resource you were looking for could not be found."}
```

So I have no idea how to add an item to the cart if I am not a user logged in with authToken and orderToken.

Now I am going to register a user and log in and try this process again. (It may be strictly necessary to be logged in to add products to the cart with the Storefront API)

Now this request:

```
Request URL: http: // localhost: 3000 / api_tokens
Request Method: GET
```

Get:

``` JSON
{
    "oauth_token": "bL1xEUgM2sMnYYzUQuRRtZjrmxNU1MvEJR_sNq7ctts",
    "order_token": null
}
```

And again I try to add a product to the cart with the Storefront API

```
Request URL: http: // localhost: 3000 / api / v2 / storefront / cart / add_item
Request Method: POST
Authorization: Bearer bL1xEUgM2sMnYYzUQuRRtZjrmxNU1MvEJR_sNq7ctts
```

I get ** 404 **:

``` JSON
{"error": "The resource you were looking for could not be found."}
```

And then, I think I need the orderToken. And I'm going to do GET / cart as the documentation says to get it:

```
Request URL: 'http: // localhost: 3000 / api / v2 / storefront / cart'
Request Method: GET
Authorization: Bearer bL1xEUgM2sMnYYzUQuRRtZjrmxNU1MvEJR_sNq7ctts
```

I get ** 404 **:

``` JSON
{"error": "The resource you were looking for could not be found."}
```

## Expected Behavior
Add products to a cart without problems

## Actual Behavior
I cant add products to a cart without a orderToken created before

## Possible Fix
I dont know

## Steps to Reproduce
Just run the api CALLS

## Your Environment

Version used: gem 'spree', '~> 3.7.3'
Gemfile and Gemfile.lock as text in a [Gist](https://gist.github.com/CharlyJazz/5976c31adaddaad953f3e00c6df777ae):
Any relevant stack traces ("Full trace" preferred):

I am open to make a video call or whatever they need for us to analyze this problem.

**Comment by storhet** [comment]
I'm not sure if it's the same but in my case the problem was a missing `default_currency` from the store object. So, when it tried to find the incomplete order the currency was present as one of the find_by params and ofc it couldn't find it. Solution was to uncomment default_currency input field here `spree/admin/stores/_form.html.erb` and fill it in.
