### ISSUE TITLE
Missing gem spree_cmd 3.7.4

### ISSUE THREAD

**Issue by gongomgra** [spree/spree#9459]
## Context
I'm trying to install Spree 3.7.4 but I'm having issues running bundle install when trying to install the `spree_cmd` gem. According to the `spree.gemspec` file, it will install the same version for all the Spree dependencies but the `spree_cmd` gem version `3.7.4` can't be found. At this moment, rubygems.org shows 3.7.3 as the latest version. Are you planning any release of the `spree_cmd` gem?

https://rubygems.org/gems/spree_cmd/versions

## Expected Behavior
To be able to install Spree 3.7.4

## Actual Behavior
`spree_cmd` 3.7.4 can't be found

**Comment by damianlegawiec** [comment]
@gongomgra fixed, thank you for the notice!

**Comment by gongomgra** [comment]
Works now, thanks!
