### ISSUE TITLE
API V2  EWay - That payment method is unsupported

### ISSUE THREAD

**Issue by JasonKroll** [spree/spree#9464]
## Context

Using the **Storefront API v2** I am trying to add a payment using the **Spree::Gateway::Eway** payment method but I get an payment method is unsupported error.

It works fine through the frontend with the payments showing up in my EWay sandbox.

Seems the same as [issue #8051](https://github.com/spree/spree/issues/8051) which was closed.

As per [docs](https://guides.spreecommerce.org/api/v2/storefront#operation/Update%20Checkout) I add address and shipping method to `PATCH /checkout` and then `PATCH /checkout/next` returns an updated cart state of "payment".

I then add the payment sources as per docs to the `PATCH /checkout` endpoint:

```
{
    "order": {
        "payments_attributes": [
            {
                "payment_method_id": 4
            },
        ]
    },
    "payment_source": {
      "4": {
        "number": "4444333322221111",
        "month": "01",
        "year": "2022",
        "verification_value": "123",
        "name": "John Doe"
      }
    }
}
```
where the payment_method_id: 4 is the Eway method.

Then try to update the checkout with `PATCH /checkout/next`

## Expected Behavior

Respond with updated cart with:
```
{
...
"state": "confirm"
...
}
```
`
Status: 200
`
As mentioned above, it works as expected through the frontend.

## Actual Behavior

I get the following response from the `PATCH /checkout/next` call

`Status:422`
```
{
    "error": "That payment method is unsupported. Please choose another one.",
    "errors": {
        "base": [
            "That payment method is unsupported. Please choose another one."
        ]
    }
}
```

## Possible Fix

N/A

## Steps to Reproduce

1. Create a new Spree project
2. Add Spree::Gateway::Eway payment method
3. Follow as per above

## Your Environment

* Version used: Spree 3.7.4, Rails 5.2.3
[Gemfile](https://gist.github.com/JasonKroll/6b63bb91f4814853bebdca48c8bcc1cd)
[Gemfile.lock](https://gist.github.com/JasonKroll/aa6a5b574864183bcb7a30698367812e)

**Comment by nvh0412** [comment]
@JasonKroll There was a problem with your body for `payment_source` then. `cc_type` should be included but it didn't

```
"payment_source": {
      "4": {
        "number": "4444333322221111",
        "month": "01",
        "year": "2022",
        "verification_value": "123",
        "name": "John Doe"
      }
    }
}
```

The value of `cc_type` actually is the brand of payment source (Credit card in this case) like 'visa', you can check more details in here https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/eway.rb#L12

So back to your body request, it should be

```
{
    "order": {
        "payments_attributes": [
            {
                "payment_method_id": 4
            },
        ]
    },
    "payment_source": {
      "4": {
        "number": "4444333322221111",
        "month": "01",
        "year": "2022",
        "verification_value": "123",
        "name": "John Doe",
        "cc_type": "visa"
      }
    }
}
```

The error message is really confused there, I'm considering to enhance it a bit, meanwhile you can fix this issue by passing `cc_type`, I think

**Comment by JasonKroll** [comment]
Thanks for the replay @nvh0412 

I tried adding the `cc_type` as suggested and now I get the following response:
`Status: 422`
```
{
    "error": "Invalid Card Number",
    "errors": {
        "base": [
            "Invalid Card Number"
        ]
    }
}
```

I initially thought this working on the frontend but now I am getting the same invalid card number message so I am not sure what I have done there.

I haven't had a chance to dig much deeper but my first thought is that the problems come from the fact that EWay and EWay rapid payment methods don't support payment profiles as mentioned [here in the docs](https://guides.spreecommerce.org/developer/customization/checkout.html#payment-profiles).

**Comment by nvh0412** [comment]
Hey @JasonKroll,

To be clear, the first error of this issue is Spree returned `Unsupported payment method`, so here is the root cause

https://github.com/spree/spree/blob/17ae2629be2e4cc9980d5bd2ecd429ee79e72436/core/app/models/spree/gateway.rb#L49-L53

Your `provider_class` is ActiveMerchant::Billing::EwayGateway. You can take a look at it via this link https://github.com/activemerchant/active_merchant/blob/8db319a6757011f3924369cc5fc93a90c3fb08e7/lib/active_merchant/billing/gateways/eway.rb

So after we pass cc_type (alias `brand`), the request has been passed `support?` validation and you didn't receive `That payment method is unsupported. Please choose another one` anymore. Then you got the new error, based on ActiveMerchant gem,[ this error was responded from EWay server](https://github.com/activemerchant/active_merchant/blob/8db319a6757011f3924369cc5fc93a90c3fb08e7/lib/active_merchant/billing/gateways/eway.rb#L177). Please consider check your environment (testing, staging) and check your card number is valid or not. 

Btw, `payment profiles` is used for refunding or void transaction. Your case is purchase, so don't care about payment profile here.

**Comment by JasonKroll** [comment]
Hi @nvh0412 

Yes I can confirm that including the cc_type in the request we no longer get the `That payment method is unsupported. Please choose another one` error.

I have started a fresh project and done nothing to the config except add the eway gateway and I get a successful purchase from the front end using the card number 4444333322221111 and it shows up in my EWay sandbox.

Using the same number through the V2 api I get the `Invalid Card Number` error from the server.

It's possible I am not understanding a process somewhere and I understand that the initial issue is resolved and am happy to leave it there and reopen this elsewhere if needed.

**Comment by nvh0412** [comment]
@JasonKroll since the number issue of Spree is huge atm, would it be possible for you to close this issue? if we get some struggle with this again, feel free reopen it, I'm willing to investigate with you.

**Comment by JasonKroll** [comment]
Hi @nvh0412 
Sure no problem. Thanks for your help.

**Comment by bhtabor** [comment]
For anyone running to such an issue, instead of a string "4", payment source object key should be a number - Spre API V2 JS SDK Readme: https://github.com/spree/spree-storefront-api-v2-js-sdk#orderUpdate. 
```
 "payment_source": {
      4: {
        "number": "4444333322221111",
        "month": "01",
        "year": "2022",
        "verification_value": "123",
        "name": "John Doe"
      }
    }
```
