### ISSUE TITLE
Error: Could not find generator 'spree:install'.

### ISSUE THREAD

**Issue by emerchan** [spree/spree#9476]
## Context
I am trying to install Spree on Windows server 2019 but when I tried to executed:
bundle exec rails g spree:install --user_class=Spree::User
or
rails g spree:install --user_class=Spree::User

I am having the following message:

Could not find generator 'spree:install'.
Run `rails generate --help` for more options.

## Environment
* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

Rails: 6.0.0
Ruby: 2.6.3p62
Spree: 3.7
gem: 3.0.6
sqlite3: 1.4.1

Gemfile.lock
https://gist.github.com/emerchan/739f8c8054d89f2793f4f0d7f34798c5

Gemfile
https://gist.github.com/emerchan/52111989853bbbf4d9071b6d506301ce

**Comment by nvh0412** [comment]
@emerchan sorry but I didn't see spree gems on your Gemfile, would it be possible for you to double check it? Seems like that's the root cause for your issue then

**Comment by Lavender-Zandile** [comment]
I am also facing a similar problem. How did you resolve it?
