### ISSUE TITLE
Spree 4 Beta - Edit Existing Address Issue

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9529]
## Context
When you are at the address stage of checkout and click edit the address so that you go into the Address Book edit mode, and you have the scenario where states are required but none are listed, so that you are presented with the input text field for entering a state, it is not updated when the address is saved.

## Expected Behavior
Edit the address, and the state gets updated

## Actual Behavior
State is as it previously was prior to the edit.

## Your Environment

- Spree 4 Beta
- Rails 6
- Ruby 2.6

<img width="539" alt="Screenshot 2019-09-15 at 17 10 13" src="https://user-images.githubusercontent.com/1240766/64924368-cdad3100-d7db-11e9-9dde-d4940aabf952.png">

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/9537
