### ISSUE TITLE
Checkout Flow Suggestion

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9532]
Just a thought about the checkout flow, now that address book is part of Spree 4, and there seems to be quite a lot of content on the address page, maybe it would be more logical to the visitor to adjust the checkout flow to the following:

**Shipping Address** > **Shipping Method** > **Payment (optional billing address)**  > **Summery or Complete**

1. Enter Shipping Address (This is then set as the billing address as default, no options for billing address are shown at this stage).
2. Select Shipping Method Based on Shipping Address given in Step 1.
3. Select Payment Method and also presented with checkbox option to expand and enter a different billing address if needed.
4. Summary or Complete depending on how you have your Spree store set up. (no change).

**Comment by damianlegawiec** [comment]
Hey @MatthewKennedy 

Yes, you're right on the money, the current checkout flow is old school, your approach fits the modern times much better. Would you mind applying those changes?

**Comment by MatthewKennedy** [comment]
Sure, I can take a look and see if I can improve the checkout flow, I'll create a pull request when ready.
