### ISSUE TITLE
API v2 /taxons does not look for filter params in `filter[]`

### ISSUE THREAD

**Issue by aforty** [spree/spree#9538]
Seems that `core/app/finders/spree/taxons/find.rb` is not digging for the parameters in `filter`. As a result `.../taxons?filter[roots]=true` does not work but `.../taxons?roots=true` does. The documentation advises users to use `filters[roots]` which doesn't work (https://guides.spreecommerce.org/api/v2/storefront/#operation/Taxons%20List). All parameters are affected and the documentation is wrong.

## Expected Behavior
I expect the documentation to match the code and for the code and url parameters to be consistent. I would expect `filter[roots]=true` to return the root taxonomies.

## Actual Behavior
Passing in `filter[roots]=true` does not work as described in the documentation.

## Possible Fix
Use `params.dig(:filter, :roots)` instead of `params[:roots]` @ `core/app/finders/spree/taxons/find.rb:11`.

## Your Environment
* Version used: 3.7

**Comment by damianlegawiec** [comment]
@aforty thank you for reporting this, version 3.7.5 containing a fix this issue is available on RubyGems
