### ISSUE TITLE
Address form is broken when Spree is mounted at a path different than "/"

### ISSUE THREAD

**Issue by qoobaa** [spree/spree#9540]
## Context

The state search is broken when you mount Spree (and the API) at a different path, due to https://github.com/spree/spree/commit/966386c200175473d04d3449718fd985a6910474#diff-ffaffad1bc65f5b9af7952c7952570aaR9

## Expected Behavior

Changing country should fetch associated states.

## Actual Behavior

Server responds with 404.
```
Routing Error

No route matches [GET] "/api/v2/storefront/countries/4"
```

## Possible Fix

Generate a correct url and use it instead of a hardcoded version.

## Steps to Reproduce

1. Mount Spree at "/store"
2. Launch the server
3. Go through the checkout process, select a country and try to select a state

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by damianlegawiec** [comment]
Thanks @qoobaa - we're going to fix this today and release rc3 containing this fix shortly

**Comment by qoobaa** [comment]
@damianlegawiec thank you sir!

It seems there's one more related issue: the state field doesn't select the saved state by default - it's blank even though the address record has a state, it requires manual selection.

**Comment by damianlegawiec** [comment]
@qooba the second issue was fixed yesterday https://github.com/spree/spree/pull/9537 - you can use 

```ruby
gem 'spree', github: 'spree/spree', branch: '4-0-stable'
```

this way you will get fixes and changes before the RubyGems releases

**Comment by qoobaa** [comment]
`4-0-stable` doesn't seem to contain the fix, `master` does.

**Comment by qoobaa** [comment]
Thanks! :heart:

**Comment by damianlegawiec** [comment]
@qoobaa ah, gotcha, fixed :)
