### ISSUE TITLE
Upgrade Spree from 3.6 to 3.7 Fails

### ISSUE THREAD

**Issue by edmondchui** [spree/spree#9545]
When I tried to upgrade Spree from 3.6.6 to 3.7.5, an error about `:verify_authenticity_token` has not been defined stop the generation of database migration files.

## Context

Following the instruction at https://guides.spreecommerce.org/developer/upgrades/three-dot-six-to-three-dot-seven.html, I tried to install the migration after successfully install the gem for Spree 3.7.5

```ruby
rails spree:install:migrations
```

The following error occurred when installing migration:

```ruby
$ rails spree:install:migrations
[Spree WARNING] Missing migrations.
[Spree WARNING] add_deleted_at_to_spree_credit_cards from spree is missing.
[Spree WARNING] add_timestamps_to_spree_prices from spree is missing.
[Spree WARNING] rename_guest_token_to_token_in_orders from spree is missing.
[Spree WARNING] Run `bundle exec rake railties:install:migrations` to get them.

[Spree_api WARNING] Missing migrations.
[Spree_api WARNING] create_doorkeeper_tables from spree_api is missing.
[Spree_api WARNING] Run `bundle exec rake railties:install:migrations` to get them.

rails aborted!
ArgumentError: Before process_action callback :verify_authenticity_token has not been defined
/server/config/environment.rb:5:in `<top (required)>'
bin/rails:8:in `require'
bin/rails:8:in `<main>'
Tasks: TOP => railties:install:migrations => db:load_config => environment
(See full trace by running task with --trace)
```

This is a showstopper.

## Expected Behavior

The database migration generation should success without error.

## Actual Behavior

The above error occurred and stopped the generation of database migration file.

## Possible Fix

After some debugging, I found out the root cause of the error is in frontend/app/controllers/spree/store_controller.rb. The offending line of code is:

```ruby
    skip_before_action :verify_authenticity_token, only: :ensure_cart
```

To fix the issue, I added `, raise: false` at the end of the line.

```ruby
    skip_before_action :verify_authenticity_token, only: :ensure_cart, raise: false
```

## Steps to Reproduce

1. Have a Spree app with version 3.6.6
2. Upgrade to Spree 3.7.5 following the instruction here: https://guides.spreecommerce.org/developer/upgrades/three-dot-six-to-three-dot-seven.html

## Your Environment

* Version used: 3.7.5
* Ruby: 2.5.6
* Rails: 5.2.3
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

```ruby
$ rails spree:install:migrations
[Spree WARNING] Missing migrations.
[Spree WARNING] add_deleted_at_to_spree_credit_cards from spree is missing.
[Spree WARNING] add_timestamps_to_spree_prices from spree is missing.
[Spree WARNING] rename_guest_token_to_token_in_orders from spree is missing.
[Spree WARNING] Run `bundle exec rake railties:install:migrations` to get them.

[Spree_api WARNING] Missing migrations.
[Spree_api WARNING] create_doorkeeper_tables from spree_api is missing.
[Spree_api WARNING] Run `bundle exec rake railties:install:migrations` to get them.

rails aborted!
ArgumentError: Before process_action callback :verify_authenticity_token has not been defined
/server/config/environment.rb:5:in `<top (required)>'
bin/rails:8:in `require'
bin/rails:8:in `<main>'
Tasks: TOP => railties:install:migrations => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by damianlegawiec** [comment]
Hey @edmondchui could you prepare a PR with this fix? Thanks!

**Comment by edmondchui** [comment]
Yup. I just submitted the PR https://github.com/spree/spree/pull/9550

**Comment by damianlegawiec** [comment]
Thank you @edmondchui - merged! Will release a new patch version later today!

**Comment by edmondchui** [comment]
Thanks for the quick turnaround @damianlegawiec. Now I don't need to use my own fork in my environments.
