### ISSUE TITLE
Spree E-commerce for Multiple Vendors

### ISSUE THREAD

**Issue by ancdbcs** [spree/spree#9562]
I need to implement multi vendors features in spree.

Admin can create a vendor account and that vendor will have their own store.

I found a gem for that https://github.com/spree-contrib/spree_multi_vendor but stuck on one issue
https://github.com/spree-contrib/spree_multi_vendor/issues/90

**Comment by damianlegawiec** [comment]
Hey @ancdbcs , this is more of a multi-vendor extension issue, not Spree itself, so closing this issue

**Comment by ancdbcs** [comment]
Could you please help me to get the solution for that.
