### ISSUE TITLE
"Remember me" doesn't save or remember my account

### ISSUE THREAD

**Issue by ninawitek** [spree/spree#9568]
There is no difference between having "Remember me" checkbox checked or unchecked in later site usage.

## Context
Button is visible on Login page 

## Actual Behavior
There is no difference, whether I check or uncheck "Remember me"

## Steps to Reproduce

1. Go on Login page
2. Type your login credentials
3. Check "Remember me" checkbox

![Screen Shot 2019-10-07 at 15 32 40](https://user-images.githubusercontent.com/30228893/66316776-92081180-e918-11e9-9b68-fdcdeb2a517d.png)

**Comment by joeltaylor** [comment]
I'm not able to reproduce this issue on `master`. In Safari/Chrome/Firefox I did the following flow:
- Login without "Remember me"
- Closed browser
- Reopened browser and verified I needed to login again when revisiting
- Logged in with "Remember me"
- Closed browser
- Reopened browser and verified that I was still logged in

Am I missing something?

**Comment by yann120** [comment]
Same I can't reproduce it.
@ninawitek can you tell us on which browser you tried this ?
