### ISSUE TITLE
An error occurred while loading spec_helper(rpsec)

### ISSUE THREAD

**Issue by laoyouzi** [spree/spree#9575]
Running tests in my engine caused file loading problems when I added the file asset_decorator.rb

##### `rspec ./spec/requests/spree/api/v2/custommake/upload_image_spec.rb`

An error occurred while loading spec_helper.
Failure/Error: Rails.configuration.cache_classes ? require(c) : load(c)
 
 NameError:
   expected file /Users/migu/app2/spree_customapp/app/models/spree/asset_decorator.rb to define constant Spree::AssetDecorator, but didn't
  /Users/migu/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.1.10/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded'
  /Users/migu/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:27:in `block in require'
  /Users/migu/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `tap'
  /Users/migu/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
  ./lib/spree_customapp/engine.rb:14:in `block in activate'
  ./lib/spree_customapp/engine.rb:13:in `glob'
  ./lib/spree_customapp/engine.rb:13:in `activate'

##  Environment

* Version used:  rails 6.0, ruby 2.5.1, spree 4.0.0.rc2

**Comment by damianlegawiec** [comment]
https://guides.spreecommerce.org/developer/customization/images.html#active-storage

You need to have the asset decorator in proper format for Zeitwerk autoloader. 

https://github.com/fxn/zeitwerk#file-structure
