### ISSUE TITLE
Login and Signup API

### ISSUE THREAD

**Issue by rhong7** [spree/spree#9577]
**Is your feature request related to a problem? Please describe.**
I've been trying to integrate react with it by having backend as spree and frontend as react. I've tried to figure out on how to I can let users login to the store using Spree API, but I couldn't find any API related to it. 

**Describe the solution you'd like**
It would be great if there's a feature where we can let our user to login/signup in our store using Spree API

**Comment by damianlegawiec** [comment]
@rhong7 so for the login endpoint you can use:

https://guides.spreecommerce.org/api/v2/authentication#operation/Create%20or%20Refresh%20Token

Signup will be added to the https://github.com/spree/spree_auth_devise extension in the future

**Comment by belhassen07** [comment]
@damianlegawiec is it added yet? Is there an endpoint for registration now? ty

**Comment by damianlegawiec** [comment]
Closing this issue, both endpoints were added to Spree Auth Devise and documented here:

* signup -> https://api.spreecommerce.org/docs/api-v2/api/docs/v2/storefront/index.yaml/paths/~1api~1v2~1storefront~1account/post
* login -> https://api.spreecommerce.org/docs/api-v2/api/docs/oauth/index.yml/paths/~1spree_oauth~1token/post
