### ISSUE TITLE
Improvement for search result string

### ISSUE THREAD

**Issue by enderahmetyurt** [spree/spree#9586]
Hi,

After searching a product on spree from search box. We see that screen

<img width="1202" alt="Screen Shot 2019-10-12 at 23 28 50" src="https://user-images.githubusercontent.com/447588/66707379-430f1180-ed48-11e9-8b51-1754eee02625.png">

Instead of `Search results for 'rails'` result string, should we write `We found 7 products related to rails.` ?

What do you think?

Or is there any way do that?

Cheers.

**Comment by CharlyJazz** [comment]
And what happend if the results have pagination, and the total is 1000 results, but each page have 20?

**Comment by enderahmetyurt** [comment]
Yes you're right @CharlyJazz but we can right `1-20 of over 1000 results for "rails"` and for the second page we can update the string to ``21-41 of over 1000 results for "rails"` what do you think?

**Comment by CharlyJazz** [comment]
Cool. Maybe we can cache the COUNT statement "1000" to avoid re-query that in each search

**Comment by enderahmetyurt** [comment]
it has been here for many years :) Let's close it.
