### ISSUE TITLE
Locale isn't set for cart link

### ISSUE THREAD

**Issue by Kulgar** [spree/spree#9590]
I'm using spree i18n and spree globalize. 
The link_to_cart helper isn't sending back a cart url with the current locale in it. 

## Context
I found that the AJAX call to get the cart_link is using Spree.pathFor... And that method doesn't seem to include the locale either. 

I normally followed official guide to set i18n. 

## Expected Behavior
When I'm on a page, like domain.com/fr, the cart link should be: domain.com/fr/cart, but it actually is: domain.com/cart 

I have the same problem when I add a product to my cart, it redirects me to the English cart page (without my locale in URL).

I'm wondering if I missed something? 

## Steps to Reproduce
1. Set up spree, spree_frontend and spree i18n
2. Set up 2 languages
3. Access none default language and try to click on the cart button

## Your Environment
* Version used: Spree 3.7.4
* spree_i18n 3.3.2

Thanks in advance for any help! :-)

**Comment by deepakmahakale** [comment]
Any solution so far?
I am facing the same issue

**Comment by Kulgar** [comment]
@deepakmahakale : I followed official documentation to override the "pathFor" method to add locale in generated paths. 

I just created the file in vendor/assets/javascripts/spree/frontend/spree_decorator.js, and put following code in it:

```
Spree.pathFor = function (path) {
  var locationOrigin = (window.location.protocol + '//' + window.location.hostname) + (window.location.port ? ':' + window.location.port : '')
  return this.url('' + locationOrigin + (this.mountedAt()) + Spree.locale + "/" + path, this.url_params).toString()
}
```

This solved my problem - and this should be the default "pathFor" function to solve the above bug.

**Comment by damianlegawiec** [comment]
Locale / currency settings has gone through a total makeover in Spree 4.2 so this issue is outdated now. Locale is set on the Store level
