### ISSUE TITLE
Create Token not working

### ISSUE THREAD

**Issue by gurmindersingh4260** [spree/spree#9605]
Create or Refresh Token
## Context

I am looking forward to use spree v2 APIs. For authentication i have been facing 1 error. 

## Actual Behavior

Getting the following error.
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}

And also, there is no option available to create oauth_application in the routes.

**Comment by damianlegawiec** [comment]
@gurmindersingh4260 please send the entire request body in a curl format, also please attach what spree version are you using

**Comment by gurmindersingh4260** [comment]
Spree Version : 4
Request Url: http://localhost:3000/spree_oauth/token

**Comment by damianlegawiec** [comment]
<img width="754" alt="Screenshot 2019-10-23 at 10 40 21 PM" src="https://user-images.githubusercontent.com/55154/67448952-93a72a00-f5e6-11e9-98dd-a522088e3285.png">

try setting params as shown in the screenshot.

**Comment by gurmindersingh4260** [comment]
@damianlegawiec I am using the same params as shown in screenshot and getting the same error.

**Comment by Rajan4436** [comment]
I am facing the same error after setting all parameters. same
