### ISSUE TITLE
It's not possible to change position of VARIANT, IMAGES and PROPERTIES on the list in Admin panel

### ISSUE THREAD

**Issue by ppietrasinski** [spree/spree#9614]
It's not possible to change the position of the element on the list in the Admin panel. While trying to do this, 422 error will occur in Devtools/Network

## Steps to Reproduce

1. Login as Admin and go to admin panel
2. Move to Products -> Specific product -> Variants/Images/Properties
3. Try to move any element of the list
4. refresh the page
5. Observe issue

## Your Environment

* Version used: 4.0

**Comment by MatthewKennedy** [comment]
This issue is fixed in PR #9611
