### ISSUE TITLE
Invalid_grant issue comes up randomly while creating token.

### ISSUE THREAD

**Issue by Rajan4436** [spree/spree#9628]
## Context
I have tried almost all possible solutions provided in this thread https://github.com/spree/spree/issues/9605 but its not working . Still getting invalid_grant while creating token from postman as well as from app. From postman it never works. from app it works sometimes and sometimes not.   

This is the setup i gave. 
![Screenshot from 2019-11-12 12-17-45](https://user-images.githubusercontent.com/10785334/68648693-0866e780-0547-11ea-9bde-ddb7ec0eb7a5.png)

## Expected Behavior
Should return token as per documentation

**Comment by damianlegawiec** [comment]
@Rajan4436 you're posting the payload as form, it should be posted as JSON body
