### ISSUE TITLE
spree3.6: rails 5.2.4.rc1 `awesome_nested_set` gem error

### ISSUE THREAD

**Issue by hoshinotsuyoshi** [spree/spree#9644]
Updating the spree3.6 app to rails 5.2.4.rc1 will cause an error in the `awesome_nested_set` gem.

#### Background

* There was a compatibility issue between rails6.0 and `awesome_nested_set`.
    * Issue: https://github.com/collectiveidea/awesome_nested_set/pull/407 .
        * Related commit: https://github.com/rails/rails/commit/cb0299c9eba6463085130debda6347abf9683463 .
    * This was solved in awesome_nested_set `3.2.0`.
        * PR: https://github.com/collectiveidea/awesome_nested_set/pull/408 .
        * CHANGELOG: https://github.com/collectiveidea/awesome_nested_set/blob/v3.2.0/CHANGELOG#L1-L4

And now, `rails 5.2.4.rc1`, released [today](https://weblog.rubyonrails.org/2019/11/23/Rails-5-2-4-rc1-has-been-released/) , contains https://github.com/rails/rails/commit/cb0299c9eba6463085130debda6347abf9683463 .

This causes the same issue as https://github.com/collectiveidea/awesome_nested_set/pull/407.

And the branch `3-6-stable` sets dependency [`'awesome_nested_set', '~> 3.1.3'`](https://github.com/spree/spree/blob/v3.6.6/core/spree_core.gemspec#L25), so user-side `bundle update` cannot solves this problem.

## Expected Behavior

No error occurs.

## Actual Behavior

An error occurs.

## Possible Fix

Backport https://github.com/spree/spree/commit/71a1519c92222a8a10913e00543be66ef6814334 to `3-6-stable` and `3-7-stable`

## Steps to Reproduce

1. Update `Gemfile`, to rails `5.2.4.rc1` from `rails 5.2.3` .
2. Do `rails c` and call `Spree::Taxon#children`.

```
[9] pry(main)> root_taxon = Spree::Taxonomy.first!.root
  Spree::Taxonomy Load (0.6ms)  SELECT  `spree_taxonomies`.* FROM `spree_taxonomies` ORDER BY spree_taxonomies.position, spree_taxonomies.created_at LIMIT 1
  Spree::Taxon Load (3.1ms)  SELECT  `spree_taxons`.* FROM `spree_taxons` WHERE `spree_taxons`.`taxonomy_id` = 3 AND `spree_taxons`.`parent_id` IS NULL LIMIT 1
=> #<Spree::Taxon:0x00007ff93823bca0
(...snip...)

[10] pry(main)> root_taxon.children
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/hoshino/go/src/github.com/masked/masked/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.rc1/lib/active_record/relation/query_methods.rb:1178:in `order_column'
```

## Your Environment

* ruby -v -> ruby `2.3.6p384`
* spree `3.6.6`
* rails `5.2.4.rc1`
* awesome_nested_set `3.1.4`

**Comment by damianlegawiec** [comment]
@hoshinotsuyoshi v3.7.9 fixes this issue, thank you for pointing this up!
