### ISSUE TITLE
Fix Ruby 2.7 compatibility

### ISSUE THREAD

**Issue by qoobaa** [spree/spree#9743]
Ruby 2.7 is out. It doesn't change much, but it brings on some new, cool features. Spree seems to work fine on it, except occasional `FrozenError (can't modify frozen String)` in a few places. It shouldn't be difficult to fix in my opinion.

**Comment by ArturT** [comment]
There is a bug `ret: 2, hash modified during iteration` in Ruby 2.7 that happens randomly for Rails: https://bugs.ruby-lang.org/issues/16503
Good to know before switching to new Ruby :)
