### ISSUE TITLE
Updating 3.7.x to 4.0 Single Table Inheritance Issue With Existing Promotions

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9810]
## Context
I attempted to update a spree store that began on 3.4.0 updated version by version up to 3.7.10, but when migrating to Spree 4.0 I get an error when attempting to delete or edit an existing promotion that was created on previous versions of Spree.

`The single-table inheritance mechanism failed to locate the subclass: 'Spree::Promotion::Rules::Store'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Spree::PromotionRule.inheritance_column to use another column for that information.`

## Steps to Reproduce
1. Create a Spree store on 3.7.x
2. Create some active promotions
3. Follow upgrade guide to Spree 4.0
4. Once on Spree 4.0 attempt to delete or edit the promotions.

If this does not reproduce the problem possibly start with a store version earlier than 3.7, create promotions and then upgrade to Spree 4.0

**Comment by damianlegawiec** [comment]
Hey @MatthewKennedy `Store` rule is defined here https://github.com/spree-contrib/spree-multi-domain/blob/master/app/models/spree/promotion/rules/store.rb - did you remove that gem?

**Comment by MatthewKennedy** [comment]
I did, I was thinking the multiple store functionality was moved into Spree 4.

My fault, I’ll close this issue.
