### ISSUE TITLE
Spree new front end sitemap.xml need to be configured

### ISSUE THREAD

**Issue by NetViz** [spree/spree#9825]
Spree new front end sitemap.xml need to be configured, 

it gives below error now,

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by mradfaber** [comment]
hey @NetViz thanks for your comment!
you are right of course but the sitemap extension isn't in Spree core so you have to add it yourself
to quote the new Spree UX docst (not released yet - that Spree version hasn't been released yet either):

> SEO recommendations
> Sitemap
> We highly recommend adding a sitemap to your site. It might affect how Google bot crawls your store pages. There is an official extension [Spree Sitemap](https://github.com/spree-contrib/spree_sitemap) for that exact purpose.

maybe we should consider moving the sitemap generator to spree core @damianlegawiec ?

**Comment by damianlegawiec** [comment]
This should be handled by sitemap extension not spree core

**Comment by NetViz** [comment]
Thank u both
