### ISSUE TITLE
Store credit not working on 4.1 with new UX

### ISSUE THREAD

**Issue by NetViz** [spree/spree#9871]
Store credit not working on 4.1 with new UX

**Comment by qoobaa** [comment]
I have the same issue with a custom "pay on delivery" option. I tried to debug it and the problem lies somewhere in `frontend/app/assets/javascripts/spree/frontend/checkout/payment.js` file - it hides too many nodes when switching payment methods.

**Comment by damianlegawiec** [comment]
This was fixed via https://github.com/spree/spree/pull/9883
