### ISSUE TITLE
active_storage_blobs' already exists error

### ISSUE THREAD

**Issue by ttakopia** [spree/spree#9872]
## Context

Hi there I tried to demo new version '~> 4.1.0.rc1' and ran into error when did bundle exec rails db:migrate after rails g spree:install --user_class=Spree::User

Please fix it.
## Expected Behavior

This is error message below
ArgumentError: Index name 'index_active_storage_blobs_on_key' on table 'active_storage_blobs' already exists

**Comment by Zeigren** [comment]
You shouldn't have to run `bundle exec rails db:migrate` as `rails g spree:install --user_class=Spree::User`  already runs migrations.

**Comment by damianlegawiec** [comment]
This isn't Spree related, closing
