### ISSUE TITLE
UX: Search gets stuck when navigating from top menu

### ISSUE THREAD

**Issue by kejiro** [spree/spree#9875]
While checking out the new UX on the demo site, I discovered a small issue with the search bar not being removed when navigating to another page from the top menu while the search bar is open.

## Expected Behavior
The search bar should disappear along with the modal screen.

## Actual Behavior
The modal screen disappear, but the search bar is still visible and stuck.

## Possible Fix
Put the modal in front of the top menu, or check if any link is triggered and remove the search.

## Steps to Reproduce
On the demo site (https://demo.spreecommerce.org)
Click on the search icon.
Navigate to another page from the top menu.

**Comment by NetViz** [comment]
Yes this need to be fixed

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/9862 & https://github.com/spree/spree/pull/9891
