### ISSUE TITLE
OG new features

### ISSUE THREAD

**Issue by NetViz** [spree/spree#9876]
I can see just OG image tag, adding below things would make a complete OG followed design.

og:title
og:type
og:url
og:description
og:image:secure_url
og:image:alt 
fb:app_id
fb:admin
og:price:currency
og:price:amount
og:site_name

![image](https://user-images.githubusercontent.com/60209134/73631200-5be85d80-467e-11ea-814d-b997a6efde26.png)

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/10524
