### ISSUE TITLE
API V2 Storefront Shipping Rates GET request crashes the server

### ISSUE THREAD

**Issue by bhtabor** [spree/spree#9901]
GET /checkout/shipping_rates crashes the server when checkout step has already advanced from Delivery step using the web. Server crashes and needs to be restarted

The endpoint should reply with the shipping rates response according to the guide, https://guides.spreecommerce.org/api/v2/storefront#operation/Shipping%20Rates

But, instead of responding, it just hangs and crashes the server.

You can reproduce on both Spree 3.7 and Spree 4 using the following steps:
1. Web: Add item to cart
2. Web: Checkout
3. Web: Fill in Address and advance to Delivery step
4. Web: Choose shipping rate and advance to Payment step
5. API: http://localhost:3000/api/v2/storefront/checkout/shipping_rates

**Comment by fauno** [comment]
just hit by this in 4.1.7, could it be backported? :(
