### ISSUE TITLE
Single Product Image Terrible Quality.

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9932]
If you only have a single image for a product, the image is really blurred.

**Comment by MatthewKennedy** [comment]
<img width="1249" alt="Screenshot 2020-02-17 at 13 37 25" src="https://user-images.githubusercontent.com/1240766/74658671-aa235380-518a-11ea-9436-68e13e9bc832.png">

**Comment by MatthewKennedy** [comment]
This might not be an issue really, as you can set image sizes on a per project basis in the code.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree/spree/pull/9959
