### ISSUE TITLE
Add More Detail Options in Stores

### ISSUE THREAD

**Issue by MatthewKennedy** [spree/spree#9949]
Would be nice to be able to add more unique information on a per store basis.

**Useful field Examples:**
- Full address (replace the static address that is hard coded into the footer).
- Dedicated field for customer facing contact email address (in case you want to use a separate send from such as a no-reply@you.com).
- upload store logo.
- upload store favicon image.

**Comment by nischay-dhiman** [comment]
@MatthewKennedy @damianlegawiec 
Are we referring to add more fields for this form, right?
[https://guides.spreecommerce.org/static/d4348df1efc418b58cb10300f3755b29/53641/new_store.jpg](url)

> Would be nice to be able to add more unique information on a per store basis.
> 
> **Useful field Examples:**
> 
> * Full address (replace the static address that is hard coded into the footer).
> * Dedicated field for customer facing contact email address (in case you want to use a separate send from such as a [no-reply@you.com](mailto:no-reply@you.com)).
> * upload store logo.
> * upload store favicon image.
