### ISSUE TITLE
Front end freezes after being in idle for sometimes

### ISSUE THREAD

**Issue by NetViz** [spree/spree#9989]
In chrome desktop browser Front end freezes after being in idle for sometimes if we have any uncompleted tasks on store tab we need to manually refresh the page to activate all buttons in the page, I am not sure how we can address this but famous websites like Amazon, Flipkart won't freeze frontend even after being in idle for n days/minutes.

**Comment by damianlegawiec** [comment]
Don't quite follow. Could you share some recordings? More detail?

**Comment by NetViz** [comment]
unable to reproduce
